SET QUERY_BAND = 'App_ID=APP07324;
     DAG_ID=re_zip_code_demographic_attributes_11521_ACE_ENG;
     Task_Name=re_zip_code_demographic_attributes_load;'
     FOR SESSION VOLATILE;

/*

Table: T2DL_DAS_REAL_ESTATE.re_zip_code_demographic_attributes_ldg
Owner: Rujira Achawanantakun
Modified: 2023-05-09
Note:
- This sql is used to read re_zip_code_demographic_attributes_ldg data from S3 and load it into
the staging table in tie 2 datalab.

*/

-- load data from s3 to a temp table
create or replace temporary view re_zip_code_demographic_attributes_ldg_csv USING CSV
OPTIONS (
    path "s3://analytics-insights-triggers/real_estate/RE_Zip_Code_Demographic_Attributes_latest.csv",
    sep ",",
    header "true"
)
;

-- load data from a temp view to a staging table
insert into table re_zip_code_demographic_attributes_ldg_temp
    select
    zip_code
    ,data_year
    ,land_area_square_miles
    ,total_population
    ,population_density
    ,total_population_5yr_proj
    ,average_age
    ,median_age
    ,age_0_to_4
    ,age_lt_1
    ,age_1
    ,age_2
    ,age_3
    ,age_4
    ,age_5
    ,age_5_to_9
    ,age_6
    ,age_7
    ,age_8
    ,age_9
    ,age_10
    ,age_10_to_14
    ,age_11
    ,age_12
    ,age_13
    ,age_14
    ,age_15
    ,age_15_to_17
    ,age_16
    ,age_17
    ,age_lt_18
    ,age_18
    ,age_18_to_19
    ,age_18_to_24
    ,age_18_plus
    ,age_19
    ,age_lt_20
    ,age_20
    ,age_21
    ,age_21_plus
    ,age_22_to_24
    ,age_25_to_29
    ,age_25_to_34
    ,age_30_to_34
    ,age_35_to_39
    ,age_35_to_44
    ,age_40_to_44
    ,age_45_to_49
    ,age_45_to_54
    ,age_50_to_54
    ,age_55_to_59
    ,age_55_to_64
    ,age_55_plus
    ,age_60_to_61
    ,age_62_to_64
    ,age_65
    ,age_65_to_74
    ,age_65_plus
    ,age_66
    ,age_67_to_69
    ,age_70_to_74
    ,age_75_to_79
    ,age_75_to_84
    ,age_80_to_84
    ,age_85_plus
    ,white
    ,black_or_african_american
    ,american_indian_alaska_native
    ,asian
    ,native_hawaiian_pacific_isld
    ,some_other_race
    ,two_or_more_races
    ,caucasian
    ,african_american
    ,asian_or_pacific_islander
    ,hispanic_latino
    ,other
    ,total_population_age_25_plus
    ,college_student_population
    ,no_schooling_completed
    ,nursery_to_4th_grade
    ,grade_5th_and_6th
    ,grade_7th_and_8th
    ,grade_9th
    ,grade_10th
    ,grade_11th
    ,grade_12th_or_no_diploma
    ,hs_grad_or_ged_or_alternative
    ,some_coll_or_less_than_1yr
    ,some_coll_1yr_or_more_no_degr
    ,associate_degree
    ,bachelors_degree
    ,masters_degree
    ,professional_school_degree
    ,doctorate_degree
    ,college_undergraduate
    ,graduate_or_prof_school
    ,less_than_high_school
    ,some_college
    ,college_degree
    ,adult_population
    ,potential_best_customers
    ,a01_american_royalty
    ,a02_platinum_prosperity
    ,a03_kids_and_cabernet
    ,a04_picture_perfect_families
    ,a05_couples_with_clout
    ,a06_jet_set_urbanites
    ,b07_across_the_ages
    ,b08_babies_and_bliss
    ,b09_family_fun_tastic
    ,b10_cosmopolitan_achievers
    ,c11_sophisticated_city_dweller
    ,c12_golf_carts_and_gourmets
    ,c13_philanthropicsophisticates
    ,c14_boomers_and_boomerangs
    ,d15_sports_utility_families
    ,d16_settled_in_suburbia
    ,d17_cul_de_sac_diversity
    ,d18_suburban_nightlife
    ,e19_consummate_consumers
    ,e20_no_place_like_home
    ,e21_unspoiled_splendor
    ,f22_fast_track_couples
    ,f23_families_matter_most
    ,g24_ambitious_singles
    ,g25_urban_edge
    ,h26_progressive_assortment
    ,h27_life_of_leisure
    ,h28_everyday_moderates
    ,h29_destination_recreation
    ,i30_potlucks_and_grt_outdoors
    ,i31_hard_working_values
    ,i32_steadfast_conventionalists
    ,i33_balance_and_harmony
    ,j34_suburban_sophisticates
    ,j35_rural_escape
    ,j36_settled_and_sensible
    ,k37_wired_for_success
    ,k38_modern_blend
    ,k39_metro_fusion
    ,k40_bohemian_groove
    ,l41_booming_and_consuming
    ,l42_rooted_flower_power
    ,l43_homemade_happiness
    ,m44_creative_comfort
    ,m45_growing_and_expanding
    ,n46_true_grit_americans
    ,n47_countrified_pragmatics
    ,n48_rural_southern_bliss
    ,n49_touch_of_tradition
    ,o50_full_steam_ahead
    ,o51_digitally_savvy
    ,o52_urban_ambition
    ,o53_colleges_and_cafes
    ,o54_influenced_by_influencers
    ,o55_family_troopers
    ,p56_mid_scale_medley
    ,p57_modest_metro_means
    ,p58_heritage_heights
    ,p59_expanding_horizons
    ,p60_striving_forward
    ,p61_simple_beginnings
    ,q62_enjoying_retirement
    ,q63_footloose_and_family_free
    ,q64_established_in_society
    ,q65_mature_and_wise
    ,r66_ambitious_dreamers
    ,r67_passionate_parents
    ,s68_small_town_sophisticates
    ,s69_urban_legacies
    ,s70_thrifty_singles
    ,s71_modest_retirees
    ,u99_unclassified
    ,rk_t5_mosaic_sgm_pop
    ,rk_t10_mosaic_sgm_pop
    ,rk_b10_mosaic_sgm_pop
    ,bargainista_t5_mosaic_sgm_pop
    ,bargainista_t10_mosaic_sgm_pop
    ,designer_mosaic_sgm_pop
    ,ns_t5_mosaic_sgm_pop
    ,ns_t10_mosaic_sgm_pop
    ,total_population_age_16_plus
    ,empld_mgmt_profess_occu
    ,empld_service_occu
    ,empld_sales_and_office_occu
    ,empld_farm_fish_forestry_occu
    ,empld_con_extra_maint_rep_occu
    ,empld_prd_tran_mat_moving_occu
    ,empld_blue_collar_occu
    ,empld_service_and_farming_occu
    ,empld_white_collar_occu
    ,empld_pop_age_16_plus
    ,professionals
    ,total_employees
    ,total_establishments
    ,total_households
    ,hhld_w_children_age_0_to_5
    ,hhld_w_children_age_6_to_17
    ,average_hhld_income
    ,median_hhld_income
    ,hhld_income_lt_10000
    ,hhld_income_10000_to_14999
    ,hhld_income_15000_to_19999
    ,hhld_income_20000_to_24999
    ,hhld_income_25000_to_29999
    ,hhld_income_30000_to_34999
    ,hhld_income_35000_to_39999
    ,hhld_income_40000_to_44999
    ,hhld_income_45000_to_49999
    ,hhld_income_50000_to_59999
    ,hhld_income_60000_to_74999
    ,hhld_income_75000_to_99999
    ,hhld_income_100000_to_124999
    ,hhld_income_125000_to_149999
    ,hhld_income_150000_to_199999
    ,hhld_income_200000_to_249999
    ,hhld_income_250000_to_499999
    ,hhld_income_lt_50000
    ,hhld_income_50000_to_74999
    ,hhld_income_75000_plus
    ,hhld_income_100000_plus
    ,hhld_income_150000_plus
    ,hhld_income_250000_plus
    ,hhld_income_500000_plus
    ,total_households_5yr_proj
    ,apparel_and_services_spend
    ,women_apparel_spend
    ,girl_apparel_spend
    ,men_apparel_spend
    ,boy_apparel_spend
    ,infant_apparel_spend
    ,footwear_spend
    ,women_footwear_spend
    ,girl_footwear_spend
    ,men_footwear_spend
    ,boy_footwear_spend
    ,accessories_spend
    ,women_accessories_spend
    ,girl_accessories_spend
    ,men_accessories_spend
    ,boy_accessories_spend
    ,infant_accessories_spend
    ,jewelry_spend
    ,watches_spend
    ,apparel_spend_per_hhld
    ,total_hotels
	from re_zip_code_demographic_attributes_ldg_csv
;
