DROP TABLE T2DL_DAS_OPEN_TO_BUY.APT_INACTIVE_CURRENT;

CREATE MULTISET TABLE T2DL_DAS_OPEN_TO_BUY.APT_INACTIVE_CURRENT,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      	SELLING_COUNTRY VARCHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC
		,SELLING_BRAND VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,CHANNEL VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,SUPPLIER_GROUP VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC 
		,CATEGORY VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC 
		,Division VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,Subdivision VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,Department VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,ACTIVE_DIVISION VARCHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC
		,ALT_INV_MODEL VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,MONTH_ID VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,MONTH_LABEL VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,HALF VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
		,QUARTER VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
		,FISCAL_YEAR_NUM VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
		,BUY_PLANNER VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
		,PREFERRED_PARTNER_DESC VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
		,AREAS_OF_RESPOSIBILITY VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
		,NPG_IND VARCHAR(5) CHARACTER SET UNICODE NOT CASESPECIFIC
		,DIVERSITY_GROUP VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
		,NORD_TO_RACK_TRANSFER_RATE VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
		,CATEGORY_PLANNER_1 VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,CATEGORY_PLANNER_2 VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC 
		,CATEGORY_GROUP VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,SEASONAL_DESIGNATION VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,RACK_MERCH_ZONE VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,IS_ACTIVEWEAR VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,CHANNEL_CATEGORY_ROLES_1 VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,CHANNEL_CATEGORY_ROLES_2 VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,BARGAINISTA_DEPT_MAP VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
		,INACTIVE_RCPTS_MTD_C DECIMAL(20,4)
		,INACTIVE_OO_C DECIMAL(20,4)
		,INACTIVE_CM_C DECIMAL(20,4)
		,PROCESS_DT VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC)
PRIMARY INDEX (Department,SELLING_BRAND, MONTH_ID, SUPPLIER_GROUP, CATEGORY );

GRANT SELECT ON T2DL_DAS_OPEN_TO_BUY.APT_INACTIVE_CURRENT TO PUBLIC ;