-- T2DL_DAS_OPEN_TO_BUY.PO_CANCELS_OTB_MONTH definition

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_OPEN_TO_BUY', 'PO_CANCELS_OTB_MONTH', OUT_RETURN_MSG);

CREATE SET TABLE T2DL_DAS_OPEN_TO_BUY.PO_CANCELS_OTB_MONTH ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      purchase_order_number VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      banner VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      div_idnt INTEGER,
      div_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      grp_idnt INTEGER,
      grp_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      dept_idnt INTEGER,
      dept_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Division VARCHAR(63) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Subdivision VARCHAR(63) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Department VARCHAR(63) CHARACTER SET UNICODE NOT CASESPECIFIC,
      vendor_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
      status VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      npg_ind CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      po_type VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      purchase_type VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      rp_ind VARCHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC,
      otb_month_idnt INTEGER,
      otb_month_label VARCHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC,
      comments VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC,
      internal_po_ind CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ttl_ordered_qty INTEGER,
      ttl_ordered_c FLOAT,
      buyer_cancel_u INTEGER,
      buyer_cancel_c DECIMAL(38,2),
      supplier_cancel_u INTEGER,
      supplier_cancel_c DECIMAL(38,2),
      other_cancel_u INTEGER,
      other_cancel_c DECIMAL(38,2),
      invalid_cancel_u INTEGER,
      invalid_cancel_c DECIMAL(38,2),
      true_supplier_cancel_u INTEGER,
      true_supplier_cancel_c DECIMAL(38,2),
      process_dt VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
      )
PRIMARY INDEX ( purchase_order_number );



-- T2DL_DAS_OPEN_TO_BUY.PO_CANCELS_ACTION_MONTH definition

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_OPEN_TO_BUY', 'PO_CANCELS_ACTION_MONTH', OUT_RETURN_MSG);

CREATE SET TABLE T2DL_DAS_OPEN_TO_BUY.PO_CANCELS_ACTION_MONTH ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      banner VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      purchase_order_number VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      div_idnt INTEGER,
      div_desc VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      grp_idnt INTEGER,
      grp_desc VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      dept_idnt INTEGER,
      dept_desc VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Division VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Subdivision VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Department VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      vendor_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
      npg_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      rp_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      po_type VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      purchase_type VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      comments VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC,
      internal_po_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      otb_month_idnt INTEGER,
      otb_month_label VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      month_idnt INTEGER,
      action_month_label VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      supplier_cancel_u INTEGER,
      supplier_cancel_c DECIMAL(38,2),
      buyer_cancel_u INTEGER,
      buyer_cancel_c DECIMAL(38,2),
      other_cancel_u INTEGER,
      other_cancel_c DECIMAL(38,2),
      invalid_cancel_u INTEGER,
      invalid_cancel_c DECIMAL(38,2),
      true_supplier_cancel_u INTEGER,
      true_supplier_cancel_c DECIMAL(38,2),
      process_dt VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
      )
PRIMARY INDEX ( purchase_order_number );

GRANT SELECT ON T2DL_DAS_OPEN_TO_BUY.PO_CANCELS_OTB_MONTH TO PUBLIC;
GRANT SELECT ON T2DL_DAS_OPEN_TO_BUY.PO_CANCELS_ACTION_MONTH TO PUBLIC;