DROP TABLE T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT;

CREATE MULTISET TABLE T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      Division VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Subdivision VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Department VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Banner VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Country VARCHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC,
      MONTH_IDNT VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Month" VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      Quarter VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Year" VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      "Active vs Inactive" CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      CP_RCPTS_RESERVE_C DECIMAL(20,4),
      CP_RCPTS_ACTIVE_C DECIMAL(20,4),
      "Cp Rcpts Less Reserve C" DECIMAL(20,4),
      "Ty NPR RP MTD Rcpts C" DECIMAL(20,4),
      "Ty NPR RP OO Rcpts C" DECIMAL(20,4),
      "Ty NRP Rcpts MTD OO CM C" DECIMAL(20,4),
      "Ty NRP Rcpts MTD C" DECIMAL(20,4),
      "Ty NRP OO C" DECIMAL(20,4),
      "Ty NRP CM C" DECIMAL(20,4),
      "NRP CM C" DECIMAL(20,4),
      "RP CM C" DECIMAL(20,4),
      "Ty RP Anticipated Spend C" DECIMAL(20,4),
      "Ty RP Rcpts MTD OO C" DECIMAL(20,4),
      "Ty RP Rcpts MTD C" DECIMAL(20,4),
      "Ty RP OO C" DECIMAL(20,4),
      "Inactive Cp Rcpts C" DECIMAL(20,4),
      "Inactive Ty MTD OO CM Rcpts C" DECIMAL(20,4),
      "Inactive Ty MTD C" DECIMAL(20,4),
      "Inactive Ty OO C" DECIMAL(20,4),
      "Inactive Ty CM C" DECIMAL(20,4),
      PROCESS_DT VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC)
PRIMARY INDEX (Department,Banner, "Month" );

GRANT SELECT ON T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT TO PUBLIC ;