CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_OPEN_TO_BUY', 'PO_OTB_DETAIL', OUT_RETURN_MSG);

CREATE MULTISET TABLE T2DL_DAS_OPEN_TO_BUY.PO_OTB_DETAIL
	,FALLBACK
	,NO BEFORE JOURNAL
	,NO AFTER JOURNAL
	,CHECKSUM = DEFAULT
	,DEFAULT MERGEBLOCKRATIO
	,MAP = TD_MAP1 (
	purchase_order_num VARCHAR(16) CHARACTER SET UNICODE NOT CASESPECIFIC
	,channel_num INTEGER
	,channel_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,channel_brand VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC
	,division_num INTEGER
	,division_name VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
	,subdivision_num INTEGER
	,subdivision_name VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
	,dept_num INTEGER
	,dept_name VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
	,class_num INTEGER
	,class_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,sbclass_num INTEGER
	,sbclass_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,manufacturer_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,vpn VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
	,style_desc VARCHAR(800) CHARACTER SET UNICODE NOT CASESPECIFIC
	,color_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_color VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
	,customer_choice VARCHAR(64) CHARACTER SET UNICODE NOT CASESPECIFIC
	,epm_choice_num BIGINT
	,STATUS VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,edi_ind CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,start_ship_date DATE FORMAT 'YY/MM/DD'
	,end_ship_date DATE FORMAT 'YY/MM/DD'
	,latest_approval_date DATE FORMAT 'YY/MM/DD'
	,last_carrier_asn_date DATE FORMAT 'YY/MM/DD'
	,last_supplier_asn_date DATE FORMAT 'YY/MM/DD'
	,last_ship_activity_date DATE FORMAT 'YY/MM/DD'
	,last_outbound_activity_date DATE FORMAT 'YY/MM/DD'
	,receipt_date DATE FORMAT 'YY/MM/DD'
	,otb_eow_date DATE FORMAT 'YY/MM/DD'
	,otb_month VARCHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC
	,otb_month_idnt INTEGER
	,order_type CHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC
	,internal_po_ind CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,npg_ind CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,po_type VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,purchase_type VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,"Month" VARCHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC
	,month_idnt INTEGER
	,week_idnt INTEGER
	,fiscal_year_num INTEGER
	,quarter_label VARCHAR(7) CHARACTER SET LATIN NOT CASESPECIFIC
	,RCPT_COST DECIMAL(38, 4)
	,RCPT_RETAIL DECIMAL(38, 4)
	,RCPT_UNITS DECIMAL(38, 4)
	,QUANTITY_ORDERED DECIMAL(38, 4)
	,QUANTITY_RECEIVED DECIMAL(38, 4)
	,QUANTITY_CANCELED DECIMAL(38, 4)
	,QUANTITY_OPEN DECIMAL(38, 4)
	,UNIT_COST_AMT DECIMAL(38, 4)
	,TOTAL_ESTIMATED_LANDING_COST DECIMAL(38, 4)
	,TOTAL_ANTICIPATED_RETAIL_AMT DECIMAL(38, 4)
	,ttl_approved_qty INTEGER
	,ttl_approved_c DECIMAL(38, 4)
	,ttl_approved_r DECIMAL(38, 4)
	,vasn_sku_qty INTEGER
	,vasn_cost DECIMAL(38, 4)
	,dc_received_qty INTEGER
	,dc_received_c DECIMAL(38, 4)
	,process_dt DATE FORMAT 'YY/MM/DD')
PRIMARY INDEX (customer_choice);