--Developed by:Isaac Wallick 12/1/2022 This cript imports the ab cm data that is used in otb reporting

---Create stg table for CM_OTB_DETAIL.CSV file
CREATE MULTISET TABLE t2dl_das_open_to_buy.AB_CM_ORDERS_STG 
	,FALLBACK
	,NO BEFORE JOURNAL
	,NO AFTER JOURNAL
	,CHECKSUM = DEFAULT
	,DEFAULT MERGEBLOCKRATIO
	,MAP = TD_MAP1 (
	channel VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,nrf_color_code VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,style_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,style_group_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,class_name VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,subclass_name VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,npg_ind VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,dept_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,plan_season_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,plan_key VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_name VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,fiscal_month_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,otb_eow_date VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,org_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,vpn VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,vpn_desc VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,class_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,subclass_id VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_color VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
	,import_country_code VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,banner VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,plan_type VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,po_key VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,rcpt_units VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,unit_cost_us VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,unit_cost_ca VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,spcl_unit_cost_us VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,spcl_unit_cost_ca VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,ttl_cost_us VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,ttl_cost_ca VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,unit_rtl_us VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,unit_rtl_ca VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,spcl_unit_rtl_us VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,spcl_unit_rtl_ca VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,rcpt_rtl_type VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,ttl_rtl_us VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,ttl_rtl_ca VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,plan_commit_ind VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,cm_dollars VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,po_number VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,plan_season_desc VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	,last_committed_otb_eow_date VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
	) 
	PRIMARY INDEX (style_id,nrf_color_code);

--load file to stg table using tpt process
CALL SYS_MGMT.S3_TPT_LOAD ('t2dl_das_open_to_buy','AB_CM_ORDERS_STG','us-east-1','cm-dollars','extract/','CM_OTB_DETAIL.CSV','7C',OUT_MESSAGE);

COLLECT STATS
	PRIMARY INDEX(style_id ,nrf_color_code)
	,COLUMN(style_id )
	,COLUMN(nrf_color_code)
		ON t2dl_das_open_to_buy.AB_CM_ORDERS_STG;
