--This script builds out the dataset for OTB Cost Reporting
--Data is at Banner/Dept/Month and is for current a future
--Author:  Isaac Wallick
--Date Created:8/30/2022
--Last Edited:3/13/2024


--lets create a store mapping for country and banner we only need open stores for everything but OO
CREATE MULTISET VOLATILE TABLE otb_loc_base AS(
	SELECT
	a.STORE_NUM
	,a.CHANNEL_NUM
	,a.CHANNEL_DESC
	,a.CHANNEL_BRAND
	,a.CHANNEL_COUNTRY
	,a.CHANNEL_NUM||','||a.CHANNEL_DESC as CHANNEL
	,CASE
		WHEN a.CHANNEL_BRAND = 'Nordstrom' AND a.CHANNEL_COUNTRY = 'US' THEN 'US Nordstrom'
		WHEN a.CHANNEL_BRAND = 'Nordstrom' AND a.CHANNEL_COUNTRY = 'CA' THEN 'CA Nordstrom'
		WHEN a.CHANNEL_BRAND = 'Nordstrom_Rack' AND a.CHANNEL_COUNTRY = 'US' THEN 'US Rack'
		WHEN a.CHANNEL_BRAND = 'Nordstrom_Rack' AND a.CHANNEL_COUNTRY = 'CA' THEN 'CA Rack'
	END AS BANNER
	FROM (
		SELECT
			STORE_NUM
			,CHANNEL_NUM
			,CHANNEL_DESC
			,CHANNEL_BRAND
			,CHANNEL_COUNTRY
		FROM PRD_NAP_USR_VWS.PRICE_STORE_DIM_VW
		GROUP BY 1,2,3,4,5
		WHERE CHANNEL_BRAND in ('Nordstrom','Nordstrom_Rack')
		AND CHANNEL_NUM IN ('110', '120', '140', '210', '220', '240', '250', '260', '310', '930', '940', '990', '111', '121', '211', '221', '261', '311')
		AND store_name NOT like 'CLSD%' -- can be found as CLSD or CLOSED
  		AND store_name NOT like 'CLOSED%')a
GROUP BY 1,2,3,4,5,6)

WITH DATA
   PRIMARY INDEX(STORE_NUM)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (STORE_NUM)
     ,COLUMN(STORE_NUM)
     ON otb_loc_base;
    
    
--lets create a store mapping for country and banner we include closed stores because some may have OO
CREATE MULTISET VOLATILE TABLE otb_loc_oo AS(
	SELECT
	a.STORE_NUM
	,a.CHANNEL_NUM
	,a.CHANNEL_DESC
	,a.CHANNEL_BRAND
	,a.CHANNEL_COUNTRY
	,a.CHANNEL_NUM||','||a.CHANNEL_DESC as CHANNEL
	,CASE
		WHEN a.CHANNEL_BRAND = 'Nordstrom' AND a.CHANNEL_COUNTRY = 'US' THEN 'US Nordstrom'
		WHEN a.CHANNEL_BRAND = 'Nordstrom' AND a.CHANNEL_COUNTRY = 'CA' THEN 'CA Nordstrom'
		WHEN a.CHANNEL_BRAND = 'Nordstrom_Rack' AND a.CHANNEL_COUNTRY = 'US' THEN 'US Rack'
		WHEN a.CHANNEL_BRAND = 'Nordstrom_Rack' AND a.CHANNEL_COUNTRY = 'CA' THEN 'CA Rack'
	END AS BANNER
	FROM (
		SELECT
			STORE_NUM
			,CHANNEL_NUM
			,CHANNEL_DESC
			,CHANNEL_BRAND
			,CHANNEL_COUNTRY
		FROM PRD_NAP_USR_VWS.PRICE_STORE_DIM_VW
		GROUP BY 1,2,3,4,5
		WHERE CHANNEL_BRAND in ('Nordstrom','Nordstrom_Rack')
		AND CHANNEL_NUM IN ('110', '120', '140', '210', '220', '240', '250', '260', '310', '930', '940', '990', '111', '121', '211', '221', '261', '311')
		)a
GROUP BY 1,2,3,4,5,6)

WITH DATA
   PRIMARY INDEX(STORE_NUM)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (STORE_NUM)
     ,COLUMN(STORE_NUM)
     ON otb_loc_oo;
    

--drop table otb_date
--this gets us all the elapsed weeks in a current month plus all future weeks
CREATE MULTISET VOLATILE TABLE otb_date AS(
SELECT 
	WEEK_IDNT
	,MONTH_IDNT
	,MONTH_LABEL
	,QUARTER_IDNT 
	,QUARTER_LABEL 
	,'FY'||substr(cast(fiscal_year_num as varchar(5)),3,2)||' '||quarter_abrv as QUARTER
	,FISCAL_YEAR_NUM 
	,CASE WHEN CURRENT_DATE BETWEEN month_start_day_date and month_end_day_date THEN 1 ELSE 0 END as curr_month_flag
FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM  
WHERE curr_month_flag =1 OR day_date >= current_date
group by 1,2,3,4,5,6,7,8)

WITH DATA
   PRIMARY INDEX(WEEK_IDNT)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (WEEK_IDNT)
     ,COLUMN(WEEK_IDNT)
     ,COLUMN(MONTH_IDNT)
     ,COLUMN(QUARTER_IDNT)
     ,COLUMN(FISCAL_YEAR_NUM)
     ON otb_date;
    
--this gets us all elapsed weeks plus current week in the current month used for mtd rcpts
CREATE MULTISET VOLATILE TABLE otb_mtd AS(
SELECT
	b.WEEK_IDNT
	,a.MONTH_IDNT
	,b.MONTH_LABEL
	,b.month_454_label
	,b.fiscal_year_num||''||b.fiscal_month_num||' '||b.month_abrv as MONTH_ID 
	,b.QUARTER_IDNT 
	,b.QUARTER_LABEL 
	,'FY'||substr(cast(b.fiscal_year_num as varchar(5)),3,2)||' '||b.quarter_abrv as QUARTER
	,b.HALF_LABEL
	,b.FISCAL_YEAR_NUM
FROM
	(SELECT 
	MAX(month_idnt) month_idnt
	FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM
	WHERE week_start_day_date <= CURRENT_DATE) a
JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b
ON a.MONTH_IDNT = b.month_idnt
WHERE week_start_day_date <= CURRENT_DATE
GROUP BY 1,2,3,4,5,6,7,8,9,10)

WITH DATA
   PRIMARY INDEX(WEEK_IDNT)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (WEEK_IDNT)
     ,COLUMN(WEEK_IDNT)
     ,COLUMN(MONTH_IDNT)
     ON otb_mtd;
   
--drop table otb_wtd_rcpts
--this gets us the rcpts for the current week
CREATE MULTISET VOLATILE TABLE otb_current_wtd_rcpts AS(
SELECT
	c.DEPT_ID
	,c.BANNER
	,c.COUNTRY
	,c.MONTH_IDNT
	,c.MONTH_LABEL
	,c.QUARTER 
	,c.FISCAL_YEAR_NUM 
	,SUM(c.RP_RCPTS_ACTIVE_WTD_C) AS TY_RCPTS_RP_ACTIVE_WTD_C
	,SUM(c.NON_RP_RCPTS_ACTIVE_WTD_C) AS TY_RCPTS_NRP_ACTIVE_WTD_C
	,SUM(c.RCPTS_INACTIVE_WTD_C) AS TY_RCPTS_INACTIVE_WTD_C
FROM(
	SELECT
		a.WEEK_ID
		,b.MONTH_IDNT
		,b.MONTH_LABEL
		,b.QUARTER
		,b.FISCAL_YEAR_NUM 
		,a.DEPARTMENT_ID as DEPT_ID
		,a.RP_RCPTS_ACTIVE_WTD_C
		,a.NON_RP_RCPTS_ACTIVE_WTD_C
		,a.RCPTS_INACTIVE_WTD_C
		,CASE
			WHEN a.BANNER_ID = '1' THEN 'US NORDSTROM'
			WHEN a.BANNER_ID = '2' THEN 'CA NORDSTROM'
			WHEN a.BANNER_ID = '3' THEN 'US RACK'
			WHEN a.BANNER_ID = '4' THEN 'CA RACK'
		  ELSE 0
		  END AS BANNER
		,CASE
			 WHEN a.BANNER_ID in ('1','3') THEN 'US'
			 WHEN a.BANNER_ID in ('2','4') THEN 'CA'
		 ELSE 0
		 END AS COUNTRY
	FROM PRD_NAP_VWS.MERCH_MFP_COST_PORECEIPTS_WTD_VW a
	JOIN otb_date b
	ON a.WEEK_ID =b.week_idnt
	WHERE FULFILMENT_ID = '3'
	--	and a.DEPARTMENT_ID = '881'
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11)c
GROUP BY 1,2,3,4,5,6,7)
WITH DATA
   PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_current_wtd_rcpts;
    
--drop table otb_mtd_rcpts    
--  this gets us the rcpts for the elapsed weeks in the current month
CREATE MULTISET VOLATILE TABLE otb_mtd_rcpts AS(
 SELECT
	c.DEPT_ID
	,c.BANNER
	,c.COUNTRY
	,c.MONTH_IDNT
	,c.MONTH_LABEL
	,c.QUARTER 
	,c.FISCAL_YEAR_NUM 
	,SUM(c.TY_RP_RECEIPTS_ACTIVE_COST_AMT) AS TY_RCPTS_RP_ACTIVE_WTD_C
	,SUM(c.TY_NON_RP_RECEIPTS_ACTIVE_COST_AMT) AS TY_RCPTS_NRP_ACTIVE_WTD_C
	,SUM(c.TY_RECEIPTS_INACTIVE_COST_AMT) AS TY_RCPTS_INACTIVE_WTD_C
FROM(   
    SELECT
		a.WEEK_NUM 
		,b.MONTH_IDNT
		,b.MONTH_LABEL
		,b.QUARTER
		,b.FISCAL_YEAR_NUM 
		,a.DEPT_NUM  as DEPT_ID
		,a.TY_RP_RECEIPTS_ACTIVE_COST_AMT
		,a.TY_NON_RP_RECEIPTS_ACTIVE_COST_AMT
		,a.TY_RECEIPTS_INACTIVE_COST_AMT
		,CASE
			WHEN a.BANNER_COUNTRY_NUM = '1' THEN 'US NORDSTROM'
			WHEN a.BANNER_COUNTRY_NUM = '2' THEN 'CA NORDSTROM'
			WHEN a.BANNER_COUNTRY_NUM = '3' THEN 'US RACK'
			WHEN a.BANNER_COUNTRY_NUM = '4' THEN 'CA RACK'
		  ELSE 0
		  END AS BANNER
		,CASE
			 WHEN a.BANNER_COUNTRY_NUM in ('1','3') THEN 'US'
			 WHEN a.BANNER_COUNTRY_NUM in ('2','4') THEN 'CA'
		 ELSE 0
		 END AS COUNTRY
	FROM PRD_NAP_USR_VWS.MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT a
	JOIN otb_mtd b
	ON a.WEEK_NUM=b.week_idnt
	WHERE FULFILL_TYPE_NUM = '3'
	--AND a.WEEK_NUM = '202251'
	--	and a.DEPARTMENT_ID = '881'
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11)c
GROUP BY 1,2,3,4,5,6,7   
)
WITH DATA
   PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_mtd_rcpts; 

--drop table otb_wtd_rcpts
--this brings current and elapsed weeks together to get MTD rcpts
CREATE MULTISET VOLATILE TABLE otb_wtd_rcpts AS(
SELECT
a.DEPT_ID
,a.BANNER
,a.COUNTRY
,a.MONTH_IDNT
,a.MONTH_LABEL
,a.QUARTER 
,a.FISCAL_YEAR_NUM 
,sum(a.TY_RCPTS_RP_ACTIVE_WTD_C) as TY_RCPTS_RP_ACTIVE_WTD_C
,sum(a.TY_RCPTS_NRP_ACTIVE_WTD_C) as TY_RCPTS_NRP_ACTIVE_WTD_C
,sum(a.TY_RCPTS_INACTIVE_WTD_C) as TY_RCPTS_INACTIVE_WTD_C 
FROM(
	SELECT
	DEPT_ID
	,BANNER
	,COUNTRY
	,MONTH_IDNT
	,MONTH_LABEL
	,QUARTER 
	,FISCAL_YEAR_NUM 
	,TY_RCPTS_RP_ACTIVE_WTD_C
	,TY_RCPTS_NRP_ACTIVE_WTD_C
	,TY_RCPTS_INACTIVE_WTD_C
	FROM otb_current_wtd_rcpts
	
	UNION ALL
	
	SELECT 
	DEPT_ID
	,BANNER
	,COUNTRY
	,MONTH_IDNT
	,MONTH_LABEL
	,QUARTER 
	,FISCAL_YEAR_NUM 
	,TY_RCPTS_RP_ACTIVE_WTD_C
	,TY_RCPTS_NRP_ACTIVE_WTD_C
	,TY_RCPTS_INACTIVE_WTD_C
	FROM otb_mtd_rcpts) a
group by 1,2,3,4,5,6,7)

WITH DATA
   PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_wtd_rcpts; 
 
--lets bring in plan and actualized data looking at elapsed/current week in current month and future weeks
CREATE MULTISET VOLATILE TABLE otb_ty AS(
SELECT
	c.DEPT_ID
	,c.BANNER
	,c.COUNTRY
	,c.MONTH_IDNT
	,c.MONTH_LABEL
	,c.QUARTER 
	,c.FISCAL_YEAR_NUM 
	,SUM(c.CP_RECEIPTS_RESERVE_COST_AMT) AS CP_RCPTS_RESERVE_C
	,SUM(c.CP_RECEIPTS_ACTIVE_COST_AMT) AS CP_RCPTS_ACTIVE_C
	,SUM(c.CP_RECEIPTS_INACTIVE_COST_AMT) AS CP_RCPTS_INACTIVE_C
FROM(
	SELECT
		a.DEPT_NUM as DEPT_ID
		,a.WEEK_NUM as WEEK_ID
		,b.MONTH_IDNT
		,b.MONTH_LABEL
		,b.QUARTER 
		,b.FISCAL_YEAR_NUM  
		,CASE
			WHEN a.BANNER_COUNTRY_NUM  = '1' THEN 'US Nordstrom'
			WHEN a.BANNER_COUNTRY_NUM = '2' THEN 'CA Nordstrom'
			WHEN a.BANNER_COUNTRY_NUM = '3' THEN 'US Rack'
			WHEN a.BANNER_COUNTRY_NUM = '4' THEN 'CA Rack'
	     ELSE 0
	     END AS BANNER
		,CASE
			 WHEN a.BANNER_COUNTRY_NUM in ('1','3') THEN 'US'
			 WHEN a.BANNER_COUNTRY_NUM in ('2','4') THEN 'CA'
		 ELSE 0
		END AS COUNTRY
		,a.CP_RECEIPTS_RESERVE_COST_AMT
		,a.CP_RECEIPTS_ACTIVE_COST_AMT
		,a.CP_RECEIPTS_INACTIVE_COST_AMT
	FROM PRD_NAP_USR_VWS.MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT a
	JOIN otb_date b
	ON a.WEEK_NUM = b.week_idnt
	WHERE a.FULFILL_TYPE_NUM  = '3'
	--AND a.DEPT_NUM ='3'
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11)c
GROUP BY 1,2,3,4,5,6,7
)
WITH DATA
   PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_ty;

--DROP table otb_rp;
-- lets bring in rp anticipated spend
CREATE MULTISET VOLATILE TABLE otb_rp AS(
SELECT
	c.DEPT_ID
	,c.MONTH_IDNT
	,c.MONTH_LABEL
	,c.QUARTER 
	,c.FISCAL_YEAR_NUM
	,c.BANNER
	,c.COUNTRY
	,SUM(c.RP_ANTSPND_C) AS TY_RP_ANTICIPATED_SPEND_C
	,SUM(c.RP_ANTSPND_U) AS TY_RP_ANTICIPATED_SPEND_U
FROM(
	select
		a.WEEK_IDNT AS WEEK_ID
		,b.MONTH_IDNT
		,b.MONTH_LABEL
		,b.QUARTER 
		,b.FISCAL_YEAR_NUM
		,a.DEPT_IDNT AS DEPT_ID
		,CASE
				WHEN a.BANNER_ID  = '1' THEN 'US Nordstrom'
				WHEN a.BANNER_ID = '2' THEN 'CA Nordstrom'
				WHEN a.BANNER_ID = '3' THEN 'US Rack'
				WHEN a.BANNER_ID = '4' THEN 'CA Rack'
	     ELSE 0
	     END AS BANNER
		,CASE
			 WHEN a.BANNER_ID in ('1','3') THEN 'US'
			 WHEN a.BANNER_ID in ('2','4') THEN 'CA'
		 ELSE 0
		 END AS COUNTRY
		,CATEGORY
		,SUPP_IDNT
		,RP_ANTSPND_U
		,RP_ANTSPND_C
	FROM t2dl_das_open_to_buy.rp_anticipated_spend_current a
	JOIN otb_date b
	ON a.WEEK_IDNT = b.WEEK_IDNT
	WHERE ft_id = '3'
	--and a.dept_idnt in ('812')
	--and month_label = '2023 JAN'
	--GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
	)c
GROUP BY 1,2,3,4,5,6,7
)

WITH DATA
   PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_rp;

--Lets bring in the CM data
CREATE MULTISET VOLATILE TABLE otb_cm AS(
SELECT
	d.DEPT_ID
	,d.BANNER
	,d.CHANNEL_COUNTRY as COUNTRY
	,d.MONTH_IDNT
	,d.MONTH_LABEL
	,d.QUARTER 
	,d.FISCAL_YEAR_NUM
	,SUM(CASE 
		WHEN d.PLAN_TYPE in ('RKPACKHOLD') AND d.BANNER in ('US NORDSTROM','US RACK') THEN d.TTL_COST_US
		WHEN d.PLAN_TYPE in ('RKPACKHOLD') AND d.BANNER in ('CA NORDSTROM','CA RACK') THEN d.TTL_COST_CA  
		ELSE 0 END) AS TY_INACTIVE_CM_C
	,SUM(CASE 
		WHEN d.PLAN_TYPE in ('BACKUP','FASHION','NRPREORDER','REPLNSHMNT') AND d.BANNER in ('US NORDSTROM','US RACK') THEN d.TTL_COST_US
		WHEN d.PLAN_TYPE in ('BACKUP','FASHION','NRPREORDER','REPLNSHMNT') AND d.BANNER in ('CA NORDSTROM','CA RACK') THEN d.TTL_COST_CA  
		ELSE 0 END) AS TY_ACTIVE_CM_C
	,SUM(CASE 
			WHEN d.PLAN_TYPE in ('BACKUP','FASHION','NRPREORDER') AND d.BANNER in ('US NORDSTROM','US RACK') THEN d.TTL_COST_US
			WHEN d.PLAN_TYPE in ('BACKUP','FASHION','NRPREORDER') AND d.BANNER in ('CA NORDSTROM','CA RACK') THEN d.TTL_COST_CA  
			ELSE 0 END) AS NRP_CM_C
	,SUM(CASE 
			WHEN d.PLAN_TYPE in ('REPLNSHMNT') AND d.BANNER in ('US NORDSTROM','US RACK') THEN d.TTL_COST_US
			WHEN d.PLAN_TYPE in ('REPLNSHMNT') AND d.BANNER in ('CA NORDSTROM','CA RACK') THEN d.TTL_COST_CA  
			ELSE 0 END) AS RP_CM_C
	--,SUM(CASE WHEN d.PLAN_TYPE in ('RKPACKHOLD') THEN d.CM_DOLLARS ELSE 0 END) AS TY_INACTIVE_CM_C
	--,SUM(CASE WHEN d.PLAN_TYPE not in ('RKPACKHOLD') THEN d.CM_DOLLARS ELSE 0 END) AS TY_ACTIVE_CM_C
FROM(
	SELECT
		a.DEPT_ID
		,a.STYLE_ID
		,a.STYLE_GROUP_ID
		,a.CLASS_NAME
		,a.SUBCLASS_NAME
		,b.BANNER
		,b.CHANNEL_COUNTRY
		,a.SUPP_ID
		,a.FISCAL_MONTH_ID
		,a.OTB_EOW_DATE
		,a.VPN
		,a.NRF_COLOR_CODE
		,a.SUPP_COLOR
		,a.PLAN_TYPE
		,a.TTL_COST_US
		,a.TTL_COST_CA
		,a.CM_DOLLARS
		--,c.week_idnt
		,c.MONTH_IDNT
		,c.MONTH_LABEL
		,c.QUARTER 
		,c.FISCAL_YEAR_NUM
		,a.PO_KEY
		,a.PLAN_KEY
	FROM t2dl_das_open_to_buy.AB_CM_ORDERS_CURRENT a
	JOIN otb_loc_base b
	ON a.ORG_ID = b.CHANNEL_NUM
	JOIN otb_date c
	on a.FISCAL_MONTH_ID = c.MONTH_IDNT
	--where a.dept_id in('800','801','802','803','804','805','806','807','809','890','892')
	--and a.fiscal_month_id = '202301'
	--and b.Banner = 'US RACK'
	group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
	) d
GROUP BY 1,2,3,4,5,6,7)

WITH DATA
   PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
   ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (DEPT_ID,BANNER,COUNTRY,month_label)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_cm;
 

--lets get the most current OO info AND CHANNEL INFO
--PRD_NAP_USR_VWS.MERCH_ON_ORDER_FACT_VW has the most current OO data and is a truncate and load daily
--drop table otb_oo_base
CREATE MULTISET VOLATILE TABLE otb_oo_base AS(
SELECT 
	c.PURCHASE_ORDER_NUMBER
	,c.RMS_SKU_NUM
	,c.RMS_CASEPACK_NUM
	,c.CHANNEL_NUM
	,c.CHANNEL_DESC
	,c.CHANNEL_COUNTRY
	,c.BANNER
	,c.STORE_NUM
	,CASE WHEN c.WEEK_NUM < c.CURR_WK_IDNT THEN c.CURR_WK_IDNT ELSE c.WEEK_NUM END AS WEEK_NUM
	,c.ORDER_TYPE
	,c.LATEST_APPROVAL_DATE
	,c.QUANTITY_OPEN
	,c.TOTAL_ESTIMATED_LANDING_COST
FROM(
	SELECT 
		a.PURCHASE_ORDER_NUMBER 
		,a.RMS_SKU_NUM
		,a.RMS_CASEPACK_NUM
		,b.CHANNEL_NUM
		,b.CHANNEL_DESC
		,b.CHANNEL_COUNTRY
		,b.BANNER
		,a.STORE_NUM
		,a.WEEK_NUM
		,(Select WEEK_IDNT from PRD_NAP_USR_VWS.DAY_CAL_454_DIM where DAY_DATE=CURRENT_DATE) as CURR_WK_IDNT
		,a.ORDER_TYPE
		,a.LATEST_APPROVAL_DATE
		,a.QUANTITY_OPEN
		,a.TOTAL_ESTIMATED_LANDING_COST
	FROM PRD_NAP_USR_VWS.MERCH_ON_ORDER_FACT_VW a
	JOIN otb_loc_oo b
	ON a.STORE_NUM = b.STORE_NUM
	WHERE  a.QUANTITY_OPEN > 0
	   AND a.FIRST_APPROVAL_DATE IS NOT NULL
	   AND ((a.STATUS = 'CLOSED' AND a.END_SHIP_DATE >= CURRENT_DATE - 45) OR a.STATUS IN ('APPROVED','WORKSHEET') )
	   --AND  RMS_SKU_NUM = '5747222' 
	   --and PURCHASE_ORDER_NUMBER = '39693651'
	   )c
	   )
WITH DATA
PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM)
     ,COLUMN(RMS_SKU_NUM)
     ,COLUMN(STORE_NUM)
     ON otb_oo_base;


 
--drop table otb_oo_hierarchy
--Lets gets associated hierarchy to skus
CREATE MULTISET VOLATILE TABLE otb_oo_hierarchy AS(
SELECT
	b.RMS_SKU_NUM
	,b.channel_country
	,a.DEPT_NUM
	,a.DEPT_DESC
FROM PRD_NAP_USR_VWS.PRODUCT_SKU_DIM_VW a
JOIN (SELECT DISTINCT RMS_SKU_NUM,channel_country FROM otb_oo_base) b
ON a.RMS_SKU_NUM = b.RMS_SKU_NUM
AND a.channel_country = b.channel_country
GROUP BY 1,2,3,4)
  WITH DATA
  PRIMARY INDEX(RMS_SKU_NUM)
  ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX (RMS_SKU_NUM)
     ,COLUMN(RMS_SKU_NUM)
     ON otb_oo_hierarchy;
    

--drop table otb_oo_final
--lets add back in the hierarchy to the base data and sum up inactive/active rcpts as well as rp nrp
--Inactive channels 930,220 and 221
CREATE MULTISET VOLATILE TABLE otb_oo_final AS(
SELECT 
	e.DEPT_NUM
	,e.BANNER
	,e.CHANNEL_COUNTRY as COUNTRY
	,e.MONTH_IDNT
	,e.MONTH_LABEL
	,e.QUARTER
	,e.FISCAL_YEAR_NUM
	,SUM(CASE WHEN e.CHANNEL_NUM IN ('930','220','221') THEN e.TOTAL_ESTIMATED_LANDING_COST
	     ELSE 0 END) AS TY_RCPTS_OO_INACTIVE_C
	,SUM(CASE WHEN e.CHANNEL_NUM NOT IN ('930','220','221') AND e.ORDER_TYPE IN('AUTOMATIC_REORDER','BUYER_REORDER') THEN e.TOTAL_ESTIMATED_LANDING_COST
	     ELSE 0 END) AS TY_RCPTS_OO_ACTIVE_RP_C
	,SUM(CASE WHEN e.CHANNEL_NUM NOT IN ('930','220','221') AND e.ORDER_TYPE NOT IN('AUTOMATIC_REORDER','BUYER_REORDER') THEN e.TOTAL_ESTIMATED_LANDING_COST
	     ELSE 0 END) AS TY_RCPTS_OO_ACTIVE_NRP_C
	--,SUM(CASE WHEN e.CHANNEL_NUM IN ('930','220','221') THEN e.QUANTITY_OPEN
	   --  ELSE 0 END) AS TY_RCPTS_INACTIVE_OO
	--,SUM(CASE WHEN e.CHANNEL_NUM NOT IN ('930','220','221') AND e.ORDER_TYPE IN('AUTOMATIC_REORDER','BUYER_REORDER') THEN e.QUANTITY_OPEN
	  --   ELSE 0 END) AS TY_RCPTS_ACTIVE_RP_OO
	--,SUM(CASE WHEN e.CHANNEL_NUM NOT IN ('930','220','221') AND e.ORDER_TYPE NOT IN('AUTOMATIC_REORDER','BUYER_REORDER') THEN e.QUANTITY_OPEN
	   --  ELSE 0 END) AS TY_RCPTS_ACTIVE_NRP_OO
FROM(
    SELECT
		a.PURCHASE_ORDER_NUMBER
    	,a.RMS_SKU_NUM
    	,a.RMS_CASEPACK_NUM
		,b.DEPT_NUM
		,b.DEPT_DESC
		,a.CHANNEL_NUM
		,a.CHANNEL_DESC
		,a.STORE_NUM
		,a.BANNER
		,a.CHANNEL_COUNTRY
		,a.WEEK_NUM
		,d.MONTH_IDNT
		,d.MONTH_LABEL
		,d.QUARTER 
		,d.FISCAL_YEAR_NUM
		,a.ORDER_TYPE
		,a.LATEST_APPROVAL_DATE
		,a.QUANTITY_OPEN
		,a.TOTAL_ESTIMATED_LANDING_COST
	FROM otb_oo_base a
	JOIN otb_oo_hierarchy b
	ON a.RMS_SKU_NUM = b.RMS_SKU_NUM
    and a.channel_country = b.channel_country
	JOIN otb_date d
	ON a.WEEK_NUM = d.WEEK_IDNT
	--where a.RMS_SKU_NUM = '2720355'
	--where dept_num in('800')
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19) e
GROUP BY 1,2,3,4,5,6,7)

 WITH DATA
  PRIMARY INDEX(DEPT_NUM,BANNER,COUNTRY,MONTH_LABEL)
  ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX(DEPT_NUM,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_NUM)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_oo_final;

--drop table otb_final_stg;
--create the final stg
CREATE MULTISET VOLATILE TABLE otb_final_stg AS(
SELECT
	a.DEPT_ID 
	,a.BANNER
	,a.COUNTRY
	,a.MONTH_IDNT
	,a.MONTH_LABEL 
	,a.QUARTER_IDNT
	,a.FISCAL_YEAR_NUM 
	,SUM(a.CP_RCPTS_RESERVE_C) AS CP_RCPTS_RESERVE_C
	,SUM(a.CP_RCPTS_ACTIVE_C) AS CP_RCPTS_ACTIVE_C
	,SUM(a.CP_RCPTS_ACTIVE_C-CP_RCPTS_RESERVE_C) AS Cp_Rcpts_Less_Reserve_C
	,SUM(a.TY_RCPTS_RP_ACTIVE_WTD_C+a.TY_RCPTS_NRP_ACTIVE_WTD_C) AS Ty_NPR_RP_MTD_Rcpts_C
	,SUM(a.TY_RCPTS_OO_ACTIVE_RP_C+a.TY_RCPTS_OO_ACTIVE_NRP_C) AS Ty_NPR_RP_OO_Rcpts_C
	,SUM(a.TY_RCPTS_NRP_ACTIVE_WTD_C+a.TY_RCPTS_OO_ACTIVE_NRP_C+a.TY_ACTIVE_CM_C) AS Ty_NRP_Rcpts_MTD_OO_CM_C
	,SUM(a.TY_RCPTS_NRP_ACTIVE_WTD_C) AS Ty_NRP_Rcpts_MTD_C
	,SUM(a.TY_RCPTS_OO_ACTIVE_NRP_C) AS Ty_NRP_OO_C
	,SUM(a.TY_ACTIVE_CM_C) AS Ty_NRP_CM_C
	,SUM(a.NRP_CM_C) AS NRP_CM_C
	,SUM(a.RP_CM_C) AS RP_CM_C
	,SUM(a.TY_RP_ANTICIPATED_SPEND_C) AS Ty_RP_Anticipated_Spend_C
	,SUM(a.TY_RCPTS_RP_ACTIVE_WTD_C+a.TY_RCPTS_OO_ACTIVE_RP_C) AS Ty_RP_Rcpts_MTD_OO_C
	,SUM(a.TY_RCPTS_RP_ACTIVE_WTD_C) AS Ty_RP_Rcpts_MTD_C
	,SUM(a.TY_RCPTS_OO_ACTIVE_RP_C) AS Ty_RP_OO_C
	,SUM(a.CP_RCPTS_INACTIVE_C) AS Inactive_Cp_Rcpts_C
	,SUM(a.TY_RCPTS_INACTIVE_WTD_C+a.TY_RCPTS_OO_INACTIVE_C+a.TY_INACTIVE_CM_C) AS Inactive_Ty_MTD_OO_CM_Rcpts_C
	,SUM(a.TY_RCPTS_INACTIVE_WTD_C) AS Inactive_Ty_MTD_C
	,SUM(a.TY_RCPTS_OO_INACTIVE_C) AS Inactive_Ty_OO_C
	,SUM(a.TY_INACTIVE_CM_C) AS Inactive_Ty_CM_C
	
	--,SUM(a.TY_RP_ANTICIPATED_SPEND_U) AS TY_RP_ANTICIPATED_SPEND_U
FROM(

	SELECT
		CAST(DEPT_ID AS int) AS DEPT_ID
		,CAST(BANNER AS varchar(20)) AS BANNER
		,CAST(COUNTRY AS varchar (5)) AS COUNTRY
		,CAST(QUARTER AS varchar(10)) AS QUARTER_IDNT
		,CAST(FISCAL_YEAR_NUM AS varchar(10)) AS FISCAL_YEAR_NUM 
		,CAST(MONTH_IDNT AS varchar(10)) AS MONTH_IDNT 
		,CAST(MONTH_LABEL AS varchar(10)) AS MONTH_LABEL
		,CAST(CP_RCPTS_RESERVE_C AS decimal (20,4)) AS CP_RCPTS_RESERVE_C
		,CAST(CP_RCPTS_ACTIVE_C AS decimal (20,4)) AS CP_RCPTS_ACTIVE_C
		,CAST(CP_RCPTS_INACTIVE_C AS decimal (20,4)) AS CP_RCPTS_INACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_RP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_NRP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_INACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_U
		,CAST(0 AS DECIMAL(20, 4)) AS TY_INACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_ACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS NRP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS RP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_INACTIVE_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_RP_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_NRP_C
	FROM otb_ty

	UNION ALL

	SELECT
		CAST(DEPT_ID AS int) AS DEPT_ID
		,CAST(BANNER AS varchar(20)) AS BANNER
		,CAST(COUNTRY AS varchar (5)) AS COUNTRY
		,CAST(QUARTER AS varchar(10)) AS QUARTER_IDNT
		,CAST(FISCAL_YEAR_NUM AS varchar(10)) AS FISCAL_YEAR_NUM 
		,CAST(MONTH_IDNT AS varchar(10)) AS MONTH_IDNT 
		,CAST(MONTH_LABEL AS varchar(10)) AS MONTH_LABEL
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_RESERVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_INACTIVE_C
		,CAST(TY_RCPTS_RP_ACTIVE_WTD_C AS DECIMAL(20, 4)) AS TY_RCPTS_RP_ACTIVE_WTD_C
		,CAST(TY_RCPTS_NRP_ACTIVE_WTD_C AS DECIMAL(20, 4)) AS TY_RCPTS_NRP_ACTIVE_WTD_C
		,CAST(TY_RCPTS_INACTIVE_WTD_C AS DECIMAL(20, 4)) AS TY_RCPTS_INACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_NRP_ANTICIPATED_SPEND_U
		,CAST(0 AS DECIMAL(20, 4)) AS TY_INACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_ACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS NRP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS RP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_INACTIVE_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_RP_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_NRP_C
	FROM otb_wtd_rcpts

	UNION ALL

	SELECT
		CAST(DEPT_ID AS int) AS DEPT_ID
		,CAST(BANNER AS varchar(20)) AS BANNER
		,CAST(COUNTRY AS varchar (5)) as COUNTRY
		,CAST(QUARTER AS varchar(10)) AS QUARTER_IDNT
		,CAST(FISCAL_YEAR_NUM AS varchar(10)) AS FISCAL_YEAR_NUM 
		,CAST(MONTH_IDNT AS varchar(10)) AS MONTH_IDNT 
		,CAST(MONTH_LABEL as varchar(10)) AS MONTH_LABEL
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_RESERVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_INACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_RP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_NRP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_INACTIVE_WTD_C
		,CAST(TY_RP_ANTICIPATED_SPEND_C AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_C
		--,CAST(TY_RP_ANTICIPATED_SPEND_U AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_U
		,CAST(0 AS DECIMAL(20, 4)) AS TY_INACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_ACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS NRP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS RP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_INACTIVE_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_RP_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_NRP_C
	FROM otb_rp

	UNION ALL

	SELECT
		CAST(DEPT_ID AS int) AS DEPT_ID
		,CAST(BANNER AS varchar(20)) AS BANNER
		,CAST(COUNTRY AS varchar (5)) AS COUNTRY
		,CAST(QUARTER AS varchar(10)) AS QUARTER_IDNT
		,CAST(FISCAL_YEAR_NUM AS varchar(10)) AS FISCAL_YEAR_NUM 
		,CAST(MONTH_IDNT AS varchar(10)) AS MONTH_IDNT 
		,CAST(MONTH_LABEL as varchar(10)) AS MONTH_LABEL
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_RESERVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_INACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_RP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_NRP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_INACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_U
		,CAST(TY_INACTIVE_CM_C AS DECIMAL(20, 4)) AS TY_INACTIVE_CM_C
		,CAST(TY_ACTIVE_CM_C AS DECIMAL(20, 4)) AS TY_ACTIVE_CM_C
		,CAST(NRP_CM_C AS DECIMAL(20, 4)) AS NRP_CM_C
		,CAST(RP_CM_C AS DECIMAL(20, 4)) AS RP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_INACTIVE_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_RP_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_NRP_C
	FROM otb_cm

	UNION ALL

	SELECT
		CAST(DEPT_NUM AS int) AS DEPT_ID
		,CAST(BANNER AS varchar(20)) AS BANNER
		,CAST(COUNTRY AS varchar (5)) AS COUNTRY
		,CAST(QUARTER AS varchar(10)) AS QUARTER_IDNT
		,CAST(FISCAL_YEAR_NUM AS varchar(10)) AS FISCAL_YEAR_NUM 
		,CAST(MONTH_IDNT AS varchar(10)) AS MONTH_IDNT 
		,CAST(MONTH_LABEL AS varchar(10)) AS MONTH_LABEL
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_RESERVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_ACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS CP_RCPTS_INACTIVE_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_RP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_NRP_ACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RCPTS_INACTIVE_WTD_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_C
		--,CAST(0 AS DECIMAL(20, 4)) AS TY_RP_ANTICIPATED_SPEND_U
		,CAST(0 AS DECIMAL(20, 4)) AS TY_INACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS TY_ACTIVE_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS NRP_CM_C
		,CAST(0 AS DECIMAL(20, 4)) AS RP_CM_C
		,CAST(TY_RCPTS_OO_INACTIVE_C AS DECIMAL(20, 4)) AS TY_RCPTS_OO_INACTIVE_C
		--,CAST(Ty_Rcpts_OO_Active_C AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_C
		,CAST(Ty_Rcpts_OO_Active_RP_C AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_RP_C
		,CAST(Ty_Rcpts_OO_Active_NRP_C AS DECIMAL(20, 4)) AS TY_RCPTS_OO_ACTIVE_NRP_C
		FROM otb_oo_final
		)a
GROUP BY 1,2,3,4,5,6,7)

WITH DATA
  PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
     PRIMARY INDEX(DEPT_ID,BANNER,COUNTRY,MONTH_LABEL)
     ,COLUMN(DEPT_ID)
     ,COLUMN(BANNER)
     ,COLUMN(COUNTRY)
     ,COLUMN(MONTH_LABEL)
     ON otb_final_stg;
    
DELETE FROM T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT;   

INSERT INTO T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT
	SELECT
		TRIM(b.DIVISION_NUM||','||b.DIVISION_NAME) AS Division
		,TRIM(b.SUBDIVISION_NUM||','||b.SUBDIVISION_NAME) AS Subdivision
		,TRIM(a.DEPT_ID||','||b.DEPT_NAME) AS Department
		,a.BANNER as Banner
		,a.COUNTRY as Country
		,a.MONTH_IDNT
		,a.MONTH_LABEL AS "Month"
		,a.QUARTER_IDNT AS Quarter
		,a.FISCAL_YEAR_NUM AS "Year"
		,b.ACTIVE_STORE_IND AS "Active vs Inactive"
		,a.CP_RCPTS_RESERVE_C 
		,a.CP_RCPTS_ACTIVE_C
		,a.Cp_Rcpts_Less_Reserve_C AS "Cp Rcpts Less Reserve C"
		,a.Ty_NPR_RP_MTD_Rcpts_C AS "Ty NPR RP MTD Rcpts C"
		,a.Ty_NPR_RP_OO_Rcpts_C AS "Ty NPR RP OO Rcpts C"
		,a.Ty_NRP_Rcpts_MTD_OO_CM_C AS "Ty NRP Rcpts MTD OO CM C"
		,a.Ty_NRP_Rcpts_MTD_C AS "Ty NRP Rcpts MTD C"
		,a.Ty_NRP_OO_C AS "Ty NRP OO C"
		,a.Ty_NRP_CM_C AS "Ty NRP CM C"
		,a.NRP_CM_C AS "NRP CM C"
		,a.RP_CM_C as "RP CM C"
		,a.Ty_RP_Anticipated_Spend_C AS "Ty RP Anticipated Spend C"
		,a.Ty_RP_Rcpts_MTD_OO_C AS "Ty RP Rcpts MTD OO C"
		,a.Ty_RP_Rcpts_MTD_C AS "Ty RP Rcpts MTD C"
		,a.Ty_RP_OO_C AS "Ty RP OO C"
		,a.Inactive_Cp_Rcpts_C AS "Inactive Cp Rcpts C"
		,a.Inactive_Ty_MTD_OO_CM_Rcpts_C AS "Inactive Ty MTD OO CM Rcpts C"
		,a.Inactive_Ty_MTD_C AS "Inactive Ty MTD C"
		,a.Inactive_Ty_OO_C AS "Inactive Ty OO C"
		,a.Inactive_Ty_CM_C AS "Inactive Ty CM C"
		,CURRENT_DATE as PROCESS_DT 
	FROM otb_final_stg a
	JOIN prd_nap_usr_vws.department_dim b
	ON a.DEPT_ID = b.DEPT_NUM
	WHERE a.CP_RCPTS_RESERVE_C <> 0
		OR a.CP_RCPTS_ACTIVE_C <> 0
		OR a.Cp_Rcpts_Less_Reserve_C <> 0 
		OR a.Ty_NPR_RP_MTD_Rcpts_C <> 0
		OR a.Ty_NPR_RP_OO_Rcpts_C <> 0
	    OR a.Ty_NRP_Rcpts_MTD_OO_CM_C <> 0
		OR a.Ty_NRP_Rcpts_MTD_C <> 0
		OR a.Ty_NRP_OO_C <> 0
		OR a.Ty_NRP_CM_C <> 0
		OR a.NRP_CM_C <> 0
		OR a.RP_CM_C <> 0
		OR a.Ty_RP_Anticipated_Spend_C <> 0
		OR a.Ty_RP_Rcpts_MTD_OO_C <> 0
		OR a.Ty_RP_Rcpts_MTD_C <> 0
		OR a.Ty_RP_OO_C <> 0
		OR a.Inactive_Cp_Rcpts_C <> 0
		OR a.Inactive_Ty_MTD_OO_CM_Rcpts_C <> 0
		OR a.Inactive_Ty_MTD_C <> 0
		OR a.Inactive_Ty_OO_C <> 0
		OR a.Inactive_Ty_CM_C <> 0;


	COLLECT STATS
     PRIMARY INDEX(Department,Banner, "Month" )
     ,COLUMN(Department)
     ,COLUMN(Banner)
     ,COLUMN("Month")
     ON T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT;