CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_OPEN_TO_BUY', 'OUTBOUND_PO_SKU_LKP', OUT_RETURN_MSG);

CREATE SET TABLE T2DL_DAS_OPEN_TO_BUY.OUTBOUND_PO_SKU_LKP ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      PURCHASE_ORDER_NUM VARCHAR(16) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SKU_NUM VARCHAR(16) CHARACTER SET UNICODE NOT CASESPECIFIC,
      WEEK_IDNT INTEGER,
      RCPT_COST DECIMAL(38,4),
      RCPT_UNITS DECIMAL(38,4),
      TOTAL_ESTIMATED_LANDING_COST DECIMAL(38,4),
      QUANTITY_OPEN DECIMAL(38,4),
      QUANTITY_ORDERED DECIMAL(38,4),
      PROCESS_DT DATE FORMAT 'YY/MM/DD')
PRIMARY INDEX ( PURCHASE_ORDER_NUM ,SKU_NUM ,WEEK_IDNT );