CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_OPEN_TO_BUY', 'PO_OTB_DETAIL_REPORT', OUT_RETURN_MSG);

CREATE MULTISET TABLE T2DL_DAS_OPEN_TO_BUY.PO_OTB_DETAIL_REPORT
	,FALLBACK
	,NO BEFORE JOURNAL
	,NO AFTER JOURNAL
	,CHECKSUM = DEFAULT
	,DEFAULT MERGEBLOCKRATIO
	,MAP = TD_MAP1 (
	purchase_order_num VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,xref_po VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,CHANNEL_NUM VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,CHANNEL_DESC VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,CHANNEL_BRAND VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,division_num VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,division_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,subdivision_num VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,subdivision_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,dept_num VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,dept_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_num VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,manufacturer_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SUPPLIER_GROUP VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,STATUS VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,otb_impact VARCHAR(19) CHARACTER SET UNICODE NOT CASESPECIFIC
	,edi_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,start_ship_date DATE FORMAT 'YY/MM/DD'
	,end_ship_date DATE FORMAT 'YY/MM/DD'
	,latest_approval_date DATE FORMAT 'YY/MM/DD'
	,otb_eow_date DATE FORMAT 'YY/MM/DD'
	,otb_month VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC
	,otb_month_idnt VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,order_type VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,internal_po_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,npg_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,po_type VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,purchase_type VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,"Month" VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC
	,month_idnt VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,fiscal_year_num VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,quarter_label VARCHAR(50) CHARACTER SET LATIN NOT CASESPECIFIC
	,plan_season_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,plan_type VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,ttl_approved_qty DECIMAL(20, 4)
	,ttl_approved_c DECIMAL(20, 4)
	,ttl_approved_r DECIMAL(20, 4)
	,UNIT_COST_AMT DECIMAL(38, 4)
	,last_carrier_asn_date DATE FORMAT 'YY/MM/DD'
	,last_supplier_asn_date DATE FORMAT 'YY/MM/DD'
	,last_ship_activity_date DATE FORMAT 'YY/MM/DD'
	,last_outbound_activity_date DATE FORMAT 'YY/MM/DD'
	,receipt_date DATE FORMAT 'YY/MM/DD'
	,RCPT_MTD_COST DECIMAL(38, 4)
	,RCPT_PREVIOUS_MTH_COST DECIMAL(38, 4)
	,RCPT_COST DECIMAL(38, 4)
	,RCPT_RETAIL DECIMAL(38, 4)
	,RCPT_MTD_UNITS DECIMAL(38, 4)
	,RCPT_PREVIOUS_MTH_UNITS DECIMAL(38, 4)
	,RCPT_UNITS DECIMAL(38, 4)
	,QUANTITY_ORDERED DECIMAL(38, 4)
	,QUANTITY_RECEIVED DECIMAL(38, 4)
	,QUANTITY_CANCELED DECIMAL(38, 4)
	,QUANTITY_OPEN DECIMAL(38, 4)
	,OO_COST DECIMAL(38, 4)
	,OO_RETAIL DECIMAL(38, 4)
	,vasn_sku_qty DECIMAL(38, 4)
	,vasn_cost DECIMAL(38, 4)
	,dc_received_qty DECIMAL(38, 4)
	,dc_received_c DECIMAL(38, 4)
	,CM_C DECIMAL(38, 4)
	,CM_R DECIMAL(38, 4)
	,CM_U DECIMAL(38, 4)
	,PROCESS_DT DATE FORMAT 'YY/MM/DD' 
	)
	PRIMARY INDEX (purchase_order_num,month_idnt);
	
	CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_OPEN_TO_BUY', 'UKNOWN_PO_DETAIL', OUT_RETURN_MSG);
	
	CREATE MULTISET TABLE T2DL_DAS_OPEN_TO_BUY.UKNOWN_PO_DETAIL
	,FALLBACK
	,NO BEFORE JOURNAL
	,NO AFTER JOURNAL
	,CHECKSUM = DEFAULT
	,DEFAULT MERGEBLOCKRATIO
	,MAP = TD_MAP1 (
	transfer_id VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,channel_num INTEGER
	,channel_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,month_idnt INTEGER
	,"Month" VARCHAR(19) CHARACTER SET LATIN NOT CASESPECIFIC
	,month_label VARCHAR(8) CHARACTER SET LATIN NOT CASESPECIFIC
	,div_num INTEGER
	,div_desc VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
	,sdiv_num INTEGER
	,sdiv_desc VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
	,dept_num INTEGER
	,dept_desc VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
	,class_num INTEGER
	,class_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,sbclass_num INTEGER
	,sbclass_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,rms_style_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,vpn VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
	,style_desc VARCHAR(800) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,supp_color VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
	,color_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,color_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,RCPT_COST DECIMAL(38, 4)
	,RCPT_RETAIL DECIMAL(38, 4)
	,RCPT_UNITS INTEGER
	,PROCESS_DT DATE FORMAT 'YY/MM/DD' 
	) 
	PRIMARY INDEX (transfer_id,month_idnt);