SET QUERY_BAND = 'App_ID=APP08629;
     DAG_ID=ddl_rakuten_publisher_daily_11521_ACE_ENG;
     Task_Name=ddl_rakuten_publisher_daily;'
     FOR SESSION VOLATILE;

/*

T2/Table Name: T2DL_DAS_APD.rakuten_publisher_daily
Team/Owner: Analytics Engineering
Date Modified: 2023-09-27

-- To support the 4 BOX Affiliates Performance Dashboard-Consolidated Version
-- Data begins '2021-05-01'

*/

--CALL SYS_MGMT.DROP_IF_EXISTS_SP ('t2dl_das_bie_dev', 'rakuten_publisher_daily', OUT_RETURN_MSG);

CREATE MULTISET TABLE {apd_t2_schema}.rakuten_publisher_daily ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DAY_DT DATE FORMAT 'YY/MM/DD',
      BANNER VARCHAR(14) CHARACTER SET UNICODE NOT CASESPECIFIC,
      UTM_CAMPAIGN VARCHAR(140) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PUBLISHER VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PUBLISHER_GROUP VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PUBLISHER_SUBGROUP VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      aff_return_rate FLOAT,
      ATTRIBUTED_DEMAND FLOAT,
      ATTRIBUTED_ORDERS FLOAT,
      ATTRIBUTED_NET_SALES FLOAT,
      ACQUIRED_ATTRIBUTED_DEMAND FLOAT,
      ACQUIRED_ATTRIBUTED_ORDERS FLOAT,
      RETAINED_ATTRIBUTED_ORDERS FLOAT,
      CLICKS DECIMAL(38,4),
      SESSIONS DECIMAL(38,5),
      PAID_PLACEMENT FLOAT,
      DAILY_COST FLOAT,
      RAKUTEN_GROSS_COMMISSIONS DECIMAL(38,2),
      ESTIMATED_NET_TOTAL_COST DECIMAL(38,2),
      RAKUTEN_GROSS_SALES DECIMAL(38,2),
      RAKUTEN_ORDERS FLOAT,
      RAKUTEN_NET_SALES DECIMAL(38,2),
      RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS FLOAT,
      RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND FLOAT,
      dw_sys_load_tmstp TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6))
PRIMARY INDEX ( DAY_DT ,BANNER ,
UTM_CAMPAIGN ,PUBLISHER ,PUBLISHER_GROUP ,PUBLISHER_SUBGROUP )
PARTITION BY Range_N(day_dt BETWEEN DATE '2021-01-31' AND DATE '2028-12-31' EACH INTERVAL '1' DAY);

COMMENT ON  {apd_t2_schema}.rakuten_publisher_daily IS '4 BOX Affiliates Performance-Consolidated Version';      

SET QUERY_BAND = NONE FOR SESSION;
