SET QUERY_BAND = 'App_ID=APP08629;
     DAG_ID=ddl_mta_publisher_daily_11521_ACE_ENG;
     Task_Name=ddl_mta_publisher_daily;'
     FOR SESSION VOLATILE;


/*

T2/Table Name: T2DL_DAS_APD.mta_publisher_daily
Team/Owner: Analytics Engineering
Date Modified: 2023-09-27

-- To support the 4 BOX Affiliates Performance Dashboard-Consolidated Version
-- Data begins '2021-05-01'

*/

--CALL SYS_MGMT.DROP_IF_EXISTS_SP ('t2dl_das_bie_dev', 'mta_publisher_daily', OUT_RETURN_MSG);

CREATE MULTISET TABLE {apd_t2_schema}.mta_publisher_daily ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      DAY_DT DATE FORMAT 'YY/MM/DD',
      BANNER VARCHAR(14) CHARACTER SET UNICODE NOT CASESPECIFIC,
      UTM_CAMPAIGN VARCHAR(140) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PUBLISHER VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PUBLISHER_GROUP VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PUBLISHER_SUBGROUP VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      AARE_STATUS_CODE VARCHAR(4) CHARACTER SET UNICODE NOT CASESPECIFIC,
      LOYALTY_STATUS VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DIVISION VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      SUB_DIVISION VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      DEPARTMENT VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      BRAND_NAME VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC,
      NPG_CODE VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      PRICE_TYPE VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ATTRIBUTED_DEMAND FLOAT,
      ATTRIBUTED_ORDERS FLOAT,
      ATTRIBUTED_NET_SALES FLOAT,
      RETAINED_ATTRIBUTED_ORDERS FLOAT,
      ACQUIRED_ATTRIBUTED_ORDERS FLOAT,
      ACQUIRED_ATTRIBUTED_DEMAND FLOAT,
      dw_sys_load_tmstp TIMESTAMP(6) DEFAULT Current_Timestamp(6) NOT NULL
      )
PRIMARY INDEX ( DAY_DT  ,BANNER ,
UTM_CAMPAIGN ,PUBLISHER ,PUBLISHER_GROUP ,PUBLISHER_SUBGROUP ,AARE_STATUS_CODE ,
LOYALTY_STATUS ,DIVISION ,SUB_DIVISION ,DEPARTMENT ,BRAND_NAME ,
NPG_CODE ,PRICE_TYPE )
PARTITION BY Range_N(day_dt BETWEEN DATE '2021-01-31' AND DATE '2028-12-31' EACH INTERVAL '1' DAY);

COMMENT ON  {apd_t2_schema}.mta_publisher_daily IS '4 BOX Affiliates Performance-Consolidated Version';

SET QUERY_BAND = NONE FOR SESSION;
