SET QUERY_BAND = 'App_ID=APP08737;
     DAG_ID=ddl_customer_sandbox_fact_11521_ACE_ENG;
     Task_Name=ddl_customer_sandbox_fact;'
     FOR SESSION VOLATILE;

/*

T2/Table Name: t2dl_das_strategy.customer_sandbox_fact
Team/Owner: Customer Analytics/Niharika Srivastava
Date Created/Modified: 04/30/2023

Note:
-- DDL for Customer Sandbox Fact table for microstrategy customer sandbox

*/

CREATE MULTISET TABLE {str_t2_schema}.customer_sandbox_fact ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      data_source VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      acp_id VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      store_banner_num INTEGER,
      store_channel_num INTEGER,
      store_channel_country INTEGER,
      store_num INTEGER,
      store_region_num INTEGER,
      div_num INTEGER,
      subdiv_num INTEGER,
      dept_num INTEGER,
      npg_flag VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC,
      brand_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      date_shopped DATE,
      month_num INTEGER,
      quarter_num INTEGER,
      year_num INTEGER,
      trip_id VARCHAR(69) CHARACTER SET UNICODE NOT CASESPECIFIC,
      gross_sales DECIMAL(38,2),
      return_amt DECIMAL(38,2),
      net_sales DECIMAL(38,2),
      gross_items INTEGER,
      return_items INTEGER,
      net_items INTEGER,
      RegPrice_net_spend DECIMAL(38,2),
      Promo_net_spend DECIMAL(38,2),
      Clearance_net_spend DECIMAL(38,2),
      RegPrice_gross_spend DECIMAL(38,2),
      Promo_gross_spend DECIMAL(38,2),
      Clearance_gross_spend DECIMAL(38,2),
      RegPrice_return_amt DECIMAL(38,2),
      Promo_return_amt DECIMAL(38,2),
      Clearance_return_amt DECIMAL(38,2),
      RegPrice_net_items INTEGER,
      Promo_net_items INTEGER,
      Clearance_net_items INTEGER,
      item_delivery_method_num INTEGER,
      employee_flag INTEGER,
      reporting_year_shopped_num INTEGER,
      audience_engagement_cohort_num INTEGER,
      cust_jwn_trip_bucket_num INTEGER,
      cust_jwn_net_spend_bucket_num INTEGER,
      cust_jwn_net_spend_bucket_ly_num INTEGER,
      cust_jwn_trip_bucket_ly_num INTEGER,
      cust_jwn_net_spend_bucket_fy_num INTEGER,
      cust_jwn_trip_bucket_num_fy_num INTEGER,
      audience_engagement_cohort_ly_num INTEGER,
      audience_engagement_cohort_fy_num INTEGER,
      cust_rack_trip_bucket_num INTEGER,
      cust_rack_net_spend_bucket_num INTEGER,
      cust_nord_trip_bucket_num INTEGER,
      cust_nord_net_spend_bucket_num INTEGER,
      cust_channel_combo_num INTEGER,
      cust_loyalty_type_num INTEGER,
      cust_loyalty_level_num INTEGER,
      cust_gender VARCHAR(7) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_age_group_num INTEGER,
      cust_employee_flag INTEGER,
      cust_tenure_bucket_years_num INTEGER,
      cust_acquisition_fiscal_year SMALLINT,
      cust_acquisition_channel_num INTEGER,
      cust_activation_channel_num INTEGER,
      cust_nms_market_num INTEGER,
      cust_nms_region_num INTEGER,
      cust_dma_num INTEGER,
      cust_region_num INTEGER,
      cust_country_num INTEGER,
      cust_tender_nordstrom INTEGER,
      cust_tender_nordstrom_note INTEGER,
      cust_tender_gift_card INTEGER,
      cust_tender_other BYTEINT,
      cust_had_a_cancel BYTEINT,
      cust_svc_group_exp_delivery INTEGER,
      cust_svc_group_order_pickup INTEGER,
      cust_svc_group_selling_relation INTEGER,
      cust_svc_group_remote_selling INTEGER,
      cust_svc_group_alterations INTEGER,
      cust_svc_group_in_store INTEGER,
      cust_svc_group_restaurant INTEGER,
      cust_service_free_exp_delivery INTEGER,
      cust_service_next_day_pickup INTEGER,
      cust_service_same_day_bopus INTEGER,
      cust_service_curbside_pickup INTEGER,
      cust_service_style_boards INTEGER,
      cust_service_gift_wrapping INTEGER,
      cust_styling INTEGER,
      cust_service_pop_in INTEGER,
      cust_ns_buyerflow_num INTEGER,
      cust_ncom_buyerflow_num INTEGER,
      cust_rs_buyerflow_num INTEGER,
      cust_rcom_buyerflow_num INTEGER,
      cust_nord_buyerflow_num INTEGER,
      cust_rack_buyerflow_num INTEGER,
      cust_jwn_buyerflow_num INTEGER,
      cust_jwn_acquired_aare INTEGER,
      cust_jwn_activated_aare INTEGER,
      cust_jwn_retained_aare INTEGER,
      cust_jwn_engaged_aare INTEGER,
      shopped_fls BYTEINT,
      shopped_ncom BYTEINT,
      shopped_rack BYTEINT,
      shopped_rcom BYTEINT,
      shopped_fp BYTEINT,
      shopped_op BYTEINT,
      shopped_jwn BYTEINT,
      cust_made_a_return BYTEINT,
      cust_platform_desktop INTEGER,
      cust_platform_MOW INTEGER,
      cust_platform_IOS INTEGER,
      cust_platform_Android INTEGER,
      cust_platform_POS INTEGER,
      cust_service_ship2store_ncom BYTEINT,
      cust_service_ship2store_rcom BYTEINT,
      restaurant_only_flag BYTEINT,
      closest_sol_dist_bucket_num INTEGER,
      closest_store_banner_num INTEGER,
      nord_sol_dist_bucket_num INTEGER,
      rack_sol_dist_bucket_num INTEGER,
      shopped_nord_local BYTEINT,
      ncom_ret_to_nstore BYTEINT,
      ncom_ret_by_mail BYTEINT,
      ncom_ret_to_rstore BYTEINT,
      rcom_ret_to_nstore BYTEINT,
      rcom_ret_by_mail BYTEINT,
      rcom_ret_to_rstore BYTEINT,
      cust_nord_Shoes_net_spend_ry DECIMAL(38,2),
      cust_nord_Beauty_net_spend_ry DECIMAL(38,2),
      cust_nord_Designer_Apparel_net_spend_ry DECIMAL(38,2),
      cust_nord_Apparel_net_spend_ry DECIMAL(38,2),
      cust_nord_Accessories_net_spend_ry DECIMAL(38,2),
      cust_nord_Home_net_spend_ry DECIMAL(38,2),
      cust_nord_Merch_Projects_net_spend_ry DECIMAL(38,2),
      cust_nord_Leased_Boutique_net_spend_ry DECIMAL(38,2),
      cust_nord_Restaurant_net_spend_ry DECIMAL(38,2),
      cust_rack_Shoes_net_spend_ry DECIMAL(38,2),
      cust_rack_Beauty_net_spend_ry DECIMAL(38,2),
      cust_rack_Designer_Apparel_net_spend_ry DECIMAL(38,2),
      cust_rack_Apparel_net_spend_ry DECIMAL(38,2),
      cust_rack_Accessories_net_spend_ry DECIMAL(38,2),
      cust_rack_Home_net_spend_ry DECIMAL(38,2),
      cust_rack_Merch_Projects_net_spend_ry DECIMAL(38,2),
      cust_Rack_Leased_Boutique_net_spend_ry DECIMAL(38,2),
      cust_Rack_Restaurant_net_spend_ry DECIMAL(38,2),
      cust_nord_RegPrice_net_spend_ry DECIMAL(38,2),
      cust_nord_Promo_net_spend_ry DECIMAL(38,2),
      cust_nord_Clearance_net_spend_ry DECIMAL(38,2),
      cust_rack_RegPrice_net_spend_ry DECIMAL(38,2),
      cust_rack_Promo_net_spend_ry DECIMAL(38,2),
      cust_rack_Clearance_net_spend_ry DECIMAL(38,2),
      cust_event_holiday INTEGER,
	cust_event_anniversary INTEGER,
	cust_contr_margin_decile INTEGER,
	cust_contr_margin_amt DECIMAL(14,4))
      
PRIMARY INDEX ( acp_id ,
		      store_num,
		      div_num,
		      subdiv_num,
		      dept_num,
		      date_shopped,
		      trip_id,
		      item_delivery_method_num,
		      employee_flag,
		      reporting_year_shopped_num,
		      audience_engagement_cohort_num,
		      cust_jwn_trip_bucket_num,
		      cust_jwn_net_spend_bucket_num,
		      cust_rack_trip_bucket_num ,
		      cust_rack_net_spend_bucket_num ,
		      cust_nord_trip_bucket_num ,
		      cust_nord_net_spend_bucket_num ,
		      cust_channel_combo_num ,
		      cust_loyalty_type_num ,
		      cust_loyalty_level_num ,
		      cust_gender,
		      cust_age_group_num ,
		      cust_tenure_bucket_years_num ,
		      cust_acquisition_fiscal_year ,
		      cust_acquisition_channel_num ,
		      cust_activation_channel_num ,
		      cust_nms_market_num ,
		      cust_dma_num ,
		      cust_had_a_cancel ,
		      cust_svc_group_exp_delivery ,
		      cust_svc_group_order_pickup ,
		      cust_svc_group_selling_relation ,
		      cust_svc_group_remote_selling ,
		      cust_svc_group_alterations ,
		      cust_svc_group_in_store ,
		      cust_svc_group_restaurant ,
		      cust_service_free_exp_delivery ,
		      cust_service_next_day_pickup ,
		      cust_service_same_day_bopus ,
		      cust_service_curbside_pickup ,
		      cust_service_style_boards ,
		      cust_service_gift_wrapping ,
		      cust_styling ,
		      cust_ns_buyerflow_num ,
		      cust_ncom_buyerflow_num ,
		      cust_rs_buyerflow_num ,
		      cust_rcom_buyerflow_num ,
		      cust_nord_buyerflow_num ,
		      cust_rack_buyerflow_num ,
		      cust_jwn_buyerflow_num ,
		      cust_jwn_acquired_aare ,
		      cust_jwn_activated_aare ,
		      cust_jwn_retained_aare ,
		      cust_jwn_engaged_aare ,
		      shopped_fls ,
		      shopped_ncom ,
		      shopped_rack ,
		      shopped_rcom ,
		      shopped_fp ,
		      shopped_op ,
		      shopped_jwn ,
		      cust_service_ship2store_ncom ,
		      cust_service_ship2store_rcom ,
		      closest_sol_dist_bucket_num)
PARTITION BY RANGE_N(date_shopped BETWEEN DATE '2019-01-01' AND DATE '2040-01-01' EACH INTERVAL '1' DAY);

-- Table Comment (STANDARD)
COMMENT ON {str_t2_schema}.audience_engagement_cohort_lkp IS 'Customer Sandbox Fact table for Customer Sandbox';

SET QUERY_BAND = NONE FOR SESSION;