SET QUERY_BAND = 'App_ID=APP07324;
     DAG_ID=ddl_ace_tpt_control_job_log_11521_ACE_ENG;
     Task_Name=t2dl_das_sessions;'
     FOR SESSION VOLATILE;

CALL SYS_MGMT.create_if_not_exists('{sessions_t2_schema}', 'tpt_control_tbl', 
'CREATE MULTISET TABLE {sessions_t2_schema}.TPT_CONTROL_TBL ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      job_name VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      database_name VARCHAR(64) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      object_name VARCHAR(60) CHARACTER SET LATIN NOT CASESPECIFIC FORMAT ''X(32)'' NOT NULL,
      object_type CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      batchusername VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      truncateindicator CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      errorlimit VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      textdelimiter_hexa_flag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      textdelimiter VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      AcceptExcessColumns CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      AcceptMissingColumns CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      QuotedData VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      OpenQuoteMark CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      s3bucket VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      s3prefix VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      s3singlepartfile VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      s3connectioncount VARCHAR(32) CHARACTER SET LATIN NOT CASESPECIFIC,
      collist_indicator_flag CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      collist VARCHAR(32000) CHARACTER SET LATIN NOT CASESPECIFIC,
      rcd_load_tmstp TIMESTAMP(6) NOT NULL,
      rcd_update_tmstp TIMESTAMP(6) NOT NULL,
      HeaderRcdIndicator CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL DEFAULT ''N'',
      AllFilesHeaderRcdIndicator CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL DEFAULT ''N'')
UNIQUE PRIMARY INDEX ( job_name )', 
OUT_RETURN_MSG);

CALL SYS_MGMT.create_if_not_exists('{sessions_t2_schema}', 'TPT_JOB_LOG', 
'CREATE MULTISET TABLE {sessions_t2_schema}.TPT_JOB_LOG ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      LogDate DATE FORMAT ''YYYY-MM-DD'' NOT NULL,
      job_name VARCHAR(128) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      job_type VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      ProcessID VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      database_name VARCHAR(64) CHARACTER SET LATIN NOT CASESPECIFIC,
      object_name VARCHAR(128) CHARACTER SET LATIN NOT CASESPECIFIC,
      ManifestFile VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      s3bucket VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      S3Prefix VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      S3Object VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      S3FileSize FLOAT COMPRESS 0.00000000000000E 000 ,
      S3FileTransferTime FLOAT COMPRESS 0.00000000000000E 000 ,
      JobStartTime TIMESTAMP(0),
      JobEndTime TIMESTAMP(0) COMPRESS ,
      ExportedRows BIGINT COMPRESS 0 ,
      RowsInserted BIGINT COMPRESS 0 ,
      RowsUpdated BIGINT COMPRESS 0 ,
      RowsDeleted BIGINT COMPRESS 0 ,
      ErrTable1Rows BIGINT COMPRESS 0 ,
      ETRows BIGINT COMPRESS 0 ,
      ErrTable2Rows BIGINT COMPRESS 0 ,
      UVRows BIGINT COMPRESS 0 ,
      RejectedRows BIGINT COMPRESS 0 ,
      DuplicateRows BIGINT COMPRESS 0 ,
      RowsInsertedAudit BIGINT COMPRESS ,
      JobCPUTime FLOAT,
      JobStatus VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      ErrorCode INTEGER COMPRESS 0 ,
      ErrorText VARCHAR(300) CHARACTER SET LATIN NOT CASESPECIFIC,
      rcd_load_tmstp TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
      rcd_update_tmstp TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6))
PRIMARY INDEX ( LogDate ,job_name )
PARTITION BY RANGE_N(LogDate  BETWEEN DATE ''2018-01-01'' AND DATE ''2030-12-31'' EACH INTERVAL ''1'' DAY )', 
OUT_RETURN_MSG);
SET QUERY_BAND = NONE FOR SESSION;