CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'new_store_opening{env_suffix}', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.new_store_opening{env_suffix}, FALLBACK,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    MAP = TD_MAP1
(
    purchase_order_num           VARCHAR(30) CHARACTER SET UNICODE, 
     store_num                    INTEGER,
     store_open_date              DATE,
     nso_wbo_end_date            DATE,
     rms_sku_num                  VARCHAR(20) CHARACTER SET UNICODE, 
     carton_num                   VARCHAR(30) CHARACTER SET UNICODE, 
     otb_eow_date                 DATE,
     po_type                      VARCHAR(10) CHARACTER SET UNICODE,
     status                       VARCHAR(10) CHARACTER SET UNICODE, 
     div_idnt                     INTEGER,
     div_desc                     VARCHAR(50) CHARACTER SET UNICODE, 
     subdiv_idnt                  INTEGER,
     subdiv_desc                  VARCHAR(50) CHARACTER SET UNICODE, 
     dept_idnt                    INTEGER,
     dept_desc                    VARCHAR(50) CHARACTER SET UNICODE, 
     class_idnt                   INTEGER,
     class_desc                   VARCHAR(50) CHARACTER SET UNICODE, 
     sbclass_idnt                 INTEGER,
     sbclass_desc                 VARCHAR(50) CHARACTER SET UNICODE, 
     category                     VARCHAR(50) CHARACTER SET UNICODE,
     brand_name                   VARCHAR(50) CHARACTER SET UNICODE,
     supplier_idnt                INTEGER,
     vpn_label                    VARCHAR(30) CHARACTER SET UNICODE, 
     transfer_id                  VARCHAR(100) CHARACTER SET UNICODE, 
     transfer_type                VARCHAR(40) CHARACTER SET UNICODE, 
     transfer_context_type        VARCHAR(40) CHARACTER SET UNICODE, 
     create_date                  DATE,
     ship_date                    DATE,
     receipt_date                 DATE,
     order_type_po                VARCHAR(3) CHARACTER SET UNICODE, 
     strategic_brand_flag         BYTEINT, -- Using BYTEINT for flag (0 or 1)
     on_order_u_actual            DECIMAL(18, 2),
     shipment_qty_intransit       DECIMAL(18, 2),
     shipment_qty_st_rcvd         DECIMAL(18, 2),
     shipment_qty_in_dc           DECIMAL(18, 2),
     rp_in_dc_u                   DECIMAL(18,2),
     rp_st_rcvd                   DECIMAL(18,2),
     rp_po_intransit              DECIMAL(18,2),
     palletized_units             DECIMAL(18, 2),
     quantity_allocated           DECIMAL(18, 2),
     approved_quantity_allocated_oo DECIMAL(18, 2),
     open_oo_u_oo                 DECIMAL(18, 2),
     on_order_u_oo                DECIMAL(18, 2),
     rp_oo                        DECIMAL(18,2),
     nonrp_oo                     DECIMAL(18,2),
     total_eoh_u                  DECIMAL(18, 2),
     eoh_reg_u                    DECIMAL(18, 2),
     eoh_clr_u                    DECIMAL(18, 2),
     create_transfer_u            DECIMAL(18, 2),
     intransit_transfer_u         DECIMAL(18, 2),
     st_rcvd_transfer_u           DECIMAL(18, 2),
     remaining_transfer_u         DECIMAL(18, 2),
     rs_transfer_u                DECIMAL(18,2),
     rp_rs_transfer_u             DECIMAL(18,2),
     rs_st_rcvd_transfer_u        DECIMAL(18,2),
     bop_plan_u                   DECIMAL(18,2),
     rp_plan_u                    DECIMAL(18,2),
     last_update_time             TIMESTAMP
) 
PRIMARY INDEX (store_num, rms_sku_num);


GRANT SELECT ON {environment_schema}.new_store_opening{env_suffix}  TO PUBLIC;