/*------------------------------------------------------
 MFP Summary
 Purpose: Provide channel-level in combination with country/banner-level MFP information at a weekly grain
 
 Last Update: 08/02/24 Asiyah Fox - Brought in Inventory Channel Plans
 Contact for logic/code: Asiyah Fox (Merch Analytics)
 Contact for ETL: Asiyah Fox (Merch Analytics)
 --------------------------------------------------------*/
 

-- Merch Hierarchy Names lookup
CREATE MULTISET VOLATILE TABLE MERCH_HIERARCHY_LKUP 
AS (
	SELECT 
		 DEPT_NUM 
		, DEPT_NAME
		, DEPARTMENT_LABEL
		, SUBDIVISION_NUM
		, SUBDIVISION_NAME
		, SUBDIVISION_LABEL
		, DIVISION_NUM
		, DIVISION_NAME
		, DIVISION_LABEL
	FROM PRD_NAP_VWS.DEPARTMENT_DIM
	GROUP BY 1,2,3,4,5,6,7,8,9
)
WITH DATA
PRIMARY INDEX (DEPT_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (DEPT_NUM)
	,COLUMN (DEPT_NUM)
		ON MERCH_HIERARCHY_LKUP;

-- Channel-level banner/country num lookup
CREATE MULTISET VOLATILE TABLE CHNL_LKUP
AS (
	SELECT DISTINCT
		CHANNEL_NUM
		, CHANNEL_LABEL
		, a.COUNTRY_CODE
		, a.BANNER_COUNTRY_DESC
		, a.BANNER_COUNTRY_NUM
		, b.BANNER_COUNTRY_LABEL
		, CASE 
			WHEN b.BANNER_DESC = 'OFF_PRICE' THEN 'NORDSTROM RACK'
			WHEN b.BANNER_DESC = 'FULL_PRICE' THEN 'NORDSTROM'
		END AS BANNER_DESC
	FROM PRD_NAP_VWS.ORG_CHANNEL_DIM a
	
	LEFT JOIN PRD_NAP_VWS.ORG_BANNER_COUNTRY_DIM b 
		ON b.BANNER_COUNTRY_NUM = a.BANNER_COUNTRY_NUM
)
WITH DATA
PRIMARY INDEX (CHANNEL_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (CHANNEL_NUM)
	,COLUMN (CHANNEL_NUM)
		ON CHNL_LKUP;

-- Country Lookup -- updated 3/7 with new channel logic for banner/country metrics
CREATE MULTISET VOLATILE TABLE COUNTRY_LKUP
as (
	SELECT DISTINCT 
		BANNER_COUNTRY_NUM
		, BANNER_DESC
		, BANNER_COUNTRY_DESC
		, BANNER_COUNTRY_LABEL
		, COUNTRY_CODE
		, CHANNEL_NUM
		, CHANNEL_LABEL
	FROM CHNL_LKUP
		
	UNION ALL
	
	SELECT DISTINCT 
    	BANNER_COUNTRY_NUM
		, BANNER_DESC
		, BANNER_COUNTRY_DESC
		, BANNER_COUNTRY_LABEL
		, COUNTRY_CODE 
		, CAST(0 AS INTEGER) AS CHANNEL_NUM
		, '0, UNKNOWN' AS CHANNEL_LABEL
	FROM CHNL_LKUP
)
WITH DATA
PRIMARY INDEX (BANNER_COUNTRY_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (BANNER_COUNTRY_NUM)
	,COLUMN (BANNER_COUNTRY_NUM)
		ON COUNTRY_LKUP;


-- Calendar Hierarchy Lookup
CREATE MULTISET VOLATILE TABLE CAL_LKUP 
AS (
	SELECT DISTINCT
		a.WEEK_NUM
		, a.WK_LABEL
		, a.WEEK_454_LABEL
		, a.MTH_LABEL
		, a.MONTH_NUM
		, a.QTR_LABEL
		, a.QUARTER_NUM
		, a.HALFYEAR_NUM
		, a.YEAR_NUM
		, (a.YR_DESC ||' '||CASE WHEN RIGHT(TO_CHAR(a.HALFYEAR_NUM),1) = 1 THEN 'H1' ELSE 'H2' END) as HALF 
		, a.YR_DESC
		, b.WEEK_END_DAY_DATE
	FROM PRD_NAP_VWS.WEEK_CAL_VW a
	LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b
		on a.WEEK_NUM = b.WEEK_IDNT
	WHERE b.fiscal_year_num >= (SELECT MAX(fiscal_year_num) FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM WHERE week_end_day_date <= CURRENT_DATE)-1 
		AND b.fiscal_year_num <= (SELECT MAX(fiscal_year_num) FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM WHERE week_end_day_date <= CURRENT_DATE)+1		
)
WITH DATA
PRIMARY INDEX (WEEK_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (WEEK_NUM)
	,COLUMN (WEEK_NUM)
		ON CAL_LKUP;

-- Fulfill Type Lookup
CREATE MULTISET VOLATILE TABLE FULFILL_TYPE_LKUP
AS (
	SELECT DISTINCT
		FULFILL_TYPE_NUM
		, FULFILL_TYPE_DESC
	FROM PRD_NAP_VWS.ALTERNATE_INVENTORY_MODEL_DIM
)
WITH DATA
PRIMARY INDEX (FULFILL_TYPE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (FULFILL_TYPE_NUM)
	,COLUMN (FULFILL_TYPE_NUM)
		ON FULFILL_TYPE_LKUP;

-- Combine information from preceding temp tables and add remaining metrics
	-- New 01.25.2024: Added TrueDay LY Fields
CREATE MULTISET VOLATILE TABLE CHANNEL
AS (
		SELECT
	    mch.DEPARTMENT_LABEL
	    , fact.DEPT_NUM
	    , tme.WEEK_454_LABEL
	    , tme.WEEK_NUM
	    , bc.BANNER_COUNTRY_LABEL 					AS BANNER_COUNTRY 
	    , bc.BANNER_DESC							AS BANNER 
	    , bc.COUNTRY_CODE 							AS COUNTRY 
	    , bc.BANNER_COUNTRY_NUM 
	    , fact.CHANNEL_NUM
	    , bc.CHANNEL_LABEL							AS CHANNEL
	    , fact.FULFILL_TYPE_NUM
		, ft.FULFILL_TYPE_DESC
	    , mch.SUBDIVISION_LABEL 					AS SUBDIVISION
	    , mch.DIVISION_LABEL 						AS DIVISION
	    , tme.MTH_LABEL 							AS "MONTH"
	    , tme.QTR_LABEL 							AS QUARTER
	    , tme.QUARTER_NUM
	    , tme.HALF
	    , tme.YR_DESC 								AS "YEAR"
		, tme.WEEK_END_DAY_DATE
		-- CP
		, SUM(CP_DEMAND_TOTAL_QTY)					AS CP_DEMAND_TOTAL_UNITS  
		, SUM(CP_DEMAND_TOTAL_RETAIL_AMT)			AS CP_DEMAND_TOTAL_RETAIL_AMT
		, SUM(CP_GROSS_MARGIN_RETAIL_AMT)			AS CP_GROSS_MARGIN_RETAIL_AMT
		, SUM(CP_GROSS_SALES_RETAIL_AMT)			AS CP_GROSS_SALES_RETAIL_AMT
		, SUM(CP_GROSS_SALES_QTY)					AS CP_GROSS_SALES_UNITS 
		, SUM(CP_NET_SALES_RETAIL_AMT)				AS CP_NET_SALES_RETAIL_AMT
		, SUM(CP_NET_SALES_QTY)					    AS CP_NET_SALES_UNITS 
		, SUM(CP_NET_SALES_COST_AMT)				AS CP_NET_SALES_COST_AMT
		, SUM(CP_NET_SALES_TRUNK_CLUB_RETAIL_AMT)	AS CP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, SUM(CP_NET_SALES_TRUNK_CLUB_QTY)			AS CP_NET_SALES_TRUNK_CLUB_UNITS 
		, SUM(CP_RETURNS_RETAIL_AMT)				AS CP_RETURNS_RETAIL_AMT
		, SUM(CP_RETURNS_QTY)						AS CP_RETURNS_UNITS 
		, SUM(CP_SHRINK_COST_AMT)					AS CP_SHRINK_COST_AMT
		, SUM(CP_SHRINK_QTY)						AS CP_SHRINK_UNITS 
		-- OP
		, SUM(OP_DEMAND_TOTAL_QTY)					AS OP_DEMAND_TOTAL_UNITS 
		, SUM(OP_DEMAND_TOTAL_RETAIL_AMT)			AS OP_DEMAND_TOTAL_RETAIL_AMT
		, SUM(OP_GROSS_MARGIN_RETAIL_AMT)			AS OP_GROSS_MARGIN_RETAIL_AMT
		, SUM(OP_GROSS_SALES_RETAIL_AMT)			AS OP_GROSS_SALES_RETAIL_AMT
		, SUM(OP_GROSS_SALES_QTY)					AS OP_GROSS_SALES_UNITS 
		, SUM(OP_NET_SALES_RETAIL_AMT)				AS OP_NET_SALES_RETAIL_AMT
		, SUM(OP_NET_SALES_QTY)					    AS OP_NET_SALES_UNITS 
		, SUM(OP_NET_SALES_COST_AMT)				AS OP_NET_SALES_COST_AMT
		, SUM(OP_NET_SALES_TRUNK_CLUB_RETAIL_AMT)	AS OP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, SUM(OP_NET_SALES_TRUNK_CLUB_QTY)			AS OP_NET_SALES_TRUNK_CLUB_UNITS 
		, SUM(OP_RETURNS_RETAIL_AMT)				AS OP_RETURNS_RETAIL_AMT
		, SUM(OP_RETURNS_QTY)						AS OP_RETURNS_UNITS 
		, SUM(OP_SHRINK_COST_AMT)					AS OP_SHRINK_COST_AMT
		, SUM(OP_SHRINK_QTY)						AS OP_SHRINK_UNITS 
		-- SP
		, SUM(SP_DEMAND_TOTAL_QTY)					AS SP_DEMAND_TOTAL_UNITS 
		, SUM(SP_DEMAND_TOTAL_RETAIL_AMT)			AS SP_DEMAND_TOTAL_RETAIL_AMT
		, SUM(SP_GROSS_MARGIN_RETAIL_AMT)			AS SP_GROSS_MARGIN_RETAIL_AMT
		, SUM(SP_GROSS_SALES_RETAIL_AMT)			AS SP_GROSS_SALES_RETAIL_AMT
		, SUM(SP_GROSS_SALES_QTY)					AS SP_GROSS_SALES_UNITS 
		, SUM(SP_NET_SALES_RETAIL_AMT)				AS SP_NET_SALES_RETAIL_AMT
		, SUM(SP_NET_SALES_QTY)					    AS SP_NET_SALES_UNITS 
		, SUM(SP_NET_SALES_COST_AMT)				AS SP_NET_SALES_COST_AMT
		, SUM(SP_NET_SALES_TRUNK_CLUB_RETAIL_AMT)	AS SP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, SUM(SP_NET_SALES_TRUNK_CLUB_QTY)			AS SP_NET_SALES_TRUNK_CLUB_UNITS 
		, SUM(SP_RETURNS_RETAIL_AMT)				AS SP_RETURNS_RETAIL_AMT
		, SUM(SP_RETURNS_QTY)						AS SP_RETURNS_UNITS 
		, SUM(SP_SHRINK_COST_AMT)					AS SP_SHRINK_COST_AMT
		, SUM(SP_SHRINK_QTY)						AS SP_SHRINK_UNITS 
		-- TY ACTUALS
		, SUM(TY_DEMAND_TOTAL_QTY)					AS TY_DEMAND_TOTAL_UNITS 
		, SUM(TY_DEMAND_TOTAL_RETAIL_AMT)			AS TY_DEMAND_TOTAL_RETAIL_AMT
		, SUM(TY_GROSS_MARGIN_RETAIL_AMT)			AS TY_GROSS_MARGIN_RETAIL_AMT
		, SUM(TY_GROSS_SALES_RETAIL_AMT)			AS TY_GROSS_SALES_RETAIL_AMT
		, SUM(TY_GROSS_SALES_QTY)					AS TY_GROSS_SALES_UNITS 
		, SUM(TY_NET_SALES_RETAIL_AMT)				AS TY_NET_SALES_RETAIL_AMT
		, SUM(TY_NET_SALES_QTY)					    AS TY_NET_SALES_UNITS 
		, SUM(TY_NET_SALES_COST_AMT)				AS TY_NET_SALES_COST_AMT
		, SUM(TY_NET_SALES_TRUNK_CLUB_RETAIL_AMT)	AS TY_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, SUM(TY_NET_SALES_TRUNK_CLUB_QTY)			AS TY_NET_SALES_TRUNK_CLUB_UNITS 
		, SUM(TY_RETURNS_RETAIL_AMT)				AS TY_RETURNS_RETAIL_AMT
		, SUM(TY_RETURNS_QTY)						AS TY_RETURNS_UNITS 
		, SUM(TY_SHRINK_COST_AMT)					AS TY_SHRINK_COST_AMT
		, SUM(TY_SHRINK_QTY)						AS TY_SHRINK_UNITS 
		-- LY ACTUALS
		, SUM(LY_DEMAND_TOTAL_QTY)					AS LY_DEMAND_TOTAL_UNITS 
		, SUM(LY_DEMAND_TOTAL_RETAIL_AMT)			AS LY_DEMAND_TOTAL_RETAIL_AMT
		, SUM(LY_GROSS_MARGIN_RETAIL_AMT)			AS LY_GROSS_MARGIN_RETAIL_AMT
		, SUM(LY_GROSS_SALES_RETAIL_AMT)			AS LY_GROSS_SALES_RETAIL_AMT
		, SUM(LY_GROSS_SALES_QTY)					AS LY_GROSS_SALES_UNITS 
		, SUM(LY_NET_SALES_RETAIL_AMT)				AS LY_NET_SALES_RETAIL_AMT
		, SUM(LY_NET_SALES_QTY)					    AS LY_NET_SALES_UNITS 
		, SUM(LY_NET_SALES_COST_AMT)				AS LY_NET_SALES_COST_AMT
		, SUM(LY_NET_SALES_TRUNK_CLUB_RETAIL_AMT)	AS LY_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, SUM(LY_NET_SALES_TRUNK_CLUB_QTY)			AS LY_NET_SALES_TRUNK_CLUB_UNITS 
		, SUM(LY_RETURNS_RETAIL_AMT)				AS LY_RETURNS_RETAIL_AMT
		, SUM(LY_RETURNS_QTY)						AS LY_RETURNS_UNITS 
		, SUM(LY_SHRINK_COST_AMT)					AS LY_SHRINK_COST_AMT
		, SUM(LY_SHRINK_QTY)						AS LY_SHRINK_UNITS 
		-- QP 
		, SUM(QP_DEMAND_TOTAL_QTY)					AS QP_DEMAND_TOTAL_UNITS 
		, SUM(QP_DEMAND_TOTAL_RETAIL_AMT)			AS QP_DEMAND_TOTAL_RETAIL_AMT
		, SUM(QP_GROSS_MARGIN_RETAIL_AMT)			AS QP_GROSS_MARGIN_RETAIL_AMT
		, SUM(QP_GROSS_SALES_RETAIL_AMT)			AS QP_GROSS_SALES_RETAIL_AMT
		, SUM(QP_GROSS_SALES_QTY)					AS QP_GROSS_SALES_UNITS 
		, SUM(QP_NET_SALES_RETAIL_AMT)				AS QP_NET_SALES_RETAIL_AMT
		, SUM(QP_NET_SALES_QTY)					    AS QP_NET_SALES_UNITS 
		, SUM(QP_NET_SALES_COST_AMT)				AS QP_NET_SALES_COST_AMT
		, SUM(QP_NET_SALES_TRUNK_CLUB_RETAIL_AMT)	AS QP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, SUM(QP_NET_SALES_TRUNK_CLUB_QTY)			AS QP_NET_SALES_TRUNK_CLUB_UNITS 
		, SUM(QP_RETURNS_RETAIL_AMT)				AS QP_RETURNS_RETAIL_AMT
		, SUM(QP_RETURNS_QTY)						AS QP_RETURNS_UNITS 
		, SUM(QP_SHRINK_COST_AMT)					AS QP_SHRINK_COST_AMT
		, SUM(QP_SHRINK_QTY)						AS QP_SHRINK_UNITS 
		-- TRUE DAY - NEW 01.25.2024
		, SUM(LY_TRUEDAY_DEMAND_TOTAL_QTY)			AS LY_TRUEDAY_DEMAND_TOTAL_UNITS 
		, SUM(LY_TRUEDAY_DEMAND_TOTAL_RETAIL_AMT)	AS LY_TRUEDAY_DEMAND_TOTAL_RETAIL_AMT
		, SUM(LY_TRUEDAY_GROSS_MARGIN_RETAIL_AMT)	AS LY_TRUEDAY_GROSS_MARGIN_RETAIL_AMT
		, SUM(LY_TRUEDAY_GROSS_SALES_RETAIL_AMT)	AS LY_TRUEDAY_GROSS_SALES_RETAIL_AMT
		, SUM(LY_TRUEDAY_GROSS_SALES_QTY)			AS LY_TRUEDAY_GROSS_SALES_UNITS 
		, SUM(LY_TRUEDAY_NET_SALES_RETAIL_AMT)		AS LY_TRUEDAY_NET_SALES_RETAIL_AMT
		, SUM(LY_TRUEDAY_NET_SALES_QTY)				AS LY_TRUEDAY_NET_SALES_UNITS 
		, SUM(LY_TRUEDAY_NET_SALES_COST_AMT)		AS LY_TRUEDAY_NET_SALES_COST_AMT
		, SUM(LY_TRUEDAY_RETURNS_RETAIL_AMT)		AS LY_TRUEDAY_RETURNS_RETAIL_AMT
		, SUM(LY_TRUEDAY_RETURNS_QTY)				AS LY_TRUEDAY_RETURNS_UNITS 
		, SUM(LY_TRUEDAY_SHRINK_COST_AMT)			AS LY_TRUEDAY_SHRINK_COST_AMT
		, SUM(LY_TRUEDAY_SHRINK_QTY)				AS LY_TRUEDAY_SHRINK_UNITS 
	FROM PRD_NAP_VWS.MFP_COST_PLAN_ACTUAL_CHANNEL_FACT fact
	JOIN MERCH_HIERARCHY_LKUP mch
		ON fact.DEPT_NUM = mch.DEPT_NUM
	JOIN CHNL_LKUP bc
		ON fact.CHANNEL_NUM = bc.CHANNEL_NUM
	JOIN CAL_LKUP tme
		ON fact.WEEK_NUM = tme.WEEK_NUM
	JOIN FULFILL_TYPE_LKUP ft
		ON fact.FULFILL_TYPE_NUM = ft.FULFILL_TYPE_NUM
	LEFT JOIN PRD_NAP_VWS.MFP_COST_PLAN_QTR_CHANNEL_FACT qp 
		ON qp.QUARTER_IDNT = tme.quarter_num
			AND qp.DEPT_NUM = fact.DEPT_NUM 
			AND qp.WEEK_NUM  = fact.WEEK_NUM 
			AND qp.CHANNEL_NUM = fact.CHANNEL_NUM 
			AND qp.FULFILL_TYPE_NUM = fact.FULFILL_TYPE_NUM 
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
)
WITH DATA
PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
	,COLUMN (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
		ON CHANNEL;

-- Combine information from preceding temp tables and add Channel Inventory Plans
CREATE MULTISET VOLATILE TABLE CHANNEL_INV
AS (
		SELECT
	    mch.DEPARTMENT_LABEL
	    , fact.DEPT_NUM
	    , tme.WEEK_454_LABEL
	    , tme.WEEK_NUM
	    , bc.BANNER_COUNTRY_LABEL 					AS BANNER_COUNTRY 
	    , bc.BANNER_DESC							AS BANNER 
	    , bc.COUNTRY_CODE 							AS COUNTRY 
	    , bc.BANNER_COUNTRY_NUM 
	    , fact.CHANNEL_NUM                          AS CHANNEL_NUM
	    , bc.CHANNEL_LABEL                          AS CHANNEL
	    , fact.FULFILL_TYPE_NUM
		, ft.FULFILL_TYPE_DESC
	    , mch.SUBDIVISION_LABEL 					AS SUBDIVISION
	    , mch.DIVISION_LABEL 						AS DIVISION
	    , tme.MTH_LABEL 							AS "MONTH"
	    , tme.QTR_LABEL 							AS QUARTER
	    , tme.QUARTER_NUM
	    , tme.HALF
	    , tme.YR_DESC 								AS "YEAR"
		, tme.WEEK_END_DAY_DATE
		-- OP
		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as OP_BOP_ACTIVE_UNITS
		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as OP_BOP_ACTIVE_COST_AMT
		, SUM(fact.OP_ENDING_OF_PERIOD_ACTIVE_QTY) 				as OP_EOP_ACTIVE_UNITS
		, SUM(fact.OP_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as OP_EOP_ACTIVE_COST_AMT
		-- Inventory Movement
--		, SUM(fact.OP_TRANSFER_OUT_INACTIVE_COST_AMT)			as OP_TRANSFER_INACTIVE_OUT_COST_AMT
--		, SUM(fact.OP_TRANSFER_OUT_INACTIVE_QTY)				as OP_TRANSFER_INACTIVE_OUT_UNITS
--		, SUM(fact.OP_TRANSFER_IN_RACKING_COST_AMT)				as OP_INV_RACK_IN_COST_AMT
--		, SUM(fact.OP_TRANSFER_IN_RACKING_QTY)					as OP_INV_RACK_IN_UNITS
--		, SUM(fact.OP_TRANSFER_OUT_RACKING_COST_AMT)			as OP_INV_RACK_OUT_COST_AMT
--		, SUM(fact.OP_TRANSFER_OUT_RACKING_QTY)					as OP_INV_RACK_OUT_UNITS
		-- Receipts
		, SUM(fact.OP_RECEIPTS_ACTIVE_COST_AMT) 				as OP_RCPTS_ACTIVE_COST_AMT
		, SUM(fact.OP_RECEIPTS_ACTIVE_QTY)						as OP_RCPTS_ACTIVE_UNITS
        , SUM(fact.OP_RECEIPTS_RESERVE_COST_AMT)                as OP_RCPTS_RESERVE_COST_AMT
        , SUM(fact.OP_RECEIPTS_RESERVE_QTY)                     as OP_RCPTS_RESERVE_UNITS
		-- Return to Vendor
--		, SUM(fact.OP_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as OP_RTV_ACTIVE_COST_AMT
--		, SUM(fact.OP_RETURN_TO_VENDOR_ACTIVE_QTY)		        as OP_RTV_ACTIVE_UNITS
    -- SP Metrics
		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as SP_BOP_ACTIVE_UNITS
		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as SP_BOP_ACTIVE_COST_AMT
		, SUM(fact.SP_ENDING_OF_PERIOD_ACTIVE_QTY) 				as SP_EOP_ACTIVE_UNITS
		, SUM(fact.SP_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as SP_EOP_ACTIVE_COST_AMT
		-- Inventory Movement
--		, SUM(fact.SP_TRANSFER_OUT_INACTIVE_COST_AMT)			as SP_TRANSFER_INACTIVE_OUT_COST_AMT
--		, SUM(fact.SP_TRANSFER_OUT_INACTIVE_QTY)				as SP_TRANSFER_INACTIVE_OUT_UNITS
--		, SUM(fact.SP_TRANSFER_IN_RACKING_COST_AMT)				as SP_INV_RACK_IN_COST_AMT
--		, SUM(fact.SP_TRANSFER_IN_RACKING_QTY)					as SP_INV_RACK_IN_UNITS
--		, SUM(fact.SP_TRANSFER_OUT_RACKING_COST_AMT)			as SP_INV_RACK_OUT_COST_AMT
--		, SUM(fact.SP_TRANSFER_OUT_RACKING_QTY)					as SP_INV_RACK_OUT_UNITS
		-- Receipts
		, SUM(fact.SP_RECEIPTS_ACTIVE_COST_AMT) 				as SP_RCPTS_ACTIVE_COST_AMT
		, SUM(fact.SP_RECEIPTS_ACTIVE_QTY)						as SP_RCPTS_ACTIVE_UNITS
        , SUM(fact.SP_RECEIPTS_RESERVE_COST_AMT)                as SP_RCPTS_RESERVE_COST_AMT
        , SUM(fact.SP_RECEIPTS_RESERVE_QTY)                     as SP_RCPTS_RESERVE_UNITS
		-- Return to Vendor
--		, SUM(fact.SP_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as SP_RTV_ACTIVE_COST_AMT
--		, SUM(fact.SP_RETURN_TO_VENDOR_ACTIVE_QTY)		        as SP_RTV_ACTIVE_UNITS
FROM T2DL_DAS_ACE_MFP.MFP_INV_CHANNEL_PLANS fact
	JOIN MERCH_HIERARCHY_LKUP mch
		ON fact.DEPT_NUM = mch.DEPT_NUM
	JOIN COUNTRY_LKUP bc
        ON fact.BANNER_COUNTRY_NUM = bc.BANNER_COUNTRY_NUM
		AND fact.CHANNEL_NUM = bc.CHANNEL_NUM
	JOIN CAL_LKUP tme
		ON fact.WEEK_NUM = tme.WEEK_NUM
	JOIN FULFILL_TYPE_LKUP ft
		ON fact.FULFILL_TYPE_NUM = ft.FULFILL_TYPE_NUM
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
)
WITH DATA
PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
	,COLUMN (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
		ON CHANNEL_INV;

-- Combine information and add metrics
	-- New 01.25.2024: Added TrueDay LY Fields
CREATE MULTISET VOLATILE TABLE BANNER_COUNTRY
AS (
	SELECT
        mch.DEPARTMENT_LABEL
        , fact.DEPT_NUM
        , tme.WEEK_454_LABEL
        , tme.WEEK_NUM
        , bc.BANNER_COUNTRY_LABEL 					as BANNER_COUNTRY
        , bc.BANNER_DESC 							as BANNER
        , bc.COUNTRY_CODE 							as COUNTRY
        , fact.BANNER_COUNTRY_NUM
        , bc.CHANNEL_NUM							 
        , bc.CHANNEL_LABEL							 
        , fact.FULFILL_TYPE_NUM
		, ft.FULFILL_TYPE_DESC
        , mch.SUBDIVISION_LABEL 					as SUBDIVISION
        , mch.DIVISION_LABEL 						as DIVISION
        , tme.MTH_LABEL 							as "MONTH"
        , tme.QTR_LABEL 							as QUARTER
		, tme.QUARTER_NUM
        , tme.HALF
        , tme.YR_DESC 								as "YEAR"
		, tme.WEEK_END_DAY_DATE
	-- CP Metrics	
        -- Inventory
		, SUM(fact.CP_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as CP_BOP_ACTIVE_UNITS
		, SUM(fact.CP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as CP_BOP_ACTIVE_COST_AMT
		, SUM(fact.CP_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as CP_BOP_INACTIVE_UNITS
		, SUM(fact.CP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as CP_BOP_INACTIVE_COST_AMT
		, SUM(fact.CP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + fact.CP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as CP_BOP_TOT_COST_AMT
		, SUM(fact.CP_BEGINNING_OF_PERIOD_ACTIVE_QTY + fact.CP_BEGINNING_OF_PERIOD_INACTIVE_QTY) as CP_BOP_TOT_UNITS
		, SUM(fact.CP_ENDING_OF_PERIOD_ACTIVE_QTY) 				as CP_EOP_ACTIVE_UNITS
		, SUM(fact.CP_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as CP_EOP_ACTIVE_COST_AMT
		, SUM(fact.CP_ENDING_OF_PERIOD_INACTIVE_QTY) 			as CP_EOP_INACTIVE_UNITS
		, SUM(fact.CP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as CP_EOP_INACTIVE_COST_AMT
		, SUM(fact.CP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + fact.CP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as CP_EOP_TOT_COST_AMT
		, SUM(fact.CP_ENDING_OF_PERIOD_ACTIVE_QTY + fact.CP_ENDING_OF_PERIOD_INACTIVE_QTY) as CP_EOP_TOT_UNITS
		, SUM(fact.CP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY) as CP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, SUM(fact.CP_TRANSFER_IN_ACTIVE_COST_AMT)				as CP_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(fact.CP_TRANSFER_IN_ACTIVE_QTY)					as CP_TRANSFER_ACTIVE_IN_UNITS
		, SUM(fact.CP_TRANSFER_OUT_ACTIVE_COST_AMT)				as CP_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(fact.CP_TRANSFER_OUT_ACTIVE_QTY)					as CP_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(fact.CP_TRANSFER_IN_INACTIVE_COST_AMT)			as CP_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(fact.CP_TRANSFER_IN_INACTIVE_QTY)					as CP_TRANSFER_INACTIVE_IN_UNITS
		, SUM(fact.CP_TRANSFER_OUT_INACTIVE_COST_AMT)			as CP_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(fact.CP_TRANSFER_OUT_INACTIVE_QTY)				as CP_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(fact.CP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as CP_INV_MVMT_IN_DS_COST_AMT
		, SUM(fact.CP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 		as CP_INV_MVMT_IN_DS_UNITS
		, SUM(fact.CP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT) as CP_INV_MVMT_OUT_DS_COST_AMT
		, SUM(fact.CP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY) 		as CP_INV_MVMT_OUT_DS_UNITS
		, SUM(fact.CP_TRANSFER_IN_RACKING_COST_AMT + fact.CP_TRANSFER_IN_OTHER_COST_AMT + fact.CP_TRANSFER_IN_ACTIVE_COST_AMT + fact.CP_RECLASS_IN_COST_AMT + fact.CP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as CP_INV_MVMT_IN_TOT_COST_AMT
		, SUM(fact.CP_TRANSFER_IN_RACKING_QTY + fact.CP_TRANSFER_IN_OTHER_QTY + fact.CP_TRANSFER_IN_ACTIVE_QTY + fact.CP_RECLASS_IN_QTY + fact.CP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 							as CP_INV_MVMT_IN_TOT_UNITS
		, SUM(fact.CP_TRANSFER_OUT_RACKING_COST_AMT + fact.CP_TRANSFER_OUT_OTHER_COST_AMT + fact.CP_TRANSFER_OUT_ACTIVE_COST_AMT + fact.CP_RECLASS_OUT_COST_AMT + fact.CP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT + fact.CP_RETURN_TO_VENDOR_ACTIVE_COST_AMT) 	as CP_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(fact.CP_TRANSFER_OUT_RACKING_QTY + fact.CP_TRANSFER_OUT_OTHER_QTY + fact.CP_TRANSFER_OUT_ACTIVE_QTY + fact.CP_RECLASS_OUT_QTY + fact.CP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY + fact.CP_RETURN_TO_VENDOR_ACTIVE_QTY) 	as CP_INV_MVMT_OUT_TOT_UNITS 
		, SUM(fact.CP_TRANSFER_IN_OTHER_COST_AMT) 				as CP_INV_OTHER_IN_COST_AMT
		, SUM(fact.CP_TRANSFER_IN_OTHER_QTY)					as CP_INV_OTHER_IN_UNITS
		, SUM(fact.CP_TRANSFER_OUT_OTHER_COST_AMT) 				as CP_INV_OTHER_OUT_COST_AMT
		, SUM(fact.CP_TRANSFER_OUT_OTHER_QTY)					as CP_INV_OTHER_OUT_UNITS
		, SUM(fact.CP_TRANSFER_IN_RACKING_COST_AMT)				as CP_INV_RACK_IN_COST_AMT
		, SUM(fact.CP_TRANSFER_IN_RACKING_QTY)					as CP_INV_RACK_IN_UNITS
		, SUM(fact.CP_TRANSFER_OUT_RACKING_COST_AMT)			as CP_INV_RACK_OUT_COST_AMT
		, SUM(fact.CP_TRANSFER_OUT_RACKING_QTY)					as CP_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(fact.CP_MERCH_MARGIN_RETAIL_AMT) 					as CP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(fact.CP_DISCOUNT_TERMS_COST_AMT) 					as CP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, SUM(fact.CP_RECEIPTS_ACTIVE_COST_AMT) 				as CP_RCPTS_ACTIVE_COST_AMT
		, SUM(fact.CP_RECEIPTS_ACTIVE_QTY)						as CP_RCPTS_ACTIVE_UNITS
		, SUM(fact.CP_RECEIPTS_INACTIVE_COST_AMT) 				as CP_RCPTS_INACTIVE_COST_AMT
		, SUM(fact.CP_RECEIPTS_INACTIVE_QTY)					as CP_RCPTS_INACTIVE_UNITS
		, SUM(fact.CP_RECEIPTS_ACTIVE_COST_AMT + fact.CP_RECEIPTS_INACTIVE_COST_AMT) as CP_RCPTS_TOT_COST_AMT
		, SUM(fact.CP_RECEIPTS_ACTIVE_QTY + fact.CP_RECEIPTS_INACTIVE_QTY) as CP_RCPTS_TOT_UNITS
        , SUM(fact.CP_RECEIPTS_RESERVE_COST_AMT)                as CP_RCPTS_RESERVE_COST_AMT
        , SUM(fact.CP_RECEIPTS_RESERVE_QTY)                     as CP_RCPTS_RESERVE_UNITS
		-- Reclass
		, SUM(fact.CP_RECLASS_IN_COST_AMT) 						as CP_RECLASS_IN_COST_AMT
		, SUM(fact.CP_RECLASS_IN_QTY)							as CP_RECLASS_IN_UNITS
		, SUM(fact.CP_RECLASS_OUT_COST_AMT) 					as CP_RECLASS_OUT_COST_AMT
		, SUM(fact.CP_RECLASS_OUT_QTY)							as CP_RECLASS_OUT_UNITS
		, SUM(fact.CP_RECLASS_IN_COST_AMT + fact.CP_RECLASS_OUT_COST_AMT) as CP_RECLASS_TOT_COST_AMT
		, SUM(fact.CP_RECLASS_IN_QTY + fact.CP_RECLASS_OUT_QTY) as CP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(fact.CP_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as CP_RTV_ACTIVE_COST_AMT
		, SUM(fact.CP_RETURN_TO_VENDOR_ACTIVE_QTY)		        as CP_RTV_ACTIVE_UNITS
		, SUM(fact.CP_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as CP_RTV_INACTIVE_COST_AMT
		, SUM(fact.CP_RETURN_TO_VENDOR_INACTIVE_QTY)		    as CP_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(fact.CP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as CP_MOS_ACTIVE_COST_AMT
        , SUM(fact.CP_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as CP_MOS_ACTIVE_UNITS
        , SUM(fact.CP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as CP_MOS_INACTIVE_COST_AMT
        , SUM(fact.CP_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as CP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(fact.CP_VENDOR_FUNDS_COST_AMT)					as CP_VENDOR_FUNDS_COST_AMT
    -- OP Metrics
        -- Inventory
--		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as OP_BOP_ACTIVE_UNITS
--		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as OP_BOP_ACTIVE_COST_AMT
		, SUM(fact.OP_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as OP_BOP_INACTIVE_UNITS
		, SUM(fact.OP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as OP_BOP_INACTIVE_COST_AMT
		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + fact.OP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as OP_BOP_TOT_COST_AMT
		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_QTY + fact.OP_BEGINNING_OF_PERIOD_INACTIVE_QTY) as OP_BOP_TOT_UNITS
--		, SUM(fact.OP_ENDING_OF_PERIOD_ACTIVE_QTY) 				as OP_EOP_ACTIVE_UNITS
--		, SUM(fact.OP_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as OP_EOP_ACTIVE_COST_AMT
		, SUM(fact.OP_ENDING_OF_PERIOD_INACTIVE_QTY) 			as OP_EOP_INACTIVE_UNITS
		, SUM(fact.OP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as OP_EOP_INACTIVE_COST_AMT
		, SUM(fact.OP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + fact.OP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as OP_EOP_TOT_COST_AMT
		, SUM(fact.OP_ENDING_OF_PERIOD_ACTIVE_QTY + fact.OP_ENDING_OF_PERIOD_INACTIVE_QTY) as OP_EOP_TOT_UNITS
		, SUM(fact.OP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY) as OP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, SUM(fact.OP_TRANSFER_IN_ACTIVE_COST_AMT)				as OP_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(fact.OP_TRANSFER_IN_ACTIVE_QTY)					as OP_TRANSFER_ACTIVE_IN_UNITS
		, SUM(fact.OP_TRANSFER_OUT_ACTIVE_COST_AMT)				as OP_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(fact.OP_TRANSFER_OUT_ACTIVE_QTY)					as OP_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(fact.OP_TRANSFER_IN_INACTIVE_COST_AMT)			as OP_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(fact.OP_TRANSFER_IN_INACTIVE_QTY)					as OP_TRANSFER_INACTIVE_IN_UNITS
		, SUM(fact.OP_TRANSFER_OUT_INACTIVE_COST_AMT)			as OP_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(fact.OP_TRANSFER_OUT_INACTIVE_QTY)				as OP_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(fact.OP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as OP_INV_MVMT_IN_DS_COST_AMT
		, SUM(fact.OP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 		as OP_INV_MVMT_IN_DS_UNITS
		, SUM(fact.OP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT) as OP_INV_MVMT_OUT_DS_COST_AMT
		, SUM(fact.OP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY) 		as OP_INV_MVMT_OUT_DS_UNITS
		, SUM(fact.OP_TRANSFER_IN_RACKING_COST_AMT + fact.OP_TRANSFER_IN_OTHER_COST_AMT + fact.OP_TRANSFER_IN_ACTIVE_COST_AMT + fact.OP_RECLASS_IN_COST_AMT + fact.OP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as OP_INV_MVMT_IN_TOT_COST_AMT
		, SUM(fact.OP_TRANSFER_IN_RACKING_QTY + fact.OP_TRANSFER_IN_OTHER_QTY + fact.OP_TRANSFER_IN_ACTIVE_QTY + fact.OP_RECLASS_IN_QTY + fact.OP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 							as OP_INV_MVMT_IN_TOT_UNITS
		, SUM(fact.OP_TRANSFER_OUT_RACKING_COST_AMT + fact.OP_TRANSFER_OUT_OTHER_COST_AMT + fact.OP_TRANSFER_OUT_ACTIVE_COST_AMT + fact.OP_RECLASS_OUT_COST_AMT + fact.OP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT + fact.OP_RETURN_TO_VENDOR_ACTIVE_COST_AMT) 	as OP_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(fact.OP_TRANSFER_OUT_RACKING_QTY + fact.OP_TRANSFER_OUT_OTHER_QTY + fact.OP_TRANSFER_OUT_ACTIVE_QTY + fact.OP_RECLASS_OUT_QTY + fact.OP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY + fact.OP_RETURN_TO_VENDOR_ACTIVE_QTY) 	as OP_INV_MVMT_OUT_TOT_UNITS 
		, SUM(fact.OP_TRANSFER_IN_OTHER_COST_AMT) 				as OP_INV_OTHER_IN_COST_AMT
		, SUM(fact.OP_TRANSFER_IN_OTHER_QTY)					as OP_INV_OTHER_IN_UNITS
		, SUM(fact.OP_TRANSFER_OUT_OTHER_COST_AMT) 				as OP_INV_OTHER_OUT_COST_AMT
		, SUM(fact.OP_TRANSFER_OUT_OTHER_QTY)					as OP_INV_OTHER_OUT_UNITS
		, SUM(fact.OP_TRANSFER_IN_RACKING_COST_AMT)				as OP_INV_RACK_IN_COST_AMT
		, SUM(fact.OP_TRANSFER_IN_RACKING_QTY)					as OP_INV_RACK_IN_UNITS
		, SUM(fact.OP_TRANSFER_OUT_RACKING_COST_AMT)			as OP_INV_RACK_OUT_COST_AMT
		, SUM(fact.OP_TRANSFER_OUT_RACKING_QTY)					as OP_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(fact.OP_MERCH_MARGIN_RETAIL_AMT) 					as OP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(fact.OP_DISCOUNT_TERMS_COST_AMT) 					as OP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
--		, SUM(fact.OP_RECEIPTS_ACTIVE_COST_AMT) 				as OP_RCPTS_ACTIVE_COST_AMT
--		, SUM(fact.OP_RECEIPTS_ACTIVE_QTY)						as OP_RCPTS_ACTIVE_UNITS
		, SUM(fact.OP_RECEIPTS_INACTIVE_COST_AMT) 				as OP_RCPTS_INACTIVE_COST_AMT
		, SUM(fact.OP_RECEIPTS_INACTIVE_QTY)					as OP_RCPTS_INACTIVE_UNITS
		, SUM(fact.OP_RECEIPTS_ACTIVE_COST_AMT + fact.OP_RECEIPTS_INACTIVE_COST_AMT) as OP_RCPTS_TOT_COST_AMT
		, SUM(fact.OP_RECEIPTS_ACTIVE_QTY + fact.OP_RECEIPTS_INACTIVE_QTY) as OP_RCPTS_TOT_UNITS
--        , SUM(fact.OP_RECEIPTS_RESERVE_COST_AMT)                as OP_RCPTS_RESERVE_COST_AMT
--        , SUM(fact.OP_RECEIPTS_RESERVE_QTY)                     as OP_RCPTS_RESERVE_UNITS
		-- Reclass
		, SUM(fact.OP_RECLASS_IN_COST_AMT) 						as OP_RECLASS_IN_COST_AMT
		, SUM(fact.OP_RECLASS_IN_QTY)							as OP_RECLASS_IN_UNITS
		, SUM(fact.OP_RECLASS_OUT_COST_AMT) 					as OP_RECLASS_OUT_COST_AMT
		, SUM(fact.OP_RECLASS_OUT_QTY)							as OP_RECLASS_OUT_UNITS
		, SUM(fact.OP_RECLASS_IN_COST_AMT + fact.OP_RECLASS_OUT_COST_AMT) as OP_RECLASS_TOT_COST_AMT
		, SUM(fact.OP_RECLASS_IN_QTY + fact.OP_RECLASS_OUT_QTY) as OP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(fact.OP_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as OP_RTV_ACTIVE_COST_AMT
		, SUM(fact.OP_RETURN_TO_VENDOR_ACTIVE_QTY)		        as OP_RTV_ACTIVE_UNITS
		, SUM(fact.OP_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as OP_RTV_INACTIVE_COST_AMT
		, SUM(fact.OP_RETURN_TO_VENDOR_INACTIVE_QTY)		    as OP_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(fact.OP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as OP_MOS_ACTIVE_COST_AMT
        , SUM(fact.OP_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as OP_MOS_ACTIVE_UNITS
        , SUM(fact.OP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as OP_MOS_INACTIVE_COST_AMT
        , SUM(fact.OP_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as OP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(fact.OP_VENDOR_FUNDS_COST_AMT)					as OP_VENDOR_FUNDS_COST_AMT		
    -- SP Metrics
        -- Inventory
--		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as SP_BOP_ACTIVE_UNITS
--		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as SP_BOP_ACTIVE_COST_AMT
		, SUM(fact.SP_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as SP_BOP_INACTIVE_UNITS
		, SUM(fact.SP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as SP_BOP_INACTIVE_COST_AMT
		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + fact.SP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as SP_BOP_TOT_COST_AMT
		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_QTY + fact.SP_BEGINNING_OF_PERIOD_INACTIVE_QTY) as SP_BOP_TOT_UNITS
--		, SUM(fact.SP_ENDING_OF_PERIOD_ACTIVE_QTY) 				as SP_EOP_ACTIVE_UNITS
--		, SUM(fact.SP_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as SP_EOP_ACTIVE_COST_AMT
		, SUM(fact.SP_ENDING_OF_PERIOD_INACTIVE_QTY) 			as SP_EOP_INACTIVE_UNITS
		, SUM(fact.SP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as SP_EOP_INACTIVE_COST_AMT
		, SUM(fact.SP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + fact.SP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as SP_EOP_TOT_COST_AMT
		, SUM(fact.SP_ENDING_OF_PERIOD_ACTIVE_QTY + fact.SP_ENDING_OF_PERIOD_INACTIVE_QTY) as SP_EOP_TOT_UNITS
		, SUM(fact.SP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY) as SP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, SUM(fact.SP_TRANSFER_IN_ACTIVE_COST_AMT)				as SP_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(fact.SP_TRANSFER_IN_ACTIVE_QTY)					as SP_TRANSFER_ACTIVE_IN_UNITS
		, SUM(fact.SP_TRANSFER_OUT_ACTIVE_COST_AMT)				as SP_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(fact.SP_TRANSFER_OUT_ACTIVE_QTY)					as SP_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(fact.SP_TRANSFER_IN_INACTIVE_COST_AMT)			as SP_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(fact.SP_TRANSFER_IN_INACTIVE_QTY)					as SP_TRANSFER_INACTIVE_IN_UNITS
		, SUM(fact.SP_TRANSFER_OUT_INACTIVE_COST_AMT)			as SP_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(fact.SP_TRANSFER_OUT_INACTIVE_QTY)				as SP_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(fact.SP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as SP_INV_MVMT_IN_DS_COST_AMT
		, SUM(fact.SP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 		as SP_INV_MVMT_IN_DS_UNITS
		, SUM(fact.SP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT) as SP_INV_MVMT_OUT_DS_COST_AMT
		, SUM(fact.SP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY) 		as SP_INV_MVMT_OUT_DS_UNITS
		, SUM(fact.SP_TRANSFER_IN_RACKING_COST_AMT + fact.SP_TRANSFER_IN_OTHER_COST_AMT + fact.SP_TRANSFER_IN_ACTIVE_COST_AMT + fact.SP_RECLASS_IN_COST_AMT + fact.SP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as SP_INV_MVMT_IN_TOT_COST_AMT
		, SUM(fact.SP_TRANSFER_IN_RACKING_QTY + fact.SP_TRANSFER_IN_OTHER_QTY + fact.SP_TRANSFER_IN_ACTIVE_QTY + fact.SP_RECLASS_IN_QTY + fact.SP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 							as SP_INV_MVMT_IN_TOT_UNITS
		, SUM(fact.SP_TRANSFER_OUT_RACKING_COST_AMT + fact.SP_TRANSFER_OUT_OTHER_COST_AMT + fact.SP_TRANSFER_OUT_ACTIVE_COST_AMT + fact.SP_RECLASS_OUT_COST_AMT + fact.SP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT + fact.SP_RETURN_TO_VENDOR_ACTIVE_COST_AMT) 	as SP_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(fact.SP_TRANSFER_OUT_RACKING_QTY + fact.SP_TRANSFER_OUT_OTHER_QTY + fact.SP_TRANSFER_OUT_ACTIVE_QTY + fact.SP_RECLASS_OUT_QTY + fact.SP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY + fact.SP_RETURN_TO_VENDOR_ACTIVE_QTY) 	as SP_INV_MVMT_OUT_TOT_UNITS 
		, SUM(fact.SP_TRANSFER_IN_OTHER_COST_AMT) 				as SP_INV_OTHER_IN_COST_AMT
		, SUM(fact.SP_TRANSFER_IN_OTHER_QTY)					as SP_INV_OTHER_IN_UNITS
		, SUM(fact.SP_TRANSFER_OUT_OTHER_COST_AMT) 				as SP_INV_OTHER_OUT_COST_AMT
		, SUM(fact.SP_TRANSFER_OUT_OTHER_QTY)					as SP_INV_OTHER_OUT_UNITS
		, SUM(fact.SP_TRANSFER_IN_RACKING_COST_AMT)				as SP_INV_RACK_IN_COST_AMT
		, SUM(fact.SP_TRANSFER_IN_RACKING_QTY)					as SP_INV_RACK_IN_UNITS
		, SUM(fact.SP_TRANSFER_OUT_RACKING_COST_AMT)			as SP_INV_RACK_OUT_COST_AMT
		, SUM(fact.SP_TRANSFER_OUT_RACKING_QTY)					as SP_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(fact.SP_MERCH_MARGIN_RETAIL_AMT) 					as SP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(fact.SP_DISCOUNT_TERMS_COST_AMT) 					as SP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
--		, SUM(fact.SP_RECEIPTS_ACTIVE_COST_AMT) 				as SP_RCPTS_ACTIVE_COST_AMT
--		, SUM(fact.SP_RECEIPTS_ACTIVE_QTY)						as SP_RCPTS_ACTIVE_UNITS
		, SUM(fact.SP_RECEIPTS_INACTIVE_COST_AMT) 				as SP_RCPTS_INACTIVE_COST_AMT
		, SUM(fact.SP_RECEIPTS_INACTIVE_QTY)					as SP_RCPTS_INACTIVE_UNITS
		, SUM(fact.SP_RECEIPTS_ACTIVE_COST_AMT + fact.SP_RECEIPTS_INACTIVE_COST_AMT) as SP_RCPTS_TOT_COST_AMT
		, SUM(fact.SP_RECEIPTS_ACTIVE_QTY + fact.SP_RECEIPTS_INACTIVE_QTY) as SP_RCPTS_TOT_UNITS
--        , SUM(fact.SP_RECEIPTS_RESERVE_COST_AMT)                as SP_RCPTS_RESERVE_COST_AMT
--        , SUM(fact.SP_RECEIPTS_RESERVE_QTY)                     as SP_RCPTS_RESERVE_UNITS
		-- Reclass
		, SUM(fact.SP_RECLASS_IN_COST_AMT) 						as SP_RECLASS_IN_COST_AMT
		, SUM(fact.SP_RECLASS_IN_QTY)							as SP_RECLASS_IN_UNITS
		, SUM(fact.SP_RECLASS_OUT_COST_AMT) 					as SP_RECLASS_OUT_COST_AMT
		, SUM(fact.SP_RECLASS_OUT_QTY)							as SP_RECLASS_OUT_UNITS
		, SUM(fact.SP_RECLASS_IN_COST_AMT + fact.SP_RECLASS_OUT_COST_AMT) as SP_RECLASS_TOT_COST_AMT
		, SUM(fact.SP_RECLASS_IN_QTY + fact.SP_RECLASS_OUT_QTY) as SP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(fact.SP_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as SP_RTV_ACTIVE_COST_AMT
		, SUM(fact.SP_RETURN_TO_VENDOR_ACTIVE_QTY)		        as SP_RTV_ACTIVE_UNITS
		, SUM(fact.SP_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as SP_RTV_INACTIVE_COST_AMT
		, SUM(fact.SP_RETURN_TO_VENDOR_INACTIVE_QTY)		    as SP_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(fact.SP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as SP_MOS_ACTIVE_COST_AMT
        , SUM(fact.SP_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as SP_MOS_ACTIVE_UNITS
        , SUM(fact.SP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as SP_MOS_INACTIVE_COST_AMT
        , SUM(fact.SP_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as SP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(fact.SP_VENDOR_FUNDS_COST_AMT)					as SP_VENDOR_FUNDS_COST_AMT
	-- QP Metrics
        -- Inventory
		, SUM(qp.QP_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as QP_BOP_ACTIVE_UNITS
		, SUM(qp.QP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as QP_BOP_ACTIVE_COST_AMT
		, SUM(qp.QP_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as QP_BOP_INACTIVE_UNITS
		, SUM(qp.QP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as QP_BOP_INACTIVE_COST_AMT
		, SUM(qp.QP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + qp.QP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as QP_BOP_TOT_COST_AMT
		, SUM(qp.QP_BEGINNING_OF_PERIOD_ACTIVE_QTY + qp.QP_BEGINNING_OF_PERIOD_INACTIVE_QTY) as QP_BOP_TOT_UNITS
		, SUM(qp.QP_ENDING_OF_PERIOD_ACTIVE_QTY) 				as QP_EOP_ACTIVE_UNITS
		, SUM(qp.QP_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as QP_EOP_ACTIVE_COST_AMT
		, SUM(qp.QP_ENDING_OF_PERIOD_INACTIVE_QTY) 			as QP_EOP_INACTIVE_UNITS
		, SUM(qp.QP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as QP_EOP_INACTIVE_COST_AMT
		, SUM(qp.QP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + qp.QP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as QP_EOP_TOT_COST_AMT
		, SUM(qp.QP_ENDING_OF_PERIOD_ACTIVE_QTY + qp.QP_ENDING_OF_PERIOD_INACTIVE_QTY) as QP_EOP_TOT_UNITS
		, SUM(qp.QP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY) as QP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, SUM(qp.QP_TRANSFER_IN_ACTIVE_COST_AMT)				as QP_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(qp.QP_TRANSFER_IN_ACTIVE_QTY)					as QP_TRANSFER_ACTIVE_IN_UNITS
		, SUM(qp.QP_TRANSFER_OUT_ACTIVE_COST_AMT)				as QP_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(qp.QP_TRANSFER_OUT_ACTIVE_QTY)					as QP_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(qp.QP_TRANSFER_IN_INACTIVE_COST_AMT)			as QP_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(qp.QP_TRANSFER_IN_INACTIVE_QTY)					as QP_TRANSFER_INACTIVE_IN_UNITS
		, SUM(qp.QP_TRANSFER_OUT_INACTIVE_COST_AMT)			as QP_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(qp.QP_TRANSFER_OUT_INACTIVE_QTY)				as QP_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(qp.QP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as QP_INV_MVMT_IN_DS_COST_AMT
		, SUM(qp.QP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 		as QP_INV_MVMT_IN_DS_UNITS
		, SUM(qp.QP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT) as QP_INV_MVMT_OUT_DS_COST_AMT
		, SUM(qp.QP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY) 		as QP_INV_MVMT_OUT_DS_UNITS
		, SUM(qp.QP_TRANSFER_IN_RACKING_COST_AMT + qp.QP_TRANSFER_IN_OTHER_COST_AMT + qp.QP_TRANSFER_IN_ACTIVE_COST_AMT + qp.QP_RECLASS_IN_COST_AMT + qp.QP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) 	as QP_INV_MVMT_IN_TOT_COST_AMT
		, SUM(qp.QP_TRANSFER_IN_RACKING_QTY + qp.QP_TRANSFER_IN_OTHER_QTY + qp.QP_TRANSFER_IN_ACTIVE_QTY + qp.QP_RECLASS_IN_QTY + qp.QP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) 							as QP_INV_MVMT_IN_TOT_UNITS
		, SUM(qp.QP_TRANSFER_OUT_RACKING_COST_AMT + qp.QP_TRANSFER_OUT_OTHER_COST_AMT + qp.QP_TRANSFER_OUT_ACTIVE_COST_AMT + qp.QP_RECLASS_OUT_COST_AMT + qp.QP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT + qp.QP_RETURN_TO_VENDOR_ACTIVE_COST_AMT) 	as QP_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(qp.QP_TRANSFER_OUT_RACKING_QTY + qp.QP_TRANSFER_OUT_OTHER_QTY + qp.QP_TRANSFER_OUT_ACTIVE_QTY + qp.QP_RECLASS_OUT_QTY + qp.QP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY + qp.QP_RETURN_TO_VENDOR_ACTIVE_QTY) 	as QP_INV_MVMT_OUT_TOT_UNITS 
		, SUM(qp.QP_TRANSFER_IN_OTHER_COST_AMT) 				as QP_INV_OTHER_IN_COST_AMT
		, SUM(qp.QP_TRANSFER_IN_OTHER_QTY)					as QP_INV_OTHER_IN_UNITS
		, SUM(qp.QP_TRANSFER_OUT_OTHER_COST_AMT) 				as QP_INV_OTHER_OUT_COST_AMT
		, SUM(qp.QP_TRANSFER_OUT_OTHER_QTY)					as QP_INV_OTHER_OUT_UNITS
		, SUM(qp.QP_TRANSFER_IN_RACKING_COST_AMT)				as QP_INV_RACK_IN_COST_AMT
		, SUM(qp.QP_TRANSFER_IN_RACKING_QTY)					as QP_INV_RACK_IN_UNITS
		, SUM(qp.QP_TRANSFER_OUT_RACKING_COST_AMT)			as QP_INV_RACK_OUT_COST_AMT
		, SUM(qp.QP_TRANSFER_OUT_RACKING_QTY)					as QP_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(qp.QP_MERCH_MARGIN_RETAIL_AMT) 					as QP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(qp.QP_DISCOUNT_TERMS_COST_AMT) 					as QP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, SUM(qp.QP_RECEIPTS_ACTIVE_COST_AMT) 				as QP_RCPTS_ACTIVE_COST_AMT
		, SUM(qp.QP_RECEIPTS_ACTIVE_QTY)						as QP_RCPTS_ACTIVE_UNITS
		, SUM(qp.QP_RECEIPTS_INACTIVE_COST_AMT) 				as QP_RCPTS_INACTIVE_COST_AMT
		, SUM(qp.QP_RECEIPTS_INACTIVE_QTY)					as QP_RCPTS_INACTIVE_UNITS
		, SUM(qp.QP_RECEIPTS_ACTIVE_COST_AMT + qp.QP_RECEIPTS_INACTIVE_COST_AMT) as QP_RCPTS_TOT_COST_AMT
		, SUM(qp.QP_RECEIPTS_ACTIVE_QTY + qp.QP_RECEIPTS_INACTIVE_QTY) as QP_RCPTS_TOT_UNITS
        , SUM(qp.QP_RECEIPTS_RESERVE_COST_AMT)                as QP_RCPTS_RESERVE_COST_AMT
        , SUM(qp.QP_RECEIPTS_RESERVE_QTY)                     as QP_RCPTS_RESERVE_UNITS
		-- Reclass
		, SUM(qp.QP_RECLASS_IN_COST_AMT) 						as QP_RECLASS_IN_COST_AMT
		, SUM(qp.QP_RECLASS_IN_QTY)							as QP_RECLASS_IN_UNITS
		, SUM(qp.QP_RECLASS_OUT_COST_AMT) 					as QP_RECLASS_OUT_COST_AMT
		, SUM(qp.QP_RECLASS_OUT_QTY)							as QP_RECLASS_OUT_UNITS
		, SUM(qp.QP_RECLASS_IN_COST_AMT + qp.QP_RECLASS_OUT_COST_AMT) as QP_RECLASS_TOT_COST_AMT
		, SUM(qp.QP_RECLASS_IN_QTY + qp.QP_RECLASS_OUT_QTY) as QP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(qp.QP_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as QP_RTV_ACTIVE_COST_AMT
		, SUM(qp.QP_RETURN_TO_VENDOR_ACTIVE_QTY)		        as QP_RTV_ACTIVE_UNITS
		, SUM(qp.QP_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as QP_RTV_INACTIVE_COST_AMT
		, SUM(qp.QP_RETURN_TO_VENDOR_INACTIVE_QTY)		    as QP_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(qp.QP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as QP_MOS_ACTIVE_COST_AMT
        , SUM(qp.QP_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as QP_MOS_ACTIVE_UNITS
        , SUM(qp.QP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as QP_MOS_INACTIVE_COST_AMT
        , SUM(qp.QP_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as QP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(qp.QP_VENDOR_FUNDS_COST_AMT)					as QP_VENDOR_FUNDS_COST_AMT
    -- TY Metrics
	    -- Inventory
		, SUM(fact.TY_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as TY_BOP_ACTIVE_UNITS
		, SUM(fact.TY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as TY_BOP_ACTIVE_COST_AMT
		, SUM(fact.TY_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as TY_BOP_INACTIVE_UNITS
		, SUM(fact.TY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as TY_BOP_INACTIVE_COST_AMT
		, SUM(fact.TY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + fact.TY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as TY_BOP_TOT_COST_AMT
		, SUM(fact.TY_BEGINNING_OF_PERIOD_ACTIVE_QTY + fact.TY_BEGINNING_OF_PERIOD_INACTIVE_QTY) as TY_BOP_TOT_UNITS
		, SUM(fact.TY_ENDING_OF_PERIOD_ACTIVE_QTY) 				as TY_EOP_ACTIVE_UNITS
		, SUM(fact.TY_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as TY_EOP_ACTIVE_COST_AMT
		, SUM(fact.TY_ENDING_OF_PERIOD_INACTIVE_QTY) 			as TY_EOP_INACTIVE_UNITS
		, SUM(fact.TY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as TY_EOP_INACTIVE_COST_AMT
		, SUM(fact.TY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + fact.TY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as TY_EOP_TOT_COST_AMT
		, SUM(fact.TY_ENDING_OF_PERIOD_ACTIVE_QTY + fact.TY_ENDING_OF_PERIOD_INACTIVE_QTY) as TY_EOP_TOT_UNITS
		-- Inventory Movement
		, SUM(fact.TY_TRANSFER_IN_ACTIVE_COST_AMT)				as TY_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(fact.TY_TRANSFER_IN_ACTIVE_QTY)					as TY_TRANSFER_ACTIVE_IN_UNITS
		, SUM(fact.TY_TRANSFER_OUT_ACTIVE_COST_AMT)				as TY_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(fact.TY_TRANSFER_OUT_ACTIVE_QTY)					as TY_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(fact.TY_TRANSFER_IN_INACTIVE_COST_AMT)			as TY_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(fact.TY_TRANSFER_IN_INACTIVE_QTY)					as TY_TRANSFER_INACTIVE_IN_UNITS
		, SUM(fact.TY_TRANSFER_OUT_INACTIVE_COST_AMT)			as TY_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(fact.TY_TRANSFER_OUT_INACTIVE_QTY)				as TY_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(fact.TY_TRANSFER_IN_RACKING_COST_AMT + fact.TY_TRANSFER_IN_OTHER_COST_AMT + fact.TY_TRANSFER_IN_ACTIVE_COST_AMT + fact.TY_RECLASS_IN_COST_AMT) as TY_INV_MVMT_IN_TOT_COST_AMT
		, SUM(fact.TY_TRANSFER_IN_RACKING_QTY + fact.TY_TRANSFER_IN_OTHER_QTY + fact.TY_TRANSFER_IN_ACTIVE_QTY + fact.TY_RECLASS_IN_QTY) as TY_INV_MVMT_IN_TOT_UNITS
		, SUM(fact.TY_TRANSFER_OUT_RACKING_COST_AMT + fact.TY_TRANSFER_OUT_OTHER_COST_AMT + fact.TY_TRANSFER_OUT_ACTIVE_COST_AMT + fact.TY_RECLASS_OUT_COST_AMT + fact.TY_RETURN_TO_VENDOR_ACTIVE_COST_AMT) as TY_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(fact.TY_TRANSFER_OUT_RACKING_QTY + fact.TY_TRANSFER_OUT_OTHER_QTY + fact.TY_TRANSFER_OUT_ACTIVE_QTY + fact.TY_RECLASS_OUT_QTY + fact.TY_RETURN_TO_VENDOR_ACTIVE_QTY) as TY_INV_MVMT_OUT_TOT_UNITS 
		, SUM(fact.TY_TRANSFER_IN_OTHER_COST_AMT) 				as TY_INV_OTHER_IN_COST_AMT
		, SUM(fact.TY_TRANSFER_IN_OTHER_QTY)					as TY_INV_OTHER_IN_UNITS
		, SUM(fact.TY_TRANSFER_OUT_OTHER_COST_AMT) 				as TY_INV_OTHER_OUT_COST_AMT
		, SUM(fact.TY_TRANSFER_OUT_OTHER_QTY)					as TY_INV_OTHER_OUT_UNITS
		, SUM(fact.TY_TRANSFER_IN_RACKING_COST_AMT)				as TY_INV_RACK_IN_COST_AMT
		, SUM(fact.TY_TRANSFER_IN_RACKING_QTY)					as TY_INV_RACK_IN_UNITS
		, SUM(fact.TY_TRANSFER_OUT_RACKING_COST_AMT)			as TY_INV_RACK_OUT_COST_AMT
		, SUM(fact.TY_TRANSFER_OUT_RACKING_QTY)					as TY_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(fact.TY_MERCH_MARGIN_RETAIL_AMT) 					as TY_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(fact.TY_DISCOUNT_TERMS_COST_AMT) 					as TY_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, SUM(fact.TY_RECEIPTS_ACTIVE_COST_AMT) 				as TY_RCPTS_ACTIVE_COST_AMT
		, SUM(fact.TY_RECEIPTS_ACTIVE_QTY)						as TY_RCPTS_ACTIVE_UNITS
		, SUM(fact.TY_RECEIPTS_INACTIVE_COST_AMT) 				as TY_RCPTS_INACTIVE_COST_AMT
		, SUM(fact.TY_RECEIPTS_INACTIVE_QTY)					as TY_RCPTS_INACTIVE_UNITS
		, SUM(fact.TY_RECEIPTS_ACTIVE_COST_AMT + fact.TY_RECEIPTS_INACTIVE_COST_AMT) as TY_RCPTS_TOT_COST_AMT
		, SUM(fact.TY_RECEIPTS_ACTIVE_QTY + fact.TY_RECEIPTS_INACTIVE_QTY) as TY_RCPTS_TOT_UNITS
		-- Reclass
		, SUM(fact.TY_RECLASS_IN_COST_AMT) 						as TY_RECLASS_IN_COST_AMT
		, SUM(fact.TY_RECLASS_IN_QTY)							as TY_RECLASS_IN_UNITS
		, SUM(fact.TY_RECLASS_OUT_COST_AMT) 					as TY_RECLASS_OUT_COST_AMT
		, SUM(fact.TY_RECLASS_OUT_QTY)							as TY_RECLASS_OUT_UNITS
		, SUM(fact.TY_RECLASS_IN_COST_AMT + fact.TY_RECLASS_OUT_COST_AMT) as TY_RECLASS_TOT_COST_AMT
		, SUM(fact.TY_RECLASS_IN_QTY + fact.TY_RECLASS_OUT_QTY) as TY_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(fact.TY_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as TY_RTV_ACTIVE_COST_AMT
		, SUM(fact.TY_RETURN_TO_VENDOR_ACTIVE_QTY)		        as TY_RTV_ACTIVE_UNITS
		, SUM(fact.TY_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as TY_RTV_INACTIVE_COST_AMT
		, SUM(fact.TY_RETURN_TO_VENDOR_INACTIVE_QTY)		    as TY_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(fact.TY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as TY_MOS_ACTIVE_COST_AMT
        , SUM(fact.TY_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as TY_MOS_ACTIVE_UNITS
        , SUM(fact.TY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as TY_MOS_INACTIVE_COST_AMT
        , SUM(fact.TY_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as TY_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(fact.TY_VENDOR_FUNDS_COST_AMT)					as TY_VENDOR_FUNDS_COST_AMT
	-- LY Metrics
        -- Inventory
		, SUM(fact.LY_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as LY_BOP_ACTIVE_UNITS
		, SUM(fact.LY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as LY_BOP_ACTIVE_COST_AMT
		, SUM(fact.LY_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as LY_BOP_INACTIVE_UNITS
		, SUM(fact.LY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as LY_BOP_INACTIVE_COST_AMT
		, SUM(fact.LY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + fact.LY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as LY_BOP_TOT_COST_AMT
		, SUM(fact.LY_BEGINNING_OF_PERIOD_ACTIVE_QTY + fact.LY_BEGINNING_OF_PERIOD_INACTIVE_QTY) as LY_BOP_TOT_UNITS
		, SUM(fact.LY_ENDING_OF_PERIOD_ACTIVE_QTY) 				as LY_EOP_ACTIVE_UNITS
		, SUM(fact.LY_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as LY_EOP_ACTIVE_COST_AMT
		, SUM(fact.LY_ENDING_OF_PERIOD_INACTIVE_QTY) 			as LY_EOP_INACTIVE_UNITS
		, SUM(fact.LY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as LY_EOP_INACTIVE_COST_AMT
		, SUM(fact.LY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + fact.LY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as LY_EOP_TOT_COST_AMT
		, SUM(fact.LY_ENDING_OF_PERIOD_ACTIVE_QTY + fact.LY_ENDING_OF_PERIOD_INACTIVE_QTY) as LY_EOP_TOT_UNITS
		-- Inventory Movement
		, SUM(fact.LY_TRANSFER_IN_ACTIVE_COST_AMT)				as LY_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(fact.LY_TRANSFER_IN_ACTIVE_QTY)					as LY_TRANSFER_ACTIVE_IN_UNITS
		, SUM(fact.LY_TRANSFER_OUT_ACTIVE_COST_AMT)				as LY_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(fact.LY_TRANSFER_OUT_ACTIVE_QTY)					as LY_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(fact.LY_TRANSFER_IN_INACTIVE_COST_AMT)			as LY_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(fact.LY_TRANSFER_IN_INACTIVE_QTY)					as LY_TRANSFER_INACTIVE_IN_UNITS
		, SUM(fact.LY_TRANSFER_OUT_INACTIVE_COST_AMT)			as LY_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(fact.LY_TRANSFER_OUT_INACTIVE_QTY)				as LY_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(fact.LY_TRANSFER_IN_RACKING_COST_AMT + fact.LY_TRANSFER_IN_OTHER_COST_AMT + fact.LY_TRANSFER_IN_ACTIVE_COST_AMT + fact.LY_RECLASS_IN_COST_AMT) as LY_INV_MVMT_IN_TOT_COST_AMT
		, SUM(fact.LY_TRANSFER_IN_RACKING_QTY + fact.LY_TRANSFER_IN_OTHER_QTY + fact.LY_TRANSFER_IN_ACTIVE_QTY + fact.LY_RECLASS_IN_QTY) as LY_INV_MVMT_IN_TOT_UNITS
		, SUM(fact.LY_TRANSFER_OUT_RACKING_COST_AMT + fact.LY_TRANSFER_OUT_OTHER_COST_AMT + fact.LY_TRANSFER_OUT_ACTIVE_COST_AMT + fact.LY_RECLASS_OUT_COST_AMT + fact.LY_RETURN_TO_VENDOR_ACTIVE_COST_AMT) as LY_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(fact.LY_TRANSFER_OUT_RACKING_QTY + fact.LY_TRANSFER_OUT_OTHER_QTY + fact.LY_TRANSFER_OUT_ACTIVE_QTY + fact.LY_RECLASS_OUT_QTY + fact.LY_RETURN_TO_VENDOR_ACTIVE_QTY) as LY_INV_MVMT_OUT_TOT_UNITS 
		, SUM(fact.LY_TRANSFER_IN_OTHER_COST_AMT) 				as LY_INV_OTHER_IN_COST_AMT
		, SUM(fact.LY_TRANSFER_IN_OTHER_QTY)					as LY_INV_OTHER_IN_UNITS
		, SUM(fact.LY_TRANSFER_OUT_OTHER_COST_AMT) 				as LY_INV_OTHER_OUT_COST_AMT
		, SUM(fact.LY_TRANSFER_OUT_OTHER_QTY)					as LY_INV_OTHER_OUT_UNITS
		, SUM(fact.LY_TRANSFER_IN_RACKING_COST_AMT)				as LY_INV_RACK_IN_COST_AMT
		, SUM(fact.LY_TRANSFER_IN_RACKING_QTY)					as LY_INV_RACK_IN_UNITS
		, SUM(fact.LY_TRANSFER_OUT_RACKING_COST_AMT)			as LY_INV_RACK_OUT_COST_AMT
		, SUM(fact.LY_TRANSFER_OUT_RACKING_QTY)					as LY_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(fact.LY_MERCH_MARGIN_RETAIL_AMT) 					as LY_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(fact.LY_DISCOUNT_TERMS_COST_AMT) 					as LY_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, SUM(fact.LY_RECEIPTS_ACTIVE_COST_AMT) 				as LY_RCPTS_ACTIVE_COST_AMT
		, SUM(fact.LY_RECEIPTS_ACTIVE_QTY)						as LY_RCPTS_ACTIVE_UNITS
		, SUM(fact.LY_RECEIPTS_INACTIVE_COST_AMT) 				as LY_RCPTS_INACTIVE_COST_AMT
		, SUM(fact.LY_RECEIPTS_INACTIVE_QTY)					as LY_RCPTS_INACTIVE_UNITS
		, SUM(fact.LY_RECEIPTS_ACTIVE_COST_AMT + fact.LY_RECEIPTS_INACTIVE_COST_AMT) as LY_RCPTS_TOT_COST_AMT
		, SUM(fact.LY_RECEIPTS_ACTIVE_QTY + fact.LY_RECEIPTS_INACTIVE_QTY) as LY_RCPTS_TOT_UNITS
		-- Reclass
		, SUM(fact.LY_RECLASS_IN_COST_AMT) 						as LY_RECLASS_IN_COST_AMT
		, SUM(fact.LY_RECLASS_IN_QTY)							as LY_RECLASS_IN_UNITS
		, SUM(fact.LY_RECLASS_OUT_COST_AMT) 					as LY_RECLASS_OUT_COST_AMT
		, SUM(fact.LY_RECLASS_OUT_QTY)							as LY_RECLASS_OUT_UNITS
		, SUM(fact.LY_RECLASS_IN_COST_AMT + fact.LY_RECLASS_OUT_COST_AMT) as LY_RECLASS_TOT_COST_AMT
		, SUM(fact.LY_RECLASS_IN_QTY + fact.LY_RECLASS_OUT_QTY) as LY_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(fact.LY_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as LY_RTV_ACTIVE_COST_AMT
		, SUM(fact.LY_RETURN_TO_VENDOR_ACTIVE_QTY)		        as LY_RTV_ACTIVE_UNITS
		, SUM(fact.LY_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as LY_RTV_INACTIVE_COST_AMT
		, SUM(fact.LY_RETURN_TO_VENDOR_INACTIVE_QTY)		    as LY_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(fact.LY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as LY_MOS_ACTIVE_COST_AMT
        , SUM(fact.LY_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as LY_MOS_ACTIVE_UNITS
        , SUM(fact.LY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as LY_MOS_INACTIVE_COST_AMT
        , SUM(fact.LY_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as LY_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(fact.LY_VENDOR_FUNDS_COST_AMT)					as LY_VENDOR_FUNDS_COST_AMT
	-- LY TRUE DAY Metrics - NEW 01.25.2024
        -- Inventory
		, SUM(fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_QTY) 			as LY_TRUEDAY_BOP_ACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT) 		as LY_TRUEDAY_BOP_ACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_QTY) 		as LY_TRUEDAY_BOP_INACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) 	as LY_TRUEDAY_BOP_INACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT  + fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as LY_TRUEDAY_BOP_TOT_COST_AMT
		, SUM(fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_QTY + fact.LY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_QTY) as LY_TRUEDAY_BOP_TOT_UNITS
		, SUM(fact.LY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_QTY) 				as LY_TRUEDAY_EOP_ACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_COST_AMT) 		as LY_TRUEDAY_EOP_ACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_QTY) 			as LY_TRUEDAY_EOP_INACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) 		as LY_TRUEDAY_EOP_INACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + fact.LY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as LY_TRUEDAY_EOP_TOT_COST_AMT
		, SUM(fact.LY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_QTY + fact.LY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_QTY) as LY_TRUEDAY_EOP_TOT_UNITS
		-- Inventory Movement
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_ACTIVE_COST_AMT)				as LY_TRUEDAY_TRANSFER_ACTIVE_IN_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_ACTIVE_QTY)					as LY_TRUEDAY_TRANSFER_ACTIVE_IN_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_ACTIVE_COST_AMT)				as LY_TRUEDAY_TRANSFER_ACTIVE_OUT_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_ACTIVE_QTY)					as LY_TRUEDAY_TRANSFER_ACTIVE_OUT_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_INACTIVE_COST_AMT)			as LY_TRUEDAY_TRANSFER_INACTIVE_IN_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_INACTIVE_QTY)					as LY_TRUEDAY_TRANSFER_INACTIVE_IN_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_INACTIVE_COST_AMT)			as LY_TRUEDAY_TRANSFER_INACTIVE_OUT_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_INACTIVE_QTY)				as LY_TRUEDAY_TRANSFER_INACTIVE_OUT_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_RACKING_COST_AMT + fact.LY_TRUEDAY_TRANSFER_IN_OTHER_COST_AMT + fact.LY_TRUEDAY_TRANSFER_IN_ACTIVE_COST_AMT + fact.LY_TRUEDAY_RECLASS_IN_COST_AMT) as LY_TRUEDAY_INV_MVMT_IN_TOT_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_RACKING_QTY + fact.LY_TRUEDAY_TRANSFER_IN_OTHER_QTY + fact.LY_TRUEDAY_TRANSFER_IN_ACTIVE_QTY + fact.LY_TRUEDAY_RECLASS_IN_QTY) as LY_TRUEDAY_INV_MVMT_IN_TOT_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_RACKING_COST_AMT + fact.LY_TRUEDAY_TRANSFER_OUT_OTHER_COST_AMT + fact.LY_TRUEDAY_TRANSFER_OUT_ACTIVE_COST_AMT + fact.LY_TRUEDAY_RECLASS_OUT_COST_AMT + fact.LY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_COST_AMT) as LY_TRUEDAY_INV_MVMT_OUT_TOT_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_RACKING_QTY + fact.LY_TRUEDAY_TRANSFER_OUT_OTHER_QTY + fact.LY_TRUEDAY_TRANSFER_OUT_ACTIVE_QTY + fact.LY_TRUEDAY_RECLASS_OUT_QTY + fact.LY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_QTY) as LY_TRUEDAY_INV_MVMT_OUT_TOT_UNITS 
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_OTHER_COST_AMT) 				as LY_TRUEDAY_INV_OTHER_IN_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_OTHER_QTY)					as LY_TRUEDAY_INV_OTHER_IN_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_OTHER_COST_AMT) 				as LY_TRUEDAY_INV_OTHER_OUT_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_OTHER_QTY)					as LY_TRUEDAY_INV_OTHER_OUT_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_RACKING_COST_AMT)				as LY_TRUEDAY_INV_RACK_IN_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_IN_RACKING_QTY)					as LY_TRUEDAY_INV_RACK_IN_UNITS
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_RACKING_COST_AMT)			as LY_TRUEDAY_INV_RACK_OUT_COST_AMT
		, SUM(fact.LY_TRUEDAY_TRANSFER_OUT_RACKING_QTY)					as LY_TRUEDAY_INV_RACK_OUT_UNITS
		-- Margin
		, SUM(fact.LY_TRUEDAY_MERCH_MARGIN_RETAIL_AMT) 					as LY_TRUEDAY_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, SUM(fact.LY_TRUEDAY_DISCOUNT_TERMS_COST_AMT) 					as LY_TRUEDAY_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, SUM(fact.LY_TRUEDAY_RECEIPTS_ACTIVE_COST_AMT) 				as LY_TRUEDAY_RCPTS_ACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_RECEIPTS_ACTIVE_QTY)						as LY_TRUEDAY_RCPTS_ACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_RECEIPTS_INACTIVE_COST_AMT) 				as LY_TRUEDAY_RCPTS_INACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_RECEIPTS_INACTIVE_QTY)					as LY_TRUEDAY_RCPTS_INACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_RECEIPTS_ACTIVE_COST_AMT + fact.LY_TRUEDAY_RECEIPTS_INACTIVE_COST_AMT) as LY_TRUEDAY_RCPTS_TOT_COST_AMT
		, SUM(fact.LY_TRUEDAY_RECEIPTS_ACTIVE_QTY + fact.LY_TRUEDAY_RECEIPTS_INACTIVE_QTY) as LY_TRUEDAY_RCPTS_TOT_UNITS
		-- Reclass
		, SUM(fact.LY_TRUEDAY_RECLASS_IN_COST_AMT) 						as LY_TRUEDAY_RECLASS_IN_COST_AMT
		, SUM(fact.LY_TRUEDAY_RECLASS_IN_QTY)							as LY_TRUEDAY_RECLASS_IN_UNITS
		, SUM(fact.LY_TRUEDAY_RECLASS_OUT_COST_AMT) 					as LY_TRUEDAY_RECLASS_OUT_COST_AMT
		, SUM(fact.LY_TRUEDAY_RECLASS_OUT_QTY)							as LY_TRUEDAY_RECLASS_OUT_UNITS
		, SUM(fact.LY_TRUEDAY_RECLASS_IN_COST_AMT + fact.LY_TRUEDAY_RECLASS_OUT_COST_AMT) as LY_TRUEDAY_RECLASS_TOT_COST_AMT
		, SUM(fact.LY_TRUEDAY_RECLASS_IN_QTY + fact.LY_TRUEDAY_RECLASS_OUT_QTY) as LY_TRUEDAY_RECLASS_TOT_UNITS
		-- Return to Vendor
		, SUM(fact.LY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_COST_AMT)         as LY_TRUEDAY_RTV_ACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_QTY)		        as LY_TRUEDAY_RTV_ACTIVE_UNITS
		, SUM(fact.LY_TRUEDAY_RETURN_TO_VENDOR_INACTIVE_COST_AMT)       as LY_TRUEDAY_RTV_INACTIVE_COST_AMT
		, SUM(fact.LY_TRUEDAY_RETURN_TO_VENDOR_INACTIVE_QTY)		    as LY_TRUEDAY_RTV_INACTIVE_UNITS
        -- MOS
        , SUM(fact.LY_TRUEDAY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT)		as LY_TRUEDAY_MOS_ACTIVE_COST_AMT
        , SUM(fact.LY_TRUEDAY_MARK_OUT_OF_STOCK_ACTIVE_QTY)				as LY_TRUEDAY_MOS_ACTIVE_UNITS
        , SUM(fact.LY_TRUEDAY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT)		as LY_TRUEDAY_MOS_INACTIVE_COST_AMT
        , SUM(fact.LY_TRUEDAY_MARK_OUT_OF_STOCK_INACTIVE_QTY)			as LY_TRUEDAY_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, SUM(fact.LY_TRUEDAY_VENDOR_FUNDS_COST_AMT)					as LY_TRUEDAY_VENDOR_FUNDS_COST_AMT
	FROM PRD_NAP_VWS.MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT fact
    JOIN MERCH_HIERARCHY_LKUP mch
        ON fact.DEPT_NUM = mch.DEPT_NUM
    JOIN COUNTRY_LKUP bc
        ON fact.BANNER_COUNTRY_NUM = bc.BANNER_COUNTRY_NUM
        AND bc.CHANNEL_NUM = 0
    JOIN CAL_LKUP tme
        ON fact.WEEK_NUM = tme.WEEK_NUM
	JOIN FULFILL_TYPE_LKUP ft
		ON fact.FULFILL_TYPE_NUM = ft.FULFILL_TYPE_NUM
	LEFT JOIN PRD_NAP_VWS.MFP_COST_PLAN_QTR_BANNER_COUNTRY_FACT qp 
		ON qp.DEPT_NUM = fact.DEPT_NUM 
		AND qp.WEEK_NUM = fact.WEEK_NUM 
		AND qp.BANNER_COUNTRY_NUM = fact.BANNER_COUNTRY_NUM 
		AND qp.FULFILL_TYPE_NUM = fact.FULFILL_TYPE_NUM 
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
)
WITH DATA
PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER_COUNTRY_NUM, FULFILL_TYPE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER_COUNTRY_NUM, FULFILL_TYPE_NUM)
	,COLUMN (DEPT_NUM, WEEK_NUM, BANNER_COUNTRY_NUM, FULFILL_TYPE_NUM)
		ON BANNER_COUNTRY;

-- New 3/7 -- Added new logic for banner/country metrics
CREATE MULTISET VOLATILE TABLE FINAL_BASELINE_HEADER
AS (
	SELECT DISTINCT
		TRIM(COALESCE(bc.DEPARTMENT_LABEL, ch.DEPARTMENT_LABEL, ci.DEPARTMENT_LABEL)) AS DEPARTMENT_LABEL
	    , TRIM(COALESCE(bc.DEPT_NUM, ch.DEPT_NUM, ci.DEPT_NUM)) AS DEPT_NUM
	    , TRIM(COALESCE(bc.WEEK_454_LABEL, ch.WEEK_454_LABEL, ci.WEEK_454_LABEL)) AS WEEK_454_LABEL
	    , TRIM(COALESCE(bc.WEEK_NUM, ch.WEEK_NUM, ci.WEEK_NUM)) AS WEEK_NUM
	    , TRIM(COALESCE(bc.BANNER_COUNTRY, ch.BANNER_COUNTRY, ci.BANNER_COUNTRY)) AS BANNER_COUNTRY 
	    , TRIM(COALESCE(bc.BANNER, ch.BANNER, ci.BANNER)) AS BANNER 
	    , TRIM(COALESCE(bc.COUNTRY, ch.COUNTRY, ci.COUNTRY)) AS COUNTRY 
	    , TRIM(COALESCE(bc.BANNER_COUNTRY_NUM, ch.BANNER_COUNTRY_NUM, ci.BANNER_COUNTRY_NUM)) AS BANNER_COUNTRY_NUM 
	    , TRIM(COALESCE(bc.CHANNEL_NUM, ch.CHANNEL_NUM, ci.CHANNEL_NUM)) AS CHANNEL_NUM
	    , TRIM(COALESCE(bc.CHANNEL_LABEL, ch.CHANNEL, ci.CHANNEL)) AS CHANNEL
	    , TRIM(COALESCE(bc.FULFILL_TYPE_NUM, ch.FULFILL_TYPE_NUM, ci.FULFILL_TYPE_NUM)) AS FULFILL_TYPE_NUM
		, TRIM(COALESCE(bc.FULFILL_TYPE_DESC, ch.FULFILL_TYPE_DESC, ci.FULFILL_TYPE_DESC)) AS FULFILL_TYPE_DESC
	    , TRIM(COALESCE(bc.SUBDIVISION, ch.SUBDIVISION, ci.SUBDIVISION)) AS SUBDIVISION
	    , TRIM(COALESCE(bc.DIVISION, ch.DIVISION, ci.DIVISION)) AS DIVISION
	   	, TRIM(COALESCE(bc."MONTH", ch."MONTH", ci."MONTH")) AS "MONTH"
	    , TRIM(COALESCE(bc.QUARTER, ch.QUARTER, ci.QUARTER)) AS QUARTER
	    , TRIM(COALESCE(bc.QUARTER_NUM, ch.QUARTER_NUM, ci.QUARTER_NUM)) AS QUARTER_NUM
	    , TRIM(COALESCE(bc.HALF, ch.HALF, ci.HALF)) AS HALF
	    , TRIM(COALESCE(bc."YEAR", ch."YEAR", ci."YEAR")) AS "YEAR"
		, CAST(COALESCE(bc.WEEK_END_DAY_DATE, ch.WEEK_END_DAY_DATE, ci.WEEK_END_DAY_DATE) AS DATE FORMAT 'YYYY-MM-DD') AS WEEK_END_DAY_DATE
	FROM BANNER_COUNTRY bc	
	FULL OUTER JOIN CHANNEL ch 
		ON bc.DEPT_NUM = ch.DEPT_NUM
			AND bc.WEEK_NUM = ch.WEEK_NUM
			AND bc.BANNER_COUNTRY_NUM = ch.BANNER_COUNTRY_NUM
			AND bc.FULFILL_TYPE_NUM = ch.FULFILL_TYPE_NUM 
			AND bc.CHANNEL_NUM = ch.CHANNEL_NUM
	FULL OUTER JOIN CHANNEL_INV ci 
		ON bc.DEPT_NUM = ci.DEPT_NUM
			AND bc.WEEK_NUM = ci.WEEK_NUM
			AND bc.BANNER_COUNTRY_NUM = ci.BANNER_COUNTRY_NUM
			AND bc.FULFILL_TYPE_NUM = ci.FULFILL_TYPE_NUM 
			AND bc.CHANNEL_NUM = ci.CHANNEL_NUM
)
WITH DATA
PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
	,COLUMN (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
		ON FINAL_BASELINE_HEADER;

-- Final combined table	
	-- New 01.25.2024: Added TrueDay LY Fields
CREATE MULTISET VOLATILE TABLE FINAL_BASELINE
AS (
	SELECT
	    h.DEPARTMENT_LABEL
	    , h.DEPT_NUM
	    , h.WEEK_454_LABEL
	    , h.WEEK_NUM
	    , h.BANNER_COUNTRY 
	    , h.BANNER 
	    , h.COUNTRY 
	    , h.BANNER_COUNTRY_NUM 
	    , h.CHANNEL_NUM
	    , h.CHANNEL
	    , h.FULFILL_TYPE_NUM
		, h.FULFILL_TYPE_DESC
	    , h.SUBDIVISION
	    , h.DIVISION
	    , h."MONTH"
	    , h.QUARTER
	    , h.QUARTER_NUM
	    , h.HALF
	    , h."YEAR"
		, h.WEEK_END_DAY_DATE
	---- CHANNEL LEVEL DATA
		-- CP
		, ZEROIFNULL(CP_DEMAND_TOTAL_UNITS) AS CP_DEMAND_TOTAL_UNITS  
		, ZEROIFNULL(CP_DEMAND_TOTAL_RETAIL_AMT) AS CP_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(CP_GROSS_MARGIN_RETAIL_AMT) AS CP_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(CP_GROSS_SALES_RETAIL_AMT) AS CP_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(CP_GROSS_SALES_UNITS) AS CP_GROSS_SALES_UNITS 
		, ZEROIFNULL(CP_NET_SALES_RETAIL_AMT) AS CP_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(CP_NET_SALES_UNITS) AS CP_NET_SALES_UNITS 
		, ZEROIFNULL(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT
		, ZEROIFNULL(CP_NET_SALES_TRUNK_CLUB_RETAIL_AMT) AS CP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, ZEROIFNULL(CP_NET_SALES_TRUNK_CLUB_UNITS) AS CP_NET_SALES_TRUNK_CLUB_UNITS 
		, ZEROIFNULL(CP_RETURNS_RETAIL_AMT) AS CP_RETURNS_RETAIL_AMT
		, ZEROIFNULL(CP_RETURNS_UNITS) AS CP_RETURNS_UNITS 
		, ZEROIFNULL(CP_SHRINK_COST_AMT) AS CP_SHRINK_COST_AMT
		, ZEROIFNULL(CP_SHRINK_UNITS) AS CP_SHRINK_UNITS 
		-- OP
		, ZEROIFNULL(OP_DEMAND_TOTAL_UNITS) AS OP_DEMAND_TOTAL_UNITS 
		, ZEROIFNULL(OP_DEMAND_TOTAL_RETAIL_AMT) AS OP_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(OP_GROSS_MARGIN_RETAIL_AMT) AS OP_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(OP_GROSS_SALES_RETAIL_AMT) AS OP_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(OP_GROSS_SALES_UNITS) AS OP_GROSS_SALES_UNITS 
		, ZEROIFNULL(OP_NET_SALES_RETAIL_AMT) AS OP_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(OP_NET_SALES_UNITS) AS OP_NET_SALES_UNITS 
		, ZEROIFNULL(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT
		, ZEROIFNULL(OP_NET_SALES_TRUNK_CLUB_RETAIL_AMT) AS OP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, ZEROIFNULL(OP_NET_SALES_TRUNK_CLUB_UNITS) AS OP_NET_SALES_TRUNK_CLUB_UNITS 
		, ZEROIFNULL(OP_RETURNS_RETAIL_AMT) AS OP_RETURNS_RETAIL_AMT
		, ZEROIFNULL(OP_RETURNS_UNITS) AS OP_RETURNS_UNITS 
		, ZEROIFNULL(OP_SHRINK_COST_AMT) AS OP_SHRINK_COST_AMT
		, ZEROIFNULL(OP_SHRINK_UNITS) AS OP_SHRINK_UNITS 
		-- SP
		, ZEROIFNULL(SP_DEMAND_TOTAL_UNITS) AS SP_DEMAND_TOTAL_UNITS 
		, ZEROIFNULL(SP_DEMAND_TOTAL_RETAIL_AMT) AS SP_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(SP_GROSS_MARGIN_RETAIL_AMT) AS SP_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(SP_GROSS_SALES_RETAIL_AMT) AS SP_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(SP_GROSS_SALES_UNITS) AS SP_GROSS_SALES_UNITS 
		, ZEROIFNULL(SP_NET_SALES_RETAIL_AMT) AS SP_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(SP_NET_SALES_UNITS) AS SP_NET_SALES_UNITS 
		, ZEROIFNULL(SP_NET_SALES_COST_AMT) AS SP_NET_SALES_COST_AMT
		, ZEROIFNULL(SP_NET_SALES_TRUNK_CLUB_RETAIL_AMT) AS SP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, ZEROIFNULL(SP_NET_SALES_TRUNK_CLUB_UNITS) AS SP_NET_SALES_TRUNK_CLUB_UNITS 
		, ZEROIFNULL(SP_RETURNS_RETAIL_AMT) AS SP_RETURNS_RETAIL_AMT
		, ZEROIFNULL(SP_RETURNS_UNITS) AS SP_RETURNS_UNITS 
		, ZEROIFNULL(SP_SHRINK_COST_AMT) AS SP_SHRINK_COST_AMT
		, ZEROIFNULL(SP_SHRINK_UNITS) AS SP_SHRINK_UNITS 
		-- QP
		, ZEROIFNULL(QP_DEMAND_TOTAL_UNITS) AS QP_DEMAND_TOTAL_UNITS 
		, ZEROIFNULL(QP_DEMAND_TOTAL_RETAIL_AMT) AS QP_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(QP_GROSS_MARGIN_RETAIL_AMT) AS QP_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(QP_GROSS_SALES_RETAIL_AMT) AS QP_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(QP_GROSS_SALES_UNITS) AS QP_GROSS_SALES_UNITS 
		, ZEROIFNULL(QP_NET_SALES_RETAIL_AMT) AS QP_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(QP_NET_SALES_UNITS) AS QP_NET_SALES_UNITS 
		, ZEROIFNULL(QP_NET_SALES_COST_AMT) AS QP_NET_SALES_COST_AMT
		, ZEROIFNULL(QP_NET_SALES_TRUNK_CLUB_RETAIL_AMT) AS QP_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, ZEROIFNULL(QP_NET_SALES_TRUNK_CLUB_UNITS) AS QP_NET_SALES_TRUNK_CLUB_UNITS 
		, ZEROIFNULL(QP_RETURNS_RETAIL_AMT) AS QP_RETURNS_RETAIL_AMT
		, ZEROIFNULL(QP_RETURNS_UNITS) AS QP_RETURNS_UNITS 
		, ZEROIFNULL(QP_SHRINK_COST_AMT) AS QP_SHRINK_COST_AMT
		, ZEROIFNULL(QP_SHRINK_UNITS) AS QP_SHRINK_UNITS 
		-- TY ACTUALS
		, ZEROIFNULL(TY_DEMAND_TOTAL_UNITS) AS TY_DEMAND_TOTAL_UNITS 
		, ZEROIFNULL(TY_DEMAND_TOTAL_RETAIL_AMT) AS TY_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(TY_GROSS_MARGIN_RETAIL_AMT) AS TY_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(TY_GROSS_SALES_RETAIL_AMT) AS TY_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(TY_GROSS_SALES_UNITS) AS TY_GROSS_SALES_UNITS 
		, ZEROIFNULL(TY_NET_SALES_RETAIL_AMT) AS TY_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(TY_NET_SALES_UNITS) AS TY_NET_SALES_UNITS 
		, ZEROIFNULL(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT
		, ZEROIFNULL(TY_NET_SALES_TRUNK_CLUB_RETAIL_AMT) AS TY_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, ZEROIFNULL(TY_NET_SALES_TRUNK_CLUB_UNITS) AS TY_NET_SALES_TRUNK_CLUB_UNITS 
		, ZEROIFNULL(TY_RETURNS_RETAIL_AMT) AS TY_RETURNS_RETAIL_AMT
		, ZEROIFNULL(TY_RETURNS_UNITS) AS TY_RETURNS_UNITS 
		, ZEROIFNULL(TY_SHRINK_COST_AMT) AS TY_SHRINK_COST_AMT
		, ZEROIFNULL(TY_SHRINK_UNITS) AS TY_SHRINK_UNITS 
		-- LY ACTUALS
		, ZEROIFNULL(LY_DEMAND_TOTAL_UNITS) AS LY_DEMAND_TOTAL_UNITS 
		, ZEROIFNULL(LY_DEMAND_TOTAL_RETAIL_AMT) AS LY_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(LY_GROSS_MARGIN_RETAIL_AMT) AS LY_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(LY_GROSS_SALES_RETAIL_AMT) AS LY_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(LY_GROSS_SALES_UNITS) AS LY_GROSS_SALES_UNITS 
		, ZEROIFNULL(LY_NET_SALES_RETAIL_AMT) AS LY_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(LY_NET_SALES_UNITS) AS LY_NET_SALES_UNITS 
		, ZEROIFNULL(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
		, ZEROIFNULL(LY_NET_SALES_TRUNK_CLUB_RETAIL_AMT) AS LY_NET_SALES_TRUNK_CLUB_RETAIL_AMT
		, ZEROIFNULL(LY_NET_SALES_TRUNK_CLUB_UNITS) AS LY_NET_SALES_TRUNK_CLUB_UNITS 
		, ZEROIFNULL(LY_RETURNS_RETAIL_AMT) AS LY_RETURNS_RETAIL_AMT
		, ZEROIFNULL(LY_RETURNS_UNITS) AS LY_RETURNS_UNITS 
		, ZEROIFNULL(LY_SHRINK_COST_AMT) AS LY_SHRINK_COST_AMT
		, ZEROIFNULL(LY_SHRINK_UNITS) AS LY_SHRINK_UNITS 
		-- LY TRUEDAY ACTUALS - NEW 01.25.2024
		, ZEROIFNULL(LY_TRUEDAY_DEMAND_TOTAL_UNITS) AS LY_TRUEDAY_DEMAND_TOTAL_UNITS 
		, ZEROIFNULL(LY_TRUEDAY_DEMAND_TOTAL_RETAIL_AMT) AS LY_TRUEDAY_DEMAND_TOTAL_RETAIL_AMT
		, ZEROIFNULL(LY_TRUEDAY_GROSS_MARGIN_RETAIL_AMT) AS LY_TRUEDAY_GROSS_MARGIN_RETAIL_AMT
		, ZEROIFNULL(LY_TRUEDAY_GROSS_SALES_RETAIL_AMT) AS LY_TRUEDAY_GROSS_SALES_RETAIL_AMT
		, ZEROIFNULL(LY_TRUEDAY_GROSS_SALES_UNITS) AS LY_TRUEDAY_GROSS_SALES_UNITS 
		, ZEROIFNULL(LY_TRUEDAY_NET_SALES_RETAIL_AMT) AS LY_TRUEDAY_NET_SALES_RETAIL_AMT
		, ZEROIFNULL(LY_TRUEDAY_NET_SALES_UNITS) AS LY_TRUEDAY_NET_SALES_UNITS 
		, ZEROIFNULL(LY_TRUEDAY_NET_SALES_COST_AMT) AS LY_TRUEDAY_NET_SALES_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RETURNS_RETAIL_AMT) AS LY_TRUEDAY_RETURNS_RETAIL_AMT
		, ZEROIFNULL(LY_TRUEDAY_RETURNS_UNITS) AS LY_TRUEDAY_RETURNS_UNITS 
		, ZEROIFNULL(LY_TRUEDAY_SHRINK_COST_AMT) AS LY_TRUEDAY_SHRINK_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_SHRINK_UNITS) AS LY_TRUEDAY_SHRINK_UNITS 
	---- BANNER COUNTRY LEVEL DATA
		-- CP Metrics	
	    -- Inventory
		, ZEROIFNULL(CP_BOP_ACTIVE_UNITS) AS CP_BOP_ACTIVE_UNITS
		, ZEROIFNULL(CP_BOP_ACTIVE_COST_AMT) AS CP_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(CP_BOP_INACTIVE_UNITS) AS CP_BOP_INACTIVE_UNITS
		, ZEROIFNULL(CP_BOP_INACTIVE_COST_AMT) AS CP_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT
		, ZEROIFNULL(CP_BOP_TOT_UNITS) AS CP_BOP_TOT_UNITS
		, ZEROIFNULL(CP_EOP_ACTIVE_UNITS) AS CP_EOP_ACTIVE_UNITS
		, ZEROIFNULL(CP_EOP_ACTIVE_COST_AMT) AS CP_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(CP_EOP_INACTIVE_UNITS) AS CP_EOP_INACTIVE_UNITS
		, ZEROIFNULL(CP_EOP_INACTIVE_COST_AMT) AS CP_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(CP_EOP_TOT_COST_AMT) AS CP_EOP_TOT_COST_AMT
		, ZEROIFNULL(CP_EOP_TOT_UNITS) AS CP_EOP_TOT_UNITS
		, ZEROIFNULL(CP_BOP_ACTIVE_TGT_UNITS) AS CP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(CP_TRANSFER_ACTIVE_IN_COST_AMT) AS CP_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(CP_TRANSFER_ACTIVE_IN_UNITS) AS CP_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(CP_TRANSFER_ACTIVE_OUT_COST_AMT) AS CP_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(CP_TRANSFER_ACTIVE_OUT_UNITS) AS CP_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(CP_TRANSFER_INACTIVE_IN_COST_AMT) AS CP_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(CP_TRANSFER_INACTIVE_IN_UNITS) AS CP_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(CP_TRANSFER_INACTIVE_OUT_COST_AMT) AS CP_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(CP_TRANSFER_INACTIVE_OUT_UNITS) AS CP_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(CP_INV_MVMT_IN_DS_COST_AMT) AS CP_INV_MVMT_IN_DS_COST_AMT
		, ZEROIFNULL(CP_INV_MVMT_IN_DS_UNITS) AS CP_INV_MVMT_IN_DS_UNITS
		, ZEROIFNULL(CP_INV_MVMT_OUT_DS_COST_AMT) AS CP_INV_MVMT_OUT_DS_COST_AMT
		, ZEROIFNULL(CP_INV_MVMT_OUT_DS_UNITS) AS CP_INV_MVMT_OUT_DS_UNITS
		, ZEROIFNULL(CP_INV_MVMT_IN_TOT_COST_AMT) AS CP_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(CP_INV_MVMT_IN_TOT_UNITS) AS CP_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(CP_INV_MVMT_OUT_TOT_COST_AMT) AS CP_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(CP_INV_MVMT_OUT_TOT_UNITS) AS CP_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(CP_INV_OTHER_IN_COST_AMT) AS CP_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(CP_INV_OTHER_IN_UNITS) AS CP_INV_OTHER_IN_UNITS
		, ZEROIFNULL(CP_INV_OTHER_OUT_COST_AMT) AS CP_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(CP_INV_OTHER_OUT_UNITS) AS CP_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(CP_INV_RACK_IN_COST_AMT) AS CP_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(CP_INV_RACK_IN_UNITS) AS CP_INV_RACK_IN_UNITS
		, ZEROIFNULL(CP_INV_RACK_OUT_COST_AMT) AS CP_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(CP_INV_RACK_OUT_UNITS) AS CP_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(CP_MERCH_MARGIN_AMT) AS CP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(CP_INVOICE_PAYMENT_TERMS_COST_AMT) AS CP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(CP_RCPTS_ACTIVE_COST_AMT) AS CP_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(CP_RCPTS_ACTIVE_UNITS) AS CP_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(CP_RCPTS_INACTIVE_COST_AMT) AS CP_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(CP_RCPTS_INACTIVE_UNITS) AS CP_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(CP_RCPTS_TOT_COST_AMT) AS CP_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(CP_RCPTS_TOT_UNITS) AS CP_RCPTS_TOT_UNITS
	    , ZEROIFNULL(CP_RCPTS_RESERVE_COST_AMT) AS CP_RCPTS_RESERVE_COST_AMT
	    , ZEROIFNULL(CP_RCPTS_RESERVE_UNITS) AS CP_RCPTS_RESERVE_UNITS
		-- Recls
		, ZEROIFNULL(CP_RECLASS_IN_COST_AMT) AS CP_RECLASS_IN_COST_AMT
		, ZEROIFNULL(CP_RECLASS_IN_UNITS) AS CP_RECLASS_IN_UNITS
		, ZEROIFNULL(CP_RECLASS_OUT_COST_AMT) AS CP_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(CP_RECLASS_OUT_UNITS) AS CP_RECLASS_OUT_UNITS
		, ZEROIFNULL(CP_RECLASS_TOT_COST_AMT) AS CP_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(CP_RECLASS_TOT_UNITS) AS CP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(CP_RTV_ACTIVE_COST_AMT) AS CP_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(CP_RTV_ACTIVE_UNITS) AS CP_RTV_ACTIVE_UNITS
		, ZEROIFNULL(CP_RTV_INACTIVE_COST_AMT) AS CP_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(CP_RTV_INACTIVE_UNITS) AS CP_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(CP_MOS_ACTIVE_COST_AMT) AS CP_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(CP_MOS_ACTIVE_UNITS) AS CP_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(CP_MOS_INACTIVE_COST_AMT) AS CP_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(CP_MOS_INACTIVE_UNITS) AS CP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(CP_VENDOR_FUNDS_COST_AMT) AS CP_VENDOR_FUNDS_COST_AMT
	-- OP Metrics
	    -- Inventory
		, ZEROIFNULL(OP_BOP_ACTIVE_UNITS) AS OP_BOP_ACTIVE_UNITS
		, ZEROIFNULL(OP_BOP_ACTIVE_COST_AMT) AS OP_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(OP_BOP_INACTIVE_UNITS) AS OP_BOP_INACTIVE_UNITS
		, ZEROIFNULL(OP_BOP_INACTIVE_COST_AMT) AS OP_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT
		, ZEROIFNULL(OP_BOP_TOT_UNITS) AS OP_BOP_TOT_UNITS
		, ZEROIFNULL(OP_EOP_ACTIVE_UNITS) AS OP_EOP_ACTIVE_UNITS
		, ZEROIFNULL(OP_EOP_ACTIVE_COST_AMT) AS OP_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(OP_EOP_INACTIVE_UNITS) AS OP_EOP_INACTIVE_UNITS
		, ZEROIFNULL(OP_EOP_INACTIVE_COST_AMT) AS OP_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(OP_EOP_TOT_COST_AMT) AS OP_EOP_TOT_COST_AMT
		, ZEROIFNULL(OP_EOP_TOT_UNITS) AS OP_EOP_TOT_UNITS
		, ZEROIFNULL(OP_BOP_ACTIVE_TGT_UNITS) AS OP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(OP_TRANSFER_ACTIVE_IN_COST_AMT) AS OP_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(OP_TRANSFER_ACTIVE_IN_UNITS) AS OP_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(OP_TRANSFER_ACTIVE_OUT_COST_AMT) AS OP_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(OP_TRANSFER_ACTIVE_OUT_UNITS) AS OP_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(OP_TRANSFER_INACTIVE_IN_COST_AMT) AS OP_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(OP_TRANSFER_INACTIVE_IN_UNITS) AS OP_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(OP_TRANSFER_INACTIVE_OUT_COST_AMT) AS OP_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(OP_TRANSFER_INACTIVE_OUT_UNITS) AS OP_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(OP_INV_MVMT_IN_DS_COST_AMT) AS OP_INV_MVMT_IN_DS_COST_AMT
		, ZEROIFNULL(OP_INV_MVMT_IN_DS_UNITS) AS OP_INV_MVMT_IN_DS_UNITS
		, ZEROIFNULL(OP_INV_MVMT_OUT_DS_COST_AMT) AS OP_INV_MVMT_OUT_DS_COST_AMT
		, ZEROIFNULL(OP_INV_MVMT_OUT_DS_UNITS) AS OP_INV_MVMT_OUT_DS_UNITS
		, ZEROIFNULL(OP_INV_MVMT_IN_TOT_COST_AMT) AS OP_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(OP_INV_MVMT_IN_TOT_UNITS) AS OP_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(OP_INV_MVMT_OUT_TOT_COST_AMT) AS OP_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(OP_INV_MVMT_OUT_TOT_UNITS) AS OP_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(OP_INV_OTHER_IN_COST_AMT) AS OP_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(OP_INV_OTHER_IN_UNITS) AS OP_INV_OTHER_IN_UNITS
		, ZEROIFNULL(OP_INV_OTHER_OUT_COST_AMT) AS OP_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(OP_INV_OTHER_OUT_UNITS) AS OP_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(OP_INV_RACK_IN_COST_AMT) AS OP_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(OP_INV_RACK_IN_UNITS) AS OP_INV_RACK_IN_UNITS
		, ZEROIFNULL(OP_INV_RACK_OUT_COST_AMT) AS OP_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(OP_INV_RACK_OUT_UNITS) AS OP_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(OP_MERCH_MARGIN_AMT) AS OP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(OP_INVOICE_PAYMENT_TERMS_COST_AMT) AS OP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(OP_RCPTS_ACTIVE_COST_AMT) AS OP_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(OP_RCPTS_ACTIVE_UNITS) AS OP_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(OP_RCPTS_INACTIVE_COST_AMT) AS OP_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(OP_RCPTS_INACTIVE_UNITS) AS OP_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(OP_RCPTS_TOT_COST_AMT) AS OP_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(OP_RCPTS_TOT_UNITS) AS OP_RCPTS_TOT_UNITS
	    , ZEROIFNULL(OP_RCPTS_RESERVE_COST_AMT) AS OP_RCPTS_RESERVE_COST_AMT
	    , ZEROIFNULL(OP_RCPTS_RESERVE_UNITS) AS OP_RCPTS_RESERVE_UNITS
		-- Recls
		, ZEROIFNULL(OP_RECLASS_IN_COST_AMT) AS OP_RECLASS_IN_COST_AMT
		, ZEROIFNULL(OP_RECLASS_IN_UNITS) AS OP_RECLASS_IN_UNITS
		, ZEROIFNULL(OP_RECLASS_OUT_COST_AMT) AS OP_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(OP_RECLASS_OUT_UNITS) AS OP_RECLASS_OUT_UNITS
		, ZEROIFNULL(OP_RECLASS_TOT_COST_AMT) AS OP_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(OP_RECLASS_TOT_UNITS) AS OP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(OP_RTV_ACTIVE_COST_AMT) AS OP_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(OP_RTV_ACTIVE_UNITS) AS OP_RTV_ACTIVE_UNITS
		, ZEROIFNULL(OP_RTV_INACTIVE_COST_AMT) AS OP_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(OP_RTV_INACTIVE_UNITS) AS OP_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(OP_MOS_ACTIVE_COST_AMT) AS OP_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(OP_MOS_ACTIVE_UNITS) AS OP_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(OP_MOS_INACTIVE_COST_AMT) AS OP_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(OP_MOS_INACTIVE_UNITS) AS OP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(OP_VENDOR_FUNDS_COST_AMT) AS OP_VENDOR_FUNDS_COST_AMT		
	-- SP Metrics
	    -- Inventory
		, ZEROIFNULL(SP_BOP_ACTIVE_UNITS) AS SP_BOP_ACTIVE_UNITS
		, ZEROIFNULL(SP_BOP_ACTIVE_COST_AMT) AS SP_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(SP_BOP_INACTIVE_UNITS) AS SP_BOP_INACTIVE_UNITS
		, ZEROIFNULL(SP_BOP_INACTIVE_COST_AMT) AS SP_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(SP_BOP_TOT_COST_AMT) AS SP_BOP_TOT_COST_AMT
		, ZEROIFNULL(SP_BOP_TOT_UNITS) AS SP_BOP_TOT_UNITS
		, ZEROIFNULL(SP_EOP_ACTIVE_UNITS) AS SP_EOP_ACTIVE_UNITS
		, ZEROIFNULL(SP_EOP_ACTIVE_COST_AMT) AS SP_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(SP_EOP_INACTIVE_UNITS) AS SP_EOP_INACTIVE_UNITS
		, ZEROIFNULL(SP_EOP_INACTIVE_COST_AMT) AS SP_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(SP_EOP_TOT_COST_AMT) AS SP_EOP_TOT_COST_AMT
		, ZEROIFNULL(SP_EOP_TOT_UNITS) AS SP_EOP_TOT_UNITS
		, ZEROIFNULL(SP_BOP_ACTIVE_TGT_UNITS) AS SP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(SP_TRANSFER_ACTIVE_IN_COST_AMT) AS SP_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(SP_TRANSFER_ACTIVE_IN_UNITS) AS SP_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(SP_TRANSFER_ACTIVE_OUT_COST_AMT) AS SP_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(SP_TRANSFER_ACTIVE_OUT_UNITS) AS SP_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(SP_TRANSFER_INACTIVE_IN_COST_AMT) AS SP_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(SP_TRANSFER_INACTIVE_IN_UNITS) AS SP_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(SP_TRANSFER_INACTIVE_OUT_COST_AMT) AS SP_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(SP_TRANSFER_INACTIVE_OUT_UNITS) AS SP_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(SP_INV_MVMT_IN_DS_COST_AMT) AS SP_INV_MVMT_IN_DS_COST_AMT
		, ZEROIFNULL(SP_INV_MVMT_IN_DS_UNITS) AS SP_INV_MVMT_IN_DS_UNITS
		, ZEROIFNULL(SP_INV_MVMT_OUT_DS_COST_AMT) AS SP_INV_MVMT_OUT_DS_COST_AMT
		, ZEROIFNULL(SP_INV_MVMT_OUT_DS_UNITS) AS SP_INV_MVMT_OUT_DS_UNITS
		, ZEROIFNULL(SP_INV_MVMT_IN_TOT_COST_AMT) AS SP_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(SP_INV_MVMT_IN_TOT_UNITS) AS SP_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(SP_INV_MVMT_OUT_TOT_COST_AMT) AS SP_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(SP_INV_MVMT_OUT_TOT_UNITS) AS SP_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(SP_INV_OTHER_IN_COST_AMT) AS SP_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(SP_INV_OTHER_IN_UNITS) AS SP_INV_OTHER_IN_UNITS
		, ZEROIFNULL(SP_INV_OTHER_OUT_COST_AMT) AS SP_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(SP_INV_OTHER_OUT_UNITS) AS SP_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(SP_INV_RACK_IN_COST_AMT) AS SP_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(SP_INV_RACK_IN_UNITS) AS SP_INV_RACK_IN_UNITS
		, ZEROIFNULL(SP_INV_RACK_OUT_COST_AMT) AS SP_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(SP_INV_RACK_OUT_UNITS) AS SP_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(SP_MERCH_MARGIN_AMT) AS SP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(SP_INVOICE_PAYMENT_TERMS_COST_AMT) AS SP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(SP_RCPTS_ACTIVE_COST_AMT) AS SP_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(SP_RCPTS_ACTIVE_UNITS) AS SP_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(SP_RCPTS_INACTIVE_COST_AMT) AS SP_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(SP_RCPTS_INACTIVE_UNITS) AS SP_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(SP_RCPTS_TOT_COST_AMT) AS SP_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(SP_RCPTS_TOT_UNITS) AS SP_RCPTS_TOT_UNITS
	    , ZEROIFNULL(SP_RCPTS_RESERVE_COST_AMT) AS SP_RCPTS_RESERVE_COST_AMT
	    , ZEROIFNULL(SP_RCPTS_RESERVE_UNITS) AS SP_RCPTS_RESERVE_UNITS
		-- Recls
		, ZEROIFNULL(SP_RECLASS_IN_COST_AMT) AS SP_RECLASS_IN_COST_AMT
		, ZEROIFNULL(SP_RECLASS_IN_UNITS) AS SP_RECLASS_IN_UNITS
		, ZEROIFNULL(SP_RECLASS_OUT_COST_AMT) AS SP_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(SP_RECLASS_OUT_UNITS) AS SP_RECLASS_OUT_UNITS
		, ZEROIFNULL(SP_RECLASS_TOT_COST_AMT) AS SP_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(SP_RECLASS_TOT_UNITS) AS SP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(SP_RTV_ACTIVE_COST_AMT) AS SP_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(SP_RTV_ACTIVE_UNITS) AS SP_RTV_ACTIVE_UNITS
		, ZEROIFNULL(SP_RTV_INACTIVE_COST_AMT) AS SP_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(SP_RTV_INACTIVE_UNITS) AS SP_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(SP_MOS_ACTIVE_COST_AMT) AS SP_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(SP_MOS_ACTIVE_UNITS) AS SP_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(SP_MOS_INACTIVE_COST_AMT) AS SP_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(SP_MOS_INACTIVE_UNITS) AS SP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(SP_VENDOR_FUNDS_COST_AMT) AS SP_VENDOR_FUNDS_COST_AMT
	-- QP Metrics
	    -- Inventory
		, ZEROIFNULL(QP_BOP_ACTIVE_UNITS) AS QP_BOP_ACTIVE_UNITS
		, ZEROIFNULL(QP_BOP_ACTIVE_COST_AMT) AS QP_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(QP_BOP_INACTIVE_UNITS) AS QP_BOP_INACTIVE_UNITS
		, ZEROIFNULL(QP_BOP_INACTIVE_COST_AMT) AS QP_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(QP_BOP_TOT_COST_AMT) AS QP_BOP_TOT_COST_AMT
		, ZEROIFNULL(QP_BOP_TOT_UNITS) AS QP_BOP_TOT_UNITS
		, ZEROIFNULL(QP_EOP_ACTIVE_UNITS) AS QP_EOP_ACTIVE_UNITS
		, ZEROIFNULL(QP_EOP_ACTIVE_COST_AMT) AS QP_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(QP_EOP_INACTIVE_UNITS) AS QP_EOP_INACTIVE_UNITS
		, ZEROIFNULL(QP_EOP_INACTIVE_COST_AMT) AS QP_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(QP_EOP_TOT_COST_AMT) AS QP_EOP_TOT_COST_AMT
		, ZEROIFNULL(QP_EOP_TOT_UNITS) AS QP_EOP_TOT_UNITS
		, ZEROIFNULL(QP_BOP_ACTIVE_TGT_UNITS) AS QP_BOP_ACTIVE_TGT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(QP_TRANSFER_ACTIVE_IN_COST_AMT) AS QP_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(QP_TRANSFER_ACTIVE_IN_UNITS) AS QP_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(QP_TRANSFER_ACTIVE_OUT_COST_AMT) AS QP_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(QP_TRANSFER_ACTIVE_OUT_UNITS) AS QP_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(QP_TRANSFER_INACTIVE_IN_COST_AMT) AS QP_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(QP_TRANSFER_INACTIVE_IN_UNITS) AS QP_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(QP_TRANSFER_INACTIVE_OUT_COST_AMT) AS QP_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(QP_TRANSFER_INACTIVE_OUT_UNITS) AS QP_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(QP_INV_MVMT_IN_DS_COST_AMT) AS QP_INV_MVMT_IN_DS_COST_AMT
		, ZEROIFNULL(QP_INV_MVMT_IN_DS_UNITS) AS QP_INV_MVMT_IN_DS_UNITS
		, ZEROIFNULL(QP_INV_MVMT_OUT_DS_COST_AMT) AS QP_INV_MVMT_OUT_DS_COST_AMT
		, ZEROIFNULL(QP_INV_MVMT_OUT_DS_UNITS) AS QP_INV_MVMT_OUT_DS_UNITS
		, ZEROIFNULL(QP_INV_MVMT_IN_TOT_COST_AMT) AS QP_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(QP_INV_MVMT_IN_TOT_UNITS) AS QP_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(QP_INV_MVMT_OUT_TOT_COST_AMT) AS QP_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(QP_INV_MVMT_OUT_TOT_UNITS) AS QP_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(QP_INV_OTHER_IN_COST_AMT) AS QP_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(QP_INV_OTHER_IN_UNITS) AS QP_INV_OTHER_IN_UNITS
		, ZEROIFNULL(QP_INV_OTHER_OUT_COST_AMT) AS QP_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(QP_INV_OTHER_OUT_UNITS) AS QP_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(QP_INV_RACK_IN_COST_AMT) AS QP_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(QP_INV_RACK_IN_UNITS) AS QP_INV_RACK_IN_UNITS
		, ZEROIFNULL(QP_INV_RACK_OUT_COST_AMT) AS QP_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(QP_INV_RACK_OUT_UNITS) AS QP_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(QP_MERCH_MARGIN_AMT) AS QP_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(QP_INVOICE_PAYMENT_TERMS_COST_AMT) AS QP_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(QP_RCPTS_ACTIVE_COST_AMT) AS QP_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(QP_RCPTS_ACTIVE_UNITS) AS QP_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(QP_RCPTS_INACTIVE_COST_AMT) AS QP_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(QP_RCPTS_INACTIVE_UNITS) AS QP_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(QP_RCPTS_TOT_COST_AMT) AS QP_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(QP_RCPTS_TOT_UNITS) AS QP_RCPTS_TOT_UNITS
	    , ZEROIFNULL(QP_RCPTS_RESERVE_COST_AMT) AS QP_RCPTS_RESERVE_COST_AMT
	    , ZEROIFNULL(QP_RCPTS_RESERVE_UNITS) AS QP_RCPTS_RESERVE_UNITS
		-- Recls
		, ZEROIFNULL(QP_RECLASS_IN_COST_AMT) AS QP_RECLASS_IN_COST_AMT
		, ZEROIFNULL(QP_RECLASS_IN_UNITS) AS QP_RECLASS_IN_UNITS
		, ZEROIFNULL(QP_RECLASS_OUT_COST_AMT) AS QP_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(QP_RECLASS_OUT_UNITS) AS QP_RECLASS_OUT_UNITS
		, ZEROIFNULL(QP_RECLASS_TOT_COST_AMT) AS QP_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(QP_RECLASS_TOT_UNITS) AS QP_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(QP_RTV_ACTIVE_COST_AMT) AS QP_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(QP_RTV_ACTIVE_UNITS) AS QP_RTV_ACTIVE_UNITS
		, ZEROIFNULL(QP_RTV_INACTIVE_COST_AMT) AS QP_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(QP_RTV_INACTIVE_UNITS) AS QP_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(QP_MOS_ACTIVE_COST_AMT) AS QP_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(QP_MOS_ACTIVE_UNITS) AS QP_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(QP_MOS_INACTIVE_COST_AMT) AS QP_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(QP_MOS_INACTIVE_UNITS) AS QP_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(QP_VENDOR_FUNDS_COST_AMT) AS QP_VENDOR_FUNDS_COST_AMT
	-- TY Metrics
	    -- Inventory
		, ZEROIFNULL(TY_BOP_ACTIVE_UNITS) AS TY_BOP_ACTIVE_UNITS
		, ZEROIFNULL(TY_BOP_ACTIVE_COST_AMT) AS TY_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(TY_BOP_INACTIVE_UNITS) AS TY_BOP_INACTIVE_UNITS
		, ZEROIFNULL(TY_BOP_INACTIVE_COST_AMT) AS TY_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT
		, ZEROIFNULL(TY_BOP_TOT_UNITS) AS TY_BOP_TOT_UNITS
		, ZEROIFNULL(TY_EOP_ACTIVE_UNITS) AS TY_EOP_ACTIVE_UNITS
		, ZEROIFNULL(TY_EOP_ACTIVE_COST_AMT) AS TY_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(TY_EOP_INACTIVE_UNITS) AS TY_EOP_INACTIVE_UNITS
		, ZEROIFNULL(TY_EOP_INACTIVE_COST_AMT) AS TY_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(TY_EOP_TOT_COST_AMT) AS TY_EOP_TOT_COST_AMT
		, ZEROIFNULL(TY_EOP_TOT_UNITS) AS TY_EOP_TOT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(TY_TRANSFER_ACTIVE_IN_COST_AMT) AS TY_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(TY_TRANSFER_ACTIVE_IN_UNITS) AS TY_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(TY_TRANSFER_ACTIVE_OUT_COST_AMT) AS TY_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(TY_TRANSFER_ACTIVE_OUT_UNITS) AS TY_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(TY_TRANSFER_INACTIVE_IN_COST_AMT) AS TY_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(TY_TRANSFER_INACTIVE_IN_UNITS) AS TY_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(TY_TRANSFER_INACTIVE_OUT_COST_AMT) AS TY_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(TY_TRANSFER_INACTIVE_OUT_UNITS) AS TY_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(TY_INV_MVMT_IN_TOT_COST_AMT) AS TY_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(TY_INV_MVMT_IN_TOT_UNITS) AS TY_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(TY_INV_MVMT_OUT_TOT_COST_AMT) AS TY_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(TY_INV_MVMT_OUT_TOT_UNITS) AS TY_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(TY_INV_OTHER_IN_COST_AMT) AS TY_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(TY_INV_OTHER_IN_UNITS) AS TY_INV_OTHER_IN_UNITS
		, ZEROIFNULL(TY_INV_OTHER_OUT_COST_AMT) AS TY_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(TY_INV_OTHER_OUT_UNITS) AS TY_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(TY_INV_RACK_IN_COST_AMT) AS TY_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(TY_INV_RACK_IN_UNITS) AS TY_INV_RACK_IN_UNITS
		, ZEROIFNULL(TY_INV_RACK_OUT_COST_AMT) AS TY_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(TY_INV_RACK_OUT_UNITS) AS TY_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(TY_MERCH_MARGIN_AMT) AS TY_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(TY_INVOICE_PAYMENT_TERMS_COST_AMT) AS TY_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(TY_RCPTS_ACTIVE_COST_AMT) AS TY_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(TY_RCPTS_ACTIVE_UNITS) AS TY_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(TY_RCPTS_INACTIVE_COST_AMT) AS TY_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(TY_RCPTS_INACTIVE_UNITS) AS TY_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(TY_RCPTS_TOT_COST_AMT) AS TY_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(TY_RCPTS_TOT_UNITS) AS TY_RCPTS_TOT_UNITS
		-- Reclass
		, ZEROIFNULL(TY_RECLASS_IN_COST_AMT) AS TY_RECLASS_IN_COST_AMT
		, ZEROIFNULL(TY_RECLASS_IN_UNITS) AS TY_RECLASS_IN_UNITS
		, ZEROIFNULL(TY_RECLASS_OUT_COST_AMT) AS TY_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(TY_RECLASS_OUT_UNITS) AS TY_RECLASS_OUT_UNITS
		, ZEROIFNULL(TY_RECLASS_TOT_COST_AMT) AS TY_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(TY_RECLASS_TOT_UNITS) AS TY_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(TY_RTV_ACTIVE_COST_AMT) AS TY_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(TY_RTV_ACTIVE_UNITS) AS TY_RTV_ACTIVE_UNITS
		, ZEROIFNULL(TY_RTV_INACTIVE_COST_AMT) AS TY_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(TY_RTV_INACTIVE_UNITS) AS TY_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(TY_MOS_ACTIVE_COST_AMT) AS TY_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(TY_MOS_ACTIVE_UNITS) AS TY_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(TY_MOS_INACTIVE_COST_AMT) AS TY_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(TY_MOS_INACTIVE_UNITS) AS TY_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(TY_VENDOR_FUNDS_COST_AMT) AS TY_VENDOR_FUNDS_COST_AMT
	-- LY Metrics
	    -- Inventory
		, ZEROIFNULL(LY_BOP_ACTIVE_UNITS) AS LY_BOP_ACTIVE_UNITS
		, ZEROIFNULL(LY_BOP_ACTIVE_COST_AMT) AS LY_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_BOP_INACTIVE_UNITS) AS LY_BOP_INACTIVE_UNITS
		, ZEROIFNULL(LY_BOP_INACTIVE_COST_AMT) AS LY_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
		, ZEROIFNULL(LY_BOP_TOT_UNITS) AS LY_BOP_TOT_UNITS
		, ZEROIFNULL(LY_EOP_ACTIVE_UNITS) AS LY_EOP_ACTIVE_UNITS
		, ZEROIFNULL(LY_EOP_ACTIVE_COST_AMT) AS LY_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_EOP_INACTIVE_UNITS) AS LY_EOP_INACTIVE_UNITS
		, ZEROIFNULL(LY_EOP_INACTIVE_COST_AMT) AS LY_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_EOP_TOT_COST_AMT) AS LY_EOP_TOT_COST_AMT
		, ZEROIFNULL(LY_EOP_TOT_UNITS) AS LY_EOP_TOT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(LY_TRANSFER_ACTIVE_IN_COST_AMT) AS LY_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(LY_TRANSFER_ACTIVE_IN_UNITS) AS LY_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(LY_TRANSFER_ACTIVE_OUT_COST_AMT) AS LY_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(LY_TRANSFER_ACTIVE_OUT_UNITS) AS LY_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(LY_TRANSFER_INACTIVE_IN_COST_AMT) AS LY_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(LY_TRANSFER_INACTIVE_IN_UNITS) AS LY_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(LY_TRANSFER_INACTIVE_OUT_COST_AMT) AS LY_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(LY_TRANSFER_INACTIVE_OUT_UNITS) AS LY_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(LY_INV_MVMT_IN_TOT_COST_AMT) AS LY_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(LY_INV_MVMT_IN_TOT_UNITS) AS LY_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(LY_INV_MVMT_OUT_TOT_COST_AMT) AS LY_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(LY_INV_MVMT_OUT_TOT_UNITS) AS LY_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(LY_INV_OTHER_IN_COST_AMT) AS LY_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(LY_INV_OTHER_IN_UNITS) AS LY_INV_OTHER_IN_UNITS
		, ZEROIFNULL(LY_INV_OTHER_OUT_COST_AMT) AS LY_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(LY_INV_OTHER_OUT_UNITS) AS LY_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(LY_INV_RACK_IN_COST_AMT) AS LY_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(LY_INV_RACK_IN_UNITS) AS LY_INV_RACK_IN_UNITS
		, ZEROIFNULL(LY_INV_RACK_OUT_COST_AMT) AS LY_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(LY_INV_RACK_OUT_UNITS) AS LY_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(LY_MERCH_MARGIN_AMT) AS LY_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(LY_INVOICE_PAYMENT_TERMS_COST_AMT) AS LY_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(LY_RCPTS_ACTIVE_COST_AMT) AS LY_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_RCPTS_ACTIVE_UNITS) AS LY_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(LY_RCPTS_INACTIVE_COST_AMT) AS LY_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_RCPTS_INACTIVE_UNITS) AS LY_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(LY_RCPTS_TOT_COST_AMT) AS LY_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(LY_RCPTS_TOT_UNITS) AS LY_RCPTS_TOT_UNITS
		-- Reclass
		, ZEROIFNULL(LY_RECLASS_IN_COST_AMT) AS LY_RECLASS_IN_COST_AMT
		, ZEROIFNULL(LY_RECLASS_IN_UNITS) AS LY_RECLASS_IN_UNITS
		, ZEROIFNULL(LY_RECLASS_OUT_COST_AMT) AS LY_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(LY_RECLASS_OUT_UNITS) AS LY_RECLASS_OUT_UNITS
		, ZEROIFNULL(LY_RECLASS_TOT_COST_AMT) AS LY_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(LY_RECLASS_TOT_UNITS) AS LY_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(LY_RTV_ACTIVE_COST_AMT) AS LY_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_RTV_ACTIVE_UNITS) AS LY_RTV_ACTIVE_UNITS
		, ZEROIFNULL(LY_RTV_INACTIVE_COST_AMT) AS LY_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_RTV_INACTIVE_UNITS) AS LY_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(LY_MOS_ACTIVE_COST_AMT) AS LY_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(LY_MOS_ACTIVE_UNITS) AS LY_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(LY_MOS_INACTIVE_COST_AMT) AS LY_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(LY_MOS_INACTIVE_UNITS) AS LY_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(LY_VENDOR_FUNDS_COST_AMT) AS LY_VENDOR_FUNDS_COST_AMT
	-- LY TRUEDAY Metrics - NEW 01.25.2024
	    -- Inventory
		, ZEROIFNULL(LY_TRUEDAY_BOP_ACTIVE_UNITS) AS LY_TRUEDAY_BOP_ACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_BOP_ACTIVE_COST_AMT) AS LY_TRUEDAY_BOP_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_BOP_INACTIVE_UNITS) AS LY_TRUEDAY_BOP_INACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_BOP_INACTIVE_COST_AMT) AS LY_TRUEDAY_BOP_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_BOP_TOT_COST_AMT) AS LY_TRUEDAY_BOP_TOT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_BOP_TOT_UNITS) AS LY_TRUEDAY_BOP_TOT_UNITS
		, ZEROIFNULL(LY_TRUEDAY_EOP_ACTIVE_UNITS) AS LY_TRUEDAY_EOP_ACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_EOP_ACTIVE_COST_AMT) AS LY_TRUEDAY_EOP_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_EOP_INACTIVE_UNITS) AS LY_TRUEDAY_EOP_INACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_EOP_INACTIVE_COST_AMT) AS LY_TRUEDAY_EOP_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_EOP_TOT_COST_AMT) AS LY_TRUEDAY_EOP_TOT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_EOP_TOT_UNITS) AS LY_TRUEDAY_EOP_TOT_UNITS
		-- Inventory Movement
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_ACTIVE_IN_COST_AMT) AS LY_TRUEDAY_TRANSFER_ACTIVE_IN_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_ACTIVE_IN_UNITS) AS LY_TRUEDAY_TRANSFER_ACTIVE_IN_UNITS
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_ACTIVE_OUT_COST_AMT) AS LY_TRUEDAY_TRANSFER_ACTIVE_OUT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_ACTIVE_OUT_UNITS) AS LY_TRUEDAY_TRANSFER_ACTIVE_OUT_UNITS
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_INACTIVE_IN_COST_AMT) AS LY_TRUEDAY_TRANSFER_INACTIVE_IN_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_INACTIVE_IN_UNITS) AS LY_TRUEDAY_TRANSFER_INACTIVE_IN_UNITS
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_INACTIVE_OUT_COST_AMT) AS LY_TRUEDAY_TRANSFER_INACTIVE_OUT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_TRANSFER_INACTIVE_OUT_UNITS) AS LY_TRUEDAY_TRANSFER_INACTIVE_OUT_UNITS
		, ZEROIFNULL(LY_TRUEDAY_INV_MVMT_IN_TOT_COST_AMT) AS LY_TRUEDAY_INV_MVMT_IN_TOT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_INV_MVMT_IN_TOT_UNITS) AS LY_TRUEDAY_INV_MVMT_IN_TOT_UNITS
		, ZEROIFNULL(LY_TRUEDAY_INV_MVMT_OUT_TOT_COST_AMT) AS LY_TRUEDAY_INV_MVMT_OUT_TOT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_INV_MVMT_OUT_TOT_UNITS) AS LY_TRUEDAY_INV_MVMT_OUT_TOT_UNITS 
		, ZEROIFNULL(LY_TRUEDAY_INV_OTHER_IN_COST_AMT) AS LY_TRUEDAY_INV_OTHER_IN_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_INV_OTHER_IN_UNITS) AS LY_TRUEDAY_INV_OTHER_IN_UNITS
		, ZEROIFNULL(LY_TRUEDAY_INV_OTHER_OUT_COST_AMT) AS LY_TRUEDAY_INV_OTHER_OUT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_INV_OTHER_OUT_UNITS) AS LY_TRUEDAY_INV_OTHER_OUT_UNITS
		, ZEROIFNULL(LY_TRUEDAY_INV_RACK_IN_COST_AMT) AS LY_TRUEDAY_INV_RACK_IN_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_INV_RACK_IN_UNITS) AS LY_TRUEDAY_INV_RACK_IN_UNITS
		, ZEROIFNULL(LY_TRUEDAY_INV_RACK_OUT_COST_AMT) AS LY_TRUEDAY_INV_RACK_OUT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_INV_RACK_OUT_UNITS) AS LY_TRUEDAY_INV_RACK_OUT_UNITS
		-- Margin
		, ZEROIFNULL(LY_TRUEDAY_MERCH_MARGIN_AMT) AS LY_TRUEDAY_MERCH_MARGIN_AMT
		-- Invoice Payment Terms
		, ZEROIFNULL(LY_TRUEDAY_INVOICE_PAYMENT_TERMS_COST_AMT) AS LY_TRUEDAY_INVOICE_PAYMENT_TERMS_COST_AMT
		-- Receipts
		, ZEROIFNULL(LY_TRUEDAY_RCPTS_ACTIVE_COST_AMT) AS LY_TRUEDAY_RCPTS_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RCPTS_ACTIVE_UNITS) AS LY_TRUEDAY_RCPTS_ACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_RCPTS_INACTIVE_COST_AMT) AS LY_TRUEDAY_RCPTS_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RCPTS_INACTIVE_UNITS) AS LY_TRUEDAY_RCPTS_INACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_RCPTS_TOT_COST_AMT) AS LY_TRUEDAY_RCPTS_TOT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RCPTS_TOT_UNITS) AS LY_TRUEDAY_RCPTS_TOT_UNITS
		-- Reclass
		, ZEROIFNULL(LY_TRUEDAY_RECLASS_IN_COST_AMT) AS LY_TRUEDAY_RECLASS_IN_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RECLASS_IN_UNITS) AS LY_TRUEDAY_RECLASS_IN_UNITS
		, ZEROIFNULL(LY_TRUEDAY_RECLASS_OUT_COST_AMT) AS LY_TRUEDAY_RECLASS_OUT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RECLASS_OUT_UNITS) AS LY_TRUEDAY_RECLASS_OUT_UNITS
		, ZEROIFNULL(LY_TRUEDAY_RECLASS_TOT_COST_AMT) AS LY_TRUEDAY_RECLASS_TOT_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RECLASS_TOT_UNITS) AS LY_TRUEDAY_RECLASS_TOT_UNITS
		-- Return to Vendor
		, ZEROIFNULL(LY_TRUEDAY_RTV_ACTIVE_COST_AMT) AS LY_TRUEDAY_RTV_ACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RTV_ACTIVE_UNITS) AS LY_TRUEDAY_RTV_ACTIVE_UNITS
		, ZEROIFNULL(LY_TRUEDAY_RTV_INACTIVE_COST_AMT) AS LY_TRUEDAY_RTV_INACTIVE_COST_AMT
		, ZEROIFNULL(LY_TRUEDAY_RTV_INACTIVE_UNITS) AS LY_TRUEDAY_RTV_INACTIVE_UNITS
	    -- MOS
	    , ZEROIFNULL(LY_TRUEDAY_MOS_ACTIVE_COST_AMT) AS LY_TRUEDAY_MOS_ACTIVE_COST_AMT
	    , ZEROIFNULL(LY_TRUEDAY_MOS_ACTIVE_UNITS) AS LY_TRUEDAY_MOS_ACTIVE_UNITS
	    , ZEROIFNULL(LY_TRUEDAY_MOS_INACTIVE_COST_AMT) AS LY_TRUEDAY_MOS_INACTIVE_COST_AMT
	    , ZEROIFNULL(LY_TRUEDAY_MOS_INACTIVE_UNITS) AS LY_TRUEDAY_MOS_INACTIVE_UNITS
		-- Vendor Funds
		, ZEROIFNULL(LY_TRUEDAY_VENDOR_FUNDS_COST_AMT) AS LY_TRUEDAY_VENDOR_FUNDS_COST_AMT
		, CURRENT_TIMESTAMP AS process_tmstp 
	
	FROM FINAL_BASELINE_HEADER h
	
	LEFT JOIN CHANNEL ch 
		ON ch.DEPT_NUM = h.DEPT_NUM
			AND ch.WEEK_NUM = h.WEEK_NUM
			AND ch.BANNER_COUNTRY_NUM = h.BANNER_COUNTRY_NUM
			AND ch.FULFILL_TYPE_NUM = h.FULFILL_TYPE_NUM
			AND ch.CHANNEL_NUM = h.CHANNEL_NUM
	
	LEFT JOIN CHANNEL_INV ci 
		ON ci.DEPT_NUM = h.DEPT_NUM
			AND ci.WEEK_NUM = h.WEEK_NUM
			AND ci.BANNER_COUNTRY_NUM = h.BANNER_COUNTRY_NUM
			AND ci.FULFILL_TYPE_NUM = h.FULFILL_TYPE_NUM
			AND ci.CHANNEL_NUM = h.CHANNEL_NUM
	
	LEFT JOIN BANNER_COUNTRY bc
		ON bc.DEPT_NUM = h.DEPT_NUM
			AND bc.WEEK_NUM = h.WEEK_NUM
			AND bc.BANNER_COUNTRY_NUM = h.BANNER_COUNTRY_NUM
			AND bc.FULFILL_TYPE_NUM = h.FULFILL_TYPE_NUM
			AND bc.CHANNEL_NUM = h.CHANNEL_NUM
)
WITH DATA
PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
ON COMMIT PRESERVE ROWS;

COLLECT STATS
	 PRIMARY INDEX (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
	,COLUMN (DEPT_NUM, WEEK_NUM, CHANNEL_NUM, FULFILL_TYPE_NUM)
		ON FINAL_BASELINE;

-- Update table
DELETE FROM T2DL_DAS_ACE_MFP.MFP_BANNER_COUNTRY_CHANNEL_STG{env_suffix}; 
INSERT INTO T2DL_DAS_ACE_MFP.MFP_BANNER_COUNTRY_CHANNEL_STG{env_suffix}
SELECT * FROM FINAL_BASELINE;