/*------------------------------------------------------
 MFP Summary DDL
 
 Last Update: 08/02/24 Asiyah Fox - Added environment variables
 Contact for logic/code: Asiyah Fox (Merch Analytics)
 Contact for ETL: Asiyah Fox (Merch Analytics)
 --------------------------------------------------------*/

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T2DL_DAS_ACE_MFP', 'MFP_BANNER_COUNTRY_CHANNEL_STG{env_suffix}', OUT_RETURN_MSG);
CREATE MULTISET TABLE T2DL_DAS_ACE_MFP.MFP_BANNER_COUNTRY_CHANNEL_STG{env_suffix}
    , FALLBACK
    , NO BEFORE JOURNAL
    , NO AFTER JOURNAL
    , CHECKSUM = DEFAULT
    , DEFAULT MERGEBLOCKRATIO
    , MAP = TD_MAP1
(
	DEPARTMENT_LABEL						VARCHAR(163)
	, DEPT_NUM								INTEGER NOT NULL
	, WEEK_454_LABEL						VARCHAR(20)
	, WEEK_NUM								INTEGER NOT NULL
	, BANNER_COUNTRY						VARCHAR(72)
	, BANNER								VARCHAR(60)
	, COUNTRY								VARCHAR(10)
	, BANNER_COUNTRY_NUM					INTEGER NOT NULL
	, CHANNEL_NUM							INTEGER NOT NULL
	, CHANNEL								VARCHAR(73)
	, FULFILL_TYPE_NUM						VARCHAR(11) NOT NULL
	, FULFILL_TYPE_DESC						VARCHAR(60)
	, SUBDIVISION							VARCHAR(163)
	, DIVISION								VARCHAR(163)
	, "MONTH"								VARCHAR(10)
	, QUARTER								VARCHAR(8)
	, QUARTER_NUM							INTEGER NOT NULL
	, HALF									VARCHAR(14)
	, "YEAR"								INTEGER NOT NULL
	, WEEK_END_DAY_DATE						DATE FORMAT 'YYYY-MM-DD' NOT NULL
	---- CHANNEL LEVEL DATA
	-- CP
	, CP_DEMAND_TOTAL_UNITS 				BIGINT 
	, CP_DEMAND_TOTAL_RETAIL_AMT			DECIMAL(32, 4)
	, CP_GROSS_MARGIN_RETAIL_AMT			DECIMAL(32, 4)
	, CP_GROSS_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, CP_GROSS_SALES_UNITS 					BIGINT  
	, CP_NET_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, CP_NET_SALES_UNITS 					BIGINT  
	, CP_NET_SALES_COST_AMT					DECIMAL(32, 4)
	, CP_NET_SALES_TRUNK_CLUB_RETAIL_AMT	DECIMAL(32, 4)
	, CP_NET_SALES_TRUNK_CLUB_UNITS  		BIGINT 
	, CP_RETURNS_RETAIL_AMT					DECIMAL(32, 4)
	, CP_RETURNS_UNITS  					BIGINT 
	, CP_SHRINK_COST_AMT					DECIMAL(32, 4)
	, CP_SHRINK_UNITS 						BIGINT  
	-- OP
	, OP_DEMAND_TOTAL_UNITS 				BIGINT 
	, OP_DEMAND_TOTAL_RETAIL_AMT			DECIMAL(32, 4)
	, OP_GROSS_MARGIN_RETAIL_AMT			DECIMAL(32, 4)
	, OP_GROSS_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, OP_GROSS_SALES_UNITS 					BIGINT 
	, OP_NET_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, OP_NET_SALES_UNITS 					BIGINT 
	, OP_NET_SALES_COST_AMT					DECIMAL(32, 4)
	, OP_NET_SALES_TRUNK_CLUB_RETAIL_AMT	DECIMAL(32, 4)
	, OP_NET_SALES_TRUNK_CLUB_UNITS 		BIGINT 
	, OP_RETURNS_RETAIL_AMT					DECIMAL(32, 4)
	, OP_RETURNS_UNITS 						BIGINT 
	, OP_SHRINK_COST_AMT					DECIMAL(32, 4)
	, OP_SHRINK_UNITS 						BIGINT 
	-- SP
	, SP_DEMAND_TOTAL_UNITS 				BIGINT 
	, SP_DEMAND_TOTAL_RETAIL_AMT			DECIMAL(32, 4)
	, SP_GROSS_MARGIN_RETAIL_AMT			DECIMAL(32, 4)
	, SP_GROSS_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, SP_GROSS_SALES_UNITS 					BIGINT 
	, SP_NET_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, SP_NET_SALES_UNITS 					BIGINT 
	, SP_NET_SALES_COST_AMT					DECIMAL(32, 4)
	, SP_NET_SALES_TRUNK_CLUB_RETAIL_AMT	DECIMAL(32, 4)
	, SP_NET_SALES_TRUNK_CLUB_UNITS 		BIGINT 
	, SP_RETURNS_RETAIL_AMT					DECIMAL(32, 4)
	, SP_RETURNS_UNITS 						BIGINT 
	, SP_SHRINK_COST_AMT					DECIMAL(32, 4)
	, SP_SHRINK_UNITS 						BIGINT 
	-- QP
	, QP_DEMAND_TOTAL_UNITS 				BIGINT 
	, QP_DEMAND_TOTAL_RETAIL_AMT			DECIMAL(32, 4)
	, QP_GROSS_MARGIN_RETAIL_AMT			DECIMAL(32, 4)
	, QP_GROSS_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, QP_GROSS_SALES_UNITS 					BIGINT 
	, QP_NET_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, QP_NET_SALES_UNITS 					BIGINT 
	, QP_NET_SALES_COST_AMT					DECIMAL(32, 4)
	, QP_NET_SALES_TRUNK_CLUB_RETAIL_AMT	DECIMAL(32, 4)
	, QP_NET_SALES_TRUNK_CLUB_UNITS 		BIGINT 
	, QP_RETURNS_RETAIL_AMT					DECIMAL(32, 4)
	, QP_RETURNS_UNITS 						BIGINT 
	, QP_SHRINK_COST_AMT					DECIMAL(32, 4)
	, QP_SHRINK_UNITS 						BIGINT 
	-- TY ACTUALS
	, TY_DEMAND_TOTAL_UNITS 				BIGINT 
	, TY_DEMAND_TOTAL_RETAIL_AMT			DECIMAL(32, 4)
	, TY_GROSS_MARGIN_RETAIL_AMT			DECIMAL(32, 4)
	, TY_GROSS_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, TY_GROSS_SALES_UNITS 					BIGINT 
	, TY_NET_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, TY_NET_SALES_UNITS					BIGINT 
	, TY_NET_SALES_COST_AMT					DECIMAL(32, 4)
	, TY_NET_SALES_TRUNK_CLUB_RETAIL_AMT	DECIMAL(32, 4)
	, TY_NET_SALES_TRUNK_CLUB_UNITS 		BIGINT 
	, TY_RETURNS_RETAIL_AMT					DECIMAL(32, 4)
	, TY_RETURNS_UNITS 						BIGINT 
	, TY_SHRINK_COST_AMT					DECIMAL(32, 4)
	, TY_SHRINK_UNITS						BIGINT 
	-- LY ACTUALS
	, LY_DEMAND_TOTAL_UNITS 				BIGINT 
	, LY_DEMAND_TOTAL_RETAIL_AMT			DECIMAL(32, 4)
	, LY_GROSS_MARGIN_RETAIL_AMT			DECIMAL(32, 4)
	, LY_GROSS_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, LY_GROSS_SALES_UNITS 					BIGINT 
	, LY_NET_SALES_RETAIL_AMT				DECIMAL(32, 4)
	, LY_NET_SALES_UNITS 					BIGINT 
	, LY_NET_SALES_COST_AMT					DECIMAL(32, 4)
	, LY_NET_SALES_TRUNK_CLUB_RETAIL_AMT	DECIMAL(32, 4)
	, LY_NET_SALES_TRUNK_CLUB_UNITS 		BIGINT 
	, LY_RETURNS_RETAIL_AMT					DECIMAL(32, 4)
	, LY_RETURNS_UNITS 						BIGINT 
	, LY_SHRINK_COST_AMT					DECIMAL(32, 4)
	, LY_SHRINK_UNITS 						BIGINT 
	-- LY TRUEDAY ACTUALS
	,  LY_TRUEDAY_DEMAND_TOTAL_UNITS 		BIGINT 
	,  LY_TRUEDAY_DEMAND_TOTAL_RETAIL_AMT	DECIMAL(32, 4)
	,  LY_TRUEDAY_GROSS_MARGIN_RETAIL_AMT	DECIMAL(32, 4)
	,  LY_TRUEDAY_GROSS_SALES_RETAIL_AMT	DECIMAL(32, 4)
	,  LY_TRUEDAY_GROSS_SALES_UNITS 		BIGINT 
	,  LY_TRUEDAY_NET_SALES_RETAIL_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_NET_SALES_UNITS 			BIGINT 
	,  LY_TRUEDAY_NET_SALES_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_RETURNS_RETAIL_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_RETURNS_UNITS 			BIGINT 
	,  LY_TRUEDAY_SHRINK_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_SHRINK_UNITS 				BIGINT 
-- BANNER/COUNTRY LEVEL
	-- CP Metrics
	-- Inventory
	, CP_BOP_ACTIVE_UNITS					BIGINT
	, CP_BOP_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, CP_BOP_INACTIVE_UNITS					BIGINT
	, CP_BOP_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, CP_BOP_TOT_COST_AMT					DECIMAL(32, 4)
	, CP_BOP_TOT_UNITS						BIGINT
	, CP_EOP_ACTIVE_UNITS					BIGINT
	, CP_EOP_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, CP_EOP_INACTIVE_UNITS					BIGINT
	, CP_EOP_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, CP_EOP_TOT_COST_AMT					DECIMAL(32, 4)
	, CP_EOP_TOT_UNITS						BIGINT
	, CP_BOP_ACTIVE_TGT_UNITS				BIGINT
	-- Inventory Movement
	, CP_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, CP_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	, CP_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, CP_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	, CP_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, CP_TRANSFER_INACTIVE_IN_UNITS			BIGINT
	, CP_TRANSFER_INACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, CP_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	, CP_INV_MVMT_IN_DS_COST_AMT			DECIMAL(32, 4)
	, CP_INV_MVMT_IN_DS_UNITS				BIGINT
	, CP_INV_MVMT_OUT_DS_COST_AMT			DECIMAL(32, 4)
	, CP_INV_MVMT_OUT_DS_UNITS				BIGINT
	, CP_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	, CP_INV_MVMT_IN_TOT_UNITS				BIGINT
	, CP_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	, CP_INV_MVMT_OUT_TOT_UNITS				BIGINT
	, CP_INV_OTHER_IN_COST_AMT				DECIMAL(32, 4)
	, CP_INV_OTHER_IN_UNITS					BIGINT
	, CP_INV_OTHER_OUT_COST_AMT				DECIMAL(32, 4)
	, CP_INV_OTHER_OUT_UNITS				BIGINT
	, CP_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	, CP_INV_RACK_IN_UNITS					BIGINT
	, CP_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	, CP_INV_RACK_OUT_UNITS					BIGINT
	-- Margin 
	, CP_MERCH_MARGIN_AMT					DECIMAL(32, 4)
	-- Invoice Payment Terms
	, CP_INVOICE_PAYMENT_TERMS_COST_AMT		DECIMAL(32, 4)
	-- receipts
	, CP_RCPTS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, CP_RCPTS_ACTIVE_UNITS					BIGINT
	, CP_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	, CP_RCPTS_INACTIVE_UNITS				BIGINT
	, CP_RCPTS_TOT_COST_AMT					DECIMAL(32, 4)
	, CP_RCPTS_TOT_UNITS					BIGINT
	, CP_RCPTS_RESERVE_COST_AMT				DECIMAL(32, 4)
	, CP_RCPTS_RESERVE_UNITS	    		BIGINT
	-- Recls
	, CP_RECLASS_IN_COST_AMT	    		DECIMAL(32, 4)
	, CP_RECLASS_IN_UNITS	        		BIGINT
	, CP_RECLASS_OUT_COST_AMT	    		DECIMAL(32, 4)
	, CP_RECLASS_OUT_UNITS	        		BIGINT
	, CP_RECLASS_TOT_COST_AMT	    		DECIMAL(32, 4)
	, CP_RECLASS_TOT_UNITS	        		BIGINT
	-- Return to Vendor
	, CP_RTV_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, CP_RTV_ACTIVE_UNITS	        		BIGINT
	, CP_RTV_INACTIVE_COST_AMT  			DECIMAL(32, 4)
	, CP_RTV_INACTIVE_UNITS	        		BIGINT
	-- MOS
	, CP_MOS_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, CP_MOS_ACTIVE_UNITS	        		BIGINT
	, CP_MOS_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, CP_MOS_INACTIVE_UNITS	        		BIGINT
	-- Vendor Funds
	, CP_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
-- OP Metrics
	-- Inventory
	, OP_BOP_ACTIVE_UNITS	        		BIGINT
	, OP_BOP_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_BOP_INACTIVE_UNITS	        		BIGINT
	, OP_BOP_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_BOP_TOT_COST_AMT	        		DECIMAL(32, 4)
	, OP_BOP_TOT_UNITS	            		BIGINT
	, OP_EOP_ACTIVE_UNITS	        		BIGINT
	, OP_EOP_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_EOP_INACTIVE_UNITS	        		BIGINT
	, OP_EOP_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_EOP_TOT_COST_AMT	        		DECIMAL(32, 4)
	, OP_EOP_TOT_UNITS	            		BIGINT
	, OP_BOP_ACTIVE_TGT_UNITS	    		BIGINT
	-- Inventory Movement
	, OP_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, OP_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	, OP_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, OP_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	, OP_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, OP_TRANSFER_INACTIVE_IN_UNITS			BIGINT
	, OP_TRANSFER_INACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, OP_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	, OP_INV_MVMT_IN_DS_COST_AMT			DECIMAL(32, 4)
	, OP_INV_MVMT_IN_DS_UNITS	    		BIGINT
	, OP_INV_MVMT_OUT_DS_COST_AMT			DECIMAL(32, 4)
	, OP_INV_MVMT_OUT_DS_UNITS	    		BIGINT
	, OP_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	, OP_INV_MVMT_IN_TOT_UNITS	    		BIGINT
	, OP_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	, OP_INV_MVMT_OUT_TOT_UNITS	    		BIGINT
	, OP_INV_OTHER_IN_COST_AMT	    		DECIMAL(32, 4)
	, OP_INV_OTHER_IN_UNITS	        		BIGINT
	, OP_INV_OTHER_OUT_COST_AMT	    		DECIMAL(32, 4)
	, OP_INV_OTHER_OUT_UNITS	    		BIGINT
	, OP_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	, OP_INV_RACK_IN_UNITS					BIGINT
	, OP_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	, OP_INV_RACK_OUT_UNITS					BIGINT
	-- Margin 
	, OP_MERCH_MARGIN_AMT	        		DECIMAL(32, 4)
	-- Invoice Payment Terms
	, OP_INVOICE_PAYMENT_COST_AMT			DECIMAL(32, 4)
	-- Receipts
	, OP_RCPTS_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_RCPTS_ACTIVE_UNITS	        		BIGINT
	, OP_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	, OP_RCPTS_INACTIVE_UNITS	    		BIGINT
	, OP_RCPTS_TOT_COST_AMT	        		DECIMAL(32, 4)
	, OP_RCPTS_TOT_UNITS	        		BIGINT
	, OP_RCPTS_RESERVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_RCPTS_RESERVE_UNITS	    		BIGINT
	-- Recls
	, OP_RECLASS_IN_COST_AMT	    		DECIMAL(32, 4)
	, OP_RECLASS_IN_UNITS	        		BIGINT
	, OP_RECLASS_OUT_COST_AMT	    		DECIMAL(32, 4)
	, OP_RECLASS_OUT_UNITS	        		BIGINT
	, OP_RECLASS_TOT_COST_AMT	    		DECIMAL(32, 4)
	, OP_RECLASS_TOT_UNITS	        		BIGINT
	-- Return to Vendor
	, OP_RTV_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_RTV_ACTIVE_UNITS	        		BIGINT
	, OP_RTV_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_RTV_INACTIVE_UNITS	        		BIGINT
	-- MOS 
	, OP_MOS_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_MOS_ACTIVE_UNITS	        		BIGINT
	, OP_MOS_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, OP_MOS_INACTIVE_UNITS	        		BIGINT
	-- Vendor Funds
	, OP_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
-- SP Metrics
	-- Inventory
	, SP_BOP_ACTIVE_UNITS	        		BIGINT
	, SP_BOP_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, SP_BOP_INACTIVE_UNITS	        		BIGINT
	, SP_BOP_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, SP_BOP_TOT_COST_AMT	        		DECIMAL(32, 4)
	, SP_BOP_TOT_UNITS	            		BIGINT
	, SP_EOP_ACTIVE_UNITS	        		BIGINT
	, SP_EOP_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, SP_EOP_INACTIVE_UNITS	        		BIGINT
	, SP_EOP_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, SP_EOP_TOT_COST_AMT	        		DECIMAL(32, 4)
	, SP_EOP_TOT_UNITS	            		BIGINT
	, SP_BOP_ACTIVE_TGT_UNITS	    		BIGINT
	-- Inventory Movement
	, SP_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, SP_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	, SP_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, SP_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	, SP_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, SP_TRANSFER_INACTIVE_IN_UNITS			BIGINT
	, SP_TRANSFER_INACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, SP_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	, SP_INV_MVMT_IN_DS_COST_AMT			DECIMAL(32, 4)
	, SP_INV_MVMT_IN_DS_UNITS	    		BIGINT
	, SP_INV_MVMT_OUT_DS_COST_AMT			DECIMAL(32, 4)
	, SP_INV_MVMT_OUT_DS_UNITS	    		BIGINT
	, SP_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	, SP_INV_MVMT_IN_TOT_UNITS	    		BIGINT
	, SP_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	, SP_INV_MVMT_OUT_TOT_UNITS	    		BIGINT
	, SP_INV_OTHER_IN_COST_AMT	    		DECIMAL(32, 4)
	, SP_INV_OTHER_IN_UNITS	        		BIGINT
	, SP_INV_OTHER_OUT_COST_AMT	    		DECIMAL(32, 4)
	, SP_INV_OTHER_OUT_UNITS	    		BIGINT
	, SP_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	, SP_INV_RACK_IN_UNITS					BIGINT
	, SP_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	, SP_INV_RACK_OUT_UNITS					BIGINT
	-- Margin
	, SP_MERCH_MARGIN_AMT	        		DECIMAL(32, 4)
	-- Invoice Payment Terms
	, SP_INVOICE_PAYMENT_COST_AMT			DECIMAL(32, 4)
	-- Receipts
	, SP_RCPTS_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, SP_RCPTS_ACTIVE_UNITS	        		BIGINT
	, SP_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	, SP_RCPTS_INACTIVE_UNITS	    		BIGINT
	, SP_RCPTS_TOT_COST_AMT	        		DECIMAL(32, 4)
	, SP_RCPTS_TOT_UNITS	        		BIGINT
	, SP_RCPTS_RESERVE_COST_AMT	    		DECIMAL(32, 4)
	, SP_RCPTS_RESERVE_UNITS	    		BIGINT
	-- Recls
	, SP_RECLASS_IN_COST_AMT	    		DECIMAL(32, 4)
	, SP_RECLASS_IN_UNITS	        		BIGINT
	, SP_RECLASS_OUT_COST_AMT	    		DECIMAL(32, 4)
	, SP_RECLASS_OUT_UNITS	        		BIGINT
	, SP_RECLASS_TOT_COST_AMT	    		DECIMAL(32, 4)
	, SP_RECLASS_TOT_UNITS					BIGINT
	-- Return to Vendor
	, SP_RTV_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, SP_RTV_ACTIVE_UNITS					BIGINT
	, SP_RTV_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, SP_RTV_INACTIVE_UNITS					BIGINT
	-- MOS
	, SP_MOS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, SP_MOS_ACTIVE_UNITS					BIGINT
	, SP_MOS_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, SP_MOS_INACTIVE_UNITS					BIGINT
	-- Vendor Funds
	, SP_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
-- QP Metrics
	-- Inventory
	, QP_BOP_ACTIVE_UNITS	        		BIGINT
	, QP_BOP_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, QP_BOP_INACTIVE_UNITS	        		BIGINT
	, QP_BOP_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, QP_BOP_TOT_COST_AMT	        		DECIMAL(32, 4)
	, QP_BOP_TOT_UNITS	            		BIGINT
	, QP_EOP_ACTIVE_UNITS	        		BIGINT
	, QP_EOP_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, QP_EOP_INACTIVE_UNITS	        		BIGINT
	, QP_EOP_INACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, QP_EOP_TOT_COST_AMT	        		DECIMAL(32, 4)
	, QP_EOP_TOT_UNITS	            		BIGINT
	, QP_BOP_ACTIVE_TGT_UNITS	    		BIGINT
	-- Inventory Movement
	, QP_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, QP_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	, QP_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, QP_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	, QP_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, QP_TRANSFER_INACTIVE_IN_UNITS			BIGINT
	, QP_TRANSFER_INACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, QP_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	, QP_INV_MVMT_IN_DS_COST_AMT			DECIMAL(32, 4)
	, QP_INV_MVMT_IN_DS_UNITS	    		BIGINT
	, QP_INV_MVMT_OUT_DS_COST_AMT			DECIMAL(32, 4)
	, QP_INV_MVMT_OUT_DS_UNITS	    		BIGINT
	, QP_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	, QP_INV_MVMT_IN_TOT_UNITS	    		BIGINT
	, QP_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	, QP_INV_MVMT_OUT_TOT_UNITS	    		BIGINT
	, QP_INV_OTHER_IN_COST_AMT	    		DECIMAL(32, 4)
	, QP_INV_OTHER_IN_UNITS	        		BIGINT
	, QP_INV_OTHER_OUT_COST_AMT	    		DECIMAL(32, 4)
	, QP_INV_OTHER_OUT_UNITS	    		BIGINT
	, QP_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	, QP_INV_RACK_IN_UNITS					BIGINT
	, QP_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	, QP_INV_RACK_OUT_UNITS					BIGINT
	-- Margin
	, QP_MERCH_MARGIN_AMT	        		DECIMAL(32, 4)
	-- Invoice Payment Terms
	, QP_INVOICE_PAYMENT_COST_AMT			DECIMAL(32, 4)
	-- Receipts
	, QP_RCPTS_ACTIVE_COST_AMT	    		DECIMAL(32, 4)
	, QP_RCPTS_ACTIVE_UNITS	        		BIGINT
	, QP_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	, QP_RCPTS_INACTIVE_UNITS	    		BIGINT
	, QP_RCPTS_TOT_COST_AMT	        		DECIMAL(32, 4)
	, QP_RCPTS_TOT_UNITS	        		BIGINT
	, QP_RCPTS_RESERVE_COST_AMT	    		DECIMAL(32, 4)
	, QP_RCPTS_RESERVE_UNITS	    		BIGINT
	-- Recls
	, QP_RECLASS_IN_COST_AMT	    		DECIMAL(32, 4)
	, QP_RECLASS_IN_UNITS	        		BIGINT
	, QP_RECLASS_OUT_COST_AMT	    		DECIMAL(32, 4)
	, QP_RECLASS_OUT_UNITS	        		BIGINT
	, QP_RECLASS_TOT_COST_AMT	    		DECIMAL(32, 4)
	, QP_RECLASS_TOT_UNITS					BIGINT
	-- Return to Vendor
	, QP_RTV_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, QP_RTV_ACTIVE_UNITS					BIGINT
	, QP_RTV_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, QP_RTV_INACTIVE_UNITS					BIGINT
	-- MOS
	, QP_MOS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, QP_MOS_ACTIVE_UNITS					BIGINT
	, QP_MOS_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, QP_MOS_INACTIVE_UNITS					BIGINT
	-- Vendor Funds
	, QP_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
-- TY Metrics
	-- Inventory
	, TY_BOP_ACTIVE_UNITS					BIGINT
	, TY_BOP_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_BOP_INACTIVE_UNITS					BIGINT
	, TY_BOP_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_BOP_TOT_COST_AMT					DECIMAL(32, 4)
	, TY_BOP_TOT_UNITS						BIGINT
	, TY_EOP_ACTIVE_UNITS					BIGINT
	, TY_EOP_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_EOP_INACTIVE_UNITS					BIGINT
	, TY_EOP_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_EOP_TOT_COST_AMT					DECIMAL(32, 4)
	, TY_EOP_TOT_UNITS						BIGINT
	-- Inventory Movement
	, TY_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, TY_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	, TY_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, TY_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	, TY_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, TY_TRANSFER_INACTIVE_IN_UNITS			BIGINT
	, TY_TRANSFER_INACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, TY_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	, TY_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	, TY_INV_MVMT_IN_TOT_UNITS				BIGINT
	, TY_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	, TY_INV_MVMT_OUT_TOT_UNITS				BIGINT
	, TY_INV_OTHER_IN_COST_AMT				DECIMAL(32, 4)
	, TY_INV_OTHER_IN_UNITS					BIGINT
	, TY_INV_OTHER_OUT_COST_AMT				DECIMAL(32, 4)
	, TY_INV_OTHER_OUT_UNITS				BIGINT
	, TY_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	, TY_INV_RACK_IN_UNITS					BIGINT
	, TY_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	, TY_INV_RACK_OUT_UNITS					BIGINT
	-- Margin
	, TY_MERCH_MARGIN_AMT					DECIMAL(32, 4)
	-- Invoice Payment Terms
	, TY_INVOICE_PAYMENT_COST_AMT			DECIMAL(32, 4)
		--, TY_DEMAND_UNITS						BIGINT
		--, TY_DEMAND_RETL_AMT					DECIMAL(32, 4)
		--, TY_GROSS_MARGIN_AMT					DECIMAL(32, 4)
	-- Receipts
	, TY_RCPTS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_RCPTS_ACTIVE_UNITS					BIGINT
	, TY_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	, TY_RCPTS_INACTIVE_UNITS				BIGINT
	, TY_RCPTS_TOT_COST_AMT					DECIMAL(32, 4)
	, TY_RCPTS_TOT_UNITS					BIGINT
	-- Reclass
	, TY_RECLASS_IN_COST_AMT				DECIMAL(32, 4)
	, TY_RECLASS_IN_UNITS					BIGINT
	, TY_RECLASS_OUT_COST_AMT				DECIMAL(32, 4)
	, TY_RECLASS_OUT_UNITS					BIGINT
	, TY_RECLASS_TOT_COST_AMT				DECIMAL(32, 4)
	, TY_RECLASS_TOT_UNITS					BIGINT
	-- Return to Vendor
	, TY_RTV_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_RTV_ACTIVE_UNITS					BIGINT
	, TY_RTV_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_RTV_INACTIVE_UNITS					BIGINT
	-- MOS
	, TY_MOS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_MOS_ACTIVE_UNITS					BIGINT
	, TY_MOS_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, TY_MOS_INACTIVE_UNITS					BIGINT
	-- Vendor Funds
	, TY_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
-- LY Metrics
	-- Inventory
	, LY_BOP_ACTIVE_UNITS					BIGINT
	, LY_BOP_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_BOP_INACTIVE_UNITS					BIGINT
	, LY_BOP_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_BOP_TOT_COST_AMT					DECIMAL(32, 4)
	, LY_BOP_TOT_UNITS						BIGINT
	, LY_EOP_ACTIVE_UNITS					BIGINT
	, LY_EOP_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_EOP_INACTIVE_UNITS					BIGINT
	, LY_EOP_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_EOP_TOT_COST_AMT					DECIMAL(32, 4)
	, LY_EOP_TOT_UNITS						BIGINT
	-- Inventory Movement
	, LY_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, LY_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	, LY_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, LY_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	, LY_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	, LY_TRANSFER_INACTIVE_IN_UNITS			BIGINT
	, LY_TRANSFER_INACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	, LY_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	, LY_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	, LY_INV_MVMT_IN_TOT_UNITS				BIGINT
	, LY_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	, LY_INV_MVMT_OUT_TOT_UNITS				BIGINT
	, LY_INV_OTHER_IN_COST_AMT				DECIMAL(32, 4)
	, LY_INV_OTHER_IN_UNITS					BIGINT
	, LY_INV_OTHER_OUT_COST_AMT				DECIMAL(32, 4)
	, LY_INV_OTHER_OUT_UNITS				BIGINT
	, LY_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	, LY_INV_RACK_IN_UNITS					BIGINT
	, LY_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	, LY_INV_RACK_OUT_UNITS					BIGINT
	-- Margin
	, LY_MERCH_MARGIN_AMT					DECIMAL(32, 4)
	-- Invoice Payment Terms
	, LY_INVOICE_PAYMENT_COST_AMT			DECIMAL(32, 4)
	-- Receipts
	, LY_RCPTS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_RCPTS_ACTIVE_UNITS					BIGINT
	, LY_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	, LY_RCPTS_INACTIVE_UNITS				BIGINT
	, LY_RCPTS_TOT_COST_AMT					DECIMAL(32, 4)
	, LY_RCPTS_TOT_UNITS					BIGINT
	-- Recl
	, LY_RECLASS_IN_COST_AMT				DECIMAL(32, 4)
	, LY_RECLASS_IN_UNITS					BIGINT
	, LY_RECLASS_OUT_COST_AMT				DECIMAL(32, 4)
	, LY_RECLASS_OUT_UNITS					BIGINT
	, LY_RECLASS_TOT_COST_AMT				DECIMAL(32, 4)
	, LY_RECLASS_TOT_UNITS					BIGINT
	-- RTV
	, LY_RTV_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_RTV_ACTIVE_UNITS					BIGINT
	, LY_RTV_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_RTV_INACTIVE_UNITS					BIGINT
	-- MOS
	, LY_MOS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_MOS_ACTIVE_UNITS					BIGINT
	, LY_MOS_INACTIVE_COST_AMT				DECIMAL(32, 4)
	, LY_MOS_INACTIVE_UNITS					BIGINT
	-- Vendor Funds
	, LY_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
-- LY TRUEDAY Metrics
	-- Inventory
	,  LY_TRUEDAY_BOP_ACTIVE_UNITS			BIGINT
	,  LY_TRUEDAY_BOP_ACTIVE_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_BOP_INACTIVE_UNITS		BIGINT
	,  LY_TRUEDAY_BOP_INACTIVE_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_BOP_TOT_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_BOP_TOT_UNITS				BIGINT
	,  LY_TRUEDAY_EOP_ACTIVE_UNITS			BIGINT
	,  LY_TRUEDAY_EOP_ACTIVE_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_EOP_INACTIVE_UNITS		BIGINT
	,  LY_TRUEDAY_EOP_INACTIVE_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_EOP_TOT_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_EOP_TOT_UNITS				BIGINT
	-- Inventory Movement
	,  LY_TRUEDAY_TRANSFER_ACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_TRANSFER_ACTIVE_IN_UNITS			BIGINT
	,  LY_TRUEDAY_TRANSFER_ACTIVE_OUT_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_TRANSFER_ACTIVE_OUT_UNITS			BIGINT
	,  LY_TRUEDAY_TRANSFER_INACTIVE_IN_COST_AMT		DECIMAL(32, 4)
	,  LY_TRUEDAY_TRANSFER_INACTIVE_IN_UNITS		BIGINT
	,  LY_TRUEDAY_TRANSFER_INACTIVE_OUT_COST_AMT	DECIMAL(32, 4)
	,  LY_TRUEDAY_TRANSFER_INACTIVE_OUT_UNITS		BIGINT
	,  LY_TRUEDAY_INV_MVMT_IN_TOT_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_INV_MVMT_IN_TOT_UNITS				BIGINT
	,  LY_TRUEDAY_INV_MVMT_OUT_TOT_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_INV_MVMT_OUT_TOT_UNITS			BIGINT
	,  LY_TRUEDAY_INV_OTHER_IN_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_INV_OTHER_IN_UNITS				BIGINT
	,  LY_TRUEDAY_INV_OTHER_OUT_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_INV_OTHER_OUT_UNITS				BIGINT
	,  LY_TRUEDAY_INV_RACK_IN_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_INV_RACK_IN_UNITS					BIGINT
	,  LY_TRUEDAY_INV_RACK_OUT_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_INV_RACK_OUT_UNITS				BIGINT
	-- Margin
	,  LY_TRUEDAY_MERCH_MARGIN_AMT					DECIMAL(32, 4)
	-- Invoice Payment Terms
	,  LY_TRUEDAY_INVOICE_PAYMENT_COST_AMT			DECIMAL(32, 4)
	-- Receipts
	,  LY_TRUEDAY_RCPTS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RCPTS_ACTIVE_UNITS				BIGINT
	,  LY_TRUEDAY_RCPTS_INACTIVE_COST_AMT			DECIMAL(32, 4)
	,  LY_TRUEDAY_RCPTS_INACTIVE_UNITS				BIGINT
	,  LY_TRUEDAY_RCPTS_TOT_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RCPTS_TOT_UNITS					BIGINT
	-- Recl
	,  LY_TRUEDAY_RECLASS_IN_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RECLASS_IN_UNITS					BIGINT
	,  LY_TRUEDAY_RECLASS_OUT_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RECLASS_OUT_UNITS					BIGINT
	,  LY_TRUEDAY_RECLASS_TOT_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RECLASS_TOT_UNITS					BIGINT
	-- RTV
	,  LY_TRUEDAY_RTV_ACTIVE_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RTV_ACTIVE_UNITS					BIGINT
	,  LY_TRUEDAY_RTV_INACTIVE_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_RTV_INACTIVE_UNITS				BIGINT
	-- MOS
	,  LY_TRUEDAY_MOS_ACTIVE_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_MOS_ACTIVE_UNITS					BIGINT
	,  LY_TRUEDAY_MOS_INACTIVE_COST_AMT				DECIMAL(32, 4)
	,  LY_TRUEDAY_MOS_INACTIVE_UNITS				BIGINT
	-- Vendor Funds
	,  LY_TRUEDAY_VENDOR_FUNDS_COST_AMT				DECIMAL(32, 4)
	-- PROCCESS TIMESTAMP
	, process_tmstp 						TIMESTAMP(6) WITH TIME ZONE
	
)
PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER_COUNTRY_NUM, FULFILL_TYPE_NUM)
;

GRANT SELECT ON T2DL_DAS_ACE_MFP.MFP_BANNER_COUNTRY_CHANNEL_STG{env_suffix} TO PUBLIC;