SET QUERY_BAND = 'App_ID=APP08629;
     DAG_ID=rakuten_publisher_daily_vw_11521_ACE_ENG;
     Task_Name=rakuten_publisher_daily_vw;'
     FOR SESSION VOLATILE;

--T2/View Name: {apd_t2_schema}.rakuten_publisher_daily_vw
--Team/Owner: Analytics Engineering
--Date Created/Modified: 2023-09-27
--Note:
-- This view supports the 4 BOX Affiliates Performance Dashboard-Consolidated Version.


Replace VIEW {apd_t2_schema}.rakuten_publisher_daily_vw 
AS
LOCK ROW FOR ACCESS 
SELECT
    day_dt
    , DAY_NUM
    , FISCAL_WEEK
    , BANNER
    , UTM_CAMPAIGN
    , PUBLISHER
    , PUBLISHER_GROUP
    , PUBLISHER_SUBGROUP 
     -- TY
	, max(aff_return_rate) as aff_return_rate
    , sum(attributed_demand) as attributed_demand
    , sum(attributed_orders) as attributed_orders
    , sum(attributed_net_sales) as attributed_net_sales
	, sum(ACQUIRED_ATTRIBUTED_DEMAND) as ACQUIRED_ATTRIBUTED_DEMAND
    , sum(ACQUIRED_ATTRIBUTED_ORDERS) as ACQUIRED_ATTRIBUTED_ORDERS
	, sum(RETAINED_ATTRIBUTED_ORDERS) as RETAINED_ATTRIBUTED_ORDERS	
    , sum(CLICKS) as CLICKS
	, sum(SESSIONS) as SESSIONS
	, sum(PAID_PLACEMENT) as PAID_PLACEMENT
    , sum(DAILY_COST) as DAILY_COST
	, sum(RAKUTEN_GROSS_COMMISSIONS) as RAKUTEN_GROSS_COMMISSIONS
	, sum(ESTIMATED_NET_TOTAL_COST) as ESTIMATED_NET_TOTAL_COST
	, sum(RAKUTEN_GROSS_SALES) as RAKUTEN_GROSS_SALES
	, sum(RAKUTEN_ORDERS) as RAKUTEN_ORDERS
	, sum(RAKUTEN_NET_SALES) as RAKUTEN_NET_SALES
	, sum(RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS) as RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS
	, sum(RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND) as RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND,
     -- LY
       max(LY_aff_return_rate) AS LY_aff_return_rate,	 
       SUM(LY_ATTRIBUTED_DEMAND) AS LY_ATTRIBUTED_DEMAND,
       SUM(LY_ATTRIBUTED_ORDERS) AS LY_ATTRIBUTED_ORDERS,
       SUM(LY_ATTRIBUTED_NET_SALES) AS LY_ATTRIBUTED_NET_SALES,
       SUM(LY_ACQUIRED_ATTRIBUTED_DEMAND) AS LY_ACQUIRED_ATTRIBUTED_DEMAND,
       SUM(LY_ACQUIRED_ATTRIBUTED_ORDERS) AS LY_ACQUIRED_ATTRIBUTED_ORDERS,              
       SUM(LY_RETAINED_ATTRIBUTED_ORDERS) AS LY_RETAINED_ATTRIBUTED_ORDERS,              
       SUM(LY_CLICKS) AS LY_CLICKS,
       SUM(LY_SESSIONS) AS LY_SESSIONS,
       SUM(LY_PAID_PLACEMENT) AS LY_PAID_PLACEMENT,
	   SUM(LY_DAILY_COST) AS LY_DAILY_COST,
       SUM(LY_RAKUTEN_GROSS_COMMISSIONS) AS LY_RAKUTEN_GROSS_COMMISSIONS,
       SUM(LY_ESTIMATED_NET_TOTAL_COST) AS LY_ESTIMATED_NET_TOTAL_COST,
       SUM(LY_RAKUTEN_GROSS_SALES) AS LY_RAKUTEN_GROSS_SALES,
       SUM(LY_RAKUTEN_ORDERS) AS LY_RAKUTEN_ORDERS,       
       SUM(LY_RAKUTEN_NET_SALES) AS LY_RAKUTEN_NET_SALES,
       SUM(LY_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS) AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       SUM(LY_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND) AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND,
     --LW
	   max(LW_aff_return_rate) AS LW_aff_return_rate,	 
       SUM(LW_ATTRIBUTED_DEMAND) AS LW_ATTRIBUTED_DEMAND,
       SUM(LW_ATTRIBUTED_ORDERS) AS LW_ATTRIBUTED_ORDERS,
       SUM(LW_ATTRIBUTED_NET_SALES) AS LW_ATTRIBUTED_NET_SALES,
       SUM(LW_ACQUIRED_ATTRIBUTED_DEMAND) AS LW_ACQUIRED_ATTRIBUTED_DEMAND,
       SUM(LW_ACQUIRED_ATTRIBUTED_ORDERS) AS LW_ACQUIRED_ATTRIBUTED_ORDERS,              
       SUM(LW_RETAINED_ATTRIBUTED_ORDERS) AS LW_RETAINED_ATTRIBUTED_ORDERS,              
       SUM(LW_CLICKS) AS LW_CLICKS,
       SUM(LW_SESSIONS) AS LW_SESSIONS,
       SUM(LW_PAID_PLACEMENT) AS LW_PAID_PLACEMENT,
	   SUM(LW_DAILY_COST) AS LW_DAILY_COST,
       SUM(LW_RAKUTEN_GROSS_COMMISSIONS) AS LW_RAKUTEN_GROSS_COMMISSIONS,
       SUM(LW_ESTIMATED_NET_TOTAL_COST) AS LW_ESTIMATED_NET_TOTAL_COST,
       SUM(LW_RAKUTEN_GROSS_SALES) AS LW_RAKUTEN_GROSS_SALES,
       SUM(LW_RAKUTEN_ORDERS) AS LW_RAKUTEN_ORDERS,       
       SUM(LW_RAKUTEN_NET_SALES) AS LW_RAKUTEN_NET_SALES,
       SUM(LW_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS) AS LW_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       SUM(LW_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND) AS LW_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND  
FROM (
    --TY
    SELECT
        d.day_date AS day_dt
       , d.DAY_NUM
        ,CONCAT(d.month_short_desc,' ',d.week_desc) AS FISCAL_WEEK
        , mpcs_ty.BANNER
        , mpcs_ty.UTM_CAMPAIGN
        , mpcs_ty.PUBLISHER
        , mpcs_ty.PUBLISHER_GROUP
        , mpcs_ty.PUBLISHER_SUBGROUP              
        -- TY
	, mpcs_ty.aff_return_rate      	
    , mpcs_ty.attributed_demand
    , mpcs_ty.attributed_orders
    , mpcs_ty.attributed_net_sales
	, mpcs_ty.ACQUIRED_ATTRIBUTED_DEMAND
    , mpcs_ty.ACQUIRED_ATTRIBUTED_ORDERS
	, mpcs_ty.RETAINED_ATTRIBUTED_ORDERS	
    , mpcs_ty.CLICKS
	, mpcs_ty.SESSIONS
	, mpcs_ty.PAID_PLACEMENT
    , mpcs_ty.DAILY_COST
	, mpcs_ty.RAKUTEN_GROSS_COMMISSIONS
	, mpcs_ty.ESTIMATED_NET_TOTAL_COST
	, mpcs_ty.RAKUTEN_GROSS_SALES
	, mpcs_ty.RAKUTEN_ORDERS
	, mpcs_ty.RAKUTEN_NET_SALES
	, mpcs_ty.RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS
	, mpcs_ty.RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND,            
        -- LY
	  CAST(0 AS FLOAT) AS LY_aff_return_rate,	
      CAST(0 AS FLOAT) AS LY_ATTRIBUTED_DEMAND,
      CAST(0 AS FLOAT) AS LY_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LY_ATTRIBUTED_NET_SALES,
       CAST(0 AS FLOAT) AS LY_ACQUIRED_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LY_ACQUIRED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LY_RETAINED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LY_CLICKS,
       CAST(0 AS FLOAT) AS LY_SESSIONS,
       CAST(0 AS FLOAT) AS LY_PAID_PLACEMENT,
	   CAST(0 AS FLOAT) AS LY_DAILY_COST,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_GROSS_COMMISSIONS,
       CAST(0 AS FLOAT) AS LY_ESTIMATED_NET_TOTAL_COST,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_GROSS_SALES,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_ORDERS,       
       CAST(0 AS FLOAT) AS LY_RAKUTEN_NET_SALES,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND,
       ---LW
	   CAST(0 AS FLOAT) AS LW_aff_return_rate,	
       CAST(0 AS FLOAT) AS LW_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LW_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LW_ATTRIBUTED_NET_SALES,
       CAST(0 AS FLOAT) AS LW_ACQUIRED_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LW_ACQUIRED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LW_RETAINED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LW_CLICKS,
       CAST(0 AS FLOAT) AS LW_SESSIONS,
       CAST(0 AS FLOAT) AS LW_PAID_PLACEMENT,
	   CAST(0 AS FLOAT) AS LW_DAILY_COST,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_GROSS_COMMISSIONS,
       CAST(0 AS FLOAT) AS LW_ESTIMATED_NET_TOTAL_COST,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_GROSS_SALES,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_ORDERS,       
       CAST(0 AS FLOAT) AS LW_RAKUTEN_NET_SALES,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND
    FROM PRD_NAP_USR_VWS.DAY_CAL d
        inner join {apd_t2_schema}.rakuten_publisher_daily mpcs_ty
            on d.day_date =  mpcs_ty.day_dt
    UNION ALL
    --LY
    SELECT
        d.day_date AS day_dt
        ,d.DAY_NUM
       ,CONCAT(d.month_short_desc,' ',d.week_desc) AS FISCAL_WEEK
        , mpcs_ly.BANNER
        , mpcs_ly.UTM_CAMPAIGN
        , mpcs_ly.PUBLISHER
        , mpcs_ly.PUBLISHER_GROUP
        , mpcs_ly.PUBLISHER_SUBGROUP        
        -- TY
		,CAST(0 AS FLOAT) AS aff_return_rate
       ,CAST(0 AS FLOAT) AS attributed_demand
	,CAST(0 AS FLOAT) AS attributed_orders
    , CAST(0 AS FLOAT) AS attributed_net_sales
	, CAST(0 AS FLOAT) AS ACQUIRED_ATTRIBUTED_DEMAND
    , CAST(0 AS FLOAT) AS ACQUIRED_ATTRIBUTED_ORDERS
	, CAST(0 AS FLOAT) AS RETAINED_ATTRIBUTED_ORDERS	
    , CAST(0 AS FLOAT) AS CLICKS
	, CAST(0 AS FLOAT) AS SESSIONS
	, CAST(0 AS FLOAT) AS PAID_PLACEMENT
    , CAST(0 AS FLOAT) AS DAILY_COST
	, CAST(0 AS FLOAT) AS RAKUTEN_GROSS_COMMISSIONS
	, CAST(0 AS FLOAT) AS ESTIMATED_NET_TOTAL_COST
	, CAST(0 AS FLOAT) AS RAKUTEN_GROSS_SALES
	, CAST(0 AS FLOAT) AS RAKUTEN_ORDERS
	, cast(0 AS FLOAT) AS RAKUTEN_NET_SALES
	, CAST(0 AS FLOAT) AS RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS
	, CAST(0 AS FLOAT) AS RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND 
        -- LY
		, mpcs_ly.aff_return_rate     AS ly_aff_return_rate
        , mpcs_ly.attributed_demand     AS ly_attributed_demand
        , mpcs_ly.attributed_orders      AS ly_attributed_orders
        , mpcs_ly.attributed_net_sales     AS ly_attributed_net_sales
	    , mpcs_ly.acquired_attributed_demand    AS ly_acquired_attributed_demand
        , mpcs_ly.acquired_attributed_orders  AS ly_acquired_attributed_orders,
        mpcs_ly.retained_attributed_orders   AS ly_retained_attributed_orders,
		mpcs_ly.CLICKS AS LY_CLICKS,
       mpcs_ly.SESSIONS AS LY_SESSIONS,
       mpcs_ly.PAID_PLACEMENT as LY_PAID_PLACEMENT,
	   mpcs_ly.DAILY_COST as LY_DAILY_COST,
       mpcs_ly.RAKUTEN_GROSS_COMMISSIONS AS LY_RAKUTEN_GROSS_COMMISSIONS,
       mpcs_ly.ESTIMATED_NET_TOTAL_COST AS LY_ESTIMATED_NET_TOTAL_COST,
       mpcs_ly.RAKUTEN_GROSS_SALES AS LY_RAKUTEN_GROSS_SALES,
       mpcs_ly.RAKUTEN_ORDERS AS LY_RAKUTEN_ORDERS,       
       mpcs_ly.RAKUTEN_NET_SALES AS LY_RAKUTEN_NET_SALES,
       mpcs_ly.RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       mpcs_ly.RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND,
       ---LW
	   CAST(0 AS FLOAT) AS LW_aff_return_rate,
       CAST(0 AS FLOAT) AS LW_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LW_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LW_ATTRIBUTED_NET_SALES,
       CAST(0 AS FLOAT) AS LW_ACQUIRED_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LW_ACQUIRED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LW_RETAINED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LW_CLICKS,
       CAST(0 AS FLOAT) AS LW_SESSIONS,
       CAST(0 AS FLOAT) AS LW_PAID_PLACEMENT,
	   CAST(0 AS FLOAT) AS LW_DAILY_COST,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_GROSS_COMMISSIONS,
       CAST(0 AS FLOAT) AS LW_ESTIMATED_NET_TOTAL_COST,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_GROSS_SALES,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_ORDERS,       
       CAST(0 AS FLOAT) AS LW_RAKUTEN_NET_SALES,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LW_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND
    FROM PRD_NAP_USR_VWS.DAY_CAL d
        inner join {apd_t2_schema}.rakuten_publisher_daily mpcs_ly
            on d.last_year_day_date_realigned =  mpcs_ly.day_dt
    union ALL 
    --LW
    	SELECT
        d.day_date AS day_dt
        ,d.DAY_NUM
       ,CONCAT(d.month_short_desc,' ',d.week_desc) AS FISCAL_WEEK
        , mpcs_lw.BANNER
        , mpcs_lw.UTM_CAMPAIGN
        , mpcs_lw.PUBLISHER
        , mpcs_lw.PUBLISHER_GROUP
        , mpcs_lw.PUBLISHER_SUBGROUP                
        -- TY
		,CAST(0 AS FLOAT) AS aff_return_rate
       ,CAST(0 AS FLOAT) AS attributed_demand
	,CAST(0 AS FLOAT) AS attributed_orders
    , CAST(0 AS FLOAT) AS attributed_net_sales
	, CAST(0 AS FLOAT) AS ACQUIRED_ATTRIBUTED_DEMAND
    , CAST(0 AS FLOAT) AS ACQUIRED_ATTRIBUTED_ORDERS
	, CAST(0 AS FLOAT) AS RETAINED_ATTRIBUTED_ORDERS	
    , CAST(0 AS FLOAT) AS CLICKS
	, CAST(0 AS FLOAT) AS SESSIONS
	, CAST(0 AS FLOAT) AS PAID_PLACEMENT
    , CAST(0 AS FLOAT) AS DAILY_COST
	, CAST(0 AS FLOAT) AS RAKUTEN_GROSS_COMMISSIONS
	, CAST(0 AS FLOAT) AS ESTIMATED_NET_TOTAL_COST
	, CAST(0 AS FLOAT) AS RAKUTEN_GROSS_SALES
	, CAST(0 AS FLOAT) AS RAKUTEN_ORDERS
	, CAST(0 AS FLOAT) AS RAKUTEN_NET_SALES
	, CAST(0 AS FLOAT) AS RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS
	, CAST(0 AS FLOAT) AS RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND, 
        -- LY
	   CAST(0 AS FLOAT) AS ly_aff_return_rate,
       CAST(0 AS FLOAT) AS LY_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LY_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LY_ATTRIBUTED_NET_SALES,
       CAST(0 AS FLOAT) AS LY_ACQUIRED_ATTRIBUTED_DEMAND,
       CAST(0 AS FLOAT) AS LY_ACQUIRED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LY_RETAINED_ATTRIBUTED_ORDERS,              
       CAST(0 AS FLOAT) AS LY_CLICKS,
       CAST(0 AS FLOAT) AS LY_SESSIONS,
       CAST(0 AS FLOAT) AS LY_PAID_PLACEMENT,
	   CAST(0 AS FLOAT) AS LY_DAILY_COST,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_GROSS_COMMISSIONS,
       CAST(0 AS FLOAT) AS LY_ESTIMATED_NET_TOTAL_COST,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_GROSS_SALES,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_ORDERS,       
       CAST(0 AS FLOAT) AS LY_RAKUTEN_NET_SALES,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       CAST(0 AS FLOAT) AS LY_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND
       ---LW
	    , mpcs_lw.aff_return_rate     AS lw_aff_return_rate
        , mpcs_lw.attributed_demand     AS lw_attributed_demand
        , mpcs_lw.attributed_orders      AS lw_attributed_orders
        , mpcs_lw.attributed_net_sales     AS lw_attributed_net_sales
	    , mpcs_lw.acquired_attributed_demand    AS lw_acquired_attributed_demand
        , mpcs_lw.acquired_attributed_orders  AS lw_acquired_attributed_orders,
        mpcs_lw.retained_attributed_orders   AS lw_retained_attributed_orders,
		mpcs_lw.CLICKS AS Lw_CLICKS,
       mpcs_lw.SESSIONS AS Lw_SESSIONS,
       mpcs_lw.PAID_PLACEMENT as Lw_PAID_PLACEMENT,
	   mpcs_lw.DAILY_COST as Lw_DAILY_COST,
       mpcs_lw.RAKUTEN_GROSS_COMMISSIONS AS Lw_RAKUTEN_GROSS_COMMISSIONS,
       mpcs_lw.ESTIMATED_NET_TOTAL_COST AS Lw_ESTIMATED_NET_TOTAL_COST,
       mpcs_lw.RAKUTEN_GROSS_SALES AS Lw_RAKUTEN_GROSS_SALES,
       mpcs_lw.RAKUTEN_ORDERS AS Lw_RAKUTEN_ORDERS,       
       mpcs_lw.RAKUTEN_NET_SALES AS Lw_RAKUTEN_NET_SALES,
       mpcs_lw.RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS AS Lw_RAKUTEN_ACQUIRED_ATTRIBUTED_ORDERS,
       mpcs_lw.RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND AS Lw_RAKUTEN_ACQUIRED_ATTRIBUTED_DEMAND
    FROM PRD_NAP_USR_VWS.DAY_CAL d
        inner join {apd_t2_schema}.rakuten_publisher_daily mpcs_lw
            on d.day_date -7 =  mpcs_lw.day_dt
) mpcs
WHERE mpcs.day_dt <= (select max(day_dt ) from {apd_t2_schema}.rakuten_publisher_daily)
GROUP BY 1, 2, 3, 4, 5, 6, 7, 8;

SET QUERY_BAND = NONE FOR SESSION;
