-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=afterpay_auth_details_update_teradata;Task_Name=job_insert_update;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary tables for selecting distinct records by 'authorization_result_ID' that have load time > max load time in the details table.
CREATE MULTISET VOLATILE TABLE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG AS (
    SELECT DISTINCT
    PAR.DW_SYS_LOAD_TMSTP,
    PAR.DW_SYS_UPDT_TMSTP,
    PAR.CHANNEL_COUNTRY,
    PAR.CHANNEL_BRAND,
    PAR.SELLING_CHANNEL,
    PAR.ACQUIRER,
    PAR.AUTHORIZATION_AMOUNT_CURRENCY_CODE,
    PAR.AUTHORIZATION_AMOUNT,
    PAR.AUTHORIZATION_RESULT_ID,
    PAR.STORE_NUMBER,
    PAR.TENDER_TYPE,
    PAR.PROCESSING_DATE,
    PAR.TRANSACTION_TIMESTAMP,
    PAR.TRANSACTION_TIME_ZONE_OFFSET_MINUTES,
    PBC.ACQUIRER_MERCHANT_IDENTIFIER,
    PBC.AUTHORIZATION_TYPE,
    PBC.CARD_TYPE,
    PBC.CARD_SUBTYPE,
    PBC.ENTRY_MODE,
    PBC.MERCHANT_CATEGORY_CODE,
    PBC.TOKEN_VALUE,
    PBC.TOKEN_AUTHORITY,
    PBC.TOKEN_DATA_CLASSIFICATION,
    PBC.TOKEN_TYPE,
    PBC.BANK_CARD_AUTHORIZATION_SOURCE,
    PBC.EXPIRATION_DATE_MONTH,
    PBC.EXPIRATION_DATE_YEAR,
    PBC.AUTHORIZATION_CODE,
    PBC.CREDIT_RESPONSE_CODE,
    PBC.CREDIT_RESPONSE_CATEGORY,
    PBC.ADDRESS_VERIFICATION_RESPONSE_CODE,
    PBC.AUTHORIZATION_SERVICE_INDICATOR,
    PBC.CVV_TWO_PRESENCE_INDICATOR,
    PBC.CVV_TWO_RESPONSE_INDICATOR,
    PBC.MAIL_PHONE_INDICATOR,
    PBC.VENDOR_AUTHORIZATION_SYSTEM,
    PBC.MASTERCARD_BANKNET_REFERENCE_NUMBER,
    PBC.MASTERCARD_BANKNET_SETTLEMENT_DATE,
    PBC.VISA_TRANSACTION_ID,
    PBC.VISA_VALIDATION_CODE,
    PBC.VISA_AUTHORIZATION_RESPONSE_CODE,
    PBC.DEBIT_RESPONSE_CODE,
    PBC.DEBIT_RESPONSE_CATEGORY,
    'N' AS ISAFTERPAY,
    cast('N/A' AS VARCHAR(128)) AS BIN_TYPE
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_RESULT_FACT AS PAR
    INNER JOIN {db_env}_NAP_BASE_VWS.PAYMENT_BANK_CARD_AUTHORIZATION_RESULT_FACT AS PBC
    ON PAR.AUTHORIZATION_RESULT_ID = PBC.AUTHORIZATION_RESULT_ID
    WHERE PAR.DW_SYS_UPDT_TMSTP > (SELECT coalesce(max(cast(DW_SYS_UPDT_TMSTP AS DATE)) - 2, cast('2023-11-01' AS DATE)) FROM {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_RESULT_DETAILS_FACT)
) WITH DATA PRIMARY INDEX (AUTHORIZATION_RESULT_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- Create temporary bin table having past 7 days records for join.
CREATE MULTISET VOLATILE TABLE PAYMENT_RESULT_BIN_LDG_TEMP AS (
    SELECT DISTINCT *
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_RESULT_BIN_FACT
    --WHERE DW_SYS_UPDT_TMSTP > (SELECT coalesce(max(cast(DW_SYS_UPDT_TMSTP AS DATE)) - 7, cast('2024-02-20' AS DATE)) FROM {db_env}_NAP_BASE_VWS.PAYMENT_RESULT_BIN_FACT)
) WITH DATA PRIMARY INDEX (ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- inner join temp table and temp bin table, and update only those records
UPDATE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG
FROM (
    SELECT DISTINCT A.AUTHORIZATION_RESULT_ID
    FROM TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG AS A
    INNER JOIN PAYMENT_RESULT_BIN_LDG_TEMP AS B
        ON A.AUTHORIZATION_AMOUNT = B.AMOUNT
        AND A.AUTHORIZATION_CODE = B.AUTHORIZATION_CODE
        AND A.STORE_NUMBER = B.STORE_NUMBER
        AND A.TENDER_TYPE = B.TENDER_TYPE
        AND A.CARD_TYPE = B.CARD_TYPE
        AND cast((A.TRANSACTION_TIMESTAMP AT 'America Pacific') AS DATE) = B.TRANSACTION_DATE --noqa
    WHERE B.BIN = '427140'
) AS C
SET ISAFTERPAY = 'Y', BIN_TYPE = 'In store'
WHERE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG.AUTHORIZATION_RESULT_ID = C.AUTHORIZATION_RESULT_ID;

UPDATE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG
FROM (
    SELECT DISTINCT A.AUTHORIZATION_RESULT_ID
    FROM TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG AS A
    INNER JOIN PAYMENT_RESULT_BIN_LDG_TEMP AS B
        ON A.AUTHORIZATION_AMOUNT = B.AMOUNT
        AND A.AUTHORIZATION_CODE = B.AUTHORIZATION_CODE
        AND A.STORE_NUMBER = B.STORE_NUMBER
        AND A.TENDER_TYPE = B.TENDER_TYPE
        AND A.CARD_TYPE = B.CARD_TYPE
        AND cast((A.TRANSACTION_TIMESTAMP AT 'America Pacific') AS DATE) = B.TRANSACTION_DATE --noqa
    WHERE B.BIN = '411361'
) AS C
SET ISAFTERPAY = 'Y', BIN_TYPE = 'Online virtual card'
WHERE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG.AUTHORIZATION_RESULT_ID = C.AUTHORIZATION_RESULT_ID;

UPDATE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG
FROM (
    SELECT DISTINCT A.AUTHORIZATION_RESULT_ID
    FROM TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG AS A
    INNER JOIN PAYMENT_RESULT_BIN_LDG_TEMP AS B
        ON A.AUTHORIZATION_AMOUNT = B.AMOUNT
        AND A.AUTHORIZATION_CODE = B.AUTHORIZATION_CODE
        AND A.STORE_NUMBER = B.STORE_NUMBER
        AND A.TENDER_TYPE = B.TENDER_TYPE
        AND A.CARD_TYPE = B.CARD_TYPE
        AND cast((A.TRANSACTION_TIMESTAMP AT 'America Pacific') AS DATE) = B.TRANSACTION_DATE --noqa
    WHERE B.BIN = '486696'
) AS C
SET ISAFTERPAY = 'Y', BIN_TYPE = 'Long term installments'
WHERE TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG.AUTHORIZATION_RESULT_ID = C.AUTHORIZATION_RESULT_ID;

--Delete if exist
DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_RESULT_DETAILS_FACT
WHERE
    AUTHORIZATION_RESULT_ID IN (SELECT AUTHORIZATION_RESULT_ID FROM TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG);

-- Insert into FACT table
INSERT INTO {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_RESULT_DETAILS_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    ACQUIRER,
    AUTHORIZATION_AMOUNT_CURRENCY_CODE,
    AUTHORIZATION_AMOUNT,
    AUTHORIZATION_RESULT_ID,
    STORE_NUMBER,
    PROCESSING_DATE,
    TENDER_TYPE,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_TIME_ZONE_OFFSET_MINUTES,
    ACQUIRER_MERCHANT_IDENTIFIER,
    AUTHORIZATION_TYPE,
    CARD_TYPE,
    CARD_SUBTYPE,
    ENTRY_MODE,
    MERCHANT_CATEGORY_CODE,
    TOKEN_VALUE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    BANK_CARD_AUTHORIZATION_SOURCE,
    EXPIRATION_DATE_MONTH,
    EXPIRATION_DATE_YEAR,
    AUTHORIZATION_CODE,
    CREDIT_RESPONSE_CODE,
    CREDIT_RESPONSE_CATEGORY,
    ADDRESS_VERIFICATION_RESPONSE_CODE,
    AUTHORIZATION_SERVICE_INDICATOR,
    CVV_TWO_PRESENCE_INDICATOR,
    CVV_TWO_RESPONSE_INDICATOR,
    MAIL_PHONE_INDICATOR,
    VENDOR_AUTHORIZATION_SYSTEM,
    MASTERCARD_BANKNET_REFERENCE_NUMBER,
    MASTERCARD_BANKNET_SETTLEMENT_DATE,
    VISA_TRANSACTION_ID,
    VISA_VALIDATION_CODE,
    VISA_AUTHORIZATION_RESPONSE_CODE,
    DEBIT_RESPONSE_CODE,
    DEBIT_RESPONSE_CATEGORY,
    ISAFTERPAY,
    BIN_TYPE
)
SELECT
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    ACQUIRER,
    AUTHORIZATION_AMOUNT_CURRENCY_CODE,
    AUTHORIZATION_AMOUNT,
    AUTHORIZATION_RESULT_ID,
    STORE_NUMBER,
    PROCESSING_DATE,
    TENDER_TYPE,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_TIME_ZONE_OFFSET_MINUTES,
    ACQUIRER_MERCHANT_IDENTIFIER,
    AUTHORIZATION_TYPE,
    CARD_TYPE,
    CARD_SUBTYPE,
    ENTRY_MODE,
    MERCHANT_CATEGORY_CODE,
    TOKEN_VALUE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    BANK_CARD_AUTHORIZATION_SOURCE,
    EXPIRATION_DATE_MONTH,
    EXPIRATION_DATE_YEAR,
    AUTHORIZATION_CODE,
    CREDIT_RESPONSE_CODE,
    CREDIT_RESPONSE_CATEGORY,
    ADDRESS_VERIFICATION_RESPONSE_CODE,
    AUTHORIZATION_SERVICE_INDICATOR,
    CVV_TWO_PRESENCE_INDICATOR,
    CVV_TWO_RESPONSE_INDICATOR,
    MAIL_PHONE_INDICATOR,
    VENDOR_AUTHORIZATION_SYSTEM,
    MASTERCARD_BANKNET_REFERENCE_NUMBER,
    MASTERCARD_BANKNET_SETTLEMENT_DATE,
    VISA_TRANSACTION_ID,
    VISA_VALIDATION_CODE,
    VISA_AUTHORIZATION_RESPONSE_CODE,
    DEBIT_RESPONSE_CODE,
    DEBIT_RESPONSE_CATEGORY,
    ISAFTERPAY,
    BIN_TYPE
FROM TEMP_PAYMENT_AUTHORIZATION_RESULT_DETAILS_STG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
