-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=afterpay_settlement_details_update_teradata;Task_Name=job_insert_update;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary tables for selecting distinct records by 'settlement_result_ID' that have load time > max load time in the details table.
CREATE MULTISET VOLATILE TABLE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG AS (
    SELECT DISTINCT
    PAR.DW_SYS_LOAD_TMSTP,
    PAR.DW_SYS_UPDT_TMSTP,
    PAR.CHANNEL_COUNTRY,
    PAR.CHANNEL_BRAND,
    PAR.SELLING_CHANNEL,
    PAR.ACQUIRER,
    PAR.SETTLEMENT_AMOUNT_CURRENCY_CODE,
    PAR.SETTLEMENT_AMOUNT,
    PAR.SETTLEMENT_RESULT_RECEIVED_ID,
    PAR.STORE_NUMBER,
    PAR.TENDER_TYPE,
    PAR.PROCESSING_DATE,
    PAR.TRANSACTION_TIMESTAMP,
    PAR.TRANSACTION_TIME_ZONE_OFFSET_MINUTES,
    PAR.TRANSACTION_TYPE,
    PBC.ACQUIRER_MERCHANT_IDENTIFIER,
    PBC.BANK_CARD_AUTHORIZATION_SOURCE,
    PBC.AUTHORIZATION_CODE,
    PBC.VENDOR_SETTLEMENT_CODE,
    PBC.EXPIRATION_DATE_MONTH,
    PBC.EXPIRATION_DATE_YEAR,
    PBC.INTERCHANGE_CODE,
    PBC.INTERCHANGE_AMOUNT_CURRENCY_CODE,
    PBC.INTERCHANGE_AMOUNT,
    PBC.MERCHANT_CATEGORY_CODE,
    PBC.ENTRY_MODE,
    PBC.TOKEN_VALUE,
    PBC.TOKEN_AUTHORITY,
    PBC.TOKEN_DATA_CLASSIFICATION,
    PBC.TOKEN_TYPE,
    PBC.TRANSACTION_MATCH_IDENTIFIER,
    PBC.CARD_TYPE,
    PBC.CARD_SUBTYPE,
    PBC.TOKEN_REQUESTOR_ID,
    PBC.CARD_PRODUCT_TYPE,
    PBC.INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE,
    PBC.INTERCHANGE_ADJUSTMENT_AMOUNT,
    PBC.INTERCHANGE_ADJUSTMENT_REASON,
    PBC.EMV_TRANSACTION_INDICATOR,
    PBC.NETWORK_REFERENCE_NUMBER,
    PBC.VISA_TRANSACTION_ID,
    PBC.MASTERCARD_BANK_NET_REFERENCE_NUMBER,
    PBC.TERMINAL_ID,
    'N' AS ISAFTERPAY,
    cast('N/A' AS VARCHAR(128)) AS BIN_TYPE
    FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_RESULT_FACT AS PAR
    INNER JOIN PREPROD_NAP_BASE_VWS.PAYMENT_BANK_CARD_SETTLEMENT_RESULT_FACT AS PBC
    ON PAR.SETTLEMENT_RESULT_RECEIVED_ID = PBC.SETTLEMENT_RESULT_RECEIVED_ID
    WHERE PAR.DW_SYS_UPDT_TMSTP > (SELECT coalesce(max(cast(DW_SYS_UPDT_TMSTP AS DATE)) - 2, cast('2023-11-01' AS DATE)) FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_RESULT_DETAILS_FACT)
) WITH DATA PRIMARY INDEX (SETTLEMENT_RESULT_RECEIVED_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- Create temporary bin table having past 7 days records for join.
CREATE MULTISET VOLATILE TABLE PAYMENT_RESULT_BIN_LDG_TEMP AS (
    SELECT DISTINCT *
    FROM PREPROD_NAP_BASE_VWS.PAYMENT_RESULT_BIN_FACT
    --WHERE DW_SYS_UPDT_TMSTP > (SELECT coalesce(max(cast(DW_SYS_UPDT_TMSTP AS DATE)) - 7, cast('2024-02-20' AS DATE)) FROM PREPROD_NAP_BASE_VWS.PAYMENT_RESULT_BIN_FACT)
) WITH DATA PRIMARY INDEX (ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- inner join temp table and temp bin table, and update only those records
UPDATE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG
FROM (
    SELECT DISTINCT A.SETTLEMENT_RESULT_RECEIVED_ID
    FROM TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG AS A
    INNER JOIN PAYMENT_RESULT_BIN_LDG_TEMP AS B
        ON A.SETTLEMENT_AMOUNT = B.AMOUNT
        AND A.AUTHORIZATION_CODE = B.AUTHORIZATION_CODE
        AND A.STORE_NUMBER = B.STORE_NUMBER
        AND A.TENDER_TYPE = B.TENDER_TYPE
        AND A.CARD_TYPE = B.CARD_TYPE
        AND cast((A.TRANSACTION_TIMESTAMP AT 'America Pacific') AS DATE) = B.TRANSACTION_DATE --noqa
    WHERE B.BIN = '427140'
) AS C
SET ISAFTERPAY = 'Y', BIN_TYPE = 'In store'
WHERE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG.SETTLEMENT_RESULT_RECEIVED_ID = C.SETTLEMENT_RESULT_RECEIVED_ID;

UPDATE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG
FROM (
    SELECT DISTINCT A.SETTLEMENT_RESULT_RECEIVED_ID
    FROM TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG AS A
    INNER JOIN PAYMENT_RESULT_BIN_LDG_TEMP AS B
        ON A.SETTLEMENT_AMOUNT = B.AMOUNT
        AND A.AUTHORIZATION_CODE = B.AUTHORIZATION_CODE
        AND A.STORE_NUMBER = B.STORE_NUMBER
        AND A.TENDER_TYPE = B.TENDER_TYPE
        AND A.CARD_TYPE = B.CARD_TYPE
        AND cast((A.TRANSACTION_TIMESTAMP AT 'America Pacific') AS DATE) = B.TRANSACTION_DATE --noqa
    WHERE B.BIN = '411361'
) AS C
SET ISAFTERPAY = 'Y', BIN_TYPE = 'Online virtual card'
WHERE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG.SETTLEMENT_RESULT_RECEIVED_ID = C.SETTLEMENT_RESULT_RECEIVED_ID;

UPDATE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG
FROM (
    SELECT DISTINCT A.SETTLEMENT_RESULT_RECEIVED_ID
    FROM TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG AS A
    INNER JOIN PAYMENT_RESULT_BIN_LDG_TEMP AS B
        ON A.SETTLEMENT_AMOUNT = B.AMOUNT
        AND A.AUTHORIZATION_CODE = B.AUTHORIZATION_CODE
        AND A.STORE_NUMBER = B.STORE_NUMBER
        AND A.TENDER_TYPE = B.TENDER_TYPE
        AND A.CARD_TYPE = B.CARD_TYPE
        AND cast((A.TRANSACTION_TIMESTAMP AT 'America Pacific') AS DATE) = B.TRANSACTION_DATE --noqa
    WHERE B.BIN = '486696'
) AS C
SET ISAFTERPAY = 'Y', BIN_TYPE = 'Long term installments'
WHERE TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG.SETTLEMENT_RESULT_RECEIVED_ID = C.SETTLEMENT_RESULT_RECEIVED_ID;

--Delete if exist
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_RESULT_DETAILS_FACT
WHERE
    SETTLEMENT_RESULT_RECEIVED_ID IN (SELECT SETTLEMENT_RESULT_RECEIVED_ID FROM TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG);

-- Insert into FACT table
INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_RESULT_DETAILS_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    SETTLEMENT_RESULT_RECEIVED_ID,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    ACQUIRER,
    SETTLEMENT_AMOUNT_CURRENCY_CODE,
    SETTLEMENT_AMOUNT,
    STORE_NUMBER,
    PROCESSING_DATE,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_TIME_ZONE_OFFSET_MINUTES,
    TRANSACTION_TYPE,
    TENDER_TYPE,
    ACQUIRER_MERCHANT_IDENTIFIER,
    BANK_CARD_AUTHORIZATION_SOURCE,
    AUTHORIZATION_CODE,
    VENDOR_SETTLEMENT_CODE,
    EXPIRATION_DATE_MONTH,
    EXPIRATION_DATE_YEAR,
    INTERCHANGE_CODE,
    INTERCHANGE_AMOUNT_CURRENCY_CODE,
    INTERCHANGE_AMOUNT,
    MERCHANT_CATEGORY_CODE,
    ENTRY_MODE,
    TOKEN_VALUE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    TRANSACTION_MATCH_IDENTIFIER,
    CARD_TYPE,
    CARD_SUBTYPE,
    TOKEN_REQUESTOR_ID,
    CARD_PRODUCT_TYPE,
    INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE,
    INTERCHANGE_ADJUSTMENT_AMOUNT,
    INTERCHANGE_ADJUSTMENT_REASON,
    EMV_TRANSACTION_INDICATOR,
    NETWORK_REFERENCE_NUMBER,
    VISA_TRANSACTION_ID,
    MASTERCARD_BANK_NET_REFERENCE_NUMBER,
    TERMINAL_ID,
    ISAFTERPAY,
    BIN_TYPE
)
SELECT
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    SETTLEMENT_RESULT_RECEIVED_ID,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    ACQUIRER,
    SETTLEMENT_AMOUNT_CURRENCY_CODE,
    SETTLEMENT_AMOUNT,
    STORE_NUMBER,
    PROCESSING_DATE,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_TIME_ZONE_OFFSET_MINUTES,
    TRANSACTION_TYPE,
    TENDER_TYPE,
    ACQUIRER_MERCHANT_IDENTIFIER,
    BANK_CARD_AUTHORIZATION_SOURCE,
    AUTHORIZATION_CODE,
    VENDOR_SETTLEMENT_CODE,
    EXPIRATION_DATE_MONTH,
    EXPIRATION_DATE_YEAR,
    INTERCHANGE_CODE,
    INTERCHANGE_AMOUNT_CURRENCY_CODE,
    INTERCHANGE_AMOUNT,
    MERCHANT_CATEGORY_CODE,
    ENTRY_MODE,
    TOKEN_VALUE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    TRANSACTION_MATCH_IDENTIFIER,
    CARD_TYPE,
    CARD_SUBTYPE,
    TOKEN_REQUESTOR_ID,
    CARD_PRODUCT_TYPE,
    INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE,
    INTERCHANGE_ADJUSTMENT_AMOUNT,
    INTERCHANGE_ADJUSTMENT_REASON,
    EMV_TRANSACTION_INDICATOR,
    NETWORK_REFERENCE_NUMBER,
    VISA_TRANSACTION_ID,
    MASTERCARD_BANK_NET_REFERENCE_NUMBER,
    TERMINAL_ID,
    ISAFTERPAY,
    BIN_TYPE
FROM TEMP_PAYMENT_SETTLEMENT_RESULT_DETAILS_STG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
