-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=authorization_hashkey_backfill_teradata;Task_Name=job_insert_update;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

UPDATE PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT
FROM (
SELECT
    A.EVENT_ID,
    B.AUTHORIZATION_CODE,
    A.ACTIVITY_DATE,
    B.TENDER_ITEM_ACCOUNT_NO,
    A.TOTAL_AMT
FROM PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT A
INNER JOIN PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_TENDER_V2_FACT B
ON A.EVENT_ID = B.EVENT_ID
WHERE B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_AUTHORIZATION_RESULT = HASH_SHA256(CONCAT(
                COALESCE(TRIM(C.AUTHORIZATION_CODE), ''),
                COALESCE(TRIM(C.TENDER_ITEM_ACCOUNT_NO), ''),
                COALESCE(TRIM(CAST(CAST(C.TOTAL_AMT AS DECIMAL(12, 2)) AS VARCHAR(50))), '')
                ))
WHERE PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT.EVENT_ID = C.EVENT_ID;

UPDATE PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT
FROM (
SELECT A.EVENT_ID
FROM PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT A
INNER JOIN PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_TENDER_V2_FACT B
ON A.EVENT_ID = B.EVENT_ID
WHERE B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_SETTLEMENT_INTENT = PURCHASE_IDENTIFIER_ID
WHERE PRD_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT.EVENT_ID = C.EVENT_ID;


SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
