SET QUERY_BAND = '
App_ID=app07420;
DAG_ID=migration_charge_info_preprd_prd_tpt_teradata;
Task_Name=insert_from_stg_to_fct_teradata_stage_job;'
-- noqa: disable=all
FOR SESSION VOLATILE;
-- noqa: enable=all

END TRANSACTION;

INSERT INTO PRD_NAP_PYMNT_FRAUD_BASE_VWS.PAYMENT_CHARGEBACK_INFORMATION_FACT
(
    DW_BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    DISPUTE_AMOUNT_CURRENCY_CODE,
    DISPUTE_AMOUNT,
    CHARGEBACK_ID,
    VENDOR_CHARGEBACK_ID,
    ACQUIRER_STORE_NUMBER,
    TRANSACTION_TIMESTAMP,
    TRANSACTION_TIME_TIMEZONE_OFFSET_MINUTES,
    CHARGEBACK_CATEGORY,
    PROCESS_STAGE,
    REASON_CODE,
    CHARGEBACK_VENDOR,
    CHARGEBACK_STATE,
    VENDOR_SETTLEMENT_CODE,
    DUE_DATE,
    VENDOR_ACTIVITY_TIMESTAMP,
    VENDOR_ACTIVITY_DATE,
    VENDOR_ACTIVITY_TIMEZONE_OFFSET_MINUTES,
    VENDOR_EXPORT_DATE,
    PAYMENT_ID,
    TOKEN_VALUE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    CARD_TYPE,
    CARD_SUBTYPE,
    SETTLEMENT_AMOUNT_CURRENCY_CODE,
    SETTLEMENT_AMOUNT,
    FINANCIAL_IMPACT,
    CHARGEBACK_ACTION_CODE,
    WORLDPAY_CUSTOMER_DISCRETIONARY_FIELD_2,
    WORLDPAY_FEE_AMOUNT,
    WORLDPAY_REGISTER_NUMBER,
    WORLDPAY_NETWORK_REFERENCE_NUMBER,
    WORLDPAY_ENTRY_MODE,
    WORLDPAY_BANK_CARD_AUTHORIZATION_SOURCE
)
SELECT DISTINCT
    current_date AS DW_BATCH_DATE,
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    DISPUTE_AMOUNT_CURRENCY_CODE,
    DISPUTE_AMOUNT,
    CHARGEBACK_ID,
    VENDOR_CHARGEBACK_ID,
    ACQUIRER_STORE_NUMBER,
    cast(concat(TRANSACTION_TIMESTAMP, '+00:00') AS TIMESTAMP(6) WITH TIME ZONE) AS TRANSACTION_TIMESTAMP,
    TRANSACTION_TIME_TIMEZONE_OFFSET_MINUTES,
    CHARGEBACK_CATEGORY,
    PROCESS_STAGE,
    REASON_CODE,
    CHARGEBACK_VENDOR,
    CHARGEBACK_STATE,
    VENDOR_SETTLEMENT_CODE,
    DUE_DATE,
    cast(concat(VENDOR_ACTIVITY_TIMESTAMP, '+00:00') AS TIMESTAMP(6) WITH TIME ZONE) AS VENDOR_ACTIVITY_TIMESTAMP,
    VENDOR_ACTIVITY_DATE,
    VENDOR_ACTIVITY_TIMEZONE_OFFSET_MINUTES,
    VENDOR_EXPORT_DATE,
    PAYMENT_ID,
    TOKEN_VALUE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    CARD_TYPE,
    CARD_SUBTYPE,
    SETTLEMENT_AMOUNT_CURRENCY_CODE,
    SETTLEMENT_AMOUNT,
    FINANCIAL_IMPACT,
    CHARGEBACK_ACTION_CODE,
    WORLDPAY_CUSTOMER_DISCRETIONARY_FIELD_2,
    WORLDPAY_FEE_AMOUNT,
    WORLDPAY_REGISTER_NUMBER,
    WORLDPAY_NETWORK_REFERENCE_NUMBER,
    WORLDPAY_ENTRY_MODE,
    WORLDPAY_BANK_CARD_AUTHORIZATION_SOURCE
FROM PRD_NAP_PYMNT_FRAUD_STG.PAYMENT_CHARGEBACK_INFORMATION_LDG
WHERE CHARGEBACK_ID NOT IN (SELECT DISTINCT CHARGEBACK_ID FROM PRD_NAP_PYMNT_FRAUD_BASE_VWS.PAYMENT_CHARGEBACK_INFORMATION_FACT);

DELETE FROM PRD_NAP_PYMNT_FRAUD_STG.PAYMENT_CHARGEBACK_INFORMATION_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
