-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_bin_v2_redemption_service_tpt_load; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'source_id'.
CREATE MULTISET VOLATILE TABLE PAYMENT_RESULT_BIN_V2_LDG_TEMP AS (
    SELECT DISTINCT *
    FROM PREPROD_NAP_PYMNT_FRAUD_STG.PAYMENT_RESULT_BIN_V2_LDG
    QUALIFY
        ROW_NUMBER() OVER (
            PARTITION BY SOURCE_ID ORDER BY CREATED_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (SOURCE_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.PAYMENT_RESULT_BIN_V2_FACT
WHERE SOURCE_ID IN (SELECT DISTINCT SOURCE_ID FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.PAYMENT_RESULT_BIN_V2_LDG);

INSERT INTO PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.PAYMENT_RESULT_BIN_V2_FACT
(
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    SOURCE_ID,
    BIN,
    EVENT_SOURCE,
    CREATED_TIME,
    CREATED_DATE
)
SELECT DISTINCT
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP,
    SOURCE_ID,
    BIN,
    EVENT_SOURCE,
    CAST(CREATED_TIME AS TIMESTAMP) AS CREATED_TIME,
    CAST(CAST(CREATED_TIME AS TIMESTAMP) AS DATE) AS CREATED_DATE
FROM PAYMENT_RESULT_BIN_V2_LDG_TEMP;

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.PAYMENT_RESULT_BIN_V2_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
