-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_settlement_intent_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary tables for selecting distinct records by 'transaction_identifier_id'
CREATE MULTISET VOLATILE TABLE SETTLEMENT_INTENT_STG_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_STG.PAYMENT_SETTLEMENT_INTENT_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY TRANSACTION_IDENTIFIER_ID ORDER BY EVENT_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_IDENTIFIER_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE BANK_CARD_SETTLEMENT_RESULTS_STG_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_STG.BANKCARD_SETTLEMENT_RESULTS_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY
                TRANSACTION_IDENTIFIER_ID
            ORDER BY TRANSACTION_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_IDENTIFIER_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE GIFTCARD_NOTE_TENDER_RESULTS_STG_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_STG.GIFTCARD_NOTE_TENDER_RESULTS_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY
                TRANSACTION_IDENTIFIER_ID
            ORDER BY TRANSACTION_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_IDENTIFIER_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE
PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_STG_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_STG.PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY
                TRANSACTION_IDENTIFIER_ID
            ORDER BY TRANSACTION_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_IDENTIFIER_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE PAYPAL_SETTLEMENT_RESULT_STG_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_STG.PAYPAL_SETTLEMENT_RESULT_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY
                TRANSACTION_IDENTIFIER_ID
            ORDER BY TRANSACTION_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_IDENTIFIER_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- PAYMENT_SETTLEMENT_INTENT_FACT
-- Purge and reprocess data to account for updates
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_FACT
WHERE
    TRANSACTION_IDENTIFIER_ID IN (SELECT TRANSACTION_IDENTIFIER_ID FROM SETTLEMENT_INTENT_STG_TEMP);

-- Insert new event data
INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    DW_BATCH_DATE,
    EVENT_TIME,
    EVENT_DATE,
    SOURCE_CHANNEL_COUNTRY,
    SOURCE_CHANNEL,
    SOURCE_PLATFORM,
    SOURCE_FEATURE,
    SOURCE_SERVICE_NAME,
    SOURCE_STORE,
    SOURCE_REGISTER,
    PURCHASE_IDENTIFIER_TYPE,
    PURCHASE_IDENTIFIER_ID,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    TOTAL_REQUESTED_AMOUNT_CURRENCY_CODE,
    TOTAL_REQUESTED_AMOUNT_AMOUNT,
    MERCHANT_IDENTIFIER,
    FAILURE_REASON,
    SERVICE_TICKET_ID
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    current_date AS DW_BATCH_DATE,
    cast(cast(EVENT_TIME AS VARCHAR(19)) AS TIMESTAMP(0)) AS EVENT_TIME,
    cast(cast(EVENT_TIME AS TIMESTAMP) AS DATE) AS EVENT_DATE,
    SOURCE_CHANNEL_COUNTRY,
    SOURCE_CHANNEL,
    SOURCE_PLATFORM,
    SOURCE_FEATURE,
    SOURCE_SERVICE_NAME,
    SOURCE_STORE,
    SOURCE_REGISTER,
    PURCHASE_IDENTIFIER_TYPE,
    PURCHASE_IDENTIFIER_ID,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    TOTAL_REQUESTED_AMOUNT_CURRENCY_CODE,
    TOTAL_REQUESTED_AMOUNT_AMOUNT,
    MERCHANT_IDENTIFIER,
    FAILURE_REASON,
    SERVICE_TICKET_ID
FROM SETTLEMENT_INTENT_STG_TEMP;

-- BANKCARD_SETTLEMENT_RESULTS_FACT
-- Purge and reprocess data to account for updates
DELETE FROM PREPROD_NAP_BASE_VWS.BANKCARD_SETTLEMENT_RESULTS_FACT
WHERE
    TRANSACTION_IDENTIFIER_ID IN (SELECT TRANSACTION_IDENTIFIER_ID FROM BANK_CARD_SETTLEMENT_RESULTS_STG_TEMP);

-- Insert new event data
INSERT INTO PREPROD_NAP_BASE_VWS.BANKCARD_SETTLEMENT_RESULTS_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    DW_BATCH_DATE,
    TRANSACTION_TIME,
    TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    TOKEN_VALUE,
    TOKEN_TYPE,
    CARD_TYPE,
    CARD_SUBTYPE,
    TOTAL_AMOUNT,
    TRANSACTION_RESULT_TYPE,
    TRANSACTION_RESULT_STATUS,
    TRANSACTION_RESULT_FAILURE_REASON,
    TOKEN_REQUESTOR_ID,
    VENDOR_SETTLEMENT_CODE
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    current_date AS DW_BATCH_DATE,
    cast(
        cast(TRANSACTION_TIME AS VARCHAR(19)) AS TIMESTAMP(0)
    ) AS TRANSACTION_TIME,
    cast(cast(TRANSACTION_TIME AS TIMESTAMP) AS DATE) AS TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    TOKEN_VALUE,
    TOKEN_TYPE,
    CARD_TYPE,
    CARD_SUBTYPE,
    TOTAL_AMOUNT,
    TRANSACTION_RESULT_TYPE,
    TRANSACTION_RESULT_STATUS,
    TRANSACTION_RESULT_FAILURE_REASON,
    TOKEN_REQUESTOR_ID,
    VENDOR_SETTLEMENT_CODE
FROM BANK_CARD_SETTLEMENT_RESULTS_STG_TEMP;

-- GIFTCARD_NOTE_TENDER_RESULTS_FACT
-- Purge and reprocess data to account for updates
DELETE FROM PREPROD_NAP_BASE_VWS.GIFTCARD_NOTE_TENDER_RESULTS_FACT
WHERE
    TRANSACTION_IDENTIFIER_ID IN (SELECT TRANSACTION_IDENTIFIER_ID FROM GIFTCARD_NOTE_TENDER_RESULTS_STG_TEMP);

-- Insert new event data
INSERT INTO PREPROD_NAP_BASE_VWS.GIFTCARD_NOTE_TENDER_RESULTS_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    DW_BATCH_DATE,
    TRANSACTION_TIME,
    TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    GIFT_CARD_NOTE_TYPE,
    ACCOUNT_NUMBER,
    REQUESTED_AMOUNT,
    APPLIED_AMOUNT,
    TENDER_TRANSACTION_RESULT_TYPE,
    TRANSACTION_STATUS
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    current_date AS DW_BATCH_DATE,
    cast(cast(TRANSACTION_TIME AS VARCHAR(19)) AS TIMESTAMP(0)) AS TRANSACTION_TIME,
    cast(cast(TRANSACTION_TIME AS TIMESTAMP) AS DATE) AS TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    GIFT_CARD_NOTE_TYPE,
    ACCOUNT_NUMBER,
    REQUESTED_AMOUNT,
    APPLIED_AMOUNT,
    TENDER_TRANSACTION_RESULT_TYPE,
    TRANSACTION_STATUS
FROM GIFTCARD_NOTE_TENDER_RESULTS_STG_TEMP;

-- PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_FACT
-- Purge and reprocess data to account for updates
DELETE FROM PREPROD_NAP_BASE_VWS.PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_FACT
WHERE
    TRANSACTION_IDENTIFIER_ID IN (
        SELECT TRANSACTION_IDENTIFIER_ID FROM PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_STG_TEMP
    );

-- Insert new event data
INSERT INTO PREPROD_NAP_BASE_VWS.PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    DW_BATCH_DATE,
    TRANSACTION_TIME,
    TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    PAYER_ID,
    TOTAL,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    ID,
    PARENT_REFERENCE_ID,
    FEE,
    NET_AMOUNT
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    current_date AS DW_BATCH_DATE,
    cast(cast(TRANSACTION_TIME AS VARCHAR(19)) AS TIMESTAMP(0)) AS TRANSACTION_TIME,
    cast(cast(TRANSACTION_TIME AS TIMESTAMP) AS DATE) AS TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    PAYER_ID,
    TOTAL,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    ID,
    PARENT_REFERENCE_ID,
    FEE,
    NET_AMOUNT
FROM PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_STG_TEMP;

-- PAYPAL_SETTLEMENT_RESULT_FACT
-- Purge and reprocess data to account for updates
DELETE FROM PREPROD_NAP_BASE_VWS.PAYPAL_SETTLEMENT_RESULT_FACT
WHERE
    TRANSACTION_IDENTIFIER_ID IN (SELECT TRANSACTION_IDENTIFIER_ID FROM PAYPAL_SETTLEMENT_RESULT_STG_TEMP);

-- Insert new event data
INSERT INTO PREPROD_NAP_BASE_VWS.PAYPAL_SETTLEMENT_RESULT_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    DW_BATCH_DATE,
    TRANSACTION_TIME,
    TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    PAYPAL_ORDER_ID,
    PAYER_ID,
    TOTAL,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    TRANSACTION_FAILURE_DESCRIPTION,
    ID,
    PARENT_REFERENCE_ID,
    FEE,
    NET_AMOUNT
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    current_date AS DW_BATCH_DATE,
    cast(cast(TRANSACTION_TIME AS VARCHAR(19)) AS TIMESTAMP(0)) AS TRANSACTION_TIME,
    cast(cast(TRANSACTION_TIME AS TIMESTAMP) AS DATE) AS TRANSACTION_DATE,
    TRANSACTION_IDENTIFIER_TYPE,
    TRANSACTION_IDENTIFIER_ID,
    PAYPAL_ORDER_ID,
    PAYER_ID,
    TOTAL,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    TRANSACTION_FAILURE_DESCRIPTION,
    ID,
    PARENT_REFERENCE_ID,
    FEE,
    NET_AMOUNT
FROM PAYPAL_SETTLEMENT_RESULT_STG_TEMP;

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_STG.BANKCARD_SETTLEMENT_RESULTS_LDG;
DELETE FROM PREPROD_NAP_STG.GIFTCARD_NOTE_TENDER_RESULTS_LDG;
DELETE FROM PREPROD_NAP_STG.PAYMENT_SETTLEMENT_INTENT_LDG;
DELETE FROM PREPROD_NAP_STG.PAYPAL_BILLING_AGREEMENT_SETTLEMENT_RESULTS_LDG;
DELETE FROM PREPROD_NAP_STG.PAYPAL_SETTLEMENT_RESULT_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
