-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_auth_teradata_v2;Task_Name=teradata_hdr_fct_update_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

UPDATE {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT
FROM (
SELECT
    A.EVENT_ID,
    B.AUTHORIZATION_CODE,
    B.TENDER_ITEM_ACCOUNT_NO,
    A.TOTAL_AMT
FROM {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT A
INNER JOIN {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_TENDER_V2_FACT B
ON A.EVENT_ID = B.EVENT_ID
WHERE A.EVENT_ID IN
(SELECT DISTINCT EVENT_ID
    FROM {db_env}_NAP_STG.PAYMENT_AUTHORIZATION_HDR_V2_LDG)
AND B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_AUTHORIZATION_RESULT = HASH_SHA256(CONCAT(
                COALESCE(TRIM(C.AUTHORIZATION_CODE), ''),
                COALESCE(TRIM(C.TENDER_ITEM_ACCOUNT_NO), ''),
                COALESCE(TRIM(CAST(CAST(C.TOTAL_AMT AS DECIMAL(12, 2)) AS VARCHAR(50))), '')
                ))
WHERE {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT.EVENT_ID = C.EVENT_ID;

UPDATE {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT
FROM (
SELECT A.EVENT_ID
FROM {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT A
INNER JOIN {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_TENDER_V2_FACT B
ON A.EVENT_ID = B.EVENT_ID
WHERE A.EVENT_ID IN
(SELECT DISTINCT EVENT_ID
    FROM {db_env}_NAP_STG.PAYMENT_AUTHORIZATION_HDR_V2_LDG)
AND B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_SETTLEMENT_INTENT = PURCHASE_IDENTIFIER_ID
WHERE {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_HDR_V2_FACT.EVENT_ID = C.EVENT_ID;

DELETE FROM {db_env}_NAP_STG.PAYMENT_AUTHORIZATION_HDR_V2_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
