-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_refund_teradata; Task_Name=teradata_tender_stg_to_teradata_tender_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE PAYMENT_REFUND_TENDER_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_REFUND_TENDER_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY EVENT_ID ORDER BY CAST(EVENT_TIME AS TIMESTAMP) DESC
        ) = 1
) WITH DATA PRIMARY INDEX (EVENT_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_REFUND_TENDER_FACT
WHERE EVENT_ID IN (SELECT DISTINCT EVENT_ID FROM {db_env}_NAP_BASE_VWS.PAYMENT_REFUND_TENDER_LDG);

INSERT INTO {db_env}_NAP_BASE_VWS.PAYMENT_REFUND_TENDER_FACT
(
  EVENT_ID,
  EVENT_TYPE,
  EVENT_TIME,
  ACTIVITY_DATE,
  TRANSACTION_TYPE,
  TRANSACTION_ID,
  PURCHASE_IDENTIFIER_ID,
  CARD_TYPE,
  CARD_SUB_TYPE,
  TENDER_ITEM_ACCOUNT_NO,
  TENDER_ITEM_ACCOUNT_VALUE_TYPE,
  TOKEN_AUTHORITY,
  TOKEN_DATA_CLASSIFICATION,
  TOKEN_TYPE,
  CURRENCY_CODE,
  TOTAL_AMT,
  TRANSACTION_TIME,
  TENDER_RECORD_NAME,
  TRANSACTION_STATUS,
  TRANSACTION_FAILURE_DESC,
  TOKEN_REQUESTOR_ID,
  VENDOR_SETTLEMENT_CODE,
  TENDER_TYPE,
  GIFT_CARD_NOTE_TYPE,
  PAYPAL_TNDR_RSLT_ORDER_ID,
  PAYPAL_TNDR_RSLT_PAYER_ID,
  PAYPAL_STLMNT_RSLT_ID,
  PAYPAL_STLMNT_RSLT_PARENT_REF_ID,
  PAYPAL_STLMNT_RSLT_FEE_CURRENCY_CODE,
  PAYPAL_STLMNT_RSLT_FEE_AMOUNT,
  PAYPAL_STLMNT_RSLT_NET_AMT_CURRENCY_CODE,
  PAYPAL_STLMNT_RSLT_NET_AMT_AMT,
  PAYPAL_BILLING_AGREEMENT_TNDR_RSLT_ID_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_EMAIL_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_ACCOUNT_COUNTRY,
  NOTE_REFUND_REASON,
  BATCH_DATE,
  DW_SYS_LOAD_TMSTP,
  DW_SYS_UPDT_TMSTP
)
SELECT DISTINCT
  EVENT_ID,
  EVENT_TYPE,
  CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
  CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS ACTIVITY_DATE,
  TRANSACTION_TYPE,
  TRANSACTION_ID,
  PURCHASE_IDENTIFIER_ID,
  CARD_TYPE,
  CARD_SUB_TYPE,
  TENDER_ITEM_ACCOUNT_NO,
  TENDER_ITEM_ACCOUNT_VALUE_TYPE,
  TOKEN_AUTHORITY,
  TOKEN_DATA_CLASSIFICATION,
  TOKEN_TYPE,
  CURRENCY_CODE,
  CAST(TOTAL_AMT AS DECIMAL(14, 4)) AS TOTAL_AMT,
  CAST(TRANSACTION_TIME AS TIMESTAMP) AS TRANSACTION_TIME,
  TENDER_RECORD_NAME,
  TRANSACTION_STATUS,
  TRANSACTION_FAILURE_DESC,
  TOKEN_REQUESTOR_ID,
  VENDOR_SETTLEMENT_CODE,
  TENDER_TYPE,
  GIFT_CARD_NOTE_TYPE,
  PAYPAL_TNDR_RSLT_ORDER_ID,
  PAYPAL_TNDR_RSLT_PAYER_ID,
  PAYPAL_STLMNT_RSLT_ID,
  PAYPAL_STLMNT_RSLT_PARENT_REF_ID,
  PAYPAL_STLMNT_RSLT_FEE_CURRENCY_CODE,
  CAST(PAYPAL_STLMNT_RSLT_FEE_AMOUNT AS DECIMAL(14, 4)) AS PAYPAL_STLMNT_RSLT_FEE_AMOUNT,
  PAYPAL_STLMNT_RSLT_NET_AMT_CURRENCY_CODE,
  CAST(PAYPAL_STLMNT_RSLT_NET_AMT_AMT AS DECIMAL(14, 4)) AS PAYPAL_STLMNT_RSLT_NET_AMT_AMT,
  PAYPAL_BILLING_AGREEMENT_TNDR_RSLT_ID_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_EMAIL_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_ACCOUNT_COUNTRY,
  NOTE_REFUND_REASON,
  CURRENT_DATE AS BATCH_DATE,
  CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
  CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM PAYMENT_REFUND_TENDER_TEMP;

-- Remove records from temporary tables
DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_REFUND_TENDER_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
