-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_reset_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_TRANSACTION_MATCH_FACT
WHERE EVENT_ID IN (SELECT DISTINCT EVENT_ID FROM PREPROD_NAP_STG.PAYMENT_SETTLEMENT_TRANSACTION_MATCH_LDG);

INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_TRANSACTION_MATCH_FACT
(
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    PROCESSED_TIMESTAMP,
    EVENT_ID,
    SETTLEMENT_RESULT_RECEIVED_ID,
    ORIGINAL_GLOBAL_TRANSACTION_ID,
    GLOBAL_TRANSACTION_ID,
    ERTM_TENDER_ITEM_SEQUENCE,
    SETTLEMENT_TRANSACTION_MATCH_CRITERIA,
    TENDER_REF_ID
)
SELECT DISTINCT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    cast(concat(PROCESSED_TIMESTAMP, '+00:00') AS TIMESTAMP(6) WITH TIME ZONE
    ) AS PROCESSED_TIMESTAMP,
    EVENT_ID,
    SETTLEMENT_RESULT_RECEIVED_ID,
    ORIGINAL_GLOBAL_TRANSACTION_ID,
    GLOBAL_TRANSACTION_ID,
    ERTM_TENDER_ITEM_SEQUENCE,
    SETTLEMENT_TRANSACTION_MATCH_CRITERIA,
    TENDER_REF_ID
FROM PREPROD_NAP_STG.PAYMENT_SETTLEMENT_TRANSACTION_MATCH_LDG;

COLLECT STATISTICS COLUMN (EVENT_ID) ON PREPROD_NAP_FCT.PAYMENT_SETTLEMENT_TRANSACTION_MATCH_FACT; -- noqa
END TRANSACTION;

-- delete stg table
DELETE FROM PREPROD_NAP_STG.PAYMENT_SETTLEMENT_TRANSACTION_MATCH_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
