-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_settlement_intent_teradata_v2; Task_Name=teradata_hdr_stg_to_teradata_hdr_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE PAYMENT_SETTLEMENT_HDR_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_LDG
    QUALIFY
        ROW_NUMBER() OVER (
            PARTITION BY TRANSACTION_ID ORDER BY CAST(EVENT_TIME AS TIMESTAMP) DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT
WHERE TRANSACTION_ID IN (SELECT DISTINCT TRANSACTION_ID FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_LDG);

INSERT INTO {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT
(
  EVENT_ID,
  EVENT_TIME,
  ACTIVITY_DATE,
  SOURCE_CHANNEL_COUNTRY,
  SOURCE_CHANNEL,
  SOURCE_PLATFORM,
  SOURCE_FEATURE,
  SOURCE_SERVICE_NAME,
  SOURCE_STORE,
  SOURCE_REGISTER,
  PURCHASE_IDENTIFIER_TYPE,
  PURCHASE_IDENTIFIER_ID,
  POS_STORE,
  POS_REGISTER,
  POS_TRANSACTION,
  POS_BUSINESS_DATE,
  STORE_TRANSACTION_TRANSACTION_ID,
  STORE_TRANSACTION_SESSION_ID,
  TRANSACTION_ID,
  TRANSACTION_ID_TYPE,
  SERVICE_TICKET_ID,
  CURRENCY_CODE,
  TOTAL_AMT,
  MERCHANT_IDENTIFIER,
  FAILURE_REASON,
  DW_BATCH_DATE,
  DW_SYS_LOAD_TMSTP,
  DW_SYS_UPDT_TMSTP
)
SELECT
  EVENT_ID,
  CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
  CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS ACTIVITY_DATE,
  SOURCE_CHANNEL_COUNTRY,
  SOURCE_CHANNEL,
  SOURCE_PLATFORM,
  SOURCE_FEATURE,
  SOURCE_SERVICE_NAME,
  SOURCE_STORE,
  SOURCE_REGISTER,
  PURCHASE_IDENTIFIER_TYPE,
  PURCHASE_IDENTIFIER_ID,
  POS_STORE,
  POS_REGISTER,
  POS_TRANSACTION,
  CAST(POS_BUSINESS_DATE AS DATE) AS POS_BUSINESS_DATE,
  STORE_TRANSACTION_TRANSACTION_ID,
  STORE_TRANSACTION_SESSION_ID,
  TRANSACTION_ID,
  TRANSACTION_ID_TYPE,
  SERVICE_TICKET_ID,
  CURRENCY_CODE,
  CAST(TOTAL_AMT AS DECIMAL(14, 4)) AS TOTAL_AMT,
  MERCHANT_IDENTIFIER,
  FAILURE_REASON,
  CURRENT_DATE AS DW_BATCH_DATE,
  CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
  CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM PAYMENT_SETTLEMENT_HDR_TEMP;


SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
