-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_auth_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary tables for selecting distinct records by 'settlementID'.
CREATE MULTISET VOLATILE TABLE TEMP_PAYMENT_AUTHORIZATION_STG AS (
    SELECT DISTINCT *
    FROM {db_env}_NAP_STG.PAYMENT_AUTHORIZATION_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY
                ID
            ORDER BY EVENT_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

--Delete if exist
DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_FACT
WHERE
    ID IN (SELECT ID FROM TEMP_PAYMENT_AUTHORIZATION_STG);

-- Insert into FACT table
INSERT INTO {db_env}_NAP_BASE_VWS.PAYMENT_AUTHORIZATION_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    ID,
    LAST_UPDATED_TIME,
    CREATED_TIMESTAMP,
    EVENT_TIME,
    EVENT_DATE,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    PURCHASE_IDENTIFIER_TYPE,
    PURCHASE_IDENTIFIER_ID,
    AMOUNT_CURRENCY_CODE,
    TOTAL_AMOUNT,
    MERCHANT_IDENTIFIER,
    AUTHORIZATION_TYPE,
    TENDER_TYPE,
    FAILURE_REASON,
    PAYER_ACCOUNT_COUNTRY,
    TENDER_ITEM_ACCOUNT_NO,
    TENDER_ITEM_ACCOUNT_VALUE_TYPE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    TOKEN_REQUESTOR_ID,
    CARD_TYPE,
    CARD_SUBTYPE,
    LAST_FOUR,
    EXPIRATION_DATE_MONTH,
    EXPIRATION_DATE_YEAR,
    APPROVAL_STATUS,
    AUTHORIZATION_CODE,
    EMV_AUTHORIZATION_INFO,
    PAYMENT_KEY,
    EMV_TAGS_INFO,
    CVV_RESULT_CODE,
    AVS_RESULT_CODE,
    GIFT_CARD_BALANCE_LOCK_ID,
    GIFT_CARD_ACCESS_CODE_VALUE,
    GIFT_CARD_NOTE_TYPE,
    GIFT_CARD_TENDER_CAPTURE_METHOD
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    ID,
    cast(cast(LAST_UPDATED_TIME AS VARCHAR(19)) AS TIMESTAMP(0)) AS LAST_UPDATED_TIME,
    cast(cast(CREATED_TIMESTAMP AS VARCHAR(19)) AS TIMESTAMP(0)) AS CREATED_TIMESTAMP,
    cast(cast(EVENT_TIME AS VARCHAR(19)) AS TIMESTAMP(0)) AS EVENT_TIME,
    cast(cast(CREATED_TIMESTAMP AS TIMESTAMP) AS DATE) AS EVENT_DATE,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    PURCHASE_IDENTIFIER_TYPE,
    PURCHASE_IDENTIFIER_ID,
    AMOUNT_CURRENCY_CODE,
    TOTAL_AMOUNT,
    MERCHANT_IDENTIFIER,
    AUTHORIZATION_TYPE,
    TENDER_TYPE,
    FAILURE_REASON,
    PAYER_ACCOUNT_COUNTRY,
    TENDER_ITEM_ACCOUNT_NO,
    TENDER_ITEM_ACCOUNT_VALUE_TYPE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    TOKEN_REQUESTOR_ID,
    CARD_TYPE,
    CARD_SUBTYPE,
    LAST_FOUR,
    EXPIRATION_DATE_MONTH,
    EXPIRATION_DATE_YEAR,
    APPROVAL_STATUS,
    AUTHORIZATION_CODE,
    EMV_AUTHORIZATION_INFO,
    PAYMENT_KEY,
    EMV_TAGS_INFO,
    CVV_RESULT_CODE,
    AVS_RESULT_CODE,
    GIFT_CARD_BALANCE_LOCK_ID,
    GIFT_CARD_ACCESS_CODE_VALUE,
    GIFT_CARD_NOTE_TYPE,
    GIFT_CARD_TENDER_CAPTURE_METHOD
FROM TEMP_PAYMENT_AUTHORIZATION_STG;

-- Remove records from temporary tables
DELETE FROM {db_env}_NAP_STG.PAYMENT_AUTHORIZATION_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
