-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_bin_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary tables for selecting distinct records by 'id'.
CREATE MULTISET VOLATILE TABLE PAYMENT_RESULT_BIN_LDG_TEMP AS (
    SELECT DISTINCT *
    FROM PREPROD_NAP_STG.PAYMENT_RESULT_BIN_LDG
    QUALIFY row_number() OVER (PARTITION BY ID ORDER BY TRANSACTION_DATE DESC) = 1
) WITH DATA PRIMARY INDEX (ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;
-- Insert or update if exist

MERGE INTO PREPROD_NAP_BASE_VWS.PAYMENT_RESULT_BIN_FACT AS PRB
USING PAYMENT_RESULT_BIN_LDG_TEMP AS SRC
    ON (SRC.ID = PRB.ID)
WHEN MATCHED THEN
    UPDATE
        SET
            DW_SYS_UPDT_TMSTP = current_timestamp(0),
            ACQUIRER = SRC.ACQUIRER,
            AMOUNT_CURRENCY_CODE = SRC.AMOUNT_CURRENCY_CODE,
            AMOUNT = SRC.AMOUNT,
            BIN = SRC.BIN,
            EVENT_SOURCE = SRC.EVENT_SOURCE,
            TENDER_TYPE = SRC.TENDER_TYPE,
            APPROVAL_STATUS = SRC.APPROVAL_STATUS,
            CHANNEL_COUNTRY = SRC.CHANNEL_COUNTRY,
            CHANNEL_BRAND = SRC.CHANNEL_BRAND,
            SELLING_CHANNEL = SRC.SELLING_CHANNEL,
            TRANSACTION_DATE = SRC.TRANSACTION_DATE,
            STORE_NUMBER = SRC.STORE_NUMBER,
            ENTRY_MODE = SRC.ENTRY_MODE,
            BANK_CARD_CREDIT_RESPONSE_CODE = SRC.BANK_CARD_CREDIT_RESPONSE_CODE,
            BANK_CARD_DEBIT_RESPONSE_CODE = SRC.BANK_CARD_DEBIT_RESPONSE_CODE,
            VENDOR_ACTIVITY_DATE = SRC.VENDOR_ACTIVITY_DATE,
            VENDOR_CHARGEBACK_ID = SRC.VENDOR_CHARGEBACK_ID,
            CHARGEBACK_CATEGORY = SRC.CHARGEBACK_CATEGORY,
            CHARGEBACK_RESPONSE_CODE = SRC.CHARGEBACK_RESPONSE_CODE,
            CHARGEBACK_STATE = SRC.CHARGEBACK_STATE,
            INTERCHANGE_AMOUNT_CURRENCY_CODE
            = SRC.INTERCHANGE_AMOUNT_CURRENCY_CODE,
            INTERCHANGE_AMOUNT = SRC.INTERCHANGE_AMOUNT,
            INTERCHANGE_CODE = SRC.INTERCHANGE_CODE,
            INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE
            = SRC.INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE,
            INTERCHANGE_ADJUSTMENT_AMOUNT = SRC.INTERCHANGE_ADJUSTMENT_AMOUNT,
            INTERCHANGE_ADJUSTMENT_REASON = SRC.INTERCHANGE_ADJUSTMENT_REASON,
            CARD_TYPE = SRC.CARD_TYPE,
            CARD_SUBTYPE = SRC.CARD_SUBTYPE,
            BANK_CARD_AUTHORIZATION_TYPE = SRC.BANK_CARD_AUTHORIZATION_TYPE,
            SETTLEMENT_TRANSACTION_TYPE = SRC.SETTLEMENT_TRANSACTION_TYPE,
            MERCHANT_CATEGORY_CODE = SRC.MERCHANT_CATEGORY_CODE,
            AUTHORIZATION_CODE = SRC.AUTHORIZATION_CODE,
            VISA_AUTHORIZATION_RESPONSE_CODE = SRC.VISA_AUTHORIZATION_RESPONSE_CODE,
            AUTHORIZATION_SOURCE = SRC.AUTHORIZATION_SOURCE,
            VISA_VALIDATION_CODE = SRC.VISA_VALIDATION_CODE,
            CREDIT_RESPONSE_CATEGORY = SRC.CREDIT_RESPONSE_CATEGORY,
            DEBIT_RESPONSE_CATEGORY = SRC.DEBIT_RESPONSE_CATEGORY,
            VENDOR_AUTHORIZATION_SYSTEM = SRC.VENDOR_AUTHORIZATION_SYSTEM,
            AUTHORIZATION_SERVICE_INDICATOR = SRC.AUTHORIZATION_SERVICE_INDICATOR,
            MAIL_PHONE_INDICATOR = SRC.MAIL_PHONE_INDICATOR,
            ADDRESS_VERIFICATION_RESPONSE_CODE = SRC.ADDRESS_VERIFICATION_RESPONSE_CODE,
            CVV2_RESPONSE_INDICATOR = SRC.CVV2_RESPONSE_INDICATOR,
            CVV2_PRESENCE_INDICATOR = SRC.CVV2_PRESENCE_INDICATOR,
            CARD_PRODUCT_TYPE = SRC.CARD_PRODUCT_TYPE
WHEN NOT MATCHED THEN
    INSERT (
        DW_SYS_LOAD_TMSTP,
        DW_SYS_UPDT_TMSTP,
        ID,
        ACQUIRER,
        AMOUNT_CURRENCY_CODE,
        AMOUNT,
        BIN,
        EVENT_SOURCE,
        TENDER_TYPE,
        APPROVAL_STATUS,
        CHANNEL_COUNTRY,
        CHANNEL_BRAND,
        SELLING_CHANNEL,
        TRANSACTION_DATE,
        STORE_NUMBER,
        ENTRY_MODE,
        BANK_CARD_CREDIT_RESPONSE_CODE,
        BANK_CARD_DEBIT_RESPONSE_CODE,
        VENDOR_ACTIVITY_DATE,
        VENDOR_CHARGEBACK_ID,
        CHARGEBACK_CATEGORY,
        CHARGEBACK_RESPONSE_CODE,
        CHARGEBACK_STATE,
        INTERCHANGE_AMOUNT_CURRENCY_CODE,
        INTERCHANGE_AMOUNT,
        INTERCHANGE_CODE,
        INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE,
        INTERCHANGE_ADJUSTMENT_AMOUNT,
        INTERCHANGE_ADJUSTMENT_REASON,
        CARD_TYPE,
        CARD_SUBTYPE,
        BANK_CARD_AUTHORIZATION_TYPE,
        SETTLEMENT_TRANSACTION_TYPE,
        MERCHANT_CATEGORY_CODE,
        AUTHORIZATION_CODE,
        VISA_AUTHORIZATION_RESPONSE_CODE,
        AUTHORIZATION_SOURCE,
        VISA_VALIDATION_CODE,
        CREDIT_RESPONSE_CATEGORY,
        DEBIT_RESPONSE_CATEGORY,
        VENDOR_AUTHORIZATION_SYSTEM,
        AUTHORIZATION_SERVICE_INDICATOR,
        MAIL_PHONE_INDICATOR,
        ADDRESS_VERIFICATION_RESPONSE_CODE,
        CVV2_RESPONSE_INDICATOR,
        CVV2_PRESENCE_INDICATOR,
        CARD_PRODUCT_TYPE
    )
        VALUES (
            current_timestamp(0),
            current_timestamp(0),
            SRC.ID,
            SRC.ACQUIRER,
            SRC.AMOUNT_CURRENCY_CODE,
            SRC.AMOUNT,
            SRC.BIN,
            SRC.EVENT_SOURCE,
            SRC.TENDER_TYPE,
            SRC.APPROVAL_STATUS,
            SRC.CHANNEL_COUNTRY,
            SRC.CHANNEL_BRAND,
            SRC.SELLING_CHANNEL,
            SRC.TRANSACTION_DATE,
            SRC.STORE_NUMBER,
            SRC.ENTRY_MODE,
            SRC.BANK_CARD_CREDIT_RESPONSE_CODE,
            SRC.BANK_CARD_DEBIT_RESPONSE_CODE,
            SRC.VENDOR_ACTIVITY_DATE,
            SRC.VENDOR_CHARGEBACK_ID,
            SRC.CHARGEBACK_CATEGORY,
            SRC.CHARGEBACK_RESPONSE_CODE,
            SRC.CHARGEBACK_STATE,
            SRC.INTERCHANGE_AMOUNT_CURRENCY_CODE,
            SRC.INTERCHANGE_AMOUNT,
            SRC.INTERCHANGE_CODE,
            SRC.INTERCHANGE_ADJUSTMENT_AMOUNT_CURRENCY_CODE,
            SRC.INTERCHANGE_ADJUSTMENT_AMOUNT,
            SRC.INTERCHANGE_ADJUSTMENT_REASON,
            SRC.CARD_TYPE,
            SRC.CARD_SUBTYPE,
            SRC.BANK_CARD_AUTHORIZATION_TYPE,
            SRC.SETTLEMENT_TRANSACTION_TYPE,
            SRC.MERCHANT_CATEGORY_CODE,
            SRC.AUTHORIZATION_CODE,
            SRC.VISA_AUTHORIZATION_RESPONSE_CODE,
            SRC.AUTHORIZATION_SOURCE,
            SRC.VISA_VALIDATION_CODE,
            SRC.CREDIT_RESPONSE_CATEGORY,
            SRC.DEBIT_RESPONSE_CATEGORY,
            SRC.VENDOR_AUTHORIZATION_SYSTEM,
            SRC.AUTHORIZATION_SERVICE_INDICATOR,
            SRC.MAIL_PHONE_INDICATOR,
            SRC.ADDRESS_VERIFICATION_RESPONSE_CODE,
            SRC.CVV2_RESPONSE_INDICATOR,
            SRC.CVV2_PRESENCE_INDICATOR,
            SRC.CARD_PRODUCT_TYPE
        );

-- Remove records from temporary tables

DELETE FROM PREPROD_NAP_STG.PAYMENT_RESULT_BIN_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
