-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_cancel_teradata; Task_Name=teradata_tender_stg_to_teradata_tender_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE PAYMENT_CANCEL_TENDER_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_BASE_VWS.PAYMENT_CANCEL_TENDER_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY EVENT_ID ORDER BY CAST(EVENT_TIME AS TIMESTAMP) DESC
        ) = 1
) WITH DATA PRIMARY INDEX (EVENT_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_CANCEL_TENDER_FACT
WHERE EVENT_ID IN (SELECT DISTINCT EVENT_ID FROM PREPROD_NAP_BASE_VWS.PAYMENT_CANCEL_TENDER_LDG);

INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_CANCEL_TENDER_FACT
(
    EVENT_ID,
    ORDER_NUMBER,
    EVENT_TIME,
    ACTIVITY_DATE,
    EVENT_TYPE,
    TENDER_TYPE,
    TENDER_RECORD_NAME,
    CARD_TYPE,
    CARD_SUB_TYPE,
    TENDER_ITEM_ACCOUNT_NO,
    TENDER_ITEM_ACCOUNT_VALUE_TYPE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    CURRENCY_CODE,
    TOTAL_AMT,
    TRANSACTION_TIME,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    TRANSACTION_FAILURE_DESC,
    TOKEN_REQUESTOR_ID,
    GIFT_CARD_NOTE_TYPE,
    GIFT_CARD_ISSUANCE_ID,
    GIFT_CARD_REFUND_METHOD,
    GIFT_CARD_BALANCE_LOCK_ID,
    PAYPAL_ORDER_ID,
    PAYPAL_PAYER_ID,
    PAYPAL_BILLING_AGREEMENT_ID_VALUE,
    PAYPAL_PAYER_EMAIL_VALUE,
    PAYPAL_PAYER_ACCOUNT_COUNTRY,
    NOTE_REFUND_REASON,
    BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT DISTINCT
    EVENT_ID,
    ORDER_NUMBER,
    CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
    CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS ACTIVITY_DATE,
    EVENT_TYPE,
    TENDER_TYPE,
    TENDER_RECORD_NAME,
    CARD_TYPE,
    CARD_SUB_TYPE,
    TENDER_ITEM_ACCOUNT_NO,
    TENDER_ITEM_ACCOUNT_VALUE_TYPE,
    TOKEN_AUTHORITY,
    TOKEN_DATA_CLASSIFICATION,
    TOKEN_TYPE,
    CURRENCY_CODE,
    CAST(TOTAL_AMT AS DECIMAL(14, 4)) AS TOTAL_AMT,
    CAST(TRANSACTION_TIME AS TIMESTAMP) AS TRANSACTION_TIME,
    TRANSACTION_TYPE,
    TRANSACTION_STATUS,
    TRANSACTION_FAILURE_DESC,
    TOKEN_REQUESTOR_ID,
    GIFT_CARD_NOTE_TYPE,
    GIFT_CARD_ISSUANCE_ID,
    GIFT_CARD_REFUND_METHOD,
    GIFT_CARD_BALANCE_LOCK_ID,
    PAYPAL_ORDER_ID,
    PAYPAL_PAYER_ID,
    PAYPAL_BILLING_AGREEMENT_ID_VALUE,
    PAYPAL_PAYER_EMAIL_VALUE,
    PAYPAL_PAYER_ACCOUNT_COUNTRY,
    NOTE_REFUND_REASON,
    CURRENT_DATE AS BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM PAYMENT_CANCEL_TENDER_TEMP;

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_CANCEL_TENDER_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
