SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=ecf_salesreporting_to_s3_extract_2656_napstore_insights;
Task_Name=ecf_salesreporting_extract_load_0_ecf_salesreporting;'
FOR SESSION VOLATILE;

--Reading Data from  Source Teradata
create temporary view  temp_ecf_salesreporting_read AS

SELECT
business_date,
'USD' as currency_code,
trim(leading '0' from employee_id) as employee_id,
digital_gross_amt_ty,
digital_gross_amt_ly,
digital_return_amt_ty,
digital_return_amt_ly,
digital_net_amt_ty,
digital_net_amt_ly,
store_gross_amt_ty,
store_gross_amt_ly,
store_net_amt_ty,
store_net_amt_ly,
gross_amt_ty,
gross_amt_ly,
return_amt_ty,
return_amt_ly,
net_amt_ty,
net_amt_ly,
digital_gross_amt_w2d,
digital_gross_amt_w2d_ly,
digital_return_amt_w2d,
digital_return_amt_w2d_ly,
digital_net_amt_w2d,
digital_net_amt_w2d_ly,
store_gross_amt_w2d,
store_gross_amt_w2d_ly,
store_return_amt_w2d,
store_return_amt_w2d_ly,
store_net_amt_w2d,
store_net_amt_w2d_ly,
gross_amt_w2d,
gross_amt_w2d_ly,
return_amt_w2d,
return_amt_w2d_ly,
net_amt_w2d,
net_amt_w2d_ly,
digital_gross_amt_m2d,
digital_gross_amt_m2d_ly,
digital_return_amt_m2d,
digital_return_amt_m2d_ly,
digital_net_amt_m2d,
digital_net_amt_m2d_ly,
store_gross_amt_m2d,
store_gross_amt_m2d_ly,
store_return_amt_m2d,
store_return_amt_m2d_ly,
store_net_amt_m2d,
store_net_amt_m2d_ly,
gross_amt_m2d,
gross_amt_m2d_ly,
return_amt_m2d,
return_amt_m2d_ly,
net_amt_m2d,
net_amt_m2d_ly,
digital_gross_amt_pp2d,
digital_gross_amt_pp2d_ly,
digital_return_amt_pp2d,
digital_return_amt_pp2d_ly,
digital_net_amt_pp2d,
digital_net_amt_pp2d_ly,
store_gross_amt_pp2d,
store_gross_amt_pp2d_ly,
store_return_amt_pp2d,
store_return_amt_pp2d_ly,
store_net_amt_pp2d,
store_net_amt_pp2d_ly,
gross_amt_pp2d,
gross_amt_pp2d_ly,
return_amt_pp2d,
return_amt_pp2d_ly,
net_amt_pp2d,
net_amt_pp2d_ly,
digital_gross_amt_y2d,
digital_gross_amt_y2d_ly,
digital_return_amt_y2d,
digital_return_amt_y2d_ly,
digital_net_amt_y2d,
digital_net_amt_y2d_ly,
store_gross_amt_y2d,
store_gross_amt_y2d_ly,
store_return_amt_y2d,
store_return_amt_y2d_ly,
store_net_amt_y2d,
store_net_amt_y2d_ly,
gross_amt_y2d,
gross_amt_y2d_ly,
return_amt_y2d,
return_amt_y2d_ly,
net_amt_y2d,
net_amt_y2d_ly
FROM ecf_salesreporting_vw;


--Writing Data from Teradata to S3
insert into table ecf_salesreporting_s3_output   PARTITION (year, month, day )
select *,year( current_date()-1) as year,month( current_date()-1) as month,day( current_date() -1) as day
from temp_ecf_salesreporting_read;
