SET QUERY_BAND = '
App_ID=app02239;
DAG_ID=hr_worker_event_load_v1_2656_napstore_insights;
Task_Name=hr_worker_event_v1_load_td_stg_to_dims;'
FOR SESSION VOLATILE;

ET;

-- Create temporary table that has the latest data for each worker number and worker type.
CREATE VOLATILE MULTISET TABLE HR_WORKER_EVENT_DIM_UNIQUE_TEMP AS (
    SELECT DISTINCT
    workerNumber,
    case when businessUnitId='' then NULL else businessUnitId end as businessUnitId,
    case when businessUnitDescription='' then NULL else businessUnitDescription end as businessUnitDescription,
    NORD_UDF.EPOCH_TMSTP(changeEffectiveDate) as changeEffectiveDate,
    case when commissionPlanName='' then NULL else commissionPlanName end as commissionPlanName,
    case when companyHierarchy='' then NULL else companyHierarchy end as companyHierarchy,
    case when companyName='' then NULL else companyName end as companyName,
    case when compensationCurrency='' then NULL else compensationCurrency end as compensationCurrency,
    date '1970-01-01' + contingentWorkerProjectedEndDate as contingentWorkerProjectedEndDate,
    case when contingentWorkerVendorName='' then NULL else contingentWorkerVendorName end as contingentWorkerVendorName,
    case when contingentWorkerVendorNumber='' then NULL else contingentWorkerVendorNumber end as contingentWorkerVendorNumber,
    case when corporateEmail='' then NULL else corporateEmail end as corporateEmail,
    case when cosmeticLineAssignment='' then NULL else cosmeticLineAssignment end as cosmeticLineAssignment,
    case when costCenterId='' then NULL else costCenterId end as costCenterId,
    case when costCenterName='' then NULL else costCenterName end as costCenterName,
    case when discountPercent='' then NULL else discountPercent end as discountPercent,
    case when discountStatus='' then NULL else discountStatus end as discountStatus,
    date '1970-01-01' + hireDate as hireDate ,
    case when isJobExempt='' then NULL else isJobExempt end as isJobExempt,
    case when isPurged='' then NULL else isPurged end as isPurged,
    case when isOnsite='' then NULL else isOnsite end as isOnsite,
    case when isRemoteWorker='' then NULL else isRemoteWorker end as isRemoteWorker,
    case when jobFamily='' then NULL else jobFamily end as jobFamily,
    case when jobFamilyGroup='' then NULL else jobFamilyGroup end as jobFamilyGroup,
    case when jobTitle='' then NULL else jobTitle end as jobTitle,
    case when lanId='' then NULL else lanId end as lanId,
    case when beautyLineAssignment='' then NULL else beautyLineAssignment end as beautyLineAssignment,
    case when lineAssignment='' then NULL else lineAssignment end as lineAssignment,
    case when locationName='' then NULL else locationName end as locationName,
    case when locationNumber='' then NULL else locationNumber end as locationNumber,
    case when managerLanId='' then NULL else managerLanId end as managerLanId,
    case when managerWorkerNumber='' then NULL else managerWorkerNumber end as managerWorkerNumber,
    case when organizationDescription='' then NULL else organizationDescription end as organizationDescription,
    date '1970-01-01' + originalHireDate as originalHireDate,
    case when otherLineAssignment='' then NULL else otherLineAssignment end as otherLineAssignment,
    case when payRateType='' then NULL else payRateType end as payRateType,
    case when payrollDepartment='' then NULL else payrollDepartment end as payrollDepartment,
    case when payrollDepartmentDescription='' then NULL else payrollDepartmentDescription end as payrollDepartmentDescription,
    case when payrollStore='' then NULL else payrollStore end as payrollStore,
    case when payrollStoreDescription='' then NULL else payrollStoreDescription end as payrollStoreDescription,
    case when regionDescription='' then NULL else regionDescription end as regionDescription,
    case when regionNumber='' then NULL else regionNumber end as regionNumber,
    date '1970-01-01' + terminationDate as terminationDate,
    case when workerStatus='' then NULL else workerStatus end as workerStatus,
    case when workerSubType='' then NULL else workerSubType end as workerSubType,
    case when workerType='' then NULL else workerType end as workerType,
    case when workLocationCountry='' then NULL else workLocationCountry end as workLocationCountry,
    case when firstName='' then NULL else firstName end as firstName,
    case when lastName='' then NULL else lastName end as lastName,
    case when middleName='' then NULL else middleName end as middleName,
    case when preferredLastName='' then NULL else preferredLastName end as preferredLastName,
    case when preferredName='' then NULL else preferredName end as preferredName
    FROM {db_env}_NAP_HR_STG.HR_WORKER_V2_LDG
    qualify row_number() over (partition BY workerNumber ORDER BY changeEffectiveDate DESC) = 1
) WITH DATA PRIMARY INDEX(workerNumber) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update if worker number exist.
MERGE INTO {db_env}_NAP_HR_BASE_VWS.HR_WORKER_V2_DIM tgt
 USING  HR_WORKER_EVENT_DIM_UNIQUE_TEMP src
	ON (src.workerNumber = tgt.worker_number)
WHEN MATCHED THEN
UPDATE
SET
      business_unit_id = src.businessUnitId,
      business_unit_description = src.businessUnitDescription,
      change_effective_date = src.changeEffectiveDate,
      commission_plan_name = src.commissionPlanName,
      company_hierarchy = src.companyHierarchy,
      company_name = src.companyName,
      compensation_currency = src.CompensationCurrency,
      contingent_worker_projected_end_date = src.contingentWorkerProjectedEndDate,
      contingent_worker_vendor_name = src.contingentWorkerVendorName,
      contingent_worker_vendor_number = src.contingentWorkerVendorNumber,
      corporate_email = src.corporateEmail,
      cosmetic_line_assignment = src.cosmeticLineAssignment,
      cost_center_id = src.costCenterId,
      cost_center_name = src.costCenterName,
      discount_percent = src.discountPercent,
      discount_status = src.discountStatus,
      hire_date = src.hireDate,
      is_job_exempt = src.isJobExempt,
      is_purged = src.isPurged,
      is_onsite = src.isOnsite,
      is_remote_worker = src.isRemoteWorker,
      job_family = src.jobFamily,
      job_family_group = src.jobFamilyGroup,
      job_title = src.jobTitle,
      lan_id = src.lanId,
      beauty_line_assignment = src.beautyLineAssignment,
      line_assignment = src.lineAssignment,
      location_name = src.locationName,
      location_number = src.locationNumber,
      manager_lan_id = src.managerLanId,
      manager_worker_number = src.managerWorkerNumber,
      organization_description = src.organizationDescription,
      original_hire_date = src.originalHireDate,
      other_line_assignment = src.otherLineAssignment,
      pay_rate_type = src.payRateType,
      payroll_department = src.payrollDepartment,
      payroll_department_description = src.payrollDepartmentDescription,
      payroll_store = src.payrollStore,
      payroll_store_description = src.payrollStoreDescription,
      region_description = src.regionDescription,
      region_number = src.regionNumber,
      termination_date = src.terminationDate,
      worker_status = src.workerStatus,
      worker_subtype = src.workerSubType,
      worker_type = src.workerType,
      work_location_country = src.workLocationCountry,
      first_name = src.firstName,
      last_name = src.lastName,
      middle_name = src.middleName,
      preferred_last_name = src.preferredLastName,
      preferred_name = src.preferredName,
      dw_batch_date = CURRENT_DATE,
      dw_sys_load_tmstp = CURRENT_TIMESTAMP(0)

WHEN NOT MATCHED THEN
INSERT (
      business_unit_id,
      business_unit_description,
      change_effective_date,
      commission_plan_name,
      company_hierarchy,
      company_name,
      compensation_currency,
      contingent_worker_projected_end_date,
      contingent_worker_vendor_name,
      contingent_worker_vendor_number,
      corporate_email,
      cosmetic_line_assignment,
      cost_center_id,
      cost_center_name,
      discount_percent,
      discount_status,
      hire_date,
      is_job_exempt,
      is_purged,
      is_onsite,
      is_remote_worker,
      job_family,
      job_family_group,
      job_title,
      lan_id,
      beauty_line_assignment,
      line_assignment,
      location_name,
      location_number,
      manager_lan_id,
      manager_worker_number,
      organization_description,
      original_hire_date,
      other_line_assignment,
      pay_rate_type,
      payroll_department,
      payroll_department_description,
      payroll_store,
      payroll_store_description,
      region_description,
      region_number,
      termination_date,
      worker_number,
      worker_status,
      worker_subtype,
      worker_type,
      work_location_country,
      first_name,
      last_name,
      middle_name,
      preferred_last_name,
      preferred_name,
      dw_batch_date,
      dw_sys_load_tmstp
)
VALUES (
      src.businessUnitId,
      src.businessUnitDescription,
      src.changeEffectiveDate,
      src.commissionPlanName,
      src.companyHierarchy,
      src.companyName,
      src.compensationCurrency,
      src.contingentWorkerProjectedEndDate,
      src.contingentWorkerVendorName,
      src.contingentWorkerVendorNumber,
      src.corporateEmail,
      src.cosmeticLineAssignment,
      src.costCenterId,
      src.costCenterName,
      src.discountPercent,
      src.discountStatus,
      src.hireDate,
      src.isJobExempt,
      src.isPurged,
      src.isOnsite,
      src.isRemoteWorker,
      src.jobFamily,
      src.jobFamilyGroup,
      src.jobTitle,
      src.lanId,
      src.beautyLineAssignment,
      src.lineAssignment,
      src.locationName,
      src.locationNumber,
      src.managerLanId,
      src.managerWorkerNumber,
      src.organizationDescription,
      src.originalHireDate,
      src.otherLineAssignment,
      src.payRateType,
      src.payrollDepartment,
      src.payrollDepartmentDescription,
      src.payrollStore,
      src.payrollStoreDescription,
      src.regionDescription,
      src.regionNumber,
      src.terminationDate,
      src.workerNumber,
      src.workerStatus,
      src.workerSubType,
      src.workerType,
      src.workLocationCountry,
      src.firstName,
      src.lastName,
      src.middleName,
      src.preferredLastName,
      src.preferredName,
      CURRENT_DATE,
      CURRENT_TIMESTAMP(0)
);
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
