SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_forecasted_metric_load_2656_napstore_insights;
Task_Name=wfm_forecasted_metric_load_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_FORECASTED_METRIC_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.FORECASTED_METRIC_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.FORECASTED_METRIC_FACT tgt
    USING WFM_FORECASTED_METRIC_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	STORE_NUMBER = src.STORE_NUMBER,
    METRIC_ID = src.METRIC_ID,
    METRIC_FREQUENCY = src.METRIC_FREQUENCY,
    FORECAST_GROUP_ID = src.FORECAST_GROUP_ID,
	EFFECTIVE_DATE = CAST(src.EFFECTIVE_DATE as DATE FORMAT 'YYYY-MM-DD'),
	LOCAL_EFFECTIVE_TIME = TIME '00:00:00' + CAST (SRC.LOCAL_EFFECTIVE_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	FINAL_FORECAST_VALUE = src.FINAL_FORECAST_VALUE,
	BASELINE_FORECAST_VALUE = src.BASELINE_FORECAST_VALUE,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)

WHEN NOT MATCHED THEN
INSERT (
    ID,
    CREATED_AT,
    LAST_UPDATED_AT,
    STORE_NUMBER,
    METRIC_ID,
    METRIC_FREQUENCY,
    FORECAST_GROUP_ID,
    EFFECTIVE_DATE,
    LOCAL_EFFECTIVE_TIME,
    FINAL_FORECAST_VALUE,
    BASELINE_FORECAST_VALUE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.STORE_NUMBER,
    src.METRIC_ID,
    src.METRIC_FREQUENCY,
    src.FORECAST_GROUP_ID,
    CAST(src.EFFECTIVE_DATE as DATE FORMAT 'YYYY-MM-DD'),
    TIME '00:00:00' + CAST (SRC.LOCAL_EFFECTIVE_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    src.FINAL_FORECAST_VALUE,
    src.BASELINE_FORECAST_VALUE,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
