SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_employee_borrowing_assignment_load_2656_napstore_insights;
Task_Name=wfm_employee_borrowing_assignment_0_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Employee borrowing assignment
CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_BORROWING_ASSIGNMENT_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.EMPLOYEE_BORROWING_ASSIGNMENT_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_BORROWING_ASSIGNMENT_FACT tgt
    USING WFM_EMPLOYEE_BORROWING_ASSIGNMENT_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	EMPLOYEE_ID = src.EMPLOYEE_ID,
	START_DATE = CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
	END_DATE = case when src.END_DATE IS NULL then NULL else CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD') end,
	STORE_NUMBER = src.STORE_NUMBER,
	IS_DELETED = cast(src.IS_DELETED as BYTEINT),
	DELETED_AT = src.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    CREATED_AT,
    LAST_UPDATED_AT,
    EMPLOYEE_ID,
    START_DATE,
    END_DATE,
    STORE_NUMBER,
    IS_DELETED,
    DELETED_AT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.EMPLOYEE_ID,
    CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    case when src.END_DATE IS NULL then NULL else CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD') end,
    src.STORE_NUMBER,
	cast(src.IS_DELETED as BYTEINT),
	DELETED_AT = src.DELETED_AT,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
