SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_scheduling_data_load_2656_napstore_insights;
Task_Name=wfm_scheduling_forecast_group_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_SCHEDULING_FORECAST_GROUP_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.SCHEDULING_FORECAST_GROUP_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.SCHEDULING_FORECAST_GROUP_FACT tgt
    USING WFM_SCHEDULING_FORECAST_GROUP_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
    NAME = src.NAME,
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
    DELETED = SRC.DELETED,
	DELETED_AT = SRC.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    NAME,
    CREATED_AT,
    LAST_UPDATED_AT,
    DELETED,
    DELETED_AT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.NAME,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.DELETED,
    src.DELETED_AT,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
