SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_scheduling_data_load_2656_napstore_insights;
Task_Name=wfm_scheduling_labor_role_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- CREATE TEMPORARY TABLE THAT HAS THE LATEST UNIQUE DATA FOR EACH JOB:
CREATE
VOLATILE MULTISET TABLE WFM_SCHEDULING_LABOR_ROLE_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.SCHEDULING_LABOR_ROLE_STG
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- MERGE AND UPDATE:
MERGE INTO {db_env}_NAP_FCT.SCHEDULING_LABOR_ROLE_FACT TGT
    USING WFM_SCHEDULING_LABOR_ROLE_TEMP SRC
    ON (SRC.ID = TGT.ID)
    WHEN MATCHED THEN
UPDATE
SET
	CREATED_AT = SRC.CREATED_AT,
	LAST_UPDATED_AT = SRC.LAST_UPDATED_AT,
	NAME = SRC.NAME,
	DELETED = SRC.DELETED,
	DELETED_AT = src.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    CREATED_AT,
    LAST_UPDATED_AT,
    ID,
    NAME,
    DELETED,
    DELETED_AT,
	DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    SRC.CREATED_AT,
    SRC.LAST_UPDATED_AT,
    SRC.ID,
    SRC.NAME,
    SRC.DELETED,
    SRC.DELETED_AT,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
