SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_scheduling_data_load_2656_napstore_insights;
Task_Name=wfm_scheduling_department_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- SCHEDULING DEPARTMENT
-- Create temporary table that has the latest unique data for each job:
CREATE
VOLATILE MULTISET TABLE WFM_SCHEDULING_DEPARTMENT_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.SCHEDULING_DEPARTMENT_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.SCHEDULING_DEPARTMENT_FACT tgt
    USING WFM_SCHEDULING_DEPARTMENT_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
    SET
    NAME = src.NAME,
    CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	DELETED = src.DELETED,
	DELETED_AT = src.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    NAME,
    CREATED_AT,
    LAST_UPDATED_AT,
    DELETED,
    DELETED_AT,
	DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.NAME,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.DELETED,
    src.DELETED_AT,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

-- SCHEDULING JOB
-- Create temporary table that has the latest unique data for each job:
CREATE
VOLATILE MULTISET TABLE WFM_SCHEDULING_JOB_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.SCHEDULING_JOB_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.SCHEDULING_JOB_FACT tgt
    USING WFM_SCHEDULING_JOB_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
	NAME = src.NAME,
	DEPARTMENT_ID = src.DEPARTMENT_ID,
    LABOR_ROLE_IDS = src.LABOR_ROLE_IDS,
    WORK_GROUP_IDS = src.WORK_GROUP_IDS,
    CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	DELETED = case when LOWER(src.DELETED) = 'true' then 1 else 0 end,
	DELETED_AT = src.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    NAME,
    DEPARTMENT_ID,
    LABOR_ROLE_IDS,
    WORK_GROUP_IDS,
    CREATED_AT,
    LAST_UPDATED_AT,
    DELETED,
    DELETED_AT,
	DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.NAME,
    src.DEPARTMENT_ID,
    src.LABOR_ROLE_IDS,
    src.WORK_GROUP_IDS,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    case when LOWER(src.DELETED) = 'true' then 1 else 0 end,
    src.DELETED_AT,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
