/* 
SQL script must begin with QUERY_BAND SETTINGS
*/
SET QUERY_BAND = 'App_ID=APP08905;
     DAG_ID=nap_migration_teradata_object_dependency_11521_ACE_ENG;
     Task_Name=teradata_object_dependency;'
     FOR SESSION VOLATILE;


CREATE MULTISET VOLATILE TABLE obj_data AS (
SELECT TA.DATABASENAME  AS SOURCE_DB,
       TA.TABLENAME  AS SOURCE_OBJ,
       TA.TABLEKIND AS SOURCE_OBJ_KIND,
       D.DATABASENAME AS TARGET_DB,
       T.TVMNAME AS TARGET_OBJ,
       T.TABLEKIND AS TARGET_OBJ_KIND
FROM   DBC.TVM T,
       DBC.DBASE D ,
       DBC.TABLESv TA
WHERE D.DATABASEID = T.DATABASEID
      AND T.CREATETEXT LIKE '%"' !! TRIM (TA.DATABASENAME) !! '"."'!! TRIM (TA.TABLENAME)!! '"%' (NOT CS)
UNION
SELECT TA.DATABASENAME AS SOURCE_DB,
       TA.TABLENAME AS SOURCE_OBJ,
       TA.TABLEKIND AS SOURCE_OBJ_KIND,
       D.DATABASENAME AS TARGET_DB,
       T.TVMNAME AS TARGET_OBJ,
       T.TABLEKIND AS TARGET_OBJ_KIND
FROM   DBC.TEXTTBL X,
       DBC.DBASE D,
       DBC.TVM T,
       DBC.TABLESv TA
WHERE X.TEXTTYPE='C'
      AND X.TEXTSTRING LIKE '%"' !! TRIM (TA.DATABASENAME) !! '"."'!! TRIM (TA.TABLENAME)!! '"%' (NOT CS)
      AND X.DATABASEID=D.DATABASEID
      AND X.TEXTID=T.TVMID
MINUS
SELECT TA.DATABASENAME AS SOURCE_DB,
       TA.TABLENAME AS SOURCE_OBJ,
       TA.TABLEKIND AS SOURCE_OBJ_KIND,
       D.DATABASENAME AS TARGET_DB,
       T.TVMNAME AS TARGET_OBJ,
       T.TABLEKIND AS TARGET_OBJ_KIND
FROM   DBC.TVM T,
       DBC.DBASE D,
       DBC.TABLESv TA
WHERE D.DATABASEID=T.DATABASEID
      AND D.DATABASENAME= TA.DATABASENAME
      AND T.TVMNAME= TA.TABLENAME
) WITH DATA
PRIMARY INDEX (SOURCE_DB,SOURCE_OBJ)
ON COMMIT PRESERVE ROWS
;


DELETE
FROM obj_data
WHERE TRIM (SOURCE_DB) !! TRIM(SOURCE_OBJ) = TRIM (TARGET_DB) !! TRIM(TARGET_OBJ)
;


DELETE 
FROM  {techex_t2_schema}.teradata_object_dependency
;

INSERT INTO {techex_t2_schema}.teradata_object_dependency 
WITH RECURSIVE DEPENDENT
( SOURCE_DB,
  SOURCE_OBJ,
  SOURCE_OBJ_KIND,
  DEPENDENT_DB,
  DEPENDENT_OBJ,
  DEPENDENT_OBJ_KIND,
  DEPENDENCY_LEVEL
)
AS
(
SELECT SOURCE_DB,
       SOURCE_OBJ,
       SOURCE_OBJ_KIND,
       TARGET_DB AS DEPENDENT_DB,
       TARGET_OBJ AS DEPENDENT_OBJ,
       TARGET_OBJ_KIND AS DEPENDENT_OBJ_KIND,
       CAST(1 AS SMALLINT) AS DEPENDENCY_LEVEL
FROM  obj_data
UNION ALL
SELECT D.SOURCE_DB,
       D.SOURCE_OBJ,
       D.SOURCE_OBJ_KIND,
       O.TARGET_DB AS DEPENDENT_DB,
       O.TARGET_OBJ AS DEPENDENT_OBJ,
       O.TARGET_OBJ_KIND AS DEPENDENT_OBJ_KIND,
       D.DEPENDENCY_LEVEL + 1 AS DEPENDENCY_LEVEL
FROM  obj_data  O
     JOIN
     DEPENDENT D
        ON O.SOURCE_DB = D.DEPENDENT_DB
           AND O.SOURCE_OBJ = D.DEPENDENT_OBJ
           AND D.DEPENDENCY_LEVEL <= 100
)
SELECT *
FROM DEPENDENT
;

/* 
SQL script must end with statement to turn off QUERY_BAND 
*/
SET QUERY_BAND = NONE FOR SESSION;


