CALL {db_env}_NAP_UTL.BATCH_END_SP ('INVENTORY_STORE_NON_CUSTOMER_ORDER_SHIPPING_LABEL_GENERATED_FACT');
CALL {db_env}_NAP_UTL.BATCH_CLEAN_SP ('INVENTORY_STORE_NON_CUSTOMER_ORDER_SHIPPING_LABEL_GENERATED_FACT');
