CREATE
VOLATILE MULTISET TABLE #SHIPPING_LABEL_GEN_TEMP AS (
  WITH ETL_BATCH_INFO AS (
    SELECT MAX(batch_id) AS dw_batch_id
         , MAX(batch_date) AS dw_batch_date
    FROM {db_env}_NAP_BASE_VWS.ETL_BATCH_INFO
    WHERE INTERFACE_CODE = 'INVENTORY_STORE_NON_CUSTOMER_ORDER_SHIPPING_LABEL_GENERATED_FACT'
    AND dw_sys_end_tmstp IS NULL ),
  SHIPPING_LABEL_GEN_TEMP AS (
    SELECT DISTINCT
               eventTime,
               CAST(eventTime AS TIMESTAMP(6)) AT 'America Pacific' as eventTimePacific,
               CAST(CAST(eventTime AS TIMESTAMP(6)) AT 'America Pacific' AS DATE FORMAT 'YYYY-MM-DD') as eventDatePacific,
               kafkaTimestamp,
               shippingNode_locationType,
               shippingNode_id,
               user_type,
               user_systemId,
               user_employee_idType,
               user_employee_id,
               user_externalUser_type,
               user_externalUser_id_value,
               user_externalUser_id_authority,
               user_externalUser_id_strategy,
               user_externalUser_id_dataClassification,
               shipmentType,
               vendorNumber,
               partnerRelationship_id,
               partnerRelationship_type,
               cartonNumber,
               plannedShipDate,
               recipientFullName,
               shipToAddress_line1,
               shipToAddress_line2,
               shipToAddress_line3,
               shipToAddress_city,
               shipToAddress_state,
               shipToAddress_postalCode,
               shipToAddress_countryCode,
               shippingCharge_currencyCode,
               shippingCharge_amount,
               shippingCharge_units,
               shippingCharge_nanos,
               estimatedDeliveryDate,
               shippingLabelDetails_scac,
               shippingLabelDetails_trackingNumber,
               sourceSystem,
               itemDetails_productSku_id,
               itemDetails_productSku_idType,
               itemDetails_quantity,
               itemDetails_multiplier,
               dw_batch_id,
               dw_batch_date
               FROM {db_env}_NAP_STG.INVENTORY_STORE_NON_CUSTOMER_ORDER_SHIPPING_LABEL_GENERATED_LDG
    LEFT JOIN ETL_BATCH_INFO ON 1=1
    qualify row_number() over (partition BY cartonNumber, shippingLabelDetails_trackingNumber, itemDetails_productSku_id, eventTime ORDER BY kafkaTimestamp DESC) = 1)
  SELECT * FROM SHIPPING_LABEL_GEN_TEMP ldg
) WITH DATA PRIMARY INDEX(cartonNumber, shippingLabelDetails_trackingNumber, itemDetails_productSku_id, eventTime) ON COMMIT PRESERVE ROWS;
ET;
-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.INVENTORY_STORE_NON_CUSTOMER_ORDER_SHIPPING_LABEL_GENERATED_FACT tgt
    USING #SHIPPING_LABEL_GEN_TEMP src
    ON (src.cartonNumber = tgt.carton_number
        AND src.shippingLabelDetails_trackingNumber = tgt.tracking_number
        AND src.itemDetails_productSku_id = tgt.product_sku_id
        AND src.eventTime = tgt.event_tmstp)
    WHEN MATCHED THEN UPDATE SET
    event_tmstp_pacific = src.eventTimePacific,
    event_date_pacific = src.eventDatePacific,
    kafka_timestamp = src.kafkaTimestamp,
    shipping_node_location_type = src.shippingNode_locationType,
    shipping_node_id = src.shippingNode_id,
    user_type = src.user_type,
    user_system_id = src.user_systemId,
    employee_id_type = src.user_employee_idType,
    employee_id = src.user_employee_id,
    external_user_type = src.user_externalUser_type,
    external_user_id_value = src.user_externalUser_id_value,
    external_user_id_authority = src.user_externalUser_id_authority,
    external_user_id_strategy = src.user_externalUser_id_strategy,
    external_user_id_data_classification = src.user_externalUser_id_dataClassification,
    shipment_type = src.shipmentType,
    vendor_number = src.vendorNumber,
    partner_relationship_id = src.partnerRelationship_id,
    partner_relationship_type = src.partnerRelationship_type,
    planned_ship_date = src.plannedShipDate,
    recipient_full_name = src.recipientFullName,
    ship_to_address_line1 = src.shipToAddress_line1,
    ship_to_address_line2 = src.shipToAddress_line2,
    ship_to_address_line3 = src.shipToAddress_line3,
    ship_to_address_city = src.shipToAddress_city,
    ship_to_address_state = src.shipToAddress_state,
    ship_to_address_postal_code = src.shipToAddress_postalCode,
    ship_to_address_country_code = src.shipToAddress_countryCode,
    shipping_charge_currency_code = src.shippingCharge_currencyCode,
    shipping_charge_amount = src.shippingCharge_amount,
    shipping_charge_units = src.shippingCharge_units,
    shipping_charge_nanos = src.shippingCharge_nanos,
    product_sku_id_type = src.itemDetails_productSku_idType,
    quantity = src.itemDetails_quantity,
    multiplier = src.itemDetails_multiplier,
    estimated_delivery_date = src.estimatedDeliveryDate,
    scac = src.shippingLabelDetails_scac,
    source_system = src.sourceSystem,
    dw_batch_id = src.dw_batch_id,
	dw_batch_date = src.dw_batch_date,
	dw_sys_updt_tmstp = CURRENT_TIMESTAMP(0)

WHEN NOT MATCHED THEN INSERT (
    event_tmstp,
    event_tmstp_pacific,
    event_date_pacific,
    kafka_timestamp,
    shipping_node_location_type,
    shipping_node_id,
    user_type,
    user_system_id,
    employee_id_type,
    employee_id,
    external_user_type,
    external_user_id_value,
    external_user_id_authority,
    external_user_id_strategy,
    external_user_id_data_classification,
    shipment_type,
    vendor_number,
    partner_relationship_id,
    partner_relationship_type,
    carton_number,
    planned_ship_date,
    recipient_full_name,
    ship_to_address_line1,
    ship_to_address_line2,
    ship_to_address_line3,
    ship_to_address_city,
    ship_to_address_state,
    ship_to_address_postal_code,
    ship_to_address_country_code,
    shipping_charge_currency_code,
    shipping_charge_amount,
    shipping_charge_units,
    shipping_charge_nanos,
    product_sku_id,
    product_sku_id_type,
    quantity,
    multiplier,
    estimated_delivery_date,
    scac,
    tracking_number,
    source_system,
    dw_batch_id,
    dw_batch_date,
    dw_sys_load_tmstp,
    dw_sys_updt_tmstp
)
VALUES (
      src.eventTime,
      src.eventTimePacific,
      src.eventDatePacific,
      src.kafkaTimestamp,
      src.shippingNode_locationType,
      src.shippingNode_id,
      src.user_type,
      src.user_systemId,
      src.user_employee_idType,
      src.user_employee_id,
      src.user_externalUser_type,
      src.user_externalUser_id_value,
      src.user_externalUser_id_authority,
      src.user_externalUser_id_strategy,
      src.user_externalUser_id_dataClassification,
      src.shipmentType,
      src.vendorNumber,
      src.partnerRelationship_id,
      src.partnerRelationship_type,
      src.cartonNumber,
      src.plannedShipDate,
      src.recipientFullName,
      src.shipToAddress_line1,
      src.shipToAddress_line2,
      src.shipToAddress_line3,
      src.shipToAddress_city,
      src.shipToAddress_state,
      src.shipToAddress_postalCode,
      src.shipToAddress_countryCode,
      src.shippingCharge_currencyCode,
      src.shippingCharge_amount,
      src.shippingCharge_units,
      src.shippingCharge_nanos,
      src.itemDetails_productSku_id,
      src.itemDetails_productSku_idType,
      src.itemDetails_quantity,
      src.itemDetails_multiplier,
      src.estimatedDeliveryDate,
      src.shippingLabelDetails_scac,
      src.shippingLabelDetails_trackingNumber,
      src.sourceSystem,
      src.dw_batch_id,
	  src.dw_batch_date,
      CURRENT_TIMESTAMP(0),
      CURRENT_TIMESTAMP(0)
    );
ET;
