CALL {db_env}_NAP_UTL.BATCH_END_SP ('INVENTORY_DEXTR_NAVI_STORE_RETURN_TO_VENDOR_LIFECYCLE_FACT');
CALL {db_env}_NAP_UTL.BATCH_CLEAN_SP ('INVENTORY_DEXTR_NAVI_STORE_RETURN_TO_VENDOR_LIFECYCLE_FACT');
