-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app06788; DAG_ID=credit_account_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE CREDIT_ACCOUNT_LDG_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_CREDIT_STG.CREDIT_ACCOUNT_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY CREDIT_ACCOUNT_ID ORDER BY OPENED_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (CREDIT_ACCOUNT_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE CREDIT_ACCOUNT_BANK_CARD_LDG_TEMP AS (
    SELECT DISTINCT *
    FROM {db_env}_NAP_CREDIT_STG.CREDIT_ACCOUNT_BANK_CARD_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY CARD_ID ORDER BY ADDED_DATE DESC
        ) = 1
) WITH DATA PRIMARY INDEX (CARD_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;


-- Purge and reprocess data to account for updates
DELETE FROM {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_ACCOUNT_FACT
WHERE
    CREDIT_ACCOUNT_ID IN (SELECT CREDIT_ACCOUNT_ID FROM CREDIT_ACCOUNT_LDG_TEMP);

INSERT INTO {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_ACCOUNT_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    OPENED_TIME,
    CLOSED_DATE,
    OPENED_CHANNEL_COUNTRY,
    OPENED_CHANNEL_BRAND,
    SELLING_CHANNEL,
    CREDIT_ACCOUNT_ID,
    CREDIT_APPLICATION_ID,
    STATUS,
    METADATA_CREATED_TIME,
    METADATA_LAST_UPDATED_TIME,
    METADATA_LAST_TRIGGERING_EVENT_NAME,
    APPLICATION_RECEIVED_TIME,
    SOURCE_CODE
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    cast(concat(OPENED_TIME, '+00:00') AS TIMESTAMP(6) WITH TIME ZONE) AS OPENED_TIME,
    CLOSED_DATE,
    OPENED_CHANNEL_COUNTRY,
    OPENED_CHANNEL_BRAND,
    SELLING_CHANNEL,
    CREDIT_ACCOUNT_ID,
    CREDIT_APPLICATION_ID,
    STATUS,
    METADATA_CREATED_TIME,
    METADATA_LAST_UPDATED_TIME,
    METADATA_LAST_TRIGGERING_EVENT_NAME,
    APPLICATION_RECEIVED_TIME,
    SOURCE_CODE
FROM CREDIT_ACCOUNT_LDG_TEMP;


DELETE FROM {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_ACCOUNT_BANK_CARD_FACT
WHERE
    CARD_ID IN (SELECT CARD_ID FROM CREDIT_ACCOUNT_BANK_CARD_LDG_TEMP);

-- Insert new event data
INSERT INTO {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_ACCOUNT_BANK_CARD_FACT (
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP,
    CREDIT_ACCOUNT_ID,
    CARD_ID,
    ADDED_DATE,
    CLOSED_DATE,
    CARD_MEMBER_ROLE,
    CARD_EXPIRATION_MONTH,
    CARD_EXPIRATION_YEAR,
    CARD_PAYMENT_ID,
    CARD_STATUS,
    NAME_ON_CARD_VALUE,
    NAME_ON_CARD_AUTHORITY,
    NAME_ON_CARD_STRATEGY,
    NAME_ON_CARD_DATA_CLASSIFICATION,
    REPLACED_CARD_ID,
    ACTIVATED_DATE,
    TENDER_SERVICE_ID,
    TENDER_SERVICE_PRODUCT_TYPE,
    CITY,
    STATE,
    COARSE_POSTAL_CODE,
    CARD_ADDED_REASON,
    CARD_CLOSED_REASON
)
SELECT
    current_timestamp(0) AS DW_SYS_LOAD_TMSTP,
    current_timestamp(0) AS DW_SYS_UPDT_TMSTP,
    CREDIT_ACCOUNT_ID,
    CARD_ID,
    ADDED_DATE,
    CLOSED_DATE,
    CARD_MEMBER_ROLE,
    CARD_EXPIRATION_MONTH,
    CARD_EXPIRATION_YEAR,
    CARD_PAYMENT_ID,
    CARD_STATUS,
    NAME_ON_CARD_VALUE,
    NAME_ON_CARD_AUTHORITY,
    NAME_ON_CARD_STRATEGY,
    NAME_ON_CARD_DATA_CLASSIFICATION,
    REPLACED_CARD_ID,
    ACTIVATED_DATE,
    TENDER_SERVICE_ID,
    TENDER_SERVICE_PRODUCT_TYPE,
    CITY,
    STATE,
    COARSE_POSTAL_CODE,
    CARD_ADDED_REASON,
    CARD_CLOSED_REASON
FROM CREDIT_ACCOUNT_BANK_CARD_LDG_TEMP;

-- delete records from stg tables
DELETE FROM {db_env}_NAP_CREDIT_STG.CREDIT_ACCOUNT_LDG;
DELETE FROM {db_env}_NAP_CREDIT_STG.CREDIT_ACCOUNT_BANK_CARD_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
