-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app06788; DAG_ID=credit_survey_requested_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

CREATE MULTISET VOLATILE TABLE CREDIT_SURVEY_REQUESTED_LDG_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_CREDIT_STG.CREDIT_SURVEY_REQUESTED_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY CREDIT_CUSTOMER_SUPPORT_CONTACTED_ID ORDER BY EVENT_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (CREDIT_CUSTOMER_SUPPORT_CONTACTED_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- Delete duplicates
DELETE FROM {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_SURVEY_REQUESTED_FACT
WHERE
    CREDIT_CUSTOMER_SUPPORT_CONTACTED_ID IN
    (SELECT CREDIT_CUSTOMER_SUPPORT_CONTACTED_ID FROM CREDIT_SURVEY_REQUESTED_LDG_TEMP);

INSERT INTO {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_SURVEY_REQUESTED_FACT (
    EVENT_TIME,
    EVENT_DATE,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    CREDIT_ACCOUNT_ID,
    CREDIT_CUSTOMER_SUPPORT_CONTACTED_ID,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT
    cast(concat(EVENT_TIME, '+00:00') AS TIMESTAMP(6) WITH TIME ZONE) AS EVENT_TIME,
    cast(cast(EVENT_TIME AS TIMESTAMP(6)) AS DATE) AS EVENT_DATE,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    CREDIT_ACCOUNT_ID,
    CREDIT_CUSTOMER_SUPPORT_CONTACTED_ID,
    current_timestamp AS DW_SYS_LOAD_TMSTP,
    current_timestamp AS DW_SYS_UPDT_TMSTP
FROM CREDIT_SURVEY_REQUESTED_LDG_TEMP;

-- delete records from stg table
DELETE FROM {db_env}_NAP_CREDIT_STG.CREDIT_SURVEY_REQUESTED_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
