/*SET QUERY_BAND='AppName=NAP-Product-Demand-KPI;AppRelease=1;AppFreq=Daily;AppPhase=dim-lkup;AppSubArea=PRODUCT_SKU_LKUP_Load;' UPDATE FOR SESSION;*/
Begin Transaction ;
 /*.IF ERRORCODE <> 0 THEN .QUIT 1*/
TRUNCATE TABLE  {{params.gcp_project_id}}.{{params.dbenv}}_NAP_DIM.PRODUCT_SKU_LKUP; 
/*.IF ERRORCODE <> 0 THEN .QUIT 2*/
INSERT INTO
  {{params.gcp_project_id}}.{{params.dbenv}}_NAP_DIM.PRODUCT_SKU_LKUP 
  (
    rms_sku_num,
    epm_sku_num,
    channel_country,
    sku_short_desc,
    sku_desc,
    web_sku_num,
    brand_label_num,
    brand_label_display_name,
    rms_style_num,
    epm_style_num,
    partner_relationship_num,
    partner_relationship_type_code,
    web_style_num,
    style_desc,
    style_group_num,
    style_group_desc,
    epm_choice_num,
    supp_part_num,
    prmy_supp_num,
    manufacturer_num,
    sbclass_num,
    sbclass_desc,
    class_num,
    class_desc,
    dept_num,
    dept_desc,
    grp_num,
    grp_desc,
    div_num,
    div_desc,
    cmpy_num,
    cmpy_desc,
    color_num,
    color_desc,
    nord_display_color,
    nrf_size_code,
    size_1_num,
    size_1_desc,
    size_2_num,
    size_2_desc,
    supp_color,
    supp_size,
    brand_name,
    return_disposition_code,
    return_disposition_desc,
    selling_status_code,
    selling_status_desc,
    live_date,
    drop_ship_eligible_ind,
    sku_type_code,
    sku_type_desc,
    pack_orderable_code,
    pack_orderable_desc,
    pack_sellable_code,
    pack_sellable_desc,
    pack_simple_code,
    pack_simple_desc,
    display_seq_1,
    display_seq_2,
    hazardous_material_class_desc,
    hazardous_material_class_code,
    fulfillment_type_code,
    selling_channel_eligibility_list,
    smart_sample_ind,
    gwp_ind,
    msrp_amt,
    msrp_currency_code,
    npg_ind,
    order_quantity_multiple,
    fp_forecast_eligible_ind,
    fp_item_planning_eligible_ind,
    fp_replenishment_eligible_ind,
    op_forecast_eligible_ind,
    op_item_planning_eligible_ind,
    op_replenishment_eligible_ind,
    size_range_desc,
    size_sequence_num,
    size_range_code,
    country_count,
    dw_batch_id,
    dw_batch_date,
    dw_sys_load_tmstp)
SELECT
  sku.rms_sku_num,
  sku.epm_sku_num,
  sku.channel_country,
  sku.sku_short_desc,
  sku.sku_desc,
  sku.web_sku_num,
  sku.brand_label_num,
  sku.brand_label_display_name,
  sku.rms_style_num,
  sku.epm_style_num,
  sku.partner_relationship_num,
  sku.partner_relationship_type_code,
  sku.web_style_num,
  sku.style_desc,
  sku.style_group_num,
  sku.style_group_desc,
  sku.epm_choice_num,
  sku.supp_part_num,
  sku.prmy_supp_num,
  sku.manufacturer_num,
  sku.sbclass_num,
  sku.sbclass_desc,
  sku.class_num,
  sku.class_desc,
  sku.dept_num,
  sku.dept_long_desc AS dept_desc,
  sku.grp_num,
  sku.grp_long_desc AS grp_desc,
  sku.div_num,
  sku.div_long_desc AS div_desc,
  sku.cmpy_num,
  sku.cmpy_desc,
  sku.color_num,
  colr.color_desc,
  sku.nord_display_color,
  sku.nrf_size_code,
  sku.size_1_num,
  sku.size_1_desc,
  sku.size_2_num,
  sku.size_2_desc,
  sku.supp_color,
  sku.supp_size,
  sku.brand_name,
  sku.return_disposition_code,
  sku.return_disposition_desc,
  sku.selling_status_code,
  sku.selling_status_desc,
  sku.live_date,
  sku.drop_ship_eligible_ind,
  sku.sku_type_code,
  sku.sku_type_desc,
  sku.pack_orderable_code,
  sku.pack_orderable_desc,
  sku.pack_sellable_code,
  sku.pack_sellable_desc,
  sku.pack_simple_code,
  sku.pack_simple_desc,
  sku.display_seq_1,
  sku.display_seq_2,
  sku.hazardous_material_class_desc,
  sku.hazardous_material_class_code,
  sku.fulfillment_type_code,
  sku.selling_channel_eligibility_list,
  sku.smart_sample_ind,
  sku.gwp_ind,
  sku.msrp_amt,
  sku.msrp_currency_code,
  sku.npg_ind,
  sku.order_quantity_multiple,
  sku.fp_forecast_eligible_ind,
  sku.fp_item_planning_eligible_ind,
  sku.fp_replenishment_eligible_ind,
  sku.op_forecast_eligible_ind,
  sku.op_item_planning_eligible_ind,
  sku.op_replenishment_eligible_ind,
  sku.size_range_desc,
  sku.size_sequence_num,
  sku.size_range_code,
  COUNT(*) OVER (PARTITION BY sku.rms_sku_num) AS country_count,
  
  --In the CASE expressions below, we are checking to see if the EPM hierarchy extract that underlies
  --the PRODUCT_HIERARCHY_DIM_VW view has a higher batch_id/batch_date than the Style record and if this has
  --resulted in a different sbclass_desc or class_desc value then we return THAT batch_id.  We do
  --this since the Merch team extracts key off the batch_id to determine if a change has occurred to
  --the record.
  sku.dw_batch_id,
  sku.dw_batch_date,
  sku.dw_sys_load_tmstp
FROM
  {{params.gcp_project_id}}.{{params.dbenv}}_NAP_BASE_VWS.PRODUCT_SKU_DIM AS sku
LEFT OUTER JOIN
  {{params.gcp_project_id}}.{{params.dbenv}}_NAP_BASE_VWS.PRODUCT_COLOR_DIM_VW AS colr
ON
  LOWER(colr.color_num) = LOWER(sku.color_num) ; 
  /*.IF ERRORCODE <> 0 THEN .QUIT 3*/
  /*.IF ERRORCODE <> 0 THEN .QUIT 4*/
   Commit Transaction ;
  --COLLECT STATS ON {{params.gcp_project_id}}.{{params.dbenv}}_NAP_DIM.PRODUCT_SKU_LKUP;
 