--LOAD TODAY'S DATA IN CPP_EBR_TRAN_FACT USING TWO TEMP TABLES

--FIRST STEP INGEST THE DATA IN TEMP 1 TABLE
CREATE VOLATILE MULTISET TABLE RETAIL_TRAN_FCT_TEMP_1 AS (
SELECT 
T1.ACP_ID AS PK,
LINE_NET_USD_AMT,
(CASE WHEN LINE_NET_USD_AMT > 0
      THEN COALESCE(TRAN_DATE,BUSINESS_DAY_DATE)
      ELSE NULL  END) AS TRAN_DATE
FROM {teradata_env}_NAP_BASE_VWS.ANALYTICAL_CUSTOMER T1
JOIN {teradata_env}_NAP_VWS.RETAIL_TRAN_DETAIL_FACT_VW T2
ON T1.ACP_ID=T2.ACP_ID 
WHERE  
     (T2.TRAN_DATE BETWEEN ADD_MONTHS(CURRENT_DATE ,-1) AND (CURRENT_DATE-1) ) 
     AND (T2.BUSINESS_DAY_DATE >= ADD_MONTHS(CURRENT_DATE ,-1)) 
     AND T1.MKTG_PROFILE_TYPE='Y' AND T1.RECORD_ACTIVE_IND='Y'
)WITH DATA
PRIMARY INDEX(PK)
ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS COLUMN(PK) ON RETAIL_TRAN_FCT_TEMP_1;

--SECOND STEP IS CALCULATE THE LATEST PURCHASE DATE BY ACP_ID  
CREATE VOLATILE MULTISET TABLE RETAIL_TRAN_FCT_TEMP_2 AS (
SELECT 
PK,
 MAX(TRAN_DATE) AS LAST_PURCHASE_DATE 
FROM RETAIL_TRAN_FCT_TEMP_1 RTDF
GROUP BY PK
) WITH DATA
PRIMARY INDEX(PK)
ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS COLUMN(PK) ON RETAIL_TRAN_FCT_TEMP_2;

--REFRESH ENTIRE CPP_EBR_TRAN_DELTA_LDG TABLE WITH TODAY'S SNAPSHOT
DELETE FROM {teradata_env}_NAP_STG.CPP_EBR_TRAN_DELTA_LDG ALL;

INSERT INTO {teradata_env}_NAP_STG.CPP_EBR_TRAN_DELTA_LDG
SELECT
    PK,
   LAST_PURCHASE_DATE,
	CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM RETAIL_TRAN_FCT_TEMP_2;
