--Reading Data from landing S3 bucket
CREATE TEMPORARY TABLE temp_ent_chase_pti_generic USING CSV
OPTIONS (
    path "s3://{dp495_s3_bucket}/csv/ent_chase_pti_generic/", header "true"
);

--Writing data to new S3 Path
INSERT INTO TABLE ent_chase_pti_generic PARTITION (year, month)
SELECT DISTINCT
    cast(advice_date AS int) AS advice_date,
    cast(auth_timestamp AS int) AS auth_timestamp,
    cast(settlement_date AS int) AS settlement_date,
    cast(transaction_mcc AS int) AS transaction_mcc,
    cast(store_forward_orig_timestamp AS int) AS store_forward_orig_timestamp,
    store_and_forward_ind,
    pos_data_code,
    cast(entry_data_source AS int) AS entry_data_source,
    card_level_results,
    cast(cash_back_amount AS int) AS cash_back_amount,
    cast(pos_misc_id AS int) AS pos_misc_id,
    cast(d3_record_sequence_num AS int) AS d3_record_sequence_num,
    d3_record_id,
    filler2,
    card_attribute_ind,
    cast(pan_encryption_method AS int) AS pan_encryption_method,
    regulatory_fraud_prev_ind,
    cast(regulatory_country_code AS int) AS regulatory_country_code,
    cast(regulatory_bin_compare_length AS int) AS regulatory_bin_compare_length,
    regulatory_exempt_ind,
    cast(ecommerce_transaction_ind AS int) AS ecommerce_transaction_ind,
    auth_agent_id_code,
    cast(transaction_disposition AS int) AS transaction_disposition,
    pos_reversal_reason_code,
    cast(currency_code AS int) AS currency_code,
    cardholder_verification_resp,
    cardholder_verification_flag,
    cti_flag,
    cps_industry,
    cast(duration AS int) AS duration,
    prepaid_ind,
    cast(total_authorized_amount AS int) AS total_authorized_amount,
    cast(auth_amount AS int) AS auth_amount,
    auth_source,
    validation_code,
    qualification_data,
    auth_characteristic_ind,
    auth_response_code,
    downgrade_reason,
    avs_requested_ind,
    avs_response_code,
    server_name,
    cast(server_error_code AS int) AS server_error_code,
    communications_type,
    cast(d2_record_sequence_num AS int) AS d2_record_sequence_num,
    d2_record_id,
    filler1,
    pin_usage_ind,
    cast(auth_time AS int) AS auth_time,
    cast(auth_date AS int) AS auth_date,
    prepaid_balance_requested_flag,
    partial_auth_request_flag,
    pan_encryption_account_status,
    guaranteed_unique_identifier,
    business_date,
    partial_auth_flag,
    partial_shipment_ind,
    cast(track_condition_code AS int) AS track_condition_code,
    cast(system_trace_audit_num AS int) AS system_trace_audit_num,
    cast(transaction_processing_code AS int) AS transaction_processing_code,
    settle_flag,
    discount_flag,
    ack_received_ind,
    transaction_void_flag,
    cardholder_id_method,
    auth_pos_entry_mode,
    pos_terminal_capability,
    pin_entry_capability,
    cast(expiration_date AS int) AS expiration_date,
    auth_num,
    cast(transaction_amount AS int) AS transaction_amount,
    transaction_time,
    cast(transaction_date AS date) AS transaction_date,
    n_token_cardholder_account_num,
    card_type,
    cast(transaction_code AS int) AS transaction_code,
    cast(record_type AS int) AS record_type,
    cast(transaction_sequence_num AS int) AS transaction_sequence_num,
    cast(d1_record_sequence_num AS int) AS d1_record_sequence_num,
    d1_record_id,
    cast(batch_time AS int) AS batch_time,
    cast(batch_date AS int) AS batch_date,
    cast(upload_num AS int) AS upload_num,
    cast(batch_num AS int) AS batch_num,
    terminal_number,
    merchant_type,
    cast(bank_merchant_number AS int) AS bank_merchant_number,
    cast(merchant_number AS bigint) AS merchant_number,
    file_name,
    cast(load_date AS date) AS load_date,
    cast(pti_txid AS decimal (22, 0)) AS pti_txid,
    pti_settlement_id,
    card_subtype,
    cardtype,
    cast(token_err_cd AS int) AS token_err_cd,
    em_data,
    d5_14data,
    d5_07data,
    d5_01data,
    d4_data,
    filler3,
    current_timestamp() AS last_updated_time,
    date_format(transaction_date, "yyyy") AS year,
    date_format(transaction_date, "MM") AS month
FROM temp_ent_chase_pti_generic;
