BEGIN
DECLARE _ERROR_CODE INT64;
DECLARE _ERROR_MESSAGE STRING;
/*SET QUERY_BAND = 'App_ID=APP08047;
DAG_ID=mta_ssa_cost_11521_ACE_ENG;
---     Task_Name=mta_ssa_cost_agg_vw;'*/
BEGIN
SET _ERROR_CODE  =  0;
CREATE OR REPLACE VIEW `{{params.gcp_project_id}}`.{{params.mta_t2_schema}}.mta_ssa_cost_agg_vw AS SELECT activity_date_pacific,
 year_num,
 month_short_desc,
 week_454_num,
 week_of_fyr,
 week_num,
 week_desc,
 month_num,
 month_desc,
 order_channel,
 channelcountry,
 arrived_channel,
 marketing_type,
 finance_rollup,
 finance_detail,
 funnel_type,
 nmn_flag,
 SUM(attributed_demand) AS attributed_demand,
 SUM(attributed_units) AS attributed_units,
 SUM(attributed_orders) AS attributed_orders,
 SUM(attributed_pred_net) AS attributed_pred_net,
 SUM(sessions) AS sessions,
 SUM(bounced_sessions) AS bounced_sessions,
 SUM(session_orders) AS session_orders,
 SUM(session_demand) AS session_demand,
 SUM(cost) AS cost,
 SUM(ly_attributed_demand) AS ly_attributed_demand,
 SUM(ly_attributed_units) AS ly_attributed_units,
 SUM(ly_attributed_orders) AS ly_attributed_orders,
 SUM(ly_attributed_pred_net) AS ly_attributed_pred_net,
 SUM(ly_sessions) AS ly_sessions,
 SUM(ly_bounced_sessions) AS ly_bounced_sessions,
 SUM(ly_session_orders) AS ly_session_orders,
 SUM(ly_session_demand) AS ly_session_demand,
 SUM(ly_cost) AS ly_cost,
 dw_sys_load_tmstp
FROM (SELECT d.day_date AS activity_date_pacific,
    d.year_num,
    d.month_short_desc,
    d.week_454_num,
    d.week_of_fyr,
    d.week_num,
    d.week_desc,
    d.month_num,
    d.month_desc,
    mpcs_ty.order_channel,
    mpcs_ty.channelcountry,
    mpcs_ty.arrived_channel,
    mpcs_ty.marketing_type,
    mpcs_ty.finance_rollup,
    mpcs_ty.finance_detail,
    mpcs_ty.funnel_type,
    mpcs_ty.nmn_flag,
    mpcs_ty.attributed_demand,
    mpcs_ty.attributed_units,
    mpcs_ty.attributed_orders,
    mpcs_ty.attributed_pred_net,
    mpcs_ty.sessions,
    mpcs_ty.bounced_sessions,
    mpcs_ty.session_orders,
    mpcs_ty.session_demand,
    mpcs_ty.cost,
    0 AS ly_attributed_demand,
    0 AS ly_attributed_units,
    0 AS ly_attributed_orders,
    0 AS ly_attributed_pred_net,
    0 AS ly_sessions,
    0 AS ly_bounced_sessions,
    0 AS ly_session_orders,
    0 AS ly_session_demand,
    0 AS ly_cost,
    mpcs_ty.dw_sys_load_tmstp
   FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.day_cal AS d
    INNER JOIN `{{params.gcp_project_id}}`.{{params.mta_t2_schema}}.mta_ssa_cost_agg AS mpcs_ty ON d.day_date = mpcs_ty.activity_date_pacific
   UNION ALL
   SELECT d0.day_date AS activity_date_pacific,
    d0.year_num,
    d0.month_short_desc,
    d0.week_454_num,
    d0.week_of_fyr,
    d0.week_num,
    d0.week_desc,
    d0.month_num,
    d0.month_desc,
    mpcs_ly.order_channel,
    mpcs_ly.channelcountry,
    mpcs_ly.arrived_channel,
    mpcs_ly.marketing_type,
    mpcs_ly.finance_rollup,
    mpcs_ly.finance_detail,
    mpcs_ly.funnel_type,
    mpcs_ly.nmn_flag,
    0 AS ty_attributed_demand,
    0 AS ty_attributed_units,
    0 AS ty_attributed_orders,
    0 AS ty_attributed_pred_net,
    0 AS ty_sessions,
    0 AS ty_bounced_sessions,
    0 AS ty_session_orders,
    0 AS ty_session_demand,
    0 AS ty_cost,
    mpcs_ly.attributed_demand AS ly_attributed_demand,
    mpcs_ly.attributed_units AS ly_attributed_units,
    mpcs_ly.attributed_orders AS ly_attributed_orders,
    mpcs_ly.attributed_pred_net AS ly_attributed_pred_net,
    mpcs_ly.sessions AS ly_sessions,
    mpcs_ly.bounced_sessions AS ly_bounced_sessions,
    mpcs_ly.session_orders AS ly_session_orders,
    mpcs_ly.session_demand AS ly_session_demand,
    mpcs_ly.cost AS ly_cost,
    mpcs_ly.dw_sys_load_tmstp
   FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.day_cal AS d0
    INNER JOIN `{{params.gcp_project_id}}`.{{params.mta_t2_schema}}.mta_ssa_cost_agg AS mpcs_ly ON d0.last_year_day_date_realigned = mpcs_ly.activity_date_pacific
     ) AS mpcs
WHERE activity_date_pacific <= (SELECT MAX(activity_date_pacific)
   FROM `{{params.gcp_project_id}}`.{{params.mta_t2_schema}}.mta_ssa_cost_agg)
GROUP BY activity_date_pacific,
 year_num,
 month_short_desc,
 week_454_num,
 week_of_fyr,
 week_num,
 week_desc,
 month_num,
 month_desc,
 order_channel,
 channelcountry,
 arrived_channel,
 marketing_type,
 finance_rollup,
 finance_detail,
 funnel_type,
 nmn_flag,
 dw_sys_load_tmstp;
EXCEPTION WHEN ERROR THEN
SET _ERROR_CODE  =  1;
SET _ERROR_MESSAGE  =  @@error.message;
END;
/*SET QUERY_BAND = NONE FOR SESSION;*/
END;