SET QUERY_BAND = '
App_ID=app07420;
DAG_ID=fraud_worldpay_bin;
Task_Name=td_dim_to_td_stg_job;'
-- noqa: disable=all
FOR SESSION VOLATILE;
-- noqa: enable=all

CREATE TEMPORARY VIEW TMP AS
SELECT * FROM WORLDPAY_BIN_DIM;

CREATE OR REPLACE TEMPORARY VIEW WORLDPAY_BIN_DIM_TMP AS
SELECT * FROM TMP
WHERE RECENTLY_UPDATED = 'Y';

CREATE OR REPLACE TEMPORARY VIEW BIN_SIX_TO_AGGREGATIONS AS
SELECT
    BIN_SIX,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(CARD_NETWORK))), ',') AS CARD_NETWORKS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(DEBIT_FLAG))), ',') AS DEBIT_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(CHECKCARD_FLAG))), ',') AS CHECKCARD_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(CREDIT_CARD_FLAG))), ',') AS CREDIT_CARD_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(CARDHOLDER_FUNDS_TRANSFER_FLAG))), ',') AS CARDHOLDER_FUNDS_TRANSFER_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(NETWORK_REGULATION_VALUE))), ',') AS NETWORK_REGULATION_VALUES,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(INTERNATIONAL_FLAG))), ',') AS INTERNATIONAL_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(COMMERCIAL_BUSINESS_FLAG))), ',') AS COMMERCIAL_BUSINESS_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(FLEET_CARD_FLAG))), ',') AS FLEET_CARD_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(PREPAID_CARD_FLAG))), ',') AS PREPAID_CARD_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(RELOAD_FLAG))), ',') AS RELOAD_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(HSA_FLAG))), ',') AS HSA_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(FSA_FLAG))), ',') AS FSA_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(EBT_FLAG))), ',') AS EBT_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(WIC_FLAG))), ',') AS WIC_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(PINLESS_POS_FLAG))), ',') AS PINLESS_POS_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(PINLESS_BILL_PAY_FLAG))), ',') AS PINLESS_BILL_PAY_FLAGS,
    ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(TOKEN_FLAG))), ',') AS TOKEN_FLAGS
FROM WORLDPAY_BIN_DIM_TMP
GROUP BY BIN_SIX;

CREATE OR REPLACE TEMPORARY VIEW BIN_SIX_TO_BASE_CARD_NETWORKS AS
WITH
L AS (
    SELECT
        BIN_SIX,
        CAST(MIN(CAST(BIN AS BIGINT)) AS STRING) AS BIN
    FROM WORLDPAY_BIN_DIM_TMP
    GROUP BY BIN_SIX
),

R AS (
    SELECT
        BIN,
        ARRAY_JOIN(SORT_ARRAY(ARRAY_DISTINCT(COLLECT_LIST(CARD_NETWORK))), ',') AS BASE_CARD_NETWORKS
    FROM WORLDPAY_BIN_DIM_TMP
    GROUP BY BIN
)

SELECT
    L.BIN_SIX,
    R.BASE_CARD_NETWORKS
FROM L
INNER JOIN R
    ON L.BIN = R.BIN;

CREATE OR REPLACE TEMPORARY VIEW WORLDPAY_BIN_ROLLUP_TMP AS
SELECT
    L.BIN_SIX,
    R.BASE_CARD_NETWORKS,
    L.CARD_NETWORKS,
    L.DEBIT_FLAGS,
    L.CHECKCARD_FLAGS,
    L.CREDIT_CARD_FLAGS,
    L.COMMERCIAL_BUSINESS_FLAGS,
    L.FLEET_CARD_FLAGS,
    L.PREPAID_CARD_FLAGS,
    L.HSA_FLAGS,
    L.PINLESS_BILL_PAY_FLAGS,
    L.EBT_FLAGS,
    L.WIC_FLAGS,
    L.INTERNATIONAL_FLAGS,
    L.NETWORK_REGULATION_VALUES,
    L.PINLESS_POS_FLAGS,
    L.TOKEN_FLAGS,
    L.RELOAD_FLAGS,
    L.CARDHOLDER_FUNDS_TRANSFER_FLAGS
FROM BIN_SIX_TO_AGGREGATIONS AS L
INNER JOIN BIN_SIX_TO_BASE_CARD_NETWORKS AS R
    ON L.BIN_SIX = R.BIN_SIX;

INSERT OVERWRITE TABLE WORLDPAY_BIN_ROLLUP_LDG
SELECT
    BIN_SIX,
    BASE_CARD_NETWORKS,
    CARD_NETWORKS,
    DEBIT_FLAGS,
    CHECKCARD_FLAGS,
    CREDIT_CARD_FLAGS,
    COMMERCIAL_BUSINESS_FLAGS,
    FLEET_CARD_FLAGS,
    PREPAID_CARD_FLAGS,
    HSA_FLAGS,
    PINLESS_BILL_PAY_FLAGS,
    EBT_FLAGS,
    WIC_FLAGS,
    INTERNATIONAL_FLAGS,
    NETWORK_REGULATION_VALUES,
    PINLESS_POS_FLAGS,
    TOKEN_FLAGS,
    RELOAD_FLAGS,
    CARDHOLDER_FUNDS_TRANSFER_FLAGS
FROM WORLDPAY_BIN_ROLLUP_TMP;
