SET QUERY_BAND = '
App_ID=app02560;
LoginUser={td_login_user};
Job_Name=sco_order_line_routing_assignment;
Data_Plane=Customer;
Team_Email=TECH_NAP_SUPPLYCHAIN_OUTBOUND@nordstrom.com;
PagerDuty=NAP_Supply_Chain_Outbound;
Conn_Type=JDBC;'
FOR SESSION VOLATILE;

-- Reading Data from  Source Kafka Topic Name = inventory-routing-decision-lifecycle-analytical-avro-value
-- Read, explode arrays, flatten objects, dedup and load into teradata stage table

--unnest routing decision details
create or replace temporary view temp_routing_decision_lifecycle_avro as
select ordernumber,
    orderlineid,
    calltype,
    attributes,
    createdTime,
    lastUpdatedTime,
    explode_outer(routingdecisiondetails) as rdd
  from routing_decision_lifecycle_avro
;

--dedup by ordernumber, orderlineid and rdd.hopCorrelationId
create or replace temporary view temp_routing_decision_lifecycle_dedup as
select orderNumber,
    orderLineId,
    callType,
    attributes,
    createdTime,
    lastUpdatedTime,
    rdd
    from (
          select *, row_number() over(partition by orderNumber, orderLineId, rdd.hopCorrelationId order by lastUpdatedTime desc) as rn
            from temp_routing_decision_lifecycle_avro
          where rdd.hopCorrelationId is not null
        ) t
    where rn = 1
;
--unnest routing decisions
create or replace temporary view temp_routing_decision_lifecycle_rdd as
select
    orderNumber,
    orderLineId,
    callType,
    case when array_contains(attributes, 'IS_ROUTING_BEAUTY') then 'Y' else 'N' end as isBeautyItem,
    case when array_contains(attributes, 'IS_ROUTING_SHIP_ALONE') then 'Y' else 'N' end as isShipAlone,
    createdTime,
    lastUpdatedTime,
    rdd.eventTime as eventTime,
    rdd.hopCorrelationId as hopCorrelationId,

    rdd.assignedNode.id as assignedNodeId,
    rdd.assignedNode.quantity as assignedNodeQuantity,
    case when rdd.assignedNode.isDropShipNode then 'Y' else 'N' end as assignedNodeIsDropShipNode,
    round(cast(rdd.assignedNode.properties.firstFillScore as decimal(32, 10)), 2) as assignedNodeFirstFillScore,
    case when rdd.assignedNode.isOnlyNode then 'Y' else 'N' end as assignedNodeIsOnlyNode,
    cast(rdd.assignedNode.dynamicProperties.laborCost.units + cast(rdd.assignedNode.dynamicProperties.laborCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as assignedNodeLaborCost,
    rdd.assignedNode.dynamicProperties.laborCost.currencyCode as currencyCode,
    cast(rdd.assignedNode.dynamicProperties.overloadedPenalty.units + cast(rdd.assignedNode.dynamicProperties.overloadedPenalty.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as assignedNodeOverloadedPenalty,
    cast(rdd.assignedNode.dynamicProperties.adjustmentPenalty.units + cast(rdd.assignedNode.dynamicProperties.adjustmentPenalty.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as assignedNodeAdjustmentPenalty,
    rdd.assignedNode.dynamicProperties.releaseToShipHours as assignedNodeReleaseToShipHours,
    rdd.assignedNode.dynamicProperties.plannedCapacity as assignedNodePlannedCapacity,
    rdd.assignedNode.dynamicProperties.queueLength as assignedNodeQueueLength,

    rdd.dynamicAssignmentProperties.lineItemGroupId as lineItemGroupId,
    cast(rdd.dynamicAssignmentProperties.predictedCost.units + cast(rdd.dynamicAssignmentProperties.predictedCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedCost,
    rdd.dynamicAssignmentProperties.nodeAssignmentProperties.overloadedBy as overloadedBy,
    cast(rdd.dynamicAssignmentProperties.nodeAssignmentProperties.predictedAdjustmentCost.units + cast(rdd.dynamicAssignmentProperties.nodeAssignmentProperties.predictedAdjustmentCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedAdjustmentCost,
    cast(rdd.dynamicAssignmentProperties.nodeAssignmentProperties.predictedOverloadedPenaltyCost.units + cast(rdd.dynamicAssignmentProperties.nodeAssignmentProperties.predictedOverloadedPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedOverloadedPenaltyCost,
    cast(rdd.dynamicAssignmentProperties.nodeAssignmentProperties.predictedDropShipPenaltyCost.units + cast(rdd.dynamicAssignmentProperties.nodeAssignmentProperties.predictedDropShipPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedDropShipPenaltyCost,
    rdd.dynamicAssignmentProperties.nodeCapabilityAssignmentProperties.capability.levelOfService as predictedLevelOfService,
    rdd.dynamicAssignmentProperties.nodeCapabilityAssignmentProperties.capability.expectedShippingDurationHours as expectedShippingDurationHours,
    nvl(nullif(rdd.dynamicAssignmentProperties.nodeCapabilityAssignmentProperties.capability.shippingZone, ''), 0) as shippingZone,
    rdd.dynamicAssignmentProperties.nodeCapabilityAssignmentProperties.predictedSLAHours as predictedSLAHours,
    cast(rdd.dynamicAssignmentProperties.nodeCapabilityAssignmentProperties.predictedShippingCost.units + cast(rdd.dynamicAssignmentProperties.nodeCapabilityAssignmentProperties.predictedShippingCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedShippingCost,
    rdd.dynamicAssignmentProperties.hoursLateBy as hoursLateBy,
    cast(rdd.dynamicAssignmentProperties.predictedLaborCost.units + cast(rdd.dynamicAssignmentProperties.predictedLaborCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedLaborCost,
    cast(rdd.dynamicAssignmentProperties.predictedMissedSLAPenaltyCost.units + cast(rdd.dynamicAssignmentProperties.predictedMissedSLAPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedMissedSLAPenaltyCost,

    rdd.executionType,
    rdd.executionPath as executionPath,
    rdd.dynamicAssignmentProperties.predictedArrivalDate as predictedArrivalDate,
	cast(rdd.dynamicAssignmentProperties.predictedMissedTargetReleaseToDeliveryPenaltyCost.units + cast(rdd.dynamicAssignmentProperties.predictedMissedTargetReleaseToDeliveryPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedMissedTargetReleaseToDeliveryPenaltyCost,
	cast(rdd.assignedNode.dynamicProperties.adjustmentCosts.value.units + cast(rdd.assignedNode.dynamicProperties.adjustmentCosts.value.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as adjustmentCostsAmt,
    case when rdd.assignedNode.dynamicProperties.adjustmentCosts.isNodeLevel then 'Y' else 'N' end as adjustmentCosts_isNodeLevel,
    cast(rdd.dynamicAssignmentProperties.predictedLineItemAdjustmentCost.units + cast(rdd.dynamicAssignmentProperties.predictedLineItemAdjustmentCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedLineItemAdjustmentCost,
    cast(rdd.assignedNode.dynamicProperties.expirationCosts.value.units + cast(rdd.assignedNode.dynamicProperties.expirationCosts.value.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as expirationCostsAmt,
    rdd.assignedNode.dynamicProperties.expirationCosts.thresholdInDays as expirationCosts_thresholdInDays,
    cast(rdd.dynamicAssignmentProperties.predictedExpirationPenaltyCost.units + cast(rdd.dynamicAssignmentProperties.predictedExpirationPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedExpirationPenaltyCost,
    rdd.assignedNode.dynamicProperties.predictedReleaseToShipModelVersion as predictedReleaseToShipModelVersion,
    array_join(rdd.experimentFlags, ',') as experimentFlags,
    array_join(rdd.availableNodes.id, ',') as availableNodeIds,
    cardinality(rdd.availableNodes) as availableNodeCount,
    aggregate(transform(rdd.availableNodes, x -> case when x.isDropShipNode then 1 else 0 end), 0, (acc, x) -> acc + x)  as availableDropshipNodesCount,
    rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.capability.predictedshippingdurationhoursmodelversion as predictedshippingdurationhoursmodelversion,

    rdd.assignedNode.dynamicPropertiesV2.releaseToShipHours as releaseToShipHoursV2,
    rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.capability.expectedShippingDurationHours as expectedShippingDurationHoursV2,
    rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.predictedSLAHours as predictedSLAHoursV2,
    rdd.dynamicAssignmentPropertiesV2.predictedArrivalTime as predictedArrivalDateV2,
    nvl(nullif(rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.capability.shippingZone, ''), 0) as shippingZoneV2,
    rdd.dynamicAssignmentPropertiesV2.lineItemGroupId as lineItemGroupIdV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedCostV2,
    rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.overloadedBy as overloadedByV2,
    cast(rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.predictedAdjustmentCost.units + cast(rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.predictedAdjustmentCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedAdjustmentCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.predictedOverloadedPenaltyCost.units + cast(rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.predictedOverloadedPenaltyCost.nanos as decimal(32,2)) / 1000000000.0 as decimal(32,2)) as predictedOverloadedPenaltyCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.predictedDropShipPenaltyCost.units + cast(rdd.dynamicAssignmentPropertiesV2.nodeAssignmentProperties.predictedDropShipPenaltyCost.nanos as decimal(32,2)) / 1000000000.0 as decimal(32,2)) as predictedDropShipPenaltyCostV2,
    rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.capability.levelOfService as predictedLevelOfServiceV2,
    cast(rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.capability.shippingCost.units + cast(rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.capability.shippingCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as shippingCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.predictedShippingCost.units + cast(rdd.dynamicAssignmentPropertiesV2.nodeCapabilityAssignmentProperties.predictedShippingCost.nanos as decimal(32,2)) / 1000000000.0 as decimal(32,2)) as predictedShippingCostV2,
    rdd.dynamicAssignmentPropertiesV2.hoursLateBy as hoursLateByV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedLaborCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedLaborCost.nanos as decimal(32,2)) / 1000000000.0 as decimal(32,2)) as predictedLaborCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedMissedSLAPenaltyCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedMissedSLAPenaltyCost.nanos as decimal(32,2)) / 1000000000.0 as decimal(32,2)) as predictedMissedSLAPenaltyCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedMissedTargetReleaseToDeliveryPenaltyCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedMissedTargetReleaseToDeliveryPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedMissedTargetReleaseToDeliveryPenaltyCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedLineItemAdjustmentCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedLineItemAdjustmentCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedLineItemAdjustmentCostV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedExpirationPenaltyCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedExpirationPenaltyCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as predictedExpirationPenaltyCostV2,
    cast(rdd.assignedNode.dynamicPropertiesV2.laborCost.units + cast(rdd.assignedNode.dynamicPropertiesV2.laborCost.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as assignedNodeLaborCostV2,
    rdd.assignedNode.dynamicPropertiesV2.laborCost.currencyCode as currencyCodeV2,
    cast(rdd.assignedNode.dynamicPropertiesV2.overloadedPenalty.units + cast(rdd.assignedNode.dynamicPropertiesV2.overloadedPenalty.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as assignedNodeOverloadedPenaltyV2,
    rdd.assignedNode.dynamicPropertiesV2.plannedCapacity as assignedNodePlannedCapacityV2,
    rdd.assignedNode.dynamicPropertiesV2.queueLength as assignedNodeQueueLengthV2,
    cast(rdd.assignedNode.dynamicPropertiesV2.adjustmentCosts.value.units + cast(rdd.assignedNode.dynamicPropertiesV2.adjustmentCosts.value.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as adjustmentCostsAmtV2,
    case when rdd.assignedNode.dynamicPropertiesV2.adjustmentCosts.isNodeLevel then 'Y' else 'N' end as adjustmentCosts_isNodeLevelV2,
    cast(rdd.assignedNode.dynamicPropertiesV2.expirationCosts.value.units + cast(rdd.assignedNode.dynamicPropertiesV2.expirationCosts.value.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as expirationCostsAmtV2,
    rdd.assignedNode.dynamicPropertiesV2.expirationCosts.thresholdInDays as expirationCosts_thresholdInDaysV2,
    rdd.assignedNode.dynamicPropertiesV2.predictedReleaseToShipModelVersion as predictedReleaseToShipModelVersionV2,
    cast(rdd.dynamicAssignmentPropertiesV2.predictedPriorityPenaltyCost.units + cast(rdd.dynamicAssignmentPropertiesV2.predictedPriorityPenaltyCost.nanos as decimal(32,2)) / 1000000000.0 as decimal(32,2)) as predictedPriorityPenaltyCostV2,
    rdd.solverType as solverType,
    explode_outer(rdd.decisions) as decisions
from temp_routing_decision_lifecycle_dedup
;

create or replace temporary view routing_decision_lifecycle_final as
select
    orderNumber,
    orderLineId,
    callType,
    isBeautyItem,
    isShipAlone,
    createdTime,
    lastUpdatedTime,
    eventTime,
    hopCorrelationId,
    assignedNodeId,
    assignedNodeQuantity,
    assignedNodeIsDropShipNode,
    assignedNodeFirstFillScore,
    assignedNodeIsOnlyNode,
    assignedNodeLaborCost,
    currencyCode,
    assignedNodeOverloadedPenalty,
    assignedNodeAdjustmentPenalty,
    assignedNodeReleaseToShipHours,
    assignedNodePlannedCapacity,
    assignedNodeQueueLength,
    lineItemGroupId,
    predictedCost,
    overloadedBy,
    predictedAdjustmentCost,
    predictedOverloadedPenaltyCost,
    predictedDropShipPenaltyCost,
    predictedLevelOfService,
    expectedShippingDurationHours,
    shippingZone,
    predictedSLAHours,
    predictedShippingCost,
    hoursLateBy,
    predictedLaborCost,
    predictedMissedSLAPenaltyCost,
    executionType,
    executionPath,
    predictedArrivalDate,
    predictedMissedTargetReleaseToDeliveryPenaltyCost,
    adjustmentCostsAmt,
    adjustmentCosts_isNodeLevel,
    predictedLineItemAdjustmentCost,
    expirationCostsAmt,
    expirationCosts_thresholdInDays,
    predictedExpirationPenaltyCost,
    predictedReleaseToShipModelVersion,
    experimentFlags,
    decisions.name as decisionName,
    decisions.decisionSequenceNumber as decisionSequenceNumber,
    max(decisions.decisionSequenceNumber) over( partition by orderNumber, orderLineId, hopCorrelationId) as maxDecisionSequenceNumber,
    array_join(transform(decisions.nodesRemaining, x -> cast(x.id as integer)), ',') as decisionNodesRemaining,
    array_join(transform(decisions.nodesRemoved, x -> cast(x.id as integer)), ',') as decisionNodesRemoved,
    cast(decisions.optimizeDecisionParameters.latePerHourPenalty.units + cast(decisions.optimizeDecisionParameters.latePerHourPenalty.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as latePerHourPenalty,
    cast(decisions.optimizeDecisionParameters.backOrderPenalty.units + cast(decisions.optimizeDecisionParameters.backOrderPenalty.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as backOrderPenalty,
    cast(decisions.optimizeDecisionParameters.dropShipPenalty.units + cast(decisions.optimizeDecisionParameters.dropShipPenalty.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as dropShipPenalty,
    decisions.optimizeDecisionParameters.shippingCostFactor as shippingCostFactor,
    decisions.optimizeDecisionParameters.fulfillCostFactor as fulfillCostFactor,
    decisions.optimizeDecisionParameters.latePenaltyFactor as latePenaltyFactor,
    decisions.optimizeDecisionParameters.adjustmentPenaltyFactor as adjustmentPenaltyFactor,
    cast(decisions.optimizeDecisionParameters.missedTargetReleaseToDeliveryPenaltyByHour.units + cast(decisions.optimizeDecisionParameters.missedTargetReleaseToDeliveryPenaltyByHour.nanos as decimal(32,2)) / 1000000000.0  as decimal(32,2)) as missedTargetReleaseToDeliveryPenaltyByHour,
    decisions.optimizeDecisionParameters.targetReleaseToDeliveryValueInDays as targetReleaseToDeliveryValueInDays,
    availableNodeIds,
    availableNodeCount,
    availableDropshipNodesCount,
    predictedshippingdurationhoursmodelversion,
    releaseToShipHoursV2,
    expectedShippingDurationHoursV2,
    predictedSLAHoursV2,
    predictedArrivalDateV2,
    shippingZoneV2,
    lineItemGroupIdV2,
    predictedCostV2,
    overloadedByV2,
    predictedAdjustmentCostV2,
    predictedOverloadedPenaltyCostV2,
    predictedDropShipPenaltyCostV2,
    predictedLevelOfServiceV2,
    shippingCostV2,
    predictedShippingCostV2,
    hoursLateByV2,
    predictedLaborCostV2,
    predictedMissedSLAPenaltyCostV2,
    predictedMissedTargetReleaseToDeliveryPenaltyCostV2,
    predictedLineItemAdjustmentCostV2,
    predictedExpirationPenaltyCostV2,
    assignedNodeLaborCostV2,
    currencyCodeV2,
    assignedNodeOverloadedPenaltyV2,
    assignedNodePlannedCapacityV2,
    assignedNodeQueueLengthV2,
    adjustmentCostsAmtV2,
    adjustmentCosts_isNodeLevelV2,
    expirationCostsAmtV2,
    expirationCosts_thresholdInDaysV2,
    predictedReleaseToShipModelVersionV2,
    predictedPriorityPenaltyCostV2,
    solverType
from temp_routing_decision_lifecycle_rdd
;

insert overwrite table order_line_routing_assignment_ldg
    (routingDecisionLdgNumber,
    orderNumber,
    orderLineId,
    rtngDcsnDtls_hopCorrelationId,
    callType,
    attributes_isBeautyItem,
    attributes_isShipAlone,
    createdTime,
    lastUpdatedTime,
    rtngDcsnDtls_eventTime,
    rtngDcsnDtls_assnmntNd_id,
    rtngDcsnDtls_assnmntNd_quantity,
    rtngDcsnDtls_assnmntNd_isDropShipNode,
    rtngDcsnDtls_assnmntNd_properties_firstFillScore,
    rtngDcsnDtls_assnmntNd_isOnlyNode,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_laborCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_laborCost_currencyCode,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_overloadedPenalty,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_adjustmentPenalty,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_releaseToShipHours,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_plannedCapacity,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_queueLength,
    rtngDcsnDtls_dnmcAssnmntPrprts_lineItemGroupId,
    rtngDcsnDtls_dnmcAssnmntPrprts_predictedCost,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_overloadedBy,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_predictedAdjustmentCost,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_predictedOverloadedPenaltyCost,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_predictedDropShipPenaltyCost,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_cpblt_levelOfService,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_cpblt_expectedShippingDurationHours,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_cpblt_shippingZone,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_predictedSLAHours,
    rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_predictedShippingCost,
    rtngDcsnDtls_dnmcAssnmntPrprts_hoursLateBy,
    rtngDcsnDtls_dnmcAssnmntPrprts_predictedLaborCost,
    rtngDcsnDtls_dnmcAssnmntPrprts_predictedMissedSLAPenaltyCost,
    rtngDcsnDtls_executionType,
    rtngDcsnDtls_executionPath,
    rtngDcsnDtls_dnmcAssnmntPrprts_predictedArrivalDate,
	rtngDcsnDtls_dnmcAssnmntPrprts_predictedMissedTargetReleaseToDeliveryPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_adjustmentCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_adjustmentCost_isNodeLevel,
    rtngDcsnDtls_dnmcAssnmntPrprts_predictedLineItemAdjustmentCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_expirationCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_expirationCost_thresholdInDays,
    rtngDcsnDtls_dnmcAssnmntPrprts_predictedExpirationPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprts_predictedReleaseToShipModelVersion,
    rtngDcsnDtls_experimentFlags,
    rtngDcsnDtls_dcsns_name,
    rtngDcsnDtls_dcsns_decisionSequenceNumber,
    rtngDcsnDtls_dcsns_nodesRemaining_ids,
    rtngDcsnDtls_dcsns_nodesRemoved_ids,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_latePerHourPenalty,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_backOrderPenalty,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_dropShipPenalty,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_shippingCostFactor,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_fulfillCostFactor,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_latePenaltyFactor,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_adjustmentPenaltyFactor,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_missedTargetReleaseToDeliveryPenaltyByHour,
    rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_targetReleaseToDeliveryValueInDays,
    rtngDcsnDtls_availableNodes_ids,
    rtngDcsnDtls_availableNodes_count,
    rtngDcsnDtls_availableNodes_isDropShipNode_count,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedShippingDurationHoursModelVersion,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_releaseToShipHours,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_expectedShippingDurationHours,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedSLAHours,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedArrivalDate,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_shippingZone,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_lineItemGroupId,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_overloadedBy,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedAdjustmentCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedOverloadedPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedDropShipPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedLevelOfService,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_shippingCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedShippingCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_hoursLateBy,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedLaborCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedMissedSLAPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedMissedTargetReleaseToDeliveryPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedLineItemAdjustmentCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedExpirationPenaltyCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodeLaborCost,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_currencyCode,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodeOverloadedPenalty,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodePlannedCapacity,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodeQueueLength,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_adjustmentCostsAmt,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_adjustmentCosts_isNodeLevel,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_expirationCostsAmt,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_expirationCosts_thresholdInDays,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedReleaseToShipModelVersion,
    rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedPriorityPenaltyCost,
    solverType,
    dw_sys_load_tmstp
    )
select
    row_number() over (order by orderNumber, orderLineId, hopCorrelationId) as routingDecisionLdgNumber,
    orderNumber,
    orderLineId,
    hopCorrelationId as rtngDcsnDtls_hopCorrelationId,
    callType,
    isBeautyItem as attributes_isBeautyItem,
    isShipAlone as attributes_isShipAlone,
    createdTime || '+00:00' as createdTime,
    lastUpdatedTime || '+00:00' as lastUpdatedTime,
    eventTime || '+00:00' as rtngDcsnDtls_eventTime,
    assignedNodeId as rtngDcsnDtls_assnmntNd_id,
    assignedNodeQuantity as rtngDcsnDtls_assnmntNd_quantity,
    assignedNodeIsDropShipNode as rtngDcsnDtls_assnmntNd_isDropShipNode,
    assignedNodeFirstFillScore as rtngDcsnDtls_assnmntNd_properties_firstFillScore,
    assignedNodeIsOnlyNode as rtngDcsnDtls_assnmntNd_isOnlyNode,
    assignedNodeLaborCost as rtngDcsnDtls_assnmntNd_dnmcPrprts_laborCost,
    currencyCode as rtngDcsnDtls_assnmntNd_dnmcPrprts_laborCost_currencyCode,
    assignedNodeOverloadedPenalty as rtngDcsnDtls_assnmntNd_dnmcPrprts_overloadedPenalty,
    assignedNodeAdjustmentPenalty as rtngDcsnDtls_assnmntNd_dnmcPrprts_adjustmentPenalty,
    assignedNodeReleaseToShipHours as rtngDcsnDtls_assnmntNd_dnmcPrprts_releaseToShipHours,
    assignedNodePlannedCapacity as rtngDcsnDtls_assnmntNd_dnmcPrprts_plannedCapacity,
    assignedNodeQueueLength as rtngDcsnDtls_assnmntNd_dnmcPrprts_queueLength,
    lineItemGroupId as rtngDcsnDtls_dnmcAssnmntPrprts_lineItemGroupId,
    predictedCost as rtngDcsnDtls_dnmcAssnmntPrprts_predictedCost,
    overloadedBy as rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_overloadedBy,
    predictedAdjustmentCost as rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_predictedAdjustmentCost,
    predictedOverloadedPenaltyCost as rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_predictedOverloadedPenaltyCost,
    predictedDropShipPenaltyCost as rtngDcsnDtls_dnmcAssnmntPrprts_ndAssnmntPrprts_predictedDropShipPenaltyCost,
    predictedLevelOfService as rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_cpblt_levelOfService,
    expectedShippingDurationHours as rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_cpblt_expectedShippingDurationHours,
    shippingZone as rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_cpblt_shippingZone,
    predictedSLAHours as rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_predictedSLAHours,
    predictedShippingCost as rtngDcsnDtls_dnmcAssnmntPrprts_ndCpbltAssnmntPrprts_predictedShippingCost,
    hoursLateBy as rtngDcsnDtls_dnmcAssnmntPrprts_hoursLateBy,
    predictedLaborCost as rtngDcsnDtls_dnmcAssnmntPrprts_predictedLaborCost,
    predictedMissedSLAPenaltyCost as rtngDcsnDtls_dnmcAssnmntPrprts_predictedMissedSLAPenaltyCost,
    executionType as rtngDcsnDtls_executionType,
    executionPath as rtngDcsnDtls_executionPath,
    predictedArrivalDate as rtngDcsnDtls_dnmcAssnmntPrprts_predictedArrivalDate,
    predictedMissedTargetReleaseToDeliveryPenaltyCost as rtngDcsnDtls_dnmcAssnmntPrprts_predictedMissedTargetReleaseToDeliveryPenaltyCost,
    adjustmentCostsAmt as rtngDcsnDtls_assnmntNd_dnmcPrprts_adjustmentCost,
    adjustmentCosts_isNodeLevel as rtngDcsnDtls_assnmntNd_dnmcPrprts_adjustmentCost_isNodeLevel,
    predictedLineItemAdjustmentCost as rtngDcsnDtls_dnmcAssnmntPrprts_predictedLineItemAdjustmentCost,
    expirationCostsAmt as rtngDcsnDtls_assnmntNd_dnmcPrprts_expirationCost,
    expirationCosts_thresholdInDays as rtngDcsnDtls_assnmntNd_dnmcPrprts_expirationCost_thresholdInDays,
    predictedExpirationPenaltyCost as rtngDcsnDtls_dnmcAssnmntPrprts_predictedExpirationPenaltyCost,
    predictedReleaseToShipModelVersion as rtngDcsnDtls_assnmntNd_dnmcPrprts_predictedReleaseToShipModelVersion,
    experimentFlags as rtngDcsnDtls_experimentFlags,
    decisionName as rtngDcsnDtls_dcsns_name,
    decisionSequenceNumber as rtngDcsnDtls_dcsns_decisionSequenceNumber,
    decisionNodesRemaining as rtngDcsnDtls_dcsns_nodesRemaining_ids,
    decisionNodesRemoved as rtngDcsnDtls_dcsns_nodesRemoved_ids,
    latePerHourPenalty as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_latePerHourPenalty,
    backOrderPenalty as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_backOrderPenalty,
    dropShipPenalty as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_dropShipPenalty,
    shippingCostFactor as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_shippingCostFactor,
    fulfillCostFactor as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_fulfillCostFactor,
    latePenaltyFactor as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_latePenaltyFactor,
    adjustmentPenaltyFactor as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_adjustmentPenaltyFactor,
    missedTargetReleaseToDeliveryPenaltyByHour as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_missedTargetReleaseToDeliveryPenaltyByHour,
    targetReleaseToDeliveryValueInDays as rtngDcsnDtls_dcsns_optmzDcsnsPrmtrs_targetReleaseToDeliveryValueInDays,
    availableNodeIds as rtngDcsnDtls_availableNodes_ids,
    availableNodeCount as rtngDcsnDtls_availableNodes_count,
    availableDropshipNodesCount as rtngDcsnDtls_availableNodes_isDropShipNode_count,
    predictedShippingDurationHoursModelVersion as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedShippingDurationHoursModelVersion,
    releaseToShipHoursV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_releaseToShipHours,
    expectedShippingDurationHoursV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_expectedShippingDurationHours,
    predictedSLAHoursV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedSLAHours,
    predictedArrivalDateV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedArrivalDate,
    shippingZoneV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_shippingZone,
    lineItemGroupIdV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_lineItemGroupId,
    predictedCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedCost,
    overloadedByV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_overloadedBy,
    predictedAdjustmentCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedAdjustmentCost,
    predictedOverloadedPenaltyCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedOverloadedPenaltyCost,
    predictedDropShipPenaltyCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedDropShipPenaltyCost,
    predictedLevelOfServiceV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedLevelOfService,
    shippingCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_shippingCost,
    predictedShippingCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedShippingCost,
    hoursLateByV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_hoursLateBy,
    predictedLaborCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedLaborCost,
    predictedMissedSLAPenaltyCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedMissedSLAPenaltyCost,
    predictedMissedTargetReleaseToDeliveryPenaltyCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedMissedTargetReleaseToDeliveryPenaltyCost,
    predictedLineItemAdjustmentCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedLineItemAdjustmentCost,
    predictedExpirationPenaltyCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedExpirationPenaltyCost,
    assignedNodeLaborCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodeLaborCost,
    currencyCodeV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_currencyCode,
    assignedNodeOverloadedPenaltyV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodeOverloadedPenalty,
    assignedNodePlannedCapacityV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodePlannedCapacity,
    assignedNodeQueueLengthV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_assignedNodeQueueLength,
    adjustmentCostsAmtV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_adjustmentCostsAmt,
    adjustmentCosts_isNodeLevelV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_adjustmentCosts_isNodeLevel,
    expirationCostsAmtV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_expirationCostsAmt,
    expirationCosts_thresholdInDaysV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_expirationCosts_thresholdInDays,
    predictedReleaseToShipModelVersionV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedReleaseToShipModelVersion,
    predictedPriorityPenaltyCostV2 as rtngDcsnDtls_assnmntNd_dnmcPrprtsV2_predictedPriorityPenaltyCost,
    solverType,
    now() as dw_sys_load_tmstp
from routing_decision_lifecycle_final
where nvl(decisionSequenceNumber, 0) = nvl(maxDecisionSequenceNumber, 0)
