----------------------------------------------------------------------------------------------------
-- DMD ITEM-LEVEL RACK ETL
-- Owner/Author: Store Selling Insights
-- Date Created: 11/15/2024
-- Last Updated: 11/15/2024
-- Updated By: Soutrik Saha (JIWG)
----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
-- STORE LOOKUP --

CREATE MULTISET VOLATILE TABLE STORES AS (
	SELECT 
		A.*, 
		B.RD_PEER_GROUP_NUM,
		B.RD_PEER_GROUP_DESC,
		B.RD_PEER_GROUP_TYPE_CODE 
	FROM PRD_NAP_USR_VWS.STORE_DIM A
	JOIN (
		SELECT   
			STORE_NUM,
			COALESCE(PEER_GROUP_NUM,'999999') AS RD_PEER_GROUP_NUM,
			COALESCE(UPPER(PEER_GROUP_DESC),'NA') AS RD_PEER_GROUP_DESC,
			COALESCE(PEER_GROUP_TYPE_CODE,'NA') AS RD_PEER_GROUP_TYPE_CODE
		FROM PRD_NAP_USR_VWS.STORE_PEER_GROUP_DIM
		WHERE PEER_GROUP_TYPE_CODE IN ('OPD')
		) B 
	ON A.STORE_NUM = B.STORE_NUM
	WHERE STORE_NAME NOT LIKE '%TEST%' 
		AND STORE_NAME NOT LIKE '%CLSD%' 
		AND STORE_NAME NOT LIKE '%CLOSED%'
		AND STORE_NAME NOT LIKE '%FINANCIAL STORE%'
		AND STORE_NAME NOT LIKE '%NORDSTROM LOCAL%'
		AND CHANNEL_NUM = 210 
	) WITH DATA PRIMARY INDEX (STORE_NUM) ON COMMIT PRESERVE rows;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM)
	ON STORES;

----------------------------------------------------------------------------------------------------
-- MERCH LOOKUP --

CREATE MULTISET VOLATILE TABLE MERCH_PRODUCT_LKP AS (
	SELECT 
		MP.RMS_SKU_NUM
		, MP.CHANNEL_COUNTRY
		, PS.STYLE_GROUP_NUM
		, PS.STYLE_GROUP_DESC
		, MP.PRMY_SUPP_NUM AS VENDOR_NUM
		, V.VENDOR_NAME
		, MP.DEPT_NUM
		, MP.DEPT_DESC
		, MP.DIV_NUM 
		, MP.DIV_DESC
		, MP.GRP_NUM
		, MP.GRP_DESC
		, SB.RACK_STRATEGIC_BRAND_IND AS RSB_IND 
	FROM PRD_NAP_USR_VWS.MERCH_PRODUCT_SKU_DIM_AS_IS_VW	MP
	JOIN PRD_NAP_USR_VWS.PRODUCT_STYLE_RMS_DIM_VW PS
	ON MP.CHANNEL_COUNTRY = PS.CHANNEL_COUNTRY  
		AND MP.RMS_STYLE_NUM = PS.RMS_STYLE_NUM
	JOIN (
		SELECT DISTINCT VENDOR_NUM, VENDOR_NAME FROM PRD_NAP_USR_VWS.VENDOR_DIM WHERE VENDOR_ROLE_NAME = 'VENDOR ORDER FROM'
		) V
	ON MP.PRMY_SUPP_NUM = V.VENDOR_NUM
	LEFT JOIN T2DL_DAS_IN_SEASON_MANAGEMENT_REPORTING.RACK_STRATEGIC_BRANDS_VW SB
	ON MP.DEPT_NUM = SB.DEPT_NUM 
		AND MP.PRMY_SUPP_NUM = SB.SUPPLIER_IDNT
	WHERE MP.DEPT_DESC NOT LIKE '%INACTIVE%'
		AND MP.DEPT_DESC NOT LIKE '%SAMPLES%'
		AND MP.DIV_NUM IN (800, 700, 600, 365, 360, 351, 345, 340, 310, 70)
		AND MP.CHANNEL_COUNTRY = 'US'
		AND SB.RACK_STRATEGIC_BRAND_IND = 'Y'
	) WITH DATA PRIMARY INDEX (RMS_SKU_NUM, STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM) ON COMMIT PRESERVE ROWS; 

COLLECT STATISTICS PRIMARY INDEX (RMS_SKU_NUM, STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	, COLUMN(VENDOR_NUM)
	ON MERCH_PRODUCT_LKP;

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-- DAILY VIEW --

CREATE MULTISET VOLATILE TABLE MERCH_TRAN_DAILY AS (
    SELECT
        'DAILY' AS DMD_VIEW
        , MT.RMS_SKU_NUM
        , S.STORE_NUM
        , S.STORE_NAME
        , S.COMP_STATUS_DESC AS STORE_STATUS
        , S.SUBGROUP_NUM
        , S.SUBGROUP_MEDIUM_DESC
		, S.RD_PEER_GROUP_DESC
        , CASE WHEN S.STORE_TYPE_CODE <> 'VS' THEN 'N' ELSE 'Y' END AS VS_INDICATOR
        , DC.DAY_DATE AS FISCAL_LABEL
        , JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
        , JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
        , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
        , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
        , INVENTORY_EOH_TOTAL_UNITS_TY
        , INVENTORY_EOH_TOTAL_UNITS_LY
        , INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
        , INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
        , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
        , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
    FROM PRD_NAP_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT_TY_LY_VW MT
    JOIN STORES S 
    	ON MT.STORE_NUM = S.STORE_NUM
    JOIN PRD_NAP_VWS.DAY_CAL_454_DIM DC 
    	ON MT.DAY_NUM = DC.DAY_IDNT
    WHERE DC.DAY_DATE >= ((SELECT MAX(dw_batch_dt) FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW WHERE interface_code = 'MRIC_DAY_AGG_DLY')-7) 
    	AND DC.DAY_DATE <= (SELECT MAX(dw_batch_dt) FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW WHERE interface_code = 'MRIC_DAY_AGG_DLY')
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, SUBGROUP_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, SUBGROUP_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_DAILY;


-- Staging table at STYLE_GROUP_NUM x STORE x DATE level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_DAILY_STG_1 AS (
	SELECT	
		DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, MP.DEPT_NUM
		, DEPT_DESC
		, DIV_NUM
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, STORE_NUM
		, STORE_NAME
		, STORE_STATUS
		, VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
        , JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
        , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
        , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
        , INVENTORY_EOH_TOTAL_UNITS_TY
        , INVENTORY_EOH_TOTAL_UNITS_LY
        , INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
        , INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
        , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
        , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_DAILY	MT
	JOIN MERCH_PRODUCT_LKP	MP
		ON MT.RMS_SKU_NUM = MP.RMS_SKU_NUM 
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	,	COLUMN(STORE_NUM)
	ON DMD_ITEM_LEVEL_DAILY_STG_1;

-- Freeing up space
DROP TABLE MERCH_TRAN_DAILY;


-- Aggregated staging table at STYLE_GROUP_NUM x STORE x DATE level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_DAILY_STG_2 AS (
	SELECT 	
		DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, DEPT_NUM
		, DEPT_DESC
		, DIV_NUM 
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, STORE_NUM
		, STORE_NAME
		, STORE_STATUS
		, VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM DMD_ITEM_LEVEL_DAILY_STG_1
	GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_DAILY_STG_2;
	
-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_DAILY_STG_1;

------------------------------------------------------------------------------
-- Staging tables for Ranking

-- Last day Data Extract for calculating Rank --ITEM LEVEL
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_DAILY_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			FISCAL_LABEL
			, STORE_NUM
			, RD_PEER_GROUP_DESC
			, STYLE_GROUP_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_DAILY_STG_2 A
		WHERE FISCAL_LABEL = (SELECT MAX(DW_BATCH_DT) FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW WHERE INTERFACE_CODE = 'MRIC_DAY_AGG_DLY')
		GROUP BY 1, 2, 3, 4
		) A
	) WITH DATA PRIMARY INDEX (FISCAL_LABEL, STYLE_GROUP_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (FISCAL_LABEL, STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_DAILY_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_DAILY_RANK AS (
	SELECT     
		FISCAL_LABEL
		, STORE_NUM
		, STYLE_GROUP_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_REGION_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_FLEET_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_DAILY_RANK_STG
	GROUP BY 1, 2, 3, 4, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (FISCAL_LABEL, STYLE_GROUP_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (FISCAL_LABEL, STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_DAILY_RANK;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_DAILY_RANK_STG;


-- Last day Data Extract for calculating Rank --SUPPLIER LEVEL
CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_DAILY_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			FISCAL_LABEL
			, STORE_NUM
			, RD_PEER_GROUP_DESC
			, VENDOR_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_DAILY_STG_2 A
		WHERE FISCAL_LABEL = (SELECT MAX(DW_BATCH_DT) FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW WHERE INTERFACE_CODE = 'MRIC_DAY_AGG_DLY')
		GROUP BY 1, 2, 3, 4
		) A
	) WITH DATA PRIMARY INDEX (FISCAL_LABEL, VENDOR_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (FISCAL_LABEL, VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_DAILY_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_DAILY_RANK AS (
	SELECT     
		FISCAL_LABEL
		, STORE_NUM
		, VENDOR_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_REGION_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_FLEET_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_FLEET_VAR_LY_RANK
	FROM DMD_SUPPLIER_LEVEL_DAILY_RANK_STG
	GROUP BY 1, 2, 3, 4, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (FISCAL_LABEL, VENDOR_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (FISCAL_LABEL, VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_DAILY_RANK;
	
-- Freeing up space
DROP TABLE DMD_SUPPLIER_LEVEL_DAILY_RANK_STG;

------------------------------------------------------------------------------
-- Daily View Final Table

CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_DAILY AS (
	SELECT 
		DMD_VIEW
		, A.STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, A.VENDOR_NUM
		, VENDOR_NAME
		, DEPT_NUM
		, DEPT_DESC
		, DIV_NUM
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, A.STORE_NUM
		, STORE_NAME
		, STORE_STATUS
		, VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, A.RD_PEER_GROUP_DESC
		, RSB_IND
		, CAST(A.FISCAL_LABEL AS VARCHAR(50)) AS FISCAL_LABEL
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
        , JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
        , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
        , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
        , INVENTORY_EOH_TOTAL_UNITS_TY
        , INVENTORY_EOH_TOTAL_UNITS_LY
        , INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
        , INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
        , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
        , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
		, SUPPLIER_REGION_RANK
		, SUPPLIER_REGION_VAR_LY_RANK
		, SUPPLIER_FLEET_RANK
		, SUPPLIER_FLEET_VAR_LY_RANK
		, ITEM_REGION_RANK
		, ITEM_REGION_VAR_LY_RANK
		, ITEM_FLEET_RANK
		, ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_DAILY_STG_2 A
	LEFT JOIN DMD_ITEM_LEVEL_DAILY_RANK B
		ON A.FISCAL_LABEL = B.FISCAL_LABEL
		AND A.STORE_NUM = B.STORE_NUM
		AND A.STYLE_GROUP_NUM = B.STYLE_GROUP_NUM
	LEFT JOIN DMD_SUPPLIER_LEVEL_DAILY_RANK C
		ON A.FISCAL_LABEL = C.FISCAL_LABEL
		AND A.STORE_NUM = C.STORE_NUM
		AND A.VENDOR_NUM = C.VENDOR_NUM
	) WITH DATA PRIMARY INDEX (FISCAL_LABEL, STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (FISCAL_LABEL, STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_DAILY;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_DAILY_STG_2;

DROP TABLE DMD_ITEM_LEVEL_DAILY_RANK;

DROP TABLE DMD_SUPPLIER_LEVEL_DAILY_RANK;

-------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------
-- YTD VIEW --

-- Year(Quarter-wise) Date Lookup
CREATE MULTISET VOLATILE TABLE QTR AS (
	WITH batch_dt AS (
		SELECT 
			MAX(dw_batch_dt) AS max_batch_dt
		FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW 
		WHERE interface_code = 'MRIC_DAY_AGG_DLY'
		),
	curr_dt AS (
		SELECT DISTINCT 
			FISCAL_YEAR_NUM AS max_batch_fyr
			, QUARTER_IDNT AS max_batch_qtr
		FROM PRD_NAP_VWS.DAY_CAL_454_DIM d
		JOIN batch_dt c
			ON c.max_batch_dt = d.day_date
	)
	SELECT 
		FISCAL_YEAR_NUM
		, QUARTER_IDNT
		, QUARTER_ABRV
		, QUARTER_LABEL
		, DAY_IDNT
		, QUARTER_START_DAY_IDNT AS MIN_DAY_IDNT
		, MAX(DAY_IDNT) OVER (PARTITION BY FISCAL_YEAR_NUM, QUARTER_IDNT) AS MAX_DAY_IDNT
		, CASE WHEN QUARTER_IDNT = c.max_batch_qtr THEN 'Y' ELSE 'N' END AS CURRENT_QTR_IND
	FROM PRD_NAP_VWS.DAY_CAL_454_DIM d
	LEFT JOIN curr_dt c
		ON c.max_batch_qtr = d.QUARTER_IDNT
	WHERE FISCAL_YEAR_NUM = (SELECT DISTINCT max_batch_fyr FROM curr_dt)
		AND DAY_DATE <= (SELECT max_batch_dt FROM batch_dt)
	) WITH DATA PRIMARY INDEX (DAY_IDNT) ON COMMIT PRESERVE ROWS; 

COLLECT STATISTICS PRIMARY INDEX (DAY_IDNT)
	, COLUMN(CURRENT_QTR_IND)
	, COLUMN(QUARTER_LABEL)
	, COLUMN(QUARTER_ABRV)
	ON QTR;


----------- Q1
-- Transaction Staging Table for Q1
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q1_STG AS (
	SELECT 	
		RMS_SKU_NUM
		, MT.STORE_NUM
		, DAY_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM PRD_NAP_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT_TY_LY_VW MT
	JOIN QTR Q
		ON MT.DAY_NUM = Q.DAY_IDNT
		AND Q.QUARTER_ABRV = 'Q1'
	JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(DAY_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q1_STG;


-- Transaction for Q1
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q1 AS (
	SELECT 	
		RMS_SKU_NUM
		, STORE_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_Q1_STG MT
	GROUP BY 1, 2, 3, 4
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q1;

-- Freeing up space
DROP TABLE MERCH_TRAN_Q1_STG;


----------- Q2
-- Transaction Staging Table for Q2
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q2_STG AS (
	SELECT 	
		RMS_SKU_NUM
		, MT.STORE_NUM
		, DAY_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM PRD_NAP_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT_TY_LY_VW MT
	JOIN QTR Q
		ON MT.DAY_NUM = Q.DAY_IDNT
		AND Q.QUARTER_ABRV = 'Q2'
	JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(DAY_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q2_STG;


-- Transaction for Q2
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q2 AS (
	SELECT 	
		RMS_SKU_NUM
		, STORE_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_Q2_STG MT
	GROUP BY 1, 2, 3, 4
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q2;

-- Freeing up space
DROP TABLE MERCH_TRAN_Q2_STG;


----------- Q3
-- Transaction Staging Table for Q3
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q3_STG AS (
	SELECT 	
		RMS_SKU_NUM
		, MT.STORE_NUM
		, DAY_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM PRD_NAP_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT_TY_LY_VW MT
	JOIN QTR Q
		ON MT.DAY_NUM = Q.DAY_IDNT
		AND Q.QUARTER_ABRV = 'Q3'
	JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(DAY_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q3_STG;


-- Transaction for Q3
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q3 AS (
	SELECT 	
		RMS_SKU_NUM
		, STORE_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_Q3_STG MT
	GROUP BY 1, 2, 3, 4
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q3;

-- Freeing up space
DROP TABLE MERCH_TRAN_Q3_STG;


----------- Q4
-- Transaction Staging Table for Q4
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q4_STG AS (
	SELECT 	
		RMS_SKU_NUM
		, MT.STORE_NUM
		, DAY_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM PRD_NAP_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT_TY_LY_VW MT
	JOIN QTR Q
		ON MT.DAY_NUM = Q.DAY_IDNT
		AND Q.QUARTER_ABRV = 'Q4'
	JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(DAY_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q4_STG;


-- Transaction for Q4
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_Q4 AS (
	SELECT 	
		RMS_SKU_NUM
		, STORE_NUM
		, FISCAL_YEAR_NUM
		, CURRENT_QTR_IND
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_Q4_STG MT
	GROUP BY 1, 2, 3, 4
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_Q4;

-- Freeing up space
DROP TABLE MERCH_TRAN_Q4_STG;


-- YTD AGG
-- MERCH TRAN STAGING
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_YTD_STG AS (
	SELECT * FROM MERCH_TRAN_Q1
	UNION ALL 
	SELECT * FROM MERCH_TRAN_Q2
	UNION ALL 
	SELECT * FROM MERCH_TRAN_Q3
	UNION ALL 
	SELECT * FROM MERCH_TRAN_Q4
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM,CURRENT_QTR_IND) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM,CURRENT_QTR_IND)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(CURRENT_QTR_IND)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_YTD_STG;

-- Freeing up space
DROP TABLE MERCH_TRAN_Q1;

DROP TABLE MERCH_TRAN_Q2;

DROP TABLE MERCH_TRAN_Q3;

DROP TABLE MERCH_TRAN_Q4;


-- AGG MERCH TRAN
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_YTD AS (
	SELECT 	
		RMS_SKU_NUM
		, STORE_NUM
		, CAST(FISCAL_YEAR_NUM AS VARCHAR(50)) AS FISCAL_LABEL
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(CASE WHEN CURRENT_QTR_IND = 'Y' THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE 0 END) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(CASE WHEN CURRENT_QTR_IND = 'Y' THEN INVENTORY_EOH_TOTAL_UNITS_LY ELSE 0 END) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(CASE WHEN CURRENT_QTR_IND = 'Y' THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(CASE WHEN CURRENT_QTR_IND = 'Y' THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_LY ELSE 0 END) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(CASE WHEN CURRENT_QTR_IND = 'Y' THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY ELSE 0 END) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(CASE WHEN CURRENT_QTR_IND = 'Y' THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY ELSE 0 END) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_YTD_STG AS MT
	GROUP BY 1, 2, 3
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_YTD;


-- Staging table at STYLE_GROUP_NUM x STORE x YTD level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_YTD_STG_1 AS (
	SELECT	
		'YTD' AS DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, MP.DEPT_NUM
		, DEPT_DESC
		, DIV_NUM
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, MT.STORE_NUM
		, STORE_NAME
		, S.COMP_STATUS_DESC AS STORE_STATUS
		, CASE WHEN S.STORE_TYPE_CODE <> 'VS' THEN 'N' ELSE 'Y' END AS VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
	    , JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
	    , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
	    , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
	    , INVENTORY_EOH_TOTAL_UNITS_TY
	    , INVENTORY_EOH_TOTAL_UNITS_LY
	    , INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
	    , INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
	    , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
	    , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_YTD	MT
	INNER JOIN MERCH_PRODUCT_LKP MP
		ON MT.RMS_SKU_NUM = MP.RMS_SKU_NUM 
	INNER JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	, COLUMN(STORE_NUM)
	ON DMD_ITEM_LEVEL_YTD_STG_1;

-- Freeing up space
DROP TABLE MERCH_TRAN_YTD;


-- Aggregated staging table at STYLE_GROUP_NUM x STORE x YTD level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_YTD_STG_2 AS (
	SELECT	
		DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, DEPT_NUM
		, DEPT_DESC
		, DIV_NUM 
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, STORE_NUM
		, STORE_NAME
		, STORE_STATUS
		, VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM DMD_ITEM_LEVEL_YTD_STG_1
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_YTD_STG_2;

------------------------------------------------------------------------------
-- Staging tables for Ranking

-- Item Level Ranking
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_YTD_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			STORE_NUM
			, RD_PEER_GROUP_DESC
			, STYLE_GROUP_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_YTD_STG_2 A
		GROUP BY 1, 2, 3
		) A
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_YTD_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_YTD_RANK AS (
	SELECT     
		STORE_NUM
		, STYLE_GROUP_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_REGION_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_FLEET_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_YTD_RANK_STG
	GROUP BY 1, 2, 3, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_YTD_RANK;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_YTD_RANK_STG;


-- Supplier Level Ranking
CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_YTD_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			STORE_NUM
			, RD_PEER_GROUP_DESC
			, VENDOR_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_YTD_STG_2 A
		GROUP BY 1, 2, 3
		) A
	) WITH DATA PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_YTD_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_YTD_RANK AS (
	SELECT     
		STORE_NUM
		, VENDOR_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_REGION_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_FLEET_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_FLEET_VAR_LY_RANK
	FROM DMD_SUPPLIER_LEVEL_YTD_RANK_STG
	GROUP BY 1, 2, 3, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_YTD_RANK;
	
-- Freeing up space
DROP TABLE DMD_SUPPLIER_LEVEL_YTD_RANK_STG;

------------------------------------------------------------------------------
-- YTD View Final Table

CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_YTD AS (
	SELECT	A.*
		, SUPPLIER_REGION_RANK
		, SUPPLIER_REGION_VAR_LY_RANK
		, SUPPLIER_FLEET_RANK
		, SUPPLIER_FLEET_VAR_LY_RANK
		, ITEM_REGION_RANK
		, ITEM_REGION_VAR_LY_RANK
		, ITEM_FLEET_RANK
		, ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_YTD_STG_2 A
	LEFT JOIN DMD_ITEM_LEVEL_YTD_RANK B
		ON A.STORE_NUM = B.STORE_NUM
		AND A.STYLE_GROUP_NUM = B.STYLE_GROUP_NUM
	LEFT JOIN DMD_SUPPLIER_LEVEL_YTD_RANK C
		ON A.STORE_NUM = C.STORE_NUM
		AND A.VENDOR_NUM = C.VENDOR_NUM
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_YTD;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_YTD_STG_2;

DROP TABLE DMD_ITEM_LEVEL_YTD_RANK;

DROP TABLE DMD_SUPPLIER_LEVEL_YTD_RANK;

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-- QTD VIEW --

-- Quarter Date Lookup
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_QTD AS (
	SELECT
		RMS_SKU_NUM
		, STORE_NUM
		, QUARTER_LABEL AS FISCAL_LABEL
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, INVENTORY_EOH_TOTAL_UNITS_TY
		, INVENTORY_EOH_TOTAL_UNITS_LY
		, INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_YTD_STG Y
	INNER JOIN (
		SELECT DISTINCT 
			CAST(QUARTER_LABEL AS VARCHAR(50)) AS QUARTER_LABEL
			, CURRENT_QTR_IND
		FROM QTR 
		WHERE CURRENT_QTR_IND = 'Y'
		)Q
		ON Q.CURRENT_QTR_IND = Y.CURRENT_QTR_IND
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	ON MERCH_TRAN_QTD;

-- Freeing up space
DROP TABLE MERCH_TRAN_YTD_STG;


-- Staging table at STYLE_GROUP_NUM x STORE x QTD level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_QTD_STG_1 AS (
	SELECT	
		'QTD' AS DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, MP.DEPT_NUM
		, DEPT_DESC
		, DIV_NUM
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, MT.STORE_NUM
		, STORE_NAME
		, S.COMP_STATUS_DESC AS STORE_STATUS
		, CASE WHEN S.STORE_TYPE_CODE <> 'VS' THEN 'N' ELSE 'Y' END AS VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
	    , JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
	    , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
	    , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
	    , INVENTORY_EOH_TOTAL_UNITS_TY
	    , INVENTORY_EOH_TOTAL_UNITS_LY
	    , INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
	    , INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
	    , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
	    , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_QTD	MT
	INNER JOIN MERCH_PRODUCT_LKP	MP
		ON MT.RMS_SKU_NUM = MP.RMS_SKU_NUM  
	INNER JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	, COLUMN(STORE_NUM)
	ON DMD_ITEM_LEVEL_QTD_STG_1;

-- Freeing up space
DROP TABLE MERCH_TRAN_QTD;


-- Aggregated staging table at STYLE_GROUP_NUM x STORE x QTD level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_QTD_STG_2 AS (
	SELECT	
		DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, DEPT_NUM
		, DEPT_DESC
		, DIV_NUM 
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, STORE_NUM
		, STORE_NAME
		, STORE_STATUS
		, VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM DMD_ITEM_LEVEL_QTD_STG_1
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_QTD_STG_2;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_QTD_STG_1;

------------------------------------------------------------------------------
-- Staging tables for Ranking

-- Item Level Ranking
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_QTD_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			STORE_NUM
			, RD_PEER_GROUP_DESC
			, STYLE_GROUP_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_QTD_STG_2 A
		GROUP BY 1, 2, 3
		) A
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_QTD_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_QTD_RANK AS (
	SELECT     
		STORE_NUM
		, STYLE_GROUP_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_REGION_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_FLEET_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_QTD_RANK_STG
	GROUP BY 1, 2, 3, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_QTD_RANK;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_QTD_RANK_STG;


-- Supplier Level Ranking
CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_QTD_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			STORE_NUM
			, RD_PEER_GROUP_DESC
			, VENDOR_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_QTD_STG_2 A
		GROUP BY 1, 2, 3
		) A
	) WITH DATA PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_QTD_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_QTD_RANK AS (
	SELECT     
		STORE_NUM
		, VENDOR_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_REGION_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_FLEET_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_FLEET_VAR_LY_RANK
	FROM DMD_SUPPLIER_LEVEL_QTD_RANK_STG
	GROUP BY 1, 2, 3, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_QTD_RANK;
	
-- Freeing up space
DROP TABLE DMD_SUPPLIER_LEVEL_QTD_RANK_STG;

------------------------------------------------------------------------------
-- QTD View Final Table

CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_QTD AS (
	SELECT	A.*
		, SUPPLIER_REGION_RANK
		, SUPPLIER_REGION_VAR_LY_RANK
		, SUPPLIER_FLEET_RANK
		, SUPPLIER_FLEET_VAR_LY_RANK
		, ITEM_REGION_RANK
		, ITEM_REGION_VAR_LY_RANK
		, ITEM_FLEET_RANK
		, ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_QTD_STG_2 A
	LEFT JOIN DMD_ITEM_LEVEL_QTD_RANK B
		ON A.STORE_NUM = B.STORE_NUM
		AND A.STYLE_GROUP_NUM = B.STYLE_GROUP_NUM
	LEFT JOIN DMD_SUPPLIER_LEVEL_QTD_RANK C
		ON A.STORE_NUM = C.STORE_NUM
		AND A.VENDOR_NUM = C.VENDOR_NUM
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_QTD;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_QTD_STG_2;

DROP TABLE DMD_ITEM_LEVEL_QTD_RANK;

DROP TABLE DMD_SUPPLIER_LEVEL_QTD_RANK;

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-- MTD VIEW --

-- Month Date Lookup
CREATE MULTISET VOLATILE TABLE MTH AS (
	SELECT DISTINCT
		FISCAL_YEAR_NUM
		, MONTH_IDNT
		, CAST(MONTH_LABEL AS VARCHAR(50)) AS MONTH_LABEL
		, DAY_IDNT
		, MONTH_START_DAY_IDNT AS MIN_DAY_IDNT
		, MAX(DAY_IDNT) OVER (PARTITION BY MONTH_IDNT) AS MAX_DAY_IDNT
	FROM PRD_NAP_VWS.DAY_CAL_454_DIM d
	WHERE MONTH_START_DAY_DATE <= (SELECT MAX(dw_batch_dt) FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW WHERE interface_code = 'MRIC_DAY_AGG_DLY')
		AND MONTH_END_DAY_DATE >= (SELECT MAX(dw_batch_dt) FROM PRD_NAP_VWS.ETL_BATCH_DT_LKUP_VW WHERE interface_code = 'MRIC_DAY_AGG_DLY')
	) WITH DATA PRIMARY INDEX (DAY_IDNT) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (DAY_IDNT)
	ON MTH;


-- Transaction Staging Table for MTD
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_MTD_STG AS (
	SELECT 	
		RMS_SKU_NUM
		, MT.STORE_NUM
		, MONTH_LABEL AS FISCAL_LABEL
		, DAY_NUM
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_UNITS_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_UNITS_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, CASE WHEN MAX_DAY_IDNT = DAY_NUM THEN INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY ELSE NULL END AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM PRD_NAP_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT_TY_LY_VW MT
	JOIN MTH DC
		ON MT.DAY_NUM = DC.DAY_IDNT
	JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM) ON COMMIT PRESERVE ROWS;
	
COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM, DAY_NUM)
	, COLUMN(STORE_NUM)
	, COLUMN(RMS_SKU_NUM)
	, COLUMN(DAY_NUM)
	ON MERCH_TRAN_MTD_STG;


-- Transaction Agg Table for MTD
CREATE MULTISET VOLATILE TABLE MERCH_TRAN_MTD AS (
	SELECT 	
		RMS_SKU_NUM
		, STORE_NUM
		, FISCAL_LABEL
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_MTD_STG
	GROUP BY 1,2,3
	) WITH DATA PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STORE_NUM, RMS_SKU_NUM)
	, COLUMN(STORE_NUM)
	, COLUMN(RMS_SKU_NUM)
	ON MERCH_TRAN_MTD;

-- Freeing up space
DROP TABLE MERCH_TRAN_MTD_STG;


-- Staging table at STYLE_GROUP_NUM x STORE x MTD level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_MTD_STG_1 AS (
	SELECT	
		'MTD' AS DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, MP.DEPT_NUM
		, DEPT_DESC
		, DIV_NUM
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC  
		, MT.STORE_NUM
		, STORE_NAME
		, S.COMP_STATUS_DESC AS STORE_STATUS
		, CASE WHEN S.STORE_TYPE_CODE <> 'VS' THEN 'N' ELSE 'Y' END AS VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
	    , JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
	    , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
	    , JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
	    , INVENTORY_EOH_TOTAL_UNITS_TY
	    , INVENTORY_EOH_TOTAL_UNITS_LY
	    , INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
	    , INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
	    , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
	    , INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM MERCH_TRAN_MTD	MT
	INNER JOIN MERCH_PRODUCT_LKP	MP
		ON MT.RMS_SKU_NUM = MP.RMS_SKU_NUM  
	INNER JOIN STORES S 
		ON MT.STORE_NUM = S.STORE_NUM
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	, COLUMN(STORE_NUM)
	ON DMD_ITEM_LEVEL_MTD_STG_1;

-- Freeing up space
DROP TABLE MERCH_TRAN_MTD;


-- Aggregated staging table at STYLE_GROUP_NUM x STORE x MTD level
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_MTD_STG_2 AS (
	SELECT	
		DMD_VIEW
		, STYLE_GROUP_NUM
		, STYLE_GROUP_DESC
		, VENDOR_NUM
		, VENDOR_NAME
		, DEPT_NUM
		, DEPT_DESC
		, DIV_NUM 
		, DIV_DESC
		, GRP_NUM
		, GRP_DESC
		, STORE_NUM
		, STORE_NAME
		, STORE_STATUS
		, VS_INDICATOR
		, SUBGROUP_NUM
		, SUBGROUP_MEDIUM_DESC
		, RD_PEER_GROUP_DESC
		, RSB_IND
		, FISCAL_LABEL
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INVENTORY_EOH_TOTAL_UNITS_LY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_LY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, SUM(INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY) AS INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
	FROM DMD_ITEM_LEVEL_MTD_STG_1
	GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_MTD_STG_2;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_MTD_STG_1;


------------------------------------------------------------------------------
-- Staging tables for Ranking

-- Item Level Ranking
CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_MTD_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			STORE_NUM
			, RD_PEER_GROUP_DESC
			, STYLE_GROUP_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_MTD_STG_2 A
		GROUP BY 1, 2, 3
		) A
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_MTD_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_MTD_RANK AS (
	SELECT     
		STORE_NUM
		, STYLE_GROUP_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_REGION_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS ITEM_FLEET_RANK
		, RANK() OVER (PARTITION BY STYLE_GROUP_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_MTD_RANK_STG
	GROUP BY 1, 2, 3, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_MTD_RANK;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_MTD_RANK_STG;


-- Supplier Level Ranking
CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_MTD_RANK_STG AS (
	SELECT A.*
		, CASE WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY = 0 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			WHEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY < 0 THEN (-1 * ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY))
			ELSE ((JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY - JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY)/JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) END AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR	
	FROM (
		SELECT	
			STORE_NUM
			, RD_PEER_GROUP_DESC
			, VENDOR_NUM
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
			, SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		FROM DMD_ITEM_LEVEL_MTD_STG_2 A
		GROUP BY 1, 2, 3
		) A
	) WITH DATA PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_MTD_RANK_STG;


CREATE MULTISET VOLATILE TABLE DMD_SUPPLIER_LEVEL_MTD_RANK AS (
	SELECT     
		STORE_NUM
		, VENDOR_NUM
		, RD_PEER_GROUP_DESC
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_REGION_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM, RD_PEER_GROUP_DESC ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_REGION_VAR_LY_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY DESC) AS SUPPLIER_FLEET_RANK
		, RANK() OVER (PARTITION BY VENDOR_NUM ORDER BY JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR DESC) AS SUPPLIER_FLEET_VAR_LY_RANK
	FROM DMD_SUPPLIER_LEVEL_MTD_RANK_STG
	GROUP BY 1, 2, 3, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_VAR
	) WITH DATA PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (VENDOR_NUM, STORE_NUM, RD_PEER_GROUP_DESC)
	, COLUMN(VENDOR_NUM, STORE_NUM)
	, COLUMN(VENDOR_NUM)
	ON DMD_SUPPLIER_LEVEL_MTD_RANK;
	
-- Freeing up space
DROP TABLE DMD_SUPPLIER_LEVEL_MTD_RANK_STG;

------------------------------------------------------------------------------
-- MTD View Final Table

CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_MTD AS (
	SELECT	A.*
		, SUPPLIER_REGION_RANK
		, SUPPLIER_REGION_VAR_LY_RANK
		, SUPPLIER_FLEET_RANK
		, SUPPLIER_FLEET_VAR_LY_RANK
		, ITEM_REGION_RANK
		, ITEM_REGION_VAR_LY_RANK
		, ITEM_FLEET_RANK
		, ITEM_FLEET_VAR_LY_RANK
	FROM DMD_ITEM_LEVEL_MTD_STG_2 A
	LEFT JOIN DMD_ITEM_LEVEL_MTD_RANK B
		ON A.STORE_NUM = B.STORE_NUM
		AND A.STYLE_GROUP_NUM = B.STYLE_GROUP_NUM
	LEFT JOIN DMD_SUPPLIER_LEVEL_MTD_RANK C
		ON A.STORE_NUM = C.STORE_NUM
		AND A.VENDOR_NUM = C.VENDOR_NUM
	) WITH DATA PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM) ON COMMIT PRESERVE ROWS;

COLLECT STATISTICS PRIMARY INDEX (STYLE_GROUP_NUM, VENDOR_NUM, DEPT_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM, STORE_NUM)
	, COLUMN(STYLE_GROUP_NUM)
	ON DMD_ITEM_LEVEL_MTD;

-- Freeing up space
DROP TABLE DMD_ITEM_LEVEL_MTD_STG_2;

DROP TABLE DMD_ITEM_LEVEL_MTD_RANK;

DROP TABLE DMD_SUPPLIER_LEVEL_MTD_RANK;

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
-- Creating final temp table before inserting into production table

CREATE MULTISET VOLATILE TABLE DMD_ITEM_LEVEL_FINAL AS (
	SELECT	
		DMD_VIEW
		, FISCAL_LABEL
		, SUBGROUP_MEDIUM_DESC AS REGION
		, TRIM(TRIM(STORE_NUM) ||', '|| STORE_NAME) AS STORE
		, STORE_STATUS
		, VS_INDICATOR
		, TRIM(TRIM(DIV_NUM) ||', '|| DIV_DESC) AS DIVISION
		, TRIM(TRIM(GRP_NUM) ||', '|| GRP_DESC) AS SUBDIVISION
		, TRIM(TRIM(DEPT_NUM) ||', '|| DEPT_DESC) AS DEPARTMENT
		, RD_PEER_GROUP_DESC AS DISTRICT
		, RSB_IND
		, VENDOR_NAME AS SUPPLIER
		, TRIM(TRIM(STYLE_GROUP_NUM) ||', '|| STYLE_GROUP_DESC) AS STYLE_GROUP
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
		, JWN_OPERATIONAL_GMV_TOTAL_UNITS_LY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		, JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_LY
		, INVENTORY_EOH_TOTAL_UNITS_TY
		, INVENTORY_EOH_TOTAL_UNITS_LY
		, INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		, INVENTORY_EOH_TOTAL_RETAIL_AMT_LY
		, INVENTORY_EOH_CLEARANCE_RETAIL_AMT_TY
		, INVENTORY_EOH_CLEARANCE_RETAIL_AMT_LY
		, SUPPLIER_REGION_RANK
		, SUPPLIER_REGION_VAR_LY_RANK
		, SUPPLIER_FLEET_RANK
		, SUPPLIER_FLEET_VAR_LY_RANK
		, ITEM_REGION_RANK
		, ITEM_REGION_VAR_LY_RANK
		, ITEM_FLEET_RANK
		, ITEM_FLEET_VAR_LY_RANK
		, CURRENT_TIMESTAMP as dw_sys_load_tmstp
	FROM (
		(SELECT * FROM DMD_ITEM_LEVEL_DAILY)
		UNION ALL 
		(SELECT * FROM DMD_ITEM_LEVEL_MTD)
		UNION ALL 
		(SELECT * FROM DMD_ITEM_LEVEL_QTD) 
		UNION ALL 
		(SELECT * FROM DMD_ITEM_LEVEL_YTD)
		) A
	) WITH DATA PRIMARY INDEX (DMD_VIEW, REGION, STORE, DIVISION, SUBDIVISION, DEPARTMENT, SUPPLIER, STYLE_GROUP) ON COMMIT PRESERVE ROWS;

----------------------------------------------------------------------------------------------------

DELETE FROM {environment_schema}.DMD_ITEM_RACK{env_suffix};

INSERT INTO {environment_schema}.DMD_ITEM_RACK{env_suffix} SELECT * FROM DMD_ITEM_LEVEL_FINAL;

----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------