-- 2022.08.04 - Insert into adhoc list
DELETE FROM T2DL_DAS_SCALED_EVENTS.ADHOC_SKU_LIST;
INSERT INTO T2DL_DAS_SCALED_EVENTS.ADHOC_SKU_LIST
SELECT SKU_IDNT
    ,COUNTRY
    ,CURRENT_TIMESTAMP AS PROCESS_TIMESTAMP
FROM T3DL_ACE_MCH.ADHOC_SKU_LIST;

COLLECT STATS
    PRIMARY INDEX ( SKU_IDNT )
    ,COLUMN ( SKU_IDNT )
        ON T2DL_DAS_SCALED_EVENTS.ADHOC_SKU_LIST;


