/*------------------------------------------------------
 SKU Daily Backorder History Table
 Purpose: Provide SKU/Day/Loc/Price level information on historical and current backorders.
 Last Update: 4/1/22 Jonathan Popescu
 Contact for logic/code: Jonathan Popescu (Merch Analytics)
 Contact for ETL: Jonathan Popescu (Merch Analytics)
 */

-- Calculate location and current backorder flag
CREATE MULTISET VOLATILE TABLE BACKORDER_BASE_01 AS (
SELECT
	RMS_SKU_NUM
	, SOURCE_CHANNEL_COUNTRY_CODE AS CHANNEL_COUNTRY
	, CASE 	WHEN SOURCE_CHANNEL_CODE = 'FULL_LINE' THEN 'NORDSTROM'
			WHEN SOURCE_CHANNEL_CODE = 'RACK' THEN 'NORDSTROM_RACK'
			ELSE NULL
	END as CHANNEL_BRAND
	, CASE 	WHEN SOURCE_PLATFORM_CODE = 'POS' THEN SOURCE_STORE_NUM
			WHEN SOURCE_CHANNEL_CODE = 'FULL_LINE' and SOURCE_CHANNEL_COUNTRY_CODE = 'US' THEN 808
			WHEN SOURCE_CHANNEL_CODE = 'FULL_LINE' AND SOURCE_CHANNEL_COUNTRY_CODE = 'CA' THEN 867
			WHEN SOURCE_CHANNEL_CODE = 'RACK' THEN 828
	END as PRICE_STORE_NUM
	, CASE 	WHEN SOURCE_PLATFORM_CODE = 'POS' THEN 'STORE'
			ELSE 'ONLINE'
	END as SELLING_CHANNEL
	, ORDER_TMSTP_PACIFIC
	, ORDER_DATE_PACIFIC
	, ORDER_LINE_AMOUNT
	, ORDER_LINE_QUANTITY
	, CASE 	WHEN SHIPPED_DATE_PACIFIC is NULL
			AND CANCELED_DATE_PACIFIC is NULL
			AND ARRIVED_AT_ORDER_PICKUP_DATE_PACIFIC is NULL
			AND FULFILLED_DATE_PACIFIC is NULL
			AND REQUESTED_MAX_PROMISE_DATE_PACIFIC > CURRENT_DATE
			THEN 'Y' ELSE 'N'
	END as CURRENT_BACKORDER_FLAG
	, CASE 	WHEN COALESCE(order_line_promotion_discount_amount_usd,0) - coalesce(order_line_employee_discount_amount_usd,0) > 0 then 1
			ELSE 0 END as PROMO_FLAG
FROM PRD_NAP_USR_VWS.ORDER_LINE_DETAIL_FACT
WHERE ORDER_DATE_PACIFIC BETWEEN CURRENT_DATE - 365 AND CURRENT_DATE
AND (BACKORDER_IND = 'Y' OR BACKORDER_DISPLAY_IND = 'Y')
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
) with data primary index(RMS_SKU_NUM, PRICE_STORE_NUM, ORDER_TMSTP_PACIFIC) on commit preserve rows
;

COLLECT STATS
	 PRIMARY INDEX (RMS_SKU_NUM, PRICE_STORE_NUM, ORDER_TMSTP_PACIFIC)
	,COLUMN (RMS_SKU_NUM)
		ON BACKORDER_BASE_01;

-- Join to price table and calculate current price type
CREATE MULTISET VOLATILE TABLE BACKORDER_BASE_02 AS (
SELECT
	 a.RMS_SKU_NUM
	, a.PRICE_STORE_NUM
	, a.ORDER_TMSTP_PACIFIC
	, a.ORDER_DATE_PACIFIC
	, a.CHANNEL_COUNTRY
	, a.CHANNEL_BRAND
	, a.ORDER_LINE_AMOUNT
	, a.ORDER_LINE_QUANTITY
	, a.CURRENT_BACKORDER_FLAG
	, CASE WHEN PROMO_FLAG = 1 AND b.selling_retail_price_type_code = 'REGULAR' then 'P'
	   WHEN b.ownership_retail_price_type_code = 'CLEARANCE' then 'C'
	   WHEN b.selling_retail_price_type_code = 'PROMOTION' then 'P'
	   ELSE 'R'
	 END AS current_price_type
	, b.regular_price_amt
	, b.selling_retail_price_amt as current_price_amt
FROM BACKORDER_BASE_01 a
LEFT JOIN PRD_NAP_USR_VWS.PRODUCT_PRICE_TIMELINE_DIM b
		ON a.RMS_SKU_NUM = b.RMS_SKU_NUM
			AND a.price_store_num = b.store_num
			AND a.selling_channel = b.selling_channel
			AND a.ORDER_TMSTP_PACIFIC BETWEEN b.EFF_BEGIN_TMSTP AND b.EFF_END_TMSTP

GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12

) with data primary index(RMS_SKU_NUM, PRICE_STORE_NUM, CURRENT_PRICE_TYPE, ORDER_TMSTP_PACIFIC, CURRENT_PRICE_AMT) on commit preserve rows
;

COLLECT STATS
	 PRIMARY INDEX (RMS_SKU_NUM, PRICE_STORE_NUM, CURRENT_PRICE_TYPE, ORDER_TMSTP_PACIFIC, CURRENT_PRICE_AMT)
	,COLUMN (RMS_SKU_NUM)
		ON BACKORDER_BASE_02;

-- Separate total historical backorders and still current backorders into different columns
CREATE MULTISET VOLATILE TABLE FINAL_BASELINE AS (
SELECT
	RMS_SKU_NUM
	, PRICE_STORE_NUM as STORE_NUM
	, CURRENT_PRICE_TYPE as PRICE_TYPE
	, ORDER_DATE_PACIFIC
	, CHANNEL_COUNTRY
    , CHANNEL_BRAND
    , CURRENT_PRICE_AMT as CURRENT_PRICE
    , REGULAR_PRICE_AMT as REGULAR_PRICE
    , SUM(ORDER_LINE_QUANTITY) as BACKORDER_UNITS
    , SUM(ORDER_LINE_AMOUNT) as BACKORDER_DOLLARS
    , SUM(case when CURRENT_BACKORDER_FLAG = 'Y' then ORDER_LINE_QUANTITY else 0 end) as CURRENT_BACKORDER_UNITS
    , SUM(case when CURRENT_BACKORDER_FLAG = 'Y' then ORDER_LINE_AMOUNT else 0 end) as CURRENT_BACKORDER_DOLLARS
FROM BACKORDER_BASE_02
GROUP BY 1,2,3,4,5,6,7,8
) with data primary index(RMS_SKU_NUM, STORE_NUM, PRICE_TYPE, ORDER_DATE_PACIFIC, CURRENT_PRICE) on commit preserve rows
;

COLLECT STATS
	 PRIMARY INDEX (RMS_SKU_NUM, STORE_NUM, PRICE_TYPE, ORDER_DATE_PACIFIC, CURRENT_PRICE)
	,COLUMN (RMS_SKU_NUM)
		ON FINAL_BASELINE;

-- Update or insert records based on existing or new
MERGE INTO
T2DL_DAS_ACE_MFP.SKU_BO_HISTORY AS a
USING
FINAL_BASELINE AS b
ON
	a.RMS_SKU_NUM = b.RMS_SKU_NUM
	AND a.STORE_NUM = b.STORE_NUM
	AND a.ORDER_DATE_PACIFIC = b.ORDER_DATE_PACIFIC
	AND a.PRICE_TYPE = b.PRICE_TYPE
	AND a.CURRENT_PRICE = b.CURRENT_PRICE
	AND a.REGULAR_PRICE = b.REGULAR_PRICE

WHEN MATCHED
THEN UPDATE
	SET
		 CHANNEL_COUNTRY = b.CHANNEL_COUNTRY
		, CHANNEL_BRAND = b.CHANNEL_BRAND
		, BACKORDER_UNITS = b.BACKORDER_UNITS
		, BACKORDER_DOLLARS = b.BACKORDER_DOLLARS
		, CURRENT_BACKORDER_UNITS = b.CURRENT_BACKORDER_UNITS
		, CURRENT_BACKORDER_DOLLARS = b.CURRENT_BACKORDER_DOLLARS

WHEN NOT MATCHED
THEN INSERT
	VALUES
	(
	b.RMS_SKU_NUM
	, b.STORE_NUM
	, b.PRICE_TYPE
	, b.ORDER_DATE_PACIFIC
	, b.CURRENT_PRICE
	, b.REGULAR_PRICE
	, b.CHANNEL_COUNTRY
	, b.CHANNEL_BRAND
	, b.BACKORDER_UNITS
	, b.BACKORDER_DOLLARS
	, b.CURRENT_BACKORDER_UNITS
	, b.CURRENT_BACKORDER_DOLLARS
	)
;
