-- 2021.12.10 - DDL Creation for the CRM Cost staging dataset
CREATE MULTISET TABLE T3DL_ACE_MCH.CP_REF_CRM_COST_STG ,FALLBACK ,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1,
     LOG
     (
	 platform VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 business_date VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 channel VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 channel_01 VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 channel_02 VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 cost_value VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 contract_start VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 contract_end VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 update_dt VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
	 process_dt VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC)
PRIMARY INDEX ( platform );	