
CREATE MULTISET TABLE T2DL_DAS_ACE_MFP.SKU_BO_HISTORY
    , FALLBACK
    , NO BEFORE JOURNAL
    , NO AFTER JOURNAL
    , CHECKSUM = DEFAULT
    , DEFAULT MERGEBLOCKRATIO
    , MAP = TD_MAP1
(
	RMS_SKU_NUM            		VARCHAR(16) CHARACTER SET UNICODE NOT CASESPECIFIC
	,STORE_NUM					INTEGER NOT NULL
	,PRICE_TYPE 				VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,ORDER_DATE_PACIFIC	      	DATE FORMAT 'YYYY-MM-DD'
    ,CURRENT_PRICE 				DECIMAL(12,2)
	,REGULAR_PRICE 				DECIMAL(12,2)
    ,CHANNEL_COUNTRY          	VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('US','CA')
    ,CHANNEL_BRAND            	VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('NORDSTROM', 'NORDSTROM_RACK')
    ,BACKORDER_UNITS     		INTEGER NOT NULL
    ,BACKORDER_DOLLARS        	DECIMAL(12,2)
    ,CURRENT_BACKORDER_UNITS 	INTEGER NOT NULL
    ,CURRENT_BACKORDER_DOLLARS 	DECIMAL(12,2)
    
)
PRIMARY INDEX (RMS_SKU_NUM, STORE_NUM, PRICE_TYPE, ORDER_DATE_PACIFIC)

PARTITION BY RANGE_N(ORDER_DATE_PACIFIC BETWEEN DATE '2011-01-01' AND DATE '2031-12-31' EACH INTERVAL '1' DAY , NO RANGE)
;