/* Purpose: Create single look-up for sustainable style groups
    info is based on a current hard-coded list of static keywords
*/


replace view t2dl_das_selection.sustainable_style_vw
as
lock row for access

select
    distinct strtok(rms_style_num, '_', 1) as style_group_num
from prd_nap_usr_vws.product_style_copy_dim
where
    features_desc like '%Sustainably Sourced%'
    or features_desc like '%30 recycled%'
    or features_desc like '%Certified recycled%'
    or features_desc like '%REPREVE%'
    or features_desc like '%recycled down%'
    or features_desc like '%Recover%'
    or features_desc like '%Nike Grind%'
    or features_desc like '%ReBOTL%'
    or features_desc like '%Nature Tex%'
    or features_desc like '%EcoPlume%'
    or features_desc like '%EcoSure%'
    or features_desc like '%Degradable Denim%'
    or features_desc like '%bluesign%'
    or features_desc like '%Butterfly Mark%'
    or features_desc like '%ChromeFree%'
    or features_desc like '%ECONYL%'
    or features_desc like '%Fair Trade%'
    or features_desc like '%Forest Stewardship%'
    or features_desc like '%Global Recycled%'
    or features_desc like '%Traceable Down%'
    or features_desc like '%Lab-created%'
    or features_desc like '%Lenzing EcoVero%'
    or features_desc like '%Livaeco%'
    or features_desc like '%EcoMade%'
    or features_desc like '%Naia%'
    or features_desc like '%Organic Content Standard%'
    or features_desc like '%Parley Ocean%'
    or features_desc like '%Recyc Leather%'
    or features_desc like '%Refibra lyocell%'
    or features_desc like '%Responsible Alpaca%'
    or features_desc like '%Responsible Down%'
    or features_desc like '%Responsible Jewellery%'
    or features_desc like '%Responsible Mohair%'
    or features_desc like '%Responsible Wool%'
    or features_desc like '%SeaCell%'
    or features_desc like '%Tencel lyocell%'
    or features_desc like '%Tencel modal%'
    or features_desc like '%VILOFT%'
    or features_desc like '%Better Work%'
    or features_desc like '%women-worker%'
    or features_desc like '%Cradle to Cradle%'
    or features_desc like '%Fair Labor%'
    or features_desc like '%Leather Working Group%'
    or features_desc like '%OEKO-TEX%'
    or features_desc like '%Fair Trade–Certified%'
    or features_desc like '%for the Planet%'
    or features_desc like '%3 Brand will donate%'
    or features_desc like '%Akola Project%'
    or features_desc like '%Circle of Life%'
    or features_desc like '%Wildlife Trust%'
    or features_desc like '%Project Soar%'
    or features_desc like '%AS by DF%'
    or features_desc like '%Balenciaga will donate%'
    or features_desc like '%Beek will donate%'
    or features_desc like '%Bella Tunno partners%'
    or features_desc like '%Trans Lifeline%'
    or features_desc like '%Bombas will donate%'
    or features_desc like '%Sightsavers%'
    or features_desc like '%support Polar%' 
    or features_desc like '%DIFF Eyewear%'
    or features_desc like '%Trees for the Future%'
    or features_desc like '%Why Not You Foundation%'
    or features_desc like '%Bamboo Villages%'
    or features_desc like '%Nura Friendship%'
    or features_desc like '%Make Your Voice Heard%'
    or features_desc like '%Empower One%'
    or features_desc like '%environmental solutions%'
    or features_desc like '%rePurpose Global%'
    or features_desc like '%Room Service%'
    or features_desc like '%Spiritual Gangster%'
    or features_desc like '%tentree%'
    or features_desc like '%Natural Park Foundation%'
    or features_desc like '%grassroots efforts%'
    or features_desc like '%Certified B Corporation%'
    or features_desc like '%empower youth%'
    or features_desc like '%Biglife in Kenya%'
    or features_desc like '%Responsible Packaging%'
    or features_desc like '%Nordstrom Sustainably%'
    or features_desc like '%cruelty-free%'
;
