CALL SYS_MGMT.DROP_IF_EXISTS_SP ('T3DL_ACE_ASSORTMENT', 'OUTSIDE_APP_TEST', OUT_RETURN_MSG);

CREATE MULTISET TABLE T3DL_ACE_ASSORTMENT.OUTSIDE_APP_TEST,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      Department VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC,
      Banner VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC
      )
PRIMARY INDEX (Department,Banner);

DELETE FROM T3DL_ACE_ASSORTMENT.OUTSIDE_APP_TEST;

INSERT INTO T3DL_ACE_ASSORTMENT.OUTSIDE_APP_TEST
SELECT DISTINCT 
    Department
    ,Banner
FROM T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT;
