

CREATE TEMPORARY TABLE IF NOT EXISTS customer_demographic_tmp AS
SELECT acp_id,
 id,
 birth_year_and_month,
 age_type,
 age_value,
 gender,
 martial_status,
 education_model_likelihood,
 occupation_type,
 retail_shopper_type,
 truetouch_strategy_brand_loyalists_likelihood,
 truetouch_strategy_deal_seekers_likelihood,
 truetouch_strategy_moment_shoppers_likelihood,
 truetouch_strategy_mainstream_adopters_likelihood,
 truetouch_strategy_novelty_seekers_likelihood,
 truetouch_strategy_organic_and_natural_likelihood,
 truetouch_strategy_quality_matters_likelihood,
 truetouch_strategy_recreational_shoppers_likelihood,
 truetouch_strategy_savvy_researchers_likelihood,
 truetouch_strategy_trendsetters_likelihood,
 is_new_home_owner_last_twenty_four_months,
 is_new_home_owner_last_twelve_months,
 is_new_mover_last_twelve_months,
 is_new_parent_last_thirty_six_months,
 household_adult_count,
 household_children_count,
 household_person_count,
 household_child_presence_likelihood,
 household_estimated_income_state_index,
 household_estimated_income_national_percentile,
 household_estimated_income_amount_in_thousands,
 household_estimated_income_range,
 household_discretionary_spend_estimate_spend_on_apparel,
 household_discretionary_spend_estimate_score,
 household_discretionary_spend_estimate_level,
 household_buyer_loyalty_card_user_likelihood_rank_asc,
 household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
 household_buyer_luxury_store_shoppers_likelihood_rank_asc,
 household_buyer_prestige_makeup_user_likelihood_rank_asc,
 household_buyer_super_center_shopper_likelihood_rank_asc,
 household_buyer_warehouse_club_member_likelihood_rank_asc,
 household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
 household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
 household_buyer_online_accessories_propensity_model_rank_desc,
 household_buyer_online_apparel_propensity_model_rank_desc,
 household_buyer_online_overall_propensity_model_rank_desc,
 household_buyer_online_shoe_propensity_model_rank_desc,
 household_buyer_retail_accessories_propensity_model_rank_desc,
 household_buyer_retail_apparel_propensity_model_rank_desc,
 household_buyer_retail_overall_propensity_model_rank_desc,
 household_buyer_retail_shoes_propensity_model_rank_desc,
 household_mosaic_lifestyle_segment,
 match_level,
 match_address,
 social_media_predictions_new_job_likelihood,
 social_media_predictions_facebook_usage_likelihood,
 social_media_predictions_instagram_usage_likelihood,
 social_media_predictions_pinterest_usage_likelihood,
 social_media_predictions_linkedin_usage_likelihood,
 social_media_predictions_twitter_usage_likelihood,
 social_media_predictions_snapchat_usage_likelihood,
 social_media_predictions_youtube_usage_likelihood,
 `{{params.project_id}}.nord_udf.epoch_tmstp`(CAST(object_system_time AS BIGINT)) AS object_sys_time
FROM {{params.project_id}}.{{params.dbenv}}_nap_cust_base_vws.customer_experian_demographic_prediction_ldg
QUALIFY (ROW_NUMBER() OVER (PARTITION BY acp_id ORDER BY `{{params.project_id}}.nord_udf.epoch_tmstp`(CAST(object_system_time AS BIGINT)) DESC)
  ) = 1;

-- EXCEPTION WHEN ERROR THEN
-- SET _ERROR_CODE  =  1;
-- SET _ERROR_MESSAGE  =  @@error.message;
-- END;

/*.IF ERRORCODE <> 0 THEN .QUIT 1*/
BEGIN TRANSACTION;

TRUNCATE TABLE {{params.project_id}}.{{params.dbenv}}_nap_cust_dim.customer_experian_demographic_prediction_dim;
/*.IF ERRORCODE <> 0 THEN .QUIT 2*/

INSERT INTO {{params.project_id}}.{{params.dbenv}}_nap_cust_dim.customer_experian_demographic_prediction_dim
(SELECT acp_id,
  id,
  birth_year_and_month,
  age_type,
  CAST(FLOOR(CAST(age_value AS FLOAT64)) AS INTEGER) AS age_value,
  gender,
  martial_status,
  education_model_likelihood,
  occupation_type,
  retail_shopper_type,
  truetouch_strategy_brand_loyalists_likelihood,
  truetouch_strategy_deal_seekers_likelihood,
  truetouch_strategy_moment_shoppers_likelihood,
  truetouch_strategy_mainstream_adopters_likelihood,
  truetouch_strategy_novelty_seekers_likelihood,
  truetouch_strategy_organic_and_natural_likelihood,
  truetouch_strategy_quality_matters_likelihood,
  truetouch_strategy_recreational_shoppers_likelihood,
  truetouch_strategy_savvy_researchers_likelihood,
  truetouch_strategy_trendsetters_likelihood,
  is_new_home_owner_last_twenty_four_months,
  is_new_home_owner_last_twelve_months,
  is_new_mover_last_twelve_months,
  is_new_parent_last_thirty_six_months,
  CAST(FLOOR(CAST(household_adult_count AS FLOAT64)) AS INTEGER) AS household_adult_count,
  CAST(FLOOR(CAST(household_children_count AS FLOAT64)) AS INTEGER) AS household_children_count,
  CAST(FLOOR(CAST(household_person_count AS FLOAT64)) AS INTEGER) AS household_person_count,
  household_child_presence_likelihood,
  household_estimated_income_state_index,
  household_estimated_income_national_percentile,
  household_estimated_income_amount_in_thousands,
  household_estimated_income_range,
  household_discretionary_spend_estimate_spend_on_apparel,
  household_discretionary_spend_estimate_score,
  household_discretionary_spend_estimate_level,
  household_buyer_loyalty_card_user_likelihood_rank_asc,
  household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
  household_buyer_luxury_store_shoppers_likelihood_rank_asc,
  household_buyer_prestige_makeup_user_likelihood_rank_asc,
  household_buyer_super_center_shopper_likelihood_rank_asc,
  household_buyer_warehouse_club_member_likelihood_rank_asc,
  household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
  household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
  household_buyer_online_accessories_propensity_model_rank_desc,
  household_buyer_online_apparel_propensity_model_rank_desc,
  household_buyer_online_overall_propensity_model_rank_desc,
  household_buyer_online_shoe_propensity_model_rank_desc,
  household_buyer_retail_accessories_propensity_model_rank_desc,
  household_buyer_retail_apparel_propensity_model_rank_desc,
  household_buyer_retail_overall_propensity_model_rank_desc,
  household_buyer_retail_shoes_propensity_model_rank_desc,
  household_mosaic_lifestyle_segment,
  match_level,
  match_address,
  CAST(object_sys_time AS DATETIME) AS object_sys_time,
   (SELECT curr_batch_date
   FROM {{params.project_id}}.{{params.dbenv}}_nap_cust_base_vws.elt_control
   WHERE LOWER(subject_area_nm) = LOWER('CUSTOMER_DEMOGRAPHIC')) AS dw_batch_date,
  CURRENT_DATETIME('PST8PDT')  AS dw_sys_load_tmstp,
  CURRENT_DATETIME('PST8PDT')  AS dw_sys_updt_tmstp,
  social_media_predictions_new_job_likelihood,
  social_media_predictions_facebook_usage_likelihood,
  social_media_predictions_instagram_usage_likelihood,
  social_media_predictions_pinterest_usage_likelihood,
  social_media_predictions_linkedin_usage_likelihood,
  social_media_predictions_twitter_usage_likelihood,
  social_media_predictions_snapchat_usage_likelihood,
  social_media_predictions_youtube_usage_likelihood
 FROM customer_demographic_tmp);

COMMIT TRANSACTION;
