
CREATE TEMPORARY TABLE IF NOT EXISTS customer_demographic_tmp
CLUSTER BY acp_id
AS
SELECT acp_id,
 id,
 birth_year_and_month,
 age_type,
 age_value,
 gender,
 martial_status,
 education_model_likelihood,
 occupation_type,
 retail_shopper_type,
 truetouch_strategy_brand_loyalists_likelihood,
 truetouch_strategy_deal_seekers_likelihood,
 truetouch_strategy_moment_shoppers_likelihood,
 truetouch_strategy_mainstream_adopters_likelihood,
 truetouch_strategy_novelty_seekers_likelihood,
 truetouch_strategy_organic_and_natural_likelihood,
 truetouch_strategy_quality_matters_likelihood,
 truetouch_strategy_recreational_shoppers_likelihood,
 truetouch_strategy_savvy_researchers_likelihood,
 truetouch_strategy_trendsetters_likelihood,
 is_new_home_owner_last_twenty_four_months,
 is_new_home_owner_last_twelve_months,
 is_new_mover_last_twelve_months,
 is_new_parent_last_thirty_six_months,
 household_adult_count,
 household_children_count,
 household_person_count,
 household_child_presence_likelihood,
 household_estimated_income_state_index,
 household_estimated_income_national_percentile,
 household_estimated_income_amount_in_thousands,
 household_estimated_income_range,
 household_discretionary_spend_estimate_spend_on_apparel,
 household_discretionary_spend_estimate_score,
 household_discretionary_spend_estimate_level,
 household_buyer_loyalty_card_user_likelihood_rank_asc,
 household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
 household_buyer_luxury_store_shoppers_likelihood_rank_asc,
 household_buyer_prestige_makeup_user_likelihood_rank_asc,
 household_buyer_super_center_shopper_likelihood_rank_asc,
 household_buyer_warehouse_club_member_likelihood_rank_asc,
 household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
 household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
 household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
 household_buyer_online_accessories_propensity_model_rank_desc,
 household_buyer_online_apparel_propensity_model_rank_desc,
 household_buyer_online_overall_propensity_model_rank_desc,
 household_buyer_online_shoe_propensity_model_rank_desc,
 household_buyer_retail_accessories_propensity_model_rank_desc,
 household_buyer_retail_apparel_propensity_model_rank_desc,
 household_buyer_retail_overall_propensity_model_rank_desc,
 household_buyer_retail_shoes_propensity_model_rank_desc,
 household_mosaic_lifestyle_segment,
 match_level,
 match_address,
 social_media_predictions_new_job_likelihood,
 social_media_predictions_facebook_usage_likelihood,
 social_media_predictions_instagram_usage_likelihood,
 social_media_predictions_pinterest_usage_likelihood,
 social_media_predictions_linkedin_usage_likelihood,
 social_media_predictions_twitter_usage_likelihood,
 social_media_predictions_snapchat_usage_likelihood,
 social_media_predictions_youtube_usage_likelihood,
 `{{params.project_id}}.nord_udf.epoch_tmstp`(CAST(object_system_time AS BIGINT)) AS object_sys_time
FROM {{params.project_id}}.{{params.dbenv}}_nap_cust_base_vws.customer_experian_demographic_prediction_ldg
QUALIFY (ROW_NUMBER() OVER (PARTITION BY acp_id ORDER BY `{{params.project_id}}.nord_udf.epoch_tmstp`(CAST(object_system_time AS BIGINT)) DESC)
  ) = 1;

/*.IF ERRORCODE <> 0 THEN .QUIT 1*/
BEGIN TRANSACTION;


MERGE INTO {{params.project_id}}.{{params.dbenv}}_nap_cust_dim.customer_experian_demographic_prediction_dim dim
USING(
  SELECT
    acp_id,
    id,
    birth_year_and_month,
    age_type,
    age_value,
    gender,
    martial_status,
    education_model_likelihood,
    occupation_type,
    retail_shopper_type,
    truetouch_strategy_brand_loyalists_likelihood,
    truetouch_strategy_deal_seekers_likelihood,
    truetouch_strategy_moment_shoppers_likelihood,
    truetouch_strategy_mainstream_adopters_likelihood,
    truetouch_strategy_novelty_seekers_likelihood,
    truetouch_strategy_organic_and_natural_likelihood,
    truetouch_strategy_quality_matters_likelihood,
    truetouch_strategy_recreational_shoppers_likelihood,
    truetouch_strategy_savvy_researchers_likelihood,
    truetouch_strategy_trendsetters_likelihood,
    is_new_home_owner_last_twenty_four_months,
    is_new_home_owner_last_twelve_months,
    is_new_mover_last_twelve_months,
    is_new_parent_last_thirty_six_months,
    household_adult_count,
    household_children_count,
    household_person_count,
    household_child_presence_likelihood,
    household_estimated_income_state_index,
    household_estimated_income_national_percentile,
    household_estimated_income_amount_in_thousands,
    household_estimated_income_range,
    household_discretionary_spend_estimate_spend_on_apparel,
    household_discretionary_spend_estimate_score,
    household_discretionary_spend_estimate_level,
    household_buyer_loyalty_card_user_likelihood_rank_asc,
    household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
    household_buyer_luxury_store_shoppers_likelihood_rank_asc,
    household_buyer_prestige_makeup_user_likelihood_rank_asc,
    household_buyer_super_center_shopper_likelihood_rank_asc,
    household_buyer_warehouse_club_member_likelihood_rank_asc,
    household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
    household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
    household_buyer_online_accessories_propensity_model_rank_desc,
    household_buyer_online_apparel_propensity_model_rank_desc,
    household_buyer_online_overall_propensity_model_rank_desc,
    household_buyer_online_shoe_propensity_model_rank_desc,
    household_buyer_retail_accessories_propensity_model_rank_desc,
    household_buyer_retail_apparel_propensity_model_rank_desc,
    household_buyer_retail_overall_propensity_model_rank_desc,
    household_buyer_retail_shoes_propensity_model_rank_desc,
    household_mosaic_lifestyle_segment,
    match_level,
    match_address,
    social_media_predictions_new_job_likelihood,
    social_media_predictions_facebook_usage_likelihood,
    social_media_predictions_instagram_usage_likelihood,
    social_media_predictions_pinterest_usage_likelihood,
    social_media_predictions_linkedin_usage_likelihood,
    social_media_predictions_twitter_usage_likelihood,
    social_media_predictions_snapchat_usage_likelihood,
    social_media_predictions_youtube_usage_likelihood,
    object_sys_time,
    ( SELECT CURR_BATCH_DATE
      FROM {{params.project_id}}.{{params.dbenv}}_NAP_CUST_BASE_VWS.ELT_CONTROL
      WHERE lower(subject_area_nm) = lower('CUSTOMER_DEMOGRAPHIC')
    ) as dw_batch_date
  FROM customer_demographic_tmp
) ldg_tmp ON lower(dim.acp_id) = lower(ldg_tmp.acp_id)
WHEN MATCHED THEN
UPDATE
SET
  id = ldg_tmp.id,
  birth_year_and_month = ldg_tmp.birth_year_and_month,
  age_type = ldg_tmp.age_type,
  age_value = CAST(FLOOR(CAST(ldg_tmp.age_value AS FLOAT64)) as INTEGER),
  gender = ldg_tmp.gender,
  martial_status = ldg_tmp.martial_status,
  education_model_likelihood = ldg_tmp.education_model_likelihood,
  occupation_type = ldg_tmp.occupation_type,
  retail_shopper_type = ldg_tmp.retail_shopper_type,
  truetouch_strategy_brand_loyalists_likelihood = ldg_tmp.truetouch_strategy_brand_loyalists_likelihood,
  truetouch_strategy_deal_seekers_likelihood = ldg_tmp.truetouch_strategy_deal_seekers_likelihood,
  truetouch_strategy_moment_shoppers_likelihood = ldg_tmp.truetouch_strategy_moment_shoppers_likelihood,
  truetouch_strategy_mainstream_adopters_likelihood = ldg_tmp.truetouch_strategy_mainstream_adopters_likelihood,
  truetouch_strategy_novelty_seekers_likelihood = ldg_tmp.truetouch_strategy_novelty_seekers_likelihood,
  truetouch_strategy_organic_and_natural_likelihood = ldg_tmp.truetouch_strategy_organic_and_natural_likelihood,
  truetouch_strategy_quality_matters_likelihood = ldg_tmp.truetouch_strategy_quality_matters_likelihood,
  truetouch_strategy_recreational_shoppers_likelihood = ldg_tmp.truetouch_strategy_recreational_shoppers_likelihood,
  truetouch_strategy_savvy_researchers_likelihood = ldg_tmp.truetouch_strategy_savvy_researchers_likelihood,
  truetouch_strategy_trendsetters_likelihood = ldg_tmp.truetouch_strategy_trendsetters_likelihood,
  is_new_home_owner_last_twenty_four_months = ldg_tmp.is_new_home_owner_last_twenty_four_months,
  is_new_home_owner_last_twelve_months = ldg_tmp.is_new_home_owner_last_twelve_months,
  is_new_mover_last_twelve_months = ldg_tmp.is_new_mover_last_twelve_months,
  is_new_parent_last_thirty_six_months = ldg_tmp.is_new_parent_last_thirty_six_months,
  household_adult_count = CAST(FLOOR(CAST(ldg_tmp.household_adult_count AS FLOAT64)) AS INTEGER),
  household_children_count = CAST(FLOOR(CAST(ldg_tmp.household_children_count AS FLOAT64)) as INTEGER),
  household_person_count = CAST(FLOOR(CAST(ldg_tmp.household_person_count AS FLOAT64)) AS INTEGER),
  household_child_presence_likelihood = ldg_tmp.household_child_presence_likelihood,
  household_estimated_income_state_index = ldg_tmp.household_estimated_income_state_index,
  household_estimated_income_national_percentile = ldg_tmp.household_estimated_income_national_percentile,
  household_estimated_income_amount_in_thousands = ldg_tmp.household_estimated_income_amount_in_thousands,
  household_estimated_income_range = ldg_tmp.household_estimated_income_range,
  household_discretionary_spend_estimate_spend_on_apparel = ldg_tmp.household_discretionary_spend_estimate_spend_on_apparel,
  household_discretionary_spend_estimate_score = ldg_tmp.household_discretionary_spend_estimate_score,
  household_discretionary_spend_estimate_level = ldg_tmp.household_discretionary_spend_estimate_level,
  household_buyer_loyalty_card_user_likelihood_rank_asc = ldg_tmp.household_buyer_loyalty_card_user_likelihood_rank_asc,
  household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc = ldg_tmp.household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
  household_buyer_luxury_store_shoppers_likelihood_rank_asc = ldg_tmp.household_buyer_luxury_store_shoppers_likelihood_rank_asc,
  household_buyer_prestige_makeup_user_likelihood_rank_asc = ldg_tmp.household_buyer_prestige_makeup_user_likelihood_rank_asc,
  household_buyer_super_center_shopper_likelihood_rank_asc = ldg_tmp.household_buyer_super_center_shopper_likelihood_rank_asc,
  household_buyer_warehouse_club_member_likelihood_rank_asc = ldg_tmp.household_buyer_warehouse_club_member_likelihood_rank_asc,
  household_buyer_young_adult_clothing_shopper_likelihood_rank_asc = ldg_tmp.household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
  household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc = ldg_tmp.household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc = ldg_tmp.household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc = ldg_tmp.household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc = ldg_tmp.household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
  household_buyer_consumer_expenditure_toys_propensity_model_rank_desc = ldg_tmp.household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
  household_buyer_online_accessories_propensity_model_rank_desc = ldg_tmp.household_buyer_online_accessories_propensity_model_rank_desc,
  household_buyer_online_apparel_propensity_model_rank_desc = ldg_tmp.household_buyer_online_apparel_propensity_model_rank_desc,
  household_buyer_online_overall_propensity_model_rank_desc = ldg_tmp.household_buyer_online_overall_propensity_model_rank_desc,
  household_buyer_online_shoe_propensity_model_rank_desc = ldg_tmp.household_buyer_online_shoe_propensity_model_rank_desc,
  household_buyer_retail_accessories_propensity_model_rank_desc = ldg_tmp.household_buyer_retail_accessories_propensity_model_rank_desc,
  household_buyer_retail_apparel_propensity_model_rank_desc = ldg_tmp.household_buyer_retail_apparel_propensity_model_rank_desc,
  household_buyer_retail_overall_propensity_model_rank_desc = ldg_tmp.household_buyer_retail_overall_propensity_model_rank_desc,
  household_buyer_retail_shoes_propensity_model_rank_desc = ldg_tmp.household_buyer_retail_shoes_propensity_model_rank_desc,
  household_mosaic_lifestyle_segment = ldg_tmp.household_mosaic_lifestyle_segment,
  match_level = ldg_tmp.match_level,
  match_address = ldg_tmp.match_address,
  social_media_predictions_new_job_likelihood = ldg_tmp.social_media_predictions_new_job_likelihood,
  social_media_predictions_facebook_usage_likelihood = ldg_tmp.social_media_predictions_facebook_usage_likelihood,
  social_media_predictions_instagram_usage_likelihood = ldg_tmp.social_media_predictions_instagram_usage_likelihood,
  social_media_predictions_pinterest_usage_likelihood = ldg_tmp.social_media_predictions_pinterest_usage_likelihood,
  social_media_predictions_linkedin_usage_likelihood = ldg_tmp.social_media_predictions_linkedin_usage_likelihood,
  social_media_predictions_twitter_usage_likelihood = ldg_tmp.social_media_predictions_twitter_usage_likelihood,
  social_media_predictions_snapchat_usage_likelihood = ldg_tmp.social_media_predictions_snapchat_usage_likelihood,
  social_media_predictions_youtube_usage_likelihood = ldg_tmp.social_media_predictions_youtube_usage_likelihood,
  object_system_time = CAST(ldg_tmp.object_sys_time AS DATETIME),
  dw_batch_date = ldg_tmp.dw_batch_date,
  dw_sys_load_tmstp = dim.dw_sys_load_tmstp,
  dw_sys_updt_tmstp =  current_datetime('PST8PDT')
WHEN NOT MATCHED THEN
INSERT (
    acp_id,
    id,
    birth_year_and_month,
    age_type,
    age_value,
    gender,
    martial_status,
    education_model_likelihood,
    occupation_type,
    retail_shopper_type,
    truetouch_strategy_brand_loyalists_likelihood,
    truetouch_strategy_deal_seekers_likelihood,
    truetouch_strategy_moment_shoppers_likelihood,
    truetouch_strategy_mainstream_adopters_likelihood,
    truetouch_strategy_novelty_seekers_likelihood,
    truetouch_strategy_organic_and_natural_likelihood,
    truetouch_strategy_quality_matters_likelihood,
    truetouch_strategy_recreational_shoppers_likelihood,
    truetouch_strategy_savvy_researchers_likelihood,
    truetouch_strategy_trendsetters_likelihood,
    is_new_home_owner_last_twenty_four_months,
    is_new_home_owner_last_twelve_months,
    is_new_mover_last_twelve_months,
    is_new_parent_last_thirty_six_months,
    household_adult_count,
    household_children_count,
    household_person_count,
    household_child_presence_likelihood,
    household_estimated_income_state_index,
    household_estimated_income_national_percentile,
    household_estimated_income_amount_in_thousands,
    household_estimated_income_range,
    household_discretionary_spend_estimate_spend_on_apparel,
    household_discretionary_spend_estimate_score,
    household_discretionary_spend_estimate_level,
    household_buyer_loyalty_card_user_likelihood_rank_asc,
    household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
    household_buyer_luxury_store_shoppers_likelihood_rank_asc,
    household_buyer_prestige_makeup_user_likelihood_rank_asc,
    household_buyer_super_center_shopper_likelihood_rank_asc,
    household_buyer_warehouse_club_member_likelihood_rank_asc,
    household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
    household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
    household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
    household_buyer_online_accessories_propensity_model_rank_desc,
    household_buyer_online_apparel_propensity_model_rank_desc,
    household_buyer_online_overall_propensity_model_rank_desc,
    household_buyer_online_shoe_propensity_model_rank_desc,
    household_buyer_retail_accessories_propensity_model_rank_desc,
    household_buyer_retail_apparel_propensity_model_rank_desc,
    household_buyer_retail_overall_propensity_model_rank_desc,
    household_buyer_retail_shoes_propensity_model_rank_desc,
    household_mosaic_lifestyle_segment,
    match_level,
    match_address,
    social_media_predictions_new_job_likelihood,
    social_media_predictions_facebook_usage_likelihood,
    social_media_predictions_instagram_usage_likelihood,
    social_media_predictions_pinterest_usage_likelihood,
    social_media_predictions_linkedin_usage_likelihood,
    social_media_predictions_twitter_usage_likelihood,
    social_media_predictions_snapchat_usage_likelihood,
    social_media_predictions_youtube_usage_likelihood,
    object_system_time,
    dw_batch_date,
    dw_sys_load_tmstp,
    dw_sys_updt_tmstp
  )
VALUES
  (
    ldg_tmp.acp_id,
    ldg_tmp.id,
    ldg_tmp.birth_year_and_month,
    ldg_tmp.age_type,
    CAST(FLOOR(CAST(ldg_tmp.age_value AS FLOAT64)) AS INTEGER),
    ldg_tmp.gender,
    ldg_tmp.martial_status,
    ldg_tmp.education_model_likelihood,
    ldg_tmp.occupation_type,
    ldg_tmp.retail_shopper_type,
    ldg_tmp.truetouch_strategy_brand_loyalists_likelihood,
    ldg_tmp.truetouch_strategy_deal_seekers_likelihood,
    ldg_tmp.truetouch_strategy_moment_shoppers_likelihood,
    ldg_tmp.truetouch_strategy_mainstream_adopters_likelihood,
    ldg_tmp.truetouch_strategy_novelty_seekers_likelihood,
    ldg_tmp.truetouch_strategy_organic_and_natural_likelihood,
    ldg_tmp.truetouch_strategy_quality_matters_likelihood,
    ldg_tmp.truetouch_strategy_recreational_shoppers_likelihood,
    ldg_tmp.truetouch_strategy_savvy_researchers_likelihood,
    ldg_tmp.truetouch_strategy_trendsetters_likelihood,
    ldg_tmp.is_new_home_owner_last_twenty_four_months,
    ldg_tmp.is_new_home_owner_last_twelve_months,
    ldg_tmp.is_new_mover_last_twelve_months,
    ldg_tmp.is_new_parent_last_thirty_six_months,
    CAST(FLOOR(CAST(ldg_tmp.household_adult_count AS FLOAT64)) AS INTEGER),
    CAST(FLOOR(CAST(ldg_tmp.household_children_count AS FLOAT64)) AS INTEGER),
    CAST(FLOOR(CAST(ldg_tmp.household_person_count AS FLOAT64)) AS INTEGER),
    ldg_tmp.household_child_presence_likelihood,
    ldg_tmp.household_estimated_income_state_index,
    ldg_tmp.household_estimated_income_national_percentile,
    ldg_tmp.household_estimated_income_amount_in_thousands,
    ldg_tmp.household_estimated_income_range,
    ldg_tmp.household_discretionary_spend_estimate_spend_on_apparel,
    ldg_tmp.household_discretionary_spend_estimate_score,
    ldg_tmp.household_discretionary_spend_estimate_level,
    ldg_tmp.household_buyer_loyalty_card_user_likelihood_rank_asc,
    ldg_tmp.household_buyer_luxury_home_goods_store_shopper_likelihood_rank_asc,
    ldg_tmp.household_buyer_luxury_store_shoppers_likelihood_rank_asc,
    ldg_tmp.household_buyer_prestige_makeup_user_likelihood_rank_asc,
    ldg_tmp.household_buyer_super_center_shopper_likelihood_rank_asc,
    ldg_tmp.household_buyer_warehouse_club_member_likelihood_rank_asc,
    ldg_tmp.household_buyer_young_adult_clothing_shopper_likelihood_rank_asc,
    ldg_tmp.household_buyer_consumer_expenditure_accessories_propensity_model_rank_desc,
    ldg_tmp.household_buyer_consumer_expenditure_apparel_propensity_model_rank_desc,
    ldg_tmp.household_buyer_consumer_expenditure_homedecor_propensity_model_rank_desc,
    ldg_tmp.household_buyer_consumer_expenditure_shoes_propensity_model_rank_desc,
    ldg_tmp.household_buyer_consumer_expenditure_toys_propensity_model_rank_desc,
    ldg_tmp.household_buyer_online_accessories_propensity_model_rank_desc,
    ldg_tmp.household_buyer_online_apparel_propensity_model_rank_desc,
    ldg_tmp.household_buyer_online_overall_propensity_model_rank_desc,
    ldg_tmp.household_buyer_online_shoe_propensity_model_rank_desc,
    ldg_tmp.household_buyer_retail_accessories_propensity_model_rank_desc,
    ldg_tmp.household_buyer_retail_apparel_propensity_model_rank_desc,
    ldg_tmp.household_buyer_retail_overall_propensity_model_rank_desc,
    ldg_tmp.household_buyer_retail_shoes_propensity_model_rank_desc,
    ldg_tmp.household_mosaic_lifestyle_segment,
    ldg_tmp.match_level,
    ldg_tmp.match_address,
    ldg_tmp.social_media_predictions_new_job_likelihood,
    ldg_tmp.social_media_predictions_facebook_usage_likelihood,
    ldg_tmp.social_media_predictions_instagram_usage_likelihood,
    ldg_tmp.social_media_predictions_pinterest_usage_likelihood,
    ldg_tmp.social_media_predictions_linkedin_usage_likelihood,
    ldg_tmp.social_media_predictions_twitter_usage_likelihood,
    ldg_tmp.social_media_predictions_snapchat_usage_likelihood,
    ldg_tmp.social_media_predictions_youtube_usage_likelihood,
    CAST(ldg_tmp.object_sys_time AS DATETIME),
    ldg_tmp.dw_batch_date,
    current_datetime('PST8PDT'),
    current_datetime('PST8PDT')
  );

  COMMIT TRANSACTION;



