

CALL `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_UTL.DATA_TIMELINESS_METRIC_FACT_LD('PRODUCT_PRICE_TIMELINE_DIM',  '{{params.dbenv}}_NAP_DIM',  'TECH_Merch_NAP_PRICE_AND_PROMOTION_INCREMENTAL_LOAD',  'dq_timeliness_start',  1,  'LOAD_START',  '',  CAST(FORMAT_TIMESTAMP('%F %H:%M:%E6S', CURRENT_DATETIME('PST8PDT')) AS DATETIME),  'NAP_PRODUCT_PRICE_LOAD');


CALL `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_UTL.DATA_TIMELINESS_METRIC_FACT_LD('PRODUCT_PROMOTION_TIMELINE_DIM',  '{{params.dbenv}}_NAP_DIM',  'TECH_Merch_NAP_PRICE_AND_PROMOTION_INCREMENTAL_LOAD',  'dq_timeliness_start',  1,  'LOAD_START',  '',  CAST(FORMAT_TIMESTAMP('%F %H:%M:%E6S', CURRENT_DATETIME('PST8PDT')) AS DATETIME),  'NAP_PRODUCT_PRICE_LOAD');

