SET QUERY_BAND = '
App_ID=app04216;
DAG_ID=event_producer_schema_v2_nonprod;
Task_Name=write_to_insight_event_stg_0;
LoginUser=SCH_NAP_MKTG_BATCH_DEV;
Job_Name=event_producer_schema_v2_prod;
Data_Plane=DAS_MARKETING;
Team_Email=DAS_Marketing@nordstrom.com;
PagerDuty=nap-marketing;
Conn_Type=JDBC;'
FOR SESSION VOLATILE;
ET;

--REMOVE YESTERDAY'S DELTA RECORDS
DELETE FROM {teradata_env}_NAP_STG.CPP_EBR_TRAN_DELTA_LDG ALL;
ET;

--ADD RECORDS TO THE DELTA TABLE WHERE THE ACP_ID IS THE SAME, BUT ANY FIELDS ARE DIFFERENT
INSERT INTO {teradata_env}_NAP_STG.CPP_EBR_TRAN_DELTA_LDG
SELECT 
TODAY.INSIGHT_ID,
TODAY.LAST_PURCHASE_DATE,
CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_FACT TODAY
JOIN {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_HIST_FACT YESTERDAY
    ON TODAY.INSIGHT_ID = YESTERDAY.INSIGHT_ID
AND 
   COALESCE(CAST(TODAY.LAST_PURCHASE_DATE AS VARCHAR(10)),'2001-01-01') <> COALESCE(CAST(YESTERDAY.LAST_PURCHASE_DATE AS VARCHAR(10)),'2001-01-01');
ET;

--ADD NEW CUSTOMERS THAT AREN'T IN THE _HIST TABLE
INSERT INTO {teradata_env}_NAP_STG.CPP_EBR_TRAN_DELTA_LDG
SELECT
    TODAY.INSIGHT_ID,
    TODAY.LAST_PURCHASE_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_FACT TODAY
LEFT JOIN {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_HIST_FACT YESTERDAY
    ON TODAY.INSIGHT_ID = YESTERDAY.INSIGHT_ID
WHERE YESTERDAY.INSIGHT_ID IS NULL;
ET;

SET QUERY_BAND = NONE FOR SESSION;
ET;
