SET QUERY_BAND = '
App_ID=app04216;
DAG_ID=event_producer_schema_v2_nonprod;
Task_Name=write_to_insight_event_stg_0;
LoginUser=SCH_NAP_MKTG_BATCH_DEV;
Job_Name=event_producer_schema_v2_prod;
Data_Plane=DAS_MARKETING;
Team_Email=jianyang.gan@nordstrom.com;
PagerDuty=nap-marketing;
Conn_Type=JDBC;'
FOR SESSION VOLATILE;
ET;

--LOAD TODAY'S DATA IN CPP_EBR_TRAN_FACT USING TWO TEMP TABLES

--FIRST STEP INGEST THE DATA IN TEMP 1 TABLE
CREATE VOLATILE MULTISET TABLE RETAIL_TRAN_FCT_TEMP_1 AS (
SELECT 
T1.ACP_ID AS PK,
LINE_NET_USD_AMT,
(CASE WHEN LINE_NET_USD_AMT > 0
      THEN COALESCE(TRAN_DATE,BUSINESS_DAY_DATE)
      ELSE NULL  END) AS TRAN_DATE
FROM {teradata_env}_NAP_BASE_VWS.ANALYTICAL_CUSTOMER T1
JOIN {teradata_env}_NAP_VWS.RETAIL_TRAN_DETAIL_FACT_VW T2
ON T1.ACP_ID=T2.ACP_ID 
WHERE  
     (TRAN_DATE BETWEEN ADD_MONTHS(CURRENT_DATE ,-1) AND (CURRENT_DATE-1) ) 
     AND (BUSINESS_DAY_DATE >= ADD_MONTHS(CURRENT_DATE ,-1)) 
     AND T1.MKTG_PROFILE_TYPE='Y' AND T1.RECORD_ACTIVE_IND='Y'
)WITH DATA
PRIMARY INDEX(PK)
ON COMMIT PRESERVE ROWS;
ET;

--COLLECT STATISTICS COLUMN(PK) ON RETAIL_TRAN_FCT_TEMP_1;

--SECOND STEP IS CALCULATE THE LATEST PURCHASE DATE BY ACP_ID  
CREATE VOLATILE MULTISET TABLE RETAIL_TRAN_FCT_TEMP_2 AS (
SELECT 
PK,
 MAX(TRAN_DATE) AS LAST_PURCHASE_DATE 
FROM RETAIL_TRAN_FCT_TEMP_1 RTDF
GROUP BY PK
) WITH DATA
PRIMARY INDEX(PK)
ON COMMIT PRESERVE ROWS;
ET;

--COLLECT STATISTICS COLUMN(PK) ON RETAIL_TRAN_FCT_TEMP_2;

--REFRESH ENTIRE CPP_EBR_TRAN_FACT TABLE
DELETE FROM {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_FACT ALL;
ET;

--LOAD TODAY'S FINAL COMPUTED RECORDS IN CPP_EBR_TRAN_FACT
INSERT INTO {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_FACT
SELECT
   A.PK AS INSIGHT_ID,
   A.LAST_PURCHASE_DATE AS LAST_PURCHASE_DATE,
   CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM RETAIL_TRAN_FCT_TEMP_2 A;
ET;

--COLLECT STATISTICS COLUMN(INSIGHT_ID) ON {teradata_env}_NAP_BASE_VWS.CPP_EBR_TRAN_FACT;
SET QUERY_BAND = NONE FOR SESSION;
ET;
