SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=alterations_load_2656_napstore_insights;
Task_Name=alterations_load_fct;'
FOR SESSION VOLATILE;

ET;

merge into {db_env}_NAP_FCT.ALTERATION_TICKET_FACT as T
    using
    (
    select
    TICKET_ID,
    cast( cast(substr(CREATED_TS,1,19) || '+00:00' as timestamp(0)) at 'GMT' AS date) as TICKET_DATE,
    cast(substr(CREATED_TS,1,19) || '+00:00' as timestamp(0))   as CREATED_TS_T,
    cast(substr(LAST_MODIFIED,1,19) || '+00:00' as timestamp(0))  as LAST_MODIFIED_T,
    CUSTOMER_ID,
    TICKET_STATUS,
    CAST(SALESPERSON_NUMBER as INTEGER) as SALESPERSON_NUMBER,
    CAST(FIT_SPECIALIST_NUMBER as BIGINT) as FIT_SPECIALIST_NUMBER,
    FITTING_DT,
    CAST(SUB_TOTAL as NUMERIC(8, 2)) as SUB_TOTAL,
    CAST(STORE_ORIGIN as INTEGER) as STORE_ORIGIN,
    CAST(STORE_DESTINATION as INTEGER) as STORE_DESTINATION,
    DELIVERY_OPTION,
    DELIVERY_DESTINATION,
    current_date-1 as DW_BATCH_DATE,
    current_timestamp(0) as DW_SYS_LOAD_TMSTP,
    current_timestamp(0) as DW_SYS_UPDT_TMSTP
    from (
	    Select a.*
,row_number() over (partition by a.TICKET_ID order by cast(substr(LAST_MODIFIED,1,19) || '+00:00' as timestamp(0)) desc ) as row_num
from
{db_env}_NAP_STG.ALTERATION_TICKET_STG a
qualify row_num = 1
where a.CUSTOMER_ID <> 'id'
	)A) s
    on s.TICKET_ID = t.TICKET_ID
    when matched then
update
    set LAST_MODIFIED = s.LAST_MODIFIED_T,
    TICKET_STATUS = s.TICKET_STATUS,
    CUSTOMER_ID = s.CUSTOMER_ID,
    TICKET_DATE = s.TICKET_DATE,
    SALESPERSON_NUMBER = s.SALESPERSON_NUMBER,
    FIT_SPECIALIST_NUMBER = s.FIT_SPECIALIST_NUMBER,
    FITTING_DT = s.FITTING_DT,
    SUB_TOTAL = s.SUB_TOTAL,
    STORE_ORIGIN = s.STORE_ORIGIN,
    STORE_DESTINATION = s.STORE_DESTINATION,
    DELIVERY_OPTION = s.DELIVERY_OPTION,
    DELIVERY_DESTINATION =s.DELIVERY_DESTINATION,
    DW_SYS_UPDT_TMSTP = current_timestamp(0)
    when not matched then
insert(
TICKET_ID,
TICKET_DATE,
CREATED_TS,
LAST_MODIFIED,
CUSTOMER_ID,
TICKET_STATUS,
SALESPERSON_NUMBER,
FIT_SPECIALIST_NUMBER,
FITTING_DT,
SUB_TOTAL,
STORE_ORIGIN,
STORE_DESTINATION,
DELIVERY_OPTION,
DELIVERY_DESTINATION,
DW_BATCH_DATE,
DW_SYS_LOAD_TMSTP,
DW_SYS_UPDT_TMSTP)
values
    (
    s.TICKET_ID,
    s.TICKET_DATE,
    s.CREATED_TS_T,
    s.LAST_MODIFIED_T,
    s.CUSTOMER_ID,
    s.TICKET_STATUS,
    s.SALESPERSON_NUMBER,
    s.FIT_SPECIALIST_NUMBER,
    s.FITTING_DT,
    s.SUB_TOTAL,
    s.STORE_ORIGIN,
    s.STORE_DESTINATION,
    s.DELIVERY_OPTION,
    s.DELIVERY_DESTINATION,
    s.DW_BATCH_DATE,
    s.DW_SYS_LOAD_TMSTP,
    s.DW_SYS_UPDT_TMSTP
    );

ET;

merge into {db_env}_NAP_FCT.ALTERATION_TICKET_GARMENT_FACT as T
    using
    (
    select
    TICKET_ID,
    GARMENT_ID,
    CAST(EXTRA_FEE as NUMERIC(6,2)) as EXTRA_FEE,
    GARMENT_COLOR,
    GARMENT_DESCRIPTION,
    CAST(GARMENT_SEQUENCE as INTEGER) as GARMENT_SEQUENCE,
    GARMENT_STATUS,
    GARMENT_TYPE,
    cast(substr(LAST_MODIFIED,1,19) || '+00:00' as timestamp(0))  as LAST_MODIFIED_T,
    CAST(PROMISE_DATE as DATE FORMAT 'YYYY-MM-DD') as PROMISE_DATE,
    GARMENT_UPC,
    QA_FAILED_REASON,
    GARMENT_ORIGIN,
    CAST(GARMENT_ALTERATION_PRICE as NUMERIC(6, 2)) as GARMENT_ALTERATION_PRICE,
    GARMENT_SIZE,
    GARMENT_BRAND,
    GARMENT_CONDITION,
    PRICE_TYPE,
    CAST(EXPEDITE_FEE as NUMERIC(6, 2)) as EXPEDITE_FEE,
    PROMISE_TIME,
    case when EXPRESS_HEM = 'TRUE' then 1 else 0 end as EXPRESS_HEM,
    --CAST(EXPRESS_HEM as BYTEINT) as EXPRESS_HEM,
    current_date-1 as DW_BATCH_DATE,
    current_timestamp(0) as DW_SYS_LOAD_TMSTP,
    current_timestamp(0) as DW_SYS_UPDT_TMSTP
    from (Select a.*
,row_number() over (partition by a.TICKET_ID,a.GARMENT_ID order by cast(substr(LAST_MODIFIED,1,19) || '+00:00' as timestamp(0)) desc ) as row_num
from
{db_env}_NAP_STG.ALTERATION_TICKET_GARMENT_STG a
qualify row_num = 1	) A) s
    on s.GARMENT_ID = t.GARMENT_ID AND s.TICKET_ID=T.TICKET_ID
    when matched then
update
    set LAST_MODIFIED = s.LAST_MODIFIED_T,
    EXTRA_FEE = s.EXTRA_FEE,
    GARMENT_COLOR = s.GARMENT_COLOR,
    GARMENT_DESCRIPTION = s.GARMENT_DESCRIPTION,
    GARMENT_SEQUENCE = s.GARMENT_SEQUENCE,
    GARMENT_STATUS = s.GARMENT_STATUS,
    GARMENT_TYPE = s.GARMENT_TYPE,
    PROMISE_DATE = s.PROMISE_DATE,
    GARMENT_UPC = s.GARMENT_UPC,
    QA_FAILED_REASON = s.QA_FAILED_REASON,
    GARMENT_ORIGIN = s.GARMENT_ORIGIN,
    GARMENT_ALTERATION_PRICE= s.GARMENT_ALTERATION_PRICE,
    GARMENT_SIZE =s.GARMENT_SIZE,
    GARMENT_BRAND =s.GARMENT_BRAND,
    GARMENT_CONDITION =s.GARMENT_CONDITION,
    PRICE_TYPE =s.PRICE_TYPE,
    EXPEDITE_FEE =s.EXPEDITE_FEE,
    PROMISE_TIME =s.PROMISE_TIME,
    EXPRESS_HEM =s.EXPRESS_HEM,
    DW_SYS_UPDT_TMSTP = current_timestamp(0)
    when not matched then
insert(
TICKET_ID,
GARMENT_ID,
EXTRA_FEE,
GARMENT_COLOR,
GARMENT_DESCRIPTION,
GARMENT_SEQUENCE,
GARMENT_STATUS,
GARMENT_TYPE,
LAST_MODIFIED,
PROMISE_DATE,
GARMENT_UPC,
QA_FAILED_REASON,
GARMENT_ORIGIN,
GARMENT_ALTERATION_PRICE,
GARMENT_SIZE,
GARMENT_BRAND,
GARMENT_CONDITION,
PRICE_TYPE,
EXPEDITE_FEE,
PROMISE_TIME,
EXPRESS_HEM,
DW_BATCH_DATE,
DW_SYS_LOAD_TMSTP,
DW_SYS_UPDT_TMSTP)
values
    (
    s.TICKET_ID,
    s.GARMENT_ID,
    s.EXTRA_FEE,
    s.GARMENT_COLOR,
    s.GARMENT_DESCRIPTION,
    s.GARMENT_SEQUENCE,
    s.GARMENT_STATUS,
    s.GARMENT_TYPE,
    s.LAST_MODIFIED_T,
    s.PROMISE_DATE,
    s.GARMENT_UPC,
    s.QA_FAILED_REASON,
    s.GARMENT_ORIGIN,
    s.GARMENT_ALTERATION_PRICE,
    s.GARMENT_SIZE,
    s.GARMENT_BRAND,
    s.GARMENT_CONDITION,
    s.PRICE_TYPE,
    s.EXPEDITE_FEE,
    s.PROMISE_TIME,
    s.EXPRESS_HEM,
    s.DW_BATCH_DATE,
    s.DW_SYS_LOAD_TMSTP,
    s.DW_SYS_UPDT_TMSTP
    );

ET;

LOCK TABLE {db_env}_NAP_STG.ALTERATION_TICKET_GARMENT_WORK_STG FOR ACCESS
merge into {db_env}_NAP_FCT.ALTERATION_TICKET_GARMENT_WORK_FACT as T
    using
    (
    select
    TICKET_ID,
    GARMENT_ID,
    GARMENT_WORK_ITEM_ID,
    ALTERATION_CATEGORY,
    ALTERATION_NAME,
    cast(MINUTES as integer) as MINUTES,
    current_date-1 as DW_BATCH_DATE,
    current_timestamp(0) as DW_SYS_LOAD_TMSTP,
    current_timestamp(0) as DW_SYS_UPDT_TMSTP
    from (select a.*
,row_number() over (partition by a.TICKET_ID,a.GARMENT_ID, GARMENT_WORK_ITEM_ID order by MINUTES asc ) as row_num
from
{db_env}_NAP_STG.ALTERATION_TICKET_GARMENT_WORK_STG a
qualify row_num = 1	) A) s
    on s.GARMENT_ID = t.GARMENT_ID AND s.TICKET_ID=T.TICKET_ID AND s.GARMENT_WORK_ITEM_ID=T.GARMENT_WORK_ITEM_ID
    when matched then
update
    set ALTERATION_CATEGORY = s.ALTERATION_CATEGORY,
    ALTERATION_NAME = s.ALTERATION_NAME,
    MINUTES = s.MINUTES,
    DW_SYS_UPDT_TMSTP = current_timestamp(0)
    when not matched then
insert(
TICKET_ID,
GARMENT_ID,
GARMENT_WORK_ITEM_ID,
ALTERATION_CATEGORY,
ALTERATION_NAME,
MINUTES,
DW_BATCH_DATE,
DW_SYS_LOAD_TMSTP,
DW_SYS_UPDT_TMSTP)
values
    (
    s.TICKET_ID,
    s.GARMENT_ID,
    s.GARMENT_WORK_ITEM_ID,
    s.ALTERATION_CATEGORY,
    s.ALTERATION_NAME,
    s.MINUTES,
    s.DW_BATCH_DATE,
    s.DW_SYS_LOAD_TMSTP,
    s.DW_SYS_UPDT_TMSTP
    );

ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
