set `mapreduce.input.fileinputformat.input.dir.recursive` = true;

insert overwrite table store_json_orc
select 
    currentData.displaydepartments,
    currentData.storeNumber,
    currentData.adminHier,
    currentData.compStatusCode,
    currentData.compStatusDesc,
    currentData.compStoreStatusSet,
    currentData.curbsidePickup,
    currentData.dc,
    currentData.detailedStoreHours,
    currentData.displayaddress,
    currentData.displayname,
    currentData.eligibilityTypes,
    currentData.floorNOWs,
    currentData.functionTypes,
    currentData.isStoreOperationalToPublic,
    currentData.isstoreopenrightnow,
    currentData.locationAddlInfo,
    currentData.locationTypeCode,
    currentData.locationTypeDesc,
    currentData.locationamenities,
    currentData.name,
    currentData.ownershipTypeCode,
    currentData.ownershipTypeDesc,
    currentData.peerGroups,
    currentData.postalAddress,
    currentData.receivingLocation,
    currentData.restaurantAmenities,
    currentData.sca,
    currentData.dma,
    currentData.selectAssocStores,
    currentData.serviceAmenities,
    currentData.shorterNames,
    currentData.socialMedias,
    currentData.storePickupLocation,
    currentData.storePlanningChannel,
    currentData.storeReserveAreaInfo,
    currentData.telephone,
    currentData.timeZoneName,
    currentData.typeCategoryCode,
    currentData.typeCategoryDesc,
    currentData.typeCode,
    currentData.typedesc,
    currentData.typeIsInventoryStore,
    currentData.typeIsSellingStore,
    currentData.uieligbilitytypes,
    currentdataupdatedtimestamp,
    rootlevelchanges
 from (
select 
   currentData,
   currentdataupdatedtimestamp,
   rootlevelchanges,
   row_number() over (partition by currentData.storeNumber order by currentDataUpdatedTimeStamp desc) as rn
from acp_etl_landing.store_json
) where rn=1;