SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_scheduling_data_load_2656_napstore_insights;
Task_Name=wfm_scheduling_workgroup_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Create temporary table that has the latest unique data for each job:
CREATE
VOLATILE MULTISET TABLE WFM_SCHEDULING_WORKGROUP_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.SCHEDULING_WORKGROUP_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.SCHEDULING_WORKGROUP_FACT tgt
    USING WFM_SCHEDULING_WORKGROUP_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	NAME = src.NAME,
	DELETED = src.DELETED,
	DELETED_AT = src.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    CREATED_AT,
    LAST_UPDATED_AT,
    ID,
    NAME,
    DELETED,
    DELETED_AT,
	DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
	src.CREATED_AT,
	src.LAST_UPDATED_AT,
	src.ID,
	src.NAME,
	src.DELETED,
	src.DELETED_AT,
	CURRENT_TIMESTAMP(6),
	CURRENT_TIMESTAMP(6)
);
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
