SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_employee_schedule_constraint_load_2656_napstore_insights;
Task_Name=wfm_employee_schedule_constraint_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_SCHEDULE_CONSTRAINT_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.EMPLOYEE_SCHEDULE_CONSTRAINT_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_SCHEDULE_CONSTRAINT_FACT tgt
    USING WFM_EMPLOYEE_SCHEDULE_CONSTRAINT_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
    EMPLOYEE_ID = src.EMPLOYEE_ID,
    START_DATE = CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    END_DATE = CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD'),
    CAN_WORK_SPLIT_SHIFT = src.CAN_WORK_SPLIT_SHIFT,
    MUST_SCTRICTLY_ENFORCE_MIN_HOURS_BETWEEN_SHIFTS = src.MUST_SCTRICTLY_ENFORCE_MIN_HOURS_BETWEEN_SHIFTS,
    MAX_CONSECUTIVE_DAYS = src.MAX_CONSECUTIVE_DAYS,
    MAX_CONSECUTIVE_DAYS_ACROSS_WEEKS = src.MAX_CONSECUTIVE_DAYS_ACROSS_WEEKS,
    MAX_DAYS_PER_WEEK = src.MAX_DAYS_PER_WEEK,
    MINIMUM_MINUTES_BETWEEN_SHIFTS = src.MINIMUM_MINUTES_BETWEEN_SHIFTS,
    MINIMUM_MINUTES_PER_WEEK = src.MINIMUM_MINUTES_PER_WEEK,
    MINIMUM_MINUTES_SUNDAY = src.MINIMUM_MINUTES_SUNDAY,
    MINIMUM_MINUTES_MONDAY = src.MINIMUM_MINUTES_MONDAY,
    MINIMUM_MINUTES_TUESDAY = src.MINIMUM_MINUTES_TUESDAY,
    MINIMUM_MINUTES_WEDNESDAY = src.MINIMUM_MINUTES_WEDNESDAY,
    MINIMUM_MINUTES_THURSDAY = src.MINIMUM_MINUTES_THURSDAY,
    MINIMUM_MINUTES_FRIDAY = src.MINIMUM_MINUTES_FRIDAY,
    MINIMUM_MINUTES_SATURDAY = src.MINIMUM_MINUTES_SATURDAY,
    MAXIMUM_MINUTES_PER_WEEK = src.MAXIMUM_MINUTES_PER_WEEK,
    MAXIMUM_MINUTES_SUNDAY = src.MAXIMUM_MINUTES_SUNDAY,
    MAXIMUM_MINUTES_MONDAY = src.MAXIMUM_MINUTES_MONDAY,
    MAXIMUM_MINUTES_TUESDAY = src.MAXIMUM_MINUTES_TUESDAY,
    MAXIMUM_MINUTES_WEDNESDAY = src.MAXIMUM_MINUTES_WEDNESDAY,
    MAXIMUM_MINUTES_THURSDAY = src.MAXIMUM_MINUTES_THURSDAY,
    MAXIMUM_MINUTES_FRIDAY = src.MAXIMUM_MINUTES_FRIDAY,
    MAXIMUM_MINUTES_SATURDAY = src.MAXIMUM_MINUTES_SATURDAY,
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
    IS_DELETED = SRC.IS_DELETED,
	DELETED_AT = SRC.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    EMPLOYEE_ID,
    START_DATE,
    END_DATE,
    CAN_WORK_SPLIT_SHIFT ,
    MUST_SCTRICTLY_ENFORCE_MIN_HOURS_BETWEEN_SHIFTS,
    MAX_CONSECUTIVE_DAYS ,
    MAX_CONSECUTIVE_DAYS_ACROSS_WEEKS ,
    MAX_DAYS_PER_WEEK,
    MINIMUM_MINUTES_BETWEEN_SHIFTS ,
    MINIMUM_MINUTES_PER_WEEK ,
    MINIMUM_MINUTES_SUNDAY,
    MINIMUM_MINUTES_MONDAY,
    MINIMUM_MINUTES_TUESDAY,
    MINIMUM_MINUTES_WEDNESDAY,
    MINIMUM_MINUTES_THURSDAY,
    MINIMUM_MINUTES_FRIDAY,
    MINIMUM_MINUTES_SATURDAY,
    MAXIMUM_MINUTES_PER_WEEK,
    MAXIMUM_MINUTES_SUNDAY,
    MAXIMUM_MINUTES_MONDAY,
    MAXIMUM_MINUTES_TUESDAY,
    MAXIMUM_MINUTES_WEDNESDAY,
    MAXIMUM_MINUTES_THURSDAY,
    MAXIMUM_MINUTES_FRIDAY,
    MAXIMUM_MINUTES_SATURDAY,
    CREATED_AT,
    LAST_UPDATED_AT,
    IS_DELETED,
    DELETED_AT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.EMPLOYEE_ID,
    CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD'),
    src.CAN_WORK_SPLIT_SHIFT,
    src.MUST_SCTRICTLY_ENFORCE_MIN_HOURS_BETWEEN_SHIFTS,
    src.MAX_CONSECUTIVE_DAYS,
    src.MAX_CONSECUTIVE_DAYS_ACROSS_WEEKS,
    src.MAX_DAYS_PER_WEEK,
    src.MINIMUM_MINUTES_BETWEEN_SHIFTS,
    src.MINIMUM_MINUTES_PER_WEEK,
    src.MINIMUM_MINUTES_SUNDAY,
    src.MINIMUM_MINUTES_MONDAY,
    src.MINIMUM_MINUTES_TUESDAY,
    src.MINIMUM_MINUTES_WEDNESDAY,
    src.MINIMUM_MINUTES_THURSDAY,
    src.MINIMUM_MINUTES_FRIDAY,
    src.MINIMUM_MINUTES_SATURDAY,
    src.MAXIMUM_MINUTES_PER_WEEK,
    src.MAXIMUM_MINUTES_SUNDAY,
    src.MAXIMUM_MINUTES_MONDAY,
    src.MAXIMUM_MINUTES_TUESDAY,
    src.MAXIMUM_MINUTES_WEDNESDAY,
    src.MAXIMUM_MINUTES_THURSDAY,
    src.MAXIMUM_MINUTES_FRIDAY,
    src.MAXIMUM_MINUTES_SATURDAY,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.IS_DELETED,
    src.DELETED_AT,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
