SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_scheduling_data_load_2656_napstore_insights;
Task_Name=wfm_store_department_operating_hours_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_STORE_DEPARTMENT_OPERATING_HOURS_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.STORE_DEPARTMENT_OPERATING_HOURS_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.STORE_DEPARTMENT_OPERATING_HOURS_FACT tgt
    USING WFM_STORE_DEPARTMENT_OPERATING_HOURS_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
    STORE_NUMBER = src.STORE_NUMBER,
    DEPARTMENT_ID = src.DEPARTMENT_ID,
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
    DELETED = SRC.DELETED,
	DELETED_AT = SRC.DELETED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    STORE_NUMBER,
    DEPARTMENT_ID,
    CREATED_AT,
    LAST_UPDATED_AT,
    DELETED,
    DELETED_AT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.STORE_NUMBER,
    src.DEPARTMENT_ID,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.DELETED,
    src.DELETED_AT,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_STORE_DEPARTMENT_OPERATING_HOURS_DETAILS_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.STORE_DEPARTMENT_OPERATING_HOURS_DETAILS_STG
    qualify row_number() over (partition BY STORE_DEPARTMENT_OPERATING_HOURS_ID, EFFECTIVE_DAY ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(STORE_DEPARTMENT_OPERATING_HOURS_ID, EFFECTIVE_DAY) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.STORE_DEPARTMENT_OPERATING_HOURS_DETAILS_FACT tgt
    USING WFM_STORE_DEPARTMENT_OPERATING_HOURS_DETAILS_TEMP src
    ON (src.STORE_DEPARTMENT_OPERATING_HOURS_ID = tgt.STORE_DEPARTMENT_OPERATING_HOURS_ID AND
        src.EFFECTIVE_DAY = tgt.EFFECTIVE_DAY)
    WHEN MATCHED THEN
UPDATE
SET
    OPERATING_HOURS_DETAIL_TYPE = src.OPERATING_HOURS_DETAIL_TYPE,
	START_TIME = TIME '00:00:00' + CAST (src.START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	END_TIME = TIME '00:00:00' + CAST (src.END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    STORE_DEPARTMENT_OPERATING_HOURS_ID,
    EFFECTIVE_DAY,
    OPERATING_HOURS_DETAIL_TYPE,
    START_TIME,
    END_TIME,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.STORE_DEPARTMENT_OPERATING_HOURS_ID,
    src.EFFECTIVE_DAY,
    src.OPERATING_HOURS_DETAIL_TYPE,
    TIME '00:00:00' + CAST (src.START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    TIME '00:00:00' + CAST (src.END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;