SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_ideal_hours_load_2656_napstore_insights;
Task_Name=wfm_ideal_hours_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- IDEAL_LABOR_HOURS:
CREATE
VOLATILE MULTISET TABLE WFM_IDEAL_LABOR_HOURS_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.IDEAL_LABOR_HOURS_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.IDEAL_LABOR_HOURS_FACT tgt
    USING WFM_IDEAL_LABOR_HOURS_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	STORE_NUMBER = src.STORE_NUMBER,
	WORKGROUP_ID = src.WORKGROUP_ID,
	LABOR_ROLE_ID = src.LABOR_ROLE_ID,
	EFFECTIVE_DATE = CAST(src.EFFECTIVE_DATE as DATE FORMAT 'YYYY-MM-DD'),
	LOCAL_EFFECTIVE_TIME = TIME '00:00:00' + CAST (SRC.LOCAL_EFFECTIVE_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	MINUTES = src.MINUTES,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    CREATED_AT,
    LAST_UPDATED_AT,
    STORE_NUMBER,
    WORKGROUP_ID,
    LABOR_ROLE_ID,
    EFFECTIVE_DATE,
    LOCAL_EFFECTIVE_TIME,
    MINUTES,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.STORE_NUMBER,
    src.WORKGROUP_ID,
    src.LABOR_ROLE_ID,
    CAST (src.EFFECTIVE_DATE as DATE FORMAT 'YYYY-MM-DD'),
    TIME '00:00:00' + CAST (SRC.LOCAL_EFFECTIVE_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    src.MINUTES,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
