SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_time_off_request_load_2656_napstore_insights;
Task_Name=wfm_time_off_request_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_TIME_OFF_REQUEST_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.TIME_OFF_REQUEST_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.TIME_OFF_REQUEST_FACT tgt
    USING WFM_TIME_OFF_REQUEST_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
    EMPLOYEE_ID = src.EMPLOYEE_ID,
    TIME_OFF_REQUEST_STATUS = src.TIME_OFF_REQUEST_STATUS,
    START_DATE = CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    END_DATE = CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD'),
    LOCAL_START_TIME = TIME '00:00:00' + CAST (SRC.LOCAL_START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    LOCAL_END_TIME = TIME '00:00:00' + CAST (SRC.LOCAL_END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
    IS_CANCELED = SRC.IS_CANCELED,
	CANCELED_AT = SRC.CANCELED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    EMPLOYEE_ID,
    TIME_OFF_REQUEST_STATUS,
    START_DATE,
    END_DATE,
    LOCAL_START_TIME,
    LOCAL_END_TIME,
    CREATED_AT,
    LAST_UPDATED_AT,
    IS_CANCELED,
    CANCELED_AT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.EMPLOYEE_ID,
    src.TIME_OFF_REQUEST_STATUS,
    CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD'),
    TIME '00:00:00' + CAST (SRC.LOCAL_START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    TIME '00:00:00' + CAST (SRC.LOCAL_END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.IS_CANCELED,
    src.CANCELED_AT,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

-- Create temp table
CREATE
VOLATILE MULTISET TABLE WFM_TIME_OFF_REQUEST_DETAILS_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.TIME_OFF_REQUEST_DETAILS_STG
    qualify row_number() over (partition BY TIME_OFF_REQUEST_ID, EFFECTIVE_DATE ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(TIME_OFF_REQUEST_ID, EFFECTIVE_DATE) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.TIME_OFF_REQUEST_DETAILS_FACT tgt
    USING WFM_TIME_OFF_REQUEST_DETAILS_TEMP src
    ON (src.TIME_OFF_REQUEST_ID = tgt.TIME_OFF_REQUEST_ID AND
        CAST(src.EFFECTIVE_DATE as DATE FORMAT 'YYYY-MM-DD') = tgt.EFFECTIVE_DATE)
    WHEN MATCHED THEN
UPDATE
SET
    MINUTES = src.MINUTES,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    TIME_OFF_REQUEST_ID,
    EFFECTIVE_DATE,
    MINUTES,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.TIME_OFF_REQUEST_ID,
    CAST(src.EFFECTIVE_DATE as DATE FORMAT 'YYYY-MM-DD'),
    src.MINUTES,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
