SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_workforce_employee_load_2656_napstore_insights;
Task_Name=wfm_workforce_employee_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- EMPLOYEE HOME STORE
-- CREATE TEMPORARY TABLE THAT HAS THE LATEST UNIQUE DATA FOR EACH JOB:
CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_HOME_STORE_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.EMPLOYEE_HOME_STORE_STG
    QUALIFY ROW_NUMBER() OVER (PARTITION BY EMPLOYEE_ID, STORE_NUMBER ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(EMPLOYEE_ID, STORE_NUMBER) ON COMMIT PRESERVE ROWS;
ET;

-- MERGE AND UPDATE:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_HOME_STORE_FACT TGT
    USING WFM_EMPLOYEE_HOME_STORE_TEMP SRC
    ON (SRC.EMPLOYEE_ID = TGT.EMPLOYEE_ID
    AND SRC.STORE_NUMBER = TGT.STORE_NUMBER
    AND SRC.CREATED_AT = TGT.CREATED_AT)
    WHEN MATCHED THEN
UPDATE
SET
	LAST_UPDATED_AT = SRC.LAST_UPDATED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    EMPLOYEE_ID,
    STORE_NUMBER,
    CREATED_AT,
    LAST_UPDATED_AT,
	DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    SRC.EMPLOYEE_ID,
    SRC.STORE_NUMBER,
    SRC.CREATED_AT,
    SRC.LAST_UPDATED_AT,
    CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );

ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
