SELECT CAST(DEPT_NUM AS VARCHAR(10)) DEPT_NUM,
coalesce(OREPLACE(DEPT_NAME, CHR(10), ''),'') DEPT_DESC,
CAST(DIVISION_NUM AS VARCHAR(10)) DIVISION_NUM,
coalesce(OREPLACE(DIVISION_NAME, CHR(10), ''),'') DIV_DESC,
CAST(SUBDIVISION_NUM AS VARCHAR(10)) SUBDIVISION_NUM,
coalesce(OREPLACE(SUBDIVISION_NAME , CHR(10), ''),'') GRP_DESC
FROM {db_env}_NAP_BASE_VWS.DEPARTMENT_DIM  ;
