/*
Purpose:          Creates empty tables in {{environment_schema}} for Anniversary Preview
Variable(s):     {{environment_schema}} T2DL_DAS_SCALED_EVENTS
Author:          Manuela Hurtado Gonzalez
*/

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'ANNIVERSARY_PREVIEW', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.ANNIVERSARY_PREVIEW
  ,FALLBACK ,
	NO BEFORE JOURNAL,
	NO AFTER JOURNAL,
	CHECKSUM = DEFAULT,
	DEFAULT MERGEBLOCKRATIO,
	MAP = TD_MAP1
	(
    day_date DATE FORMAT 'YYYY/MM/DD' NOT NULL
    , day_idnt INTEGER
    , ty_ly_ind VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('TY', 'LY')
    , country VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('US', 'CA')
    , days_since_launch INTEGER
    , yr_num INTEGER
    , experience VARCHAR(20)CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
    , rms_sku_num VARCHAR(20)CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
    , dropship_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , rp_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , udig VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , product_views DECIMAL(12,2)
    , cart_adds INTEGER
    , com_demand DECIMAL(12,2)
    , com_ordered_units INTEGER
    , wishlist_adds INTEGER
    , fls_gross_sales_r DECIMAL(12,2)
    , fls_gross_sales_c DECIMAL(12,2)
    , fls_gross_sales_u INTEGER
    , eoh_r DECIMAL(12,2)
    , eoh_c DECIMAL(12,2)
    , eoh_u INTEGER
    , in_transit_r DECIMAL(12,2)
    , in_transit_c DECIMAL(12,2)
    , in_transit_u INTEGER
    , oo_r DECIMAL(12,2)
    , oo_c DECIMAL(12,2)
    , oo_u INTEGER
    , QUANTRIX_CATEGORY VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , CCS_CATEGORY VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , CCS_SUBCATEGORY VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , ASSORTMENT_GROUPING VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , anniversary_theme VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
    , merch_theme VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
    , style_group_num VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
    , style_desc VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
    , supp_color VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
    , div_num INTEGER
    , div_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , division VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , grp_num INTEGER
    , grp_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , subdivision VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , dept_num INTEGER
    , dept_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , department VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , class_num INTEGER
    , class_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , "class" VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , sbclass_num INTEGER
    , sbclass_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , subclass VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , supplier VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , brand_name VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , vpn VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC
    , is_npg VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , anchor_brands_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , process_tmstp TIMESTAMP(6) WITH TIME ZONE
  )
PRIMARY INDEX (
		day_date,
		rms_sku_num,
		experience)

PARTITION BY RANGE_N(day_idnt BETWEEN 2023150 AND 2025000 EACH 1);
GRANT SELECT ON {environment_schema}.ANNIVERSARY_PREVIEW TO PUBLIC;
