
CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'CYBER_OWNERSHIP_DAILY', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.CYBER_OWNERSHIP_DAILY
    , FALLBACK
    , NO BEFORE JOURNAL
    , NO AFTER JOURNAL
    , CHECKSUM = DEFAULT
    , DEFAULT MERGEBLOCKRATIO
    , MAP = TD_MAP1
(
	day_date 		DATE FORMAT 'YYYY/MM/DD' NOT NULL
    , data_source			VARCHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('NAP')
    , country				VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('US')
    , channel				VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('110, FULL LINE STORES', '310, RESERVE STOCK', '120, N.COM')
    , channel_idnt			INTEGER NOT NULL COMPRESS(110, 310, 120, 210, 250)
    , banner VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC
    , region				VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC
    , location				VARCHAR(46) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
    , division				VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC
    , subdivision			VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC
    , department			VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC
    , "class"				VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC
    , subclass				VARCHAR(73) CHARACTER SET UNICODE NOT CASESPECIFIC
    , style_group_num		VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    , style_group_desc		VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , style_num 			BIGINT
    , style_desc			VARCHAR(300) CHARACTER SET UNICODE NOT CASESPECIFIC
    , vpn					VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
    , supp_color			VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
    , nrf_colr				VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    , brand_tier 			VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , brand 				VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    , supplier_num 			VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    , supplier 				VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    , udig					VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , npg_ind				VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , rp_ind				VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , anchor_brands_ind				VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL COMPRESS ('Y', 'N')
    , on_order_dollars		DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , on_order_cost 		DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , on_order_units		INTEGER NOT NULL
    , ttl_ordered_dollars   DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , ttl_ordered_cost      DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , ttl_ordered_units 	INTEGER NOT NULL
    , ttl_received_dollars  DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , ttl_received_cost     DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , ttl_received_units	INTEGER NOT NULL
    , ttl_canceled_units	INTEGER NOT NULL
    , in_transit_dollars	DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , in_transit_cost   	DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , in_transit_units		INTEGER NOT NULL
    , eoh_dollars			DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , eoh_cost  			DECIMAL(20,2) NOT NULL DEFAULT 0.00 COMPRESS 0.00
    , eoh_units				INTEGER NOT NULL
)
PRIMARY INDEX (vpn, supp_color, location);
GRANT SELECT ON {environment_schema}.CYBER_OWNERSHIP_DAILY TO PUBLIC;
