SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=ecf_salesreporting_to_postgres_extract_2656_napstore_insights;
Task_Name=ecf_salesreporting_load_teradata_to_postgres;'
FOR SESSION VOLATILE;

create temporary view ecf_salesreporting_temp AS
SELECT
    business_date,
    'USD' as currency_code,
    trim(leading '0' from employee_id) as employee_id,
    SUM(digital_gross_amt_ty) as digital_gross_amt_ty,
    SUM(digital_gross_amt_ly) as digital_gross_amt_ly,
    SUM(digital_return_amt_ty) as digital_return_amt_ty,
    SUM(digital_return_amt_ly) as digital_return_amt_ly,
    SUM(digital_net_amt_ty) as digital_net_amt_ty,
    SUM(digital_net_amt_ly) as digital_net_amt_ly,
    SUM(store_gross_amt_ty) as store_gross_amt_ty,
    SUM(store_gross_amt_ly) as store_gross_amt_ly,
    SUM(store_net_amt_ty) as store_net_amt_ty,
    SUM(store_net_amt_ly) as store_net_amt_ly,
    SUM(gross_amt_ty) as gross_amt_ty,
    SUM(gross_amt_ly) as gross_amt_ly,
    SUM(return_amt_ty) as return_amt_ty,
    SUM(return_amt_ly) as return_amt_ly,
    SUM(net_amt_ty) as net_amt_ty,
    SUM(net_amt_ly) as net_amt_ly,
    SUM(digital_gross_amt_w2d) as digital_gross_amt_w2d,
    SUM(digital_gross_amt_w2d_ly) as digitaL_gross_amt_w2d_ly,
    SUM(digital_return_amt_w2d) as digital_return_amt_w2d,
    SUM(digital_return_amt_w2d_ly) as digital_return_amt_w2d_ly,
    SUM(digital_net_amt_w2d) as digital_net_amt_w2d,
    SUM(digital_net_amt_w2d_ly) as digital_net_amt_w2d_ly,
    SUM(store_gross_amt_w2d) as store_gross_amt_w2d,
    SUM(store_gross_amt_w2d_ly) as store_gross_amt_w2d_ly,
    SUM(store_return_amt_w2d) as store_return_amt_w2d,
    SUM(store_return_amt_w2d_ly) as store_return_amt_w2d_ly,
    SUM(store_net_amt_w2d) as store_net_amt_w2d,
    SUM(store_net_amt_w2d_ly) as store_net_amt_w2d_ly,
    SUM(gross_amt_w2d) as gross_amt_w2d,
    SUM(gross_amt_w2d_ly) as gross_amt_w2d_ly,
    SUM(return_amt_w2d) as return_amt_w2d,
    SUM(return_amt_w2d_ly) as return_amt_w2d_ly,
    SUM(net_amt_w2d) as net_amt_w2d,
    SUM(net_amt_w2d_ly) as net_amt_w2d_ly,
    SUM(digital_gross_amt_m2d) as digital_gross_amt_m2d,
    SUM(digital_gross_amt_m2d_ly) as digital_gross_amt_m2d_ly,
    SUM(digital_return_amt_m2d) as digital_return_amt_m2d,
    SUM(digital_return_amt_m2d_ly) as digital_return_amt_m2d_ly,
    SUM(digital_net_amt_m2d) as digital_net_amt_m2d,
    SUM(digital_net_amt_m2d_ly) as digital_net_amt_m2d_ly,
    SUM(store_gross_amt_m2d) as store_gross_amt_m2d,
    SUM(store_gross_amt_m2d_ly) as store_gross_amt_m2d_ly,
    SUM(store_return_amt_m2d) as store_return_amt_m2d,
    SUM(store_return_amt_m2d_ly) as store_return_amt_m2d_ly,
    SUM(store_net_amt_m2d) as store_net_amt_m2d,
    SUM(store_net_amt_m2d_ly) as store_net_amt_m2d_ly,
    SUM(gross_amt_m2d) as gross_amt_m2d,
    SUM(gross_amt_m2d_ly) as gross_amt_m2d_ly,
    SUM(return_amt_m2d) as return_amt_m2d,
    SUM(return_amt_m2d_ly) as return_amt_m2d_ly,
    SUM(net_amt_m2d) as net_amt_m2d,
    SUM(net_amt_m2d_ly) as net_amt_m2d_ly,
    SUM(digital_gross_amt_pp2d) as digital_gross_amt_pp2d,
    SUM(digitaL_gross_amt_pp2d_ly) as digitaL_gross_amt_pp2d_ly,
    SUM(digital_return_amt_pp2d) as digital_return_amt_pp2d,
    SUM(digital_return_amt_pp2d_ly) as digital_return_amt_pp2d_ly,
    SUM(digital_net_amt_pp2d) as digital_net_amt_pp2d,
    SUM(digital_net_amt_pp2d_ly) as digital_net_amt_pp2d_ly,
    SUM(store_gross_amt_pp2d) as store_gross_amt_pp2d,
    SUM(store_gross_amt_pp2d_ly) as store_gross_amt_pp2d_ly,
    SUM(store_return_amt_pp2d) as store_return_amt_pp2d,
    SUM(store_return_amt_pp2d_ly) as store_return_amt_pp2d_ly,
    SUM(store_net_amt_pp2d) as store_net_amt_pp2d,
    SUM(store_net_amt_pp2d_ly) as store_net_amt_pp2d_ly,
    SUM(gross_amt_pp2d) as gross_amt_pp2d,
    SUM(gross_amt_pp2d_ly) as gross_amt_pp2d_ly,
    SUM(return_amt_pp2d) as return_amt_pp2d,
    SUM(return_amt_pp2d_ly) as return_amt_pp2d_ly,
    SUM(net_amt_pp2d) as net_amt_pp2d,
    SUM(net_amt_pp2d_ly) as net_amt_pp2d_ly,
    SUM(digital_gross_amt_y2d) as digital_gross_amt_y2d,
    SUM(digital_gross_amt_y2d_ly) as digital_gross_amt_y2d_ly,
    SUM(digital_return_amt_y2d) as digital_return_amt_y2d,
    SUM(digital_return_amt_y2d_ly) as digital_return_amt_y2d_ly,
    SUM(digital_net_amt_y2d) as digital_net_amt_y2d,
    SUM(digital_net_amt_y2d_ly) as digital_net_amt_y2d_ly,
    SUM(store_gross_amt_y2d) as store_gross_amt_y2d,
    SUM(store_gross_amt_y2d_ly) as store_gross_amt_y2d_ly,
    SUM(store_return_amt_y2d) as store_return_amt_y2d,
    SUM(store_return_amt_y2d_ly) as store_return_amt_y2d_ly,
    SUM(store_net_amt_y2d) as store_net_amt_y2d,
    SUM(store_net_amt_y2d_ly) as store_net_amt_y2d_ly,
    SUM(gross_amt_y2d) as gross_amt_y2d,
    SUM(gross_amt_y2d_ly) as gross_amt_y2d_ly,
    SUM(return_amt_y2d) as return_amt_y2d,
    SUM(return_amt_y2d_ly) as return_amt_y2d_ly,
    SUM(net_amt_y2d) as net_amt_y2d,
    SUM(net_amt_y2d_ly) as net_amt_y2d_ly
FROM ecf_salesreporting_vw
GROUP BY 1, 2, 3;


insert overwrite table ecf_salesreporting_postgres
select * from ecf_salesreporting_temp;