select             
     acp_id
    ,session_id
    ,channel
    ,platform                
    ,loyalty_status                
    ,cardmember_flag               
    ,member_flag                   
    ,engagement_cohort             
    ,billing_zipcode               
    ,us_dma_code                   
    ,dma_desc                      
    ,CITY_NAME                     
    ,STATE_NAME                    
    ,predicted_ct_segment          
    ,clv_jwn                       
    ,clv_op                        
    ,clv_fp                        
    ,aare_chnl_code                
    ,aare_status_date              
    ,activated_chnl_code           
    ,activated_date   
    ,ncom_first_digital_transaction
    ,ncom_second_digital_transaction
    ,ncom_last_digital_transaction
    ,rcom_first_digital_transaction
    ,rcom_second_digital_transaction
    ,rcom_last_digital_transaction
    ,first_digital_transaction
    ,second_digital_transaction
    ,last_digital_transaction   
    ,pre_22_digital_order_count
    ,pre_22_digital_demand
    ,pre_22_digital_units
    ,pre_22_ncom_order_count
    ,pre_22_ncom_demand
    ,pre_22_ncom_units
    ,pre_22_rcom_order_count
    ,pre_22_rcom_demand
    ,pre_22_rcom_units        
    ,age_group                     
    ,lifestage                      
    ,dw_sys_load_tmstp  
	,activity_date_pacific     
from {digital_merch_t2_schema}.customer_attributes_table
where activity_date_pacific between {start_date} and {end_date};
