-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app06788; DAG_ID=credit_application_decisioning_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'application_id and event_time'
CREATE MULTISET VOLATILE TABLE CREDIT_APPLICATION_DECISIONING_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_CREDIT_STG.CREDIT_APPLICATION_DECISIONING_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY APPLICATION_ID, EVENT_TIME ORDER BY EVENT_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (APPLICATION_ID, EVENT_TIME) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- Delete duplicates
DELETE FROM {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_APPLICATION_DECISIONING_FACT
WHERE APPLICATION_ID IN (SELECT DISTINCT APPLICATION_ID FROM CREDIT_APPLICATION_DECISIONING_TEMP);

INSERT INTO {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_APPLICATION_DECISIONING_FACT
(
    EVENT_TIME,
    APPLICATION_ID,
    APPLICATION_DECISION_STATUS,
    CUSTOMER_ID,
    CUSTOMER_ID_TYPE,
    CLIENT_REFERENCE_ID,
    CREDIT_CARD_PRODUCT_TYPE,
    CREDIT_CARD_PRODUCT_SUBTYPE,
    FAILURE_REASON,
    DW_BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT
    CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
    APPLICATION_ID,
    APPLICATION_DECISION_STATUS,
    CUSTOMER_ID,
    CUSTOMER_ID_TYPE,
    CLIENT_REFERENCE_ID,
    CREDIT_CARD_PRODUCT_TYPE,
    CREDIT_CARD_PRODUCT_SUBTYPE,
    FAILURE_REASON,
    CURRENT_DATE AS DW_BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM CREDIT_APPLICATION_DECISIONING_TEMP;

-- delete records from stg table
DELETE FROM {db_env}_NAP_CREDIT_STG.CREDIT_APPLICATION_DECISIONING_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
