-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app06788; DAG_ID=credit_application_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

/*Create temporary tables for selecting distinct records by
'credit_application_id'.*/

CREATE MULTISET VOLATILE TABLE CREDIT_APPLICATION_LDG_TEMP AS (
    SELECT DISTINCT *
    FROM {db_env}_NAP_CREDIT_STG.CREDIT_APPLICATION_LDG
    QUALIFY
        row_number() OVER (
            PARTITION BY CREDIT_APPLICATION_ID ORDER BY LAST_UPDATED_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (CREDIT_APPLICATION_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- Insert or update if exist

MERGE INTO {db_env}_NAP_CREDIT_BASE_VWS.CREDIT_APPLICATION_FACT AS CAF
USING CREDIT_APPLICATION_LDG_TEMP AS SRC
    ON (SRC.CREDIT_APPLICATION_ID = CAF.CREDIT_APPLICATION_ID)
WHEN MATCHED THEN
    UPDATE
        SET
            DW_SYS_UPDT_TMSTP = current_timestamp(0),
            LAST_UPDATED_TIME = SRC.LAST_UPDATED_TIME,
            SUBMITTED_TIME = SRC.SUBMITTED_TIME,
            CHANNEL_COUNTRY = SRC.CHANNEL_COUNTRY,
            CHANNEL_BRAND = SRC.CHANNEL_BRAND,
            SELLING_CHANNEL = SRC.SELLING_CHANNEL,
            STORE_NUMBER = SRC.STORE_NUMBER,
            EMPLOYEE_ID_TYPE = SRC.EMPLOYEE_ID_TYPE,
            EMPLOYEE_ID = SRC.EMPLOYEE_ID,
            CUSTOMER_ID_TYPE = SRC.CUSTOMER_ID_TYPE,
            CUSTOMER_ID = SRC.CUSTOMER_ID,
            CREDIT_PRODUCT_SELECTION = SRC.CREDIT_PRODUCT_SELECTION,
            ACQUISITION_OFFER = SRC.ACQUISITION_OFFER,
            EXPERIENCE = SRC.EXPERIENCE,
            TERMS_AND_CONDITIONS_BARCODE = SRC.TERMS_AND_CONDITIONS_BARCODE,
            IP_ADDRESS_VALUE = SRC.IP_ADDRESS_VALUE,
            IP_ADDRESS_AUTHORITY = SRC.IP_ADDRESS_AUTHORITY,
            IP_ADDRESS_DATA_CLASSIFICATION = SRC.IP_ADDRESS_DATA_CLASSIFICATION,
            SHOPPER_ID = SRC.SHOPPER_ID,
            IOVATION_DEVICE_ID = SRC.IOVATION_DEVICE_ID,
            CONTEXT_ID = SRC.CONTEXT_ID,
            EMAIL_VALUE = SRC.EMAIL_VALUE,
            EMAIL_AUTHORITY = SRC.EMAIL_AUTHORITY,
            EMAIL_DATA_CLASSIFICATION = SRC.EMAIL_DATA_CLASSIFICATION,
            ANNUAL_INCOME_CURRENCY_CODE = SRC.ANNUAL_INCOME_CURRENCY_CODE,
            ANNUAL_INCOME_SALARY_VALUE = SRC.ANNUAL_INCOME_SALARY_VALUE,
            ANNUAL_INCOME_SALARY_AUTHORITY = SRC.ANNUAL_INCOME_SALARY_AUTHORITY,
            ANNUAL_INCOME_SALARY_DATA_CLASSIFICATION = SRC.ANNUAL_INCOME_SALARY_DATA_CLASSIFICATION

WHEN NOT MATCHED THEN
    INSERT (
        DW_SYS_LOAD_TMSTP,
        DW_SYS_UPDT_TMSTP,
        LAST_UPDATED_TIME,
        SUBMITTED_TIME,
        CHANNEL_COUNTRY,
        CHANNEL_BRAND,
        SELLING_CHANNEL,
        STORE_NUMBER,
        EMPLOYEE_ID_TYPE,
        EMPLOYEE_ID,
        CREDIT_APPLICATION_ID,
        CUSTOMER_ID_TYPE,
        CUSTOMER_ID,
        CREDIT_PRODUCT_SELECTION,
        ACQUISITION_OFFER,
        EXPERIENCE,
        TERMS_AND_CONDITIONS_BARCODE,
        IP_ADDRESS_VALUE,
        IP_ADDRESS_AUTHORITY,
        IP_ADDRESS_DATA_CLASSIFICATION,
        SHOPPER_ID,
        IOVATION_DEVICE_ID,
        CONTEXT_ID,
        EMAIL_VALUE,
        EMAIL_AUTHORITY,
        EMAIL_DATA_CLASSIFICATION,
        ANNUAL_INCOME_CURRENCY_CODE,
        ANNUAL_INCOME_SALARY_VALUE,
        ANNUAL_INCOME_SALARY_AUTHORITY,
        ANNUAL_INCOME_SALARY_DATA_CLASSIFICATION
    )
        VALUES (
            current_timestamp(0),
            current_timestamp(0),
            SRC.LAST_UPDATED_TIME,
            SRC.SUBMITTED_TIME,
            SRC.CHANNEL_COUNTRY,
            SRC.CHANNEL_BRAND,
            SRC.SELLING_CHANNEL,
            SRC.STORE_NUMBER,
            SRC.EMPLOYEE_ID_TYPE,
            SRC.EMPLOYEE_ID,
            SRC.CREDIT_APPLICATION_ID,
            SRC.CUSTOMER_ID_TYPE,
            SRC.CUSTOMER_ID,
            SRC.CREDIT_PRODUCT_SELECTION,
            SRC.ACQUISITION_OFFER,
            SRC.EXPERIENCE,
            SRC.TERMS_AND_CONDITIONS_BARCODE,
            SRC.IP_ADDRESS_VALUE,
            SRC.IP_ADDRESS_AUTHORITY,
            SRC.IP_ADDRESS_DATA_CLASSIFICATION,
            SRC.SHOPPER_ID,
            SRC.IOVATION_DEVICE_ID,
            SRC.CONTEXT_ID,
            SRC.EMAIL_VALUE,
            SRC.EMAIL_AUTHORITY,
            SRC.EMAIL_DATA_CLASSIFICATION,
            SRC.ANNUAL_INCOME_CURRENCY_CODE,
            SRC.ANNUAL_INCOME_SALARY_VALUE,
            SRC.ANNUAL_INCOME_SALARY_AUTHORITY,
            SRC.ANNUAL_INCOME_SALARY_DATA_CLASSIFICATION
        );

-- Remove records from temporary tables
DELETE FROM {db_env}_NAP_CREDIT_STG.CREDIT_APPLICATION_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
