/*
Supply Chain Ops Scorecard Main
Author: Shaila Karole
Date Created: 20/9/23
Date Last Updated: 15/04/24 - by Shaila Karole


Datalab:
Deletes and Inserts into Table: T2DL_DAS_OSU.WEEKLY_OPS_STANDUP
*/

---------------------------------------------------------------------------------------------------------------------------
-- code begins here --


CREATE MULTISET VOLATILE TABLE WEEKLY_OPS_STANDUP, --copy of the permanent table
FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1 
(
      OPS_NAME VARCHAR(50),
      BANNER VARCHAR(50),
      CHANNEL VARCHAR(50),
      METRIC_NAME VARCHAR(50),
      FISCAL_NUM INTEGER,
      FISCAL_DESC VARCHAR(50),
      LABEL VARCHAR(50),			-- Chart Plot Axis (x-axis)
      ROLLING_FISCAL_IND INTEGER,	-- identifier for Rolling & Forward weeks 
      PLAN_OP FLOAT,
      PLAN_CP FLOAT,
      TY FLOAT,
      LY FLOAT,						-- most recent completed week	
	  DAY_DATE DATE					-- Adding new column to accomodate Holiday Season data
) PRIMARY INDEX (OPS_NAME,BANNER,METRIC_NAME,FISCAL_NUM,LABEL)  ON COMMIT PRESERVE rows ;


-- WK Identifier for automating weekly plots
CREATE MULTISET VOLATILE TABLE CURR_WK AS (
SELECT WEEK_IDNT
, WEEK_START_DAY_DATE
, WEEK_END_DAY_DATE
, MONTH_IDNT
, MONTH_START_DAY_DATE
, MONTH_END_DAY_DATE
FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM
WHERE day_date = {start_date} - 7
) WITH data PRIMARY INDEX (WEEK_IDNT) ON COMMIT PRESERVE rows ;


-- CAL_LKUP;
CREATE MULTISET VOLATILE TABLE CAL_LKUP AS (
SELECT DISTINCT
a.WEEK_NUM
,a.week_of_fyr
, a.WEEK_454_NUM
, a.MONTH_SHORT_DESC
, b.WEEK_START_DAY_DATE
, b.WEEK_END_DAY_DATE
, a.MONTH_NUM
, b.MONTH_START_DAY_DATE
, b.MONTH_END_DAY_DATE
, a.YEAR_NUM
FROM PRD_NAP_USR_VWS.DAY_CAL a
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b
on a.WEEK_NUM = b.WEEK_IDNT
and a.MONTH_NUM = b.MONTH_IDNT
WHERE b.day_date BETWEEN {start_date}-42 AND {start_date}+21
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;



-- DC Inbound Days of Backlog   
CREATE MULTISET VOLATILE TABLE DC_INBOUND AS (
SELECT
week_num
,MONTH_SHORT_DESC
,WEEK_454_NUM
,CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND
,DAYS_OF_BACKLOG 
,ACTUAL_BACKLOG
FROM
(SELECT "Date",AVG(DAYS_OF_BACKLOG) AS DAYS_OF_BACKLOG , SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG --To find average of (days of backlog) at site level
FROM 
(SELECT "Date", ss_Ops_Site_DC_Only_Locations, SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG, (SUM(DAYS_TO_PROCESS_NUMERATOR)/SUM(ACTUAL_BACKLOG)) AS DAYS_OF_BACKLOG --To find sum of values at site and date level
FROM T2DL_SCA_VWS.DC_INBOUND_DAILY_PROJECTIONS_FCT_VW
WHERE DOW = 'Sat' AND ss_Ops_Site_DC_Only_Locations like '%DC%' AND ACTUAL_BACKLOG <> 0
AND "Date" BETWEEN {start_date}-50 AND {start_date} +50 
GROUP BY 1,2)a
GROUP BY 1)b
JOIN CAL_LKUP c ON b."date" = c.week_end_day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'DC Inbound Days of Backlog (DAYS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, 3.5 AS PLAN_OP
	, NULL AS PLAN_CP
	, DAYS_OF_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
DC_INBOUND;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'DC Inbound Days of Backlog (UNITS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, NULL AS PLAN_OP
	, NULL AS PLAN_CP
	, ACTUAL_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
DC_INBOUND;


-- FC Inbound Days of Backlog  
CREATE MULTISET VOLATILE TABLE FC_INBOUND AS (
SELECT
week_num
,MONTH_SHORT_DESC
,WEEK_454_NUM
,CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND
,DAYS_OF_BACKLOG 
,ACTUAL_BACKLOG
FROM
(SELECT "Date",AVG(DAYS_OF_BACKLOG) AS DAYS_OF_BACKLOG , SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG --To find average of (days of backlog) at site level
FROM 
(SELECT "Date",ss_Ops_Site_Outbound_ops,SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG, (SUM(DAYS_TO_PROCESS_NUMERATOR)/SUM(ACTUAL_BACKLOG)) AS DAYS_OF_BACKLOG --To find sum of values at site and date level
FROM T2DL_SCA_VWS.DAILY_INBOUND_FCT_VW
WHERE DOW = 'Sat' AND ss_Business_Unit_21_Day_Labor <> 'TC' AND ACTUAL_BACKLOG <> 0 
AND "Date" BETWEEN {start_date}-50 AND {start_date} +50
GROUP BY 1,2)a
GROUP BY 1)b 
JOIN CAL_LKUP c ON b."date" = c.week_end_day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'FC Inbound Days of Backlog (DAYS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, 3.5 AS PLAN_OP
	, NULL AS PLAN_CP
	, DAYS_OF_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
FC_INBOUND;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'FC Inbound Days of Backlog (UNITS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, NULL AS PLAN_OP
	, NULL AS PLAN_CP
	, ACTUAL_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
FC_INBOUND;


-- FC Outbound Days of Backlog 
CREATE MULTISET VOLATILE TABLE FC_OUTBOUND AS (
SELECT
WEEK_NUM
,MONTH_SHORT_DESC
,WEEK_454_NUM
,CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND
,DAYS_OF_BACKLOG
,ACTUAL_BACKLOG
FROM
(SELECT "Date",AVG(DAYS_OF_BACKLOG) AS DAYS_OF_BACKLOG , SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG --To find average of (days of backlog) at site level
FROM 
(SELECT "Date",ss_Ops_Site_Outbound_ops,SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG, (SUM(DAYS_TO_PROCESS_NUMERATOR)/SUM(ACTUAL_BACKLOG)) AS DAYS_OF_BACKLOG --To find sum of values at site and date level
FROM T2DL_SCA_VWS.DAILY_OUTBOUND_FCT_VW
WHERE DOW = 'Sat' AND ACTUAL_BACKLOG <> 0 
AND "Date" BETWEEN {start_date}-50 AND {start_date} +50
GROUP BY 1,2)a
GROUP BY 1)b 
JOIN CAL_LKUP c ON b."date" = c.week_end_day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'FC Outbound Days of Backlog (DAYS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, 2 AS PLAN_OP
	, NULL AS PLAN_CP
	, DAYS_OF_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
FC_OUTBOUND;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'FC Outbound Days of Backlog (UNITS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, NULL AS PLAN_OP
	, NULL AS PLAN_CP
	, ACTUAL_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
FC_OUTBOUND;


-- Store Returns Inspect Days of Backlog
CREATE MULTISET VOLATILE TABLE STORE_RETURNS AS (
SELECT
week_num
,MONTH_SHORT_DESC
,WEEK_454_NUM
,CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND
,DAYS_OF_BACKLOG
,ACTUAL_BACKLOG
FROM
(SELECT "Date",AVG(DAYS_OF_BACKLOG) AS DAYS_OF_BACKLOG , SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG --To find average of (days of backlog) at site level
FROM 
(SELECT "Date",ss_Ops_Site_Returns_inspect_ops,SUM(ACTUAL_BACKLOG) AS ACTUAL_BACKLOG, (SUM(DAYS_TO_PROCESS_NUMERATOR)/SUM(ACTUAL_BACKLOG)) AS DAYS_OF_BACKLOG --To find sum of values at site and date level
FROM T2DL_SCA_VWS.DAILY_RETURNS_INSPECTIONS_FCT_VW
WHERE DOW = 'Sat' AND ACTUAL_BACKLOG <> 0 AND Return_Locations <> 'Mail'
AND "Date" BETWEEN {start_date}-50 AND {start_date} +50
GROUP BY 1,2)a
GROUP BY 1)b 
JOIN CAL_LKUP c ON b."date" = c.week_end_day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'Store Returns Inspect Days of Backlog (DAYS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, 3.5 AS PLAN_OP
	, NULL AS PLAN_CP
	, DAYS_OF_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
STORE_RETURNS;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'Store Returns Inspect Days of Backlog (UNITS)' AS METRIC_NAME
	, WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, ROLLING_FISCAL_IND
	, NULL AS PLAN_OP
	, NULL AS PLAN_CP
	, ACTUAL_BACKLOG AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
STORE_RETURNS;


-- Mail Returns Drop-Off to Credit P50 and P90
-- To get USPS Minimum Timestamp against each RMA_ID AND TRACKING NUMBER
CREATE MULTISET VOLATILE TABLE T1 AS ( 
SELECT
TRACKING_NUM
,RMA_ID
,CARRIER_CODE
,SHIPMENT_ID
,MIN(ACTIVITY_TMSTP) AS USPS_FEDEX_SCAN_Min_Activity 
FROM
(SELECT
TRACKING_NUM
,RMA_ID
,CARRIER_CODE
,SHIPMENT_ID
,COALESCE (ACTIVITY_TMSTP_PACIFIC, ACTIVITY_TMSTP_LOCAL) as ACTIVITY_TMSTP
,CASE when (CARRIER_CODE = 'fdeg' and SHIPMENT_STATUS = 'in_transit' AND SHIPMENT_DESCRIPTION NOT LIKE '%Label%') THEN 'USPS_FEDEX_SCAN'
when (CARRIER_CODE = 'nsfv' and SHIPMENT_STATUS = 'in_transit' AND SHIPMENT_DESCRIPTION NOT LIKE '%Label%') THEN 'USPS_FEDEX_SCAN'
when (CARRIER_CODE = 'fdeg' and SHIPMENT_STATUS = 'out_for_delivery') THEN 'USPS_FEDEX_SCAN'
when SHIPMENT_DESCRIPTION like '%Newigistcs%' THEN 'PB_SCAN'
when SHIPMENT_DESCRIPTION like '%Pitney Bowes%' THEN 'PB_SCAN'
when SHIPMENT_DESCRIPTION in ('Delivered to FDR facility', 'Container prepared for shipment') THEN 'PB_SCAN'
when SHIPMENT_STATUS = 'delivered' THEN 'DELIVERY_SCAN'
WHEN (SHIPMENT_DESCRIPTION  LIKE '%Label%' OR SHIPMENT_DESCRIPTION  LIKE '%Pick%' )THEN 'NOT_USED_SCAN'
ELSE 'USPS_FEDEX_SCAN' END AS SCANNED_STATUS
FROM PRD_NAP_USR_VWS.CUSTOMER_SHIPMENT_TRACKING_EVENT_FACT fact
JOIN PRD_NAP_USR_VWS.DAY_CAL dc ON CAST (fact.ACTIVITY_TMSTP AS DATE) = dc.day_date
WHERE CARRIER_CODE in ('nfsv', 'fdeg')
AND MAIL_IN_RETURN_IND = 'Y'
AND EVENT_TYPE = 'SHIPMENT_TRACKING'
AND RMA_ID IS NOT NULL
AND WEEK_NUM in (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP) 
)a
WHERE SCANNED_STATUS = 'USPS_FEDEX_SCAN'
AND ACTIVITY_TMSTP IS NOT NULL
GROUP BY 1,2,3,4
) WITH data PRIMARY INDEX (TRACKING_NUM,SHIPMENT_ID,RMA_ID) ON COMMIT PRESERVE ROWS ;


-- To get timestamps for when the return was first scanned and when the return invoice was created.
CREATE MULTISET VOLATILE TABLE T2 AS (
SELECT
RMA_ID
,TRACKING_NUM
,PURCHASE_ID
,SKU_ID
,LINE_ITEM_ID
,max(shipment_ID) as shipment_id
,max(return_invoiced_tmstp_pacific) AS return_invoiced_tmstp_pacific
,max(SHIPMENT_FIRST_SCAN_TMSTP_PACIFIC) as SHIPMENT_FIRST_SCAN_TMSTP_PACIFIC
FROM PRD_NAP_USR_VWS.CUSTOMER_ITEM_RETURN_FACT fact
JOIN PRD_NAP_USR_VWS.DAY_CAL dc ON CAST (fact.return_invoiced_tmstp_pacific AS DATE) = dc.day_date
WHERE RMA_ID IS NOT NULL
AND return_invoiced_tmstp_pacific IS NOT NULL
AND WEEK_NUM IN (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP) 
group by 1,2,3,4,5
) WITH data PRIMARY INDEX (TRACKING_NUM,SHIPMENT_ID,RMA_ID) ON COMMIT PRESERVE ROWS ;


CREATE MULTISET VOLATILE TABLE T3 AS (
SELECT DISTINCT
r.RMA_ID
,r.TRACKING_NUM
,carrier_code
,return_invoiced_tmstp_pacific
,coalesce(r.SHIPMENT_FIRST_SCAN_TMSTP_PACIFIC, cte.USPS_FEDEX_SCAN_Min_Activity) AS "USPS-FedEx First Scan Tmstp Pacific"
,CAST(return_invoiced_tmstp_pacific AS DATE) AS "DATE"
,week_idnt
FROM T2 r
left join T1 cte
ON r.TRACKING_NUM = cte.tracking_num
AND r.RMA_ID = cte.RMA_ID
AND r.shipment_id = cte.SHIPMENT_ID
JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM q ON "DATE" = q.day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
) WITH data PRIMARY INDEX (TRACKING_NUM,RMA_ID) ON COMMIT PRESERVE rows ;



CREATE MULTISET VOLATILE TABLE MAIL_RETURNS AS (
SELECT week_idnt
,1.00*CAST((1000*PERCENTILE_DISC(.5) WITHIN GROUP (ORDER BY MAIL_RETURNS_DAYS ASC)) AS INT)/1000	AS P50
,1.00*CAST((1000*PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY MAIL_RETURNS_DAYS ASC)) AS INT)/1000	AS P90
FROM
(SELECT "DATE"
, RMA_ID
, TRACKING_NUM
, week_idnt
, (MAIL_RETURNS_SECONDS/86400) AS MAIL_RETURNS_DAYS
FROM
(SELECT "DATE"
,week_idnt
, RMA_ID
, TRACKING_NUM
, max((CAST(((return_invoiced_tmstp_pacific- "USPS-FedEx First Scan Tmstp Pacific") DAY(4)) AS BIGINT) * 86400)
+ ((EXTRACT(HOUR FROM return_invoiced_tmstp_pacific) - EXTRACT(HOUR FROM "USPS-FedEx First Scan Tmstp Pacific")) * 3600)
+ ((EXTRACT(MINUTE FROM return_invoiced_tmstp_pacific) - EXTRACT(MINUTE FROM "USPS-FedEx First Scan Tmstp Pacific")) * 60)
+ (EXTRACT(SECOND FROM return_invoiced_tmstp_pacific) - EXTRACT(SECOND FROM "USPS-FedEx First Scan Tmstp Pacific")))AS MAIL_RETURNS_SECONDS
FROM T3
group by 1,2,3,4
) a ) a
group by 1 ) WITH data PRIMARY INDEX (week_idnt) ON COMMIT PRESERVE rows ;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'Mail Returns Drop-Off to Credit (P50)' AS METRIC_NAME
	, x.week_idnt AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 7.5 AS PLAN_OP
	, NULL AS PLAN_CP
	, P50 AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM MAIL_RETURNS x
JOIN CAL_LKUP y ON x.week_idnt = y.week_num;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'Mail Returns Drop-Off to Credit (P90)' AS METRIC_NAME
	, x.week_idnt AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 11.5 AS PLAN_OP
	, NULL AS PLAN_CP
	, P90 AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM MAIL_RETURNS x
JOIN CAL_LKUP y ON x.week_idnt = y.week_num;


-- Store On Time Delivery
CREATE MULTISET VOLATILE TABLE STORE_ONTIME AS (
SELECT
WEEK_IDNT as week_num
,(SUM (ON_TIME+ONTIME+THRESH)*100.0)/(SUM(ON_TIME+ONTIME+THRESH+CRITICAL+CRITICAL_LATE+LATE)*1.0) AS ONTIME_DELIVERY
FROM
(SELECT 
Appt_Date,
COUNT( CASE WHEN Delivery_Status = 'On-Time' THEN 1 END) AS ON_TIME,
COUNT( CASE WHEN Delivery_Status = 'On Time' THEN 1 END) AS ONTIME,
COUNT( CASE WHEN Delivery_Status = 'Threshold' THEN 1 END) AS THRESH,
COUNT( CASE WHEN Delivery_Status = 'Critical Late' THEN 1 END) AS CRITICAL,
COUNT( CASE WHEN Delivery_Status = 'CriticalLate' THEN 1 END) AS CRITICAL_LATE,
COUNT( CASE WHEN Delivery_Status = 'Late' THEN 1 END) AS LATE
FROM T3DL_CTRAN_SCM.StoreDeliveryOperationalData_VW 
WHERE Delivery_Status IS NOT NULL AND Order_Number IS NOT NULL
GROUP BY 1)a
JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b ON a.Appt_Date = b.day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1
) WITH data PRIMARY INDEX (week_num) ON COMMIT PRESERVE rows ;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'Store On Time Delivery' AS METRIC_NAME
	, x.week_num AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 95 AS PLAN_OP
	, NULL AS PLAN_CP
	, ONTIME_DELIVERY AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM STORE_ONTIME x
JOIN CAL_LKUP y ON x.week_num = y.week_num;


-- FC On Time Delivery to Promise
CREATE MULTISET VOLATILE TABLE FC_ONTIME AS (
SELECT 
WEEK_IDNT as week_num
,CAST(SUM(Y_PKG) AS FLOAT) AS Y_PKG 	
,CAST(SUM(TOTAL_PKG) AS FLOAT) AS TOTAL_PKG
FROM
(SELECT 
DISTINCT DELIVERY_DATE,
SUM(CASE WHEN ON_TM_FST_DLVRY_ATMPT = 'Y' THEN PKG ELSE 0 END) AS Y_PKG,
SUM(PKG) AS TOTAL_PKG
from
(SELECT 
CAST(CSSF.CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE) AS DELIVERY_DATE,
COUNT(CSSF.TRACKING_NUM) AS PKG,
CAST(CSSF.REQUESTED_MAX_PROMISE_TMSTP_PACIFIC AS DATE) AS PROMISE_DATE,
CASE 
WHEN CAST(CSSF.CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE) > PROMISE_DATE THEN 'N'
WHEN CAST(CSSF.CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE) <= PROMISE_DATE THEN 'Y'
ELSE NULL
END AS ON_TM_FST_DLVRY_ATMPT
FROM PRD_NAP_USR_VWS.CUSTOMER_SHIPMENT_SUMMARY_FACT CSSF  
INNER JOIN
(SELECT DISTINCT OLDF.CARRIER_TRACKING_NUM
		, max(COALESCE(OLDF.CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC,OLDF.CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_LOCAL)) AS DEL_DT
		, OLDF.CARRIER_TRACKING_NUM AS TRCK_NO
 		, PROMISE_TYPE_CODE
		, OLDF.SHIPPED_DATE_PACIFIC
		, RQLOS.ORD_LOS_MED_DESC
	FROM PRD_NAP_USR_VWS.ORDER_LINE_DETAIL_FACT OLDF
	LEFT JOIN T2DL_DAS_OSU.ORD_LOS_DIM RQLOS
    ON (OLDF.REQUESTED_LEVEL_OF_SERVICE_CODE = RQLOS.ORD_LOS_CD)
    WHERE 1=1 AND 
    SHIPPED_NODE_TYPE_CODE = 'FC' AND ORD_LOS_MED_DESC IN ('Ground Service','Standard Shipping','Standard Sign Reqd','Cedar Pick Up','Saturday','Saturday Sign Reqd') 
    AND SHIPPED_DATE_PACIFIC >= (Select (WEEK_START_DAY_DATE -50) from curr_wk )
    GROUP BY 1,3,4,5,6)ca ON CSSF.TRACKING_NUM = CA.TRCK_NO AND CAST(CSSF.CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE) = CA.DEL_DT 
    GROUP BY 1,3,4)a 
   group by 1)b
  JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM c ON b.DELIVERY_DATE = c.day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1
) WITH data PRIMARY INDEX (week_num) ON COMMIT PRESERVE ROWS ;


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'FC On Time Delivery to Promise' AS METRIC_NAME
	, x.week_num AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 97 AS PLAN_OP
	, NULL AS PLAN_CP
	, CASE WHEN TOTAL_PKG = 0 THEN 0 ELSE (Y_PKG*100/TOTAL_PKG)END AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM FC_ONTIME x
JOIN CAL_LKUP y ON x.week_num = y.week_num;


-- Click to Delivery
CREATE MULTISET VOLATILE TABLE CLICK_TO_DELIVERY AS
(SELECT WEEK_IDNT as week_num
,CHANNEL
,NODE_TYPE
,AVG(P50) AS P50
,AVG(P90) AS P90
FROM
(SELECT
DELIVERY_DATE
,CHANNEL
,NODE_TYPE
,1.00*CAST((1000*PERCENTILE_DISC(.5) WITHIN GROUP (ORDER BY CLICK_TO_DELIVERY ASC)) AS INT)/1000	AS P50
,1.00*CAST((1000*PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY CLICK_TO_DELIVERY ASC)) AS INT)/1000	AS P90
FROM
(SELECT
DELIVERY_DATE
,CHANNEL
,NODE_TYPE
,ORDER_NUM
,CARRIER_TRACKING_NUM
,ORDER_DATE_PACIFIC
,CASE	
	WHEN CLICK_TO_DELIVERY_SECONDS IS NULL THEN CAST(NULL AS FLOAT)
	WHEN CAST(CLICK_TO_DELIVERY_SECONDS AS FLOAT)/86400 > 20 THEN 	20
	WHEN CAST(CLICK_TO_DELIVERY_SECONDS AS FLOAT)/86400 <= 0 THEN  	CAST(NULL AS FLOAT)
	ELSE ROUND(CAST(CLICK_TO_DELIVERY_SECONDS AS FLOAT)/86400, 2)
	END AS CLICK_TO_DELIVERY
FROM
(SELECT
ORDER_NUM
,CARRIER_TRACKING_NUM
,ORDER_DATE_PACIFIC
,MAX(CAST(CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE)) AS DELIVERY_DATE
,CASE WHEN  SOURCE_CHANNEL_CODE = 'FULL_LINE' THEN 'N.COM'
	  WHEN  SOURCE_CHANNEL_CODE = 'RACK' THEN 'R.COM'  END AS CHANNEL
,CASE  WHEN LAST_RELEASED_NODE_TYPE_CODE = 'DS' THEN 'DROPSHIP' ELSE 'OWNED' END AS NODE_TYPE
,MAX((CAST(((CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC- ORDER_TMSTP_PACIFIC) DAY(4)) AS BIGINT) * 86400)
 + ((EXTRACT(HOUR FROM CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC) - EXTRACT(HOUR FROM ORDER_TMSTP_PACIFIC))* 3600)
 + ((EXTRACT(MINUTE FROM CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC) - EXTRACT(MINUTE FROM ORDER_TMSTP_PACIFIC)) * 60)
 +  (EXTRACT(SECOND FROM CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC) - EXTRACT(SECOND FROM ORDER_TMSTP_PACIFIC))) AS CLICK_TO_DELIVERY_SECONDS
WHERE CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC > SHIPPED_TMSTP_PACIFIC
AND SHIPPED_TMSTP_PACIFIC > ORDER_TMSTP_PACIFIC
AND CAST(CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE) > {start_date} - 52
AND CAST(CARRIER_FIRST_ATTEMPTED_DELIVERY_TMSTP_PACIFIC AS DATE) < {start_date} + 1
FROM PRD_NAP_USR_VWS.ORDER_LINE_DETAIL_FACT
GROUP BY 1,2,3,5,6)a)a
GROUP BY 1,2,3)a
JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b ON a.DELIVERY_DATE = b.day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3
) WITH DATA PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS;

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, CASE  WHEN CHANNEL = 'N.COM' THEN 'NORDSTROM' ELSE 'NORDSTROM RACK' END AS BANNER
	, CHANNEL AS CHANNEL
	, 'Click to Delivery DROPSHIP (P50)' AS METRIC_NAME
	, x.week_num AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 5.2 AS PLAN_OP
	, NULL AS PLAN_CP
	, P50 AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM CLICK_TO_DELIVERY x
JOIN CAL_LKUP y ON x.week_num = y.week_num
WHERE NODE_TYPE = 'DROPSHIP';


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, CASE  WHEN CHANNEL = 'N.COM' THEN 'NORDSTROM' ELSE 'NORDSTROM RACK' END AS BANNER
	, CHANNEL AS CHANNEL
	, 'Click to Delivery DROPSHIP (P90)' AS METRIC_NAME
	, x.week_num AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 8 AS PLAN_OP
	, NULL AS PLAN_CP
	, P90 AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM CLICK_TO_DELIVERY x
JOIN CAL_LKUP y ON x.week_num = y.week_num
WHERE NODE_TYPE = 'DROPSHIP';

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, CASE  WHEN CHANNEL = 'N.COM' THEN 'NORDSTROM' ELSE 'NORDSTROM RACK' END AS BANNER
	, CHANNEL AS CHANNEL
	, 'Click to Delivery OWNED (P50)' AS METRIC_NAME
	, x.week_num AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 5.2 AS PLAN_OP
	, NULL AS PLAN_CP
	, P50 AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM CLICK_TO_DELIVERY x
JOIN CAL_LKUP y ON x.week_num = y.week_num
WHERE NODE_TYPE = 'OWNED';

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, CASE  WHEN CHANNEL = 'N.COM' THEN 'NORDSTROM' ELSE 'NORDSTROM RACK' END AS BANNER
	, CHANNEL AS CHANNEL
	, 'Click to Delivery OWNED (P90)' AS METRIC_NAME
	, x.week_num AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 8 AS PLAN_OP
	, NULL AS PLAN_CP
	, P90 AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM CLICK_TO_DELIVERY x
JOIN CAL_LKUP y ON x.week_num = y.week_num
WHERE NODE_TYPE = 'OWNED';


-- PPH
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'PPH' AS METRIC_NAME
	,  b.week_num AS FISCAL_NUM
	, 'Week'  AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 15 AS PLAN_OP
	, NULL AS PLAN_CP
	, ACTUAL_PPH AS TY  
	, WIG_PPH AS LY
	, NULL AS DAY_DATE
FROM
(SELECT
FiscalYear,
FiscalWeek,
case when ACTUAL_HOURS = 0 then 0 else ACTUAL_UNITS/ACTUAL_HOURS end AS ACTUAL_PPH,
case when WIG_HOURS = 0 then 0 else WIG_UNITS/WIG_HOURS end AS WIG_PPH --Wildly Important Goal (LY)
from
(SELECT FiscalYear
,FiscalWeek
, SUM(CASE WHEN Scenario = 'Actual' THEN Units ELSE 0 END) AS ACTUAL_UNITS
, SUM(CASE WHEN Scenario = 'Actual' THEN TotalHours ELSE 0 END) AS ACTUAL_HOURS
, SUM(CASE WHEN Scenario = 'WIG Baseline' THEN Units ELSE 0 END) AS WIG_UNITS
, SUM(CASE WHEN Scenario = 'WIG Baseline' THEN Hours ELSE 0 END) AS WIG_HOURS
FROM T2DL_SCA_VWS.PPH_WBR_FCT_VW
WHERE Building NOT IN ('NQC','0', 'LA LOH')
AND Department NOT IN ('Customer Returns', 'Rack Warehouse','Returns Inpection','Shipping Dock') --Inpection not a typo
AND "Date" BETWEEN {start_date} - 45 AND {start_date}
GROUP BY 1,2
)a) a
JOIN CAL_LKUP b ON a.FiscalYear = b.year_num AND a.FiscalWeek = b.week_of_fyr
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK);


-- DC Forecast Accuracy
CREATE MULTISET VOLATILE TABLE DC_FORECAST AS (
SELECT WEEK_NUM,
SUM(Incoming_Actual) AS Incoming_Actual, 
SUM(Incoming_Projected) AS Incoming_Projected,
(AVG("ERROR")*100.00) AS MAPE 
FROM
(SELECT
WEEK_IDNT as WEEK_NUM,
ss_Ops_Site_DC_Only_Locations,
SUM(Incoming_Actual) AS Incoming_Actual, 
SUM(Incoming_Projected) AS Incoming_Projected,
ABS(CASE WHEN (SUM(Incoming_Projected)) = 0 THEN 0 ELSE ((SUM(Incoming_Actual)) - (SUM(Incoming_Projected)))/(SUM(Incoming_Projected)) END) AS "ERROR"
FROM
(SELECT "Date", ss_Ops_Site_DC_Only_Locations, SUM(Incoming_Actual) AS Incoming_Actual, SUM(Incoming_Projected) AS Incoming_Projected 
FROM T2DL_SCA_VWS.DC_INBOUND_DAILY_PROJECTIONS_FCT_VW
WHERE  "Date" BETWEEN {start_date}-50 AND {start_date} 
AND ss_Ops_Site_DC_Only_Locations LIKE ('DC%')
GROUP BY 1,2)a
JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b ON a."Date" = b.day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2)a
GROUP BY 1
) WITH DATA PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS ;


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'DC Forecast Accuracy' AS METRIC_NAME
	, x.WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, Incoming_Projected AS PLAN_OP
	, NULL AS PLAN_CP
	, Incoming_Actual AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
DC_FORECAST  x
JOIN CAL_LKUP y ON x.week_num = y.week_num;


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'DC Forecast Accuracy (MAPE)' AS METRIC_NAME
	, x.WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, NULL AS PLAN_OP
	, 15 AS PLAN_CP
	, MAPE AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM
DC_FORECAST  x
JOIN CAL_LKUP y ON x.week_num = y.week_num;

-- P&H Inventory Speed
CREATE MULTISET VOLATILE TABLE INV_SPEED AS (
SELECT
WeekNumReceipt AS WEEK_NUM,
1.00*CAST((1000*PERCENTILE_DISC(.5) WITHIN GROUP (ORDER BY DATEDIFF ASC)) AS INT)/1000	AS P50,
1.00*CAST((1000*PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY DATEDIFF ASC)) AS INT)/1000	AS P90
FROM
(SELECT
operation_number,
shipment_number,
item_product_id,
CAST(create_time AS DATE AT SOURCE TIME ZONE) AS create_dt, 
CAST(receipt_date_utc AS DATE) AS receipt_dt,
WeekNumReceipt,
(receipt_dt - create_dt) AS DATEDIFF
FROM
(SELECT
rcisf.operation_number,
rcisf.shipment_number,
rcisf.item_product_id,
p.create_time,
rcisf.receipt_date_utc,
RD.week_num  AS WeekNumReceipt
FROM 
(SELECT DISTINCT
operation_number,
operation_type,
shipment_number,
item_product_id,
from_location_logical,
from_location_facility,
to_location_facility,
shipment_date_utc,
shipment_quantity,
receipt_date_utc,
receipt_quantity
FROM PRD_NAP_USR_VWS.RMS_COST_INTERNAL_SHIPMENT_FACT
where (from_location_logical = 697 or from_location_logical = 297) 
and receipt_date_utc >= '2023-05-01'
and operation_type = 'TRANSFER'
)  rcisf
LEFT JOIN PRD_NAP_USR_VWS.RMS_COST_TRANSFERS_FACT P
on rcisf.operation_number = p.transfer_num and p.rms_sku_num =rcisf.item_product_id and p.from_location_logical=rcisf.from_location_logical
left join PRD_NAP_USR_VWS.STORE_DIM T
On rcisf.to_location_facility = t.store_num
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL RD
on rcisf.receipt_date_utc = RD.day_date
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL CRD
on cast(p.create_time as date) = CRD.day_date
WHERE p.transfer_context_type in ('RACK_PACK_AND_HOLD'))a
JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b ON a.receipt_date_utc = b.day_date
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK))a
group by 1
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'SUPPLYCHAIN' AS OPS_NAME
, NULL AS BANNER
, NULL AS CHANNEL
, 'P&H Inventory Speed (P50)' AS METRIC_NAME
, x.week_num AS FISCAL_NUM
, 'WEEK' AS FISCAL_DESC
, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
, NULL AS ROLLING_FISCAL_IND
, 35 AS PLAN_OP
, NULL AS PLAN_CP
, P50 AS TY
, NULL AS LY
, NULL AS DAY_DATE
FROM INV_SPEED x
JOIN CAL_LKUP y ON x.week_num = y.week_num;


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'SUPPLYCHAIN' AS OPS_NAME
, NULL AS BANNER
, NULL AS CHANNEL
, 'P&H Inventory Speed (P90)' AS METRIC_NAME
, x.week_num AS FISCAL_NUM
, 'WEEK' AS FISCAL_DESC
, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
, NULL AS ROLLING_FISCAL_IND
, 35 AS PLAN_OP
, NULL AS PLAN_CP
, P90 AS TY
, NULL AS LY
, NULL AS DAY_DATE
FROM INV_SPEED x
JOIN CAL_LKUP y ON x.week_num = y.week_num;


--In Yard to Trailer Empty
CREATE MULTISET VOLATILE TABLE tchk AS (
SELECT location_id
, CASE
  WHEN location_id IN (89)  THEN 'Portland, OR'
  WHEN location_id IN (299) THEN 'Dubuque, IA'
  WHEN location_id IN (399) THEN 'Ontario, CA'
  WHEN location_id IN (499) THEN 'Newark, CA'
  WHEN location_id IN (599) THEN 'Cedar Rapids, IA'
  WHEN location_id IN (699) THEN 'Upper Marlboro, MD'
  WHEN location_id IN (799) THEN 'Gainesville, FL'
  WHEN location_id IN (569) THEN 'ECFC'
  WHEN location_id IN (584) THEN 'WCOC'
  WHEN location_id IN (808) THEN 'MWFC'
  WHEN location_id IN (879) THEN 'SBFC'
  END AS location_name
, event_name
, MIN(event_time)                                   AS event_time
, CAST(MIN(event_time) AS DATE AT SOURCE TIME ZONE) AS event_dt
, carrier_bill_of_lading
, trailer_num
, trailer_type
, appointment_id
FROM prd_nap_usr_vws.yard_trailer_v2_event_fact ytef
WHERE 1 = 1
AND trailer_type = 'INBOUND'
AND event_name = 'TrailerCheckedIntoYard'
GROUP BY location_id, event_name, carrier_bill_of_lading, trailer_num, trailer_type, appointment_id
) WITH data PRIMARY INDEX (location_id) ON COMMIT PRESERVE rows ;
     
     
CREATE MULTISET VOLATILE TABLE temp AS (
      SELECT location_id
           , event_name
           , MAX(event_time)                                   AS event_time
           , CAST(MAX(event_time) AS DATE AT source TIME ZONE) AS event_dt
           , carrier_bill_of_lading
           , trailer_num
           , trailer_type
           , appointment_id
        FROM prd_nap_usr_vws.yard_trailer_v2_event_fact ytef
       WHERE 1 = 1
         AND event_name = 'TrailerMarkedEmpty'
       GROUP BY location_id, event_name, carrier_bill_of_lading, trailer_num, trailer_type, appointment_id
) WITH data PRIMARY INDEX (location_id) ON COMMIT PRESERVE rows ;


CREATE MULTISET VOLATILE TABLE chk2emp AS (
      SELECT tchk.location_id
           , tchk.location_name
           , tchk.event_name
           , tchk.event_time                                   AS chk_event
           , CAST(tchk.event_time AS DATE AT source TIME ZONE) AS chk_event_dt
           , temp.event_time                                   AS emp_event
           , CAST(temp.event_time AS DATE AT source TIME ZONE) AS emp_event_dt
           , (CAST((CAST(temp.event_time AS DATE AT source TIME ZONE) -
                    CAST(tchk.event_time AS DATE AT source TIME ZONE)) AS DECIMAL(18, 6)) * 60 * 24) +
             ((EXTRACT(HOUR FROM temp.event_time) - EXTRACT(HOUR FROM tchk.event_time)) * 60) +
             ((EXTRACT(MINUTE FROM temp.event_time) - EXTRACT(MINUTE FROM tchk.event_time))) +
             ((EXTRACT(SECOND FROM temp.event_time) - EXTRACT(SECOND FROM tchk.event_time)) /
              60)                                              AS "Difference in Minutes"
           , tchk.carrier_bill_of_lading
           , tchk.trailer_num
           , tchk.trailer_type
           , tchk.appointment_id
        FROM tchk
             JOIN temp
                  ON tchk.appointment_id = temp.appointment_id
       WHERE 1 = 1
         AND tchk.event_time < temp.event_time
 ) WITH data PRIMARY INDEX (location_id) ON COMMIT PRESERVE rows ;


CREATE MULTISET VOLATILE TABLE DCFC_P90 AS (
SELECT chk2emp.location_id
     , chk2emp.location_name
     , week_idnt 
     , (percentile_cont(0.9) within GROUP (ORDER BY chk2emp."Difference in Minutes") / 1440) AS p90_dd
  FROM chk2emp
  JOIN t2dl_sca_vws.day_cal_454_dim_vw cal
  ON chk2emp.emp_event_dt = cal.day_date
 WHERE 1 = 1
   AND cal.trailing_future_week BETWEEN -53 AND 0
   AND location_id IN (89, 299, 399, 499, 699, 799, 569, 584, 808, 879)
   AND "Difference In Minutes" < 43200
 GROUP BY 1, 2, 3
) WITH data PRIMARY INDEX (location_id) ON COMMIT PRESERVE rows ;



CREATE MULTISET VOLATILE TABLE DC_IYTE AS ( 
SELECT week_idnt AS WEEK_NUM
,AVG(p90_dd) AS DC_P90
FROM DCFC_P90 a
JOIN CAL_LKUP b ON a.week_idnt = b.week_num
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
AND location_id IN (89, 299, 399, 499, 699, 799)
GROUP BY 1
) WITH DATA PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS ;


CREATE MULTISET VOLATILE TABLE FC_IYTE AS ( 
SELECT week_idnt AS WEEK_NUM
,AVG(p90_dd) AS FC_P90
FROM DCFC_P90
WHERE 1=1
AND location_id IN (569, 584, 808, 879)
AND WEEK_NUM in (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP)
GROUP BY 1
) WITH DATA PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS ;


CREATE MULTISET VOLATILE TABLE DCFC_DIFF AS ( 
SELECT WEEK_NUM
,1-(DCFC_P90/8.4) AS DCFC_DIFF
FROM
(SELECT a.WEEK_NUM
, (DC_P90+FC_P90)/2 AS DCFC_P90
FROM FC_IYTE a
JOIN DC_IYTE b ON a.WEEK_NUM = b.WEEK_NUM)a
) WITH DATA PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS ;


--Click to ship
CREATE MULTISET VOLATILE TABLE CTS AS (
SELECT WEEK_NUM
,1-(CTS_P90/2.7) AS CTS_DIFF
FROM
(SELECT WEEK_NUM
,1.00*CAST((1000*PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY CLICK_TO_SHIP ASC)) AS INT)/1000	AS CTS_P90
FROM 
(SELECT ORDER_NUM
 , SHIPPED_DATE_PACIFIC
 , WEEK_NUM 
 , SOURCE_CHANNEL_CODE
 , NODE_TYPE
 , NODE
 , CLICK_TO_SHIP          
 FROM
 (SELECT OL.ORDER_NUM
  , OL.CARRIER_TRACKING_NUM
  , OL.SOURCE_CHANNEL_CODE
  , OL.NODE_TYPE
  , COALESCE(N.NODE_ALIAS, N.NODE_ABBR, OL."NODE", OL.NODE_TYPE) AS "NODE"
  , DDD.week_idnt AS WEEK_NUM
  , OL.SHIPPED_DATE_PACIFIC
  , CASE
   WHEN OL.CLICK_TO_SHIP_SECONDS IS NULL                     THEN CAST(NULL AS FLOAT)
   WHEN CAST(OL.CLICK_TO_SHIP_SECONDS AS FLOAT) / 86400 > 20 THEN 20
   WHEN CAST(OL.CLICK_TO_SHIP_SECONDS AS FLOAT) / 86400 <= 0 THEN CAST(NULL AS FLOAT)
   ELSE ROUND(CAST(OL.CLICK_TO_SHIP_SECONDS AS FLOAT) / 86400, 2) END AS CLICK_TO_SHIP
   FROM
   (SELECT OLDF.ORDER_NUM
    , OLDF.CARRIER_TRACKING_NUM
    , OLDF.SOURCE_CHANNEL_CODE
    , OLDF.SHIPPED_DATE_PACIFIC
    , CASE
      WHEN OLDF.LAST_RELEASED_NODE_TYPE_CODE = 'RK' THEN 'RACK_STORE'
      WHEN OLDF.LAST_RELEASED_NODE_TYPE_CODE = 'FL' THEN 'FLS'
      WHEN OLDF.LAST_RELEASED_NODE_TYPE_CODE = 'DS' THEN 'DS'
      WHEN OLDF.LAST_RELEASED_NODE_TYPE_CODE IN ('OF', 'LH', 'CR', 'OC', 'SS', 'FC', 'RS', 'DC')
      THEN 'FC'ELSE 'UNKNOWN'END AS NODE_TYPE
    , CASE
      WHEN NODE_TYPE IN ('FC', 'UNKNOWN') THEN OLDF.LAST_RELEASED_NODE_NUM
      ELSE NULL END AS "NODE"
    , MAX(OLDF.CREATED_TO_SHIPPED_LAG_SECS) AS CLICK_TO_SHIP_SECONDS
    FROM PRD_NAP_USR_VWS.ORDER_LINE_DETAIL_FACT OLDF
    GROUP BY 1,2,3,4,5,6) OL
    INNER JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM DDD ON DDD.day_date = OL.SHIPPED_DATE_PACIFIC
    LEFT JOIN T2DL_SCA_VWS.NODE_VW N ON N.NODE_NUMBER = CAST(OL."NODE" AS INT)) AS tbl
  WHERE 1 = 1
  AND NODE_TYPE = 'FC'
  AND WEEK_NUM in (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP)
  GROUP BY 1, 2, 3, 4, 5, 6, 7)a
GROUP BY 1)a
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows;

      
--Deliver to Credit     
CREATE MULTISET VOLATILE TABLE DELIVERED AS (      
SELECT TRACKING_NUM
,RMA_ID
,CARRIER_CODE
,SHIPMENT_ID
,MAX(COALESCE (ACTIVITY_TMSTP_PACIFIC,ACTIVITY_TMSTP_LOCAL)) AS MAX_ACTIVITY_TMSTP  --Delivered Timestamp       
FROM PRD_NAP_USR_VWS.CUSTOMER_SHIPMENT_TRACKING_EVENT_FACT 
WHERE CARRIER_CODE in ('nfsv', 'fdeg')
AND MAIL_IN_RETURN_IND = 'Y'
AND EVENT_TYPE = 'SHIPMENT_TRACKING'
AND RMA_ID is not null
AND SHIPMENT_STATUS = 'delivered'
GROUP BY 1,2,3,4
) WITH data PRIMARY INDEX (TRACKING_NUM,RMA_ID,SHIPMENT_ID) ON COMMIT PRESERVE ROWS ;


CREATE MULTISET VOLATILE TABLE CREDIT AS (     
SELECT RMA_ID
,TRACKING_NUM
,PURCHASE_ID
,SKU_ID
,LINE_ITEM_ID
,MAX(SHIPMENT_ID) AS SHIPMENT_ID 
,MAX(RETURN_INVOICED_TMSTP_PACIFIC) AS MAX_RETURN_INVOICED_TMSP --Credit Timestamp
,MAX(SHIPMENT_DELIVERED_TMSTP_PACIFIC) AS MAX_DELIVERED_TMSTP --Delivered Timestamp
FROM
PRD_NAP_USR_VWS.CUSTOMER_ITEM_RETURN_FACT 
GROUP BY 1,2,3,4,5
) WITH data PRIMARY INDEX (TRACKING_NUM,RMA_ID,SHIPMENT_ID) ON COMMIT PRESERVE ROWS ;


CREATE MULTISET VOLATILE TABLE DTC AS (
SELECT WEEK_NUM
,1-(DTC_P90/4.0) AS DTC_DIFF
FROM
(SELECT WEEK_NUM
,1.00*CAST((1000*PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY DIFF_IN_DAY ASC)) AS INT)/1000	AS DTC_P90
FROM
(SELECT CREDIT_DATE
,WEEK_NUM
,RMA_ID
,SKU_ID
,PURCHASE_ID
,(CAST((CAST(MAX_RETURN_INVOICED_TMSP AS DATE)- CAST(DELIVERED_TMSTP  AS DATE)) AS DECIMAL(18,6))*60*24)
    + ((EXTRACT(HOUR FROM MAX_RETURN_INVOICED_TMSP) - EXTRACT(HOUR FROM DELIVERED_TMSTP ))*60)
    + ((EXTRACT(MINUTE FROM MAX_RETURN_INVOICED_TMSP) - EXTRACT(MINUTE FROM DELIVERED_TMSTP )))
    + ((EXTRACT(SECOND FROM MAX_RETURN_INVOICED_TMSP) - EXTRACT(SECOND FROM DELIVERED_TMSTP ))/60)
AS DIFF_IN_MIN
,DIFF_IN_MIN/1440 AS DIFF_IN_DAY
FROM
(SELECT c.RMA_ID
,c.TRACKING_NUM
,c.PURCHASE_ID
,c.SKU_ID
,c.LINE_ITEM_ID
,c.SHIPMENT_ID 
,COALESCE (c.MAX_DELIVERED_TMSTP,d.MAX_ACTIVITY_TMSTP) AS DELIVERED_TMSTP
,c.MAX_RETURN_INVOICED_TMSP
,x.day_date AS CREDIT_DATE
,x.week_idnt AS WEEK_NUM
FROM CREDIT c
LEFT JOIN  DELIVERED d
ON c.TRACKING_NUM = d.TRACKING_NUM
AND c.RMA_ID = d.RMA_ID
AND c.SHIPMENT_ID  = d.SHIPMENT_ID
LEFT JOIN  PRD_NAP_USR_VWS.DAY_CAL_454_DIM x
ON x.day_date = CAST(c.MAX_RETURN_INVOICED_TMSP AS DATE)
WHERE 1=1
AND c.RMA_ID IS NOT NULL
AND WEEK_NUM in (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP)
GROUP BY 1,2,3,4,5,6,7,8,9,10)a)a
GROUP BY 1)a
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS;


--Received to Palletized
CREATE MULTISET VOLATILE TABLE RTP AS (
SELECT WEEK_NUM
,1-(RTP_P90/7.8) AS RTP_DIFF
FROM
(SELECT year_week AS WEEK_NUM,
 p90_dd AS RTP_P90
FROM T2DL_SCA_VWS.DC_CYCLETIME_PERCENTILE_BY_WK_VW 
WHERE STAGE = '0C: Received to Palletized' 
AND location_id = 'DC Network'
AND WEEK_NUM in (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP)
AND banner = 'All Up'
AND channel = 'All Up'
AND po_type = 'All Up'
AND pack_type = 'All Up')a
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS;


--Total Network Speed
CREATE MULTISET VOLATILE TABLE TOTAL_NETWORK_SPEED AS (
SELECT a.WEEK_NUM
,(RTP_DIFF+DTC_DIFF+CTS_DIFF+DCFC_DIFF)/4 AS TOTAL_NETWORK_SPEED
FROM RTP a
JOIN DTC b ON a.WEEK_NUM = b.WEEK_NUM
JOIN CTS c ON a.WEEK_NUM = c.WEEK_NUM
JOIN DCFC_DIFF d ON a.WEEK_NUM = d.WEEK_NUM
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE ROWS;


INSERT INTO WEEKLY_OPS_STANDUP
SELECT
	'SUPPLYCHAIN' AS OPS_NAME
	, NULL AS BANNER
	, NULL AS CHANNEL
	, 'TOTAL NETWORK SPEED' AS METRIC_NAME
	, x.WEEK_NUM AS FISCAL_NUM
	, 'WEEK' AS FISCAL_DESC
	, CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL
	, NULL AS ROLLING_FISCAL_IND
	, 0.35 AS PLAN_OP
	, NULL AS PLAN_CP
	, TOTAL_NETWORK_SPEED AS TY
	, NULL AS LY
	, NULL AS DAY_DATE
FROM TOTAL_NETWORK_SPEED x
JOIN CAL_LKUP y ON x.WEEK_NUM = y.week_num
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK);


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Final table insertion

DELETE FROM {environment_schema}.WEEKLY_OPS_STANDUP
WHERE OPS_NAME = 'SUPPLYCHAIN' -- Adding an extra filter since all Ops Scorecard will be using the same table
AND UPDATED_WEEK = (SELECT WEEK_IDNT FROM CURR_WK);

INSERT INTO {environment_schema}.WEEKLY_OPS_STANDUP
SELECT 
	OPS_NAME,
	BANNER,
	CHANNEL,
	METRIC_NAME,
	FISCAL_NUM,
	FISCAL_DESC,
	LABEL,
	ROLLING_FISCAL_IND,
	PLAN_OP,
	PLAN_CP,
	TY,
	LY,
	WEEK_IDNT AS UPDATED_WEEK, 
	CURRENT_TIMESTAMP as update_timestamp,
	DAY_DATE
FROM WEEKLY_OPS_STANDUP AS A, CURR_WK;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
