/*
Inventory Ops Scorecard Main
Author: Soutrik Saha
Date Created: 1/6/23
Date Last Updated: 30/11/23

Datalab:
Deletes and Inserts into Table: T2DL_DAS_OSU.WEEKLY_OPS_STANDUP
*/

-- code begins here --

CREATE MULTISET VOLATILE TABLE WEEKLY_OPS_STANDUP, --copy of the permanent table
FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1 
(
      OPS_NAME VARCHAR(50),
      BANNER VARCHAR(50),
      CHANNEL VARCHAR(50),
      METRIC_NAME VARCHAR(50),
      FISCAL_NUM INTEGER,
      FISCAL_DESC VARCHAR(50),
      LABEL VARCHAR(50),			-- Chart Plot Axis (x-axis)
      ROLLING_FISCAL_IND INTEGER, 	-- identifier for Rolling & Forward weeks 
      PLAN_OP FLOAT,
      PLAN_CP FLOAT,
      TY FLOAT,
      LY FLOAT,						-- most recent completed week	
	  DAY_DATE DATE					-- Adding new column to accomodate Holiday Season data
) PRIMARY INDEX (OPS_NAME,BANNER,METRIC_NAME,FISCAL_NUM,LABEL)  ON COMMIT PRESERVE rows ;



 
-- WK Identifier for automating weekly plots
CREATE MULTISET VOLATILE TABLE CURR_WK AS (  
	SELECT WEEK_IDNT
		, WEEK_START_DAY_DATE
		, WEEK_END_DAY_DATE
		, MONTH_IDNT
		, MONTH_START_DAY_DATE
		, MONTH_END_DAY_DATE
	FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM
	WHERE day_date = {start_date}-7 	-- (CURRENT_DATE) - 7
) WITH data PRIMARY INDEX (WEEK_IDNT) ON COMMIT PRESERVE rows ;


-- CAL_LKUP;
CREATE MULTISET VOLATILE TABLE CAL_LKUP AS (
SELECT DISTINCT
	a.WEEK_NUM
	, a.WEEK_454_NUM
	, a.MONTH_SHORT_DESC
	, b.WEEK_START_DAY_DATE
	, b.WEEK_END_DAY_DATE
	, a.MONTH_NUM
	, b.MONTH_START_DAY_DATE
	, b.MONTH_END_DAY_DATE
	, a.YEAR_NUM
FROM PRD_NAP_USR_VWS.DAY_CAL a
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b
	on a.WEEK_NUM = b.WEEK_IDNT
		and a.MONTH_NUM = b.MONTH_IDNT
WHERE b.day_date BETWEEN ({start_date}-220) AND ({start_date}+120) -- (CURRENT_DATE)-220 AND (CURRENT_DATE)+120
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;


-- MERCH_HIERARCHY_LKUP;
CREATE MULTISET VOLATILE TABLE MERCH_HIERARCHY_LKUP  AS (
	SELECT DISTINCT DEPT_NUM, DEPT_NAME, DIVISION_NUM, DIVISION_NAME
	FROM PRD_NAP_VWS.DEPARTMENT_DIM
	WHERE DEPT_NUM NOT IN (584,585) AND DIVISION_NUM NOT IN (600) -- Excluding samples and ALt Model
) WITH data PRIMARY INDEX (DEPT_NUM) ON COMMIT PRESERVE rows ;


-- BANNER_CHNL_LKUP;
CREATE MULTISET VOLATILE TABLE BANNER_CHNL_LKUP AS (
	SELECT DISTINCT	CHANNEL_NUM
		, a.COUNTRY_CODE
		, a.BANNER_COUNTRY_NUM
		, CASE WHEN b.BANNER_DESC = 'OFF_PRICE' THEN 'NORDSTROM RACK'
			WHEN b.BANNER_DESC = 'FULL_PRICE' THEN 'NORDSTROM' END AS BANNER
	FROM PRD_NAP_VWS.ORG_CHANNEL_DIM a
	LEFT JOIN PRD_NAP_VWS.ORG_BANNER_COUNTRY_DIM b
		ON b.BANNER_COUNTRY_NUM = a.BANNER_COUNTRY_NUM
	WHERE a.COUNTRY_CODE = 'US'
) WITH data PRIMARY INDEX (CHANNEL_NUM) ON COMMIT PRESERVE rows ;

-------------------------------------------------------------------------------------------------------------------------------------------------------

-- Fileds from table : MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT
CREATE MULTISET VOLATILE TABLE INV_OPS_1
AS (
SELECT
	FACT.WEEK_NUM
	, TME.WEEK_454_NUM
	, TME.MONTH_SHORT_DESC
	, TME.WEEK_START_DAY_DATE
	, TME.WEEK_END_DAY_DATE
	, TME.MONTH_NUM
	, TME.MONTH_START_DAY_DATE
	, TME.MONTH_END_DAY_DATE
	, CASE WHEN BANNER_COUNTRY_NUM = 1 THEN 'NORDSTROM'
		   WHEN BANNER_COUNTRY_NUM = 3 THEN 'NORDSTROM RACK' END AS BANNER
	, FACT.DEPT_NUM
	, MCH.DIVISION_NAME
	--EOP $
	, SUM(OP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + OP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as OP_EOP_TOT_COST_AMT
	, SUM(CP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + CP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as CP_EOP_TOT_COST_AMT
	, SUM(TY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + TY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as TY_EOP_TOT_COST_AMT
	, SUM(LY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + LY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as LY_EOP_TOT_COST_AMT
	--Stock to Sales $
	, SUM(OP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + OP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as OP_BOP_TOT_COST_AMT
	, SUM(CP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + CP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as CP_BOP_TOT_COST_AMT
	, SUM(TY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + TY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as TY_BOP_TOT_COST_AMT
	, SUM(LY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + LY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as LY_BOP_TOT_COST_AMT
	--Projected Spend $
	, SUM(OP_RECEIPTS_ACTIVE_COST_AMT + OP_RECEIPTS_INACTIVE_COST_AMT) as OP_RCPTS_TOT_COST_AMT
	, SUM(CP_RECEIPTS_ACTIVE_COST_AMT + CP_RECEIPTS_INACTIVE_COST_AMT) as CP_RCPTS_TOT_COST_AMT
	, SUM(TY_RECEIPTS_ACTIVE_COST_AMT + TY_RECEIPTS_INACTIVE_COST_AMT) as TY_RCPTS_TOT_COST_AMT
	, SUM(LY_RECEIPTS_ACTIVE_COST_AMT + LY_RECEIPTS_INACTIVE_COST_AMT) as LY_RCPTS_TOT_COST_AMT
	--EOP U
	, SUM(OP_ENDING_OF_PERIOD_ACTIVE_QTY + OP_ENDING_OF_PERIOD_INACTIVE_QTY) as OP_EOP_TOT_UNITS
	, SUM(CP_ENDING_OF_PERIOD_ACTIVE_QTY + CP_ENDING_OF_PERIOD_INACTIVE_QTY) as CP_EOP_TOT_UNITS
	, SUM(TY_ENDING_OF_PERIOD_ACTIVE_QTY + TY_ENDING_OF_PERIOD_INACTIVE_QTY) as TY_EOP_TOT_UNITS
	--Sellable % of EOP U
	, SUM(LY_ENDING_OF_PERIOD_ACTIVE_QTY + LY_ENDING_OF_PERIOD_INACTIVE_QTY) as LY_EOP_TOT_UNITS
	--Receipt U and Total U ST %
	, SUM(OP_BEGINNING_OF_PERIOD_ACTIVE_QTY + OP_BEGINNING_OF_PERIOD_INACTIVE_QTY) as OP_BOP_TOT_UNITS
	, SUM(CP_BEGINNING_OF_PERIOD_ACTIVE_QTY + CP_BEGINNING_OF_PERIOD_INACTIVE_QTY) as CP_BOP_TOT_UNITS
	, SUM(TY_BEGINNING_OF_PERIOD_ACTIVE_QTY + TY_BEGINNING_OF_PERIOD_INACTIVE_QTY) as TY_BOP_TOT_UNITS
	, SUM(LY_BEGINNING_OF_PERIOD_ACTIVE_QTY + LY_BEGINNING_OF_PERIOD_INACTIVE_QTY) as LY_BOP_TOT_UNITS
	, SUM(OP_RECEIPTS_ACTIVE_QTY + OP_RECEIPTS_INACTIVE_QTY) as OP_RCPTS_TOT_UNITS
	, SUM(CP_RECEIPTS_ACTIVE_QTY + CP_RECEIPTS_INACTIVE_QTY) as CP_RCPTS_TOT_UNITS
	, SUM(TY_RECEIPTS_ACTIVE_QTY + TY_RECEIPTS_INACTIVE_QTY) as TY_RCPTS_TOT_UNITS
	, SUM(LY_RECEIPTS_ACTIVE_QTY + LY_RECEIPTS_INACTIVE_QTY) as LY_RCPTS_TOT_UNITS
	, SUM(OP_TRANSFER_IN_RACKING_COST_AMT + OP_TRANSFER_IN_OTHER_COST_AMT + OP_TRANSFER_IN_ACTIVE_COST_AMT + OP_RECLASS_IN_COST_AMT + OP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) as OP_INV_MVMT_IN_TOT_COST_AMT
	, SUM(CP_TRANSFER_IN_RACKING_COST_AMT + CP_TRANSFER_IN_OTHER_COST_AMT + CP_TRANSFER_IN_ACTIVE_COST_AMT + CP_RECLASS_IN_COST_AMT + CP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT) as CP_INV_MVMT_IN_TOT_COST_AMT
	, SUM(TY_TRANSFER_IN_RACKING_COST_AMT + TY_TRANSFER_IN_OTHER_COST_AMT + TY_TRANSFER_IN_ACTIVE_COST_AMT + TY_RECLASS_IN_COST_AMT) as TY_INV_MVMT_IN_TOT_COST_AMT
	, SUM(LY_TRANSFER_IN_RACKING_COST_AMT + LY_TRANSFER_IN_OTHER_COST_AMT + LY_TRANSFER_IN_ACTIVE_COST_AMT + LY_RECLASS_IN_COST_AMT) as LY_INV_MVMT_IN_TOT_COST_AMT
	--Total U ST %
	, SUM(OP_TRANSFER_IN_ACTIVE_QTY + OP_TRANSFER_IN_OTHER_QTY + OP_TRANSFER_IN_RACKING_QTY + OP_RECLASS_IN_QTY + OP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) as OP_INV_MVMNT_IN_UNITS
	, SUM(CP_TRANSFER_IN_ACTIVE_QTY + CP_TRANSFER_IN_OTHER_QTY + CP_TRANSFER_IN_RACKING_QTY + CP_RECLASS_IN_QTY + CP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY) as CP_INV_MVMNT_IN_UNITS
	, SUM(TY_TRANSFER_IN_ACTIVE_QTY + TY_TRANSFER_IN_OTHER_QTY + TY_TRANSFER_IN_RACKING_QTY + TY_RECLASS_IN_QTY) as TY_INV_MVMNT_IN_UNITS
	, SUM(LY_TRANSFER_IN_ACTIVE_QTY + LY_TRANSFER_IN_OTHER_QTY + LY_TRANSFER_IN_RACKING_QTY + LY_RECLASS_IN_QTY) as LY_INV_MVMNT_IN_UNITS
FROM PRD_NAP_USR_VWS.MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT FACT
JOIN MERCH_HIERARCHY_LKUP MCH
	ON FACT.DEPT_NUM = MCH.DEPT_NUM
JOIN CAL_LKUP TME
	ON FACT.WEEK_NUM = TME.WEEK_NUM
WHERE FACT.WEEK_NUM IN (SELECT WEEK_NUM FROM CAL_LKUP)
AND BANNER_COUNTRY_NUM IN(1,3)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
) WITH DATA PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER) ON COMMIT PRESERVE rows ;


-- Fileds from table: MFP_COST_PLAN_ACTUAL_CHANNEL_FACT (Net Sales)
CREATE MULTISET VOLATILE TABLE INV_OPS_2
AS (
SELECT
	FACT.WEEK_NUM
	, TME.WEEK_454_NUM
	, TME.MONTH_SHORT_DESC
	, TME.WEEK_START_DAY_DATE
	, TME.WEEK_END_DAY_DATE
	, TME.MONTH_NUM
	, TME.MONTH_START_DAY_DATE
	, TME.MONTH_END_DAY_DATE
	, BC.BANNER
	, FACT.DEPT_NUM
	, MCH.DIVISION_NAME
	, SUM(OP_NET_SALES_COST_AMT) as OP_NET_SALES_COST_AMT
	, SUM(CP_NET_SALES_COST_AMT) as CP_NET_SALES_COST_AMT
	, SUM(TY_NET_SALES_COST_AMT) as TY_NET_SALES_COST_AMT
	, SUM(LY_NET_SALES_COST_AMT) as LY_NET_SALES_COST_AMT
	, SUM(OP_NET_SALES_RETAIL_AMT) as OP_NET_SALES_RETAIL_AMT
	, SUM(CP_NET_SALES_RETAIL_AMT) as CP_NET_SALES_RETAIL_AMT
	, SUM(TY_NET_SALES_RETAIL_AMT) as TY_NET_SALES_RETAIL_AMT
	, SUM(LY_NET_SALES_RETAIL_AMT) as LY_NET_SALES_RETAIL_AMT
	, SUM(OP_GROSS_MARGIN_RETAIL_AMT) as OP_GROSS_MARGIN_RETAIL_AMT
	, SUM(CP_GROSS_MARGIN_RETAIL_AMT) as CP_GROSS_MARGIN_RETAIL_AMT
	, SUM(TY_GROSS_MARGIN_RETAIL_AMT) as TY_GROSS_MARGIN_RETAIL_AMT
	, SUM(LY_GROSS_MARGIN_RETAIL_AMT) as LY_GROSS_MARGIN_RETAIL_AMT
	, SUM(OP_NET_SALES_QTY) as OP_NET_SALES_QTY
	, SUM(CP_NET_SALES_QTY) as CP_NET_SALES_QTY
	, SUM(TY_NET_SALES_QTY) as TY_NET_SALES_QTY
	, SUM(LY_NET_SALES_QTY) as LY_NET_SALES_QTY
	, SUM(CASE WHEN FULFILL_TYPE_NUM = 1 then OP_NET_SALES_QTY else 0 end) as OP_DS_NET_SALES_UNITS
	, SUM(CASE WHEN FULFILL_TYPE_NUM = 1 then CP_NET_SALES_QTY else 0 end) as CP_DS_NET_SALES_UNITS
	, SUM(CASE WHEN FULFILL_TYPE_NUM = 1 then TY_NET_SALES_QTY else 0 end) as TY_DS_NET_SALES_UNITS
	, SUM(CASE WHEN FULFILL_TYPE_NUM = 1 then LY_NET_SALES_QTY else 0 end) as LY_DS_NET_SALES_UNITS
FROM PRD_NAP_USR_VWS.MFP_COST_PLAN_ACTUAL_CHANNEL_FACT FACT
JOIN MERCH_HIERARCHY_LKUP MCH
	ON FACT.DEPT_NUM = MCH.DEPT_NUM
JOIN BANNER_CHNL_LKUP BC
	ON FACT.CHANNEL_NUM  = BC.CHANNEL_NUM
JOIN CAL_LKUP TME
	ON FACT.WEEK_NUM = TME.WEEK_NUM
WHERE FACT.WEEK_NUM IN (SELECT WEEK_NUM FROM CAL_LKUP)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
) WITH DATA PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER) ON COMMIT PRESERVE rows ;


-- Fields from table MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT_VW (EOH)
CREATE MULTISET VOLATILE TABLE INV_OPS_3
AS (
SELECT
	INV.WEEK_NUM
	, TME.WEEK_454_NUM
	, TME.MONTH_SHORT_DESC
	, TME.WEEK_START_DAY_DATE
	, TME.WEEK_END_DAY_DATE
	, TME.MONTH_NUM
	, TME.MONTH_START_DAY_DATE
	, TME.MONTH_END_DAY_DATE
	, BC.BANNER
	, INV.DEPT_NUM
	, MCH.DIVISION_NAME
	, SUM(INVENTORY_EOH_TOTAL_UNITS_LY) AS INV_EOH_TOT_UNITS_LY
	, SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INV_EOH_TOT_UNITS_TY
	, sum(inventory_eoh_in_transit_total_units_ty) as inventory_eoh_in_transit_U_TY --For calculation of Sellable % of EOP U
	, sum(inventory_eoh_in_transit_total_units_ly) as inventory_eoh_in_transit_U_LY --For calculation of Sellable % of EOP U
FROM PRD_NAP_VWS.MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT_VW INV
JOIN MERCH_HIERARCHY_LKUP MCH
ON INV.DEPT_NUM = MCH.DEPT_NUM
JOIN BANNER_CHNL_LKUP BC
ON INV.CHANNEL_NUM = BC.CHANNEL_NUM
JOIN CAL_LKUP TME
ON INV.WEEK_NUM = TME.WEEK_NUM
WHERE INV.WEEK_NUM IN (SELECT WEEK_NUM FROM CAL_LKUP)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11
) WITH DATA PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER) ON COMMIT PRESERVE rows ;


-- COMBINING ALL FIELDS
CREATE MULTISET VOLATILE TABLE INV_OPS_4 AS (
SELECT
	COALESCE(A.WEEK_NUM,B.WEEK_NUM,C.WEEK_NUM) AS WEEK_NUM
	, COALESCE(A.WEEK_454_NUM,B.WEEK_454_NUM,C.WEEK_454_NUM) AS WEEK_454_NUM
	, COALESCE(A.MONTH_SHORT_DESC,B.MONTH_SHORT_DESC,C.MONTH_SHORT_DESC) AS MONTH_SHORT_DESC
	, COALESCE(A.WEEK_START_DAY_DATE, B.WEEK_START_DAY_DATE, C.WEEK_START_DAY_DATE) AS WEEK_START_DAY_DATE
	, COALESCE(A.WEEK_END_DAY_DATE, B.WEEK_END_DAY_DATE, C.WEEK_END_DAY_DATE) AS WEEK_END_DAY_DATE
	, COALESCE(A.MONTH_NUM, B.MONTH_NUM, C.MONTH_NUM) AS MONTH_NUM
	, COALESCE(A.MONTH_START_DAY_DATE, B.MONTH_START_DAY_DATE, C.MONTH_START_DAY_DATE) AS MONTH_START_DAY_DATE
	, COALESCE(A.MONTH_END_DAY_DATE, B.MONTH_END_DAY_DATE, C.MONTH_END_DAY_DATE) AS MONTH_END_DAY_DATE
	, COALESCE(A.BANNER, B.BANNER, C.BANNER) AS BANNER
	, COALESCE(A.DEPT_NUM, B.DEPT_NUM, C.DEPT_NUM) AS DEPT_NUM
	, COALESCE(A.DIVISION_NAME, B.DIVISION_NAME, C.DIVISION_NAME) AS DIVISION_NAME
	, CAST(COALESCE(OP_EOP_TOT_COST_AMT,0) AS FLOAT) AS OP_EOP_TOT_COST_AMT
	, CAST(COALESCE(CP_EOP_TOT_COST_AMT,0) AS FLOAT) AS CP_EOP_TOT_COST_AMT
	, CAST(COALESCE(TY_EOP_TOT_COST_AMT,0) AS FLOAT) AS TY_EOP_TOT_COST_AMT
	, CAST(COALESCE(LY_EOP_TOT_COST_AMT,0) AS FLOAT) AS LY_EOP_TOT_COST_AMT
	, CAST(COALESCE(OP_BOP_TOT_COST_AMT,0) AS FLOAT) AS OP_BOP_TOT_COST_AMT
	, CAST(COALESCE(CP_BOP_TOT_COST_AMT,0) AS FLOAT) AS CP_BOP_TOT_COST_AMT
	, CAST(COALESCE(TY_BOP_TOT_COST_AMT,0) AS FLOAT) AS TY_BOP_TOT_COST_AMT
	, CAST(COALESCE(LY_BOP_TOT_COST_AMT,0) AS FLOAT) AS LY_BOP_TOT_COST_AMT
	, CAST(COALESCE(OP_RCPTS_TOT_COST_AMT,0) AS FLOAT) AS OP_RCPTS_TOT_COST_AMT
	, CAST(COALESCE(CP_RCPTS_TOT_COST_AMT,0) AS FLOAT) AS CP_RCPTS_TOT_COST_AMT
	, CAST(COALESCE(TY_RCPTS_TOT_COST_AMT,0) AS FLOAT) AS TY_RCPTS_TOT_COST_AMT
	, CAST(COALESCE(LY_RCPTS_TOT_COST_AMT,0) AS FLOAT) AS LY_RCPTS_TOT_COST_AMT
	, CAST(COALESCE(OP_EOP_TOT_UNITS,0) AS FLOAT) AS OP_EOP_TOT_UNITS
	, CAST(COALESCE(CP_EOP_TOT_UNITS,0) AS FLOAT) AS CP_EOP_TOT_UNITS
	, CAST(COALESCE(TY_EOP_TOT_UNITS,0) AS FLOAT) AS TY_EOP_TOT_UNITS
	, CAST(COALESCE(LY_EOP_TOT_UNITS,0) AS FLOAT) AS LY_EOP_TOT_UNITS
	, CAST(COALESCE(OP_BOP_TOT_UNITS,0) AS FLOAT) AS OP_BOP_TOT_UNITS
	, CAST(COALESCE(CP_BOP_TOT_UNITS,0) AS FLOAT) AS CP_BOP_TOT_UNITS
	, CAST(COALESCE(TY_BOP_TOT_UNITS,0) AS FLOAT) AS TY_BOP_TOT_UNITS
	, CAST(COALESCE(LY_BOP_TOT_UNITS,0) AS FLOAT) AS LY_BOP_TOT_UNITS
	, CAST(COALESCE(OP_RCPTS_TOT_UNITS,0) AS FLOAT) AS OP_RCPTS_TOT_UNITS
	, CAST(COALESCE(CP_RCPTS_TOT_UNITS,0) AS FLOAT) AS CP_RCPTS_TOT_UNITS
	, CAST(COALESCE(TY_RCPTS_TOT_UNITS,0) AS FLOAT) AS TY_RCPTS_TOT_UNITS
	, CAST(COALESCE(LY_RCPTS_TOT_UNITS,0) AS FLOAT) AS LY_RCPTS_TOT_UNITS
	, CAST(COALESCE(OP_INV_MVMT_IN_TOT_COST_AMT,0) AS FLOAT) AS OP_INV_MVMT_IN_TOT_COST_AMT
	, CAST(COALESCE(CP_INV_MVMT_IN_TOT_COST_AMT,0) AS FLOAT) AS CP_INV_MVMT_IN_TOT_COST_AMT
	, CAST(COALESCE(TY_INV_MVMT_IN_TOT_COST_AMT,0) AS FLOAT) AS TY_INV_MVMT_IN_TOT_COST_AMT
	, CAST(COALESCE(LY_INV_MVMT_IN_TOT_COST_AMT,0) AS FLOAT) AS LY_INV_MVMT_IN_TOT_COST_AMT
	, CAST(COALESCE(OP_INV_MVMNT_IN_UNITS,0) AS FLOAT) AS OP_INV_MVMNT_IN_UNITS
	, CAST(COALESCE(CP_INV_MVMNT_IN_UNITS,0) AS FLOAT) AS CP_INV_MVMNT_IN_UNITS
	, CAST(COALESCE(TY_INV_MVMNT_IN_UNITS,0) AS FLOAT) AS TY_INV_MVMNT_IN_UNITS
	, CAST(COALESCE(LY_INV_MVMNT_IN_UNITS,0) AS FLOAT) AS LY_INV_MVMNT_IN_UNITS
	, CAST(COALESCE(OP_NET_SALES_COST_AMT,0) AS FLOAT) AS OP_NET_SALES_COST_AMT
	, CAST(COALESCE(CP_NET_SALES_COST_AMT,0) AS FLOAT) AS CP_NET_SALES_COST_AMT
	, CAST(COALESCE(TY_NET_SALES_COST_AMT,0) AS FLOAT) AS TY_NET_SALES_COST_AMT
	, CAST(COALESCE(LY_NET_SALES_COST_AMT,0) AS FLOAT) AS LY_NET_SALES_COST_AMT
	, CAST(COALESCE(OP_NET_SALES_RETAIL_AMT,0) AS FLOAT) AS OP_NET_SALES_RETAIL_AMT
	, CAST(COALESCE(CP_NET_SALES_RETAIL_AMT,0) AS FLOAT) AS CP_NET_SALES_RETAIL_AMT
	, CAST(COALESCE(TY_NET_SALES_RETAIL_AMT,0) AS FLOAT) AS TY_NET_SALES_RETAIL_AMT
	, CAST(COALESCE(LY_NET_SALES_RETAIL_AMT,0) AS FLOAT) AS LY_NET_SALES_RETAIL_AMT
	, CAST(COALESCE(OP_NET_SALES_QTY,0) AS FLOAT) AS OP_NET_SALES_QTY
	, CAST(COALESCE(CP_NET_SALES_QTY,0) AS FLOAT) AS CP_NET_SALES_QTY
	, CAST(COALESCE(TY_NET_SALES_QTY,0) AS FLOAT) AS TY_NET_SALES_QTY
	, CAST(COALESCE(LY_NET_SALES_QTY,0) AS FLOAT) AS LY_NET_SALES_QTY
	, CAST(COALESCE(OP_DS_NET_SALES_UNITS,0) AS FLOAT) AS OP_DS_NET_SALES_UNITS
	, CAST(COALESCE(CP_DS_NET_SALES_UNITS,0) AS FLOAT) AS CP_DS_NET_SALES_UNITS
	, CAST(COALESCE(TY_DS_NET_SALES_UNITS,0) AS FLOAT) AS TY_DS_NET_SALES_UNITS
	, CAST(COALESCE(LY_DS_NET_SALES_UNITS,0) AS FLOAT) AS LY_DS_NET_SALES_UNITS
	, CAST(COALESCE(INV_EOH_TOT_UNITS_TY,0) AS FLOAT) AS INV_EOH_TOT_UNITS_TY
	, CAST(COALESCE(INV_EOH_TOT_UNITS_LY,0) AS FLOAT) AS INV_EOH_TOT_UNITS_LY
	, CAST(COALESCE(inventory_eoh_in_transit_U_TY,0) as float) as inventory_eoh_in_transit_U_TY --For calculation of Sellable % of EOP U
	, CAST(COALESCE(inventory_eoh_in_transit_U_LY,0) as float) as inventory_eoh_in_transit_U_LY --For calculation of Sellable % of EOP U
	, CAST(COALESCE(OP_GROSS_MARGIN_RETAIL_AMT,0) AS FLOAT) AS OP_GROSS_MARGIN_RETAIL_AMT
	, CAST(COALESCE(CP_GROSS_MARGIN_RETAIL_AMT,0) AS FLOAT) AS CP_GROSS_MARGIN_RETAIL_AMT
	, CAST(COALESCE(TY_GROSS_MARGIN_RETAIL_AMT,0) AS FLOAT) AS TY_GROSS_MARGIN_RETAIL_AMT
	, CAST(COALESCE(LY_GROSS_MARGIN_RETAIL_AMT,0) AS FLOAT) AS LY_GROSS_MARGIN_RETAIL_AMT
FROM INV_OPS_1 A
FULL JOIN INV_OPS_2 B
ON a.WEEK_NUM = b.WEEK_NUM
AND a.DEPT_NUM = b.DEPT_NUM
AND a.BANNER = b.BANNER
FULL JOIN INV_OPS_3 c
ON a.WEEK_NUM = c.WEEK_NUM
AND a.DEPT_NUM = c.DEPT_NUM
AND a.BANNER = c.BANNER
) WITH DATA PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER) ON COMMIT PRESERVE rows ;

----------------------------------------------------------------------------------------------------------------------------------------------------

---- Dashboard table insertion, metric wise ----


-- NORDSTROM INVENTORY | HOW MUCH --

-- EOP $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'EOP $' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS LABEL,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_COST_AMT) AS PLAN_OP,
SUM(CP_EOP_TOT_COST_AMT) AS PLAN_CP,
SUM(TY_EOP_TOT_COST_AMT) AS TY,
SUM(LY_EOP_TOT_COST_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


--Stock to Sales $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' as OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Stock to Sales $' as METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' as FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS LABEL,
ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
WEEK_NUM,
MONTH_SHORT_DESC,
WEEK_454_NUM,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5) a ;


-- Projected Spend $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Projected Spend $' AS METRIC_NAME,
A.MONTH_NUM AS FISCAL_NUM,
'MONTH' AS FISCAL_DESC,
MONTH_SHORT_DESC AS LABEL,
ROLLING_FISCAL_IND,
CASE WHEN Cp_Rcpts_Less_Reserve_C > 0 then Cp_Rcpts_Less_Reserve_C else OP_RCPTS_TOT_COST_AMT end AS PLAN_OP,
NULL AS PLAN_CP,
CASE WHEN TY_RCPTS_TOT_COST_AMT > 0 THEN TY_RCPTS_TOT_COST_AMT
	 WHEN TY_RCPTS_TOT_COST_AMT = 0 AND (TY_RP_ANTICIPATED_SPEND_C >= TY_RP_RCPT_MTD_OO_C) THEN (TY_NRP_RCPT_MTD_OO_CM_C + TY_RP_ANTICIPATED_SPEND_C)
	 WHEN TY_RCPTS_TOT_COST_AMT = 0 AND (TY_RP_ANTICIPATED_SPEND_C < TY_RP_RCPT_MTD_OO_C) THEN (TY_NRP_RCPT_MTD_OO_CM_C + TY_RP_RCPT_MTD_OO_C) END AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM
(SELECT
A.MONTH_NUM,
A.BANNER,
MONTH_SHORT_DESC,
ROLLING_FISCAL_IND,
OP_RCPTS_TOT_COST_AMT,
TY_RCPTS_TOT_COST_AMT
FROM
(SELECT
MONTH_NUM,
BANNER,
CASE WHEN INV_OPS_4.MONTH_NUM < CURR_WK.MONTH_IDNT THEN 1
WHEN curr_wk.week_end_day_date = curr_wk.month_end_day_date and INV_OPS_4.MONTH_NUM = CURR_WK.MONTH_IDNT then 1 ELSE 0 END AS ROLLING_FISCAL_IND, --updated to include completed month
SUM(OP_RCPTS_TOT_COST_AMT) AS OP_RCPTS_TOT_COST_AMT,
--SUM(CP_RCPTS_TOT_COST_AMT) AS CP_RCPTS_TOT_COST_AMT,
SUM(CASE WHEN INV_OPS_4.MONTH_NUM = CURR_WK.MONTH_IDNT AND CURR_WK.WEEK_END_DAY_DATE < CURR_WK.MONTH_END_DAY_DATE THEN 0 ELSE TY_RCPTS_TOT_COST_AMT END) AS TY_RCPTS_TOT_COST_AMT
--SUM(LY_RCPTS_TOT_COST_AMT) AS LY_RCPTS_TOT_COST_AMT
FROM INV_OPS_4, CURR_WK
GROUP BY 1,2,3) A
JOIN
(select MONTH_NUM, MONTH_SHORT_DESC
from
(SELECT DISTINCT MONTH_NUM, MONTH_SHORT_DESC, cal_lkup.MONTH_START_DAY_DATE, curr_wk.week_end_day_date as curr_week_end_day_date, curr_wk.month_end_day_date as curr_month_end_day_date
FROM CAL_LKUP, curr_wk) a
WHERE ((MONTH_START_DAY_DATE BETWEEN (select (MONTH_START_DAY_DATE -75) from CURR_WK) AND (select (MONTH_START_DAY_DATE +100) from CURR_WK))
and (curr_week_end_day_date = curr_month_end_day_date)) --Added logic to check if the previous month has ended and accordingly fetch data from source
or
((MONTH_START_DAY_DATE BETWEEN (select (MONTH_START_DAY_DATE -100) from CURR_WK) AND (select (MONTH_START_DAY_DATE +75) from CURR_WK))
and (curr_week_end_day_date <> curr_month_end_day_date)) --Added logic to check if the previous month has ended and accordingly fetch data from source
) B
ON A.MONTH_NUM = B.MONTH_NUM) A
LEFT JOIN
(SELECT
MONTH_IDNT,
CASE WHEN BANNER = 'US Rack' THEN 'NORDSTROM RACK'
			WHEN BANNER = 'US Nordstrom' THEN 'NORDSTROM' END AS BANNER,
SUM("Ty NRP Rcpts MTD OO CM C") AS TY_NRP_RCPT_MTD_OO_CM_C,
SUM("Ty RP Anticipated Spend C") AS TY_RP_ANTICIPATED_SPEND_C,
SUM("Ty RP Rcpts MTD OO C") AS TY_RP_RCPT_MTD_OO_C,
SUM("Cp Rcpts Less Reserve C") AS Cp_Rcpts_Less_Reserve_C
from T2DL_DAS_OPEN_TO_BUY.OTB_COST_CURRENT
WHERE COUNTRY = 'US' AND LEFT(Division,3) NOT IN ('990','600') AND LEFT(DEPARTMENT,3) NOT IN ('584','585') --also excluding DIVISION number 990
GROUP BY 1,2) B
ON A.MONTH_NUM = B.MONTH_IDNT
AND A.BANNER = B.BANNER ;


--Division Stock to Sales MTD $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Division Stock to Sales MTD $' as METRIC_NAME,
MONTH_NUM AS FISCAL_NUM,
'MTD' AS FISCAL_DESC,
DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
case when DIVISION_NAME in('ACCESSORIES','HOME') then 'ACC/HOME' else division_name end AS DIVISION_NAME,
MONTH_NUM,
-- Pulling first week BOP value for each month. Monthly/MTD BOP = First week BOP
SUM(case when week_454_num = 1 then TY_BOP_TOT_COST_AMT else 0 end) AS TY_BOP_TOT_COST_AMT,
SUM(case when week_454_num = 1 then OP_BOP_TOT_COST_AMT else 0 end) AS OP_BOP_TOT_COST_AMT,
SUM(case when week_454_num = 1 then CP_BOP_TOT_COST_AMT else 0 end) AS CP_BOP_TOT_COST_AMT,
SUM(case when week_454_num = 1 then LY_BOP_TOT_COST_AMT else 0 end) AS LY_BOP_TOT_COST_AMT,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_4 A
JOIN (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP WHERE MONTH_NUM = (SELECT MONTH_IDNT FROM CURR_WK) AND WEEK_NUM <= (SELECT WEEK_IDNT FROM CURR_WK)) B
ON A.WEEK_NUM = B.WEEK_NUM
GROUP BY 1,2,3) A  ;



-- EOP U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'EOP U' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS LABEL,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(TY_EOP_TOT_UNITS) AS TY,
SUM(LY_EOP_TOT_UNITS) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- Sellable % of EOP U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Sellable % of EOP U' as METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
ROLLING_FISCAL_IND,
NULL AS PLAN_OP,
NULL AS PLAN_CP,
CASE WHEN (INV_EOH_TOT_UNITS_TY + inventory_eoh_in_transit_U_TY) = 0 THEN 0 ELSE (CAST(INV_EOH_TOT_UNITS_TY AS FLOAT)/(CAST(INV_EOH_TOT_UNITS_TY AS FLOAT) + CAST(inventory_eoh_in_transit_U_TY AS FLOAT))) END AS TY,
CASE WHEN (INV_EOH_TOT_UNITS_LY + inventory_eoh_in_transit_U_LY) = 0 THEN 0 ELSE (CAST(INV_EOH_TOT_UNITS_LY AS FLOAT)/(CAST(INV_EOH_TOT_UNITS_LY AS FLOAT) + CAST(inventory_eoh_in_transit_U_LY AS FLOAT))) END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
WEEK_NUM,
MONTH_SHORT_DESC,
WEEK_454_NUM,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(inventory_eoh_in_transit_U_LY) AS inventory_eoh_in_transit_U_LY,
SUM(INV_EOH_TOT_UNITS_LY) AS INV_EOH_TOT_UNITS_LY,
SUM(inventory_eoh_in_transit_U_TY) AS inventory_eoh_in_transit_U_TY,
SUM(INV_EOH_TOT_UNITS_TY) AS INV_EOH_TOT_UNITS_TY,
sum(TY_INV_MVMNT_IN_UNITS) AS TY_INV_MVMNT_IN_UNITS,
sum(LY_INV_MVMNT_IN_UNITS) AS LY_INV_MVMNT_IN_UNITS
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3,4,5) A ;


-- RECEIPT U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'RECEIPT U' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS LABEL,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_RCPTS_TOT_UNITS) AS PLAN_OP,
SUM(CP_RCPTS_TOT_UNITS) AS PLAN_CP,
SUM(TY_RCPTS_TOT_UNITS) AS TY,
SUM(LY_RCPTS_TOT_UNITS) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,13 ;



--DS % Pen of Sales U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'DS % Pen of Sales U' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS LABEL,
ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_QTY = 0 THEN 0 ELSE OP_DS_NET_SALES_UNITS/OP_NET_SALES_QTY END AS PLAN_OP,
CASE WHEN CP_NET_SALES_QTY = 0 THEN 0 ELSE CP_DS_NET_SALES_UNITS/CP_NET_SALES_QTY END AS PLAN_CP,
CASE WHEN TY_NET_SALES_QTY = 0 THEN 0 ELSE TY_DS_NET_SALES_UNITS/TY_NET_SALES_QTY END AS TY,
CASE WHEN LY_NET_SALES_QTY = 0 THEN 0 ELSE LY_DS_NET_SALES_UNITS/LY_NET_SALES_QTY END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
WEEK_NUM,
MONTH_SHORT_DESC,
WEEK_454_NUM,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_QTY) AS OP_NET_SALES_QTY,
SUM(CP_NET_SALES_QTY) AS CP_NET_SALES_QTY,
SUM(TY_NET_SALES_QTY) AS TY_NET_SALES_QTY,
SUM(LY_NET_SALES_QTY) AS LY_NET_SALES_QTY,
SUM(OP_DS_NET_SALES_UNITS) AS OP_DS_NET_SALES_UNITS,
SUM(CP_DS_NET_SALES_UNITS) AS CP_DS_NET_SALES_UNITS,
SUM(TY_DS_NET_SALES_UNITS) AS TY_DS_NET_SALES_UNITS,
SUM(LY_DS_NET_SALES_UNITS) AS LY_DS_NET_SALES_UNITS
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5) A ;



-- BANNER INVENTORY | WHAT --

--Total U ST %
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Total U ST %' as METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS LABEL,
ROLLING_FISCAL_IND,
CASE WHEN (OP_BOP_TOT_UNITS + OP_RCPTS_TOT_UNITS + OP_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE OP_NET_SALES_QTY/(OP_BOP_TOT_UNITS + OP_RCPTS_TOT_UNITS + OP_INV_MVMNT_IN_UNITS) END AS PLAN_OP,
CASE WHEN (CP_BOP_TOT_UNITS + CP_RCPTS_TOT_UNITS + CP_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE CP_NET_SALES_QTY/(CP_BOP_TOT_UNITS + CP_RCPTS_TOT_UNITS + CP_INV_MVMNT_IN_UNITS) END AS PLAN_CP,
CASE WHEN (TY_BOP_TOT_UNITS + TY_RCPTS_TOT_UNITS + TY_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE TY_NET_SALES_QTY/(TY_BOP_TOT_UNITS + TY_RCPTS_TOT_UNITS + TY_INV_MVMNT_IN_UNITS) END AS TY,
CASE WHEN (LY_BOP_TOT_UNITS + LY_RCPTS_TOT_UNITS + LY_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE LY_NET_SALES_QTY/(LY_BOP_TOT_UNITS + LY_RCPTS_TOT_UNITS + LY_INV_MVMNT_IN_UNITS) END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
WEEK_NUM,
MONTH_SHORT_DESC,
WEEK_454_NUM,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_QTY) AS OP_NET_SALES_QTY,
SUM(CP_NET_SALES_QTY) AS CP_NET_SALES_QTY,
SUM(TY_NET_SALES_QTY) AS TY_NET_SALES_QTY,
SUM(LY_NET_SALES_QTY) AS LY_NET_SALES_QTY,
SUM(OP_BOP_TOT_UNITS) AS OP_BOP_TOT_UNITS,
SUM(CP_BOP_TOT_UNITS) AS CP_BOP_TOT_UNITS,
SUM(TY_BOP_TOT_UNITS) AS TY_BOP_TOT_UNITS,
SUM(LY_BOP_TOT_UNITS) AS LY_BOP_TOT_UNITS,
SUM(OP_RCPTS_TOT_UNITS) AS OP_RCPTS_TOT_UNITS,
SUM(CP_RCPTS_TOT_UNITS) AS CP_RCPTS_TOT_UNITS,
SUM(TY_RCPTS_TOT_UNITS) AS TY_RCPTS_TOT_UNITS,
SUM(LY_RCPTS_TOT_UNITS) AS LY_RCPTS_TOT_UNITS,
SUM(OP_INV_MVMNT_IN_UNITS) AS OP_INV_MVMNT_IN_UNITS,
SUM(CP_INV_MVMNT_IN_UNITS) AS CP_INV_MVMNT_IN_UNITS,
SUM(TY_INV_MVMNT_IN_UNITS) AS TY_INV_MVMNT_IN_UNITS,
SUM(LY_INV_MVMNT_IN_UNITS) AS LY_INV_MVMNT_IN_UNITS
FROM INV_OPS_4
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5) A ;


-- MTD Div U ST %
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' as OPS_NAME,
BANNER,
NULL AS CHANNEL,
'MTD Div U ST %' as METRIC_NAME,
MONTH_NUM AS FISCAL_NUM,
'MTD' AS FISCAL_DESC,
DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN (OP_BOP_TOT_UNITS + OP_RCPTS_TOT_UNITS + OP_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE OP_NET_SALES_QTY/(OP_BOP_TOT_UNITS + OP_RCPTS_TOT_UNITS + OP_INV_MVMNT_IN_UNITS) END AS PLAN_OP,
CASE WHEN (CP_BOP_TOT_UNITS + CP_RCPTS_TOT_UNITS + CP_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE CP_NET_SALES_QTY/(CP_BOP_TOT_UNITS + CP_RCPTS_TOT_UNITS + CP_INV_MVMNT_IN_UNITS) END AS PLAN_CP,
CASE WHEN (TY_BOP_TOT_UNITS + TY_RCPTS_TOT_UNITS + TY_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE TY_NET_SALES_QTY/(TY_BOP_TOT_UNITS + TY_RCPTS_TOT_UNITS + TY_INV_MVMNT_IN_UNITS) END AS TY,
CASE WHEN (LY_BOP_TOT_UNITS + LY_RCPTS_TOT_UNITS + LY_INV_MVMNT_IN_UNITS) = 0 THEN 0 ELSE LY_NET_SALES_QTY/(LY_BOP_TOT_UNITS + LY_RCPTS_TOT_UNITS + LY_INV_MVMNT_IN_UNITS) END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
case when DIVISION_NAME in('ACCESSORIES','HOME') then 'ACC/HOME' else division_name end AS DIVISION_NAME,
MONTH_NUM,
SUM(OP_NET_SALES_QTY) AS OP_NET_SALES_QTY,
SUM(CP_NET_SALES_QTY) AS CP_NET_SALES_QTY,
SUM(TY_NET_SALES_QTY) AS TY_NET_SALES_QTY,
SUM(LY_NET_SALES_QTY) AS LY_NET_SALES_QTY,
-- Pulling first week BOP value for each month. Monthly/MTD BOP = First week BOP
SUM(case when week_454_num = 1 then OP_BOP_TOT_UNITS else 0 end) AS OP_BOP_TOT_UNITS,
SUM(case when week_454_num = 1 then CP_BOP_TOT_UNITS else 0 end) AS CP_BOP_TOT_UNITS,
SUM(case when week_454_num = 1 then TY_BOP_TOT_UNITS else 0 end) AS TY_BOP_TOT_UNITS,
SUM(case when week_454_num = 1 then LY_BOP_TOT_UNITS else 0 end) AS LY_BOP_TOT_UNITS,
SUM(OP_RCPTS_TOT_UNITS) AS OP_RCPTS_TOT_UNITS,
SUM(CP_RCPTS_TOT_UNITS) AS CP_RCPTS_TOT_UNITS,
SUM(TY_RCPTS_TOT_UNITS) AS TY_RCPTS_TOT_UNITS,
SUM(LY_RCPTS_TOT_UNITS) AS LY_RCPTS_TOT_UNITS,
SUM(OP_INV_MVMNT_IN_UNITS) AS OP_INV_MVMNT_IN_UNITS,
SUM(CP_INV_MVMNT_IN_UNITS) AS CP_INV_MVMNT_IN_UNITS,
SUM(TY_INV_MVMNT_IN_UNITS) AS TY_INV_MVMNT_IN_UNITS,
SUM(LY_INV_MVMNT_IN_UNITS) AS LY_INV_MVMNT_IN_UNITS
FROM INV_OPS_4 A
JOIN (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP WHERE MONTH_NUM = (SELECT MONTH_IDNT FROM CURR_WK) AND WEEK_NUM <= (SELECT WEEK_IDNT FROM CURR_WK)) B
ON A.WEEK_NUM = B.WEEK_NUM
GROUP BY 1,2,3) A ;


-- Nordstrom Rack Strategic Brands % EOP $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
'NORDSTROM RACK' AS BANNER,
NULL AS CHANNEL,
'Strategic Brands % EOH $' AS METRIC_NAME,
A.WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
ROLLING_FISCAL_IND,
0.65 AS PLAN_OP, -- HARDCODING Planned value for 'Strategic Brands % EOH $' to 65% as confirmed by Theresa
NULL AS PLAN_CP,
CASE WHEN RACK_TTL_EOH_TY = 0 THEN 0 ELSE RACK_SB_EOH_TY/RACK_TTL_EOH_TY END AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM
(SELECT
WEEK_NUM,
SUM(inventory_eoh_total_cost_amt_ty) AS RACK_TTL_EOH_TY,
SUM(CASE WHEN RSB = 'Y' THEN inventory_eoh_total_cost_amt_ty ELSE 0 END) AS RACK_SB_EOH_TY
FROM PRD_NAP_VWS.MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT_VW a
left join t2dl_das_in_season_management_reporting.rsb_vendor_dim b on a.vndr_label_code = b.vndr_label_code
join merch_hierarchy_lkup c on a.dept_num = c.dept_num
WHERE a.banner_country_num = 3 AND store_country_code = 'US' and channel_num in (210,250) --Added filter for better accuracy in numbers
AND c.DEPT_NUM NOT IN (584,585)
AND c.DIVISION_NUM NOT IN (600)
GROUP BY 1) A
JOIN
(SELECT DISTINCT WEEK_NUM, WEEK_454_NUM, MONTH_SHORT_DESC, CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND
FROM CAL_LKUP
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)) B
ON A.WEEK_NUM = B.WEEK_NUM ;


-- Nordstrom Rack Strategic Brands % Sales $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' AS OPS_NAME,
'NORDSTROM RACK' AS BANNER,
NULL AS CHANNEL,
'Strategic Brands % Sales $' AS METRIC_NAME,
A.WEEK_NUM AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
ROLLING_FISCAL_IND,
0.65 AS PLAN_OP, -- HARDCODING Planned value for 'Strategic Brands % EOH $' to 65% as confirmed by Theresa
NULL AS PLAN_CP,
CASE WHEN RACK_TTL_EOH_TY = 0 THEN 0 ELSE RACK_SB_EOH_TY/RACK_TTL_EOH_TY END AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM
(SELECT
WEEK_NUM,
SUM(jwn_operational_gmv_total_retail_amt_ty) AS RACK_TTL_EOH_TY,
SUM(CASE WHEN RSB = 'Y' THEN jwn_operational_gmv_total_retail_amt_ty ELSE 0 END) AS RACK_SB_EOH_TY
FROM PRD_NAP_VWS.MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT_VW a
left join t2dl_das_in_season_management_reporting.rsb_vendor_dim b on a.vndr_label_code = b.vndr_label_code
join merch_hierarchy_lkup c on a.dept_num = c.dept_num
WHERE a.banner_country_num = 3 AND store_country_code = 'US' and channel_num in (210,250) --Added filter for better accuracy in numbers
AND c.DEPT_NUM NOT IN (584,585)
AND c.DIVISION_NUM NOT IN (600)
GROUP BY 1) A
JOIN
(SELECT DISTINCT WEEK_NUM, WEEK_454_NUM, MONTH_SHORT_DESC, CASE WHEN WEEK_START_DAY_DATE <= ({start_date}-7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND
FROM CAL_LKUP
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)) B
ON A.WEEK_NUM = B.WEEK_NUM ;


-- % Inv $ 17+Wks & Clear
INSERT INTO WEEKLY_OPS_STANDUP
SELECT									-- AOI logic has been updated 
'MERCH_INVENTORY' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'% Inv $ 17+Wks & Clear' AS METRIC_NAME,
A.MONTH_NUM AS FISCAL_NUM,
'MONTH' AS FISCAL_DESC,
MONTH_SHORT_DESC AS LABEL,
NULL AS ROLLING_FISCAL_IND,
NULL AS PLAN_OP,
NULL AS PLAN_CP,
case when TY_EOP_COST = 0 then 0 else TY_EOP_COST_17Wks/TY_EOP_COST end as TY,
case when LY_EOP_COST = 0 then 0 else LY_EOP_COST_17Wks/LY_EOP_COST end as LY,
NULL AS DAY_DATE
FROM
(SELECT 
MONTH_NUM,
CASE WHEN BANNER_NUM = 1 THEN 'NORDSTROM'
	 WHEN BANNER_NUM = 3 THEN 'NORDSTROM RACK' END AS BANNER,
SUM(CASE WHEN OWNERSHIP_PRICE_TYPE='R' AND  INVENTORY_AGE_DAYS >= 119 THEN END_OF_PERIOD_TOTAL_COST
		 WHEN OWNERSHIP_PRICE_TYPE='C' THEN END_OF_PERIOD_TOTAL_COST END) AS TY_EOP_COST_17Wks,
SUM(END_OF_PERIOD_TOTAL_COST) as TY_EOP_COST
FROM PRD_NAP_VWS.MERCH_INVENTORY_AGE_SKU_STORE_VW x
JOIN PRD_NAP_USR_VWS.PRODUCT_SKU_DIM_VW y
ON x.RMS_SKU_NUM = y.rms_sku_num AND x.CHANNEL_COUNTRY = y.channel_country 
WHERE BANNER_NUM IN (1,3)
AND DEPT_NUM NOT IN (584,585) AND DIV_NUM NOT IN (600)
AND CHANNEL_NUM IN (110,120,210,250)
AND MONTH_NUM IN (SELECT DISTINCT MONTH_NUM FROM PRD_NAP_USR_VWS.DAY_CAL WHERE day_date BETWEEN (select (MONTH_START_DAY_DATE -135) from CURR_WK) AND (select MONTH_START_DAY_DATE from CURR_WK))
GROUP BY 1,2) a
join
(SELECT 
MONTH_NUM,
CASE WHEN BANNER_NUM = 1 THEN 'NORDSTROM'
	 WHEN BANNER_NUM = 3 THEN 'NORDSTROM RACK' END AS BANNER,
SUM(CASE WHEN OWNERSHIP_PRICE_TYPE='R' AND  INVENTORY_AGE_DAYS >= 119 THEN END_OF_PERIOD_TOTAL_COST
		 WHEN OWNERSHIP_PRICE_TYPE='C' THEN END_OF_PERIOD_TOTAL_COST END) AS LY_EOP_COST_17Wks,
SUM(END_OF_PERIOD_TOTAL_COST) as LY_EOP_COST
FROM PRD_NAP_VWS.MERCH_INVENTORY_AGE_SKU_STORE_VW x
JOIN PRD_NAP_USR_VWS.PRODUCT_SKU_DIM_VW y
ON x.RMS_SKU_NUM = y.rms_sku_num AND x.CHANNEL_COUNTRY = y.channel_country 
WHERE BANNER_NUM IN (1,3)
AND DEPT_NUM NOT IN (584,585) AND DIV_NUM NOT IN (600)
AND CHANNEL_NUM IN (110,120,210,250)
AND MONTH_NUM IN (SELECT DISTINCT (MONTH_NUM-100) FROM PRD_NAP_USR_VWS.DAY_CAL WHERE day_date BETWEEN (select (MONTH_START_DAY_DATE -135) from CURR_WK) AND (select MONTH_START_DAY_DATE from CURR_WK))   -- Month condition
GROUP BY 1,2) b
ON A.MONTH_NUM = B.MONTH_NUM+100
AND A.BANNER = B.BANNER
join
(SELECT DISTINCT MONTH_NUM, MONTH_SHORT_DESC FROM CAL_LKUP) C
ON A.MONTH_NUM = C.MONTH_NUM ;


-- MTD Div Product Margin %
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' as OPS_NAME,
BANNER,
NULL AS CHANNEL,
'MTD Div Product Margin %' as METRIC_NAME,
MONTH_NUM AS FISCAL_NUM,
'MTD' AS FISCAL_DESC,
DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE OP_GROSS_MARGIN_RETAIL_AMT/OP_NET_SALES_RETAIL_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE CP_GROSS_MARGIN_RETAIL_AMT/CP_NET_SALES_RETAIL_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE TY_GROSS_MARGIN_RETAIL_AMT/TY_NET_SALES_RETAIL_AMT END AS TY,
CASE WHEN LY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE LY_GROSS_MARGIN_RETAIL_AMT/LY_NET_SALES_RETAIL_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
case when DIVISION_NAME in('ACCESSORIES','HOME') then 'ACC/HOME' else division_name end AS DIVISION_NAME,
MONTH_NUM,
SUM(OP_GROSS_MARGIN_RETAIL_AMT) AS OP_GROSS_MARGIN_RETAIL_AMT,
SUM(CP_GROSS_MARGIN_RETAIL_AMT) AS CP_GROSS_MARGIN_RETAIL_AMT,
SUM(TY_GROSS_MARGIN_RETAIL_AMT) AS TY_GROSS_MARGIN_RETAIL_AMT,
SUM(LY_GROSS_MARGIN_RETAIL_AMT) AS LY_GROSS_MARGIN_RETAIL_AMT,
SUM(OP_NET_SALES_RETAIL_AMT) AS OP_NET_SALES_RETAIL_AMT,
SUM(CP_NET_SALES_RETAIL_AMT) AS CP_NET_SALES_RETAIL_AMT,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY_NET_SALES_RETAIL_AMT,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY_NET_SALES_RETAIL_AMT
FROM INV_OPS_4 A
JOIN (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP WHERE MONTH_NUM = (SELECT MONTH_IDNT FROM CURR_WK) AND WEEK_NUM <= (SELECT WEEK_IDNT FROM CURR_WK)) B
ON A.WEEK_NUM = B.WEEK_NUM
GROUP BY 1,2,3) A ;


-- MTD Div Product Margin % ('TOTAL' DIVISIONS)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH_INVENTORY' as OPS_NAME,
BANNER,
NULL AS CHANNEL,
'MTD Div Product Margin %' as METRIC_NAME,
MONTH_NUM AS FISCAL_NUM,
'MTD' AS FISCAL_DESC,
DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE OP_GROSS_MARGIN_RETAIL_AMT/OP_NET_SALES_RETAIL_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE CP_GROSS_MARGIN_RETAIL_AMT/CP_NET_SALES_RETAIL_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE TY_GROSS_MARGIN_RETAIL_AMT/TY_NET_SALES_RETAIL_AMT END AS TY,
CASE WHEN LY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE LY_GROSS_MARGIN_RETAIL_AMT/LY_NET_SALES_RETAIL_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
'TOTAL' AS DIVISION_NAME,
MONTH_NUM,
SUM(OP_GROSS_MARGIN_RETAIL_AMT) AS OP_GROSS_MARGIN_RETAIL_AMT,
SUM(CP_GROSS_MARGIN_RETAIL_AMT) AS CP_GROSS_MARGIN_RETAIL_AMT,
SUM(TY_GROSS_MARGIN_RETAIL_AMT) AS TY_GROSS_MARGIN_RETAIL_AMT,
SUM(LY_GROSS_MARGIN_RETAIL_AMT) AS LY_GROSS_MARGIN_RETAIL_AMT,
SUM(OP_NET_SALES_RETAIL_AMT) AS OP_NET_SALES_RETAIL_AMT,
SUM(CP_NET_SALES_RETAIL_AMT) AS CP_NET_SALES_RETAIL_AMT,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY_NET_SALES_RETAIL_AMT,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY_NET_SALES_RETAIL_AMT
FROM INV_OPS_4 A
JOIN (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP WHERE MONTH_NUM = (SELECT MONTH_IDNT FROM CURR_WK) AND WEEK_NUM <= (SELECT WEEK_IDNT FROM CURR_WK)) B
ON A.WEEK_NUM = B.WEEK_NUM
GROUP BY 1,2,3) A ;


---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Final table insertion

DELETE FROM {environment_schema}.WEEKLY_OPS_STANDUP
WHERE OPS_NAME = 'MERCH_INVENTORY' -- Adding an extra filter since all Ops Scorecard will be using the same table
AND UPDATED_WEEK = (SELECT WEEK_IDNT FROM CURR_WK);


INSERT INTO {environment_schema}.WEEKLY_OPS_STANDUP
SELECT 
	OPS_NAME,
	BANNER,
	CHANNEL,
	METRIC_NAME,
	FISCAL_NUM,
	FISCAL_DESC,
	LABEL,
	ROLLING_FISCAL_IND,
	PLAN_OP,
	PLAN_CP,
	TY,
	LY,
	WEEK_IDNT AS UPDATED_WEEK, 
	CURRENT_TIMESTAMP as update_timestamp,
	DAY_DATE
FROM WEEKLY_OPS_STANDUP AS A, CURR_WK;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
