------------------------------------------------------------
-- Inventory Where OPS SCORECARD --
-- Date Created: 10/12/2023
-- Last Updated: 04/29/2024 - by Aman Kumar
-- Author: Ankur Niranjan
------------------------------------------------------------
-- code begins here --

CREATE MULTISET VOLATILE TABLE WEEKLY_OPS_STANDUP, --copy of the permanent table
FALLBACK,
NO BEFORE JOURNAL,
NO AFTER JOURNAL,
CHECKSUM = DEFAULT,
DEFAULT MERGEBLOCKRATIO,
MAP = TD_MAP1 
(
      OPS_NAME VARCHAR(50),
      BANNER VARCHAR(50),
      CHANNEL VARCHAR(50),
      METRIC_NAME VARCHAR(50),
      FISCAL_NUM INTEGER,
      FISCAL_DESC VARCHAR(50),
      LABEL VARCHAR(50),			-- Chart Plot Axis (x-axis)
      ROLLING_FISCAL_IND INTEGER,	-- identifier for Rolling & Forward weeks 
      PLAN_OP FLOAT,
      PLAN_CP FLOAT,
      TY FLOAT,
      LY FLOAT,						-- most recent completed week	
	  DAY_DATE DATE					-- Adding new column to accomodate Holiday Season data
) PRIMARY INDEX (OPS_NAME,BANNER,METRIC_NAME,FISCAL_NUM,LABEL)  ON COMMIT PRESERVE rows ;

------------------------------------------------------------------------------------------------


 -- WK Identifier for automating weekly plots
CREATE MULTISET VOLATILE TABLE CURR_WK AS (
SELECT WEEK_IDNT
, WEEK_START_DAY_DATE
, WEEK_END_DAY_DATE
, MONTH_IDNT
, MONTH_START_DAY_DATE 
, MONTH_END_DAY_DATE
, QUARTER_IDNT
, QUARTER_START_DAY_DATE
, QUARTER_END_DAY_DATE
FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM
WHERE day_date = {start_date} - 7
) WITH data PRIMARY INDEX (WEEK_IDNT) ON COMMIT PRESERVE rows ;



 -- CAL_LKUP;
CREATE MULTISET VOLATILE TABLE CAL_LKUP AS (
SELECT DISTINCT
a.WEEK_NUM
, a.WEEK_454_NUM
, a.MONTH_SHORT_DESC
, b.WEEK_START_DAY_DATE
, b.WEEK_END_DAY_DATE
, a.MONTH_NUM
, b.MONTH_START_DAY_DATE
, b.MONTH_END_DAY_DATE
, a.YEAR_NUM
, a.quarter_num
, b.quarter_start_day_date
, b.quarter_end_day_date
FROM PRD_NAP_USR_VWS.DAY_CAL a
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM b
on a.WEEK_NUM = b.WEEK_IDNT
and a.MONTH_NUM = b.MONTH_IDNT
WHERE b.day_date BETWEEN ({start_date}-220) AND ({start_date}+220) -- {start_date} and {end_date}	
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;

-----------------------------------------------------------------------------------------------

--- VASN TO STORE RECEIVE TIME AVG/P90 ---

CREATE MULTISET VOLATILE TABLE BAN_CNTRY_STORE_DIM_VW AS
(SELECT	org.*,
	    case when store_country_code = 'US' and channel_num in (110, 120, 140, 310, 920, 940, 990) then 'FP US'
                   when store_country_code = 'US' and channel_num in (210, 220, 250, 260) then 'OP US'
		           when store_country_code = 'CA' and channel_num in (111, 121, 311, 921) then 'FP CA'
		           when store_country_code = 'CA' and channel_num in (211, 221, 261, 922) then 'OP CA'
	    end as banner_country
FROM PRD_NAP_USR_VWS.STORE_DIM ORG) WITH DATA PRIMARY INDEX (BANNER_COUNTRY) ON COMMIT PRESERVE ROWS ;



CREATE MULTISET VOLATILE TABLE PO_DISTRIBUTE_STORE_VW AS
(select distinct 
    PURCHASE_ORDER_NUM as PURCHASE_ORDER_NUM
	,SHIP_LOCATION_ID as SHIP_LOCATION_ID
    ,FIRST_VALUE(DISTRIBUTE_LOCATION_ID) over (partition by PURCHASE_ORDER_NUM, SHIP_LOCATION_ID order by sum_allocated_qty desc, sum_prescaled_qty desc, DISTRIBUTE_LOCATION_ID asc) as MIN_DIST_LOC
from (
select
	 PURCHASE_ORDER_NUM
	,SHIP_LOCATION_ID
    ,DISTRIBUTE_LOCATION_ID
    ,sum(ALLOCATED_QTY) as sum_allocated_qty
    ,sum(PRESCALED_QTY) as sum_prescaled_qty
from PRD_NAP_USR_VWS.PURCHASE_ORDER_ITEM_DISTRIBUTELOCATION_FACT
group by 1,2,3
) po_qty
) WITH DATA PRIMARY INDEX (PURCHASE_ORDER_NUM,SHIP_LOCATION_ID) ON COMMIT PRESERVE ROWS ;


CREATE MULTISET VOLATILE TABLE CYCLE_TIME AS (
SELECT
WEEK_IDNT,
SUPP.VENDOR_NAME,
ISF.INBOUND_WAREHOUSE_NUM ,
ISF.FINAL_WAREHOUSE_NUM,
ISF.STORE_NUM,
ISF.SHIPPING_METHOD,
ISF.DIRECT_TO_STORE_IND,
ISF.PURCHASE_ORDER_TYPE,
ISF.ORDER_TYPE,
CAST((TRIM(LEADING ' ' FROM CAST(SKU.DEPT_NUM as varchar(4))) || ', ' || DEPT.DEPT_SHORT_NAME) as varchar(40)) DEPT_DESC ,
CASE WHEN ISF.PURCHASE_ORDER_PREMARK_IND = 't' THEN 'Store Pack' WHEN ISF.PURCHASE_ORDER_PREMARK_IND = 'f' THEN 'Bulk Sort' ELSE 'Null' END premark_ind,
CASE WHEN ISF.NORDSTROM_PRODUCTGROUP_IND = 'T' THEN 'Y' ELSE 'N' END NPG_FLAG,
COALESCE(DIST_ORG.BANNER_COUNTRY, ORG.BANNER_COUNTRY) AS BANNER_COUNTRY ,
VENDOR_SHIPPED_TO_STORE_RECEIVED_DAYS,
VENDOR_SHIPPED_TO_WAREHOUSE_RECEIVED_DAYS,
WAREHOUSE_RECEIVED_TO_WAREHOUSE_SHIPPED_DAYS,
WAREHOUSE_SHIPPED_TO_STORE_RECEIVED_DAYS,
SUM(ISF.UNIT_QTY) AS UNIT_QTY,
SUM(VENDOR_SHIPPED_TO_STORE_RECEIVED_DAYS*ISF.UNIT_QTY) WEIGHTED_CYCLE_UNITS_VENDORSTORE
FROM PRD_NAP_USR_VWS.CARTON_LIFECYCLE_FACT_VW ISF
LEFT JOIN BAN_CNTRY_STORE_DIM_VW ORG
ON COALESCE(CAST(ISF.INBOUND_WAREHOUSE_NUM AS NUMBER),ISF.STORE_NUM) = CAST(ORG.STORE_NUM AS NUMBER)
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM CAL
ON CAL.DAY_DATE = COALESCE(CAST((ISF.STORE_RECEIVED_TMSTP) AS DATE),CAST('1901-01-01' AS DATE FORMAT 'YYYY-MM-DD') )
LEFT JOIN
(SELECT PURCHASE_ORDER_NUM,
CASE WHEN SHIP_LOCATION_ID IN (869,896,891,859,889,856)THEN 868
WHEN SHIP_LOCATION_ID = 562 THEN 569
WHEN SHIP_LOCATION_ID = 563 THEN 599
WHEN BC.STORE_TYPE_CODE IN ('RR','RS','WH') THEN BC.DISTRIBUTION_CENTER_NUM
ELSE SHIP_LOCATION_ID END AS SHIP_LOCATION_ID_DRVD,
MIN(MIN_DIST_LOC) AS MIN_DIST_LOC
FROM PO_DISTRIBUTE_STORE_VW PO
JOIN BAN_CNTRY_STORE_DIM_VW BC
ON PO.SHIP_LOCATION_ID = BC.STORE_NUM
GROUP BY 1,2) DIST
ON ISF.INBOUND_WAREHOUSE_NUM = SHIP_LOCATION_ID_DRVD AND ISF.PURCHASE_ORDER_NUM = DIST.PURCHASE_ORDER_NUM
LEFT JOIN BAN_CNTRY_STORE_DIM_VW DIST_ORG ON DIST.MIN_DIST_LOC = DIST_ORG.STORE_NUM
LEFT JOIN PRD_NAP_USR_VWS.PRODUCT_SKU_DIM SKU ON ISF.RMS_SKU_NUM = SKU.RMS_SKU_NUM AND ORG.STORE_COUNTRY_CODE = SKU.CHANNEL_COUNTRY
LEFT JOIN PRD_NAP_USR_VWS.VENDOR_DIM SUPP ON COALESCE(SKU.PRMY_SUPP_NUM, ISF.SUPPLIER_NUM) = SUPP.VENDOR_NUM
LEFT JOIN PRD_NAP_USR_VWS.DEPARTMENT_DIM DEPT ON DEPT.DEPT_NUM = SKU.DEPT_NUM
WHERE WEEK_IDNT IN (SELECT DISTINCT WEEK_NUM FROM CAL_LKUP WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK))
AND UNIT_QTY >= 0
AND VENDOR_SHIPPED_TO_STORE_RECEIVED_DAYS>0                       ----Added filter to exclude -ve receipts 
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
) WITH DATA PRIMARY INDEX (BANNER_COUNTRY,WEEK_IDNT) ON COMMIT PRESERVE ROWS ;


-- TOTAL
CREATE MULTISET VOLATILE TABLE CYCLE_TIME_TOTAL AS (
SELECT
BANNER_COUNTRY,
WEEK_IDNT,
(CAST(SUM(VENDOR_SHIPPED_TO_STORE_RECEIVED_DAYS*UNIT_QTY) AS FLOAT)/CAST(SUM(UNIT_QTY) AS FLOAT)) AS VASN_STORE_RECIEVE_AVG,
(PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY WEIGHTED_CYCLE_UNITS_VENDORSTORE/UNIT_QTY ASC))	AS VASN_STORE_RECIEVE_P90
FROM CYCLE_TIME
WHERE NPG_FLAG = 'N'
AND STORE_NUM NOT IN (11,47,48,706)  ---2024-01-18 to exclude HI & AK stores
AND vendor_name not like '%NIKE%'    ---2024-01-18 to exclude vendor "NIKE"
AND UNIT_QTY>0                      ---2024-01-30 to avoid division by zero error      
GROUP BY 1,2) WITH DATA PRIMARY INDEX (BANNER_COUNTRY,WEEK_IDNT) ON COMMIT PRESERVE ROWS ;

-- DOM_SP
CREATE MULTISET VOLATILE TABLE CYCLE_TIME_DOM_SP AS (
SELECT
BANNER_COUNTRY,
WEEK_IDNT,
(CAST(SUM(VENDOR_SHIPPED_TO_STORE_RECEIVED_DAYS*UNIT_QTY) AS FLOAT)/CAST(SUM(UNIT_QTY) AS FLOAT)) AS VASN_STORE_RECIEVE_AVG,
(PERCENTILE_DISC(.9) WITHIN GROUP (ORDER BY WEIGHTED_CYCLE_UNITS_VENDORSTORE/UNIT_QTY ASC))	AS VASN_STORE_RECIEVE_P90
FROM CYCLE_TIME
WHERE NPG_FLAG = 'N'
AND STORE_NUM NOT IN (11,47,48,706)
AND vendor_name not like '%NIKE%'     ---2024-01-18 to exclude vendor "NIKE"
AND PREMARK_IND = 'Store Pack' 
AND UNIT_QTY>0                      ---2024-01-30 to avoid division by zero error
GROUP BY 1,2) WITH DATA PRIMARY INDEX (BANNER_COUNTRY,WEEK_IDNT) ON COMMIT PRESERVE ROWS ;


-- VASN TO STORE RECEIVE TIME (Total P90)
INSERT into WEEKLY_OPS_STANDUP
select
'INVENTORY WHERE' AS OPS_NAME,
CASE WHEN BANNER_COUNTRY = 'FP US' THEN 'NORDSTROM' when BANNER_COUNTRY = 'OP US' THEN 'NORDSTROM RACK' END AS BANNER,
NULL AS CHANNEL,
'VASN to Store Receive Time (Total P90)' as METRIC_NAME,
WEEK_IDNT AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE when BANNER_COUNTRY = 'FP US' THEN 21 
	 when BANNER_COUNTRY = 'OP US' THEN 28 END AS PLAN_OP,
NULL AS PLAN_CP,
VASN_STORE_RECIEVE_P90 as TY,
NULL AS LY,
NULL AS DAY_DATE
from CYCLE_TIME_TOTAL a
join cal_lkup b on a.week_idnt = b.week_num;


-- VASN TO STORE RECEIVE TIME (DOMESTIC STORE PACK P90)
INSERT into WEEKLY_OPS_STANDUP
select
'INVENTORY WHERE' as OPS_NAME,
CASE WHEN BANNER_COUNTRY = 'FP US' THEN 'NORDSTROM' when BANNER_COUNTRY = 'OP US' THEN 'NORDSTROM RACK' END AS BANNER,
NULL AS CHANNEL,
'VASN to Store Receive Time (DOM_SP P90)' as METRIC_NAME,
WEEK_IDNT AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE when BANNER_COUNTRY = 'OP US' THEN 21 END AS PLAN_OP,
NULL AS PLAN_CP,
VASN_STORE_RECIEVE_P90 as TY,
NULL AS LY,
NULL AS DAY_DATE
from CYCLE_TIME_DOM_SP a
join cal_lkup b on a.week_idnt = b.week_num;


-- VASN TO STORE RECEIVE TIME (Total AVG)
INSERT into WEEKLY_OPS_STANDUP
select
'INVENTORY WHERE' as OPS_NAME,
CASE WHEN BANNER_COUNTRY = 'FP US' THEN 'NORDSTROM' when BANNER_COUNTRY = 'OP US' THEN 'NORDSTROM RACK' END AS BANNER,
NULL AS CHANNEL,
'VASN to Store Receive Time (Total AVG)' as METRIC_NAME,
WEEK_IDNT AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE when BANNER_COUNTRY = 'FP US' THEN 14 
	 when BANNER_COUNTRY = 'OP US' THEN 14 END AS PLAN_OP,
NULL AS PLAN_CP,
VASN_STORE_RECIEVE_AVG as TY,
NULL AS LY,
NULL AS DAY_DATE
from CYCLE_TIME_TOTAL a
join cal_lkup b on a.week_idnt = b.week_num;


-- VASN TO STORE RECEIVE TIME (DOMESTIC STORE PACK AVG)
INSERT into WEEKLY_OPS_STANDUP
select
'INVENTORY WHERE' as OPS_NAME,
CASE WHEN BANNER_COUNTRY = 'FP US' THEN 'NORDSTROM' when BANNER_COUNTRY = 'OP US' THEN 'NORDSTROM RACK' END AS BANNER,
NULL AS CHANNEL,
'VASN to Store Receive Time (DOM_SP AVG)' as METRIC_NAME,
WEEK_IDNT AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
NULL AS ROLLING_FISCAL_IND,
NULL AS PLAN_OP,
NULL AS PLAN_CP,
VASN_STORE_RECIEVE_AVG as TY,
NULL AS LY,
NULL AS DAY_DATE
from CYCLE_TIME_DOM_SP a
join cal_lkup b on a.week_idnt = b.week_num ;

------------------------------------------------------------------------------------------

--- RECEIPT CHANNEL SPLIT (COMMITTED U) ---

-- Step 1: Pulling Planned numbers, at Month X Channel X Dept level
CREATE MULTISET VOLATILE TABLE RCPT_PLAN AS (
SELECT A.MTH_IDNT, MONTH_SHORT_DESC, QUARTER_NUM, A.CHNL_IDNT, DEPT_IDNT, SUM(PLAN_RCPT_U) AS PLAN_RCPT_U
FROM T2DL_DAS_APT.DEPT_CHNL_SPLIT_INTENTIONAL A
INNER JOIN
(SELECT DISTINCT DEPT_NUM
FROM PRD_NAP_USR_VWS.DEPARTMENT_DIM_HIST
WHERE EFF_END_TMSTP = (SELECT MAX(EFF_END_TMSTP) FROM PRD_NAP_USR_VWS.DEPARTMENT_DIM_HIST)
AND DEPT_SUBTYPE_CODE = 'MO'
AND ACTIVE_STORE_IND = 'A'
AND DEPT_NAME NOT LIKE ALL ('%OP%','%INACTIVE%','%NQC%', '%FLX%', '%DUMMY%', '%AM%', 'CP%', '%NPG%', '%TEST%', 'chrome%RESERVE%')
AND DIVISION_NUM <> 60) B
ON A.DEPT_IDNT = B.DEPT_NUM
INNER JOIN 
-- AUTOMATING DATES FOR FETCHING 3 QUARTERS/9 MONTHS OF DATA
(SELECT DISTINCT MONTH_SHORT_DESC, MONTH_NUM, QUARTER_NUM 
FROM CAL_LKUP, CURR_WK
WHERE ((CAL_LKUP.MONTH_START_DAY_DATE BETWEEN (SELECT (MONTH_START_DAY_DATE -100)  FROM CURR_WK) AND (SELECT (MONTH_START_DAY_DATE +170) FROM CURR_WK)) AND (CURR_WK.MONTH_START_DAY_DATE = CURR_WK.QUARTER_START_DAY_DATE)) 
   OR ((CAL_LKUP.MONTH_START_DAY_DATE BETWEEN (SELECT (MONTH_START_DAY_DATE -170) FROM CURR_WK) AND (SELECT (MONTH_START_DAY_DATE +100)  FROM CURR_WK)) AND (CURR_WK.MONTH_END_DAY_DATE = CURR_WK.QUARTER_END_DAY_DATE))  
   OR ((CAL_LKUP.MONTH_START_DAY_DATE BETWEEN (SELECT (MONTH_START_DAY_DATE -130) FROM CURR_WK) AND (SELECT (MONTH_START_DAY_DATE +135) FROM CURR_WK)) AND (CURR_WK.MONTH_END_DAY_DATE <> CURR_WK.QUARTER_END_DAY_DATE) AND (CURR_WK.MONTH_START_DAY_DATE <> CURR_WK.QUARTER_START_DAY_DATE))) c 
ON A.MTH_IDNT = C.MONTH_NUM
INNER JOIN
-- DEFINING PLAN MONTH, BASED ON LATEST (MAX) PLAN_CYCLE AVAILABLE FOR EACH MONTH
(SELECT 
MTH_IDNT, 
CHNL_IDNT,
MAX(PLAN_CYCLE) AS PLAN_CYCLE
FROM T2DL_DAS_APT.DEPT_CHNL_SPLIT_INTENTIONAL 
WHERE CHNL_IDNT IN (110,120,210,250)
GROUP BY 1,2) D
ON A.MTH_IDNT = D.MTH_IDNT AND A.PLAN_CYCLE = D.PLAN_CYCLE AND A.CHNL_IDNT = D.CHNL_IDNT
WHERE A.CHNL_IDNT IN (110,120,210,250)
AND PLAN_RCPT_U > 0
GROUP BY 1,2,3,4,5
) WITH DATA PRIMARY INDEX (MTH_IDNT,CHNL_IDNT,DEPT_IDNT) ON COMMIT PRESERVE ROWS ;


-- Step 2: Taggind Actual numbers at Month X Channel X Dept Level
CREATE MULTISET VOLATILE TABLE RCPT_PLAN_ACT AS (
SELECT
A.MTH_IDNT,
MONTH_SHORT_DESC, 
QUARTER_NUM,
CASE WHEN CHNL_IDNT IN (110,120) THEN 'NORDSTROM'
	 WHEN CHNL_IDNT IN (210,250) THEN 'NORDSTROM RACK' END AS BANNER,
CASE WHEN CHNL_IDNT = 110 THEN 'FLS'
	 WHEN CHNL_IDNT = 120 THEN 'N.COM'
	 WHEN CHNL_IDNT = 210 THEN 'RACK STORE'
	 WHEN CHNL_IDNT = 250 THEN 'R.COM' END AS CHANNEL,
SUM(PLAN_RCPT_U) AS PLAN,
SUM(NRP_OO_U) AS NRP_OO_U,
SUM(NRP_CM_U) AS NRP_CM_U,
SUM(NRP_RCPTS_MTD_U) AS NRP_RCPT_MTD,
SUM(PO_RCPT_U) AS PO_RCPT_U
FROM RCPT_PLAN A
LEFT JOIN
(SELECT
MONTH_IDNT,
STRTOK(CHANNEL,',',1) AS CHNL,
STRTOK(DEPARTMENT,',',1) AS DEPT_IDNT,
SUM(NRP_OO_U) AS NRP_OO_U,
SUM(NRP_CM_U) AS NRP_CM_U,
SUM(NRP_RCPTS_MTD_U) AS NRP_RCPTS_MTD_U
FROM T2DL_DAS_OPEN_TO_BUY.APT_SUPP_CAT_SPEND_CURRENT APT 
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = APT.MONTH_LABEL
WHERE SELLING_COUNTRY = 'US'
AND ACTIVE_DIVISION = 'A'
AND ALT_INV_MODEL = 'NON-FANATICS'
AND STRTOK(Channel,',',1) IN (110,120,210,250)
GROUP BY 1,2,3) b
ON A.CHNL_IDNT = B.CHNL AND A.MTH_IDNT = B.MONTH_IDNT AND A.DEPT_IDNT = B.DEPT_IDNT
LEFT JOIN
(SELECT
MONTH_NUM,
CHANNEL_NUM,
DEPT_NUM,
SUM(RECEIPTS_PO_UNITS_TY) AS PO_RCPT_U
FROM PRD_NAP_VWS.MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT_VW
WHERE CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3) C
ON A.CHNL_IDNT = C.CHANNEL_NUM AND A.MTH_IDNT = C.MONTH_NUM AND A.DEPT_IDNT = C.DEPT_NUM
GROUP BY 1,2,3,4,5
) WITH data PRIMARY INDEX (MTH_IDNT, BANNER, CHANNEL) ON COMMIT PRESERVE ROWS ;



-- Step 3: Final Channel Split table: defining Actual
CREATE MULTISET VOLATILE TABLE CHANNEL_SPLIT AS (
SELECT
BANNER,
CHANNEL,
MTH_IDNT,
MONTH_SHORT_DESC, 
QUARTER_NUM,
PLAN,
case when (NRP_OO_U + NRP_CM_U + NRP_Rcpt_MTD) > 0 then (NRP_OO_U + NRP_CM_U + NRP_Rcpt_MTD) else PO_Rcpt_U end AS Actual
from RCPT_PLAN_ACT 
) WITH data PRIMARY INDEX (MTH_IDNT, BANNER) ON COMMIT PRESERVE rows ;


-- INSERTING QUARTERLY NUMBERS (PREVIOUS AND CURRENT QUARTER)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'INVENTORY WHERE' as OPS_NAME,
A.BANNER,
A.CHANNEL,
'Receipt Channel Split (Committed U)' AS METRIC_NAME,
A.QUARTER_NUM AS FISCAL_NUM,
'QUARTER' AS FISCAL_DESC,
CASE WHEN RIGHT(CAST(A.QUARTER_NUM AS VARCHAR(12)),1) = 1 THEN 'Q1'
	 WHEN RIGHT(CAST(A.QUARTER_NUM AS VARCHAR(12)),1) = 2 THEN 'Q2'
	 WHEN RIGHT(CAST(A.QUARTER_NUM AS VARCHAR(12)),1) = 3 THEN 'Q3'
	 WHEN RIGHT(CAST(A.QUARTER_NUM AS VARCHAR(12)),1) = 4 THEN 'Q4'
	 END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CAST(A.PLAN AS FLOAT)/CAST(B.PLAN AS FLOAT) AS PLAN_OP,
NULL AS PLAN_CP,
CAST(A.ACTUAL AS FLOAT)/CAST(B.ACTUAL AS FLOAT) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM 
(SELECT
QUARTER_NUM,
BANNER,
CHANNEL,
SUM(PLAN) AS PLAN,
SUM(ACTUAL) AS ACTUAL
FROM CHANNEL_SPLIT 
GROUP BY 1,2,3) A
JOIN
(SELECT
QUARTER_NUM,
BANNER,
SUM(PLAN) AS PLAN,
SUM(ACTUAL) AS ACTUAL
FROM CHANNEL_SPLIT
GROUP BY 1,2) B
ON A.QUARTER_NUM = B.QUARTER_NUM AND A.BANNER = B.BANNER
where A.QUARTER_NUM < (SELECT MAX(QUARTER_NUM) AS QUARTER_NUM FROM CHANNEL_SPLIT) ;


-- INSERTING MONTHLY DATA FOR NEXT QUARTER
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'INVENTORY WHERE' as OPS_NAME,
A.BANNER,
A.CHANNEL,
'Receipt Channel Split (Committed U)' AS METRIC_NAME,
A.MTH_IDNT AS FISCAL_NUM,
'MONTH' AS FISCAL_DESC,
MONTH_SHORT_DESC AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CAST(A.PLAN AS FLOAT)/CAST(B.PLAN AS FLOAT) AS PLAN_OP,
NULL AS PLAN_CP,
CAST(A.ACTUAL AS FLOAT)/CAST(B.ACTUAL AS FLOAT) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM CHANNEL_SPLIT A
JOIN
(SELECT
MTH_IDNT,
BANNER,
SUM(PLAN) AS PLAN,
SUM(ACTUAL) AS ACTUAL
FROM CHANNEL_SPLIT
GROUP BY 1,2) B
ON A.MTH_IDNT = B.MTH_IDNT AND A.BANNER = B.BANNER
where A.QUARTER_NUM = (SELECT MAX(QUARTER_NUM) AS QUARTER_NUM FROM CHANNEL_SPLIT) ;

------------------------------------------------------------------------------------------------

------------------- MTD Rcpt vs Plan by Region(U)-------------------------


----STEP 1: Pulling Rcpt_Plan for Channel(Nord) 

CREATE MULTISET VOLATILE TABLE Rcpt_Plan_Nord AS (
SELECT
fls.month_idnt 
,MONTH_ABRV
,(CAST(SUM(COALESCE(total_receipts_total_units_ty,0) + COALESCE(total_po_oo_u,0) + COALESCE(in_transit_qty,0)) as float)/CAST(SUM(rcpt_plan) as FLOAT)) AS Rcpt_to_Plan
FROM T2DL_DAS_LIT.location_inventory_tracking_total fls ---------2024-06-17 changed table
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT,MONTH_ABRV, QUARTER_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = fls.MONTH_LABEL
WHERE store_open_date <= CURRENT_DATE() 
AND fls.MONTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND chnl_idnt=110 ---------2024-06-17 to filter for Nord stores
AND rcpt_plan>0 ----to avoid division by zero error
GROUP BY 1,2
) WITH data PRIMARY INDEX (month_idnt,MONTH_ABRV) ON COMMIT PRESERVE ROWS ;

----Inserting %locations within 10% of channel adjusted receipt plan for Nord

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'INVENTORY WHERE' as OPS_NAME,
'NORDSTROM' as banner,
NULL as channel,
'MTD Rcpt vs. Plan by Region(U)' AS METRIC_NAME,
A.MONTH_IDNT AS FISCAL_NUM,
MONTH_ABRV AS FISCAL_DESC,
subgroup_short_desc AS LABEL,
NULL AS ROLLING_FISCAL_IND,
NULL AS PLAN_OP,
NULL AS PLAN_CP,
loc_per AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM 
(SELECT month_idnt
,month_abrv
,subgroup_short_desc
,count(DISTINCT CASE WHEN (loc_Rcpt_to_Plan>= (0.9)*Rcpt_to_Plan AND loc_Rcpt_to_Plan <=(1.1)*Rcpt_to_Plan) then loc_idnt END) as loc_count
,count(DISTINCT loc_idnt) as loc_total
,CAST(count(DISTINCT CASE WHEN (loc_Rcpt_to_Plan>= (0.9)*Rcpt_to_Plan AND loc_Rcpt_to_Plan <=(1.1)*Rcpt_to_Plan) then loc_idnt END) AS FLOAT)/
CAST(count(DISTINCT loc_idnt) AS FLOAT) as loc_per
from
(SELECT
fls.month_idnt 
,DCD.MONTH_ABRV
,loc_idnt 
,subgroup_short_desc
,(CAST(SUM(COALESCE(total_receipts_total_units_ty,0) + COALESCE(total_po_oo_u,0) + COALESCE(in_transit_qty,0)) as float)/CAST(SUM(rcpt_plan) as FLOAT)) AS loc_Rcpt_to_Plan
,b.Rcpt_to_Plan
FROM T2DL_DAS_LIT.location_inventory_tracking_total fls ---------2024-06-17 changed table
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT,MONTH_ABRV, QUARTER_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = fls.MONTH_LABEL
JOIN Rcpt_Plan_Nord as b on fls.month_idnt=b.month_idnt
WHERE store_open_date <= CURRENT_DATE() 
AND fls.MONTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND chnl_idnt=110 ---------2024-06-17 to filter for Nord stores
AND rcpt_plan>0 ----to avoid division by zero error
GROUP BY 1,2,3,4,6) A
group by 1,2,3) A;

----------Inserting Adjusted receipt plan at region level for Nord

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'INVENTORY WHERE' as OPS_NAME,
'NORDSTROM' as banner,
NULL as channel,
'Adj Rcpt Plan by Region (U)' AS METRIC_NAME,
A.MONTH_IDNT AS FISCAL_NUM,
MONTH_ABRV AS FISCAL_DESC,
subgroup_short_desc AS LABEL,
NULL AS ROLLING_FISCAL_IND,
Rcpt_Plan AS PLAN_OP,
NULL AS PLAN_CP,
Actual AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM 
(SELECT
fls.month_idnt 
,DCD.MONTH_ABRV 
,subgroup_short_desc
,CAST(SUM(COALESCE(total_receipts_total_units_ty,0) + COALESCE(total_po_oo_u,0) + COALESCE(in_transit_qty,0)) as float) as Actual
,CAST(SUM(rcpt_plan) as FLOAT) AS Rcpt_Plan
FROM T2DL_DAS_LIT.location_inventory_tracking_total fls ---------2024-06-17 changed table
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT,MONTH_ABRV, QUARTER_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = fls.MONTH_LABEL
WHERE store_open_date <= CURRENT_DATE() 
AND fls.MONTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND chnl_idnt=110 ---------2024-06-17 to filter for Nord stores
AND rcpt_plan>0 ----to avoid division by zero error
GROUP BY 1,2,3) A;


---------------STEP 1: Pulling Rcpt_Plan for Channel(Rack)--------

CREATE MULTISET VOLATILE TABLE Rcpt_Plan_rack AS (
SELECT
rack.month_idnt 
,MONTH_ABRV
,(CAST(SUM(COALESCE(total_receipts_total_units_ty,0) + COALESCE(total_po_oo_u,0) + COALESCE(in_transit_qty,0)) as float)/CAST(SUM(rcpt_plan) as FLOAT)) AS Rcpt_to_Plan
FROM T2DL_DAS_LIT.location_inventory_tracking_total rack  ---2024-06-17 changed table
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT,MONTH_ABRV, QUARTER_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = rack.MONTH_LABEL
WHERE store_open_date <= CURRENT_DATE() 
AND rack.MONTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND chnl_idnt=210  ----2024-06-17 to filter for Rack stores
AND rcpt_plan>0 ----to avoid division by zero error
GROUP BY 1,2
) WITH data PRIMARY INDEX (month_idnt,MONTH_ABRV) ON COMMIT PRESERVE ROWS ;

----Inserting %locations within 10% of channel adjusted receipt plan(Rack)

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'INVENTORY WHERE' as OPS_NAME,
'NORDSTROM RACK' as banner,
NULL as channel,
'MTD Rcpt vs. Plan by Region(U)' AS METRIC_NAME,
A.MONTH_IDNT AS FISCAL_NUM,
MONTH_ABRV AS FISCAL_DESC,
subgroup_short_desc AS LABEL,
NULL AS ROLLING_FISCAL_IND,
NULL AS PLAN_OP,
NULL AS PLAN_CP,
loc_per AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM 
(SELECT month_idnt
,month_abrv
,subgroup_short_desc
,count(DISTINCT CASE WHEN (loc_Rcpt_to_Plan>= (0.9)*Rcpt_to_Plan AND loc_Rcpt_to_Plan <=(1.1)*Rcpt_to_Plan) then loc_idnt END) as loc_count
,count(DISTINCT loc_idnt) as loc_total
,CAST(count(DISTINCT CASE WHEN (loc_Rcpt_to_Plan>= (0.9)*Rcpt_to_Plan AND loc_Rcpt_to_Plan <=(1.1)*Rcpt_to_Plan) then loc_idnt END) AS FLOAT)/
CAST(count(DISTINCT loc_idnt) AS FLOAT) as loc_per
from
(SELECT
rack.month_idnt 
,DCD.MONTH_ABRV
,loc_idnt 
,subgroup_short_desc
,(CAST(SUM(COALESCE(total_receipts_total_units_ty,0) + COALESCE(total_po_oo_u,0) + COALESCE(in_transit_qty,0)) as float)/CAST(SUM(rcpt_plan) as FLOAT)) AS loc_Rcpt_to_Plan
,b.Rcpt_to_Plan
FROM T2DL_DAS_LIT.location_inventory_tracking_total rack  ---2024-06-17 changed table
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT,MONTH_ABRV, QUARTER_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = rack.MONTH_LABEL
JOIN Rcpt_Plan_rack as b on rack.month_idnt=b.month_idnt
WHERE store_open_date <= CURRENT_DATE() 
AND rack.MONTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND chnl_idnt=210  ----2024-06-17 to filter for Rack stores
AND rcpt_plan>0 ----to avoid division by zero error
GROUP BY 1,2,3,4,6) A
group by 1,2,3) A;

----------Inserting Adjusted receipt plan at region level for Rack

INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'INVENTORY WHERE' as OPS_NAME,
'NORDSTROM RACK' as banner,
NULL as channel,
'Adj Rcpt Plan by Region (U)' AS METRIC_NAME,
A.MONTH_IDNT AS FISCAL_NUM,
MONTH_ABRV AS FISCAL_DESC,
subgroup_short_desc AS LABEL,
NULL AS ROLLING_FISCAL_IND,
Rcpt_Plan AS PLAN_OP,
NULL AS PLAN_CP,
Actual AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM 
(SELECT
rack.month_idnt 
,DCD.MONTH_ABRV 
,subgroup_short_desc
,CAST(SUM(COALESCE(total_receipts_total_units_ty,0) + COALESCE(total_po_oo_u,0) + COALESCE(in_transit_qty,0)) as float) as Actual
,CAST(SUM(rcpt_plan) as FLOAT) AS Rcpt_Plan
FROM T2DL_DAS_LIT.location_inventory_tracking_total rack  ---2024-06-17 changed table
JOIN (SELECT DISTINCT MONTH_LABEL, MONTH_IDNT,MONTH_ABRV, QUARTER_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM) DCD ON DCD.MONTH_LABEL = rack.MONTH_LABEL
WHERE store_open_date <= CURRENT_DATE() 
AND rack.MONTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND chnl_idnt=210  ----2024-06-17 to filter for Rack stores
AND rcpt_plan>0 ----to avoid division by zero error
GROUP BY 1,2,3) A;


/**
-- Step 1: Pulling SALES_PLAN for each location for the month of 202307
CREATE MULTISET VOLATILE TABLE SALES_LOCATION AS (
SELECT
MTH_IDNT,
CASE WHEN business_unit_medium_desc = 'FULL LINE' THEN 'NORDSTROM' ELSE 'NORDSTROM RACK' END AS BANNER,
LOC_IDNT AS LOCATION,
SUM(SALES_PLAN) AS SALES_PLAN,
SUM(RCPT_PLAN) AS RCPT_PLAN
FROM T2DL_DAS_LOCATION_PLANNING.LOC_PLAN_PRD_VW A
JOIN PRD_NAP_USR_VWS.STORE_DIM B ON A.LOC_IDNT = B.STORE_NUM
WHERE MTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND business_unit_medium_desc IN ('FULL LINE','RACK')
AND ((STORE_OPEN_DATE <= (SELECT WEEK_END_DAY_DATE FROM CURR_WK) and business_unit_medium_desc IN ('RACK')) or business_unit_medium_desc IN ('FULL LINE'))  --2024-01-30 Excludes New Rack Stores from Store Grade Calculations
GROUP BY 1,2,3
) WITH data PRIMARY INDEX (MTH_IDNT,BANNER,LOCATION) ON COMMIT PRESERVE ROWS ;


-- Step 2: Calculating AVG SALES_PLAN at Banner level (Nordstrom and Rack), i.e. SALES_PLAN per LOCATION
CREATE MULTISET VOLATILE TABLE AVG_SALES AS (
SELECT 
BANNER,
AVG(SALES_PLAN) as AVG_SALES_PLAN
from SALES_LOCATION
group by 1
) WITH data PRIMARY INDEX (BANNER) ON COMMIT PRESERVE rows ;


-- Step 3 : Take count of stores for both Nordstrom and Rack
CREATE MULTISET VOLATILE TABLE LOC_COUNT AS (
SELECT 
CASE WHEN business_unit_medium_desc = 'FULL LINE' THEN 'NORDSTROM' ELSE 'NORDSTROM RACK' END AS BANNER,
COUNT(DISTINCT LOC_IDNT) AS NUM_LOC
FROM T2DL_DAS_LOCATION_PLANNING.LOC_PLAN_PRD_VW LP
JOIN PRD_NAP_USR_VWS.STORE_DIM OS ON OS.STORE_NUM = LP.LOC_IDNT
WHERE business_unit_medium_desc IN ('FULL LINE','RACK')
AND MTH_IDNT = (SELECT MONTH_IDNT FROM CURR_WK)
AND ((STORE_OPEN_DATE <= (SELECT WEEK_END_DAY_DATE FROM CURR_WK) and business_unit_medium_desc IN ('RACK')) or business_unit_medium_desc IN ('FULL LINE')) --2024-01-30 Excludes New Rack Stores from Store Count
GROUP BY 1
) WITH DATA PRIMARY INDEX (BANNER) ON COMMIT PRESERVE ROWS ; 


-- Step 4: Calculate Std deviation for both Nordstrom and Rack
CREATE MULTISET VOLATILE TABLE STD_DEV AS (
SELECT 
A.BANNER,
SQRT(DEV_SQ_SUM/NUM_LOC) AS STD_DEV
FROM
(SELECT 
BANNER,
SUM(DEV_SQ) AS DEV_SQ_SUM
FROM
(SELECT
A.BANNER,
LOCATION,
(SALES_PLAN - AVG_SALES_PLAN)**2 AS DEV_SQ
FROM SALES_LOCATION A
JOIN AVG_SALES B ON A.BANNER = B.BANNER) A
GROUP BY 1) A
JOIN LOC_COUNT B ON A.BANNER = B.BANNER
) WITH DATA PRIMARY INDEX (BANNER) ON COMMIT PRESERVE ROWS ;


-- Step 5: Calculating Z Score for each Store and defining Store grade (A,B,C,D,E)
CREATE MULTISET VOLATILE TABLE STORE_GRADE AS ( 
SELECT DISTINCT
BANNER,
A.LOCATION,
RCPT_PLAN,
CASE WHEN Z_SCORE >= 2.5 THEN 'A'
	 WHEN Z_SCORE >= 1 THEN 'B'
	 WHEN Z_SCORE >= 0 THEN 'C'
	 WHEN Z_SCORE >= -0.5 THEN 'D'
	 WHEN Z_SCORE >= -1 THEN 'E'
	 ELSE 'F' END AS STORE_GRADE
FROM
(SELECT
A.BANNER,
A.LOCATION,
RCPT_PLAN,
(A.SALES_PLAN - AVG_SALES_PLAN) / STD_DEV AS Z_SCORE
FROM SALES_LOCATION A
JOIN AVG_SALES B ON A.BANNER = B.BANNER
JOIN STD_DEV C ON A.BANNER = C.BANNER) a
) WITH data PRIMARY INDEX (BANNER,LOCATION) ON COMMIT PRESERVE rows ;

--Step 6 --On Order units calculation--                                --2024-01-30  Query to include On Order Units
CREATE MULTISET VOLATILE TABLE ON_ORDER AS( 
SELECT
MONTH_NUM
,CAST(CASE WHEN store_num IN ('210','212') THEN '209' ELSE store_num END as int) as STORE_NUM
,SUM(NON_RP_OO_ACTIVE_UNITS ) AS nrp_po_oo_u
,sum(RP_OO_ACTIVE_UNITS) AS rp_po_oo_u
,SUM(NON_RP_OO_ACTIVE_UNITS) + sum(RP_OO_ACTIVE_UNITS) as total_po_oo_u
FROM prd_nap_usr_vws.merch_apt_on_order_insight_fact_vw
WHERE month_num = (SELECT DISTINCT Month_IDNT FROM CURR_WK)
group by 1,2)
WITH data PRIMARY INDEX (MONTH_NUM,STORE_NUM) ON COMMIT PRESERVE rows;


-- RCPT Spread
insert into WEEKLY_OPS_STANDUP
SELECT 
'INVENTORY WHERE' as OPS_NAME,
BANNER,
NULL AS CHANNEL,
'MTD Rcpt Spread vs Target by Store Volume (U)' AS METRIC_NAME,
MTH_IDNT AS FISCAL_NUM,
'MONTH' AS FISCAL_DESC,
STORE_GRADE AS LABEL,
NULL AS ROLLING_FISCAL_IND,
RECEIPT_PLAN AS PLAN_OP,
NULL AS PLAN_CP,
(PO_RCPT_U + inventory_eoh_in_transit_total_units_ty + coalesce(total_po_oo_u,0)) AS TY,	-- included in_transit on OPS weekly update 2023 DEC WK2 and On_Order on 2024-01-30, requested by Emily
NULL AS LY,
NULL AS DAY_DATE
FROM 
(
SELECT 
A.MTH_IDNT,
A.BANNER,
B.STORE_GRADE,
SUM(CASE WHEN A.LOCATION = 209 THEN 0 ELSE A.RCPT_PLAN END) AS RECEIPT_PLAN,	-- The plan for all 3 NYC stores is duplicated into location 209 for allocation system purposes
SUM(PO_RCPT_U) AS PO_RCPT_U,
SUM(inventory_eoh_in_transit_total_units_ty) AS inventory_eoh_in_transit_total_units_ty,
SUM(total_po_oo_u) AS total_po_oo_u                                              --2024-01-30 - On Order Units metric added
FROM SALES_LOCATION A
JOIN STORE_GRADE B ON A.LOCATION = B.LOCATION
JOIN
(SELECT
STORE_NUM,
A.MONTH_NUM,
SUM(RECEIPTS_PO_UNITS_TY) AS PO_RCPT_U,
SUM(CASE WHEN A.WEEK_NUM = B.WEEK_NUM THEN inventory_eoh_in_transit_total_units_ty ELSE 0 END) AS inventory_eoh_in_transit_total_units_ty
FROM PRD_NAP_VWS.MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT_VW A
JOIN (SELECT MONTH_NUM, MAX(WEEK_NUM) AS WEEK_NUM FROM DAY_CAL WHERE MONTH_NUM = (SELECT MONTH_IDNT FROM CURR_WK) AND WEEK_NUM <= (SELECT WEEK_IDNT FROM CURR_WK) GROUP BY 1) B
ON A.MONTH_NUM = B.MONTH_NUM
WHERE A.MONTH_NUM = (SELECT MONTH_IDNT FROM CURR_WK) and A.WEEK_NUM <= (SELECT WEEK_IDNT FROM CURR_WK)
GROUP BY 1,2 ) C
ON A.MTH_IDNT = C.MONTH_NUM AND A.LOCATION = C.STORE_NUM
LEFT JOIN ON_ORDER D on A.MTH_IDNT = D.MONTH_NUM and A.LOCATION = D.STORE_NUM            --2024-01-30 - To add on order units metric
where A.RCPT_PLAN > 0  
GROUP BY 1,2,3) AS A;


-- RCPT Spread, store count by Store Grade
insert into WEEKLY_OPS_STANDUP
SELECT 
'INVENTORY WHERE' as OPS_NAME,
BANNER,
NULL AS CHANNEL,
'MTD Rcpt Spread (Store Count by Grade)' AS METRIC_NAME,
MONTH_IDNT AS FISCAL_NUM,
'MONTH' AS FISCAL_DESC,
STORE_GRADE AS LABEL,
NULL AS ROLLING_FISCAL_IND,
NULL AS PLAN_OP,
NULL AS PLAN_CP,
count(distinct location) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM STORE_GRADE, curr_wk
where RCPT_PLAN > 0  
group by 1,2,3,4,5,6,7,8,9,10,12,13 ;
**/
---------------------------------------------------------------------------------------------

-- TWIST RP In-Stock

INSERT into WEEKLY_OPS_STANDUP
select
'INVENTORY WHERE' as OPS_NAME,
CASE When channel in ('120, N.COM','110, FULL LINE STORES') then 'NORDSTROM'
	 when channel in ('250, OFFPRICE ONLINE','210, RACK STORES') then 'NORDSTROM RACK' END as BANNER,
CASE when channel in ('120, N.COM') then 'N.COM'
	 when channel in ('110, FULL LINE STORES') then 'FLS'
	 when channel in ('250, OFFPRICE ONLINE') then 'R.COM'
	 when channel in ('210, RACK STORES') then 'RACK STORE' END as CHANNEL,
'TWIST RP In-Stock' as METRIC_NAME,
week_num  AS FISCAL_NUM,
'WEEK' AS FISCAL_DESC,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE when channel in ('120, N.COM') then 96
	 when channel in ('110, FULL LINE STORES') then 85
	 when channel in ('250, OFFPRICE ONLINE') then 94
	 when channel in ('210, RACK STORES') then 82 END AS PLAN_OP,
NULL AS PLAN_CP,
(SUM(INSTOCK_TRAFFIC)*100/NULLIF(SUM(TRAFFIC), 0)) AS TY,
NULL AS LY,
NULL AS DAY_DATE
from t2dl_das_twist.twist_summary_weekly a
join CAL_LKUP b on a.wk_end_day_dt = b.week_end_day_date
where rp_desc='rp'
and WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -35) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK) --change it to -35
GROUP BY 1,2,3,4,5,6,7,8,9,10,12,13 ;

---------------------------------------------------------------------------------------

-- Final table insertion

DELETE FROM {environment_schema}.WEEKLY_OPS_STANDUP
WHERE OPS_NAME = 'INVENTORY WHERE' AND UPDATED_WEEK = (SELECT WEEK_IDNT FROM CURR_WK);


INSERT INTO {environment_schema}.WEEKLY_OPS_STANDUP
SELECT 
	OPS_NAME,
	BANNER,
	CHANNEL,
	METRIC_NAME,
	FISCAL_NUM,
	FISCAL_DESC,
	LABEL,
	ROLLING_FISCAL_IND,
	PLAN_OP,
	PLAN_CP,
	TY,
	LY,
	WEEK_IDNT AS UPDATED_WEEK, 
	CURRENT_TIMESTAMP as update_timestamp,
	DAY_DATE
FROM WEEKLY_OPS_STANDUP AS A, CURR_WK;

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
