SET QUERY_BAND = 'App_ID=APP08240;
DAG_ID=ddl_cco_customer_level_attributes_daily_11521_ACE_ENG;
Task_Name=run_teradata_ddl_cco_customer_level_attributes;'
FOR SESSION VOLATILE;

--drop table {cco_t2_schema}.cco_customer_level_attributes;

CREATE MULTISET TABLE {cco_t2_schema}.cco_customer_level_attributes ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      acp_id VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC,
      reporting_year_shopped VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_gender VARCHAR(7) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('Male','Unknown','Female'),
      cust_age INTEGER,
      cust_lifestage VARCHAR(16) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('01) Young Adult','Unknown','05) Retired','04) Late Career','02) Early Career','03) Mid Career'),
      cust_age_group VARCHAR(13) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('1) 18-24 yrs','Unknown','3) 35-44 yrs','5) 55-64 yrs','4) 45-54 yrs','0) <18 yrs','6) 65+ yrs','2) 25-34 yrs'),
      cust_NMS_market VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_dma VARCHAR(55) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_country VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_dma_rank VARCHAR(11) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_loyalty_type VARCHAR(14) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('c) Non-Loyalty','a) Cardmember','b) Member'),
      cust_loyalty_level VARCHAR(13) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('3) AMBASSADOR','4) ICON','2) INFLUENCER','1) MEMBER'),
      cust_loy_member_enroll_dt DATE FORMAT 'YY/MM/DD',
      cust_loy_cardmember_enroll_dt DATE FORMAT 'YY/MM/DD',
      cust_acquisition_date DATE FORMAT 'YY/MM/DD',
      cust_acquisition_fiscal_year SMALLINT,
      cust_acquisition_channel VARCHAR(19) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_acquisition_banner VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('NORDSTROM','RACK'),
      cust_acquisition_brand VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_tenure_bucket_months VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_tenure_bucket_years VARCHAR(13) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('4) 5-10 years','5) 10+ years','1) <= 1 year','2) 1-2 years','3) 2-5 years'),
      cust_activation_date DATE FORMAT 'YY/MM/DD',
      cust_activation_channel VARCHAR(19) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('1) Nordstrom Stores','3) Rack Stores','4) Rack.com','2) Nordstrom.com'),
      cust_activation_banner VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('NORDSTROM','RACK'),
      cust_engagement_cohort VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('Highly-Engaged','Moderately-Engaged','Lightly-Engaged','Acquire & Activate'),
      cust_channel_count INTEGER COMPRESS (3,2,4,1),
      cust_channel_combo VARCHAR(32) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_banner_count INTEGER COMPRESS (2,1),
      cust_banner_combo VARCHAR(17) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('2) Rack-only','3) Dual-Banner','1) Nordstrom-only'),
      cust_employee_flag INTEGER COMPRESS (1,0),
      cust_jwn_trip_bucket VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_jwn_net_spend_bucket VARCHAR(11) CHARACTER SET UNICODE NOT CASESPECIFIC,
      cust_jwn_gross_sales DECIMAL(38,2),
      cust_jwn_return_amt DECIMAL(38,2),
      cust_jwn_net_sales DECIMAL(38,2),
      cust_jwn_net_sales_apparel DECIMAL(38,2),
      cust_jwn_trips INTEGER,
      cust_jwn_gross_items INTEGER,
      cust_jwn_return_items INTEGER,
      cust_jwn_net_items INTEGER,
      cust_tender_nordstrom INTEGER COMPRESS (1,0),
      cust_tender_nordstrom_note INTEGER COMPRESS (1,0),
      cust_tender_3rd_party_credit INTEGER COMPRESS (1,0),
      cust_tender_debit_card INTEGER COMPRESS (1,0),
      cust_tender_gift_card INTEGER COMPRESS (1,0),
      cust_tender_cash INTEGER COMPRESS (1,0),
      cust_tender_paypal INTEGER COMPRESS (1,0),
      cust_tender_check INTEGER COMPRESS (1,0),
      cust_event_holiday INTEGER COMPRESS (1,0),
      cust_event_anniversary INTEGER COMPRESS (1,0),
      cust_svc_group_exp_delivery INTEGER COMPRESS (1,0),
      cust_svc_group_order_pickup INTEGER COMPRESS (1,0),
      cust_svc_group_selling_relation INTEGER COMPRESS (1,0),
      cust_svc_group_remote_selling INTEGER COMPRESS (1,0),
      cust_svc_group_alterations INTEGER COMPRESS (1,0),
      cust_svc_group_in_store INTEGER COMPRESS (1,0),
      cust_svc_group_restaurant INTEGER COMPRESS (1,0),
      cust_service_free_exp_delivery INTEGER COMPRESS (1,0),
      cust_service_next_day_pickup INTEGER COMPRESS (1,0),
      cust_service_same_day_bopus INTEGER COMPRESS (1,0),
      cust_service_curbside_pickup INTEGER COMPRESS (1,0),
      cust_service_style_boards INTEGER COMPRESS (1,0),
      cust_service_gift_wrapping INTEGER COMPRESS (1,0),
      cust_service_pop_in INTEGER COMPRESS (1,0),
      cust_marketplace_flag INTEGER COMPRESS (1,0),
      cust_platform_desktop INTEGER COMPRESS (1,0),
      cust_platform_MOW INTEGER COMPRESS (1,0),
      cust_platform_IOS INTEGER COMPRESS (1,0),
      cust_platform_Android INTEGER COMPRESS (1,0),
      cust_platform_POS INTEGER COMPRESS (1,0),
      cust_anchor_brand BYTEINT,
      cust_strategic_brand BYTEINT,
      cust_store_customer BYTEINT,
      cust_digital_customer BYTEINT,
      cust_clv_jwn DECIMAL(14,4),
      cust_clv_fp DECIMAL(14,4),
      cust_clv_op DECIMAL(14,4),
      dw_sys_load_tmstp TIMESTAMP(6),
      dw_sys_updt_tmstp TIMESTAMP(6))
PRIMARY INDEX (acp_id, reporting_year_shopped);


collect statistics
column  (acp_id),
column  (reporting_year_shopped),
column  (cust_gender),
column  (cust_age),
column  (cust_lifestage),
column  (cust_age_group),
column  (cust_NMS_market),
column  (cust_dma),
column  (cust_country),
column  (cust_dma_rank),
column  (cust_loyalty_type),
column  (cust_loyalty_level),
column  (cust_employee_flag),
column  (acp_id, reporting_year_shopped)
on
{cco_t2_schema}.cco_customer_level_attributes;


SET QUERY_BAND = NONE FOR SESSION;
