SET QUERY_BAND = 'App_ID=APP08240;
DAG_ID=ddl_cco_line_items_daily_11521_ACE_ENG;
Task_Name=run_teradata_ddl_cco_line_items;'
FOR SESSION VOLATILE;

drop table {cco_t2_schema}.cco_line_items;

CREATE MULTISET TABLE {cco_t2_schema}.cco_line_items ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      business_day_date DATE,
      global_tran_id BIGINT,
      line_item_seq_num SMALLINT,
      data_source VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('1) TRANSACTION','2) NSEAM'),
      order_num VARCHAR(32) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS,
      acp_id VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC  COMPRESS,
      banner VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('NORDSTROM','RACK'),
      channel VARCHAR(19) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('1) Nordstrom Stores','2) Nordstrom.com','3) Rack Stores','4) Rack.com'),
      channel_country VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('US','CA'),
      store_num INTEGER  COMPRESS,
      store_region VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('FULL LINE CANADA','MIDWEST FLS','MIDWEST RACKS','N.CA','N.COM','NORTHEAST FLS','NORTHEAST RACKS','NORTHWEST FLS','NORTHWEST RACKS','OFFPRICE ONLINE','RACK CANADA','SCAL RACKS','SOUTHEAST FLS','SOUTHEAST RACKS','SOUTHERN CALIFORNIA FLS','SOUTHWEST FLS','SOUTHWEST RACKS'),
      div_num INTEGER COMPRESS,
      div_desc VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('RESTAURANT', 'MERCH PROJECTS', 'HOME', 'APPAREL', 'OTHER/NON-MERCH', 'SHOES', 'LEASED BOUTIQUES', 'ACCESSORIES', 'BEAUTY', 'DESIGNER'),
      subdiv_num INTEGER  COMPRESS,
      subdiv_desc VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('ACCESSORIES','BAG FEES','BEAUTY SERVICES','CREATIVE PROJECTS','DEPOSITS/SERVICES','FRAGRANCE','HOME','KIDS APPAREL','KIDS DESIGNER','KIDS SHOES','LEASED BOUTIQUES','MAKEUP&SKINCARE','MENS APPAREL','MENS DESIGNER','MENS SHOES','MENS SPECIALIZED','MERCH PROJECTS','NEW CONCEPTS','NII NON INVENTORY ITEMS','RESTAURANT','WMNS DESIGNER','WOMENS APPAREL','WOMENS SHOES','WOMENS SPECIALIZED'),
      dept_num INTEGER COMPRESS,
      dept_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('WMNS BETTER LC','YOUNG WOMENS SHOES','SPECIALTY COFFEE BAR','LINGERIE','WOMENS BETTER SHOES','DRESSES','YOUNG WOMENS APPAREL','WMNS ACTIVEWEAR','MAKEUP','ADVANCED TECHNOLOGY/TOOLS','WMNS BETTER MC','JEWELRY','CAFE','MENS BETTER SPORTSWEAR','WMNS BETTER EC','HDBG/SLG/LUG','CONTEMPORARY 1','WOMENS ACTIVE SHOES','ACCESSORIES','SKINCARE','WMNS FRAGRANCE','MENS ACTIVEWEAR','MENS DRESSWEAR','YOUNG MENS APPAREL','BIG GIRL','BEAUTY GIFT','SLEEPWEAR','WMNS SWIM WEAR','NON ACTIVE KIDS SHOES','MENS SPECIALIZED','DESIGNER','WMNS DENIM','ACTIVE KIDS SHOES','MENS BETTER SHOES','EYEWEAR','HOSIERY','MENS ACTIVE SHOES','MENS DENIM','BIG BOY'),
      brand_name VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS,
      npg_flag VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('Y','N'),
      price_type VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('R','C','P'),
      store_country VARCHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('US','CA'),
      ntn_tran INTEGER COMPRESS,
      date_shopped DATE FORMAT 'YY/MM/DD' COMPRESS,
      fiscal_month_num INTEGER COMPRESS,
      fiscal_qtr_num INTEGER COMPRESS,
      fiscal_yr_num INTEGER COMPRESS,
      fiscal_year_shopped VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS,
      reporting_year_shopped VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS,
      item_price_band VARCHAR(11) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS,
      gross_sales DECIMAL(12,2) COMPRESS,
      gross_incl_gc DECIMAL(12,2) COMPRESS,
      return_amt DECIMAL(12,2)  COMPRESS 0.00 ,
      net_sales DECIMAL(13,2)  COMPRESS 0.00 ,
      gross_items INTEGER COMPRESS,
      return_items INTEGER COMPRESS,
      net_items INTEGER COMPRESS,
      return_date DATE FORMAT 'YY/MM/DD' COMPRESS,
      days_to_return INTEGER COMPRESS,
      return_store INTEGER COMPRESS,
      return_banner VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('NORDSTROM','RACK'),
      return_channel VARCHAR(19) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('1) Nordstrom Stores','2) Nordstrom.com','3) Rack Stores','4) Rack.com'),
      item_delivery_method VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('FC_BOPUS','FREE_2DAY_DELIVERY','FREE_2DAY_SHIP_TO_STORE','NEXT_DAY_SHIP_TO_STORE','PAID_EXPEDITED_SHIP_TO_HOME','PAID_EXPEDITED_SHIP_TO_STORE','SAME_DAY_BOPUS','SAME_DAY_DELIVERY','SHIP_TO_STORE','NEXT_DAY_BOPUS'),
      pickup_store INTEGER COMPRESS,
      pickup_date DATE FORMAT 'YY/MM/DD' COMPRESS,
      pickup_channel VARCHAR(19) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('1) Nordstrom Stores','2) Nordstrom.com','3) Rack Stores','4) Rack.com'),
      pickup_banner VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('NORDSTROM','RACK'),
      platform VARCHAR(40) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('WEB','IOS','MOW','POS','ANDROID','CSR_PHONE','THIRD_PARTY_VENDOR'),
      employee_flag INTEGER COMPRESS (0 ,1 ),
      tender_nordstrom INTEGER COMPRESS (0 ,1 ),
      tender_nordstrom_note INTEGER COMPRESS (0 ,1 ),
      tender_3rd_party_credit INTEGER COMPRESS (0 ,1 ),
      tender_debit_card INTEGER COMPRESS (0 ,1 ),
      tender_gift_card INTEGER COMPRESS (0 ,1 ),
      tender_cash INTEGER COMPRESS (0 ,1 ),
      tender_paypal INTEGER COMPRESS (0 ,1 ),
      tender_check INTEGER COMPRESS (0 ,1 ),
      event_holiday INTEGER COMPRESS (0 ,1 ),
      event_anniversary INTEGER COMPRESS (0 ,1 ),
      svc_group_exp_delivery INTEGER COMPRESS (0 ,1 ),
      svc_group_order_pickup INTEGER COMPRESS (0 ,1 ),
      svc_group_selling_relation INTEGER COMPRESS (0 ,1 ),
      svc_group_remote_selling INTEGER COMPRESS (0 ,1 ),
      svc_group_alterations INTEGER COMPRESS (0 ,1 ),
      svc_group_in_store INTEGER COMPRESS (0 ,1 ),
      svc_group_restaurant INTEGER COMPRESS (0 ,1 ),
      service_free_exp_delivery INTEGER COMPRESS (0 ,1 ),
      service_next_day_pickup INTEGER COMPRESS (0 ,1 ),
      service_same_day_bopus INTEGER COMPRESS (0 ,1 ),
      service_curbside_pickup INTEGER COMPRESS (0 ,1 ),
      service_style_boards INTEGER COMPRESS (0 ,1 ),
      service_gift_wrapping INTEGER COMPRESS (0 ,1 ),
      service_pop_in INTEGER COMPRESS (0 ,1 ),
      marketplace_flag INTEGER COMPRESS (0 ,1 ),
      dw_sys_load_tmstp TIMESTAMP(6),
      dw_sys_updt_tmstp TIMESTAMP(6))
PRIMARY INDEX ( global_tran_id ,line_item_seq_num )
PARTITION BY RANGE_N(business_day_date  BETWEEN DATE '2017-01-01' AND DATE '2031-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);

collect statistics
column (global_tran_id),
column (line_item_seq_num),
column (data_source),
column (order_num),
column (acp_id),
column (banner),
column (channel),
column (channel_country),
column (store_num),
column (employee_flag),
column (date_shopped),
column (fiscal_year_shopped),
column (reporting_year_shopped),
column (item_delivery_method),
column (return_store),
column (return_banner),
column (return_channel),
column (price_type),
column (acp_id,reporting_year_shopped),
column (acp_id ,banner,reporting_year_shopped),
column (acp_id ,channel,reporting_year_shopped),
column (global_tran_id ,line_item_seq_num) 
on
{cco_t2_schema}.cco_line_items;

SET QUERY_BAND = NONE FOR SESSION;
