/*
DDL for Assortment Hierarchy Table
Variable(s):    {{environment_schema}} T2DL_DAS_ASSORTMENT_DIM (prod) or {environment_schema}
                {{env_suffix}} '' or '{env_suffix}' tablesuffix for prod testing
Author: Sara Riker & Christine Buckler

Updated 2/9/22: Added in vendor label information

Creates Tables:
    {environment_schema}.assortment_hierarchy{env_suffix}
*/

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'assortment_hierarchy{env_suffix}', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.assortment_hierarchy{env_suffix}, FALLBACK,
	NO BEFORE JOURNAL,
	NO AFTER JOURNAL,
	CHECKSUM = DEFAULT,
	DEFAULT MERGEBLOCKRATIO,
	MAP = TD_MAP1
(
     customer_choice VARCHAR(64) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,epm_choice_num BIGINT
    ,cc_style_color VARCHAR(64) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,sku_idnt VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,channel_country VARCHAR(4) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('US', 'CA')
    ,supplier_idnt VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,div_idnt INTEGER 
    ,div_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,grp_idnt INTEGER 
    ,grp_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,dept_idnt INTEGER 
    ,dept_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,class_idnt INTEGER 
    ,class_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,sbclass_idnt INTEGER
    ,sbclass_desc VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,quantrix_category VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,ccs_category VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,ccs_subcategory VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,style_group_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,web_style_num BIGINT
    ,epm_style_num VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,rms_style_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,style_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,brand_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,fanatics_ind BYTEINT
    ,marketplace_ind BYTEINT
    ,npg_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('Y', 'N')
    ,vendor_name VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,vendor_label_code INTEGER
    ,vendor_label_name VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,vendor_label_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,vendor_brand_name VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,fp_supplier_group VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,op_supplier_group VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,supp_part_num VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,supp_color VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,nrf_size_code VARCHAR(6) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,supp_size VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,size_1_num VARCHAR(6) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,size_1_desc VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,size_2_num VARCHAR(6) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,size_2_desc VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,color_num VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC 
    ,color_desc VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,nord_display_color VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,nord_role VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,nord_role_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,rack_role VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,rack_role_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,parent_group VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,merch_themes VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,assortment_grouping VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,smart_sample_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('Y', 'N')
    ,gwp_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('Y', 'N')
    ,fulfillment_type_code VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,nord_store_sellable_ind BYTEINT
    ,nord_web_sellable_ind BYTEINT
    ,rack_store_sellable_ind BYTEINT
    ,rack_web_sellable_ind BYTEINT
    ,sku_type_code VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,sku_type_desc VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,return_disposition_code VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,return_disposition_desc VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,drop_ship_eligible_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,fp_replenishment_eligible_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,op_replenishment_eligible_ind VARCHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
    ,dw_sys_load_tmstp TIMESTAMP(6)
    ,update_timestamp TIMESTAMP(6) WITH TIME ZONE
)
PRIMARY INDEX(div_idnt, grp_idnt, dept_idnt, customer_choice);

GRANT SELECT ON {environment_schema}.assortment_hierarchy{env_suffix} TO PUBLIC;