DELETE FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_financial_country_banner_plan_qtr_plan_fct AS tgt
WHERE week_num >= (SELECT first_week_idnt
  FROM (SELECT quarter_idnt,
     MIN(day_date) AS first_quarter_sat,
     MIN(week_idnt) AS first_week_idnt
    FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_dim.day_cal_454_dim AS c
    WHERE day_num_of_fiscal_week = 7
    GROUP BY quarter_idnt
    HAVING first_quarter_sat = CURRENT_DATE('PST8PDT')) AS t1);


INSERT INTO `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_financial_country_banner_plan_qtr_plan_fct
(
quarter_idnt,
dept_num,
week_num,
banner_country_num,
fulfill_type_num,
qp_beginning_of_period_active_cost_amt,
qp_beginning_of_period_active_inventory_target_qty,
qp_beginning_of_period_active_qty,
qp_beginning_of_period_inactive_cost_amt,
qp_beginning_of_period_inactive_qty,
qp_ending_of_period_active_cost_amt,
qp_ending_of_period_active_qty,
qp_ending_of_period_inactive_cost_amt,
qp_ending_of_period_inactive_qty,
qp_transfer_in_active_cost_amt,
qp_transfer_in_active_qty,
qp_transfer_out_active_cost_amt,
qp_transfer_out_active_qty,
qp_transfer_in_inactive_cost_amt,
qp_transfer_in_inactive_qty,
qp_transfer_out_inactive_cost_amt,
qp_transfer_out_inactive_qty,
qp_transfer_in_other_cost_amt,
qp_transfer_in_other_qty,
qp_transfer_out_other_cost_amt,
qp_transfer_out_other_qty,
qp_transfer_in_racking_cost_amt,
qp_transfer_in_racking_qty,
qp_transfer_out_racking_cost_amt,
qp_transfer_out_racking_qty,
qp_mark_out_of_stock_active_cost_amt,
qp_mark_out_of_stock_active_qty,
qp_mark_out_of_stock_inactive_cost_amt,
qp_mark_out_of_stock_inactive_qty,
qp_receipts_active_cost_amt,
qp_receipts_active_qty,
qp_receipts_inactive_cost_amt,
qp_receipts_inactive_qty,
qp_receipts_reserve_cost_amt,
qp_receipts_reserve_qty,
qp_reclass_in_cost_amt,
qp_reclass_in_qty,
qp_reclass_out_cost_amt,
qp_reclass_out_qty,
qp_return_to_vendor_active_cost_amt,
qp_return_to_vendor_active_qty,
qp_return_to_vendor_inactive_cost_amt,
qp_return_to_vendor_inactive_qty,
qp_vendor_funds_cost_amt,
qp_discount_terms_cost_amt,
qp_merch_margin_retail_amt,
qp_inventory_movement_in_dropship_cost_amt,
qp_inventory_movement_in_dropship_qty,
qp_inventory_movement_out_dropship_cost_amt,
qp_inventory_movement_out_dropship_qty,
qp_other_inventory_adjustment_cost_amt,
qp_other_inventory_adjustment_qty,
qp_open_to_buy_receipts_active_cost_amt,
qp_open_to_buy_receipts_inactive_cost_amt,
dw_sys_load_tmstp
)
WITH cal AS (SELECT quarter_idnt,
 MIN(day_date) AS first_quarter_sat,
 MIN(week_idnt) AS first_week_idnt
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_dim.day_cal_454_dim AS c
WHERE day_num_of_fiscal_week = 7
GROUP BY quarter_idnt
HAVING first_quarter_sat = CURRENT_DATE('PST8PDT'))
SELECT c.quarter_idnt,
 mfcbpf.department_number AS dept_num,
 mfcbpf.week_id AS week_num,
 obcd.banner_country_num,
 aimd.fulfill_type_num,
 mfcbpf.active_beginning_inventory_dollar_amount AS qp_beginning_of_period_active_cost_amt,
 mfcbpf.active_beginning_period_inventory_target_units AS qp_beginning_of_period_active_inventory_target_qty,
 mfcbpf.active_beginning_inventory_units AS qp_beginning_of_period_active_qty,
 mfcbpf.inactive_beginning_period_inventory_dollar_amount AS qp_beginning_of_period_inactive_cost_amt,
 mfcbpf.inactive_beginning_period_inventory_units AS qp_beginning_of_period_inactive_qty,
 mfcbpf.active_ending_inventory_dollar_amount AS qp_ending_of_period_active_cost_amt,
 mfcbpf.active_ending_inventory_units AS qp_ending_of_period_active_qty,
 mfcbpf.inactive_ending_inventory_dollar_amount AS qp_ending_of_period_inactive_cost_amt,
 mfcbpf.inactive_ending_inventory_units AS qp_ending_of_period_inactive_qty,
 mfcbpf.active_inventory_in_dollar_amount AS qp_transfer_in_active_cost_amt,
 mfcbpf.active_inventory_in_units AS qp_transfer_in_active_qty,
 mfcbpf.active_inventory_out_dollar_amount AS qp_transfer_out_active_cost_amt,
 mfcbpf.active_inventory_out_units AS qp_transfer_out_active_qty,
 mfcbpf.inactive_inventory_in_dollar_amount AS qp_transfer_in_inactive_cost_amt,
 mfcbpf.inactive_inventory_in_units AS qp_transfer_in_inactive_qty,
 mfcbpf.inactive_inventory_out_dollar_amount AS qp_transfer_out_inactive_cost_amt,
 mfcbpf.inactive_inventory_out_units AS qp_transfer_out_inactive_qty,
 mfcbpf.other_inventory_in_dollar_amount AS qp_transfer_in_other_cost_amt,
 mfcbpf.other_inventory_in_units AS qp_transfer_in_other_qty,
 mfcbpf.other_inventory_out_dollar_amount AS qp_transfer_out_other_cost_amt,
 mfcbpf.other_inventory_out_units AS qp_transfer_out_other_qty,
 mfcbpf.racking_in_dollar_amount AS qp_transfer_in_racking_cost_amt,
 mfcbpf.racking_in_units AS qp_transfer_in_racking_qty,
 mfcbpf.racking_out_dollar_amount AS qp_transfer_out_racking_cost_amt,
 mfcbpf.racking_out_units AS qp_transfer_out_racking_qty,
 mfcbpf.active_mos_dollar_amount AS qp_mark_out_of_stock_active_cost_amt,
 mfcbpf.active_mos_units AS qp_mark_out_of_stock_active_qty,
 mfcbpf.inactive_mos_dollar_amount AS qp_mark_out_of_stock_inactive_cost_amt,
 mfcbpf.inactive_mos_units AS qp_mark_out_of_stock_inactive_qty,
 mfcbpf.active_receipts_dollar_amount AS qp_receipts_active_cost_amt,
 mfcbpf.active_receipts_units AS qp_receipts_active_qty,
 mfcbpf.inactive_receipts_dollar_amount AS qp_receipts_inactive_cost_amt,
 mfcbpf.inactive_receipts_units AS qp_receipts_inactive_qty,
 mfcbpf.reserve_receipts_dollar_amount AS qp_receipts_reserve_cost_amt,
 mfcbpf.reserve_receipts_units AS qp_receipts_reserve_qty,
 mfcbpf.reclass_in_dollar_amount AS qp_reclass_in_cost_amt,
 mfcbpf.reclass_in_units AS qp_reclass_in_qty,
 mfcbpf.reclass_out_dollar_amount AS qp_reclass_out_cost_amt,
 mfcbpf.reclass_out_units AS qp_reclass_out_qty,
 mfcbpf.active_rtv_dollar_amount AS qp_return_to_vendor_active_cost_amt,
 mfcbpf.active_rtv_units AS qp_return_to_vendor_active_qty,
 mfcbpf.inactive_rtv_dollar_amount AS qp_return_to_vendor_inactive_cost_amt,
 mfcbpf.inactive_rtv_units AS qp_return_to_vendor_inactive_qty,
 mfcbpf.vendor_funds_cost_amount AS qp_vendor_funds_cost_amt,
 mfcbpf.discount_terms_cost_amount AS qp_discount_terms_cost_amt,
 mfcbpf.merch_margin_retail_amount AS qp_merch_margin_retail_amt,
 mfcbpf.inventory_movement_drop_ship_in_dollar_amount AS qp_inventory_movement_in_dropship_cost_amt,
 mfcbpf.inventory_movement_drop_ship_in_units AS qp_inventory_movement_in_dropship_qty,
 mfcbpf.inventory_movement_drop_ship_out_dollar_amount AS qp_inventory_movement_out_dropship_cost_amt,
 mfcbpf.inventory_movement_drop_ship_out_units AS qp_inventory_movement_out_dropship_qty,
 mfcbpf.other_inventory_adjustments_dollar_amount AS qp_other_inventory_adjustment_cost_amt,
 mfcbpf.other_inventory_adjustments_units AS qp_other_inventory_adjustment_qty,
 mfcbpf.active_opentobuy_cost_amount AS qp_open_to_buy_receipts_active_cost_amt,
 mfcbpf.inactive_opentobuy_cost_amount AS qp_open_to_buy_receipts_inactive_cost_amt,
 CAST(FORMAT_TIMESTAMP('%F %H:%M:%E6S', CURRENT_DATETIME('PST8PDT')) AS DATETIME)
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.merch_financial_country_banner_plan_fct AS mfcbpf
 INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.alternate_inventory_model_dim AS aimd ON LOWER(mfcbpf.alternate_inventory_model) = LOWER(aimd
   .fulfill_type_desc)
 INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_dim.day_cal_454_dim AS c ON mfcbpf.week_id = c.week_idnt
 LEFT JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_vws.org_banner_country_dim AS obcd ON LOWER(mfcbpf.channel_country) = LOWER(obcd.country_code) AND
   LOWER(mfcbpf.pricing_channel) = LOWER(obcd.banner_desc)
 INNER JOIN cal ON mfcbpf.week_id >= cal.first_week_idnt
WHERE c.day_num_of_fiscal_week = 1
 AND LOWER(mfcbpf.financial_plan_version) = LOWER('SNAP_PLAN');