


DECLARE ERROR_CODE INT64;
DECLARE ERROR_MESSAGE STRING;


DELETE FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_transaction_sku_store_day_agg_fact
WHERE day_num IN (SELECT dcal.day_idnt
        FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.day_cal_454_dim AS cal
            INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.etl_batch_dt_lkup AS etl ON cal.day_date = etl.dw_batch_dt
            INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.day_cal_454_dim AS dcal ON cal.week_idnt = dcal.week_idnt
        WHERE LOWER(etl.interface_code) = LOWER('MRIc_DAY_AGG_DLY'));



INSERT INTO `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_transaction_sku_store_day_agg_fact (rms_sku_num, store_num, day_num, rp_ind,
 jwn_demand_total_units_ty, jwn_demand_total_retail_amt_ty, jwn_demand_regular_units_ty,
 jwn_demand_regular_retail_amt_ty, jwn_demand_promo_units_ty, jwn_demand_promo_retail_amt_ty,
 jwn_demand_clearance_units_ty, jwn_demand_clearance_retail_amt_ty, jwn_demand_persistent_units_ty,
 jwn_demand_persistent_retail_amt_ty, jwn_demand_persistent_regular_units_ty,
 jwn_demand_persistent_regular_retail_amt_ty, jwn_demand_persistent_promo_units_ty,
 jwn_demand_persistent_promo_retail_amt_ty, jwn_demand_persistent_clearance_units_ty,
 jwn_demand_persistent_clearance_retail_amt_ty, jwn_demand_flash_units_ty, jwn_demand_flash_retail_amt_ty,
 jwn_demand_flash_regular_units_ty, jwn_demand_flash_regular_retail_amt_ty, jwn_demand_flash_promo_units_ty,
 jwn_demand_flash_promo_retail_amt_ty, jwn_demand_flash_clearance_units_ty, jwn_demand_flash_clearance_retail_amt_ty,
 jwn_operational_gmv_total_units_ty, jwn_operational_gmv_total_retail_amt_ty, jwn_operational_gmv_total_cost_amt_ty,
 jwn_operational_gmv_regular_units_ty, jwn_operational_gmv_regular_retail_amt_ty,
 jwn_operational_gmv_regular_cost_amt_ty, jwn_operational_gmv_promo_units_ty, jwn_operational_gmv_promo_retail_amt_ty,
 jwn_operational_gmv_promo_cost_amt_ty, jwn_operational_gmv_clearance_units_ty,
 jwn_operational_gmv_clearance_retail_amt_ty, jwn_operational_gmv_clearance_cost_amt_ty, jwn_returns_total_units_ty,
 jwn_returns_total_retail_amt_ty, jwn_returns_total_cost_amt_ty, jwn_returns_regular_units_ty,
 jwn_returns_regular_retail_amt_ty, jwn_returns_regular_cost_amt_ty, jwn_returns_promo_units_ty,
 jwn_returns_promo_retail_amt_ty, jwn_returns_promo_cost_amt_ty, jwn_returns_clearance_units_ty,
 jwn_returns_clearance_retail_amt_ty, jwn_returns_clearance_cost_amt_ty, inventory_eoh_total_units_ty,
 inventory_eoh_total_retail_amt_ty, inventory_eoh_total_cost_amt_ty, inventory_eoh_regular_units_ty,
 inventory_eoh_regular_retail_amt_ty, inventory_eoh_regular_cost_amt_ty, inventory_eoh_clearance_units_ty,
 inventory_eoh_clearance_retail_amt_ty, inventory_eoh_clearance_cost_amt_ty, jwn_demand_total_units_ly,
 jwn_demand_total_retail_amt_ly, jwn_demand_regular_units_ly, jwn_demand_regular_retail_amt_ly,
 jwn_demand_promo_units_ly, jwn_demand_promo_retail_amt_ly, jwn_demand_clearance_units_ly,
 jwn_demand_clearance_retail_amt_ly, jwn_demand_persistent_units_ly, jwn_demand_persistent_retail_amt_ly,
 jwn_demand_persistent_regular_units_ly, jwn_demand_persistent_regular_retail_amt_ly,
 jwn_demand_persistent_promo_units_ly, jwn_demand_persistent_promo_retail_amt_ly,
 jwn_demand_persistent_clearance_units_ly, jwn_demand_persistent_clearance_retail_amt_ly, jwn_demand_flash_units_ly,
 jwn_demand_flash_retail_amt_ly, jwn_demand_flash_regular_units_ly, jwn_demand_flash_regular_retail_amt_ly,
 jwn_demand_flash_promo_units_ly, jwn_demand_flash_promo_retail_amt_ly, jwn_demand_flash_clearance_units_ly,
 jwn_demand_flash_clearance_retail_amt_ly, jwn_operational_gmv_total_units_ly, jwn_operational_gmv_total_retail_amt_ly,
 jwn_operational_gmv_total_cost_amt_ly, jwn_operational_gmv_regular_units_ly, jwn_operational_gmv_regular_retail_amt_ly
 , jwn_operational_gmv_regular_cost_amt_ly, jwn_operational_gmv_promo_units_ly, jwn_operational_gmv_promo_retail_amt_ly
 , jwn_operational_gmv_promo_cost_amt_ly, jwn_operational_gmv_clearance_units_ly,
 jwn_operational_gmv_clearance_retail_amt_ly, jwn_operational_gmv_clearance_cost_amt_ly, jwn_returns_total_units_ly,
 jwn_returns_total_retail_amt_ly, jwn_returns_total_cost_amt_ly, jwn_returns_regular_units_ly,
 jwn_returns_regular_retail_amt_ly, jwn_returns_regular_cost_amt_ly, jwn_returns_promo_units_ly,
 jwn_returns_promo_retail_amt_ly, jwn_returns_promo_cost_amt_ly, jwn_returns_clearance_units_ly,
 jwn_returns_clearance_retail_amt_ly, jwn_returns_clearance_cost_amt_ly, inventory_eoh_total_units_ly,
 inventory_eoh_total_retail_amt_ly, inventory_eoh_total_cost_amt_ly, inventory_eoh_regular_units_ly,
 inventory_eoh_regular_retail_amt_ly, inventory_eoh_regular_cost_amt_ly, inventory_eoh_clearance_units_ly,
 inventory_eoh_clearance_retail_amt_ly, inventory_eoh_clearance_cost_amt_ly, dw_sys_load_tmstp, dw_sys_load_dt)
(SELECT rms_sku_num,
  store_num,
  day_num,
  rp_ind,
  COALESCE(SUM(jwn_demand_total_units_ty), 0) AS jwn_demand_total_units_ty,
  COALESCE(SUM(jwn_demand_total_retail_amt_ty), 0) AS jwn_demand_total_retail_amt_ty,
  COALESCE(SUM(jwn_demand_regular_units_ty), 0) AS jwn_demand_regular_units_ty,
  COALESCE(SUM(jwn_demand_regular_retail_amt_ty), 0) AS jwn_demand_regular_retail_amt_ty,
  COALESCE(SUM(jwn_demand_promo_units_ty), 0) AS jwn_demand_promo_units_ty,
  COALESCE(SUM(jwn_demand_promo_retail_amt_ty), 0) AS jwn_demand_promo_retail_amt_ty,
  COALESCE(SUM(jwn_demand_clearance_units_ty), 0) AS jwn_demand_clearance_units_ty,
  COALESCE(SUM(jwn_demand_clearance_retail_amt_ty), 0) AS jwn_demand_clearance_retail_amt_ty,
  COALESCE(SUM(jwn_demand_persistent_units_ty), 0) AS jwn_demand_persistent_units_ty,
  COALESCE(SUM(jwn_demand_persistent_retail_amt_ty), 0) AS jwn_demand_persistent_retail_amt_ty,
  COALESCE(SUM(jwn_demand_persistent_regular_units_ty), 0) AS jwn_demand_persistent_regular_units_ty,
  COALESCE(SUM(jwn_demand_persistent_regular_retail_amt_ty), 0) AS jwn_demand_persistent_regular_retail_amt_ty,
  COALESCE(SUM(jwn_demand_persistent_promo_units_ty), 0) AS jwn_demand_persistent_promo_units_ty,
  COALESCE(SUM(jwn_demand_persistent_promo_retail_amt_ty), 0) AS jwn_demand_persistent_promo_retail_amt_ty,
  COALESCE(SUM(jwn_demand_persistent_clearance_units_ty), 0) AS jwn_demand_persistent_clearance_units_ty,
  COALESCE(SUM(jwn_demand_persistent_clearance_retail_amt_ty), 0) AS jwn_demand_persistent_clearance_retail_amt_ty,
  COALESCE(SUM(jwn_demand_flash_units_ty), 0) AS jwn_demand_flash_units_ty,
  COALESCE(SUM(jwn_demand_flash_retail_amt_ty), 0) AS jwn_demand_flash_retail_amt_ty,
  COALESCE(SUM(jwn_demand_flash_regular_units_ty), 0) AS jwn_demand_flash_regular_units_ty,
  COALESCE(SUM(jwn_demand_flash_regular_retail_amt_ty), 0) AS jwn_demand_flash_regular_retail_amt_ty,
  COALESCE(SUM(jwn_demand_flash_promo_units_ty), 0) AS jwn_demand_flash_promo_units_ty,
  COALESCE(SUM(jwn_demand_flash_promo_retail_amt_ty), 0) AS jwn_demand_flash_promo_retail_amt_ty,
  COALESCE(SUM(jwn_demand_flash_clearance_units_ty), 0) AS jwn_demand_flash_clearance_units_ty,
  COALESCE(SUM(jwn_demand_flash_clearance_retail_amt_ty), 0) AS jwn_demand_flash_clearance_retail_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_total_units_ty), 0) AS jwn_operational_gmv_total_units_ty,
  COALESCE(SUM(jwn_operational_gmv_total_retail_amt_ty), 0) AS jwn_operational_gmv_total_retail_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_total_cost_amt_ty), 0) AS jwn_operational_gmv_total_cost_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_regular_units_ty), 0) AS jwn_operational_gmv_regular_units_ty,
  COALESCE(SUM(jwn_operational_gmv_regular_retail_amt_ty), 0) AS jwn_operational_gmv_regular_retail_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_regular_cost_amt_ty), 0) AS jwn_operational_gmv_regular_cost_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_promo_units_ty), 0) AS jwn_operational_gmv_promo_units_ty,
  COALESCE(SUM(jwn_operational_gmv_promo_retail_amt_ty), 0) AS jwn_operational_gmv_promo_retail_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_promo_cost_amt_ty), 0) AS jwn_operational_gmv_promo_cost_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_clearance_units_ty), 0) AS jwn_operational_gmv_clearance_units_ty,
  COALESCE(SUM(jwn_operational_gmv_clearance_retail_amt_ty), 0) AS jwn_operational_gmv_clearance_retail_amt_ty,
  COALESCE(SUM(jwn_operational_gmv_clearance_cost_amt_ty), 0) AS jwn_operational_gmv_clearance_cost_amt_ty,
  COALESCE(SUM(jwn_returns_total_units_ty), 0) AS jwn_returns_total_units_ty,
  COALESCE(SUM(jwn_returns_total_retail_amt_ty), 0) AS jwn_returns_total_retail_amt_ty,
  COALESCE(SUM(jwn_returns_total_cost_amt_ty), 0) AS jwn_returns_total_cost_amt_ty,
  COALESCE(SUM(jwn_returns_regular_units_ty), 0) AS jwn_returns_regular_units_ty,
  COALESCE(SUM(jwn_returns_regular_retail_amt_ty), 0) AS jwn_returns_regular_retail_amt_ty,
  COALESCE(SUM(jwn_returns_regular_cost_amt_ty), 0) AS jwn_returns_regular_cost_amt_ty,
  COALESCE(SUM(jwn_returns_promo_units_ty), 0) AS jwn_returns_promo_units_ty,
  COALESCE(SUM(jwn_returns_promo_retail_amt_ty), 0) AS jwn_returns_promo_retail_amt_ty,
  COALESCE(SUM(jwn_returns_promo_cost_amt_ty), 0) AS jwn_returns_promo_cost_amt_ty,
  COALESCE(SUM(jwn_returns_clearance_units_ty), 0) AS jwn_returns_clearance_units_ty,
  COALESCE(SUM(jwn_returns_clearance_retail_amt_ty), 0) AS jwn_returns_clearance_retail_amt_ty,
  COALESCE(SUM(jwn_returns_clearance_cost_amt_ty), 0) AS jwn_returns_clearance_cost_amt_ty,
  COALESCE(SUM(inventory_eoh_total_units_ty), 0) AS inventory_eoh_total_units_ty,
  COALESCE(SUM(inventory_eoh_total_retail_amt_ty), 0) AS inventory_eoh_total_retail_amt_ty,
  COALESCE(SUM(inventory_eoh_total_cost_amt_ty), 0) AS inventory_eoh_total_cost_amt_ty,
  COALESCE(SUM(inventory_eoh_regular_units_ty), 0) AS inventory_eoh_regular_units_ty,
  COALESCE(SUM(inventory_eoh_regular_retail_amt_ty), 0) AS inventory_eoh_regular_retail_amt_ty,
  COALESCE(SUM(inventory_eoh_regular_cost_amt_ty), 0) AS inventory_eoh_regular_cost_amt_ty,
  COALESCE(SUM(inventory_eoh_clearance_units_ty), 0) AS inventory_eoh_clearance_units_ty,
  COALESCE(SUM(inventory_eoh_clearance_retail_amt_ty), 0) AS inventory_eoh_clearance_retail_amt_ty,
  COALESCE(SUM(inventory_eoh_clearance_cost_amt_ty), 0) AS inventory_eoh_clearance_cost_amt_ty,
  COALESCE(SUM(jwn_demand_total_units_ly), 0) AS jwn_demand_total_units_ly,
  COALESCE(SUM(jwn_demand_total_retail_amt_ly), 0) AS jwn_demand_total_retail_amt_ly,
  COALESCE(SUM(jwn_demand_regular_units_ly), 0) AS jwn_demand_regular_units_ly,
  COALESCE(SUM(jwn_demand_regular_retail_amt_ly), 0) AS jwn_demand_regular_retail_amt_ly,
  COALESCE(SUM(jwn_demand_promo_units_ly), 0) AS jwn_demand_promo_units_ly,
  COALESCE(SUM(jwn_demand_promo_retail_amt_ly), 0) AS jwn_demand_promo_retail_amt_ly,
  COALESCE(SUM(jwn_demand_clearance_units_ly), 0) AS jwn_demand_clearance_units_ly,
  COALESCE(SUM(jwn_demand_clearance_retail_amt_ly), 0) AS jwn_demand_clearance_retail_amt_ly,
  COALESCE(SUM(jwn_demand_persistent_units_ly), 0) AS jwn_demand_persistent_units_ly,
  COALESCE(SUM(jwn_demand_persistent_retail_amt_ly), 0) AS jwn_demand_persistent_retail_amt_ly,
  COALESCE(SUM(jwn_demand_persistent_regular_units_ly), 0) AS jwn_demand_persistent_regular_units_ly,
  COALESCE(SUM(jwn_demand_persistent_regular_retail_amt_ly), 0) AS jwn_demand_persistent_regular_retail_amt_ly,
  COALESCE(SUM(jwn_demand_persistent_promo_units_ly), 0) AS jwn_demand_persistent_promo_units_ly,
  COALESCE(SUM(jwn_demand_persistent_promo_retail_amt_ly), 0) AS jwn_demand_persistent_promo_retail_amt_ly,
  COALESCE(SUM(jwn_demand_persistent_clearance_units_ly), 0) AS jwn_demand_persistent_clearance_units_ly,
  COALESCE(SUM(jwn_demand_persistent_clearance_retail_amt_ly), 0) AS jwn_demand_persistent_clearance_retail_amt_ly,
  COALESCE(SUM(jwn_demand_flash_units_ly), 0) AS jwn_demand_flash_units_ly,
  COALESCE(SUM(jwn_demand_flash_retail_amt_ly), 0) AS jwn_demand_flash_retail_amt_ly,
  COALESCE(SUM(jwn_demand_flash_regular_units_ly), 0) AS jwn_demand_flash_regular_units_ly,
  COALESCE(SUM(jwn_demand_flash_regular_retail_amt_ly), 0) AS jwn_demand_flash_regular_retail_amt_ly,
  COALESCE(SUM(jwn_demand_flash_promo_units_ly), 0) AS jwn_demand_flash_promo_units_ly,
  COALESCE(SUM(jwn_demand_flash_promo_retail_amt_ly), 0) AS jwn_demand_flash_promo_retail_amt_ly,
  COALESCE(SUM(jwn_demand_flash_clearance_units_ly), 0) AS jwn_demand_flash_clearance_units_ly,
  COALESCE(SUM(jwn_demand_flash_clearance_retail_amt_ly), 0) AS jwn_demand_flash_clearance_retail_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_total_units_ly), 0) AS jwn_operational_gmv_total_units_ly,
  COALESCE(SUM(jwn_operational_gmv_total_retail_amt_ly), 0) AS jwn_operational_gmv_total_retail_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_total_cost_amt_ly), 0) AS jwn_operational_gmv_total_cost_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_regular_units_ly), 0) AS jwn_operational_gmv_regular_units_ly,
  COALESCE(SUM(jwn_operational_gmv_regular_retail_amt_ly), 0) AS jwn_operational_gmv_regular_retail_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_regular_cost_amt_ly), 0) AS jwn_operational_gmv_regular_cost_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_promo_units_ly), 0) AS jwn_operational_gmv_promo_units_ly,
  COALESCE(SUM(jwn_operational_gmv_promo_retail_amt_ly), 0) AS jwn_operational_gmv_promo_retail_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_promo_cost_amt_ly), 0) AS jwn_operational_gmv_promo_cost_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_clearance_units_ly), 0) AS jwn_operational_gmv_clearance_units_ly,
  COALESCE(SUM(jwn_operational_gmv_clearance_retail_amt_ly), 0) AS jwn_operational_gmv_clearance_retail_amt_ly,
  COALESCE(SUM(jwn_operational_gmv_clearance_cost_amt_ly), 0) AS jwn_operational_gmv_clearance_cost_amt_ly,
  COALESCE(SUM(jwn_returns_total_units_ly), 0) AS jwn_returns_total_units_ly,
  COALESCE(SUM(jwn_returns_total_retail_amt_ly), 0) AS jwn_returns_total_retail_amt_ly,
  COALESCE(SUM(jwn_returns_total_cost_amt_ly), 0) AS jwn_returns_total_cost_amt_ly,
  COALESCE(SUM(jwn_returns_regular_units_ly), 0) AS jwn_returns_regular_units_ly,
  COALESCE(SUM(jwn_returns_regular_retail_amt_ly), 0) AS jwn_returns_regular_retail_amt_ly,
  COALESCE(SUM(jwn_returns_regular_cost_amt_ly), 0) AS jwn_returns_regular_cost_amt_ly,
  COALESCE(SUM(jwn_returns_promo_units_ly), 0) AS jwn_returns_promo_units_ly,
  COALESCE(SUM(jwn_returns_promo_retail_amt_ly), 0) AS jwn_returns_promo_retail_amt_ly,
  COALESCE(SUM(jwn_returns_promo_cost_amt_ly), 0) AS jwn_returns_promo_cost_amt_ly,
  COALESCE(SUM(jwn_returns_clearance_units_ly), 0) AS jwn_returns_clearance_units_ly,
  COALESCE(SUM(jwn_returns_clearance_retail_amt_ly), 0) AS jwn_returns_clearance_retail_amt_ly,
  COALESCE(SUM(jwn_returns_clearance_cost_amt_ly), 0) AS jwn_returns_clearance_cost_amt_ly,
  COALESCE(SUM(inventory_eoh_total_units_ly), 0) AS inventory_eoh_total_units_ly,
  COALESCE(SUM(inventory_eoh_total_retail_amt_ly), 0) AS inventory_eoh_total_retail_amt_ly,
  COALESCE(SUM(inventory_eoh_total_cost_amt_ly), 0) AS inventory_eoh_total_cost_amt_ly,
  COALESCE(SUM(inventory_eoh_regular_units_ly), 0) AS inventory_eoh_regular_units_ly,
  COALESCE(SUM(inventory_eoh_regular_retail_amt_ly), 0) AS inventory_eoh_regular_retail_amt_ly,
  COALESCE(SUM(inventory_eoh_regular_cost_amt_ly), 0) AS inventory_eoh_regular_cost_amt_ly,
  COALESCE(SUM(inventory_eoh_clearance_units_ly), 0) AS inventory_eoh_clearance_units_ly,
  COALESCE(SUM(inventory_eoh_clearance_retail_amt_ly), 0) AS inventory_eoh_clearance_retail_amt_ly,
  COALESCE(SUM(inventory_eoh_clearance_cost_amt_ly), 0) AS inventory_eoh_clearance_cost_amt_ly,
  CAST(FORMAT_TIMESTAMP('%F %H:%M:%S', CURRENT_DATETIME('PST8PDT')) AS DATETIME) AS dw_sys_load_tmstp,
  CURRENT_DATE('PST8PDT') AS dw_sys_load_dt
 FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_stg.merch_transaction_sku_store_day_agg_wrk AS wrk
 WHERE day_num IN (SELECT dcal.day_idnt
    FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.day_cal_454_dim AS cal
     INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.etl_batch_dt_lkup AS etl ON cal.day_date = etl.dw_batch_dt
     INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.day_cal_454_dim AS dcal ON cal.week_idnt = dcal.week_idnt
    WHERE LOWER(etl.interface_code) = LOWER('MRIc_DAY_AGG_DLY'))
 GROUP BY rms_sku_num,
  store_num,
  day_num,
  rp_ind);

