-- SET QUERY_BAND = '
-- App_ID=APP04070;
-- DAG_ID=merch_gds_ongoing_load;
-- Task_Name=gds_tran_fact_load;'
-- FOR SESSION VOLATILE;

-- ET;
MERGE INTO `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_inv_tran_sku_store_day_fact AS tgt
USING 
(SELECT rms_sku_num, 
day_date, 
store_num, 
MAX(selling_retail_price_amt) AS selling_retail_price_amt, 
MAX(ownership_retail_price_amt) AS ownership_retail_price_amt, 
MAX(regular_price_amt) AS regular_price_amt, 
MAX(compare_at_retail_price_amt) AS compare_at_retail_price_amt, 
MAX(weighted_average_cost_amt) AS weighted_average_cost_amt
    FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.merch_tran_sku_store_day_wrk AS w01
    GROUP BY rms_sku_num, day_date, store_num) AS SRC
ON LOWER(SRC.rms_sku_num) = LOWER(tgt.rms_sku_num) 
AND SRC.day_date = tgt.day_date 
AND SRC.store_num = tgt.store_num
WHEN MATCHED THEN UPDATE SET
    sales_units = 0,
    sales_retail_amt = 0,
    sales_cost_amt = 0,
    return_units = 0,
    return_retail_amt = 0,
    return_cost_amt = 0,
    reported_demand_units = 0,
    reported_demand_retail_amt = 0,
    fulfilled_demand_units = 0,
    fulfilled_demand_retail_amt = 0,
    demand_canceled_units = 0,
    demand_canceled_retail_amt = 0,
    demand_dropship_units = 0,
    demand_dropship_retail_amt = 0,
    store_fulfill_units = 0,
    store_fulfill_retail_amt = 0,
    receipt_units = 0,
    receipt_retail_amt = 0,
    receipt_cost_amt = 0,
    receipt_po_units = 0,
    receipt_po_retail_amt = 0,
    receipt_po_cost_amt = 0,
    receipt_pah_units = 0,
    receipt_pah_retail_amt = 0,
    receipt_pah_cost_amt = 0,
    receipt_dropship_units = 0,
    receipt_dropship_retail_amt = 0,
    receipt_dropship_cost_amt = 0,
    receipt_reservestock_units = 0,
    receipt_reservestock_retail_amt = 0,
    receipt_reservestock_cost_amt = 0,
    selling_retail_price_amt = SRC.selling_retail_price_amt,
    ownership_retail_price_amt = SRC.ownership_retail_price_amt,
    regular_price_amt = SRC.regular_price_amt,
    compare_at_retail_price_amt = SRC.compare_at_retail_price_amt,
    weighted_average_cost_amt = SRC.weighted_average_cost_amt,
    dw_sys_updt_tmstp = CAST(FORMAT_TIMESTAMP('%F %H:%M:%S', CURRENT_DATETIME('PST8PDT')) AS DATETIME);


MERGE INTO `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_inv_tran_sku_store_day_fact AS tgt
USING 
(SELECT rms_sku_num, day_date, 
  price_type,
  store_num,
  sales_units,
  sales_retail_amt,
  sales_cost_amt,
  return_units,
  return_retail_amt,
  return_cost_amt,
  reported_demand_units,
  reported_demand_retail_amt,
  fulfilled_demand_units,
  fulfilled_demand_retail_amt,
  demand_canceled_units,
  demand_canceled_retail_amt,
  demand_dropship_units,
  demand_dropship_retail_amt,
  store_fulfill_units,
  store_fulfill_retail_amt,
  receipt_units,
  receipt_retail_amt,
  receipt_cost_amt,
  receipt_po_units,
  receipt_po_retail_amt,
  receipt_po_cost_amt,
  receipt_pah_units,
  receipt_pah_retail_amt,
  receipt_pah_cost_amt,
  receipt_dropship_units,
  receipt_dropship_retail_amt,
  receipt_dropship_cost_amt,
  receipt_reservestock_units,
  receipt_reservestock_retail_amt,
  receipt_reservestock_cost_amt,
  selling_retail_price_amt,
  ownership_retail_price_amt,
  regular_price_amt,
  compare_at_retail_price_amt,
  weighted_average_cost_amt
  FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_base_vws.merch_tran_sku_store_day_wrk AS w01) AS SRC
ON LOWER(SRC.rms_sku_num) = LOWER(tgt.rms_sku_num) 
AND SRC.day_date = tgt.day_date 
AND LOWER(SRC.price_type) = LOWER(tgt.price_type) 
AND SRC.store_num = tgt.store_num
WHEN MATCHED THEN UPDATE SET
    sales_units = SRC.sales_units,
    sales_retail_amt = SRC.sales_retail_amt,
    sales_cost_amt = SRC.sales_cost_amt,
    return_units = SRC.return_units,
    return_retail_amt = SRC.return_retail_amt,
    return_cost_amt = SRC.return_cost_amt,
    reported_demand_units = SRC.reported_demand_units,
    reported_demand_retail_amt = SRC.reported_demand_retail_amt,
    fulfilled_demand_units = SRC.fulfilled_demand_units,
    fulfilled_demand_retail_amt = SRC.fulfilled_demand_retail_amt,
    demand_canceled_units = SRC.demand_canceled_units,
    demand_canceled_retail_amt = SRC.demand_canceled_retail_amt,
    demand_dropship_units = SRC.demand_dropship_units,
    demand_dropship_retail_amt = SRC.demand_dropship_retail_amt,
    store_fulfill_units = SRC.store_fulfill_units,
    store_fulfill_retail_amt = SRC.store_fulfill_retail_amt,
    receipt_units = SRC.receipt_units,
    receipt_retail_amt = SRC.receipt_retail_amt,
    receipt_cost_amt = SRC.receipt_cost_amt,
    receipt_po_units = SRC.receipt_po_units,
    receipt_po_retail_amt = SRC.receipt_po_retail_amt,
    receipt_po_cost_amt = SRC.receipt_po_cost_amt,
    receipt_pah_units = SRC.receipt_pah_units,
    receipt_pah_retail_amt = SRC.receipt_pah_retail_amt,
    receipt_pah_cost_amt = SRC.receipt_pah_cost_amt,
    receipt_dropship_units = SRC.receipt_dropship_units,
    receipt_dropship_retail_amt = SRC.receipt_dropship_retail_amt,
    receipt_dropship_cost_amt = SRC.receipt_dropship_cost_amt,
    receipt_reservestock_units = SRC.receipt_reservestock_units,
    receipt_reservestock_retail_amt = SRC.receipt_reservestock_retail_amt,
    receipt_reservestock_cost_amt = SRC.receipt_reservestock_cost_amt,
    selling_retail_price_amt = SRC.selling_retail_price_amt,
    ownership_retail_price_amt = SRC.ownership_retail_price_amt,
    regular_price_amt = SRC.regular_price_amt,
    compare_at_retail_price_amt = SRC.compare_at_retail_price_amt,
    weighted_average_cost_amt = SRC.weighted_average_cost_amt,
    dw_sys_updt_tmstp = CAST(FORMAT_TIMESTAMP('%F %H:%M:%S', CURRENT_DATETIME('PST8PDT')) AS DATETIME)
WHEN NOT MATCHED THEN 
INSERT
  (rms_sku_num,
    day_date,
    price_type,
    store_num,
    sales_units,
    sales_retail_amt,
    sales_cost_amt,
    return_units,
    return_retail_amt,
    return_cost_amt,
    reported_demand_units,
    reported_demand_retail_amt,
    fulfilled_demand_units,
    fulfilled_demand_retail_amt,
    demand_canceled_units,
    demand_canceled_retail_amt,
    demand_dropship_units,
    demand_dropship_retail_amt,
    store_fulfill_units,
    store_fulfill_retail_amt,
    RECEIPT_UNITS,
    RECEIPT_RETAIL_AMT,
    RECEIPT_COST_AMT,
    RECEIPT_PO_UNITS,
    RECEIPT_PO_RETAIL_AMT,
    RECEIPT_PO_COST_AMT,
    RECEIPT_PAH_UNITS,
    RECEIPT_PAH_RETAIL_AMT,
    RECEIPT_PAH_COST_AMT,
    RECEIPT_DROPSHIP_UNITS,
    RECEIPT_DROPSHIP_RETAIL_AMT,
    RECEIPT_DROPSHIP_COST_AMT,
    RECEIPT_RESERVESTOCK_UNITS,
    RECEIPT_RESERVESTOCK_RETAIL_AMT,
    RECEIPT_RESERVESTOCK_COST_AMT,
    SELLING_RETAIL_PRICE_AMT,
    OWNERSHIP_RETAIL_PRICE_AMT,
    REGULAR_PRICE_AMT,
    COMPARE_AT_RETAIL_PRICE_AMT,
    WEIGHTED_AVERAGE_COST_AMT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP)

 VALUES(  SRC.rms_sku_num,
  SRC.day_date,
  SRC.price_type,
  SRC.store_num,
  SRC.sales_units,
  SRC.sales_retail_amt,
  SRC.sales_cost_amt,
  SRC.return_units,
  SRC.return_retail_amt,
  SRC.return_cost_amt,
  SRC.reported_demand_units,
  SRC.reported_demand_retail_amt,
  SRC.fulfilled_demand_units,
  SRC.fulfilled_demand_retail_amt,
  SRC.demand_canceled_units,
  SRC.demand_canceled_retail_amt,
  SRC.demand_dropship_units,
  SRC.demand_dropship_retail_amt,
  SRC.store_fulfill_units,
  SRC.store_fulfill_retail_amt,
  SRC.receipt_units,
  SRC.receipt_retail_amt,
  SRC.receipt_cost_amt,
  SRC.receipt_po_units,
  SRC.receipt_po_retail_amt,
  SRC.receipt_po_cost_amt,
  SRC.receipt_pah_units,
  SRC.receipt_pah_retail_amt,
  SRC.receipt_pah_cost_amt,
  SRC.receipt_dropship_units,
  SRC.receipt_dropship_retail_amt,
  SRC.receipt_dropship_cost_amt,
  SRC.receipt_reservestock_units,
  SRC.receipt_reservestock_retail_amt,
  SRC.receipt_reservestock_cost_amt,
  CAST(TRUNC(SRC.selling_retail_price_amt) AS int64),
  SRC.ownership_retail_price_amt,
  SRC.regular_price_amt,
  CAST(TRUNC(SRC.compare_at_retail_price_amt) AS int64),
  SRC.weighted_average_cost_amt,
  CURRENT_DATETIME('PST8PDT') ,		
  CURRENT_DATETIME('PST8PDT'));

-- ET;
TRUNCATE TABLE `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_stg.merch_tran_sku_store_day_wrk;
-- ET;
TRUNCATE TABLE `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_stg.merch_sale_sku_store_day_wrk;
-- ET;
-- ET;
