/* SET QUERY_BAND = '
App_ID=APP04070;
DAG_ID=mfp_cost_country_banner_blend_week_fact_load;
Task_Name=country_banner_blend_data_load_country_banner_week_fct_load;'
FOR SESSION VOLATILE;*/

-- ET;


TRUNCATE TABLE `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.mfp_cost_plan_actual_banner_country_fact;


insert into `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.mfp_cost_plan_actual_banner_country_fact
(
      DEPT_NUM,
      WEEK_NUM,
      BANNER_COUNTRY_NUM,
      FULFILL_TYPE_NUM,
      CP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      CP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY,
      CP_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      CP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      CP_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      CP_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      CP_ENDING_OF_PERIOD_ACTIVE_QTY,
      CP_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      CP_ENDING_OF_PERIOD_INACTIVE_QTY,
      CP_TRANSFER_IN_ACTIVE_COST_AMT,
      CP_TRANSFER_IN_ACTIVE_QTY,
      CP_TRANSFER_OUT_ACTIVE_COST_AMT,
      CP_TRANSFER_OUT_ACTIVE_QTY,
      CP_TRANSFER_IN_INACTIVE_COST_AMT,
      CP_TRANSFER_IN_INACTIVE_QTY,
      CP_TRANSFER_OUT_INACTIVE_COST_AMT,
      CP_TRANSFER_OUT_INACTIVE_QTY,
      CP_TRANSFER_IN_OTHER_COST_AMT,
      CP_TRANSFER_IN_OTHER_QTY,
      CP_TRANSFER_OUT_OTHER_COST_AMT,
      CP_TRANSFER_OUT_OTHER_QTY,
      CP_TRANSFER_IN_RACKING_COST_AMT,
      CP_TRANSFER_IN_RACKING_QTY,
      CP_TRANSFER_OUT_RACKING_COST_AMT,
      CP_TRANSFER_OUT_RACKING_QTY,
      CP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      CP_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      CP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      CP_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      CP_RECEIPTS_ACTIVE_COST_AMT,
      CP_RECEIPTS_ACTIVE_QTY,
      CP_RECEIPTS_INACTIVE_COST_AMT,
      CP_RECEIPTS_INACTIVE_QTY,
      CP_RECEIPTS_RESERVE_COST_AMT,
      CP_RECEIPTS_RESERVE_QTY,
      CP_RECLASS_IN_COST_AMT,
      CP_RECLASS_IN_QTY,
      CP_RECLASS_OUT_COST_AMT,
      CP_RECLASS_OUT_QTY,
      CP_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      CP_RETURN_TO_VENDOR_ACTIVE_QTY,
      CP_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      CP_RETURN_TO_VENDOR_INACTIVE_QTY,
      CP_VENDOR_FUNDS_COST_AMT,
      CP_DISCOUNT_TERMS_COST_AMT,
      CP_MERCH_MARGIN_RETAIL_AMT,
      CP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT,
      CP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY,
      CP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT,
      CP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY,
      CP_OTHER_INVENTORY_ADJUSTMENT_COST_AMT,
      CP_OTHER_INVENTORY_ADJUSTMENT_QTY,
      CP_OPEN_TO_BUY_RECEIPTS_ACTIVE_COST_AMT,
      CP_OPEN_TO_BUY_RECEIPTS_INACTIVE_COST_AMT,
      OP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      OP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY,
      OP_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      OP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      OP_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      OP_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      OP_ENDING_OF_PERIOD_ACTIVE_QTY,
      OP_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      OP_ENDING_OF_PERIOD_INACTIVE_QTY,
      OP_TRANSFER_IN_ACTIVE_COST_AMT,
      OP_TRANSFER_IN_ACTIVE_QTY,
      OP_TRANSFER_OUT_ACTIVE_COST_AMT,
      OP_TRANSFER_OUT_ACTIVE_QTY,
      OP_TRANSFER_IN_INACTIVE_COST_AMT,
      OP_TRANSFER_IN_INACTIVE_QTY,
      OP_TRANSFER_OUT_INACTIVE_COST_AMT,
      OP_TRANSFER_OUT_INACTIVE_QTY,
      OP_TRANSFER_IN_OTHER_COST_AMT,
      OP_TRANSFER_IN_OTHER_QTY,
      OP_TRANSFER_OUT_OTHER_COST_AMT,
      OP_TRANSFER_OUT_OTHER_QTY,
      OP_TRANSFER_IN_RACKING_COST_AMT,
      OP_TRANSFER_IN_RACKING_QTY,
      OP_TRANSFER_OUT_RACKING_COST_AMT,
      OP_TRANSFER_OUT_RACKING_QTY,
      OP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      OP_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      OP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      OP_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      OP_RECEIPTS_ACTIVE_COST_AMT,
      OP_RECEIPTS_ACTIVE_QTY,
      OP_RECEIPTS_INACTIVE_COST_AMT,
      OP_RECEIPTS_INACTIVE_QTY,
      OP_RECEIPTS_RESERVE_COST_AMT,
      OP_RECEIPTS_RESERVE_QTY,
      OP_RECLASS_IN_COST_AMT,
      OP_RECLASS_IN_QTY,
      OP_RECLASS_OUT_COST_AMT,
      OP_RECLASS_OUT_QTY,
      OP_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      OP_RETURN_TO_VENDOR_ACTIVE_QTY,
      OP_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      OP_RETURN_TO_VENDOR_INACTIVE_QTY,
      OP_VENDOR_FUNDS_COST_AMT,
      OP_DISCOUNT_TERMS_COST_AMT,
      OP_MERCH_MARGIN_RETAIL_AMT,
      OP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT,
      OP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY,
      OP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT,
      OP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY,
      OP_OTHER_INVENTORY_ADJUSTMENT_COST_AMT,
      OP_OTHER_INVENTORY_ADJUSTMENT_QTY,
      SP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      SP_BEGINNING_OF_PERIOD_ACTIVE_INVENTORY_TARGET_QTY,
      SP_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      SP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      SP_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      SP_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      SP_ENDING_OF_PERIOD_ACTIVE_QTY,
      SP_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      SP_ENDING_OF_PERIOD_INACTIVE_QTY,
      SP_TRANSFER_IN_ACTIVE_COST_AMT,
      SP_TRANSFER_IN_ACTIVE_QTY,
      SP_TRANSFER_OUT_ACTIVE_COST_AMT,
      SP_TRANSFER_OUT_ACTIVE_QTY,
      SP_TRANSFER_IN_INACTIVE_COST_AMT,
      SP_TRANSFER_IN_INACTIVE_QTY,
      SP_TRANSFER_OUT_INACTIVE_COST_AMT,
      SP_TRANSFER_OUT_INACTIVE_QTY,
      SP_TRANSFER_IN_OTHER_COST_AMT,
      SP_TRANSFER_IN_OTHER_QTY,
      SP_TRANSFER_OUT_OTHER_COST_AMT,
      SP_TRANSFER_OUT_OTHER_QTY,
      SP_TRANSFER_IN_RACKING_COST_AMT,
      SP_TRANSFER_IN_RACKING_QTY,
      SP_TRANSFER_OUT_RACKING_COST_AMT,
      SP_TRANSFER_OUT_RACKING_QTY,
      SP_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      SP_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      SP_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      SP_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      SP_RECEIPTS_ACTIVE_COST_AMT,
      SP_RECEIPTS_ACTIVE_QTY,
      SP_RECEIPTS_INACTIVE_COST_AMT,
      SP_RECEIPTS_INACTIVE_QTY,
      SP_RECEIPTS_RESERVE_COST_AMT,
      SP_RECEIPTS_RESERVE_QTY,
      SP_RECLASS_IN_COST_AMT,
      SP_RECLASS_IN_QTY,
      SP_RECLASS_OUT_COST_AMT,
      SP_RECLASS_OUT_QTY,
      SP_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      SP_RETURN_TO_VENDOR_ACTIVE_QTY,
      SP_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      SP_RETURN_TO_VENDOR_INACTIVE_QTY,
      SP_VENDOR_FUNDS_COST_AMT,
      SP_DISCOUNT_TERMS_COST_AMT,
      SP_MERCH_MARGIN_RETAIL_AMT,
      SP_INVENTORY_MOVEMENT_IN_DROPSHIP_COST_AMT,
      SP_INVENTORY_MOVEMENT_IN_DROPSHIP_QTY,
      SP_INVENTORY_MOVEMENT_OUT_DROPSHIP_COST_AMT,
      SP_INVENTORY_MOVEMENT_OUT_DROPSHIP_QTY,
      SP_OTHER_INVENTORY_ADJUSTMENT_COST_AMT,
      SP_OTHER_INVENTORY_ADJUSTMENT_QTY,
      SP_OPEN_TO_BUY_RECEIPTS_ACTIVE_COST_AMT,
      SP_OPEN_TO_BUY_RECEIPTS_INACTIVE_COST_AMT,
      TY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      TY_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      TY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      TY_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      TY_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      TY_ENDING_OF_PERIOD_ACTIVE_QTY,
      TY_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      TY_ENDING_OF_PERIOD_INACTIVE_QTY,
      TY_TRANSFER_IN_ACTIVE_COST_AMT,
      TY_TRANSFER_IN_ACTIVE_QTY,
      TY_TRANSFER_OUT_ACTIVE_COST_AMT,
      TY_TRANSFER_OUT_ACTIVE_QTY,
      TY_TRANSFER_IN_INACTIVE_COST_AMT,
      TY_TRANSFER_IN_INACTIVE_QTY,
      TY_TRANSFER_OUT_INACTIVE_COST_AMT,
      TY_TRANSFER_OUT_INACTIVE_QTY,
      TY_TRANSFER_IN_OTHER_COST_AMT,
      TY_TRANSFER_IN_OTHER_QTY,
      TY_TRANSFER_OUT_OTHER_COST_AMT,
      TY_TRANSFER_OUT_OTHER_QTY,
      TY_TRANSFER_IN_RACKING_COST_AMT,
      TY_TRANSFER_IN_RACKING_QTY,
      TY_TRANSFER_OUT_RACKING_COST_AMT,
      TY_TRANSFER_OUT_RACKING_QTY,
      TY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      TY_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      TY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      TY_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      TY_RECEIPTS_ACTIVE_COST_AMT,
      TY_RECEIPTS_ACTIVE_QTY,
      TY_RECEIPTS_INACTIVE_COST_AMT,
      TY_RECEIPTS_INACTIVE_QTY,
      TY_RP_RECEIPTS_ACTIVE_COST_AMT,
      TY_NON_RP_RECEIPTS_ACTIVE_COST_AMT,
      TY_RECLASS_IN_COST_AMT,
      TY_RECLASS_IN_QTY,
      TY_RECLASS_OUT_COST_AMT,
      TY_RECLASS_OUT_QTY,
      TY_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      TY_RETURN_TO_VENDOR_ACTIVE_QTY,
      TY_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      TY_RETURN_TO_VENDOR_INACTIVE_QTY,
      TY_VENDOR_FUNDS_COST_AMT,
      TY_DISCOUNT_TERMS_COST_AMT,
      TY_MERCH_MARGIN_RETAIL_AMT,
      TY_SHRINK_BANNER_COST_AMT,
      TY_SHRINK_BANNER_QTY,
      TY_OTHER_INVENTORY_ADJ_COST,
      TY_MERCH_MARGIN_CHARGES_COST,
      LY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      LY_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      LY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      LY_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      LY_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      LY_ENDING_OF_PERIOD_ACTIVE_QTY,
      LY_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      LY_ENDING_OF_PERIOD_INACTIVE_QTY,
      LY_TRANSFER_IN_ACTIVE_COST_AMT,
      LY_TRANSFER_IN_ACTIVE_QTY,
      LY_TRANSFER_OUT_ACTIVE_COST_AMT,
      LY_TRANSFER_OUT_ACTIVE_QTY,
      LY_TRANSFER_IN_INACTIVE_COST_AMT,
      LY_TRANSFER_IN_INACTIVE_QTY,
      LY_TRANSFER_OUT_INACTIVE_COST_AMT,
      LY_TRANSFER_OUT_INACTIVE_QTY,
      LY_TRANSFER_IN_OTHER_COST_AMT,
      LY_TRANSFER_IN_OTHER_QTY,
      LY_TRANSFER_OUT_OTHER_COST_AMT,
      LY_TRANSFER_OUT_OTHER_QTY,
      LY_TRANSFER_IN_RACKING_COST_AMT,
      LY_TRANSFER_IN_RACKING_QTY,
      LY_TRANSFER_OUT_RACKING_COST_AMT,
      LY_TRANSFER_OUT_RACKING_QTY,
      LY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      LY_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      LY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      LY_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      LY_RECEIPTS_ACTIVE_COST_AMT,
      LY_RECEIPTS_ACTIVE_QTY,
      LY_RECEIPTS_INACTIVE_COST_AMT,
      LY_RECEIPTS_INACTIVE_QTY,
      LY_RP_RECEIPTS_ACTIVE_COST_AMT,
      LY_NON_RP_RECEIPTS_ACTIVE_COST_AMT,
      LY_RECLASS_IN_COST_AMT,
      LY_RECLASS_IN_QTY,
      LY_RECLASS_OUT_COST_AMT,
      LY_RECLASS_OUT_QTY,
      LY_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      LY_RETURN_TO_VENDOR_ACTIVE_QTY,
      LY_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      LY_RETURN_TO_VENDOR_INACTIVE_QTY,
      LY_VENDOR_FUNDS_COST_AMT,
      LY_DISCOUNT_TERMS_COST_AMT,
      LY_MERCH_MARGIN_RETAIL_AMT,
      LY_SHRINK_BANNER_COST_AMT,
      LY_SHRINK_BANNER_QTY,
      LY_OTHER_INVENTORY_ADJ_COST,
      LY_MERCH_MARGIN_CHARGES_COST,
      LLY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      LLY_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      LLY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      LLY_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      LLY_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      LLY_ENDING_OF_PERIOD_ACTIVE_QTY,
      LLY_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      LLY_ENDING_OF_PERIOD_INACTIVE_QTY,
      LLY_TRANSFER_IN_ACTIVE_COST_AMT,
      LLY_TRANSFER_IN_ACTIVE_QTY,
      LLY_TRANSFER_OUT_ACTIVE_COST_AMT,
      LLY_TRANSFER_OUT_ACTIVE_QTY,
      LLY_TRANSFER_IN_INACTIVE_COST_AMT,
      LLY_TRANSFER_IN_INACTIVE_QTY,
      LLY_TRANSFER_OUT_INACTIVE_COST_AMT,
      LLY_TRANSFER_OUT_INACTIVE_QTY,
      LLY_TRANSFER_IN_OTHER_COST_AMT,
      LLY_TRANSFER_IN_OTHER_QTY,
      LLY_TRANSFER_OUT_OTHER_COST_AMT,
      LLY_TRANSFER_OUT_OTHER_QTY,
      LLY_TRANSFER_IN_RACKING_COST_AMT,
      LLY_TRANSFER_IN_RACKING_QTY,
      LLY_TRANSFER_OUT_RACKING_COST_AMT,
      LLY_TRANSFER_OUT_RACKING_QTY,
      LLY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      LLY_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      LLY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      LLY_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      LLY_RECEIPTS_ACTIVE_COST_AMT,
      LLY_RECEIPTS_ACTIVE_QTY,
      LLY_RECEIPTS_INACTIVE_COST_AMT,
      LLY_RECEIPTS_INACTIVE_QTY,
      LLY_RP_RECEIPTS_ACTIVE_COST_AMT,
      LLY_NON_RP_RECEIPTS_ACTIVE_COST_AMT,
      LLY_RECLASS_IN_COST_AMT,
      LLY_RECLASS_IN_QTY,
      LLY_RECLASS_OUT_COST_AMT,
      LLY_RECLASS_OUT_QTY,
      LLY_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      LLY_RETURN_TO_VENDOR_ACTIVE_QTY,
      LLY_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      LLY_RETURN_TO_VENDOR_INACTIVE_QTY,
      LLY_VENDOR_FUNDS_COST_AMT,
      LLY_DISCOUNT_TERMS_COST_AMT,
      LLY_MERCH_MARGIN_RETAIL_AMT,
      LLY_SHRINK_BANNER_COST_AMT,
      LLY_SHRINK_BANNER_QTY,
      LLY_OTHER_INVENTORY_ADJ_COST,
      LLY_MERCH_MARGIN_CHARGES_COST,
      LY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      LY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      LY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      LY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      LY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      LY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_QTY,
      LY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      LY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_QTY,
      LY_TRUEDAY_TRANSFER_IN_ACTIVE_COST_AMT,
      LY_TRUEDAY_TRANSFER_IN_ACTIVE_QTY,
      LY_TRUEDAY_TRANSFER_OUT_ACTIVE_COST_AMT,
      LY_TRUEDAY_TRANSFER_OUT_ACTIVE_QTY,
      LY_TRUEDAY_TRANSFER_IN_INACTIVE_COST_AMT,
      LY_TRUEDAY_TRANSFER_IN_INACTIVE_QTY,
      LY_TRUEDAY_TRANSFER_OUT_INACTIVE_COST_AMT,
      LY_TRUEDAY_TRANSFER_OUT_INACTIVE_QTY,
      LY_TRUEDAY_TRANSFER_IN_OTHER_COST_AMT,
      LY_TRUEDAY_TRANSFER_IN_OTHER_QTY,
      LY_TRUEDAY_TRANSFER_OUT_OTHER_COST_AMT,
      LY_TRUEDAY_TRANSFER_OUT_OTHER_QTY,
      LY_TRUEDAY_TRANSFER_IN_RACKING_COST_AMT,
      LY_TRUEDAY_TRANSFER_IN_RACKING_QTY,
      LY_TRUEDAY_TRANSFER_OUT_RACKING_COST_AMT,
      LY_TRUEDAY_TRANSFER_OUT_RACKING_QTY,
      LY_TRUEDAY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      LY_TRUEDAY_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      LY_TRUEDAY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      LY_TRUEDAY_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      LY_TRUEDAY_RECEIPTS_ACTIVE_COST_AMT,
      LY_TRUEDAY_RECEIPTS_ACTIVE_QTY,
      LY_TRUEDAY_RECEIPTS_INACTIVE_COST_AMT,
      LY_TRUEDAY_RECEIPTS_INACTIVE_QTY,
      LY_TRUEDAY_RP_RECEIPTS_ACTIVE_COST_AMT,
      LY_TRUEDAY_NON_RP_RECEIPTS_ACTIVE_COST_AMT,
      LY_TRUEDAY_RECLASS_IN_COST_AMT,
      LY_TRUEDAY_RECLASS_IN_QTY,
      LY_TRUEDAY_RECLASS_OUT_COST_AMT,
      LY_TRUEDAY_RECLASS_OUT_QTY,
      LY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      LY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_QTY,
      LY_TRUEDAY_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      LY_TRUEDAY_RETURN_TO_VENDOR_INACTIVE_QTY,
      LY_TRUEDAY_VENDOR_FUNDS_COST_AMT,
      LY_TRUEDAY_DISCOUNT_TERMS_COST_AMT,
      LY_TRUEDAY_MERCH_MARGIN_RETAIL_AMT,
      LY_TRUEDAY_SHRINK_BANNER_COST_AMT,
      LY_TRUEDAY_SHRINK_BANNER_QTY,
      LY_TRUEDAY_OTHER_INVENTORY_ADJ_COST,
      LY_TRUEDAY_MERCH_MARGIN_CHARGES_COST,
      LLY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT,
      LLY_TRUEDAY_BEGINNING_OF_PERIOD_ACTIVE_QTY,
      LLY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT,
      LLY_TRUEDAY_BEGINNING_OF_PERIOD_INACTIVE_QTY,
      LLY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_COST_AMT,
      LLY_TRUEDAY_ENDING_OF_PERIOD_ACTIVE_QTY,
      LLY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_COST_AMT,
      LLY_TRUEDAY_ENDING_OF_PERIOD_INACTIVE_QTY,
      LLY_TRUEDAY_TRANSFER_IN_ACTIVE_COST_AMT,
      LLY_TRUEDAY_TRANSFER_IN_ACTIVE_QTY,
      LLY_TRUEDAY_TRANSFER_OUT_ACTIVE_COST_AMT,
      LLY_TRUEDAY_TRANSFER_OUT_ACTIVE_QTY,
      LLY_TRUEDAY_TRANSFER_IN_INACTIVE_COST_AMT,
      LLY_TRUEDAY_TRANSFER_IN_INACTIVE_QTY,
      LLY_TRUEDAY_TRANSFER_OUT_INACTIVE_COST_AMT,
      LLY_TRUEDAY_TRANSFER_OUT_INACTIVE_QTY,
      LLY_TRUEDAY_TRANSFER_IN_OTHER_COST_AMT,
      LLY_TRUEDAY_TRANSFER_IN_OTHER_QTY,
      LLY_TRUEDAY_TRANSFER_OUT_OTHER_COST_AMT,
      LLY_TRUEDAY_TRANSFER_OUT_OTHER_QTY,
      LLY_TRUEDAY_TRANSFER_IN_RACKING_COST_AMT,
      LLY_TRUEDAY_TRANSFER_IN_RACKING_QTY,
      LLY_TRUEDAY_TRANSFER_OUT_RACKING_COST_AMT,
      LLY_TRUEDAY_TRANSFER_OUT_RACKING_QTY,
      LLY_TRUEDAY_MARK_OUT_OF_STOCK_ACTIVE_COST_AMT,
      LLY_TRUEDAY_MARK_OUT_OF_STOCK_ACTIVE_QTY,
      LLY_TRUEDAY_MARK_OUT_OF_STOCK_INACTIVE_COST_AMT,
      LLY_TRUEDAY_MARK_OUT_OF_STOCK_INACTIVE_QTY,
      LLY_TRUEDAY_RECEIPTS_ACTIVE_COST_AMT,
      LLY_TRUEDAY_RECEIPTS_ACTIVE_QTY,
      LLY_TRUEDAY_RECEIPTS_INACTIVE_COST_AMT,
      LLY_TRUEDAY_RECEIPTS_INACTIVE_QTY,
      LLY_TRUEDAY_RP_RECEIPTS_ACTIVE_COST_AMT,
      LLY_TRUEDAY_NON_RP_RECEIPTS_ACTIVE_COST_AMT,
      LLY_TRUEDAY_RECLASS_IN_COST_AMT,
      LLY_TRUEDAY_RECLASS_IN_QTY,
      LLY_TRUEDAY_RECLASS_OUT_COST_AMT,
      LLY_TRUEDAY_RECLASS_OUT_QTY,
      LLY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_COST_AMT,
      LLY_TRUEDAY_RETURN_TO_VENDOR_ACTIVE_QTY,
      LLY_TRUEDAY_RETURN_TO_VENDOR_INACTIVE_COST_AMT,
      LLY_TRUEDAY_RETURN_TO_VENDOR_INACTIVE_QTY,
      LLY_TRUEDAY_VENDOR_FUNDS_COST_AMT,
      LLY_TRUEDAY_DISCOUNT_TERMS_COST_AMT,
      LLY_TRUEDAY_MERCH_MARGIN_RETAIL_AMT,
      LLY_TRUEDAY_SHRINK_BANNER_COST_AMT,
      LLY_TRUEDAY_SHRINK_BANNER_QTY,
      LLY_TRUEDAY_OTHER_INVENTORY_ADJ_COST,
      LLY_TRUEDAY_MERCH_MARGIN_CHARGES_COST,
      DW_BATCH_DATE, 
      DW_SYS_LOAD_TMSTP
)
SELECT dept_num,
 week_num,
 banner_country_num,
 fulfill_type_num,
 SUM(cp_beginning_of_period_active_cost_amt) AS cp_beginning_of_period_active_cost_amt,
 SUM(cp_beginning_of_period_active_inventory_target_qty) AS cp_beginning_of_period_active_inventory_target_qty,
 SUM(cp_beginning_of_period_active_qty) AS cp_beginning_of_period_active_qty,
 SUM(cp_beginning_of_period_inactive_cost_amt) AS cp_beginning_of_period_inactive_cost_amt,
 SUM(cp_beginning_of_period_inactive_qty) AS cp_beginning_of_period_inactive_qty,
 SUM(cp_ending_of_period_active_cost_amt) AS cp_ending_of_period_active_cost_amt,
 SUM(cp_ending_of_period_active_qty) AS cp_ending_of_period_active_qty,
 SUM(cp_ending_of_period_inactive_cost_amt) AS cp_ending_of_period_inactive_cost_amt,
 SUM(cp_ending_of_period_inactive_qty) AS cp_ending_of_period_inactive_qty,
 SUM(cp_transfer_in_active_cost_amt) AS cp_transfer_in_active_cost_amt,
 SUM(cp_transfer_in_active_qty) AS cp_transfer_in_active_qty,
 SUM(cp_transfer_out_active_cost_amt) AS cp_transfer_out_active_cost_amt,
 SUM(cp_transfer_out_active_qty) AS cp_transfer_out_active_qty,
 SUM(cp_transfer_in_inactive_cost_amt) AS cp_transfer_in_inactive_cost_amt,
 SUM(cp_transfer_in_inactive_qty) AS cp_transfer_in_inactive_qty,
 SUM(cp_transfer_out_inactive_cost_amt) AS cp_transfer_out_inactive_cost_amt,
 SUM(cp_transfer_out_inactive_qty) AS cp_transfer_out_inactive_qty,
 SUM(cp_transfer_in_other_cost_amt) AS cp_transfer_in_other_cost_amt,
 SUM(cp_transfer_in_other_qty) AS cp_transfer_in_other_qty,
 SUM(cp_transfer_out_other_cost_amt) AS cp_transfer_out_other_cost_amt,
 SUM(cp_transfer_out_other_qty) AS cp_transfer_out_other_qty,
 SUM(cp_transfer_in_racking_cost_amt) AS cp_transfer_in_racking_cost_amt,
 SUM(cp_transfer_in_racking_qty) AS cp_transfer_in_racking_qty,
 SUM(cp_transfer_out_racking_cost_amt) AS cp_transfer_out_racking_cost_amt,
 SUM(cp_transfer_out_racking_qty) AS cp_transfer_out_racking_qty,
 SUM(cp_mark_out_of_stock_active_cost_amt) AS cp_mark_out_of_stock_active_cost_amt,
 SUM(cp_mark_out_of_stock_active_qty) AS cp_mark_out_of_stock_active_qty,
 SUM(cp_mark_out_of_stock_inactive_cost_amt) AS cp_mark_out_of_stock_inactive_cost_amt,
 SUM(cp_mark_out_of_stock_inactive_qty) AS cp_mark_out_of_stock_inactive_qty,
 SUM(cp_receipts_active_cost_amt) AS cp_receipts_active_cost_amt,
 SUM(cp_receipts_active_qty) AS cp_receipts_active_qty,
 SUM(cp_receipts_inactive_cost_amt) AS cp_receipts_inactive_cost_amt,
 SUM(cp_receipts_inactive_qty) AS cp_receipts_inactive_qty,
 SUM(cp_receipts_reserve_cost_amt) AS cp_receipts_reserve_cost_amt,
 SUM(cp_receipts_reserve_qty) AS cp_receipts_reserve_qty,
 SUM(cp_reclass_in_cost_amt) AS cp_reclass_in_cost_amt,
 SUM(cp_reclass_in_qty) AS cp_reclass_in_qty,
 SUM(cp_reclass_out_cost_amt) AS cp_reclass_out_cost_amt,
 SUM(cp_reclass_out_qty) AS cp_reclass_out_qty,
 SUM(cp_return_to_vendor_active_cost_amt) AS cp_return_to_vendor_active_cost_amt,
 SUM(cp_return_to_vendor_active_qty) AS cp_return_to_vendor_active_qty,
 SUM(cp_return_to_vendor_inactive_cost_amt) AS cp_return_to_vendor_inactive_cost_amt,
 SUM(cp_return_to_vendor_inactive_qty) AS cp_return_to_vendor_inactive_qty,
 SUM(cp_vendor_funds_cost_amt) AS cp_vendor_funds_cost_amt,
 SUM(cp_discount_terms_cost_amt) AS cp_discount_terms_cost_amt,
 SUM(cp_merch_margin_retail_amt) AS cp_merch_margin_retail_amt,
 SUM(cp_inventory_movement_in_dropship_cost_amt) AS cp_inventory_movement_in_dropship_cost_amt,
 SUM(cp_inventory_movement_in_dropship_qty) AS cp_inventory_movement_in_dropship_qty,
 SUM(cp_inventory_movement_out_dropship_cost_amt) AS cp_inventory_movement_out_dropship_cost_amt,
 SUM(cp_inventory_movement_out_dropship_qty) AS cp_inventory_movement_out_dropship_qty,
 SUM(cp_other_inventory_adjustment_cost_amt) AS cp_other_inventory_adjustment_cost_amt,
 SUM(cp_other_inventory_adjustment_qty) AS cp_other_inventory_adjustment_qty,
 SUM(cp_open_to_buy_receipts_active_cost_amt) AS cp_open_to_buy_receipts_active_cost_amt,
 SUM(cp_open_to_buy_receipts_inactive_cost_amt) AS cp_open_to_buy_receipts_inactive_cost_amt,
 SUM(op_beginning_of_period_active_cost_amt) AS op_beginning_of_period_active_cost_amt,
 SUM(op_beginning_of_period_active_inventory_target_qty) AS op_beginning_of_period_active_inventory_target_qty,
 SUM(op_beginning_of_period_active_qty) AS op_beginning_of_period_active_qty,
 SUM(op_beginning_of_period_inactive_cost_amt) AS op_beginning_of_period_inactive_cost_amt,
 SUM(op_beginning_of_period_inactive_qty) AS op_beginning_of_period_inactive_qty,
 SUM(op_ending_of_period_active_cost_amt) AS op_ending_of_period_active_cost_amt,
 SUM(op_ending_of_period_active_qty) AS op_ending_of_period_active_qty,
 SUM(op_ending_of_period_inactive_cost_amt) AS op_ending_of_period_inactive_cost_amt,
 SUM(op_ending_of_period_inactive_qty) AS op_ending_of_period_inactive_qty,
 SUM(op_transfer_in_active_cost_amt) AS op_transfer_in_active_cost_amt,
 SUM(op_transfer_in_active_qty) AS op_transfer_in_active_qty,
 SUM(op_transfer_out_active_cost_amt) AS op_transfer_out_active_cost_amt,
 SUM(op_transfer_out_active_qty) AS op_transfer_out_active_qty,
 SUM(op_transfer_in_inactive_cost_amt) AS op_transfer_in_inactive_cost_amt,
 SUM(op_transfer_in_inactive_qty) AS op_transfer_in_inactive_qty,
 SUM(op_transfer_out_inactive_cost_amt) AS op_transfer_out_inactive_cost_amt,
 SUM(op_transfer_out_inactive_qty) AS op_transfer_out_inactive_qty,
 SUM(op_transfer_in_other_cost_amt) AS op_transfer_in_other_cost_amt,
 SUM(op_transfer_in_other_qty) AS op_transfer_in_other_qty,
 SUM(op_transfer_out_other_cost_amt) AS op_transfer_out_other_cost_amt,
 SUM(op_transfer_out_other_qty) AS op_transfer_out_other_qty,
 SUM(op_transfer_in_racking_cost_amt) AS op_transfer_in_racking_cost_amt,
 SUM(op_transfer_in_racking_qty) AS op_transfer_in_racking_qty,
 SUM(op_transfer_out_racking_cost_amt) AS op_transfer_out_racking_cost_amt,
 SUM(op_transfer_out_racking_qty) AS op_transfer_out_racking_qty,
 SUM(op_mark_out_of_stock_active_cost_amt) AS op_mark_out_of_stock_active_cost_amt,
 SUM(op_mark_out_of_stock_active_qty) AS op_mark_out_of_stock_active_qty,
 SUM(op_mark_out_of_stock_inactive_cost_amt) AS op_mark_out_of_stock_inactive_cost_amt,
 SUM(op_mark_out_of_stock_inactive_qty) AS op_mark_out_of_stock_inactive_qty,
 SUM(op_receipts_active_cost_amt) AS op_receipts_active_cost_amt,
 SUM(op_receipts_active_qty) AS op_receipts_active_qty,
 SUM(op_receipts_inactive_cost_amt) AS op_receipts_inactive_cost_amt,
 SUM(op_receipts_inactive_qty) AS op_receipts_inactive_qty,
 SUM(op_receipts_reserve_cost_amt) AS op_receipts_reserve_cost_amt,
 SUM(op_receipts_reserve_qty) AS op_receipts_reserve_qty,
 SUM(op_reclass_in_cost_amt) AS op_reclass_in_cost_amt,
 SUM(op_reclass_in_qty) AS op_reclass_in_qty,
 SUM(op_reclass_out_cost_amt) AS op_reclass_out_cost_amt,
 SUM(op_reclass_out_qty) AS op_reclass_out_qty,
 SUM(op_return_to_vendor_active_cost_amt) AS op_return_to_vendor_active_cost_amt,
 SUM(op_return_to_vendor_active_qty) AS op_return_to_vendor_active_qty,
 SUM(op_return_to_vendor_inactive_cost_amt) AS op_return_to_vendor_inactive_cost_amt,
 SUM(op_return_to_vendor_inactive_qty) AS op_return_to_vendor_inactive_qty,
 SUM(op_vendor_funds_cost_amt) AS op_vendor_funds_cost_amt,
 SUM(op_discount_terms_cost_amt) AS op_discount_terms_cost_amt,
 SUM(op_merch_margin_retail_amt) AS op_merch_margin_retail_amt,
 SUM(op_inventory_movement_in_dropship_cost_amt) AS op_inventory_movement_in_dropship_cost_amt,
 SUM(op_inventory_movement_in_dropship_qty) AS op_inventory_movement_in_dropship_qty,
 SUM(op_inventory_movement_out_dropship_cost_amt) AS op_inventory_movement_out_dropship_cost_amt,
 SUM(op_inventory_movement_out_dropship_qty) AS op_inventory_movement_out_dropship_qty,
 SUM(op_other_inventory_adjustment_cost_amt) AS op_other_inventory_adjustment_cost_amt,
 SUM(op_other_inventory_adjustment_qty) AS op_other_inventory_adjustment_qty,
 SUM(sp_beginning_of_period_active_cost_amt) AS sp_beginning_of_period_active_cost_amt,
 SUM(sp_beginning_of_period_active_inventory_target_qty) AS sp_beginning_of_period_active_inventory_target_qty,
 SUM(sp_beginning_of_period_active_qty) AS sp_beginning_of_period_active_qty,
 SUM(sp_beginning_of_period_inactive_cost_amt) AS sp_beginning_of_period_inactive_cost_amt,
 SUM(sp_beginning_of_period_inactive_qty) AS sp_beginning_of_period_inactive_qty,
 SUM(sp_ending_of_period_active_cost_amt) AS sp_ending_of_period_active_cost_amt,
 SUM(sp_ending_of_period_active_qty) AS sp_ending_of_period_active_qty,
 SUM(sp_ending_of_period_inactive_cost_amt) AS sp_ending_of_period_inactive_cost_amt,
 SUM(sp_ending_of_period_inactive_qty) AS sp_ending_of_period_inactive_qty,
 SUM(sp_transfer_in_active_cost_amt) AS sp_transfer_in_active_cost_amt,
 SUM(sp_transfer_in_active_qty) AS sp_transfer_in_active_qty,
 SUM(sp_transfer_out_active_cost_amt) AS sp_transfer_out_active_cost_amt,
 SUM(sp_transfer_out_active_qty) AS sp_transfer_out_active_qty,
 SUM(sp_transfer_in_inactive_cost_amt) AS sp_transfer_in_inactive_cost_amt,
 SUM(sp_transfer_in_inactive_qty) AS sp_transfer_in_inactive_qty,
 SUM(sp_transfer_out_inactive_cost_amt) AS sp_transfer_out_inactive_cost_amt,
 SUM(sp_transfer_out_inactive_qty) AS sp_transfer_out_inactive_qty,
 SUM(sp_transfer_in_other_cost_amt) AS sp_transfer_in_other_cost_amt,
 SUM(sp_transfer_in_other_qty) AS sp_transfer_in_other_qty,
 SUM(sp_transfer_out_other_cost_amt) AS sp_transfer_out_other_cost_amt,
 SUM(sp_transfer_out_other_qty) AS sp_transfer_out_other_qty,
 SUM(sp_transfer_in_racking_cost_amt) AS sp_transfer_in_racking_cost_amt,
 SUM(sp_transfer_in_racking_qty) AS sp_transfer_in_racking_qty,
 SUM(sp_transfer_out_racking_cost_amt) AS sp_transfer_out_racking_cost_amt,
 SUM(sp_transfer_out_racking_qty) AS sp_transfer_out_racking_qty,
 SUM(sp_mark_out_of_stock_active_cost_amt) AS sp_mark_out_of_stock_active_cost_amt,
 SUM(sp_mark_out_of_stock_active_qty) AS sp_mark_out_of_stock_active_qty,
 SUM(sp_mark_out_of_stock_inactive_cost_amt) AS sp_mark_out_of_stock_inactive_cost_amt,
 SUM(sp_mark_out_of_stock_inactive_qty) AS sp_mark_out_of_stock_inactive_qty,
 SUM(sp_receipts_active_cost_amt) AS sp_receipts_active_cost_amt,
 SUM(sp_receipts_active_qty) AS sp_receipts_active_qty,
 SUM(sp_receipts_inactive_cost_amt) AS sp_receipts_inactive_cost_amt,
 SUM(sp_receipts_inactive_qty) AS sp_receipts_inactive_qty,
 SUM(sp_receipts_reserve_cost_amt) AS sp_receipts_reserve_cost_amt,
 SUM(sp_receipts_reserve_qty) AS sp_receipts_reserve_qty,
 SUM(sp_reclass_in_cost_amt) AS sp_reclass_in_cost_amt,
 SUM(sp_reclass_in_qty) AS sp_reclass_in_qty,
 SUM(sp_reclass_out_cost_amt) AS sp_reclass_out_cost_amt,
 SUM(sp_reclass_out_qty) AS sp_reclass_out_qty,
 SUM(sp_return_to_vendor_active_cost_amt) AS sp_return_to_vendor_active_cost_amt,
 SUM(sp_return_to_vendor_active_qty) AS sp_return_to_vendor_active_qty,
 SUM(sp_return_to_vendor_inactive_cost_amt) AS sp_return_to_vendor_inactive_cost_amt,
 SUM(sp_return_to_vendor_inactive_qty) AS sp_return_to_vendor_inactive_qty,
 SUM(sp_vendor_funds_cost_amt) AS sp_vendor_funds_cost_amt,
 SUM(sp_discount_terms_cost_amt) AS sp_discount_terms_cost_amt,
 SUM(sp_merch_margin_retail_amt) AS sp_merch_margin_retail_amt,
 SUM(sp_inventory_movement_in_dropship_cost_amt) AS sp_inventory_movement_in_dropship_cost_amt,
 SUM(sp_inventory_movement_in_dropship_qty) AS sp_inventory_movement_in_dropship_qty,
 SUM(sp_inventory_movement_out_dropship_cost_amt) AS sp_inventory_movement_out_dropship_cost_amt,
 SUM(sp_inventory_movement_out_dropship_qty) AS sp_inventory_movement_out_dropship_qty,
 SUM(sp_other_inventory_adjustment_cost_amt) AS sp_other_inventory_adjustment_cost_amt,
 SUM(sp_other_inventory_adjustment_qty) AS sp_other_inventory_adjustment_qty,
 SUM(sp_open_to_buy_receipts_active_cost_amt) AS sp_open_to_buy_receipts_active_cost_amt,
 SUM(sp_open_to_buy_receipts_inactive_cost_amt) AS sp_open_to_buy_receipts_inactive_cost_amt,
 SUM(ty_beginning_of_period_active_cost_amt) AS ty_beginning_of_period_active_cost_amt,
 SUM(ty_beginning_of_period_active_qty) AS ty_beginning_of_period_active_qty,
 SUM(ty_beginning_of_period_inactive_cost_amt) AS ty_beginning_of_period_inactive_cost_amt,
 SUM(ty_beginning_of_period_inactive_qty) AS ty_beginning_of_period_inactive_qty,
 SUM(ty_ending_of_period_active_cost_amt) AS ty_ending_of_period_active_cost_amt,
 SUM(ty_ending_of_period_active_qty) AS ty_ending_of_period_active_qty,
 SUM(ty_ending_of_period_inactive_cost_amt) AS ty_ending_of_period_inactive_cost_amt,
 SUM(ty_ending_of_period_inactive_qty) AS ty_ending_of_period_inactive_qty,
 SUM(ty_transfer_in_active_cost_amt) AS ty_transfer_in_active_cost_amt,
 SUM(ty_transfer_in_active_qty) AS ty_transfer_in_active_qty,
 SUM(ty_transfer_out_active_cost_amt) AS ty_transfer_out_active_cost_amt,
 SUM(ty_transfer_out_active_qty) AS ty_transfer_out_active_qty,
 SUM(ty_transfer_in_inactive_cost_amt) AS ty_transfer_in_inactive_cost_amt,
 SUM(ty_transfer_in_inactive_qty) AS ty_transfer_in_inactive_qty,
 SUM(ty_transfer_out_inactive_cost_amt) AS ty_transfer_out_inactive_cost_amt,
 SUM(ty_transfer_out_inactive_qty) AS ty_transfer_out_inactive_qty,
 SUM(ty_transfer_in_other_cost_amt) AS ty_transfer_in_other_cost_amt,
 SUM(ty_transfer_in_other_qty) AS ty_transfer_in_other_qty,
 SUM(ty_transfer_out_other_cost_amt) AS ty_transfer_out_other_cost_amt,
 SUM(ty_transfer_out_other_qty) AS ty_transfer_out_other_qty,
 SUM(ty_transfer_in_racking_cost_amt) AS ty_transfer_in_racking_cost_amt,
 SUM(ty_transfer_in_racking_qty) AS ty_transfer_in_racking_qty,
 SUM(ty_transfer_out_racking_cost_amt) AS ty_transfer_out_racking_cost_amt,
 SUM(ty_transfer_out_racking_qty) AS ty_transfer_out_racking_qty,
 SUM(ty_mark_out_of_stock_active_cost_amt) AS ty_mark_out_of_stock_active_cost_amt,
 SUM(ty_mark_out_of_stock_active_qty) AS ty_mark_out_of_stock_active_qty,
 SUM(ty_mark_out_of_stock_inactive_cost_amt) AS ty_mark_out_of_stock_inactive_cost_amt,
 SUM(ty_mark_out_of_stock_inactive_qty) AS ty_mark_out_of_stock_inactive_qty,
 SUM(ty_receipts_active_cost_amt) AS ty_receipts_active_cost_amt,
 SUM(ty_receipts_active_qty) AS ty_receipts_active_qty,
 SUM(ty_receipts_inactive_cost_amt) AS ty_receipts_inactive_cost_amt,
 SUM(ty_receipts_inactive_qty) AS ty_receipts_inactive_qty,
 SUM(ty_rp_receipts_active_cost_amt) AS ty_rp_receipts_active_cost_amt,
 SUM(ty_non_rp_receipts_active_cost_amt) AS ty_non_rp_receipts_active_cost_amt,
 SUM(ty_reclass_in_cost_amt) AS ty_reclass_in_cost_amt,
 SUM(ty_reclass_in_qty) AS ty_reclass_in_qty,
 SUM(ty_reclass_out_cost_amt) AS ty_reclass_out_cost_amt,
 SUM(ty_reclass_out_qty) AS ty_reclass_out_qty,
 SUM(ty_return_to_vendor_active_cost_amt) AS ty_return_to_vendor_active_cost_amt,
 SUM(ty_return_to_vendor_active_qty) AS ty_return_to_vendor_active_qty,
 SUM(ty_return_to_vendor_inactive_cost_amt) AS ty_return_to_vendor_inactive_cost_amt,
 SUM(ty_return_to_vendor_inactive_qty) AS ty_return_to_vendor_inactive_qty,
 SUM(ty_vendor_funds_cost_amt) AS ty_vendor_funds_cost_amt,
 SUM(ty_discount_terms_cost_amt) AS ty_discount_terms_cost_amt,
 SUM(ty_merch_margin_retail_amt) AS ty_merch_margin_retail_amt,
 SUM(ty_shrink_banner_cost_amt) AS ty_shrink_banner_cost_amt,
 SUM(ty_shrink_banner_qty) AS ty_shrink_banner_qty,
 SUM(ty_other_inventory_adj_cost) AS ty_other_inventory_adj_cost,
 SUM(ty_merch_margin_charges_cost) AS ty_merch_margin_charges_cost,
 SUM(ly_beginning_of_period_active_cost_amt) AS ly_beginning_of_period_active_cost_amt,
 SUM(ly_beginning_of_period_active_qty) AS ly_beginning_of_period_active_qty,
 SUM(ly_beginning_of_period_inactive_cost_amt) AS ly_beginning_of_period_inactive_cost_amt,
 SUM(ly_beginning_of_period_inactive_qty) AS ly_beginning_of_period_inactive_qty,
 SUM(ly_ending_of_period_active_cost_amt) AS ly_ending_of_period_active_cost_amt,
 SUM(ly_ending_of_period_active_qty) AS ly_ending_of_period_active_qty,
 SUM(ly_ending_of_period_inactive_cost_amt) AS ly_ending_of_period_inactive_cost_amt,
 SUM(ly_ending_of_period_inactive_qty) AS ly_ending_of_period_inactive_qty,
 SUM(ly_transfer_in_active_cost_amt) AS ly_transfer_in_active_cost_amt,
 SUM(ly_transfer_in_active_qty) AS ly_transfer_in_active_qty,
 SUM(ly_transfer_out_active_cost_amt) AS ly_transfer_out_active_cost_amt,
 SUM(ly_transfer_out_active_qty) AS ly_transfer_out_active_qty,
 SUM(ly_transfer_in_inactive_cost_amt) AS ly_transfer_in_inactive_cost_amt,
 SUM(ly_transfer_in_inactive_qty) AS ly_transfer_in_inactive_qty,
 SUM(ly_transfer_out_inactive_cost_amt) AS ly_transfer_out_inactive_cost_amt,
 SUM(ly_transfer_out_inactive_qty) AS ly_transfer_out_inactive_qty,
 SUM(ly_transfer_in_other_cost_amt) AS ly_transfer_in_other_cost_amt,
 SUM(ly_transfer_in_other_qty) AS ly_transfer_in_other_qty,
 SUM(ly_transfer_out_other_cost_amt) AS ly_transfer_out_other_cost_amt,
 SUM(ly_transfer_out_other_qty) AS ly_transfer_out_other_qty,
 SUM(ly_transfer_in_racking_cost_amt) AS ly_transfer_in_racking_cost_amt,
 SUM(ly_transfer_in_racking_qty) AS ly_transfer_in_racking_qty,
 SUM(ly_transfer_out_racking_cost_amt) AS ly_transfer_out_racking_cost_amt,
 SUM(ly_transfer_out_racking_qty) AS ly_transfer_out_racking_qty,
 SUM(ly_mark_out_of_stock_active_cost_amt) AS ly_mark_out_of_stock_active_cost_amt,
 SUM(ly_mark_out_of_stock_active_qty) AS ly_mark_out_of_stock_active_qty,
 SUM(ly_mark_out_of_stock_inactive_cost_amt) AS ly_mark_out_of_stock_inactive_cost_amt,
 SUM(ly_mark_out_of_stock_inactive_qty) AS ly_mark_out_of_stock_inactive_qty,
 SUM(ly_receipts_active_cost_amt) AS ly_receipts_active_cost_amt,
 SUM(ly_receipts_active_qty) AS ly_receipts_active_qty,
 SUM(ly_receipts_inactive_cost_amt) AS ly_receipts_inactive_cost_amt,
 SUM(ly_receipts_inactive_qty) AS ly_receipts_inactive_qty,
 SUM(ly_rp_receipts_active_cost_amt) AS ly_rp_receipts_active_cost_amt,
 SUM(ly_non_rp_receipts_active_cost_amt) AS ly_non_rp_receipts_active_cost_amt,
 SUM(ly_reclass_in_cost_amt) AS ly_reclass_in_cost_amt,
 SUM(ly_reclass_in_qty) AS ly_reclass_in_qty,
 SUM(ly_reclass_out_cost_amt) AS ly_reclass_out_cost_amt,
 SUM(ly_reclass_out_qty) AS ly_reclass_out_qty,
 SUM(ly_return_to_vendor_active_cost_amt) AS ly_return_to_vendor_active_cost_amt,
 SUM(ly_return_to_vendor_active_qty) AS ly_return_to_vendor_active_qty,
 SUM(ly_return_to_vendor_inactive_cost_amt) AS ly_return_to_vendor_inactive_cost_amt,
 SUM(ly_return_to_vendor_inactive_qty) AS ly_return_to_vendor_inactive_qty,
 SUM(ly_vendor_funds_cost_amt) AS ly_vendor_funds_cost_amt,
 SUM(ly_discount_terms_cost_amt) AS ly_discount_terms_cost_amt,
 SUM(ly_merch_margin_retail_amt) AS ly_merch_margin_retail_amt,
 SUM(ly_shrink_banner_cost_amt) AS ly_shrink_banner_cost_amt,
 SUM(ly_shrink_banner_qty) AS ly_shrink_banner_qty,
 SUM(ly_other_inventory_adj_cost) AS ly_other_inventory_adj_cost,
 SUM(ly_merch_margin_charges_cost) AS ly_merch_margin_charges_cost,
 SUM(lly_beginning_of_period_active_cost_amt) AS lly_beginning_of_period_active_cost_amt,
 SUM(lly_beginning_of_period_active_qty) AS lly_beginning_of_period_active_qty,
 SUM(lly_beginning_of_period_inactive_cost_amt) AS lly_beginning_of_period_inactive_cost_amt,
 SUM(lly_beginning_of_period_inactive_qty) AS lly_beginning_of_period_inactive_qty,
 SUM(lly_ending_of_period_active_cost_amt) AS lly_ending_of_period_active_cost_amt,
 SUM(lly_ending_of_period_active_qty) AS lly_ending_of_period_active_qty,
 SUM(lly_ending_of_period_inactive_cost_amt) AS lly_ending_of_period_inactive_cost_amt,
 SUM(lly_ending_of_period_inactive_qty) AS lly_ending_of_period_inactive_qty,
 SUM(lly_transfer_in_active_cost_amt) AS lly_transfer_in_active_cost_amt,
 SUM(lly_transfer_in_active_qty) AS lly_transfer_in_active_qty,
 SUM(lly_transfer_out_active_cost_amt) AS lly_transfer_out_active_cost_amt,
 SUM(lly_transfer_out_active_qty) AS lly_transfer_out_active_qty,
 SUM(lly_transfer_in_inactive_cost_amt) AS lly_transfer_in_inactive_cost_amt,
 SUM(lly_transfer_in_inactive_qty) AS lly_transfer_in_inactive_qty,
 SUM(lly_transfer_out_inactive_cost_amt) AS lly_transfer_out_inactive_cost_amt,
 SUM(lly_transfer_out_inactive_qty) AS lly_transfer_out_inactive_qty,
 SUM(lly_transfer_in_other_cost_amt) AS lly_transfer_in_other_cost_amt,
 SUM(lly_transfer_in_other_qty) AS lly_transfer_in_other_qty,
 SUM(lly_transfer_out_other_cost_amt) AS lly_transfer_out_other_cost_amt,
 SUM(lly_transfer_out_other_qty) AS lly_transfer_out_other_qty,
 SUM(lly_transfer_in_racking_cost_amt) AS lly_transfer_in_racking_cost_amt,
 SUM(lly_transfer_in_racking_qty) AS lly_transfer_in_racking_qty,
 SUM(lly_transfer_out_racking_cost_amt) AS lly_transfer_out_racking_cost_amt,
 SUM(lly_transfer_out_racking_qty) AS lly_transfer_out_racking_qty,
 SUM(lly_mark_out_of_stock_active_cost_amt) AS lly_mark_out_of_stock_active_cost_amt,
 SUM(lly_mark_out_of_stock_active_qty) AS lly_mark_out_of_stock_active_qty,
 SUM(lly_mark_out_of_stock_inactive_cost_amt) AS lly_mark_out_of_stock_inactive_cost_amt,
 SUM(lly_mark_out_of_stock_inactive_qty) AS lly_mark_out_of_stock_inactive_qty,
 SUM(lly_receipts_active_cost_amt) AS lly_receipts_active_cost_amt,
 SUM(lly_receipts_active_qty) AS lly_receipts_active_qty,
 SUM(lly_receipts_inactive_cost_amt) AS lly_receipts_inactive_cost_amt,
 SUM(lly_receipts_inactive_qty) AS lly_receipts_inactive_qty,
 SUM(lly_rp_receipts_active_cost_amt) AS lly_rp_receipts_active_cost_amt,
 SUM(lly_non_rp_receipts_active_cost_amt) AS lly_non_rp_receipts_active_cost_amt,
 SUM(lly_reclass_in_cost_amt) AS lly_reclass_in_cost_amt,
 SUM(lly_reclass_in_qty) AS lly_reclass_in_qty,
 SUM(lly_reclass_out_cost_amt) AS lly_reclass_out_cost_amt,
 SUM(lly_reclass_out_qty) AS lly_reclass_out_qty,
 SUM(lly_return_to_vendor_active_cost_amt) AS lly_return_to_vendor_active_cost_amt,
 SUM(lly_return_to_vendor_active_qty) AS lly_return_to_vendor_active_qty,
 SUM(lly_return_to_vendor_inactive_cost_amt) AS lly_return_to_vendor_inactive_cost_amt,
 SUM(lly_return_to_vendor_inactive_qty) AS lly_return_to_vendor_inactive_qty,
 SUM(lly_vendor_funds_cost_amt) AS lly_vendor_funds_cost_amt,
 SUM(lly_discount_terms_cost_amt) AS lly_discount_terms_cost_amt,
 SUM(lly_merch_margin_retail_amt) AS lly_merch_margin_retail_amt,
 SUM(lly_shrink_banner_cost_amt) AS lly_shrink_banner_cost_amt,
 SUM(lly_shrink_banner_qty) AS lly_shrink_banner_qty,
 SUM(lly_other_inventory_adj_cost) AS lly_other_inventory_adj_cost,
 SUM(lly_merch_margin_charges_cost) AS lly_merch_margin_charges_cost,
 SUM(ly_trueday_beginning_of_period_active_cost_amt) AS ly_trueday_beginning_of_period_active_cost_amt,
 SUM(ly_trueday_beginning_of_period_active_qty) AS ly_trueday_beginning_of_period_active_qty,
 SUM(ly_trueday_beginning_of_period_inactive_cost_amt) AS ly_trueday_beginning_of_period_inactive_cost_amt,
 SUM(ly_trueday_beginning_of_period_inactive_qty) AS ly_trueday_beginning_of_period_inactive_qty,
 SUM(ly_trueday_ending_of_period_active_cost_amt) AS ly_trueday_ending_of_period_active_cost_amt,
 SUM(ly_trueday_ending_of_period_active_qty) AS ly_trueday_ending_of_period_active_qty,
 SUM(ly_trueday_ending_of_period_inactive_cost_amt) AS ly_trueday_ending_of_period_inactive_cost_amt,
 SUM(ly_trueday_ending_of_period_inactive_qty) AS ly_trueday_ending_of_period_inactive_qty,
 SUM(ly_trueday_transfer_in_active_cost_amt) AS ly_trueday_transfer_in_active_cost_amt,
 SUM(ly_trueday_transfer_in_active_qty) AS ly_trueday_transfer_in_active_qty,
 SUM(ly_trueday_transfer_out_active_cost_amt) AS ly_trueday_transfer_out_active_cost_amt,
 SUM(ly_trueday_transfer_out_active_qty) AS ly_trueday_transfer_out_active_qty,
 SUM(ly_trueday_transfer_in_inactive_cost_amt) AS ly_trueday_transfer_in_inactive_cost_amt,
 SUM(ly_trueday_transfer_in_inactive_qty) AS ly_trueday_transfer_in_inactive_qty,
 SUM(ly_trueday_transfer_out_inactive_cost_amt) AS ly_trueday_transfer_out_inactive_cost_amt,
 SUM(ly_trueday_transfer_out_inactive_qty) AS ly_trueday_transfer_out_inactive_qty,
 SUM(ly_trueday_transfer_in_other_cost_amt) AS ly_trueday_transfer_in_other_cost_amt,
 SUM(ly_trueday_transfer_in_other_qty) AS ly_trueday_transfer_in_other_qty,
 SUM(ly_trueday_transfer_out_other_cost_amt) AS ly_trueday_transfer_out_other_cost_amt,
 SUM(ly_trueday_transfer_out_other_qty) AS ly_trueday_transfer_out_other_qty,
 SUM(ly_trueday_transfer_in_racking_cost_amt) AS ly_trueday_transfer_in_racking_cost_amt,
 SUM(ly_trueday_transfer_in_racking_qty) AS ly_trueday_transfer_in_racking_qty,
 SUM(ly_trueday_transfer_out_racking_cost_amt) AS ly_trueday_transfer_out_racking_cost_amt,
 SUM(ly_trueday_transfer_out_racking_qty) AS ly_trueday_transfer_out_racking_qty,
 SUM(ly_trueday_mark_out_of_stock_active_cost_amt) AS ly_trueday_mark_out_of_stock_active_cost_amt,
 SUM(ly_trueday_mark_out_of_stock_active_qty) AS ly_trueday_mark_out_of_stock_active_qty,
 SUM(ly_trueday_mark_out_of_stock_inactive_cost_amt) AS ly_trueday_mark_out_of_stock_inactive_cost_amt,
 SUM(ly_trueday_mark_out_of_stock_inactive_qty) AS ly_trueday_mark_out_of_stock_inactive_qty,
 SUM(ly_trueday_receipts_active_cost_amt) AS ly_trueday_receipts_active_cost_amt,
 SUM(ly_trueday_receipts_active_qty) AS ly_trueday_receipts_active_qty,
 SUM(ly_trueday_receipts_inactive_cost_amt) AS ly_trueday_receipts_inactive_cost_amt,
 SUM(ly_trueday_receipts_inactive_qty) AS ly_trueday_receipts_inactive_qty,
 SUM(ly_trueday_rp_receipts_active_cost_amt) AS ly_trueday_rp_receipts_active_cost_amt,
 SUM(ly_trueday_non_rp_receipts_active_cost_amt) AS ly_trueday_non_rp_receipts_active_cost_amt,
 SUM(ly_trueday_reclass_in_cost_amt) AS ly_trueday_reclass_in_cost_amt,
 SUM(ly_trueday_reclass_in_qty) AS ly_trueday_reclass_in_qty,
 SUM(ly_trueday_reclass_out_cost_amt) AS ly_trueday_reclass_out_cost_amt,
 SUM(ly_trueday_reclass_out_qty) AS ly_trueday_reclass_out_qty,
 SUM(ly_trueday_return_to_vendor_active_cost_amt) AS ly_trueday_return_to_vendor_active_cost_amt,
 SUM(ly_trueday_return_to_vendor_active_qty) AS ly_trueday_return_to_vendor_active_qty,
 SUM(ly_trueday_return_to_vendor_inactive_cost_amt) AS ly_trueday_return_to_vendor_inactive_cost_amt,
 SUM(ly_trueday_return_to_vendor_inactive_qty) AS ly_trueday_return_to_vendor_inactive_qty,
 SUM(ly_trueday_vendor_funds_cost_amt) AS ly_trueday_vendor_funds_cost_amt,
 SUM(ly_trueday_discount_terms_cost_amt) AS ly_trueday_discount_terms_cost_amt,
 SUM(ly_trueday_merch_margin_retail_amt) AS ly_trueday_merch_margin_retail_amt,
 SUM(ly_trueday_shrink_banner_cost_amt) AS ly_trueday_shrink_banner_cost_amt,
 SUM(ly_trueday_shrink_banner_qty) AS ly_trueday_shrink_banner_qty,
 SUM(ly_trueday_other_inventory_adj_cost) AS ly_trueday_other_inventory_adj_cost,
 SUM(ly_trueday_merch_margin_charges_cost) AS ly_trueday_merch_margin_charges_cost,
 SUM(lly_trueday_beginning_of_period_active_cost_amt) AS lly_trueday_beginning_of_period_active_cost_amt,
 SUM(lly_trueday_beginning_of_period_active_qty) AS lly_trueday_beginning_of_period_active_qty,
 SUM(lly_trueday_beginning_of_period_inactive_cost_amt) AS lly_trueday_beginning_of_period_inactive_cost_amt,
 SUM(lly_trueday_beginning_of_period_inactive_qty) AS lly_trueday_beginning_of_period_inactive_qty,
 SUM(lly_trueday_ending_of_period_active_cost_amt) AS lly_trueday_ending_of_period_active_cost_amt,
 SUM(lly_trueday_ending_of_period_active_qty) AS lly_trueday_ending_of_period_active_qty,
 SUM(lly_trueday_ending_of_period_inactive_cost_amt) AS lly_trueday_ending_of_period_inactive_cost_amt,
 SUM(lly_trueday_ending_of_period_inactive_qty) AS lly_trueday_ending_of_period_inactive_qty,
 SUM(lly_trueday_transfer_in_active_cost_amt) AS lly_trueday_transfer_in_active_cost_amt,
 SUM(lly_trueday_transfer_in_active_qty) AS lly_trueday_transfer_in_active_qty,
 SUM(lly_trueday_transfer_out_active_cost_amt) AS lly_trueday_transfer_out_active_cost_amt,
 SUM(lly_trueday_transfer_out_active_qty) AS lly_trueday_transfer_out_active_qty,
 SUM(lly_trueday_transfer_in_inactive_cost_amt) AS lly_trueday_transfer_in_inactive_cost_amt,
 SUM(lly_trueday_transfer_in_inactive_qty) AS lly_trueday_transfer_in_inactive_qty,
 SUM(lly_trueday_transfer_out_inactive_cost_amt) AS lly_trueday_transfer_out_inactive_cost_amt,
 SUM(lly_trueday_transfer_out_inactive_qty) AS lly_trueday_transfer_out_inactive_qty,
 SUM(lly_trueday_transfer_in_other_cost_amt) AS lly_trueday_transfer_in_other_cost_amt,
 SUM(lly_trueday_transfer_in_other_qty) AS lly_trueday_transfer_in_other_qty,
 SUM(lly_trueday_transfer_out_other_cost_amt) AS lly_trueday_transfer_out_other_cost_amt,
 SUM(lly_trueday_transfer_out_other_qty) AS lly_trueday_transfer_out_other_qty,
 SUM(lly_trueday_transfer_in_racking_cost_amt) AS lly_trueday_transfer_in_racking_cost_amt,
 SUM(lly_trueday_transfer_in_racking_qty) AS lly_trueday_transfer_in_racking_qty,
 SUM(lly_trueday_transfer_out_racking_cost_amt) AS lly_trueday_transfer_out_racking_cost_amt,
 SUM(lly_trueday_transfer_out_racking_qty) AS lly_trueday_transfer_out_racking_qty,
 SUM(lly_trueday_mark_out_of_stock_active_cost_amt) AS lly_trueday_mark_out_of_stock_active_cost_amt,
 SUM(lly_trueday_mark_out_of_stock_active_qty) AS lly_trueday_mark_out_of_stock_active_qty,
 SUM(lly_trueday_mark_out_of_stock_inactive_cost_amt) AS lly_trueday_mark_out_of_stock_inactive_cost_amt,
 SUM(lly_trueday_mark_out_of_stock_inactive_qty) AS lly_trueday_mark_out_of_stock_inactive_qty,
 SUM(lly_trueday_receipts_active_cost_amt) AS lly_trueday_receipts_active_cost_amt,
 SUM(lly_trueday_receipts_active_qty) AS lly_trueday_receipts_active_qty,
 SUM(lly_trueday_receipts_inactive_cost_amt) AS lly_trueday_receipts_inactive_cost_amt,
 SUM(lly_trueday_receipts_inactive_qty) AS lly_trueday_receipts_inactive_qty,
 SUM(lly_trueday_rp_receipts_active_cost_amt) AS lly_trueday_rp_receipts_active_cost_amt,
 SUM(lly_trueday_non_rp_receipts_active_cost_amt) AS lly_trueday_non_rp_receipts_active_cost_amt,
 SUM(lly_trueday_reclass_in_cost_amt) AS lly_trueday_reclass_in_cost_amt,
 SUM(lly_trueday_reclass_in_qty) AS lly_trueday_reclass_in_qty,
 SUM(lly_trueday_reclass_out_cost_amt) AS lly_trueday_reclass_out_cost_amt,
 SUM(lly_trueday_reclass_out_qty) AS lly_trueday_reclass_out_qty,
 SUM(lly_trueday_return_to_vendor_active_cost_amt) AS lly_trueday_return_to_vendor_active_cost_amt,
 SUM(lly_trueday_return_to_vendor_active_qty) AS lly_trueday_return_to_vendor_active_qty,
 SUM(lly_trueday_return_to_vendor_inactive_cost_amt) AS lly_trueday_return_to_vendor_inactive_cost_amt,
 SUM(lly_trueday_return_to_vendor_inactive_qty) AS lly_trueday_return_to_vendor_inactive_qty,
 SUM(lly_trueday_vendor_funds_cost_amt) AS lly_trueday_vendor_funds_cost_amt,
 SUM(lly_trueday_discount_terms_cost_amt) AS lly_trueday_discount_terms_cost_amt,
 SUM(lly_trueday_merch_margin_retail_amt) AS lly_trueday_merch_margin_retail_amt,
 SUM(lly_trueday_shrink_banner_cost_amt) AS lly_trueday_shrink_banner_cost_amt,
 SUM(lly_trueday_shrink_banner_qty) AS lly_trueday_shrink_banner_qty,
 SUM(lly_trueday_other_inventory_adj_cost) AS lly_trueday_other_inventory_adj_cost,
 SUM(lly_trueday_merch_margin_charges_cost) AS lly_trueday_merch_margin_charges_cost,
 MAX(dw_batch_date) AS dw_batch_date,
 CAST(FORMAT_TIMESTAMP('%F %H:%M:%E6S', CURRENT_DATETIME('PST8PDT')) AS DATETIME) AS dw_sys_load_tmstp
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_stg.mfp_cost_plan_actual_banner_country_wrk
GROUP BY dept_num,
 week_num,
 banner_country_num,
 fulfill_type_num;
	
-- ET;

/* SET QUERY_BAND = NONE FOR SESSION;*/

-- ET;
