-- COMMIT TRANSACTION;


DELETE
FROM
  `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_mark_out_of_stock_sku_loc_week_agg_fact AS mos_agg_vw
WHERE
  mos_agg_vw.week_num BETWEEN (
  SELECT
    START_REBUILD_WEEK_NUM
  FROM
    `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_BASE_VWS.MERCH_TRAN_BATCH_VW AS tran_vw1
  WHERE
    LOWER(tran_vw1.INTERFACE_CODE) =LOWER('MERCH_NAP_MOS_DLY'))
  AND (
  SELECT
    END_REBUILD_WEEK_NUM
  FROM
    `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_BASE_VWS.MERCH_TRAN_BATCH_VW AS tran_vw2
  WHERE
    LOWER(tran_vw2.INTERFACE_CODE) =LOWER('MERCH_NAP_MOS_DLY'));


INSERT INTO
  `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_fct.merch_mark_out_of_stock_sku_loc_week_agg_fact
SELECT
  RMS_SKU_NUM,
  STORE_NUM,
  WEEK_NUM,
  TOTAL_COST_CURRENCY_CODE,
  TOTAL_RETAIL_CURRENCY_CODE,
  CAST(RP_IND AS STRING),
  SUM(MOS_ACTIVE_COST) AS MOS_ACTIVE_COST,
  SUM(MOS_ACTIVE_REGULAR_COST) AS MOS_ACTIVE_REGULAR_COST,
  SUM(MOS_ACTIVE_CLEARANCE_COST) AS MOS_ACTIVE_CLEARANCE_COST,
  SUM(MOS_ACTIVE_PROMO_COST) AS MOS_ACTIVE_PROMO_COST,
  CAST(TRUNC(SUM(MOS_ACTIVE_UNITS)) AS INT64) AS MOS_ACTIVE_UNITS,
  CAST(TRUNC(SUM(MOS_ACTIVE_REGULAR_UNITS)) AS INT64)  AS MOS_ACTIVE_REGULAR_UNITS,
  CAST(TRUNC(SUM( MOS_ACTIVE_CLEARANCE_UNITS)) AS INT64)  AS MOS_ACTIVE_CLEARANCE_UNITS,
  CAST(TRUNC(SUM( MOS_ACTIVE_PROMO_UNITS)) AS INT64)  AS MOS_ACTIVE_PROMO_UNITS,
  SUM(MOS_ACTIVE_RETAIL) AS MOS_ACTIVE_RETAIL,
  SUM(MOS_ACTIVE_REGULAR_RETAIL) AS MOS_ACTIVE_REGULAR_RETAIL,
  SUM(MOS_ACTIVE_CLEARANCE_RETAIL) AS MOS_ACTIVE_CLEARANCE_RETAIL,
  SUM(MOS_ACTIVE_PROMO_RETAIL) AS MOS_ACTIVE_PROMO_RETAIL,
  SUM(MOS_INACTIVE_COST) AS MOS_INACTIVE_COST,
  SUM(MOS_INACTIVE_REGULAR_COST) AS MOS_INACTIVE_REGULAR_COST,
  SUM(MOS_INACTIVE_CLEARANCE_COST) AS MOS_INACTIVE_CLEARANCE_COST,
  SUM(MOS_INACTIVE_PROMO_COST) AS MOS_INACTIVE_PROMO_COST,
  CAST(TRUNC(SUM(MOS_INACTIVE_UNITS)) AS INT64)  AS MOS_INACTIVE_UNITS,
  CAST(TRUNC(SUM(MOS_INACTIVE_REGULAR_UNITS)) AS INT64)  AS MOS_INACTIVE_REGULAR_UNITS,
  CAST(TRUNC(SUM(MOS_INACTIVE_CLEARANCE_UNITS)) AS INT64)  AS MOS_INACTIVE_CLEARANCE_UNITS,
  CAST(TRUNC(SUM(MOS_INACTIVE_PROMO_UNITS))AS INT64) AS MOS_INACTIVE_PROMO_UNITS,
  SUM(MOS_INACTIVE_RETAIL) AS MOS_INACTIVE_RETAIL,
  SUM(MOS_INACTIVE_REGULAR_RETAIL) AS MOS_INACTIVE_REGULAR_RETAIL,
  SUM(MOS_INACTIVE_CLEARANCE_RETAIL) AS MOS_INACTIVE_CLEARANCE_RETAIL,
  SUM(MOS_INACTIVE_PROMO_RETAIL) AS MOS_INACTIVE_PROMO_RETAIL,
  SUM(MOS_TOTAL_COST) AS MOS_TOTAL_COST,
  SUM(MOS_TOTAL_REGULAR_COST) AS MOS_TOTAL_REGULAR_COST,
  SUM(MOS_TOTAL_CLEARANCE_COST) AS MOS_TOTAL_CLEARANCE_COST,
  SUM(MOS_TOTAL_PROMOTION_COST) AS MOS_TOTAL_PROMOTION_COST,
  CAST(TRUNC(SUM(MOS_TOTAL_UNITS)) AS INT64) AS MOS_TOTAL_UNITS,
  CAST(TRUNC(SUM(MOS_TOTAL_REGULAR_UNITS)) AS INT64) AS MOS_TOTAL_REGULAR_UNITS,
  CAST(TRUNC(SUM(MOS_TOTAL_CLEARANCE_UNITS)) AS INT64) AS MOS_TOTAL_CLEARANCE_UNITS,
  CAST(TRUNC(SUM(MOS_TOTAL_PROMO_UNITS)) AS INT64) AS MOS_TOTAL_PROMO_UNITS,
  SUM(MOS_TOTAL_RETAIL) AS MOS_TOTAL_RETAIL,
  SUM(MOS_TOTAL_REGULAR_RETAIL) AS MOS_TOTAL_REGULAR_RETAIL,
  SUM(MOS_TOTAL_CLEARANCE_RETAIL) AS MOS_TOTAL_CLEARANCE_RETAIL,
  SUM(MOS_TOTAL_PROMOTION_RETAIL) AS MOS_TOTAL_PROMOTION_RETAIL,
  SUM(SHRINK_ACTIVE_COST) AS SHRINK_ACTIVE_COST,
  SUM(SHRINK_ACTIVE_REGULAR_COST) AS SHRINK_ACTIVE_REGULAR_COST,
  SUM(SHRINK_ACTIVE_CLEARANCE_COST) AS SHRINK_ACTIVE_CLEARANCE_COST,
  SUM(SHRINK_ACTIVE_PROMO_COST) AS SHRINK_ACTIVE_PROMO_COST,
  CAST(TRUNC(SUM(SHRINK_ACTIVE_UNITS)) AS INT64)  AS SHRINK_ACTIVE_UNITS,
  CAST(TRUNC(SUM(SHRINK_ACTIVE_REGULAR_UNITS)) AS INT64)  AS SHRINK_ACTIVE_REGULAR_UNITS,
  CAST(TRUNC(SUM(SHRINK_ACTIVE_CLEARANCE_UNITS)) AS INT64)  AS SHRINK_ACTIVE_CLEARANCE_UNITS,
  CAST(TRUNC(SUM(SHRINK_ACTIVE_PROMO_UNITS)) AS INT64)  AS SHRINK_ACTIVE_PROMO_UNITS,
  SUM(SHRINK_ACTIVE_RETAIL) AS SHRINK_ACTIVE_RETAIL,
  SUM(SHRINK_ACTIVE_REGULAR_RETAIL) AS SHRINK_ACTIVE_REGULAR_RETAIL,
  SUM(SHRINK_ACTIVE_CLEARANCE_RETAIL) AS SHRINK_ACTIVE_CLEARANCE_RETAIL,
  SUM(SHRINK_ACTIVE_PROMO_RETAIL) AS SHRINK_ACTIVE_PROMO_RETAIL,
  SUM(SHRINK_INACTIVE_COST) AS SHRINK_INACTIVE_COST,
  SUM(SHRINK_INACTIVE_REGULAR_COST) AS SHRINK_INACTIVE_REGULAR_COST,
  SUM(SHRINK_INACTIVE_CLEARANCE_COST) AS SHRINK_INACTIVE_CLEARANCE_COST,
  SUM(SHRINK_INACTIVE_PROMO_COST) AS SHRINK_INACTIVE_PROMO_COST,
  CAST(TRUNC(SUM(SHRINK_INACTIVE_UNITS)) AS INT64)  AS SHRINK_INACTIVE_UNITS,
  CAST(TRUNC(SUM(SHRINK_INACTIVE_REGULAR_UNITS)) AS INT64)  AS SHRINK_INACTIVE_REGULAR_UNITS,
  CAST(TRUNC(SUM(SHRINK_INACTIVE_CLEARANCE_UNITS)) AS INT64)  AS SHRINK_INACTIVE_CLEARANCE_UNITS,
  CAST(TRUNC(SUM(SHRINK_INACTIVE_PROMO_UNITS)) AS INT64)  AS SHRINK_INACTIVE_PROMO_UNITS,
  SUM(SHRINK_INACTIVE_RETAIL) AS SHRINK_INACTIVE_RETAIL,
  SUM(SHRINK_INACTIVE_REGULAR_RETAIL) AS SHRINK_INACTIVE_REGULAR_RETAIL,
  SUM(SHRINK_INACTIVE_CLEARANCE_RETAIL) AS SHRINK_INACTIVE_CLEARANCE_RETAIL,
  SUM(SHRINK_INACTIVE_PROMO_RETAIL) AS SHRINK_INACTIVE_PROMO_RETAIL,
  SUM(SHRINK_TOTAL_COST) AS SHRINK_TOTAL_COST,
  SUM(SHRINK_TOTAL_REGULAR_COST) AS SHRINK_TOTAL_REGULAR_COST,
  SUM(SHRINK_TOTAL_CLEARANCE_COST) AS SHRINK_TOTAL_CLEARANCE_COST,
  SUM(SHRINK_TOTAL_PROMO_COST) AS SHRINK_TOTAL_PROMO_COST,
  CAST(TRUNC(SUM(SHRINK_TOTAL_UNITS)) AS INT64) AS SHRINK_TOTAL_UNITS,
  CAST(TRUNC(SUM(SHRINK_TOTAL_REGULAR_UNITS)) AS INT64) AS SHRINK_TOTAL_REGULAR_UNITS,
  CAST(TRUNC(SUM(SHRINK_TOTAL_CLEARANCE_UNITS)) AS INT64) AS SHRINK_TOTAL_CLEARANCE_UNITS,
  CAST(TRUNC(SUM(SHRINK_TOTAL_PROMO_UNITS)) AS INT64) AS SHRINK_TOTAL_PROMO_UNITS,
  SUM(SHRINK_TOTAL_RETAIL) AS SHRINK_TOTAL_RETAIL,
  SUM(SHRINK_TOTAL_REGULAR_RETAIL) AS SHRINK_TOTAL_REGULAR_RETAIL,
  SUM(SHRINK_TOTAL_CLEARANCE_RETAIL) AS SHRINK_TOTAL_CLEARANCE_RETAIL,
  SUM(SHRINK_TOTAL_PROMO_RETAIL) AS SHRINK_TOTAL_PROMO_RETAIL,
  CAST(FORMAT_TIMESTAMP('%F %H:%M:%E6S', CURRENT_DATETIME('PST8PDT')) AS DATETIME) AS  dw_sys_load_tmstp,
  CURRENT_DATE('PST8PDT') AS DW_BATCH_DATE
FROM
  `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_BASE_VWS.MERCH_MARK_OUT_OF_STOCK_COLUMNAR_VW mos
WHERE
  mos.WEEK_NUM BETWEEN(
  SELECT
    START_REBUILD_WEEK_NUM
  FROM
    `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_BASE_VWS.MERCH_TRAN_BATCH_VW AS tran_vw1
  WHERE
    LOWER(tran_vw1.INTERFACE_CODE) =LOWER('MERCH_NAP_MOS_DLY'))
  AND (
  SELECT
    END_REBUILD_WEEK_NUM
  FROM
    `{{params.gcp_project_id}}`.{{params.dbenv}}_NAP_BASE_VWS.MERCH_TRAN_BATCH_VW AS tran_vw2
  WHERE
    LOWER(tran_vw2.INTERFACE_CODE) =LOWER('MERCH_NAP_MOS_DLY'))
GROUP BY
  RMS_SKU_NUM,
  STORE_NUM,
  WEEK_NUM,
  TOTAL_COST_CURRENCY_CODE,
  TOTAL_RETAIL_CURRENCY_CODE,
  RP_IND;


-- COMMIT TRANSACTION;
-- COMMIT TRANSACTION;