SET QUERY_BAND = '
App_ID=APP04070;
DAG_ID=project_mfp_eowsl_kafka_to_td_tpt;
Task_Name=read_eowsl_from_kafka_and_write_to_td_job_4;'
FOR SESSION VOLATILE;

--Source
--Reading Data from  Source Kafka Topic Name=merch-inv-eow-stock-ledger-avro-dev using SQL API CODE
create temporary view temp_eowsl_object_model AS select *,locationId as location_num, productHierarchy.departmentNumber as product_hierarchy_dept_num, productHierarchy.classNumber as product_hierarchy_class_num, productHierarchy.subClassNumber as product_hierarchy_subclass_num, element_at(headers,'LastUpdatedTime') as last_updated_time_in_millis, endOfWeekDate as end_of_week_date from kafka_eowsl_tpt_table;
--Transform Logic
--Extracting Required Column from Kafka (Cache in previous SQL)

create temporary view kafka_eowsl_object_model_avro_extract_columns as
select id as eowsl_num,
correlationId as correlation_num,
eventTime as event_time,
location_num as location_num,
last_updated_time_in_millis as last_updated_time_in_millis,
ledgerBookName as ledger_book_name,
end_of_week_date as end_of_week_date,
product_hierarchy_dept_num as product_hierarchy_dept_num,
product_hierarchy_class_num as product_hierarchy_class_num,
product_hierarchy_subclass_num as product_hierarchy_subclass_num,
physicalYear as fiscal_year,
calendarHalf as calendar_half,
month as month_name,
week as week,
closingStockRetail.currencyCode as closing_stock_retail_currency_code,
closingStockRetail.units as closing_stock_retail_units,
closingStockRetail.nanos as closing_stock_retail_nanos,

closingStockCost.currencyCode as closing_stock_cost_currency_code,
closingStockCost.units as closing_stock_cost_units,
closingStockCost.nanos as closing_stock_cost_nanos,

openStockRetail.currencyCode as open_stock_retail_currency_code,
openStockRetail.units as open_stock_retail_units,
openStockRetail.nanos as open_stock_retail_nanos,

openStockCost.currencyCode as open_stock_cost_currency_code,
openStockCost.units as open_stock_cost_units,
openStockCost.nanos as open_stock_cost_nanos,

stockAdjustmentRetail.currencyCode as stock_adjustment_retail_currency_code,
stockAdjustmentRetail.units as stock_adjustment_retail_units,
stockAdjustmentRetail.nanos as stock_adjustment_retail_nanos,

stockAdjustmentCost.currencyCode as stock_adjustment_cost_currency_code,
stockAdjustmentCost.units as stock_adjustment_cost_units,
stockAdjustmentCost.nanos as stock_adjustment_cost_nanos,

stockTakeAdjustmentRetail.currencyCode as stock_take_adjustment_retail_currency_code,
stockTakeAdjustmentRetail.units as stock_take_adjustment_retail_units,
stockTakeAdjustmentRetail.nanos as stock_take_adjustment_retail_nanos,

stockTakeAdjustmentCost.currencyCode as stock_take_adjustment_cost_currency_code,
stockTakeAdjustmentCost.units as stock_take_adjustment_cost_units,
stockTakeAdjustmentCost.nanos as stock_take_adjustment_cost_nanos,

stockAdjustmentCogsRetail.currencyCode as stock_adjustment_cogs_retail_currency_code,
stockAdjustmentCogsRetail.units as stock_adjustment_cogs_retail_units,
stockAdjustmentCogsRetail.nanos as stock_adjustment_cogs_retail_nanos,

stockAdjustmentCogsCost.currencyCode as stock_adjustment_cogs_cost_currency_code,
stockAdjustmentCogsCost.units as stock_adjustment_cogs_cost_units,
stockAdjustmentCogsCost.nanos as stock_adjustment_cogs_cost_nanos,

purchaseRetail.currencyCode as purchase_retail_currency_code,
purchaseRetail.units as purchase_retail_units,
purchaseRetail.nanos as purchase_retail_nanos,

purchaseCost.currencyCode as purchase_cost_currency_code,
purchaseCost.units as purchase_cost_units,
purchaseCost.nanos as purchase_cost_nanos,

dealIncomePurchases.currencyCode as deal_income_purchases_currency_code,
dealIncomePurchases.units as deal_income_purchases_units,
dealIncomePurchases.nanos as deal_income_purchases_nanos,

freightClaimRetail.currencyCode as freight_claim_retail_currency_code,
freightClaimRetail.units as freight_claim_retail_units,
freightClaimRetail.nanos as freight_claim_retail_nanos,

freightClaimCost.currencyCode as freight_claim_cost_currency_code,
freightClaimCost.units as freight_claim_cost_units,
freightClaimCost.nanos as freight_claim_cost_nanos,

freightCost.currencyCode as freight_cost_currency_code,
freightCost.units as freight_cost_units,
freightCost.nanos as freight_cost_nanos,

profitUpCharges.currencyCode as profit_up_charges_currency_code,
profitUpCharges.units as profit_up_charges_units,
profitUpCharges.nanos as profit_up_charges_nanos,

expenseUpCharges.currencyCode as expense_up_charges_currency_code,
expenseUpCharges.units as expense_up_charges_units,
expenseUpCharges.nanos as expense_up_charges_nanos,

rtvRetail.currencyCode as rtv_retail_currency_code,
rtvRetail.units as rtv_retail_units,
rtvRetail.nanos as rtv_retail_nanos,

rtvCost.currencyCode as rtv_cost_currency_code,
rtvCost.units as rtv_cost_units,
rtvCost.nanos as rtv_cost_nanos,

transferInRetail.currencyCode as transfer_in_retail_currency_code,
transferInRetail.units as transfer_in_retail_units,
transferInRetail.nanos as transfer_in_retail_nanos,

transferInCost.currencyCode as transfer_in_cost_currency_code,
transferInCost.units as transfer_in_cost_units,
transferInCost.nanos as transfer_in_cost_nanos,

transferInBookRetail.currencyCode as transfer_in_book_retail_currency_code,
transferInBookRetail.units as transfer_in_book_retail_units,
transferInBookRetail.nanos as transfer_in_book_retail_nanos,

transferInBookCost.currencyCode as transfer_in_book_cost_currency_code,
transferInBookCost.units as transfer_in_book_cost_units,
transferInBookCost.nanos as transfer_in_book_cost_nanos,

transferOutRetail.currencyCode as transfer_out_retail_currency_code,
transferOutRetail.units as transfer_out_retail_units,
transferOutRetail.nanos as transfer_out_retail_nanos,

transferOutCost.currencyCode as transfer_out_cost_currency_code,
transferOutCost.units as transfer_out_cost_units,
transferOutCost.nanos as transfer_out_cost_nanos,

transferOutBookRetail.currencyCode as transfer_out_book_retail_currency_code,
transferOutBookRetail.units as transfer_out_book_retail_units,
transferOutBookRetail.nanos as transfer_out_book_retail_nanos,

transferOutBookCost.currencyCode as transfer_out_book_cost_currency_code,
transferOutBookCost.units as transfer_out_book_cost_units,
transferOutBookCost.nanos as transfer_out_book_cost_nanos,

intercompanyInRetail.currencyCode as intercompany_in_retail_currency_code,
intercompanyInRetail.units as intercompany_in_retail_units,
intercompanyInRetail.nanos as intercompany_in_retail_nanos,

intercompanyInCost.currencyCode as intercompany_in_cost_currency_code,
intercompanyInCost.units as intercompany_in_cost_units,
intercompanyInCost.nanos as intercompany_in_cost_nanos,

intercompanyOutRetail.currencyCode as intercompany_out_retail_currency_code,
intercompanyOutRetail.units as intercompany_out_retail_units,
intercompanyOutRetail.nanos as intercompany_out_retail_nanos,

intercompanyOutCost.currencyCode as intercompany_out_cost_currency_code,
intercompanyOutCost.units as intercompany_out_cost_units,
intercompanyOutCost.nanos as intercompany_out_cost_nanos,

intercompanyMarkup.currencyCode as intercompany_mark_up_currency_code,
intercompanyMarkup.units as intercompany_mark_up_units,
intercompanyMarkup.nanos as intercompany_mark_up_nanos,

intercompanyMarkdown.currencyCode as intercompany_mark_down_currency_code,
intercompanyMarkdown.units as intercompany_mark_down_units,
intercompanyMarkdown.nanos as intercompany_mark_down_nanos,

interCompanyMargin.currencyCode as intercompany_margin_currency_code,
interCompanyMargin.units as intercompany_margin_units,
interCompanyMargin.nanos as intercompany_margin_nanos,

salesQuantities as sales_quantities,

netSalesRetail.currencyCode as net_sale_retail_currency_code,
netSalesRetail.units as net_sale_retail_units,
netSalesRetail.nanos as net_sale_retail_nanos,

netSalesCost.currencyCode as net_sales_cost_currency_code,
netSalesCost.units as net_sales_cost_units,
netSalesCost.nanos as net_sales_cost_nanos,

netSalesRetailExcludingVat.currencyCode as net_sales_retail_excluding_vat_currency_code,
netSalesRetailExcludingVat.units as net_sales_retail_excluding_vat_units,
netSalesRetailExcludingVat.nanos as net_sales_retail_excluding_vat_nanos,

returnsRetail.currencyCode as returns_retail_currency_code,
returnsRetail.units as returns_retail_units,
returnsRetail.nanos as returns_retail_nanos,

returnsCost.currencyCode as returns_cost_currency_code,
returnsCost.units as returns_cost_units,
returnsCost.nanos as returns_cost_nanos,

netSalesNonInventoryRetail.currencyCode as net_sales_non_inventory_retail_currency_code,
netSalesNonInventoryRetail.units as net_sales_non_inventory_retail_units,
netSalesNonInventoryRetail.nanos as net_sales_non_inventory_retail_nanos,

netSalesNonInventoryCost.currencyCode as net_sales_non_inventory_cost_currency_code,
netSalesNonInventoryCost.units as net_sales_non_inventory_cost_units,
netSalesNonInventoryCost.nanos as net_sales_non_inventory_cost_nanos,

netSalesNonInventoryRetailExcludingVat.currencyCode as net_sales_non_inventory_retail_excluding_vat_currency_code,
netSalesNonInventoryRetailExcludingVat.units as net_sales_non_inventory_retail_excluding_vat_units,
netSalesNonInventoryRetailExcludingVat.nanos as net_sales_non_inventory_retail_excluding_vat_nanos,

markupRetail.currencyCode as markup_retail_currency_code,
markupRetail.units as markup_retail_units,
markupRetail.nanos as markup_retail_nanos,

markupCancelationRetail.currencyCode as markup_cancelation_retail_currency_code,
markupCancelationRetail.units as markup_cancelation_retail_units,
markupCancelationRetail.nanos as markup_cancelation_retail_nanos,

clearMarkdownRetail.currencyCode as clear_markdown_retail_currency_code,
clearMarkdownRetail.units as clear_markdown_retail_units,
clearMarkdownRetail.nanos as clear_markdown_retail_nanos,

permanentMarkdownRetail.currencyCode as permanent_markdown_retail_currency_code,
permanentMarkdownRetail.units as permanent_markdown_retail_units,
permanentMarkdownRetail.nanos as permanent_markdown_retail_nanos,

promotionMarkdownRetail.currencyCode as promotion_markdown_retail_currency_code,
promotionMarkdownRetail.units as promotion_markdown_retail_units,
promotionMarkdownRetail.nanos as promotion_markdown_retail_nanos,

markdownCancelationRetail.currencyCode as markdown_cancelation_retail_currency_code,
markdownCancelationRetail.units as markdown_cancelation_retail_units,
markdownCancelationRetail.nanos as markdown_cancelation_retail_nanos,

franchiseReturnsRetail.currencyCode as franchise_returns_retail_currency_code,
franchiseReturnsRetail.units as franchise_returns_retail_units,
franchiseReturnsRetail.nanos as franchise_returns_retail_nanos,

franchiseReturnsCost.currencyCode as franchise_returns_cost_currency_code,
franchiseReturnsCost.units as franchise_returns_cost_units,
franchiseReturnsCost.nanos as franchise_returns_cost_nanos,

franchiseSalesRetail.currencyCode as franchise_sales_retail_currency_code,
franchiseSalesRetail.units as franchise_sales_retail_units,
franchiseSalesRetail.nanos as franchise_sales_retail_nanos,

franchiseSalesCost.currencyCode as franchise_sales_cost_currency_code,
franchiseSalesCost.units as franchise_sales_cost_units,
franchiseSalesCost.nanos as franchise_sales_cost_nanos,

franchiseMarkupRetail.currencyCode as franchise_markup_retail_currency_code,
franchiseMarkupRetail.units as franchise_markup_retail_units,
franchiseMarkupRetail.nanos as franchise_markup_retail_nanos,

franchiseMarkdownRetail.currencyCode as franchise_markdown_retail_currency_code,
franchiseMarkdownRetail.units as franchise_markdown_retail_units,
franchiseMarkdownRetail.nanos as franchise_markdown_retail_nanos,

employeeDiscountRetail.currencyCode as employee_discount_retail_currency_code,
employeeDiscountRetail.units as employee_discount_retail_units,
employeeDiscountRetail.nanos as employee_discount_retail_nanos,

dealIncomeSales.currencyCode as deal_income_sales_currency_code,
dealIncomeSales.units as deal_income_sales_units,
dealIncomeSales.nanos as deal_income_sales_nanos,

workroomAmount.currencyCode as workroom_amt_currency_code,
workroomAmount.units as workroom_amt_units,
workroomAmount.nanos as workroom_amt_nanos,

cashDiscountAmount.currencyCode as cash_discount_amt_currency_code,
cashDiscountAmount.units as cash_discount_amt_units,
cashDiscountAmount.nanos as cash_discount_amt_nanos,

cumulativeMarkonPercent as cumulative_markon_percent,

shrinkageRetail.currencyCode as shrinkage_retail_currency_code,
shrinkageRetail.units as shrinkage_retail_units,
shrinkageRetail.nanos as shrinkage_retail_nanos,

shrinkageCost.currencyCode as shrinkage_cost_currency_code,
shrinkageCost.units as shrinkage_cost_units,
shrinkageCost.nanos as shrinkage_cost_nanos,

reclassInRetail.currencyCode as reclass_in_retail_currency_code,
reclassInRetail.units as reclass_in_retail_units,
reclassInRetail.nanos as reclass_in_retail_nanos,

reclassInCost.currencyCode as reclass_in_cost_currency_code,
reclassInCost.units as reclass_in_cost_units,
reclassInCost.nanos as reclass_in_cost_nanos,

reclassOutRetail.currencyCode as reclass_out_retail_currency_code,
reclassOutRetail.units as reclass_out_retail_units,
reclassOutRetail.nanos as reclass_out_retail_nanos,

reclassOutCost.currencyCode as reclass_out_cost_currency_code,
reclassOutCost.units as reclass_out_cost_units,
reclassOutCost.nanos as reclass_out_cost_nanos,

grossMarginAmount.currencyCode as gross_margin_amt_currency_code,
grossMarginAmount.units as gross_margin_amt_units,
grossMarginAmount.nanos as gross_margin_amt_nanos,

marginCostVariance.currencyCode as margin_cost_variance_currency_code,
marginCostVariance.units as margin_cost_variance_units,
marginCostVariance.nanos as margin_cost_variance_nanos,

retailCostVariance.currencyCode as retail_cost_variance_currency_code,
retailCostVariance.units as retail_cost_variance_units,
retailCostVariance.nanos as retail_cost_variance_nanos,

costVarianceAmount.currencyCode as cost_variance_amt_currency_code,
costVarianceAmount.units as cost_variance_amt_units,
costVarianceAmount.nanos as cost_variance_amt_nanos,

halfToDateGoodsAvailableForSaleRetail.currencyCode as half_to_date_doods_available_for_sale_retail_currency_code,
halfToDateGoodsAvailableForSaleRetail.units as half_to_date_doods_available_for_sale_retail_units,
halfToDateGoodsAvailableForSaleRetail.nanos as half_to_date_doods_available_for_sale_retail_nanos,

halfToDateGoodsAvailableForSaleCost.currencyCode as half_to_date_goods_available_for_sale_cost_currency_code,
halfToDateGoodsAvailableForSaleCost.units as half_to_date_goods_available_for_sale_cost_units,
halfToDateGoodsAvailableForSaleCost.nanos as half_to_date_goods_available_for_sale_cost_nanos,

receiverCostAdjustmentVariance.currencyCode as receiver_cost_adjustment_variance_currency_code,
receiverCostAdjustmentVariance.units as receiver_cost_adjustment_variance_units,
receiverCostAdjustmentVariance.nanos as receiver_cost_adjustment_variance_nanos,

workOrderActvityUpdateInventoryAmount.currencyCode as workorder_actvity_update_inventory_amt_currency_code,
workOrderActvityUpdateInventoryAmount.units as workorder_actvity_update_inventory_amt_units,
workOrderActvityUpdateInventoryAmount.nanos as workorder_actvity_update_inventory_amt_nanos,

workOrderActvityPostToFinanceAmount.currencyCode as workorder_actvity_post_to_finance_amt_currency_code,
workOrderActvityPostToFinanceAmount.units as workorder_actvity_post_to_finance_amt_units,
workOrderActvityPostToFinanceAmount.nanos as workorder_actvity_post_to_finance_amt_nanos,

restockingFee.currencyCode as restocking_fee_currency_code,
restockingFee.units as restocking_fee_units,
restockingFee.nanos as restocking_fee_nanos,

franchiseRestockingFee.currencyCode as franchise_restocking_fee_currency_code,
franchiseRestockingFee.units as franchise_restocking_fee_units,
franchiseRestockingFee.nanos as franchise_restocking_fee_nanos,

inputVatAmount.currencyCode as input_vat_amt_currency_code,
inputVatAmount.units as input_vat_amt_units,
inputVatAmount.nanos as input_vat_amt_nanos,

outputVatAmount.currencyCode as output_vat_amt_currency_code,
outputVatAmount.units as output_vat_amt_units,
outputVatAmount.nanos as output_vat_amt_nanos,

weightVarianceRetail.currencyCode as weight_variance_retail_currency_code,
weightVarianceRetail.units as weight_variance_retail_units,
weightVarianceRetail.nanos as weight_variance_retail_nanos,

recoverableTaxAmount.currencyCode as recoverable_tax_amt_currency_code,
recoverableTaxAmount.units as recoverable_tax_amt_units,
recoverableTaxAmount.nanos as recoverable_tax_amt_nanos

from temp_eowsl_object_model;
--Sink

---Writing Kafka Data to Teradata using SQL API CODE
--insert overwrite table write_teradata_eowsl_object_tbl select distinct * from kafka_eowsl_object_model_avro_extract_columns;
--insert into table eowsl partition (year, month, day )

insert into table eowsl partition (year, month, day )
SELECT
 EOWSL_NUM,
 CORRELATION_NUM,
 CAST(EVENT_TIME AS STRING),
 LOCATION_NUM,
 LAST_UPDATED_TIME_IN_MILLIS,
 LEDGER_BOOK_NAME,
 CAST(END_OF_WEEK_DATE AS STRING),
 PRODUCT_HIERARCHY_DEPT_NUM,
 PRODUCT_HIERARCHY_CLASS_NUM,
 PRODUCT_HIERARCHY_SUBCLASS_NUM,
 CAST(FISCAL_YEAR AS STRING),
 CALENDAR_HALF,
 MONTH_NAME,
 CAST(WEEK AS STRING),
 CLOSING_STOCK_RETAIL_CURRENCY_CODE,
 CAST(CLOSING_STOCK_RETAIL_UNITS AS STRING),
 CAST(CLOSING_STOCK_RETAIL_NANOS AS STRING),
 CLOSING_STOCK_COST_CURRENCY_CODE,
 CAST(CLOSING_STOCK_COST_UNITS AS STRING),
 CAST(CLOSING_STOCK_COST_NANOS AS STRING),
 OPEN_STOCK_RETAIL_CURRENCY_CODE,
 CAST(OPEN_STOCK_RETAIL_UNITS AS STRING),
 CAST(OPEN_STOCK_RETAIL_NANOS AS STRING),
 OPEN_STOCK_COST_CURRENCY_CODE,
 CAST(OPEN_STOCK_COST_UNITS AS STRING),
 CAST(OPEN_STOCK_COST_NANOS AS STRING),
 STOCK_ADJUSTMENT_RETAIL_CURRENCY_CODE,
 CAST(STOCK_ADJUSTMENT_RETAIL_UNITS AS STRING),
 CAST(STOCK_ADJUSTMENT_RETAIL_NANOS AS STRING),
 STOCK_ADJUSTMENT_COST_CURRENCY_CODE,
 CAST(STOCK_ADJUSTMENT_COST_UNITS AS STRING),
 CAST(STOCK_ADJUSTMENT_COST_NANOS AS STRING),
 STOCK_TAKE_ADJUSTMENT_RETAIL_CURRENCY_CODE,
 CAST(STOCK_TAKE_ADJUSTMENT_RETAIL_UNITS AS STRING),
 CAST(STOCK_TAKE_ADJUSTMENT_RETAIL_NANOS AS STRING),
 STOCK_TAKE_ADJUSTMENT_COST_CURRENCY_CODE,
 CAST(STOCK_TAKE_ADJUSTMENT_COST_UNITS AS STRING),
 CAST(STOCK_TAKE_ADJUSTMENT_COST_NANOS AS STRING),
 STOCK_ADJUSTMENT_COGS_RETAIL_CURRENCY_CODE,
 CAST(STOCK_ADJUSTMENT_COGS_RETAIL_UNITS AS STRING),
 CAST(STOCK_ADJUSTMENT_COGS_RETAIL_NANOS AS STRING),
 STOCK_ADJUSTMENT_COGS_COST_CURRENCY_CODE,
 CAST(STOCK_ADJUSTMENT_COGS_COST_UNITS AS STRING),
 CAST(STOCK_ADJUSTMENT_COGS_COST_NANOS AS STRING),
 PURCHASE_RETAIL_CURRENCY_CODE,
 CAST(PURCHASE_RETAIL_UNITS AS STRING),
 CAST(PURCHASE_RETAIL_NANOS AS STRING),
 PURCHASE_COST_CURRENCY_CODE,
 CAST(PURCHASE_COST_UNITS AS STRING),
 CAST(PURCHASE_COST_NANOS AS STRING),
 DEAL_INCOME_PURCHASES_CURRENCY_CODE,
 CAST(DEAL_INCOME_PURCHASES_UNITS AS STRING),
 CAST(DEAL_INCOME_PURCHASES_NANOS AS STRING),
 FREIGHT_CLAIM_RETAIL_CURRENCY_CODE,
 CAST(FREIGHT_CLAIM_RETAIL_UNITS AS STRING),
 CAST(FREIGHT_CLAIM_RETAIL_NANOS AS STRING),
 FREIGHT_CLAIM_COST_CURRENCY_CODE,
 CAST(FREIGHT_CLAIM_COST_UNITS AS STRING),
 CAST(FREIGHT_CLAIM_COST_NANOS AS STRING),
 FREIGHT_COST_CURRENCY_CODE,
 CAST(FREIGHT_COST_UNITS AS STRING),
 CAST(FREIGHT_COST_NANOS AS STRING),
 PROFIT_UP_CHARGES_CURRENCY_CODE,
 CAST(PROFIT_UP_CHARGES_UNITS AS STRING),
 CAST(PROFIT_UP_CHARGES_NANOS AS STRING),
 EXPENSE_UP_CHARGES_CURRENCY_CODE,
 CAST(EXPENSE_UP_CHARGES_UNITS AS STRING),
 CAST(EXPENSE_UP_CHARGES_NANOS AS STRING),
 RTV_RETAIL_CURRENCY_CODE,
 CAST(RTV_RETAIL_UNITS AS STRING),
 CAST(RTV_RETAIL_NANOS AS STRING),
 RTV_COST_CURRENCY_CODE,
 CAST(RTV_COST_UNITS AS STRING),
 CAST(RTV_COST_NANOS AS STRING),
 TRANSFER_IN_RETAIL_CURRENCY_CODE,
 CAST(TRANSFER_IN_RETAIL_UNITS AS STRING),
 CAST(TRANSFER_IN_RETAIL_NANOS AS STRING),
 TRANSFER_IN_COST_CURRENCY_CODE,
 CAST(TRANSFER_IN_COST_UNITS AS STRING),
 CAST(TRANSFER_IN_COST_NANOS AS STRING),
 TRANSFER_IN_BOOK_RETAIL_CURRENCY_CODE,
 CAST(TRANSFER_IN_BOOK_RETAIL_UNITS AS STRING),
 CAST(TRANSFER_IN_BOOK_RETAIL_NANOS AS STRING),
 TRANSFER_IN_BOOK_COST_CURRENCY_CODE,
 CAST(TRANSFER_IN_BOOK_COST_UNITS AS STRING),
 CAST(TRANSFER_IN_BOOK_COST_NANOS AS STRING),
 TRANSFER_OUT_RETAIL_CURRENCY_CODE,
 CAST(TRANSFER_OUT_RETAIL_UNITS AS STRING),
 CAST(TRANSFER_OUT_RETAIL_NANOS AS STRING),
 TRANSFER_OUT_COST_CURRENCY_CODE,
 CAST(TRANSFER_OUT_COST_UNITS AS STRING),
 CAST(TRANSFER_OUT_COST_NANOS AS STRING),
 TRANSFER_OUT_BOOK_RETAIL_CURRENCY_CODE,
 CAST(TRANSFER_OUT_BOOK_RETAIL_UNITS AS STRING),
 CAST(TRANSFER_OUT_BOOK_RETAIL_NANOS AS STRING),
 TRANSFER_OUT_BOOK_COST_CURRENCY_CODE,
 CAST(TRANSFER_OUT_BOOK_COST_UNITS AS STRING),
 CAST(TRANSFER_OUT_BOOK_COST_NANOS AS STRING),
 INTERCOMPANY_IN_RETAIL_CURRENCY_CODE,
 CAST(INTERCOMPANY_IN_RETAIL_UNITS AS STRING),
 CAST(INTERCOMPANY_IN_RETAIL_NANOS AS STRING),
 INTERCOMPANY_IN_COST_CURRENCY_CODE,
 CAST(INTERCOMPANY_IN_COST_UNITS AS STRING),
 CAST(INTERCOMPANY_IN_COST_NANOS AS STRING),
 INTERCOMPANY_OUT_RETAIL_CURRENCY_CODE,
 CAST(INTERCOMPANY_OUT_RETAIL_UNITS AS STRING),
 CAST(INTERCOMPANY_OUT_RETAIL_NANOS AS STRING),
 INTERCOMPANY_OUT_COST_CURRENCY_CODE,
 CAST(INTERCOMPANY_OUT_COST_UNITS AS STRING),
 CAST(INTERCOMPANY_OUT_COST_NANOS AS STRING),
 INTERCOMPANY_MARK_UP_CURRENCY_CODE,
 CAST(INTERCOMPANY_MARK_UP_UNITS AS STRING),
 CAST(INTERCOMPANY_MARK_UP_NANOS AS STRING),
 INTERCOMPANY_MARK_DOWN_CURRENCY_CODE,
 CAST(INTERCOMPANY_MARK_DOWN_UNITS AS STRING),
 CAST(INTERCOMPANY_MARK_DOWN_NANOS AS STRING),
 INTERCOMPANY_MARGIN_CURRENCY_CODE,
 CAST(INTERCOMPANY_MARGIN_UNITS AS STRING),
 CAST(INTERCOMPANY_MARGIN_NANOS AS STRING),
 CAST(SALES_QUANTITIES AS STRING),
 NET_SALE_RETAIL_CURRENCY_CODE,
 CAST(NET_SALE_RETAIL_UNITS AS STRING),
 CAST(NET_SALE_RETAIL_NANOS AS STRING),
 NET_SALES_COST_CURRENCY_CODE,
 CAST(NET_SALES_COST_UNITS AS STRING),
 CAST(NET_SALES_COST_NANOS AS STRING),
 NET_SALES_RETAIL_EXCLUDING_VAT_CURRENCY_CODE,
 CAST(NET_SALES_RETAIL_EXCLUDING_VAT_UNITS AS STRING),
 CAST(NET_SALES_RETAIL_EXCLUDING_VAT_NANOS AS STRING),
 RETURNS_RETAIL_CURRENCY_CODE,
 CAST(RETURNS_RETAIL_UNITS AS STRING),
 CAST(RETURNS_RETAIL_NANOS AS STRING),
 RETURNS_COST_CURRENCY_CODE,
 CAST(RETURNS_COST_UNITS AS STRING),
 CAST(RETURNS_COST_NANOS AS STRING),
 NET_SALES_NON_INVENTORY_RETAIL_CURRENCY_CODE,
 CAST(NET_SALES_NON_INVENTORY_RETAIL_UNITS AS STRING),
 CAST(NET_SALES_NON_INVENTORY_RETAIL_NANOS AS STRING),
 NET_SALES_NON_INVENTORY_COST_CURRENCY_CODE,
 CAST(NET_SALES_NON_INVENTORY_COST_UNITS AS STRING),
 CAST(NET_SALES_NON_INVENTORY_COST_NANOS AS STRING),
 NET_SALES_NON_INVENTORY_RETAIL_EXCLUDING_VAT_CURRENCY_CODE,
 CAST(NET_SALES_NON_INVENTORY_RETAIL_EXCLUDING_VAT_UNITS AS STRING),
 CAST(NET_SALES_NON_INVENTORY_RETAIL_EXCLUDING_VAT_NANOS AS STRING),
 MARKUP_RETAIL_CURRENCY_CODE,
 CAST(MARKUP_RETAIL_UNITS AS STRING),
 CAST(MARKUP_RETAIL_NANOS AS STRING),
 MARKUP_CANCELATION_RETAIL_CURRENCY_CODE,
 CAST(MARKUP_CANCELATION_RETAIL_UNITS AS STRING),
 CAST(MARKUP_CANCELATION_RETAIL_NANOS AS STRING),
 CLEAR_MARKDOWN_RETAIL_CURRENCY_CODE,
 CAST(CLEAR_MARKDOWN_RETAIL_UNITS AS STRING),
 CAST(CLEAR_MARKDOWN_RETAIL_NANOS AS STRING),
 PERMANENT_MARKDOWN_RETAIL_CURRENCY_CODE,
 CAST(PERMANENT_MARKDOWN_RETAIL_UNITS AS STRING),
 CAST(PERMANENT_MARKDOWN_RETAIL_NANOS AS STRING),
 PROMOTION_MARKDOWN_RETAIL_CURRENCY_CODE,
 CAST(PROMOTION_MARKDOWN_RETAIL_UNITS AS STRING),
 CAST(PROMOTION_MARKDOWN_RETAIL_NANOS AS STRING),
 MARKDOWN_CANCELATION_RETAIL_CURRENCY_CODE,
 CAST(MARKDOWN_CANCELATION_RETAIL_UNITS AS STRING),
 CAST(MARKDOWN_CANCELATION_RETAIL_NANOS AS STRING),
 FRANCHISE_RETURNS_RETAIL_CURRENCY_CODE,
 CAST(FRANCHISE_RETURNS_RETAIL_UNITS AS STRING),
 CAST(FRANCHISE_RETURNS_RETAIL_NANOS AS STRING),
 FRANCHISE_RETURNS_COST_CURRENCY_CODE,
 CAST(FRANCHISE_RETURNS_COST_UNITS AS STRING),
 CAST(FRANCHISE_RETURNS_COST_NANOS AS STRING),
 FRANCHISE_SALES_RETAIL_CURRENCY_CODE,
 CAST(FRANCHISE_SALES_RETAIL_UNITS AS STRING),
 CAST(FRANCHISE_SALES_RETAIL_NANOS AS STRING),
 FRANCHISE_SALES_COST_CURRENCY_CODE,
 CAST(FRANCHISE_SALES_COST_UNITS AS STRING),
 CAST(FRANCHISE_SALES_COST_NANOS AS STRING),
 FRANCHISE_MARKUP_RETAIL_CURRENCY_CODE,
 CAST(FRANCHISE_MARKUP_RETAIL_UNITS AS STRING),
 CAST(FRANCHISE_MARKUP_RETAIL_NANOS AS STRING),
 FRANCHISE_MARKDOWN_RETAIL_CURRENCY_CODE,
 CAST(FRANCHISE_MARKDOWN_RETAIL_UNITS AS STRING),
 CAST(FRANCHISE_MARKDOWN_RETAIL_NANOS AS STRING),
 EMPLOYEE_DISCOUNT_RETAIL_CURRENCY_CODE,
 CAST(EMPLOYEE_DISCOUNT_RETAIL_UNITS AS STRING),
 CAST(EMPLOYEE_DISCOUNT_RETAIL_NANOS AS STRING),
 DEAL_INCOME_SALES_CURRENCY_CODE,
 CAST(DEAL_INCOME_SALES_UNITS AS STRING),
 CAST(DEAL_INCOME_SALES_NANOS AS STRING),
 WORKROOM_AMT_CURRENCY_CODE,
 CAST(WORKROOM_AMT_UNITS AS STRING),
 CAST(WORKROOM_AMT_NANOS AS STRING),
 CASH_DISCOUNT_AMT_CURRENCY_CODE,
 CAST(CASH_DISCOUNT_AMT_UNITS AS STRING),
 CAST(CASH_DISCOUNT_AMT_NANOS AS STRING),
 CAST(CUMULATIVE_MARKON_PERCENT AS STRING),
 SHRINKAGE_RETAIL_CURRENCY_CODE,
 CAST(SHRINKAGE_RETAIL_UNITS AS STRING),
 CAST(SHRINKAGE_RETAIL_NANOS AS STRING),
 SHRINKAGE_COST_CURRENCY_CODE,
 CAST(SHRINKAGE_COST_UNITS AS STRING),
 CAST(SHRINKAGE_COST_NANOS AS STRING),
 RECLASS_IN_RETAIL_CURRENCY_CODE,
 CAST(RECLASS_IN_RETAIL_UNITS AS STRING),
 CAST(RECLASS_IN_RETAIL_NANOS AS STRING),
 RECLASS_IN_COST_CURRENCY_CODE,
 CAST(RECLASS_IN_COST_UNITS AS STRING),
 CAST(RECLASS_IN_COST_NANOS AS STRING),
 RECLASS_OUT_RETAIL_CURRENCY_CODE,
 CAST(RECLASS_OUT_RETAIL_UNITS AS STRING),
 CAST(RECLASS_OUT_RETAIL_NANOS AS STRING),
 RECLASS_OUT_COST_CURRENCY_CODE,
 CAST(RECLASS_OUT_COST_UNITS AS STRING),
 CAST(RECLASS_OUT_COST_NANOS AS STRING),
 GROSS_MARGIN_AMT_CURRENCY_CODE,
 CAST(GROSS_MARGIN_AMT_UNITS AS STRING),
 CAST(GROSS_MARGIN_AMT_NANOS AS STRING),
 MARGIN_COST_VARIANCE_CURRENCY_CODE,
 CAST(MARGIN_COST_VARIANCE_UNITS AS STRING),
 CAST(MARGIN_COST_VARIANCE_NANOS AS STRING),
 RETAIL_COST_VARIANCE_CURRENCY_CODE,
 CAST(RETAIL_COST_VARIANCE_UNITS AS STRING),
 CAST(RETAIL_COST_VARIANCE_NANOS AS STRING),
 COST_VARIANCE_AMT_CURRENCY_CODE,
 CAST(COST_VARIANCE_AMT_UNITS AS STRING),
 CAST(COST_VARIANCE_AMT_NANOS AS STRING),
 HALF_TO_DATE_DOODS_AVAILABLE_FOR_SALE_RETAIL_CURRENCY_CODE,
 CAST(HALF_TO_DATE_DOODS_AVAILABLE_FOR_SALE_RETAIL_UNITS AS STRING),
 CAST(HALF_TO_DATE_DOODS_AVAILABLE_FOR_SALE_RETAIL_NANOS AS STRING),
 HALF_TO_DATE_GOODS_AVAILABLE_FOR_SALE_COST_CURRENCY_CODE,
 CAST(HALF_TO_DATE_GOODS_AVAILABLE_FOR_SALE_COST_UNITS AS STRING),
 CAST(HALF_TO_DATE_GOODS_AVAILABLE_FOR_SALE_COST_NANOS AS STRING),
 RECEIVER_COST_ADJUSTMENT_VARIANCE_CURRENCY_CODE,
 CAST(RECEIVER_COST_ADJUSTMENT_VARIANCE_UNITS AS STRING),
 CAST(RECEIVER_COST_ADJUSTMENT_VARIANCE_NANOS AS STRING),
 WORKORDER_ACTVITY_UPDATE_INVENTORY_AMT_CURRENCY_CODE,
 CAST(WORKORDER_ACTVITY_UPDATE_INVENTORY_AMT_UNITS AS STRING),
 CAST(WORKORDER_ACTVITY_UPDATE_INVENTORY_AMT_NANOS AS STRING),
 WORKORDER_ACTVITY_POST_TO_FINANCE_AMT_CURRENCY_CODE,
 CAST(WORKORDER_ACTVITY_POST_TO_FINANCE_AMT_UNITS AS STRING),
 CAST(WORKORDER_ACTVITY_POST_TO_FINANCE_AMT_NANOS AS STRING),
 RESTOCKING_FEE_CURRENCY_CODE,
 CAST(RESTOCKING_FEE_UNITS AS STRING),
 CAST(RESTOCKING_FEE_NANOS AS STRING),
 FRANCHISE_RESTOCKING_FEE_CURRENCY_CODE,
 CAST(FRANCHISE_RESTOCKING_FEE_UNITS AS STRING),
 CAST(FRANCHISE_RESTOCKING_FEE_NANOS AS STRING),
 INPUT_VAT_AMT_CURRENCY_CODE,
 CAST(INPUT_VAT_AMT_UNITS AS STRING),
 CAST(INPUT_VAT_AMT_NANOS AS STRING),
 OUTPUT_VAT_AMT_CURRENCY_CODE,
 CAST(OUTPUT_VAT_AMT_UNITS AS STRING),
 CAST(OUTPUT_VAT_AMT_NANOS AS STRING),
 WEIGHT_VARIANCE_RETAIL_CURRENCY_CODE,
 CAST(WEIGHT_VARIANCE_RETAIL_UNITS AS STRING),
 CAST(WEIGHT_VARIANCE_RETAIL_NANOS AS STRING),
 RECOVERABLE_TAX_AMT_CURRENCY_CODE,
 CAST(RECOVERABLE_TAX_AMT_UNITS AS STRING),
 CAST(RECOVERABLE_TAX_AMT_NANOS AS STRING),
year( current_date()) as year,
     month( current_date()) as month,
     day( current_date()) as day
FROM (SELECT *, rank() over (PARTITION BY location_num, end_of_week_date, product_hierarchy_dept_num,
product_hierarchy_class_num, product_hierarchy_subclass_num  ORDER BY last_updated_time_in_millis DESC) as
ranking FROM kafka_eowsl_object_model_avro_extract_columns) tmp where ranking == 1 ;

