/*
Purpose:          Creates empty tables in {{environment_schema}} for RP Performance
                            RP PERFORMANCE ROLLUP
Variable(s):     {{environment_schema}} T2DL_DAS_IN_SEASON_MANAGEMENT_REPORTING
				 {{env_suffix}} dev or prod as appropriate
Author:          Jen Latta
Date:			 1/26/24

Date Updated: 2/15/24
Updates: 

	* Add Return R,C
	* Add Receipt U,R,C
	* Add PO Receipt U,R,C
	* Add EOH In Transit R
	* Add Total OO R,C
	* Add OO 0WK U,R,C
	* Add OO 1WK U,R,C
	* Add OO 2WK U,R,C
	* Add OO 3WK U,R,C
	* Add BOH U,R,C
	* Add BOH In Transit U,R,C
	* Add RS Transfer In U,R,C
	* Add RS Transfer Out U,R,C
	* Add Order Pack Size
	* Add NPG Ind
	* Update RP CURRENTLY_ACTIVE_RP_SKUS_DIM to include RS locations

Date Updated: 3/26/24
Updates: 
	* Add Last Week Sales R,C,U
	* Add 4Wk Sales R,C,U
	* Add WTD Sales R,C,U
	* Add EOH Reg/Clr R,C,U

Date Updated:6/20/24
Updates:

	* Add Quantrix Category

*/

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'RP_PERFORMANCE_ROLLUP{env_suffix}', OUT_RETURN_MSG);

CREATE MULTISET TABLE {environment_schema}.RP_PERFORMANCE_ROLLUP{env_suffix}
    ,FALLBACK
	,NO BEFORE JOURNAL 
	,NO AFTER JOURNAL
	,CHECKSUM = DEFAULT 
	,DEFAULT MERGEBLOCKRATIO 
(  
 	  SKU_IDNT VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
	,STORE_NUM VARCHAR(16) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
	,WK_IDNT INTEGER
	,RP_PRODUCT_IND INTEGER
	,RP_STATUS_FLAG VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC 
	,CLASS_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,COLOR_NUM VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
	,COLOR_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,DEPT_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,DIV_DESC VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
	,DIV_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SUBCLASS_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SUBCLASS_CATEGORY VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SDIV_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SIZE_1_NUM VARCHAR(6) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SIZE_2_DESC VARCHAR(30) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SIZE_2_NUM  VARCHAR(6) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SUPPLIER_COLOR VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
	,VPN VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SUPPLIER_SIZE VARCHAR(80) CHARACTER SET UNICODE NOT CASESPECIFIC
	,VPN_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,STYLE_NUM VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,NPG_IND CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC
	,ORDER_PACK_SIZE INTEGER
	,STYLE_GROUP_NUM VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
	,REGN_LABEL  VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
	,CHANNEL_DESC VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,CHANNEL_LABEL VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
	,DISTT_LABEL VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
	,LOC_LABEL VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
	,STORE_STATUS VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,SUPPLIER_NAME VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,VENDOR_LABEL_NAME VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,CLUSTER_CLIMATE VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
	,RETURN_TOTAL_UNITS INTEGER 
	,RETURN_TOTAL_RETL_DOLLARS DECIMAL(38,4) 
	,RETURN_TOTAL_COST DECIMAL(38,4) 
	,NET_SALES_TOTAL_RETL_DOLLARS DECIMAL(38,4) 
	,SALES_4WK_RETL_DOLLARS DECIMAL(38,4)  -- NEW 
	,SALES_LWK_RETL_DOLLARS DECIMAL(38,4)  -- NEW 
	,SALES_WTD_RETL_DOLLARS DECIMAL(38,4)  -- NEW 
    ,NET_SALES_TOTAL_UNITS INTEGER 
    ,SALES_4WK_UNITS INTEGER -- NEW 
    ,SALES_LWK_UNITS INTEGER -- NEW 
    ,SALES_WTD_UNITS INTEGER -- NEW 
	,NET_SALES_TOTAL_COST  DECIMAL(38,4)
	,SALES_4WK_COST_AMT DECIMAL(38,4) -- NEW 
	,SALES_LWK_COST_AMT DECIMAL(38,4) -- NEW 
	,SALES_WTD_COST_AMT DECIMAL(38,4) -- NEW
	,RECEIPT_TOTAL_UNITS INTEGER 
	,RECEIPT_TOTAL_RETL_DOLLARS DECIMAL(38,4) 
	,RECEIPT_TOTAL_COST DECIMAL(38,4) 
	,RECEIPT_TOTAL_PO_UNITS INTEGER 
	,RECEIPT_TOTAL_PO_RETL_DOLLARS DECIMAL(38,4) 
	,RECEIPT_TOTAL_PO_COST DECIMAL(38,4) 
    ,EOH_TOTAL_RETL_DOLLARS DECIMAL(38,4) 
	,EOH_TOTAL_UNITS INTEGER  
	,EOH_TOTAL_COST DECIMAL(38,4)
	,EOH_TOTAL_REG_RETL_DOLLARS DECIMAL(38,4) -- NEW 
	,EOH_TOTAL_REG_UNITS INTEGER -- NEW 
	,EOH_TOTAL_REG_COST DECIMAL(38,4)-- NEW 
	,EOH_TOTAL_CLR_RETL_DOLLARS DECIMAL(38,4) -- NEW 
	,EOH_TOTAL_CLR_UNITS INTEGER -- NEW 
	,EOH_TOTAL_CLR_COST DECIMAL(38,4)-- NEW 
	,EOH_IN_TRNST_TOTAL_UNITS INTEGER 
	,EOH_IN_TRNST_TOTAL_COST DECIMAL(38,4)
	,EOH_IN_TRNST_TOTAL_RETAIL_DOLLARS DECIMAL(38,4)
	,BOH_TOTAL_UNITS INTEGER 
	,BOH_TOTAL_RETAIL_DOLLARS DECIMAL(38,9)
	,BOH_TOTAL_COST_DOLLARS  DECIMAL(38,9)
	,BOH_IN_TRANSIT_TOTAL_UNITS INTEGER 
	,BOH_IN_TRANSIT_TOTAL_COST_DOLLARS DECIMAL(38,9)
	,BOH_IN_TRANSIT_TOTAL_RETAIL_DOLLARS DECIMAL(38,9)
	,RESERVE_STOCK_TRANSFER_IN_RETAIL DECIMAL(32,4)
	,RESERVE_STOCK_TRANSFER_IN_UNITS INTEGER 
	,RESERVE_STOCK_TRANSFER_IN_COST DECIMAL(32,4)
	,RESERVE_STOCK_TRANSFER_OUT_RETAIL DECIMAL(32,4)
	,RESERVE_STOCK_TRANSFER_OUT_UNITS  DECIMAL(32,4)
	,RESERVE_STOCK_TRANSFER_OUT_COST   DECIMAL(32,4)
   	,DEMAND_TOTAL_RETL_DOLLARS DECIMAL(38,4) 
	,DEMAND_TOTAL_UNITS INTEGER
	,ON_ORDER_TOTAL_UNITS INTEGER         
	,ON_ORDER_TOTAL_RETAIL_DOLLARS DECIMAL(38,9)
	,ON_ORDER_TOTAL_COST_DOLLARS  DECIMAL(38,9)
	,ON_ORDER_0WK_UNITS INTEGER 
    ,ON_ORDER_1WK_UNITS INTEGER 
	,ON_ORDER_2WK_UNITS INTEGER 
	,ON_ORDER_3WK_UNITS INTEGER 
	,ON_ORDER_4WK_UNITS INTEGER
	,ON_ORDER_0WK_RETAIL_DOLLARS DECIMAL(38,9)
	,ON_ORDER_1WK_RETAIL_DOLLARS DECIMAL(38,9)
	,ON_ORDER_2WK_RETAIL_DOLLARS DECIMAL(38,9)
	,ON_ORDER_3WK_RETAIL_DOLLARS DECIMAL(38,9)
	,ON_ORDER_4WK_RETAIL_DOLLARS DECIMAL(38,9)
	,ON_ORDER_0WK_COST_DOLLARS DECIMAL(38,9)
	,ON_ORDER_1WK_COST_DOLLARS DECIMAL(38,9)
	,ON_ORDER_2WK_COST_DOLLARS DECIMAL(38,9)
	,ON_ORDER_3WK_COST_DOLLARS DECIMAL(38,9)
	,ON_ORDER_4WK_COST_DOLLARS DECIMAL(38,9)
	,FCST_0WK_DMND_UNITS FLOAT
	,FCST_1WK_DMND_UNITS FLOAT
	,FCST_2WK_DMND_UNITS FLOAT
	,FCST_3WK_DMND_UNITS FLOAT
	,FCST_4WK_DMND_UNITS FLOAT
	,FCST_5WK_DMND_UNITS FLOAT
	,FCST_6WK_DMND_UNITS FLOAT
	,FCST_7WK_DMND_UNITS FLOAT
	,FCST_8WK_DMND_UNITS FLOAT
	,FCST_9WK_DMND_UNITS FLOAT
	,IN_STOCK_IND INTEGER
	,DAYS_IN_STOCK	INTEGER 
	,DW_SYS_LOAD_TMSTP TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
)
PRIMARY INDEX (SKU_IDNT, STORE_NUM ,WK_IDNT);

GRANT SELECT ON {environment_schema}.RP_PERFORMANCE_ROLLUP{env_suffix} TO PUBLIC;

