/*
Name:RP Performance
Project:RP Performance Dashboard
Purpose: Serve as the datasource to the Tableau RP Performance Published Data Source and to the RP Performance/RP Dept Store Callout Dashboard
Variable(s): {{environment_schema}} T2DL_DAS_IN_SEASON_MANAGEMENT_REPORTING
			 {{env_suffix}} dev or prod as appropriate
DAG: merch_main_rp_contribution_9850_MERCH_ANALYTICS_insights 
schedule: 0 16 * * 1-5
Author(s):Jen Latta
Date Created:1/31/24 

Date Updated:2/15/24
Updates: 

	* Add Return R,C
	* Add Receipt U,R,C
	* Add PO Receipt U,R,C
	* Add EOH In Transit R
	* Add Total OO R,C
	* Add OO 0WK U,R,C
	* Add OO 1WK U,R,C
	* Add OO 2WK U,R,C
	* Add OO 3WK U,R,C
	* Add BOH U,R,C
	* Add BOH In Transit U,R,C
	* Add RS Transfer In U,R,C
	* Add RS Transfer Out U,R,C
	* Add Order Pack Size
	* Add NPG Ind
	* Update RP CURRENTLY_ACTIVE_RP_SKUS_DIM to include RS locations
	
Date Updated:3/1/24
Updates: 
	
	* Update RP CURRENTLY_ACTIVE_RP_SKUS_DIM to pull from PRD_NAP_USR_VWS.MERCH_RP_SKU_LOC_DIM_HIST
	* Correct Trailing spaces on concatenated fields
	
	
Date Updated:3/7/24
Updates: 
	
	* Update RP_PERFORMANCE_FACT to cast locations in channel 120 to 808 and cast locations in channel 250 to 828
	
Date Updated:3/26/24
Updates:

	* Add Last Week Sales R,C,U
	* Add 4Wk Sales R,C,U
	* Add WTD Sales R,C,U
	* Add EOH Reg/Clr R,C,U

Date Updated:6/20/24
Updates:

	* Add Quantrix Category

*/

/* Previous day  */

CREATE MULTISET VOLATILE TABLE PREVIOUS_DAY_DIM AS (
	select
		 a.DAY_DATE
		,a.WEEK_IDNT
	    FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM a
		WHERE a.DAY_DATE= (SELECT DAY_DATE FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM WHERE DAY_DATE=CURRENT_DATE-1)
		GROUP BY a.DAY_DATE
		,a.WEEK_IDNT
	)       
	WITH DATA 
	PRIMARY INDEX (DAY_DATE,WEEK_IDNT) 
	ON COMMIT PRESERVE ROWS;
	COLLECT STATS PRIMARY INDEX(DAY_DATE,WEEK_IDNT) ON PREVIOUS_DAY_DIM;


/* Current week as of the previous day + 9 weeks in the future */

CREATE MULTISET VOLATILE TABLE FUTURE_WKS_DIM AS (

	SELECT TOP 10 
				a.WEEK_IDNT
			   ,a.WEEK_END_DAY_DATE
			  , Row_Number() Over(ORDER BY a.WEEK_IDNT ASC) WK_RANK
	    FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM a
		WHERE a.WEEK_IDNT >= (SELECT WEEK_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM WHERE DAY_DATE=CURRENT_DATE-1)
		GROUP BY a.WEEK_IDNT
		,a.WEEK_END_DAY_DATE
		ORDER BY a.WEEK_IDNT ASC
	)       
	WITH DATA 
	PRIMARY INDEX (WEEK_IDNT) 
	ON COMMIT PRESERVE ROWS;
	COLLECT STATS PRIMARY INDEX(WEEK_IDNT) ON FUTURE_WKS_DIM;


/* Past 4 weeks + Current week WTD */

CREATE MULTISET VOLATILE TABLE PAST_WKS_DIM
	AS
	(
 SELECT
	 b.WEEK_IDNT
	,d.DAY_DATE
	,d.DAY_IDNT
	,b.week_rank   
	,d.DAY_NUM_OF_FISCAL_WEEK
	FROM
	(SELECT week_idnt,rank() over(ORDER BY a.WEEK_IDNT) AS week_rank
	FROM 
		(
		SELECT 
			TOP 5 
			a.WEEK_IDNT
		   FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM a
		WHERE a.WEEK_IDNT  <= (SELECT WEEK_IDNT FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM WHERE DAY_DATE=CURRENT_DATE-1)
		GROUP BY a.WEEK_IDNT
		ORDER BY a.WEEK_IDNT DESC
		) a GROUP BY 1 ) b
		INNER JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM d
		ON b.WEEK_IDNT=d.WEEK_IDNT
	    AND d.DAY_DATE < CURRENT_DATE
GROUP BY 1,2,3,4,5
)
	WITH DATA 
	PRIMARY INDEX (WEEK_IDNT,DAY_DATE) 
	ON COMMIT PRESERVE ROWS;

COLLECT STATS PRIMARY INDEX(WEEK_IDNT,DAY_DATE) ON PAST_WKS_DIM;

/* Skus active and on RP as of yesterday */

CREATE MULTISET VOLATILE TABLE CURRENTLY_ACTIVE_RP_SKUS_DIM AS (

  SELECT DISTINCT 
        rp.RMS_SKU_NUM
      , rp.LOCATION_NUM
      , d.WEEK_IDNT
      , RP_IND_FLAG as RP_IND
      , case when RP_ACTIVE_FLAG = 'Y' then 'ACTIVE' else 'INACTIVE' end as RP_STATUS_FLAG
  FROM PRD_NAP_USR_VWS.RP_SKU_LOC_STATUS_VW rp 
  INNER JOIN PREVIOUS_DAY_DIM d
  ON d.DAY_DATE BETWEEN eff_begin_tmstp AND eff_end_tmstp
  INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
  ON s.STORE_NUM=rp.LOCATION_NUM
  WHERE s.STORE_COUNTRY_CODE='US' and RP_IND_FLAG = 'Y'-- AND rms_sku_num = '8228715' AND location_num = 763
)       
WITH DATA 
PRIMARY INDEX (RMS_SKU_NUM,LOCATION_NUM,WEEK_IDNT) 
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,LOCATION_NUM,WEEK_IDNT) ON CURRENTLY_ACTIVE_RP_SKUS_DIM;

CREATE MULTISET VOLATILE TABLE ACTIVE_RP_SKUS_STATUS_DIM AS (

  SELECT DISTINCT 
        rp.RMS_SKU_NUM
      , rp.LOCATION_NUM
      , d.WEEK_IDNT
      , RP_IND_FLAG as RP_IND
      , case when RP_ACTIVE_FLAG = 'Y' then 'ACTIVE' else 'INACTIVE' end as RP_STATUS_FLAG
  FROM PRD_NAP_USR_VWS.RP_SKU_LOC_STATUS_VW rp 
  INNER JOIN PAST_WKS_DIM d
  ON d.DAY_DATE > eff_begin_tmstp AND d.DAY_DATE < eff_end_tmstp
  INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
  ON s.STORE_NUM=rp.LOCATION_NUM
  WHERE s.STORE_COUNTRY_CODE='US' and RP_IND_FLAG = 'Y'-- AND rms_sku_num = '8228715' AND location_num = 763
)       
WITH DATA 
PRIMARY INDEX (RMS_SKU_NUM,LOCATION_NUM,WEEK_IDNT) 
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,LOCATION_NUM,WEEK_IDNT) ON ACTIVE_RP_SKUS_STATUS_DIM;

CREATE MULTISET VOLATILE TABLE CLIMATE_CLUSTER_DIM
AS
(
	SELECT  A.STORE_NUM AS STORE_NUM,
	COALESCE(UPPER(B.PEER_GROUP_DESC),'NA') AS PEER_GROUP_DESC
	FROM PRD_NAP_USR_VWS.STORE_DIM A
	LEFT JOIN (SELECT   STORE_NUM,
                PEER_GROUP_NUM,
                UPPER(PEER_GROUP_DESC) PEER_GROUP_DESC,
                PEER_GROUP_TYPE_CODE
             FROM   PRD_NAP_USR_VWS.STORE_PEER_GROUP_DIM
             WHERE PEER_GROUP_TYPE_CODE IN ('OPC', 'FPC')) B
	ON A.STORE_NUM = B.STORE_NUM )
	WITH DATA 
	PRIMARY INDEX (STORE_NUM) 
	ON COMMIT PRESERVE ROWS;
	COLLECT STATS PRIMARY INDEX(STORE_NUM) ON CLIMATE_CLUSTER_DIM;

/* Forecast Demannd Units- Current week as of the previous day + 9 weeks in the future */

CREATE MULTISET VOLATILE TABLE FORECAST_FACT
	AS
	(
		SELECT DISTINCT
		 p.RMS_SKU_NUM 
		,a.LOCATION_ID 
		,rp.WEEK_IDNT AS WK_IDNT
		,rp.RP_IND
		,rp.RP_STATUS_FLAG
		,SUM(CASE WHEN d.WK_RANK = 1  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_0WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 2  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_1WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 3  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_2WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 4  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_3WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 5  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_4WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 6  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_5WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 7  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_6WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 8  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_7WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 9  THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_8WK_DMND_UNITS
	  	,SUM(CASE WHEN d.WK_RANK = 10 THEN a.INVENTORY_FORECAST_QTY ELSE 0 END) AS  FCST_9WK_DMND_UNITS  
		FROM PRD_NAP_USR_VWS.INVENTORY_APPROVED_WEEKLY_DEPLOYMENT_FORECAST_FACT a
		INNER JOIN PRD_NAP_USR_VWS.PRODUCT_SKU_DIM_VW p
		ON a.SKU_ID=CAST(p.EPM_SKU_NUM AS VARCHAR(20))
		AND p.CHANNEL_COUNTRY='US'
		INNER JOIN FUTURE_WKS_DIM d
		ON a.WEEK_ID = CAST(d.WEEK_IDNT AS CHAR(6))
		INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		ON  rp.RMS_SKU_NUM=p.RMS_SKU_NUM
		AND CAST(rp.LOCATION_NUM AS VARCHAR(16))=a.LOCATION_ID 
		GROUP BY
		p.RMS_SKU_NUM 
		,a.LOCATION_ID 
		,rp.WEEK_IDNT 
		,rp.RP_IND
		,rp.RP_STATUS_FLAG
		
	)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,LOCATION_ID,WK_IDNT)
		ON COMMIT PRESERVE ROWS;
		COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM ,LOCATION_ID,WK_IDNT) ON FORECAST_FACT;		

/* Sales and Returns - skus currently on RP for the past 4 weeks + current WTD */

CREATE MULTISET VOLATILE TABLE SALES_FACT
	AS
	(	
		 SELECT
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND AS RP_IND 
		,status.RP_STATUS_FLAG
		,SUM(a.JWN_RETURNS_TOTAL_UNITS_TY) AS JWN_RETURNS_TOTAL_UNITS_TY 
		,SUM(a.JWN_RETURNS_TOTAL_RETAIL_AMT_TY) AS JWN_RETURNS_TOTAL_RETAIL_AMT_TY 
		,SUM(a.JWN_RETURNS_TOTAL_COST_AMT_TY) AS JWN_RETURNS_TOTAL_COST_AMT_TY 
        ,SUM(a.JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
        ,SUM(CASE WHEN WK_RANK<5 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS SALES_4WK_RETL_DOLLARS   
        ,SUM(CASE WHEN WK_RANK=4 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS SALES_LWK_RETL_DOLLARS   
        ,SUM(CASE WHEN WK_RANK=5 THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS SALES_WTD_RETL_DOLLARS   
        ,SUM(a.JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
        ,SUM(CASE WHEN WK_RANK<5 THEN JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY ELSE 0 END) AS SALES_4WK_UNITS  
        ,SUM(CASE WHEN WK_RANK=4 THEN JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY ELSE 0 END) AS SALES_LWK_UNITS  
        ,SUM(CASE WHEN WK_RANK=5 THEN JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY ELSE 0 END) AS SALES_WTD_UNITS   
		,SUM(a.JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,SUM(CASE WHEN WK_RANK<5 THEN JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY ELSE 0 END) AS SALES_4WK_COST_AMT  
		,SUM(CASE WHEN WK_RANK=4 THEN JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY ELSE 0 END) AS SALES_LWK_COST_AMT   
		,SUM(CASE WHEN WK_RANK=5 THEN JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY ELSE 0 END) AS SALES_WTD_COST_AMT    
		FROM PRD_NAP_USR_VWS.MERCH_JWN_SALE_RETURN_SKU_STORE_WEEK_AGG_FACT a
		INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		ON  a.RMS_SKU_NUM = rp.RMS_SKU_NUM
		AND a.STORE_NUM=rp.LOCATION_NUM
		INNER JOIN ACTIVE_RP_SKUS_STATUS_DIM status
        ON rp.rms_sku_num = status.rms_sku_num
        AND rp.location_num = status.location_num
        AND a.week_num = status.week_idnt
		INNER JOIN (
			SELECT DISTINCT 
			WEEK_IDNT, week_rank AS wk_rank
			FROM PAST_WKS_DIM) w
		ON w.WEEK_IDNT=a.WEEK_NUM
		GROUP BY
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND 
		,status.RP_STATUS_FLAG
	)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
		ON COMMIT PRESERVE ROWS;

COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON SALES_FACT;	
	
	/* Receipts - skus currently on RP for the past 4 weeks + current WTD */
	
	CREATE MULTISET VOLATILE TABLE RECEIPTS_FACT
	AS
	(	
		 SELECT
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND AS RP_IND 
		,status.RP_STATUS_FLAG
		,SUM(a.RECEIPTS_TOTAL_UNITS_TY) AS RECEIPTS_TOTAL_UNITS_TY 
        ,SUM(a.RECEIPTS_TOTAL_RETAIL_AMT_TY) AS RECEIPTS_TOTAL_RETAIL_AMT_TY 
        ,SUM(a.RECEIPTS_TOTAL_COST_AMT_TY) AS RECEIPTS_TOTAL_COST_AMT_TY 
		,SUM(a.RECEIPTS_PO_UNITS_TY) AS RECEIPTS_PO_UNITS_TY 
        ,SUM(a.RECEIPTS_PO_RETAIL_AMT_TY) AS RECEIPTS_PO_RETAIL_AMT_TY 
        ,SUM(a.RECEIPTS_PO_COST_AMT_TY) AS RECEIPTS_PO_COST_AMT_TY 
		FROM PRD_NAP_USR_VWS.MERCH_PORECEIPT_SKU_STORE_WEEK_AGG_FACT a
		INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		ON  a.RMS_SKU_NUM = rp.RMS_SKU_NUM
		AND a.STORE_NUM=rp.LOCATION_NUM
		INNER JOIN ACTIVE_RP_SKUS_STATUS_DIM status
        ON rp.rms_sku_num = status.rms_sku_num
        AND rp.location_num = status.location_num
        AND a.week_num = status.week_idnt
		INNER JOIN (
			SELECT DISTINCT 
			WEEK_IDNT
			FROM PAST_WKS_DIM) w
		ON w.WEEK_IDNT=a.WEEK_NUM
		GROUP BY
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND 
		,status.RP_STATUS_FLAG
	)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
		ON COMMIT PRESERVE ROWS;
		COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON RECEIPTS_FACT;		
	
	/* Inventory - skus currently on RP for the past 4 weeks + current WTD */
	
	CREATE MULTISET VOLATILE TABLE INVENTORY_FACT
	AS
	(	
		 SELECT
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND AS RP_IND 
		,status.RP_STATUS_FLAG
		,SUM(a.INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
        ,SUM(a.INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
		,SUM(a.INVENTORY_EOH_TOTAL_COST_AMT_TY) AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,SUM(a.inventory_eoh_regular_units_ty) AS INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,SUM(a.inventory_eoh_regular_retail_amt_ty) AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY    
		,SUM(a.inventory_eoh_regular_cost_amt_ty) AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
        ,SUM(a.inventory_eoh_clearance_units_ty) AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
        ,SUM(a.inventory_eoh_clearance_retail_amt_ty) AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY  
		,SUM(a.inventory_eoh_clearance_cost_amt_ty) AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY  
        ,SUM(a.INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,SUM(a.INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,SUM(a.INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,SUM(a.INVENTORY_BOH_TOTAL_UNITS_TY) AS INVENTORY_BOH_TOTAL_UNITS_TY
		,SUM(a.INVENTORY_BOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,SUM(a.INVENTORY_BOH_TOTAL_COST_AMT_TY) AS INVENTORY_BOH_TOTAL_COST_AMT_TY
		,SUM(a.INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY)	AS INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,SUM(a.INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,SUM(a.INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		FROM PRD_NAP_USR_VWS.MERCH_INVENTORY_SKU_STORE_WEEK_AGG_FACT a
		INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		ON  a.RMS_SKU_NUM = rp.RMS_SKU_NUM
		AND a.STORE_NUM=rp.LOCATION_NUM
		INNER JOIN ACTIVE_RP_SKUS_STATUS_DIM status
        ON rp.rms_sku_num = status.rms_sku_num
        AND rp.location_num = status.location_num
        AND a.week_num = status.week_idnt
		INNER JOIN (
			SELECT DISTINCT 
			WEEK_IDNT
			FROM PAST_WKS_DIM) w
		ON w.WEEK_IDNT=a.WEEK_NUM
		GROUP BY
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND 
		,status.RP_STATUS_FLAG
	)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
		ON COMMIT PRESERVE ROWS;
	
COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON INVENTORY_FACT;
		
	/* Demand- skus currently on RP for the past 4 weeks + current WTD */
	
		CREATE MULTISET VOLATILE TABLE DEMAND_FACT
	AS
	(	
		 SELECT
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND AS RP_IND 
		,status.RP_STATUS_FLAG
		,SUM(a.JWN_DEMAND_TOTAL_RETAIL_AMT_TY) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,SUM(a.JWN_DEMAND_TOTAL_UNITS_TY) AS JWN_DEMAND_TOTAL_UNITS_TY
		FROM PRD_NAP_USR_VWS.MERCH_JWN_DEMAND_SKU_STORE_WEEK_AGG_FACT a
		INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		ON  a.RMS_SKU_NUM = rp.RMS_SKU_NUM
		AND a.STORE_NUM=rp.LOCATION_NUM
		INNER JOIN ACTIVE_RP_SKUS_STATUS_DIM status
        ON rp.rms_sku_num = status.rms_sku_num
        AND rp.location_num = status.location_num
        AND a.week_num = status.week_idnt
		INNER JOIN (
			SELECT DISTINCT 
			WEEK_IDNT
			FROM PAST_WKS_DIM) w
		ON w.WEEK_IDNT=a.WEEK_NUM
		GROUP BY
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND 
		,status.RP_STATUS_FLAG
	)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
		ON COMMIT PRESERVE ROWS;
		COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON DEMAND_FACT;
	
	
		/* RS- skus currently on RP for the past 4 weeks + current WTD */
	
			CREATE MULTISET VOLATILE TABLE RS_FACT
	AS
	(	
		 SELECT
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND AS RP_IND 
		,status.RP_STATUS_FLAG
		,SUM(a.RESERVESTOCK_TRANSFER_IN_RETAIL) AS RESERVESTOCK_TRANSFER_IN_RETAIL
		,SUM(a.RESERVESTOCK_TRANSFER_IN_UNITS) AS RESERVESTOCK_TRANSFER_IN_UNITS
		,SUM(a.RESERVESTOCK_TRANSFER_IN_COST) AS RESERVESTOCK_TRANSFER_IN_COST
		,SUM(RESERVESTOCK_TRANSFER_OUT_RETAIL) AS RESERVESTOCK_TRANSFER_OUT_RETAIL
		,SUM(RESERVESTOCK_TRANSFER_OUT_UNITS) AS RESERVESTOCK_TRANSFER_OUT_UNITS
		,SUM(RESERVESTOCK_TRANSFER_OUT_COST) AS RESERVESTOCK_TRANSFER_OUT_COST
		FROM PRD_NAP_USR_VWS.MERCH_TRANSFER_SKU_LOC_WEEK_AGG_FACT_VW a
		INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		ON  a.RMS_SKU_NUM = rp.RMS_SKU_NUM
		AND a.STORE_NUM=rp.LOCATION_NUM
		INNER JOIN ACTIVE_RP_SKUS_STATUS_DIM status
        ON rp.rms_sku_num = status.rms_sku_num
        AND rp.location_num = status.location_num
        AND a.week_num = status.week_idnt
		INNER JOIN (
			SELECT DISTINCT 
			WEEK_IDNT
			FROM PAST_WKS_DIM) w
		ON w.WEEK_IDNT=a.WEEK_NUM
		GROUP BY
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,a.WEEK_NUM
		,rp.RP_IND 
		,status.RP_STATUS_FLAG
	)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
		ON COMMIT PRESERVE ROWS;
		COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON RS_FACT;
	

	/* On Order Units- skus currently on RP as of previous day */
	
		CREATE MULTISET VOLATILE TABLE OO_FACT 
	AS
	(
	 	SELECT 
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,rp.WEEK_IDNT AS WEEK_NUM 
		,rp.RP_IND
		,rp.RP_STATUS_FLAG
		,SUM(a.QUANTITY_OPEN) AS ON_ORDER_TOTAL_UNITS 
		,SUM(a.QUANTITY_OPEN*a.ANTICIPATED_RETAIL_AMT) AS ON_ORDER_TOTAL_RETAIL_DOLLARS
		,SUM(a.QUANTITY_OPEN*a.UNIT_COST_AMT) AS ON_ORDER_TOTAL_COST_DOLLARS
		,SUM(CASE WHEN WK_RANK=1 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN ELSE 0 END) AS ON_ORDER_0WK_UNITS
		,SUM(CASE WHEN WK_RANK=2 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN ELSE 0 END) AS ON_ORDER_1WK_UNITS
		,SUM(CASE WHEN WK_RANK=3 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN ELSE 0 END) AS ON_ORDER_2WK_UNITS
		,SUM(CASE WHEN WK_RANK=4 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN ELSE 0 END) AS ON_ORDER_3WK_UNITS
		,SUM(CASE WHEN WK_RANK=5 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN ELSE 0 END) AS ON_ORDER_4WK_UNITS   
		,SUM(CASE WHEN WK_RANK=1 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.ANTICIPATED_RETAIL_AMT ELSE 0 END) AS ON_ORDER_0WK_RETAIL_DOLLARS
		,SUM(CASE WHEN WK_RANK=2 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.ANTICIPATED_RETAIL_AMT ELSE 0 END) AS ON_ORDER_1WK_RETAIL_DOLLARS
		,SUM(CASE WHEN WK_RANK=3 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.ANTICIPATED_RETAIL_AMT ELSE 0 END) AS ON_ORDER_2WK_RETAIL_DOLLARS
		,SUM(CASE WHEN WK_RANK=4 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.ANTICIPATED_RETAIL_AMT ELSE 0 END) AS ON_ORDER_3WK_RETAIL_DOLLARS
		,SUM(CASE WHEN WK_RANK=5 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.ANTICIPATED_RETAIL_AMT ELSE 0 END) AS ON_ORDER_4WK_RETAIL_DOLLARS   
		,SUM(CASE WHEN WK_RANK=1 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.UNIT_COST_AMT ELSE 0 END) AS ON_ORDER_0WK_COST_DOLLARS
		,SUM(CASE WHEN WK_RANK=2 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.UNIT_COST_AMT ELSE 0 END) AS ON_ORDER_1WK_COST_DOLLARS
		,SUM(CASE WHEN WK_RANK=3 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.UNIT_COST_AMT ELSE 0 END) AS ON_ORDER_2WK_COST_DOLLARS
		,SUM(CASE WHEN WK_RANK=4 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.UNIT_COST_AMT ELSE 0 END) AS ON_ORDER_3WK_COST_DOLLARS
		,SUM(CASE WHEN WK_RANK=5 AND OTB_EOW_DATE <= d.WEEK_END_DAY_DATE THEN a.QUANTITY_OPEN*a.UNIT_COST_AMT ELSE 0 END) AS ON_ORDER_4WK_COST_DOLLARS   
		FROM PRD_NAP_USR_VWS.MERCH_ON_ORDER_FACT_VW a
		 LEFT JOIN FUTURE_WKS_DIM d
		 ON a.WEEK_NUM=d.WEEK_IDNT
		 INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
		 ON  rp.RMS_SKU_NUM=a.RMS_SKU_NUM
		 AND rp.LOCATION_NUM=a.STORE_NUM
		 WHERE ORDER_TYPE in ('AUTOMATIC_REORDER','BUYER_REORDER')
		 AND a.QUANTITY_OPEN > 0
	  AND a.FIRST_APPROVAL_DATE IS NOT NULL
      AND (
         -- include closed POs with ship dates in the recent past
         (a.STATUS = 'CLOSED' AND a.END_SHIP_DATE >= (SELECT MAX(WEEK_END_DAY_DATE) FROM PRD_NAP_USR_VWS.DAY_CAL_454_DIM WHERE WEEK_END_DAY_DATE < CURRENT_DATE) - 45)
         -- include POs that aren't closed yet
         OR a.STATUS IN ('APPROVED','WORKSHEET')
      	) 
		 GROUP BY
		 a.RMS_SKU_NUM
		,a.STORE_NUM
		,rp.WEEK_IDNT
		,rp.RP_IND 
		,rp.RP_STATUS_FLAG
		)
		WITH DATA
		PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
		ON COMMIT PRESERVE ROWS;
	
COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON OO_FACT;
	
	
		/* In Stock Indicator and Days in Stock: Past 4 weeks + WTD */
	
CREATE MULTISET VOLATILE TABLE STOCK_STATUS_FACT
	AS
	(
	SELECT
	 x.RMS_SKU_NUM AS RMS_SKU_NUM 
	,x.STORE_NUM AS STORE_NUM
	,x.WEEK_IDNT AS WEEK_NUM
	,x.RP_IND AS RP_IND
	,x.RP_STATUS_FLAG
	,CASE WHEN SUM(x.F_I_IN_STOCK_IND_DAY1
	  	  +x.F_I_IN_STOCK_IND_DAY2
	  	  +x.F_I_IN_STOCK_IND_DAY3
	  	  +x.F_I_IN_STOCK_IND_DAY4
	  	  +x.F_I_IN_STOCK_IND_DAY5
	  	  +x.F_I_IN_STOCK_IND_DAY6
	  	  +x.F_I_IN_STOCK_IND_DAY7)>=1
		  THEN 1
		  ELSE 0 END AS F_I_EOH_IN_STOCK_IND
  	,SUM(x.F_I_IN_STOCK_IND_DAY1
	  	  +x.F_I_IN_STOCK_IND_DAY2
	  	  +x.F_I_IN_STOCK_IND_DAY3
	  	  +x.F_I_IN_STOCK_IND_DAY4
	  	  +x.F_I_IN_STOCK_IND_DAY5
	  	  +x.F_I_IN_STOCK_IND_DAY6
	  	  +x.F_I_IN_STOCK_IND_DAY7)
		  AS DAYS_IN_STOCK
	FROM
	(
		SELECT
 		 s.RMS_SKU_NUM
		,s.STORE_NUM
		,s.WEEK_IDNT
		,s.RP_IND
		,s.RP_STATUS_FLAG
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=1 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY1
				
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=2 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY2
				
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=3 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY3
				
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=4 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY4
				
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=5 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY5
				
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=6 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY6
				
		,CASE WHEN SUM(CASE WHEN DAY_NUM_OF_FISCAL_WEEK=7 THEN s.INVENTORY_EOH_TOTAL_UNITS_TY END) >=1 
				THEN 1 
				ELSE 0 
				END AS F_I_IN_STOCK_IND_DAY7
		FROM 
			(SELECT
		 		 s.RMS_SKU_NUM
				,s.STORE_NUM
				,w.DAY_NUM_OF_FISCAL_WEEK
				,w.WEEK_IDNT
				,s.RP_IND
				,status.RP_STATUS_FLAG
				,SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
			FROM PRD_NAP_USR_VWS.MERCH_TRANSACTION_SKU_STORE_DAY_AGG_FACT s
			INNER JOIN PAST_WKS_DIM w
			ON w.DAY_IDNT=s.DAY_NUM
			INNER JOIN CURRENTLY_ACTIVE_RP_SKUS_DIM rp
			ON  s.RMS_SKU_NUM = rp.RMS_SKU_NUM
			AND s.STORE_NUM=rp.LOCATION_NUM
			AND s.RP_IND='Y'
			INNER JOIN ACTIVE_RP_SKUS_STATUS_DIM status
            ON rp.rms_sku_num = status.rms_sku_num
            AND rp.location_num = status.location_num
            AND w.week_idnt = status.week_idnt
        	GROUP BY 
		 		 s.RMS_SKU_NUM
				,s.STORE_NUM
				,w.DAY_NUM_OF_FISCAL_WEEK
				,w.WEEK_IDNT
				,s.RP_IND
				,status.RP_STATUS_FLAG) s
			GROUP BY
	 			 s.RMS_SKU_NUM
				,s.STORE_NUM
				,s.WEEK_IDNT
				,s.RP_IND
				,s.RP_STATUS_FLAG
				)x
			GROUP BY
		 	 	x.RMS_SKU_NUM
				,x.STORE_NUM
				,x.WEEK_IDNT
				,x.RP_IND
				,x.RP_STATUS_FLAG
	)
	WITH DATA 
	PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM) 
	ON COMMIT PRESERVE ROWS;
	COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON STOCK_STATUS_FACT;
	
	
	
	CREATE MULTISET VOLATILE TABLE RP_PERFORMANCE_FACT AS (
	 SELECT
	 RMS_SKU_NUM
	,STORE_NUM
	,WEEK_NUM
	,RP_IND 
	,RP_STATUS_FLAG
	,SUM(JWN_RETURNS_TOTAL_UNITS_TY) AS JWN_RETURNS_TOTAL_UNITS_TY
	,SUM(JWN_RETURNS_TOTAL_RETAIL_AMT_TY) AS JWN_RETURNS_TOTAL_RETAIL_AMT_TY
	,SUM(JWN_RETURNS_TOTAL_COST_AMT_TY) AS JWN_RETURNS_TOTAL_COST_AMT_TY
	,SUM(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
	,SUM(SALES_4WK_RETL_DOLLARS) AS SALES_4WK_RETL_DOLLARS   
    ,SUM(SALES_LWK_RETL_DOLLARS) AS SALES_LWK_RETL_DOLLARS   
    ,SUM(SALES_WTD_RETL_DOLLARS) AS SALES_WTD_RETL_DOLLARS   
    ,SUM(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
    ,SUM(SALES_4WK_UNITS) AS SALES_4WK_UNITS  
    ,SUM(SALES_LWK_UNITS) AS SALES_LWK_UNITS  
    ,SUM(SALES_WTD_UNITS) AS SALES_WTD_UNITS   
	,SUM(JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
	,SUM(SALES_4WK_COST_AMT) AS SALES_4WK_COST_AMT  
	,SUM(SALES_LWK_COST_AMT) AS SALES_LWK_COST_AMT   
	,SUM(SALES_WTD_COST_AMT) AS SALES_WTD_COST_AMT   
	,SUM(RECEIPTS_TOTAL_UNITS_TY) AS RECEIPTS_TOTAL_UNITS_TY
	,SUM(RECEIPTS_TOTAL_RETAIL_AMT_TY) AS RECEIPTS_TOTAL_RETAIL_AMT_TY 
	,SUM(RECEIPTS_TOTAL_COST_AMT_TY) AS RECEIPTS_TOTAL_COST_AMT_TY 
	,SUM(RECEIPTS_PO_UNITS_TY) AS RECEIPTS_PO_UNITS_TY
	,SUM(RECEIPTS_PO_RETAIL_AMT_TY) AS RECEIPTS_PO_RETAIL_AMT_TY
	,SUM(RECEIPTS_PO_COST_AMT_TY) AS RECEIPTS_PO_COST_AMT_TY
    ,SUM(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
	,SUM(INVENTORY_EOH_TOTAL_UNITS_TY) AS INVENTORY_EOH_TOTAL_UNITS_TY
	,SUM(INVENTORY_EOH_TOTAL_COST_AMT_TY) AS INVENTORY_EOH_TOTAL_COST_AMT_TY
	,SUM(INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY     
	,SUM(INVENTORY_EOH_TOTAL_REG_UNITS_TY) AS INVENTORY_EOH_TOTAL_REG_UNITS_TY     
	,SUM(INVENTORY_EOH_TOTAL_REG_COST_AMT_TY) AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY     
	,sUM(INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY) AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY     
	,SUM(INVENTORY_EOH_TOTAL_CLR_UNITS_TY) AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY     
	,sum(INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY) AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY     
	,SUM(INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
	,SUM(INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
	,SUM(INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
	,SUM(INVENTORY_BOH_TOTAL_UNITS_TY) AS INVENTORY_BOH_TOTAL_UNITS_TY
	,SUM(INVENTORY_BOH_TOTAL_RETAIL_AMT_TY) AS INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
	,SUM(INVENTORY_BOH_TOTAL_COST_AMT_TY) AS INVENTORY_BOH_TOTAL_COST_AMT_TY
	,SUM(INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
	,SUM(INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
	,SUM(INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
	,SUM(RESERVESTOCK_TRANSFER_IN_RETAIL) AS RESERVESTOCK_TRANSFER_IN_RETAIL
	,SUM(RESERVESTOCK_TRANSFER_IN_UNITS) AS RESERVESTOCK_TRANSFER_IN_UNITS
	,SUM(RESERVESTOCK_TRANSFER_IN_COST) AS RESERVESTOCK_TRANSFER_IN_COST
	,SUM(RESERVESTOCK_TRANSFER_OUT_RETAIL) AS RESERVESTOCK_TRANSFER_OUT_RETAIL
	,SUM(RESERVESTOCK_TRANSFER_OUT_UNITS) AS RESERVESTOCK_TRANSFER_OUT_UNITS
	,SUM(RESERVESTOCK_TRANSFER_OUT_COST) AS RESERVESTOCK_TRANSFER_OUT_COST
   	,SUM(JWN_DEMAND_TOTAL_RETAIL_AMT_TY) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
	,SUM(JWN_DEMAND_TOTAL_UNITS_TY) AS JWN_DEMAND_TOTAL_UNITS_TY
	,SUM(ON_ORDER_TOTAL_UNITS) AS ON_ORDER_TOTAL_UNITS
	,SUM(ON_ORDER_TOTAL_RETAIL_DOLLARS) AS ON_ORDER_TOTAL_RETAIL_DOLLARS
	,SUM(ON_ORDER_TOTAL_COST_DOLLARS) AS ON_ORDER_TOTAL_COST_DOLLARS
	,SUM(ON_ORDER_0WK_UNITS) AS ON_ORDER_0WK_UNITS
	,SUM(ON_ORDER_1WK_UNITS) AS ON_ORDER_1WK_UNITS
	,SUM(ON_ORDER_2WK_UNITS) AS ON_ORDER_2WK_UNITS
	,SUM(ON_ORDER_3WK_UNITS) AS ON_ORDER_3WK_UNITS
	,SUM(ON_ORDER_4WK_UNITS) AS ON_ORDER_4WK_UNITS   
	,SUM(ON_ORDER_0WK_RETAIL_DOLLARS) AS ON_ORDER_0WK_RETAIL_DOLLARS
	,SUM(ON_ORDER_1WK_RETAIL_DOLLARS) AS ON_ORDER_1WK_RETAIL_DOLLARS
	,SUM(ON_ORDER_2WK_RETAIL_DOLLARS) AS ON_ORDER_2WK_RETAIL_DOLLARS
	,SUM(ON_ORDER_3WK_RETAIL_DOLLARS) AS ON_ORDER_3WK_RETAIL_DOLLARS
	,SUM(ON_ORDER_4WK_RETAIL_DOLLARS) AS ON_ORDER_4WK_RETAIL_DOLLARS   
	,SUM(ON_ORDER_0WK_COST_DOLLARS) AS ON_ORDER_0WK_COST_DOLLARS
	,SUM(ON_ORDER_1WK_COST_DOLLARS) AS ON_ORDER_1WK_COST_DOLLARS
	,SUM(ON_ORDER_2WK_COST_DOLLARS) AS ON_ORDER_2WK_COST_DOLLARS
	,SUM(ON_ORDER_3WK_COST_DOLLARS) AS ON_ORDER_3WK_COST_DOLLARS
	,SUM(ON_ORDER_4WK_COST_DOLLARS) AS ON_ORDER_4WK_COST_DOLLARS   
	,SUM(FCST_0WK_DMND_UNITS)  AS FCST_0WK_DMND_UNITS
	,SUM(FCST_1WK_DMND_UNITS)  AS FCST_1WK_DMND_UNITS
	,SUM(FCST_2WK_DMND_UNITS)  AS FCST_2WK_DMND_UNITS
	,SUM(FCST_3WK_DMND_UNITS)  AS FCST_3WK_DMND_UNITS
	,SUM(FCST_4WK_DMND_UNITS)  AS FCST_4WK_DMND_UNITS
	,SUM(FCST_5WK_DMND_UNITS)  AS FCST_5WK_DMND_UNITS
	,SUM(FCST_6WK_DMND_UNITS)  AS FCST_6WK_DMND_UNITS
	,SUM(FCST_7WK_DMND_UNITS)  AS FCST_7WK_DMND_UNITS
	,SUM(FCST_8WK_DMND_UNITS)  AS FCST_8WK_DMND_UNITS
	,SUM(FCST_9WK_DMND_UNITS)  AS FCST_9WK_DMND_UNITS
	,MAX(F_I_EOH_IN_STOCK_IND) AS F_I_EOH_IN_STOCK_IND
	,MAX(DAYS_IN_STOCK)		   AS DAYS_IN_STOCK
	--,CASE WHEN week_num = max(week_num) THEN 1 END AS max_week
	
	FROM
	(
		 SELECT
		 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828)
		 ELSE CAST(sf.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND 
		,RP_STATUS_FLAG
		,COALESCE(JWN_RETURNS_TOTAL_UNITS_TY,0) AS JWN_RETURNS_TOTAL_UNITS_TY
		,COALESCE(JWN_RETURNS_TOTAL_RETAIL_AMT_TY,0) AS JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,COALESCE(JWN_RETURNS_TOTAL_COST_AMT_TY,0) AS JWN_RETURNS_TOTAL_COST_AMT_TY
		,COALESCE(JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY,0) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,COALESCE(SALES_4WK_RETL_DOLLARS,0) AS SALES_4WK_RETL_DOLLARS   
		,COALESCE(SALES_LWK_RETL_DOLLARS,0) AS SALES_LWK_RETL_DOLLARS   
		,COALESCE(SALES_WTD_RETL_DOLLARS,0) AS SALES_WTD_RETL_DOLLARS   
      	,COALESCE(JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY,0) AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,COALESCE(SALES_4WK_UNITS,0) AS SALES_4WK_UNITS   
      	,COALESCE(SALES_LWK_UNITS,0) AS SALES_LWK_UNITS   
      	,COALESCE(SALES_WTD_UNITS,0) AS SALES_WTD_UNITS   
		,COALESCE(JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY,0) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,COALESCE(SALES_4WK_COST_AMT,0) AS SALES_4WK_COST_AMT   
		,COALESCE(SALES_LWK_COST_AMT,0) AS SALES_LWK_COST_AMT   
		,COALESCE(SALES_WTD_COST_AMT,0) AS SALES_WTD_COST_AMT   
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
      	,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
   		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
		,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		 FROM SALES_FACT sf
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON sf.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
		 
		 
		 UNION ALL 
		 
		 SELECT
	 	 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(rf.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND 
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT   
		,COALESCE(RECEIPTS_TOTAL_UNITS_TY,0) AS RECEIPTS_TOTAL_UNITS_TY
		,COALESCE(RECEIPTS_TOTAL_RETAIL_AMT_TY ,0) AS RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,COALESCE(RECEIPTS_TOTAL_COST_AMT_TY ,0) AS RECEIPTS_TOTAL_COST_AMT_TY 
		,COALESCE(RECEIPTS_PO_UNITS_TY,0) AS RECEIPTS_PO_UNITS_TY
		,COALESCE(RECEIPTS_PO_RETAIL_AMT_TY,0) AS RECEIPTS_PO_RETAIL_AMT_TY
		,COALESCE(RECEIPTS_PO_COST_AMT_TY,0) AS RECEIPTS_PO_COST_AMT_TY
      	,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
   		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
		,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		 FROM RECEIPTS_FACT rf
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON rf.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
		 
		 UNION ALL 
	
		 SELECT
	 	 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(invf.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND 
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT  
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
      	,COALESCE(INVENTORY_EOH_TOTAL_RETAIL_AMT_TY,0) AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,COALESCE(INVENTORY_EOH_TOTAL_UNITS_TY,0) AS INVENTORY_EOH_TOTAL_UNITS_TY
		,COALESCE(INVENTORY_EOH_TOTAL_COST_AMT_TY,0) AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,COALESCE(INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY,0) AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY     
		,COALESCE(INVENTORY_EOH_TOTAL_REG_UNITS_TY,0) AS INVENTORY_EOH_TOTAL_REG_UNITS_TY     
		,COALESCE(INVENTORY_EOH_TOTAL_REG_COST_AMT_TY,0) AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY     
		,COALESCE(INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY,0) AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY     
		,COALESCE(INVENTORY_EOH_TOTAL_CLR_UNITS_TY,0) AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY     
		,COALESCE(INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY,0) AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY     
		,COALESCE(INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY,0) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,COALESCE(INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY,0) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,COALESCE(INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY,0) AS INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,COALESCE(INVENTORY_BOH_TOTAL_UNITS_TY,0) AS INVENTORY_BOH_TOTAL_UNITS_TY
		,COALESCE(INVENTORY_BOH_TOTAL_RETAIL_AMT_TY,0) AS INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,COALESCE(INVENTORY_BOH_TOTAL_COST_AMT_TY,0) AS INVENTORY_BOH_TOTAL_COST_AMT_TY
		,COALESCE(INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY,0) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,COALESCE(INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY,0) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,COALESCE(INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY,0) AS INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
   		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
		,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		 FROM INVENTORY_FACT invf
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON invf.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
		 
		 
		UNION ALL 
	
		 SELECT
	 	 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(rs.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND 
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY	
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT  
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
        ,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,COALESCE(RESERVESTOCK_TRANSFER_IN_RETAIL,0) AS RESERVESTOCK_TRANSFER_IN_RETAIL
		,COALESCE(RESERVESTOCK_TRANSFER_IN_UNITS,0) AS RESERVESTOCK_TRANSFER_IN_UNITS
		,COALESCE(RESERVESTOCK_TRANSFER_IN_COST,0) AS RESERVESTOCK_TRANSFER_IN_COST
		,COALESCE(RESERVESTOCK_TRANSFER_OUT_RETAIL,0) AS RESERVESTOCK_TRANSFER_OUT_RETAIL
		,COALESCE(RESERVESTOCK_TRANSFER_OUT_UNITS,0) AS RESERVESTOCK_TRANSFER_OUT_UNITS
		,COALESCE(RESERVESTOCK_TRANSFER_OUT_COST,0) AS RESERVESTOCK_TRANSFER_OUT_COST
   		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
	    ,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		 FROM RS_FACT rs
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON rs.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
		 
		 UNION ALL 
	    
		 SELECT
		 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(df.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT  
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
      	,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
		,COALESCE(JWN_DEMAND_TOTAL_RETAIL_AMT_TY,0) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,COALESCE(JWN_DEMAND_TOTAL_UNITS_TY,0) AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
        ,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		 FROM DEMAND_FACT df
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON df.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
		 
		 UNION ALL
		 
		 SELECT
		 RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(ff.LOCATION_ID AS VARCHAR(16)) END AS STORE_NUM
	  	,WK_IDNT AS WEEK_NUM
		,CAST(RP_IND AS CHAR(1)) AS RP_IND
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT  
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
      	,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
		,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,COALESCE(FCST_0WK_DMND_UNITS,0) AS FCST_0WK_DMND_UNITS
	  	,COALESCE(FCST_1WK_DMND_UNITS,0) AS FCST_1WK_DMND_UNITS
	  	,COALESCE(FCST_2WK_DMND_UNITS,0) AS FCST_2WK_DMND_UNITS
	  	,COALESCE(FCST_3WK_DMND_UNITS,0) AS FCST_3WK_DMND_UNITS
	  	,COALESCE(FCST_4WK_DMND_UNITS,0) AS FCST_4WK_DMND_UNITS
	  	,COALESCE(FCST_5WK_DMND_UNITS,0) AS FCST_5WK_DMND_UNITS
	  	,COALESCE(FCST_6WK_DMND_UNITS,0) AS FCST_6WK_DMND_UNITS
	  	,COALESCE(FCST_7WK_DMND_UNITS,0) AS FCST_7WK_DMND_UNITS
	  	,COALESCE(FCST_8WK_DMND_UNITS,0) AS FCST_8WK_DMND_UNITS
	  	,COALESCE(FCST_9WK_DMND_UNITS,0) AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		FROM FORECAST_FACT ff
		INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		ON ff.LOCATION_ID=CAST(s.STORE_NUM AS VARCHAR(16))
		
		UNION ALL
		
	     SELECT
	 	 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(oof.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND 
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT  
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
      	,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,COALESCE(ON_ORDER_TOTAL_UNITS,0) AS ON_ORDER_TOTAL_UNITS
		,COALESCE(ON_ORDER_TOTAL_RETAIL_DOLLARS,0) AS ON_ORDER_TOTAL_RETAIL_DOLLARS
		,COALESCE(ON_ORDER_TOTAL_COST_DOLLARS,0) AS ON_ORDER_TOTAL_COST_DOLLARS
		,COALESCE(ON_ORDER_0WK_UNITS,0) AS ON_ORDER_0WK_UNITS
		,COALESCE(ON_ORDER_1WK_UNITS,0) AS ON_ORDER_1WK_UNITS
		,COALESCE(ON_ORDER_2WK_UNITS,0) AS ON_ORDER_2WK_UNITS
		,COALESCE(ON_ORDER_3WK_UNITS,0) AS ON_ORDER_3WK_UNITS
		,COALESCE(ON_ORDER_4WK_UNITS,0) AS ON_ORDER_4WK_UNITS   
		,COALESCE(ON_ORDER_0WK_RETAIL_DOLLARS,0) AS ON_ORDER_0WK_RETAIL_DOLLARS
		,COALESCE(ON_ORDER_1WK_RETAIL_DOLLARS,0) AS ON_ORDER_1WK_RETAIL_DOLLARS
		,COALESCE(ON_ORDER_2WK_RETAIL_DOLLARS,0) AS ON_ORDER_2WK_RETAIL_DOLLARS
		,COALESCE(ON_ORDER_3WK_RETAIL_DOLLARS,0) AS ON_ORDER_3WK_RETAIL_DOLLARS
		,COALESCE(ON_ORDER_4WK_RETAIL_DOLLARS,0) AS ON_ORDER_4WK_RETAIL_DOLLARS   
		,COALESCE(ON_ORDER_0WK_COST_DOLLARS,0) AS ON_ORDER_0WK_COST_DOLLARS
		,COALESCE(ON_ORDER_1WK_COST_DOLLARS,0) AS ON_ORDER_1WK_COST_DOLLARS
		,COALESCE(ON_ORDER_2WK_COST_DOLLARS,0) AS ON_ORDER_2WK_COST_DOLLARS
		,COALESCE(ON_ORDER_3WK_COST_DOLLARS,0) AS ON_ORDER_3WK_COST_DOLLARS
		,COALESCE(ON_ORDER_4WK_COST_DOLLARS,0) AS ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,CAST(0 AS INTEGER) AS F_I_EOH_IN_STOCK_IND
		,CAST(0 AS INTEGER) AS DAYS_IN_STOCK
		 FROM OO_FACT oof
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON oof.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
		 
		 UNION ALL
		 
		 SELECT
	 	 CAST(RMS_SKU_NUM AS VARCHAR(20)) AS RMS_SKU_NUM
		,CASE WHEN s.CHANNEL_NUM=120 THEN TRIM(808)  
		 WHEN s.CHANNEL_NUM=250 THEN TRIM(828) 
		 ELSE CAST(sf.STORE_NUM AS VARCHAR(16)) END AS STORE_NUM
		,WEEK_NUM
		,RP_IND 
		,RP_STATUS_FLAG
		,CAST(0 AS INTEGER) AS JWN_RETURNS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  JWN_RETURNS_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS  SALES_4WK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_RETL_DOLLARS   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_RETL_DOLLARS   
      	,CAST(0 AS INTEGER)  AS JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY
      	,CAST(0 AS INTEGER)  AS SALES_4WK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_LWK_UNITS   
      	,CAST(0 AS INTEGER)  AS SALES_WTD_UNITS   
		,CAST(0 AS DECIMAL(38,4)) AS JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4)) AS SALES_4WK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_LWK_COST_AMT   
		,CAST(0 AS DECIMAL(38,4)) AS SALES_WTD_COST_AMT  
		,CAST(0 AS Integer) AS  RECEIPTS_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_RETAIL_AMT_TY 
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_TOTAL_COST_AMT_TY 
		,CAST(0 AS Integer) AS  RECEIPTS_PO_UNITS_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  RECEIPTS_PO_COST_AMT_TY
      	,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_COST_AMT_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS  INVENTORY_EOH_TOTAL_REG_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_REG_COST_AMT_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_TOTAL_CLR_UNITS_TY   
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY   
		,CAST(0 AS INTEGER)  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS DECIMAL(38,4))  AS INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,4)) AS  INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_TOTAL_COST_AMT_TY
		,CAST(0 AS Integer) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY
		,CAST(0 AS Decimal(38,9)) AS  INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_RETAIL
		,CAST(0 AS Integer) AS  RESERVESTOCK_TRANSFER_IN_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_IN_COST
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_RETAIL
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_UNITS
		,CAST(0 AS Decimal(32,4)) AS  RESERVESTOCK_TRANSFER_OUT_COST
		,CAST(0 AS DECIMAL(38,4)) AS JWN_DEMAND_TOTAL_RETAIL_AMT_TY
		,CAST(0 AS INTEGER)  AS JWN_DEMAND_TOTAL_UNITS_TY
		,CAST(0 AS Integer) AS  ON_ORDER_TOTAL_UNITS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_TOTAL_COST_DOLLARS
		,CAST(0 AS Integer) AS  ON_ORDER_0WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_1WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_2WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_3WK_UNITS
		,CAST(0 AS Integer) AS  ON_ORDER_4WK_UNITS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_RETAIL_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_RETAIL_DOLLARS   
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_0WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_1WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_2WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_3WK_COST_DOLLARS
		,CAST(0 AS Decimal(38,9)) AS  ON_ORDER_4WK_COST_DOLLARS   
		,CAST(0 AS FLOAT)  AS FCST_0WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_1WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_2WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_3WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_4WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_5WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_6WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_7WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_8WK_DMND_UNITS
		,CAST(0 AS FLOAT)  AS FCST_9WK_DMND_UNITS
		,COALESCE(F_I_EOH_IN_STOCK_IND,0) AS F_I_EOH_IN_STOCK_IND
		,COALESCE(DAYS_IN_STOCK,0) AS DAYS_IN_STOCK
		 FROM STOCK_STATUS_FACT sf
		 INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
		 ON sf.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
			) factvw
		GROUP BY
		RMS_SKU_NUM
	   ,STORE_NUM
	   ,WEEK_NUM
	   ,RP_IND 
	   ,RP_STATUS_FLAG
		)
	
	WITH DATA
	PRIMARY INDEX (RMS_SKU_NUM,STORE_NUM,WEEK_NUM)
	ON COMMIT PRESERVE ROWS;

COLLECT STATS PRIMARY INDEX(RMS_SKU_NUM,STORE_NUM,WEEK_NUM) ON RP_PERFORMANCE_FACT;
	
CREATE MULTISET VOLATILE TABLE RP_PERFORMANCE_FACT_DIM AS (
	 
	 SELECT DISTINCT 
	 f.RMS_SKU_NUM AS SKU_IDNT
	,f.STORE_NUM AS STORE_NUM
	,f.WEEK_NUM AS WK_IDNT
	,CASE WHEN f.RP_IND='Y' THEN 1
	 WHEN f.RP_IND='N' THEN 0
	 ELSE NULL END AS  RP_PRODUCT_IND
	,RP_STATUS_FLAG
	,TRIM(CONCAT(p.CLASS_NUM,', ',p.CLASS_DESC)) AS CLASS_LABEL
	,TRIM(COALESCE(p.COLOR_NUM, p.SUPP_COLOR)) AS COLOR_NUM
	,TRIM(CONCAT(p.COLOR_NUM,', ',p.SUPP_COLOR)) AS COLOR_LABEL
	,TRIM(CONCAT(p.DEPT_NUM,', ',p.DEPT_DESC)) AS DEPT_LABEL
	,p.DIV_DESC AS DIV_DESC
	,TRIM(CONCAT(p.DIV_NUM,', ',p.DIV_DESC)) AS DIV_LABEL
	,TRIM(CONCAT(p.SBCLASS_NUM,', ',p.SBCLASS_DESC)) AS SUBCLASS_LABEL
	,sbclass.SBCLASS_CATEGORY AS SUBCLASS_CATEGORY
	,TRIM(CONCAT(p.GRP_NUM,', ',p.GRP_DESC)) AS SDIV_LABEL
	,p.SIZE_1_NUM AS SIZE_1_NUM
	,p.SIZE_2_DESC AS SIZE_2_DESC
	,p.SIZE_2_NUM AS SIZE_2_NUM
	,p.SUPP_COLOR AS SUPPLIER_COLOR
	,p.SUPP_PART_NUM   AS VPN
	,p.SUPP_SIZE  AS SUPPLIER_SIZE
	,TRIM(CONCAT(p.SUPP_PART_NUM,', ',p.STYLE_DESC)) AS VPN_LABEL
	,p.RMS_STYLE_NUM AS STYLE_NUM
	,p.STYLE_GROUP_NUM AS STYLE_GROUP_NUM
	,p.NPG_IND 
	,p.ORDER_QUANTITY_MULTIPLE AS ORDER_PACK_SIZE
	,TRIM(CONCAT(s.SUBGROUP_NUM,', ',s.SUBGROUP_DESC)) AS REGN_LABEL 
	,s.CHANNEL_DESC AS CHANNEL_DESC
	,TRIM(CONCAT(s.CHANNEL_NUM,', ',s.CHANNEL_DESC)) AS CHANNEL_LABEL
	,TRIM(CONCAT(s.REGION_NUM,', ',s.REGION_DESC)) AS DISTT_LABEL
	,TRIM(CONCAT(s.STORE_NUM,', ',s.STORE_SHORT_NAME)) AS LOC_LABEL
	,s.COMP_STATUS_DESC AS STORE_STATUS
	,v.VENDOR_NAME AS SUPPLIER_NAME
	,psd.VENDOR_LABEL_NAME
	,c.PEER_GROUP_DESC AS CLUSTER_CLIMATE
	,JWN_RETURNS_TOTAL_UNITS_TY	AS RETURN_TOTAL_UNITS
	,JWN_RETURNS_TOTAL_RETAIL_AMT_TY AS RETURN_TOTAL_RETL_DOLLARS
	,JWN_RETURNS_TOTAL_COST_AMT_TY AS RETURN_TOTAL_COST
	,JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY AS NET_SALES_TOTAL_RETL_DOLLARS 
	,SALES_4WK_RETL_DOLLARS   
	,SALES_LWK_RETL_DOLLARS   
	,SALES_WTD_RETL_DOLLARS   
    ,JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY  AS NET_SALES_TOTAL_UNITS
    ,SALES_4WK_UNITS   
    ,SALES_LWK_UNITS   
    ,SALES_WTD_UNITS   
	,JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY AS NET_SALES_TOTAL_COST
	,SALES_4WK_COST_AMT   
	,SALES_LWK_COST_AMT   
	,SALES_WTD_COST_AMT  
	,RECEIPTS_TOTAL_UNITS_TY AS RECEIPT_TOTAL_UNITS
	,RECEIPTS_TOTAL_RETAIL_AMT_TY  AS RECEIPT_TOTAL_RETL_DOLLARS
	,RECEIPTS_TOTAL_COST_AMT_TY  AS RECEIPT_TOTAL_COST
	,RECEIPTS_PO_UNITS_TY AS RECEIPT_TOTAL_PO_UNITS
	,RECEIPTS_PO_RETAIL_AMT_TY AS RECEIPT_TOTAL_PO_RETL_DOLLARS
	,RECEIPTS_PO_COST_AMT_TY AS RECEIPT_TOTAL_PO_COST
    ,INVENTORY_EOH_TOTAL_RETAIL_AMT_TY AS EOH_TOTAL_RETL_DOLLARS
	,INVENTORY_EOH_TOTAL_UNITS_TY AS EOH_TOTAL_UNITS
	,INVENTORY_EOH_TOTAL_COST_AMT_TY AS EOH_TOTAL_COST
	,INVENTORY_EOH_TOTAL_REG_RETAIL_AMT_TY AS EOH_TOTAL_REG_RETL_DOLLARS   
	,INVENTORY_EOH_TOTAL_REG_UNITS_TY AS EOH_TOTAL_REG_UNITS   
	,INVENTORY_EOH_TOTAL_REG_COST_AMT_TY AS EOH_TOTAL_REG_COST   
	,INVENTORY_EOH_TOTAL_CLR_RETAIL_AMT_TY AS EOH_TOTAL_CLR_RETL_DOLLARS   
	,INVENTORY_EOH_TOTAL_CLR_UNITS_TY AS EOH_TOTAL_CLR_UNITS   
	,INVENTORY_EOH_TOTAL_CLR_COST_AMT_TY AS EOH_TOTAL_CLR_COST   
	,INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY AS EOH_IN_TRNST_TOTAL_UNITS
	,INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY AS EOH_IN_TRNST_TOTAL_COST
	,INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY AS EOH_IN_TRNST_TOTAL_RETAIL_DOLLARS
	,INVENTORY_BOH_TOTAL_UNITS_TY AS BOH_TOTAL_UNITS
	,INVENTORY_BOH_TOTAL_RETAIL_AMT_TY AS BOH_TOTAL_RETAIL_DOLLARS
	,INVENTORY_BOH_TOTAL_COST_AMT_TY AS BOH_TOTAL_COST_DOLLARS
	,INVENTORY_BOH_IN_TRANSIT_TOTAL_UNITS_TY AS BOH_IN_TRANSIT_TOTAL_UNITS
	,INVENTORY_BOH_IN_TRANSIT_TOTAL_COST_AMT_TY AS BOH_IN_TRANSIT_TOTAL_COST_DOLLARS
	,INVENTORY_BOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY AS BOH_IN_TRANSIT_TOTAL_RETAIL_DOLLARS
	,RESERVESTOCK_TRANSFER_IN_RETAIL AS RESERVE_STOCK_TRANSFER_IN_RETAIL
	,RESERVESTOCK_TRANSFER_IN_UNITS AS RESERVE_STOCK_TRANSFER_IN_UNITS
	,RESERVESTOCK_TRANSFER_IN_COST AS RESERVE_STOCK_TRANSFER_IN_COST
	,RESERVESTOCK_TRANSFER_OUT_RETAIL AS RESERVE_STOCK_TRANSFER_OUT_RETAIL
	,RESERVESTOCK_TRANSFER_OUT_UNITS AS RESERVE_STOCK_TRANSFER_OUT_UNITS
	,RESERVESTOCK_TRANSFER_OUT_COST AS RESERVE_STOCK_TRANSFER_OUT_COST
   	,JWN_DEMAND_TOTAL_RETAIL_AMT_TY AS DEMAND_TOTAL_RETL_DOLLARS 
	,JWN_DEMAND_TOTAL_UNITS_TY AS DEMAND_TOTAL_UNITS
	,ON_ORDER_TOTAL_UNITS AS ON_ORDER_TOTAL_UNITS
	,ON_ORDER_TOTAL_RETAIL_DOLLARS AS ON_ORDER_TOTAL_RETAIL_DOLLARS
	,ON_ORDER_TOTAL_COST_DOLLARS AS ON_ORDER_TOTAL_COST_DOLLARS
	,ON_ORDER_0WK_UNITS AS ON_ORDER_0WK_UNITS
	,ON_ORDER_1WK_UNITS AS ON_ORDER_1WK_UNITS
	,ON_ORDER_2WK_UNITS AS ON_ORDER_2WK_UNITS
	,ON_ORDER_3WK_UNITS AS ON_ORDER_3WK_UNITS
	,ON_ORDER_4WK_UNITS AS ON_ORDER_4WK_UNITS  
	,ON_ORDER_0WK_RETAIL_DOLLARS AS ON_ORDER_0WK_RETAIL_DOLLARS
	,ON_ORDER_1WK_RETAIL_DOLLARS AS ON_ORDER_1WK_RETAIL_DOLLARS
	,ON_ORDER_2WK_RETAIL_DOLLARS AS ON_ORDER_2WK_RETAIL_DOLLARS
	,ON_ORDER_3WK_RETAIL_DOLLARS AS ON_ORDER_3WK_RETAIL_DOLLARS
	,ON_ORDER_4WK_RETAIL_DOLLARS AS ON_ORDER_4WK_RETAIL_DOLLARS  
	,ON_ORDER_0WK_COST_DOLLARS AS ON_ORDER_0WK_COST_DOLLARS
	,ON_ORDER_1WK_COST_DOLLARS AS ON_ORDER_1WK_COST_DOLLARS
	,ON_ORDER_2WK_COST_DOLLARS AS ON_ORDER_2WK_COST_DOLLARS
	,ON_ORDER_3WK_COST_DOLLARS AS ON_ORDER_3WK_COST_DOLLARS
	,ON_ORDER_4WK_COST_DOLLARS AS ON_ORDER_4WK_COST_DOLLARS   
    ,FCST_0WK_DMND_UNITS
	,FCST_1WK_DMND_UNITS
	,FCST_2WK_DMND_UNITS
	,FCST_3WK_DMND_UNITS
	,FCST_4WK_DMND_UNITS
	,FCST_5WK_DMND_UNITS
	,FCST_6WK_DMND_UNITS
	,FCST_7WK_DMND_UNITS
	,FCST_8WK_DMND_UNITS
	,FCST_9WK_DMND_UNITS
	,F_I_EOH_IN_STOCK_IND AS IN_STOCK_IND
	,DAYS_IN_STOCK
	FROM RP_PERFORMANCE_FACT f
	LEFT JOIN PRD_NAP_USR_VWS.PRODUCT_SKU_DIM_VW p
	ON f.RMS_SKU_NUM=p.RMS_SKU_NUM
	AND p.CHANNEL_COUNTRY='US'
	LEFT JOIN PRD_NAP_USR_VWS.PRODUCT_STYLE_DIM psd 
	ON psd.epm_style_num = p.epm_style_num 
	AND psd.channel_country = p.channel_country 
	AND psd.prmy_supp_num = p.prmy_supp_num 
	LEFT JOIN PRD_NAP_USR_VWS.VENDOR_DIM v
	ON p.PRMY_SUPP_NUM=v.VENDOR_NUM
	INNER JOIN PRD_NAP_USR_VWS.STORE_DIM s
	ON f.STORE_NUM=CAST(s.STORE_NUM AS VARCHAR(16))
	AND s.STORE_COUNTRY_CODE='US'
	AND s.STORE_ABBREV_NAME <>'CLOSED'
	LEFT JOIN CLIMATE_CLUSTER_DIM c
	ON c.STORE_NUM=s.STORE_NUM
	LEFT JOIN PRD_NAP_VWS.MERCH_PRODUCT_SUBCLASS_DIM_VW sbclass 
	ON sbclass.DIVISION_NUM = P.DIV_NUM
	AND sbclass.SUBDIVISION_NUM = p.grp_num 
	AND sbclass.DEPT_NUM = p.dept_num 
	AND sbclass.CLASS_NUM = p.class_num 
	AND sbclass.SBCLASS_NUM = p.sbclass_num 
	WHERE UPPER(p.DIV_DESC) not like '%INACT%'
	AND UPPER(p.GRP_DESC) not like '%INACT%'
	)
	WITH DATA
	PRIMARY INDEX (SKU_IDNT,STORE_NUM,WK_IDNT)
	ON COMMIT PRESERVE ROWS;

COLLECT STATS PRIMARY INDEX(SKU_IDNT,STORE_NUM,WK_IDNT) ON RP_PERFORMANCE_FACT_DIM;
	
	DELETE {environment_schema}.RP_PERFORMANCE_ROLLUP{env_suffix} ALL;
	
	INSERT INTO {environment_schema}.RP_PERFORMANCE_ROLLUP{env_suffix} 
(
  	SKU_IDNT,
    STORE_NUM,
    WK_IDNT,
    RP_PRODUCT_IND,
	RP_STATUS_FLAG,
    CLASS_LABEL,
    COLOR_NUM,
    COLOR_LABEL,
    DEPT_LABEL,
    DIV_DESC,
    DIV_LABEL,
    SUBCLASS_LABEL,
	SUBCLASS_CATEGORY,
    SDIV_LABEL,
    SIZE_1_NUM,
    SIZE_2_DESC,
    SIZE_2_NUM,
    SUPPLIER_COLOR,
    VPN,
    SUPPLIER_SIZE,
    VPN_LABEL,
    STYLE_NUM,
    STYLE_GROUP_NUM,
	NPG_IND,
	ORDER_PACK_SIZE,
    REGN_LABEL,
    CHANNEL_DESC,
    CHANNEL_LABEL,
    DISTT_LABEL,
    LOC_LABEL,
    STORE_STATUS,
    SUPPLIER_NAME,
	VENDOR_LABEL_NAME,
    CLUSTER_CLIMATE,
    RETURN_TOTAL_UNITS,
	RETURN_TOTAL_RETL_DOLLARS,
	RETURN_TOTAL_COST,
    NET_SALES_TOTAL_RETL_DOLLARS,
    SALES_4WK_RETL_DOLLARS,   
	SALES_LWK_RETL_DOLLARS,   
	SALES_WTD_RETL_DOLLARS,   
    NET_SALES_TOTAL_UNITS,
    SALES_4WK_UNITS,   
    SALES_LWK_UNITS,   
    SALES_WTD_UNITS,   
	NET_SALES_TOTAL_COST,
 	SALES_4WK_COST_AMT,   
	SALES_LWK_COST_AMT,   
	SALES_WTD_COST_AMT,  
	RECEIPT_TOTAL_UNITS,
	RECEIPT_TOTAL_RETL_DOLLARS,
	RECEIPT_TOTAL_COST,
	RECEIPT_TOTAL_PO_UNITS,
	RECEIPT_TOTAL_PO_RETL_DOLLARS,
	RECEIPT_TOTAL_PO_COST,
    EOH_TOTAL_RETL_DOLLARS,
    EOH_TOTAL_UNITS,
	EOH_TOTAL_COST,
	EOH_TOTAL_REG_RETL_DOLLARS,   
	EOH_TOTAL_REG_UNITS,   
	EOH_TOTAL_REG_COST,   
	EOH_TOTAL_CLR_RETL_DOLLARS,   
	EOH_TOTAL_CLR_UNITS,   
	EOH_TOTAL_CLR_COST,   
    EOH_IN_TRNST_TOTAL_UNITS,
	EOH_IN_TRNST_TOTAL_COST,
	EOH_IN_TRNST_TOTAL_RETAIL_DOLLARS,
	BOH_TOTAL_UNITS,
	BOH_TOTAL_RETAIL_DOLLARS,
	BOH_TOTAL_COST_DOLLARS,
	BOH_IN_TRANSIT_TOTAL_UNITS,
	BOH_IN_TRANSIT_TOTAL_COST_DOLLARS,
	BOH_IN_TRANSIT_TOTAL_RETAIL_DOLLARS,
	RESERVE_STOCK_TRANSFER_IN_RETAIL,
	RESERVE_STOCK_TRANSFER_IN_UNITS,
	RESERVE_STOCK_TRANSFER_IN_COST,
	RESERVE_STOCK_TRANSFER_OUT_RETAIL,
	RESERVE_STOCK_TRANSFER_OUT_UNITS,
	RESERVE_STOCK_TRANSFER_OUT_COST,
    DEMAND_TOTAL_RETL_DOLLARS,
	DEMAND_TOTAL_UNITS,
    ON_ORDER_TOTAL_UNITS,
	ON_ORDER_TOTAL_RETAIL_DOLLARS,
	ON_ORDER_TOTAL_COST_DOLLARS,
	ON_ORDER_0WK_UNITS,
    ON_ORDER_1WK_UNITS,
	ON_ORDER_2WK_UNITS,
	ON_ORDER_3WK_UNITS,
	ON_ORDER_4WK_UNITS,   
	ON_ORDER_0WK_RETAIL_DOLLARS,
	ON_ORDER_1WK_RETAIL_DOLLARS,
	ON_ORDER_2WK_RETAIL_DOLLARS,
	ON_ORDER_3WK_RETAIL_DOLLARS,
	ON_ORDER_4WK_RETAIL_DOLLARS,   
	ON_ORDER_0WK_COST_DOLLARS,
	ON_ORDER_1WK_COST_DOLLARS,
	ON_ORDER_2WK_COST_DOLLARS,
	ON_ORDER_3WK_COST_DOLLARS,
	ON_ORDER_4WK_COST_DOLLARS,   
    FCST_0WK_DMND_UNITS,
    FCST_1WK_DMND_UNITS,
    FCST_2WK_DMND_UNITS,
    FCST_3WK_DMND_UNITS,
    FCST_4WK_DMND_UNITS,
    FCST_5WK_DMND_UNITS,
    FCST_6WK_DMND_UNITS,
    FCST_7WK_DMND_UNITS,
    FCST_8WK_DMND_UNITS,
    FCST_9WK_DMND_UNITS,
	IN_STOCK_IND,
	DAYS_IN_STOCK,
	DW_SYS_LOAD_TMSTP  
)
SELECT 
	SKU_IDNT,
    STORE_NUM,
    WK_IDNT,
    RP_PRODUCT_IND,
	RP_STATUS_FLAG,
    CLASS_LABEL,
    COLOR_NUM,
    COLOR_LABEL,
    DEPT_LABEL,
    DIV_DESC,
    DIV_LABEL,
    SUBCLASS_LABEL,
	SUBCLASS_CATEGORY,
    SDIV_LABEL,
    SIZE_1_NUM,
    SIZE_2_DESC,
    SIZE_2_NUM,
    SUPPLIER_COLOR,
    VPN,
    SUPPLIER_SIZE,
    VPN_LABEL,
    STYLE_NUM,
    STYLE_GROUP_NUM,
	NPG_IND,
	ORDER_PACK_SIZE,
    REGN_LABEL,
    CHANNEL_DESC,
    CHANNEL_LABEL,
    DISTT_LABEL,
    LOC_LABEL,
    STORE_STATUS,
    SUPPLIER_NAME,
	VENDOR_LABEL_NAME,
    CLUSTER_CLIMATE,
    RETURN_TOTAL_UNITS,
	RETURN_TOTAL_RETL_DOLLARS,
	RETURN_TOTAL_COST,
    NET_SALES_TOTAL_RETL_DOLLARS,
    SALES_4WK_RETL_DOLLARS,   
	SALES_LWK_RETL_DOLLARS,   
	SALES_WTD_RETL_DOLLARS,   
    NET_SALES_TOTAL_UNITS,
    SALES_4WK_UNITS,   
    SALES_LWK_UNITS,   
    SALES_WTD_UNITS,   
	NET_SALES_TOTAL_COST,
 	SALES_4WK_COST_AMT,   
	SALES_LWK_COST_AMT,   
	SALES_WTD_COST_AMT,  
	RECEIPT_TOTAL_UNITS,
	RECEIPT_TOTAL_RETL_DOLLARS,
	RECEIPT_TOTAL_COST,
	RECEIPT_TOTAL_PO_UNITS,
	RECEIPT_TOTAL_PO_RETL_DOLLARS,
	RECEIPT_TOTAL_PO_COST,
    EOH_TOTAL_RETL_DOLLARS,
    EOH_TOTAL_UNITS,
	EOH_TOTAL_COST,
	EOH_TOTAL_REG_RETL_DOLLARS,   
	EOH_TOTAL_REG_UNITS,   
	EOH_TOTAL_REG_COST,   
	EOH_TOTAL_CLR_RETL_DOLLARS,   
	EOH_TOTAL_CLR_UNITS,   
	EOH_TOTAL_CLR_COST,   
    EOH_IN_TRNST_TOTAL_UNITS,
	EOH_IN_TRNST_TOTAL_COST,
	EOH_IN_TRNST_TOTAL_RETAIL_DOLLARS,
	BOH_TOTAL_UNITS,
	BOH_TOTAL_RETAIL_DOLLARS,
	BOH_TOTAL_COST_DOLLARS,
	BOH_IN_TRANSIT_TOTAL_UNITS,
	BOH_IN_TRANSIT_TOTAL_COST_DOLLARS,
	BOH_IN_TRANSIT_TOTAL_RETAIL_DOLLARS,
	RESERVE_STOCK_TRANSFER_IN_RETAIL,
	RESERVE_STOCK_TRANSFER_IN_UNITS,
	RESERVE_STOCK_TRANSFER_IN_COST,
	RESERVE_STOCK_TRANSFER_OUT_RETAIL,
	RESERVE_STOCK_TRANSFER_OUT_UNITS,
	RESERVE_STOCK_TRANSFER_OUT_COST,
    DEMAND_TOTAL_RETL_DOLLARS,
	DEMAND_TOTAL_UNITS,
    ON_ORDER_TOTAL_UNITS,
	ON_ORDER_TOTAL_RETAIL_DOLLARS,
	ON_ORDER_TOTAL_COST_DOLLARS,
	ON_ORDER_0WK_UNITS,
    ON_ORDER_1WK_UNITS,
	ON_ORDER_2WK_UNITS,
	ON_ORDER_3WK_UNITS,
	ON_ORDER_4WK_UNITS,   
	ON_ORDER_0WK_RETAIL_DOLLARS,
	ON_ORDER_1WK_RETAIL_DOLLARS,
	ON_ORDER_2WK_RETAIL_DOLLARS,
	ON_ORDER_3WK_RETAIL_DOLLARS,
	ON_ORDER_4WK_RETAIL_DOLLARS,   
	ON_ORDER_0WK_COST_DOLLARS,
	ON_ORDER_1WK_COST_DOLLARS,
	ON_ORDER_2WK_COST_DOLLARS,
	ON_ORDER_3WK_COST_DOLLARS,
	ON_ORDER_4WK_COST_DOLLARS,   
    FCST_0WK_DMND_UNITS,
    FCST_1WK_DMND_UNITS,
    FCST_2WK_DMND_UNITS,
    FCST_3WK_DMND_UNITS,
    FCST_4WK_DMND_UNITS,
    FCST_5WK_DMND_UNITS,
    FCST_6WK_DMND_UNITS,
    FCST_7WK_DMND_UNITS,
    FCST_8WK_DMND_UNITS,
    FCST_9WK_DMND_UNITS,
	IN_STOCK_IND,   
	DAYS_IN_STOCK,
	CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP 
	FROM RP_PERFORMANCE_FACT_DIM; 
	
COLLECT STATS PRIMARY INDEX(SKU_IDNT,STORE_NUM,WK_IDNT) ON {environment_schema}.RP_PERFORMANCE_ROLLUP{env_suffix};

