-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=card_to_wallet_threshold_violated_teradata; Task_Name=kafka_to_teradata_stg_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE CARD_TO_WALLET_THRESHOLD_VIOLATED_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.CARD_TO_WALLET_THRESHOLD_VIOLATED_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY CUSTOMER_ID, EVENT_TIME ORDER BY EVENT_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (CUSTOMER_ID, EVENT_TIME) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.CARD_TO_WALLET_THRESHOLD_VIOLATED_FACT
WHERE CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.CARD_TO_WALLET_THRESHOLD_VIOLATED_LDG);

INSERT INTO PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.CARD_TO_WALLET_THRESHOLD_VIOLATED_FACT
(
    EVENT_TIME,
    EVENT_DATE,
    CUSTOMER_ID,
    CUSTOMER_ID_TYPE,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    VIOLATION_REASON,
    EVENT_ID,
    DW_BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT DISTINCT
    CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
    CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS EVENT_DATE,
    CUSTOMER_ID,
    CUSTOMER_ID_TYPE,
    CHANNEL_COUNTRY,
    CHANNEL_BRAND,
    SELLING_CHANNEL,
    VIOLATION_REASON,
    HASH_SHA256(CONCAT(
                COALESCE(TRIM(CUSTOMER_ID), ''),
                COALESCE(TRIM(TO_CHAR(EVENT_TIME)), '')
                )) AS EVENT_ID,
    CURRENT_DATE AS DW_BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM CARD_TO_WALLET_THRESHOLD_VIOLATED_TEMP;

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.CARD_TO_WALLET_THRESHOLD_VIOLATED_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
