-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=fraud_blocklist_activity_teradata; Task_Name=fraud_blocklist_activity_td_stg_to_td_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE FRAUD_BLOCKLIST_ACTIVITY_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_PYMNT_FRAUD_BASE_VWS.FRAUD_BLOCKLIST_ACTIVITY_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY CUSTOMER_ID, ACTIVITY_TYPE, EVENT_TIME ORDER BY EVENT_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (CUSTOMER_ID, ACTIVITY_TYPE, EVENT_TIME) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM {db_env}_NAP_PYMNT_FRAUD_BASE_VWS.FRAUD_BLOCKLIST_ACTIVITY_FACT
WHERE CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM {db_env}_NAP_PYMNT_FRAUD_BASE_VWS.FRAUD_BLOCKLIST_ACTIVITY_LDG);

INSERT INTO {db_env}_NAP_PYMNT_FRAUD_BASE_VWS.FRAUD_BLOCKLIST_ACTIVITY_FACT
(
    EVENT_TIME,
    EVENT_DATE,
    ACTIVITY_TYPE,
    CUSTOMER_ID,
    CUSTOMER_ID_TYPE,
    REASON,
    EVENT_ID,
    DW_BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT DISTINCT
    CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
    CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS EVENT_DATE,
    ACTIVITY_TYPE,
    CUSTOMER_ID,
    CUSTOMER_ID_TYPE,
    REASON,
    HASH_SHA256(CONCAT(
                COALESCE(TRIM(CUSTOMER_ID), ''),
                COALESCE(TRIM(ACTIVITY_TYPE), ''),
                COALESCE(TRIM(TO_CHAR(EVENT_TIME)), '')
                )) AS EVENT_ID,
    CURRENT_DATE AS DW_BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM FRAUD_BLOCKLIST_ACTIVITY_TEMP;

-- Remove records from temporary tables
DELETE FROM {db_env}_NAP_PYMNT_FRAUD_BASE_VWS.FRAUD_BLOCKLIST_ACTIVITY_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
