-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=fraud_worldpay_bin; Task_Name=td_stg_to_td_dim_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_LDG
WHERE MASTER_MERCHANT_BIN_FILE_LINE LIKE '%HEADER%';

DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_LDG
WHERE MASTER_MERCHANT_BIN_FILE_LINE LIKE '%TRAILR%';

CREATE MULTISET VOLATILE TABLE WORLDPAY_BIN_LDG_TMP AS (
    SELECT
        SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 7, 2) AS BIN_LENGTH,
        SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 9, 2) AS PAN_LENGTH,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 11, 12)), '') AS BIN,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 23, 4)), '') AS CARD_NETWORK,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 27, 1)), '') AS DEBIT_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 28, 1)), '') AS CHECKCARD_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 29, 1)), '') AS CREDIT_CARD_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 30, 1)), '') AS COMMERCIAL_BUSINESS_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 31, 1)), '') AS FLEET_CARD_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 32, 1)), '') AS PREPAID_CARD_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 33, 1)), '') AS HSA_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 34, 1)), '') AS PINLESS_BILL_PAY_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 35, 1)), '') AS EBT_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 36, 1)), '') AS WIC_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 37, 1)), '') AS INTERNATIONAL_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 38, 1)), '') AS NETWORK_REGULATION_VALUE,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 39, 1)), '') AS PINLESS_POS_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 40, 1)), '') AS TOKEN_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 41, 1)), '') AS RELOAD_FLAG,
        NULLIF(TRIM(SUBSTRING(MASTER_MERCHANT_BIN_FILE_LINE, 42, 1)), '') AS CARDHOLDER_FUNDS_TRANSFER_FLAG
    FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_LDG
) WITH DATA ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM WORLDPAY_BIN_LDG_TMP
WHERE (
       BIN_LENGTH,
       PAN_LENGTH,
       BIN,
       CARD_NETWORK,
       DEBIT_FLAG,
       CHECKCARD_FLAG,
       CREDIT_CARD_FLAG,
       COMMERCIAL_BUSINESS_FLAG,
       FLEET_CARD_FLAG,
       PREPAID_CARD_FLAG,
       HSA_FLAG,
       PINLESS_BILL_PAY_FLAG,
       EBT_FLAG,
       WIC_FLAG,
       INTERNATIONAL_FLAG,
       NETWORK_REGULATION_VALUE,
       PINLESS_POS_FLAG,
       TOKEN_FLAG,
       RELOAD_FLAG,
       CARDHOLDER_FUNDS_TRANSFER_FLAG
  )
   IN (
    SELECT DISTINCT
       BIN_LENGTH,
       PAN_LENGTH,
       BIN,
       CARD_NETWORK,
       DEBIT_FLAG,
       CHECKCARD_FLAG,
       CREDIT_CARD_FLAG,
       COMMERCIAL_BUSINESS_FLAG,
       FLEET_CARD_FLAG,
       PREPAID_CARD_FLAG,
       HSA_FLAG,
       PINLESS_BILL_PAY_FLAG,
       EBT_FLAG,
       WIC_FLAG,
       INTERNATIONAL_FLAG,
       NETWORK_REGULATION_VALUE,
       PINLESS_POS_FLAG,
       TOKEN_FLAG,
       RELOAD_FLAG,
       CARDHOLDER_FUNDS_TRANSFER_FLAG
     FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_DIM
);

INSERT INTO PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_DIM
(
    BIN_LENGTH,
    PAN_LENGTH,
    BIN,
    BIN_SIX,
    CARD_NETWORK,
    DEBIT_FLAG,
    CHECKCARD_FLAG,
    CREDIT_CARD_FLAG,
    COMMERCIAL_BUSINESS_FLAG,
    FLEET_CARD_FLAG,
    PREPAID_CARD_FLAG,
    HSA_FLAG,
    PINLESS_BILL_PAY_FLAG,
    EBT_FLAG,
    WIC_FLAG,
    INTERNATIONAL_FLAG,
    NETWORK_REGULATION_VALUE,
    PINLESS_POS_FLAG,
    TOKEN_FLAG,
    RELOAD_FLAG,
    CARDHOLDER_FUNDS_TRANSFER_FLAG,
    RECENTLY_UPDATED,
    DATE_ADDED,
    DW_BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT DISTINCT
    BIN_LENGTH,
    PAN_LENGTH,
    BIN,
    SUBSTRING(BIN, 1, 6) AS BIN_SIX,
    CARD_NETWORK,
    DEBIT_FLAG,
    CHECKCARD_FLAG,
    CREDIT_CARD_FLAG,
    COMMERCIAL_BUSINESS_FLAG,
    FLEET_CARD_FLAG,
    PREPAID_CARD_FLAG,
    HSA_FLAG,
    PINLESS_BILL_PAY_FLAG,
    EBT_FLAG,
    WIC_FLAG,
    INTERNATIONAL_FLAG,
    NETWORK_REGULATION_VALUE,
    PINLESS_POS_FLAG,
    TOKEN_FLAG,
    RELOAD_FLAG,
    CARDHOLDER_FUNDS_TRANSFER_FLAG,
    'Y' AS RECENTLY_UPDATED,
    CURRENT_TIMESTAMP(0) AS DATE_ADDED,
    CURRENT_DATE AS DW_BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM WORLDPAY_BIN_LDG_TMP;

UPDATE PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_DIM
SET RECENTLY_UPDATED = 'Y'
WHERE BIN_SIX IN (SELECT BIN_SIX FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_DIM WHERE RECENTLY_UPDATED = 'Y');

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_PYMNT_FRAUD_BASE_VWS.WORLDPAY_BIN_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
