-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_settlement_intent_teradata_v2; Task_Name=teradata_tender_stg_to_teradata_tender_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting latest distinct records by 'transaction_id'
CREATE MULTISET VOLATILE TABLE PAYMENT_SETTLEMENT_TENDER_TEMP AS (
    SELECT DISTINCT *
    FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY TRANSACTION_ID ORDER BY CAST(EVENT_TIME AS TIMESTAMP) DESC
        ) = 1
) WITH DATA PRIMARY INDEX (TRANSACTION_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_FACT
WHERE TRANSACTION_ID IN (SELECT DISTINCT TRANSACTION_ID FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_LDG);

INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_FACT
(
  EVENT_TIME,
  ACTIVITY_DATE,
  TENDER_RECORD_NAME,
  TRANSACTION_ID,
  TENDER_TYPE,
  PURCHASE_IDENTIFIER_ID,
  CARD_TYPE,
  CARD_SUB_TYPE,
  TENDER_ITEM_ACCOUNT_NO,
  TENDER_ITEM_ACCOUNT_VALUE_TYPE,
  TOKEN_AUTHORITY,
  TOKEN_DATA_CLASSIFICATION,
  TOKEN_TYPE,
  CURRENCY_CODE,
  TOTAL_AMT,
  TOTAL_AMT_TYPE,
  TRANSACTION_TIME,
  TRANSACTION_TYPE,
  TRANSACTION_DATE,
  TRANSACTION_STATUS,
  TRANSACTION_FAILURE_DESC,
  TOKEN_REQUESTOR_ID,
  VENDOR_SETTLEMENT_CODE,
  GIFT_CARD_NOTE_TYPE,
  GIFT_CARD_REQ_AMT_CURRENCY_CODE,
  GIFT_CARD_REQ_AMT,
  BALANCE_LOCK_ID,
  PAYPAL_TNDR_RSLT_ORDER_ID,
  PAYPAL_TNDR_RSLT_PAYER_ID,
  PAYPAL_STLMNT_RSLT_ID,
  PAYPAL_STLMNT_RSLT_PARENT_REF_ID,
  PAYPAL_STLMNT_RSLT_FEE_CURRENCY_CODE,
  PAYPAL_STLMNT_RSLT_FEE_AMOUNT,
  PAYPAL_STLMNT_RSLT_NET_AMT_CURRENCY_CODE,
  PAYPAL_STLMNT_RSLT_NET_AMT_AMT,
  PAYPAL_BILLING_AGREEMENT_TNDR_RSLT_ID_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_EMAIL_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_ACCOUNT_COUNTRY,
  DW_BATCH_DATE,
  DW_SYS_LOAD_TMSTP,
  DW_SYS_UPDT_TMSTP
)
SELECT
  CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
  CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS ACTIVITY_DATE,
  TENDER_RECORD_NAME,
  TRANSACTION_ID,
  TENDER_TYPE,
  PURCHASE_IDENTIFIER_ID,
  CARD_TYPE,
  CARD_SUB_TYPE,
  TENDER_ITEM_ACCOUNT_NO,
  TENDER_ITEM_ACCOUNT_VALUE_TYPE,
  TOKEN_AUTHORITY,
  TOKEN_DATA_CLASSIFICATION,
  TOKEN_TYPE,
  CURRENCY_CODE,
  CAST(TOTAL_AMT AS DECIMAL(14, 4)) AS TOTAL_AMT,
  TOTAL_AMT_TYPE,
  CAST(TRANSACTION_TIME AS TIMESTAMP) AS TRANSACTION_TIME,
  TRANSACTION_TYPE,
  CAST(TRANSACTION_DATE AS DATE) AS TRANSACTION_DATE,
  TRANSACTION_STATUS,
  TRANSACTION_FAILURE_DESC,
  TOKEN_REQUESTOR_ID,
  VENDOR_SETTLEMENT_CODE,
  GIFT_CARD_NOTE_TYPE,
  GIFT_CARD_REQ_AMT_CURRENCY_CODE,
  CAST(GIFT_CARD_REQ_AMT AS DECIMAL(14, 4)) AS GIFT_CARD_REQ_AMT,
  BALANCE_LOCK_ID,
  PAYPAL_TNDR_RSLT_ORDER_ID,
  PAYPAL_TNDR_RSLT_PAYER_ID,
  PAYPAL_STLMNT_RSLT_ID,
  PAYPAL_STLMNT_RSLT_PARENT_REF_ID,
  PAYPAL_STLMNT_RSLT_FEE_CURRENCY_CODE,
  CAST(PAYPAL_STLMNT_RSLT_FEE_AMOUNT AS DECIMAL(14, 4)) AS PAYPAL_STLMNT_RSLT_FEE_AMOUNT,
  PAYPAL_STLMNT_RSLT_NET_AMT_CURRENCY_CODE,
  CAST(PAYPAL_STLMNT_RSLT_NET_AMT_AMT AS DECIMAL(14, 4)) AS PAYPAL_STLMNT_RSLT_NET_AMT_AMT,
  PAYPAL_BILLING_AGREEMENT_TNDR_RSLT_ID_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_EMAIL_VALUE,
  PAYPAL_TNDR_RSLT_PAYER_ACCOUNT_COUNTRY,
  CURRENT_DATE AS DW_BATCH_DATE,
  CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
  CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM PAYMENT_SETTLEMENT_TENDER_TEMP;

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
