-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_refund_teradata; Task_Name=teradata_hdr_stg_to_teradata_hdr_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE PAYMENT_REFUND_HDR_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_BASE_VWS.PAYMENT_REFUND_HDR_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY EVENT_ID ORDER BY CAST(EVENT_TIME AS TIMESTAMP) DESC
        ) = 1
) WITH DATA PRIMARY INDEX (EVENT_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_REFUND_HDR_FACT
WHERE EVENT_ID IN (SELECT DISTINCT EVENT_ID FROM PREPROD_NAP_BASE_VWS.PAYMENT_REFUND_HDR_LDG);

INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_REFUND_HDR_FACT
(
  EVENT_ID,
  EVENT_TYPE,
  EVENT_TIME,
  ACTIVITY_DATE,
  CHANNEL_COUNTRY,
  CHANNEL,
  PLATFORM,
  FEATURE,
  SERVICE_NAME,
  STORE,
  REGISTER,
  PURCHASE_IDENTIFIER_TYPE,
  PURCHASE_IDENTIFIER_ID,
  POS_STORE,
  POS_REGISTER,
  POS_TRANSACTION,
  POS_BUSINESS_DATE,
  STORE_TRANSACTION_TRANSACTION_ID,
  STORE_TRANSACTION_SESSION_ID,
  TRANSACTION_ID,
  TRANSACTION_ID_TYPE,
  SERVICE_TICKET_ID,
  REASON,
  CURRENCY_CODE,
  TOTAL_AMT,
  MERCHANT_IDENTIFIER,
  FAILURE_REASON,
  BATCH_DATE,
  DW_SYS_LOAD_TMSTP,
  DW_SYS_UPDT_TMSTP
)
SELECT DISTINCT
  EVENT_ID,
  EVENT_TYPE,
  CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
  CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS ACTIVITY_DATE,
  CHANNEL_COUNTRY,
  CHANNEL,
  PLATFORM,
  FEATURE,
  SERVICE_NAME,
  STORE,
  REGISTER,
  PURCHASE_IDENTIFIER_TYPE,
  PURCHASE_IDENTIFIER_ID,
  POS_STORE,
  POS_REGISTER,
  POS_TRANSACTION,
  CAST(POS_BUSINESS_DATE AS DATE) AS POS_BUSINESS_DATE,
  STORE_TRANSACTION_TRANSACTION_ID,
  STORE_TRANSACTION_SESSION_ID,
  TRANSACTION_ID,
  TRANSACTION_ID_TYPE,
  SERVICE_TICKET_ID,
  REASON,
  CURRENCY_CODE,
  CAST(TOTAL_AMT AS DECIMAL(14, 4)) AS TOTAL_AMT,
  MERCHANT_IDENTIFIER,
  FAILURE_REASON,
  CURRENT_DATE AS BATCH_DATE,
  CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
  CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM PAYMENT_REFUND_HDR_TEMP;

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_REFUND_HDR_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
