-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_cancel_teradata; Task_Name=teradata_dtl_stg_to_teradata_dtl_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary table for selecting distinct records by 'event_id'
CREATE MULTISET VOLATILE TABLE PAYMENT_CANCEL_DTL_TEMP AS (
    SELECT *
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_CANCEL_DTL_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY EVENT_ID ORDER BY CAST(EVENT_TIME AS TIMESTAMP) DESC
        ) = 1
) WITH DATA PRIMARY INDEX (EVENT_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_CANCEL_DTL_FACT
WHERE EVENT_ID IN (SELECT DISTINCT EVENT_ID FROM {db_env}_NAP_BASE_VWS.PAYMENT_CANCEL_DTL_LDG);

INSERT INTO {db_env}_NAP_BASE_VWS.PAYMENT_CANCEL_DTL_FACT
(
    EVENT_ID,
    EVENT_TYPE,
    EVENT_TIME,
    ACTIVITY_DATE,
    ORDER_NUMBER,
    ORDER_LINE_ID,
    SERVICE_LINE_ID,
    BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT
    EVENT_ID,
    EVENT_TYPE,
    CAST(EVENT_TIME AS TIMESTAMP) AS EVENT_TIME,
    CAST(CAST(EVENT_TIME AS TIMESTAMP) AS DATE) AS ACTIVITY_DATE,
    ORDER_NUMBER,
    ORDER_LINE_ID,
    SERVICE_LINE_ID,
    CURRENT_DATE AS BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM PAYMENT_CANCEL_DTL_TEMP;

-- Remove records from temporary tables
DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_CANCEL_DTL_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
