-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_settlement_intent_teradata_v2;Task_Name=teradata_hdr_fct_update_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Update PAYMENT_ID_SETTLEMENT_RESULT column
UPDATE {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT
FROM (
SELECT
    A.TRANSACTION_ID,
    B.VENDOR_SETTLEMENT_CODE,
    B.TENDER_ITEM_ACCOUNT_NO,
    A.TOTAL_AMT
FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT A
INNER JOIN {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_FACT B
ON A.TRANSACTION_ID = B.TRANSACTION_ID
WHERE A.TRANSACTION_ID IN
(SELECT DISTINCT TRANSACTION_ID
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_LDG)
AND B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_SETTLEMENT_RESULT = HASH_SHA256(CONCAT(
                COALESCE(TRIM(C.VENDOR_SETTLEMENT_CODE), ''),
                COALESCE(TRIM(C.TENDER_ITEM_ACCOUNT_NO), ''),
                COALESCE(TRIM(CAST(CAST(C.TOTAL_AMT AS DECIMAL(12, 2)) AS VARCHAR(50))), '')
                ))
WHERE {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT.TRANSACTION_ID = C.TRANSACTION_ID;

-- Update PAYMENT_ID_AUTHORIZATION column
UPDATE {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT
FROM (
SELECT A.TRANSACTION_ID
FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT A
INNER JOIN {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_FACT B
ON A.TRANSACTION_ID = B.TRANSACTION_ID
WHERE A.TRANSACTION_ID IN
(SELECT DISTINCT TRANSACTION_ID
    FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_LDG)
AND B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_AUTHORIZATION = PURCHASE_IDENTIFIER_ID
WHERE {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT.TRANSACTION_ID = C.TRANSACTION_ID;


-- Remove records from temporary tables
DELETE FROM {db_env}_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
