-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=payment_qr_code_lifecycle_teradata; Task_Name=teradata_stg_to_teradata_fct_job;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

-- Create temporary tables for selecting distinct records by 'transaction_identifier_id'
CREATE MULTISET VOLATILE TABLE QR_CODE_LIFECYCLE_STG_TEMP AS (
    SELECT *
    FROM PREPROD_NAP_STG.PAYMENT_QR_CODE_LIFECYCLE_LDG
    QUALIFY
        RANK() OVER (
            PARTITION BY QR_CODE_ID ORDER BY LAST_UPDATED_TIME DESC
        ) = 1
) WITH DATA PRIMARY INDEX (QR_CODE_ID) ON COMMIT PRESERVE ROWS;

END TRANSACTION;

-- Purge and reprocess data to account for updates
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_QR_CODE_LIFECYCLE_FACT
WHERE
    QR_CODE_ID IN (SELECT DISTINCT QR_CODE_ID FROM QR_CODE_LIFECYCLE_STG_TEMP);

-- Insert new event data
INSERT INTO PREPROD_NAP_BASE_VWS.PAYMENT_QR_CODE_LIFECYCLE_FACT (
    QR_CODE_ID,
    LAST_UPDATED_TIME,
    CREATED_TIMESTAMP,
    CREATED_DATE,
    CREATED_CHANNEL_COUNTRY,
    CREATED_CHANNEL_BRAND,
    CREATED_SELLING_CHANNEL,
    DEVICE_ID,
    USER_AGENT,
    CUSTOMER_WALLET_PAYMENT_ID,
    CUSTOMER_ID_TYPE,
    CUSTOMER_ID,
    CREDIT_CARD_LAST_FOUR,
    LIFECYCLE_STATUS,
    STATUS_EVENT_ID,
    STATUS_EVENT_TIME,
    STATUS_CHANNEL_COUNTRY,
    STATUS_CHANNEL_BRAND,
    STATUS_SELLING_CHANNEL,
    STATUS_STORE,
    STATUS_REGISTER,
    STATUS_QR_CODE_FAILURE_REASON,
    QR_CODE_INVOKED,
    QR_CODE_EXPIRED_WITHOUT_USE,
    QR_CODE_USED,
    REDEMPTION_TIME_SINCE_CREATION_SEC,
    DW_BATCH_DATE,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
SELECT
    QR_CODE_ID,
    CAST(LAST_UPDATED_TIME AS TIMESTAMP) AS LAST_UPDATED_TIME,
    CAST(CREATED_TIMESTAMP AS TIMESTAMP) AS CREATED_TIMESTAMP,
    CAST(CAST(CREATED_TIMESTAMP AS TIMESTAMP) AS DATE) AS CREATED_DATE,
    CREATED_CHANNEL_COUNTRY,
    CREATED_CHANNEL_BRAND,
    CREATED_SELLING_CHANNEL,
    DEVICE_ID,
    USER_AGENT,
    CUSTOMER_WALLET_PAYMENT_ID,
    CUSTOMER_ID_TYPE,
    CUSTOMER_ID,
    CREDIT_CARD_LAST_FOUR,
    LIFECYCLE_STATUS,
    STATUS_EVENT_ID,
    CAST(STATUS_EVENT_TIME AS TIMESTAMP) AS STATUS_EVENT_TIME,
    STATUS_CHANNEL_COUNTRY,
    STATUS_CHANNEL_BRAND,
    STATUS_SELLING_CHANNEL,
    STATUS_STORE,
    STATUS_REGISTER,
    STATUS_QR_CODE_FAILURE_REASON,
    'Y' AS QR_CODE_INVOKED,
    '' AS QR_CODE_EXPIRED_WITHOUT_USE,
    'N' AS QR_CODE_USED,
    (CAST(STATUS_EVENT_TIME AS TIMESTAMP) - CAST(CREATED_TIMESTAMP AS TIMESTAMP)) DAY(4) to SECOND(6) -- noqa
              AS REDEMPTION_TIME_SINCE_CREATION_SEC,
    CURRENT_DATE AS DW_BATCH_DATE,
    CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP,
    CURRENT_TIMESTAMP(0) AS DW_SYS_UPDT_TMSTP
FROM QR_CODE_LIFECYCLE_STG_TEMP;

UPDATE TGT
FROM PREPROD_NAP_BASE_VWS.PAYMENT_QR_CODE_LIFECYCLE_FACT TGT,
 (
  SELECT DISTINCT
            QR_CODE_ID,
            LAST_UPDATED_TIME
  FROM QR_CODE_LIFECYCLE_STG_TEMP
  WHERE LIFECYCLE_STATUS = 'redemption_succeeded'
) AS SRC
SET QR_CODE_USED = 'Y'
WHERE SRC.QR_CODE_ID = TGT.QR_CODE_ID
  AND SRC.LAST_UPDATED_TIME = TGT.LAST_UPDATED_TIME;

UPDATE PREPROD_NAP_BASE_VWS.PAYMENT_QR_CODE_LIFECYCLE_FACT
SET QR_CODE_EXPIRED_WITHOUT_USE = (CASE
                                        WHEN
                                          QR_CODE_USED = 'Y'
                                          THEN 'N'
                                        ELSE 'Y'
                                      END)
WHERE QR_CODE_ID IN (SELECT DISTINCT QR_CODE_ID FROM QR_CODE_LIFECYCLE_STG_TEMP);

-- Remove records from temporary tables
DELETE FROM PREPROD_NAP_BASE_VWS.PAYMENT_QR_CODE_LIFECYCLE_LDG;

SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
