-- mandatory Query Band part
SET QUERY_BAND = 'App_ID=app07420; DAG_ID=settlement_intent_hashkey_backfill_teradata;Task_Name=job_insert_update;' -- noqa
FOR SESSION VOLATILE;

END TRANSACTION;

UPDATE PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT
FROM (
SELECT
    A.TRANSACTION_ID,
    B.VENDOR_SETTLEMENT_CODE,
    A.ACTIVITY_DATE,
    B.TENDER_ITEM_ACCOUNT_NO,
    A.TOTAL_AMT
FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT A
INNER JOIN PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_FACT B
ON A.TRANSACTION_ID = B.TRANSACTION_ID
WHERE B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_SETTLEMENT_RESULT = HASH_SHA256(CONCAT(
                COALESCE(TRIM(C.VENDOR_SETTLEMENT_CODE), ''),
                COALESCE(TRIM(C.TENDER_ITEM_ACCOUNT_NO), ''),
                COALESCE(TRIM(CAST(CAST(C.TOTAL_AMT AS DECIMAL(12, 2)) AS VARCHAR(50))), '')
                ))
WHERE PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT.TRANSACTION_ID = C.TRANSACTION_ID;

UPDATE PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT
FROM (
SELECT A.TRANSACTION_ID
FROM PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT A
INNER JOIN PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_TENDER_V2_FACT B
ON A.TRANSACTION_ID = B.TRANSACTION_ID
WHERE B.TENDER_TYPE IN ('CREDIT_CARD', 'DEBIT_CARD', 'AFTERPAY')
) AS C
SET PAYMENT_ID_AUTHORIZATION = PURCHASE_IDENTIFIER_ID
WHERE PREPROD_NAP_BASE_VWS.PAYMENT_SETTLEMENT_INTENT_HDR_V2_FACT.TRANSACTION_ID = C.TRANSACTION_ID;


SET QUERY_BAND = NONE FOR SESSION; -- noqa

END TRANSACTION;
