create or replace temporary view media_pacing_report_view

(OrgId string,
Date_Start string,
Date_End string,
Comp_Date_Start string,
Comp_Date_End string,
Comp_Status string,
Analysis_Setup_Instance_Name string,
Analysis_Category_Name string,
NMNFlag string,
PlatformType string,
AcqRetType string,
AdFormat string,
LoyaltyStatus string,
Category string,
Banner string,
Level9 string,
Executed_Audience string,
Comp_Audience string,
Executed_Spend string,
Comp_Spend string,
Expected_Count1_Min string,
Estimated_Count1 string,
Expected_Count1_Max string,
Expected_Count2_Min string,
Estimated_Count2 string,
Expected_Count2_Max string,
Expected_Count3_Min string,
Estimated_Count3 string,
Expected_Count3_Max string,
Expected_Count4_Min string,
Estimated_Count4 string,
Expected_Count4_Max string,
Expected_Count5_Min string,
Estimated_Count5 string,
Expected_Count5_Max string,
Expected_Count6_Min string,
Estimated_Count6 string,
Expected_Count6_Max string,
Expected_Count7_Min string,
Estimated_Count7 string,
Expected_Count7_Max string,
Expected_Count8_Min string,
Estimated_Count8 string,
Expected_Count8_Max string,
Expected_Count9_Min string ,
Estimated_Count9 string,
Expected_Count9_Max string,
Expected_Count10_Min string,
Estimated_Count10 string ,
Expected_Count10_Max string,
Expected_Value1_Min string,
Estimated_Value1 string,
Expected_Value1_Max string,
Expected_Value2_Min string,
Estimated_Value2 string,
Expected_Value2_Max string,
Expected_Value3_Min string,
Estimated_Value3 string,
Expected_Value3_Max string,
Expected_Value4_Min string,
Estimated_Value4 string,
Expected_Value4_Max string,
Expected_Value5_Min string,
Estimated_Value5 string,
Expected_Value5_Max string    	
)
 USING CSV 
 OPTIONS (
    path "s3://mim-production/RMI/*Pacing*.csv", 
    sep ",",
    header "true" 
)
;


-- Writing output to teradata landing table.
-- This sould match the "sql_table_reference" indicated on the .json file.
INSERT OVERWRITE TABLE media_pacing_report_ldg_output
SELECT
OrgId ,
Date_Start, 
Date_End, 
Comp_Date_Start, 
Comp_Date_End, 
Comp_Status ,
Analysis_Setup_Instance_Name ,
Analysis_Category_Name ,
NMNFlag ,
PlatformType ,
AcqRetType ,
AdFormat ,
LoyaltyStatus ,
Category ,
Banner ,
Level9 ,
cast(Executed_Audience as float ) as Executed_Audience ,
 cast(Comp_Audience as float ) as Comp_Audience,
 cast(Executed_Spend as float ) as Executed_Spend,
 cast(Comp_Spend as float ) as Comp_Spend,
  cast(Expected_Count1_Min as float ) as Expected_Count1_Min,
  cast(Estimated_Count1 as float ) as Estimated_Count1,
  cast(Expected_Count1_Max as float ) as Expected_Count1_Max,
  cast(Expected_Count2_Min as float ) as Expected_Count2_Min,
 cast(Estimated_Count2 as float ) as Estimated_Count2,
 cast(Expected_Count2_Max as float ) as Expected_Count2_Max,
 cast(Expected_Count3_Min as float ) as Expected_Count3_Min,
 cast(Estimated_Count3 as float ) as Estimated_Count3,
 cast(Expected_Count3_Max as float ) as Expected_Count3_Max,
 cast(Expected_Count4_Min as float ) as Expected_Count4_Min,
 cast(Estimated_Count4 as float ) as Estimated_Count4,
 cast(Expected_Count4_Max as float ) as Expected_Count4_Max,
 cast(Expected_Count5_Min as float ) as Expected_Count5_Min,
 cast(Estimated_Count5 as float ) as Estimated_Count5,
 cast(Expected_Count5_Max as float ) as Expected_Count5_Max,
 cast(Expected_Count6_Min as float ) as Expected_Count6_Min,
 cast(Estimated_Count6 as float ) as Estimated_Count6,
 cast(Expected_Count6_Max as float ) as Expected_Count6_Max,
 cast(Expected_Count7_Min as float ) as Expected_Count7_Min,
 cast(Estimated_Count7 as float ) as Estimated_Count7,
 cast(Expected_Count7_Max as float ) as Expected_Count7_Max,
 cast(Expected_Count8_Min as float ) as Expected_Count8_Min,
 cast(Estimated_Count8 as float ) as Estimated_Count8,
 cast(Expected_Count8_Max as float ) as Expected_Count8_Max,
 cast(Expected_Count9_Min as float ) as Expected_Count9_Min,
 cast(Estimated_Count9 as float ) as Estimated_Count9,
 cast(Expected_Count9_Max as float ) as Expected_Count9_Max,
 cast(Expected_Count10_Min as float ) as Expected_Count10_Min,
 cast(Estimated_Count10 as float ) as Estimated_Count10,
 cast(Expected_Count10_Max as float ) as Expected_Count10_Max,
 cast(Expected_Value1_Min as float ) as Expected_Value1_Min,
 cast(Estimated_Value1 as float ) as Estimated_Value1,
 cast(Expected_Value1_Max as float ) as Expected_Value1_Max,
 cast(Expected_Value2_Min as float ) as Expected_Value2_Min,
 cast(Estimated_Value2 as float ) as Estimated_Value2,
 cast(Expected_Value2_Max as float ) as Expected_Value2_Max,
 cast(Expected_Value3_Min as float ) as Expected_Value3_Min,
 cast(Estimated_Value3 as float ) as Estimated_Value3,
 cast(Expected_Value3_Max as float ) as Expected_Value3_Max,
 cast(Expected_Value4_Min as float ) as Expected_Value4_Min,
 cast(Estimated_Value4 as float ) as Estimated_Value4,
 cast(Expected_Value4_Max as float ) as Expected_Value4_Max,
 cast(Expected_Value5_Min as float ) as Expected_Value5_Min,
 cast(Estimated_Value5 as float ) as Estimated_Value5,
 cast(Expected_Value5_Max as float ) as Expected_Value5_Max 
FROM media_pacing_report_view 
;





