SET QUERY_BAND = '
App_ID=app02432;
DAG_ID=wfm_employee_availability_load_2656_napstore_insights;
Task_Name=wfm_employee_availability_load_1_fct_table;'
FOR SESSION VOLATILE;

ET;

-- Employee job assignment
CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_AVAILABILITY_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.EMPLOYEE_AVAILABILITY_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- Merge and update:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_AVAILABILITY_FACT tgt
    USING WFM_EMPLOYEE_AVAILABILITY_TEMP src
    ON (src.ID = tgt.ID)
    WHEN MATCHED THEN
UPDATE
SET
	EMPLOYEE_ID = src.EMPLOYEE_ID,
	START_DATE = CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    END_DATE = CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD'),
    LOCAL_START_TIME = TIME '00:00:00' + CAST (SRC.LOCAL_START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    LOCAL_END_TIME = TIME '00:00:00' + CAST (SRC.LOCAL_END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
	NUMBER_OF_WEEKS = src.NUMBER_OF_WEEKS,
    CYCLE_BASE_DATE = CAST(src.CYCLE_BASE_DATE as DATE FORMAT 'YYYY-MM-DD'),
    CREATED_AT = src.CREATED_AT,
	LAST_UPDATED_AT = src.LAST_UPDATED_AT,
	IS_CANCELED = src.IS_CANCELED,
	CANCELED_AT = src.CANCELED_AT,
	DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
WHEN NOT MATCHED THEN
INSERT (
    ID,
    EMPLOYEE_ID,
    START_DATE,
    END_DATE,
    LOCAL_START_TIME,
    LOCAL_END_TIME,
    NUMBER_OF_WEEKS,
    CYCLE_BASE_DATE,
    CREATED_AT,
    LAST_UPDATED_AT,
    IS_CANCELED,
    CANCELED_AT,
    DW_SYS_LOAD_TMSTP,
    DW_SYS_UPDT_TMSTP
)
VALUES (
    src.ID,
    src.EMPLOYEE_ID,
    CAST(src.START_DATE as DATE FORMAT 'YYYY-MM-DD'),
    CAST(src.END_DATE as DATE FORMAT 'YYYY-MM-DD'),
    TIME '00:00:00' + CAST (SRC.LOCAL_START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    TIME '00:00:00' + CAST (SRC.LOCAL_END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND,
    src.NUMBER_OF_WEEKS,
    CAST(src.CYCLE_BASE_DATE as DATE FORMAT 'YYYY-MM-DD'),
    src.CREATED_AT,
    src.LAST_UPDATED_AT,
    src.IS_CANCELED,
    src.CANCELED_AT,
	CURRENT_TIMESTAMP(6),
    CURRENT_TIMESTAMP(6)
    );
ET;

CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_AVAILABILITY_DETAILS_TEMP AS (
    SELECT DISTINCT
    ID,
    EMPLOYEE_AVAILABILITY_ID,
    TIME '00:00:00' + CAST(START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND as START_TIME,
    TIME '00:00:00' + CAST(END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND as END_TIME,
    EFFECTIVE_DAY,
    AVAILABILITY_DETAIL_TYPE,
    WEEK_NUMBER,
    CREATED_AT,
    LAST_UPDATED_AT,
    CASE WHEN IS_DELETED = 'true' THEN 1 ELSE 0 END as IS_DELETED,
    DELETED_AT
    FROM {db_env}_NAP_STG.EMPLOYEE_AVAILABILITY_DETAILS_STG
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ID  ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- MERGE AND UPDATE:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_AVAILABILITY_DETAILS_FACT TGT
    USING WFM_EMPLOYEE_AVAILABILITY_DETAILS_TEMP SRC
    ON (SRC.ID = TGT.ID)
    WHEN MATCHED THEN
        UPDATE
            SET
                EMPLOYEE_AVAILABILITY_ID = SRC.EMPLOYEE_AVAILABILITY_ID,
                START_TIME = SRC.START_TIME,
                END_TIME = SRC.END_TIME,
                EFFECTIVE_DAY = SRC.EFFECTIVE_DAY,
                AVAILABILITY_DETAIL_TYPE = SRC.AVAILABILITY_DETAIL_TYPE,
                WEEK_NUMBER = SRC.WEEK_NUMBER,
                CREATED_AT = SRC.CREATED_AT,
                LAST_UPDATED_AT = SRC.LAST_UPDATED_AT,
                IS_DELETED = SRC.IS_DELETED,
                DELETED_AT = SRC.DELETED_AT,
                DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
    WHEN NOT MATCHED THEN
        INSERT (
                ID,
                EMPLOYEE_AVAILABILITY_ID,
                START_TIME,
                END_TIME,
                EFFECTIVE_DAY,
                AVAILABILITY_DETAIL_TYPE,
                WEEK_NUMBER,
                CREATED_AT,
                LAST_UPDATED_AT,
                IS_DELETED,
                DELETED_AT,
                DW_SYS_LOAD_TMSTP,
                DW_SYS_UPDT_TMSTP
            )
            VALUES (SRC.ID,
                    SRC.EMPLOYEE_AVAILABILITY_ID,
                    SRC.START_TIME,
                    SRC.END_TIME,
                    SRC.EFFECTIVE_DAY,
                    SRC.AVAILABILITY_DETAIL_TYPE,
                    SRC.WEEK_NUMBER,
                    SRC.CREATED_AT,
                    SRC.LAST_UPDATED_AT,
                    SRC.IS_DELETED,
                    SRC.DELETED_AT,
                    CURRENT_TIMESTAMP(6),
                    CURRENT_TIMESTAMP(6));

ET;

CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_FIXED_SHIFT_DETAILS_TEMP AS (
    SELECT DISTINCT * FROM {db_env}_NAP_STG.EMPLOYEE_FIXED_SHIFT_DETAILS_STG
    qualify row_number() over (partition BY ID ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;
ET;

-- MERGE AND UPDATE:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_FIXED_SHIFT_DETAILS_FACT TGT
    USING WFM_EMPLOYEE_FIXED_SHIFT_DETAILS_TEMP SRC
    ON (SRC.ID = TGT.ID)
    WHEN MATCHED THEN
        UPDATE
            SET
                EMPLOYEE_AVAILABILITY_ID = SRC.EMPLOYEE_AVAILABILITY_ID,
                EFFECTIVE_DAY = SRC.EFFECTIVE_DAY,
                WEEK_NUMBER = SRC.WEEK_NUMBER,
                CREATED_AT = SRC.CREATED_AT,
                LAST_UPDATED_AT = SRC.LAST_UPDATED_AT,
                IS_DELETED = CASE WHEN SRC.IS_DELETED = 'true' THEN 1 ELSE 0 END,
                DELETED_AT = SRC.DELETED_AT,
                DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
    WHEN NOT MATCHED THEN
        INSERT (
                ID,
                EMPLOYEE_AVAILABILITY_ID,
                EFFECTIVE_DAY,
                WEEK_NUMBER,
                CREATED_AT,
                LAST_UPDATED_AT,
                IS_DELETED,
                DELETED_AT,
                DW_SYS_LOAD_TMSTP,
                DW_SYS_UPDT_TMSTP
            )
            VALUES (SRC.ID,
                    SRC.EMPLOYEE_AVAILABILITY_ID,
                    SRC.EFFECTIVE_DAY,
                    SRC.WEEK_NUMBER,
                    SRC.CREATED_AT,
                    SRC.LAST_UPDATED_AT,
                    CASE WHEN SRC.IS_DELETED = 'true' THEN 1 ELSE 0 END,
                    SRC.DELETED_AT,
                    CURRENT_TIMESTAMP(6),
                    CURRENT_TIMESTAMP(6));

ET;

CREATE
VOLATILE MULTISET TABLE WFM_EMPLOYEE_FIXED_SHIFT_JOB_SEGMENT_DETAILS_TEMP AS (
    SELECT DISTINCT
    ID,
    EMPLOYEE_FIXED_SHIFT_DETAILS_ID,
    JOB_ID,
    TIME '00:00:00' + CAST(START_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND as START_TIME,
    TIME '00:00:00' + CAST(END_TIME AS INTEGER) / 1000 * INTERVAL '00:00:01' HOUR TO SECOND as END_TIME,
    CREATED_AT,
    LAST_UPDATED_AT,
    CASE WHEN IS_DELETED = 'true' THEN 1 ELSE 0 END as IS_DELETED,
    DELETED_AT
    FROM {db_env}_NAP_STG.EMPLOYEE_FIXED_SHIFT_JOB_SEGMENT_DETAILS_STG
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ID  ORDER BY LAST_UPDATED_AT DESC, KAFKA_LAST_UPDATED_AT DESC) = 1
) WITH DATA PRIMARY INDEX(ID) ON COMMIT PRESERVE ROWS;

ET;
-- MERGE AND UPDATE:
MERGE INTO {db_env}_NAP_FCT.EMPLOYEE_FIXED_SHIFT_JOB_SEGMENT_DETAILS_FACT TGT
    USING WFM_EMPLOYEE_FIXED_SHIFT_JOB_SEGMENT_DETAILS_TEMP SRC
    ON (SRC.ID = TGT.ID)
    WHEN MATCHED THEN
        UPDATE
            SET
                EMPLOYEE_FIXED_SHIFT_DETAILS_ID = SRC.EMPLOYEE_FIXED_SHIFT_DETAILS_ID,
                JOB_ID = SRC.JOB_ID,
                START_TIME = SRC.START_TIME,
                END_TIME = SRC.END_TIME,
                CREATED_AT = SRC.CREATED_AT,
                LAST_UPDATED_AT = SRC.LAST_UPDATED_AT,
                IS_DELETED = SRC.IS_DELETED,
                DELETED_AT = SRC.DELETED_AT,
                DW_SYS_UPDT_TMSTP = CURRENT_TIMESTAMP(6)
    WHEN NOT MATCHED THEN
        INSERT (
                ID,
                EMPLOYEE_FIXED_SHIFT_DETAILS_ID,
                JOB_ID,
                START_TIME,
                END_TIME,
                CREATED_AT,
                LAST_UPDATED_AT,
                IS_DELETED,
                DELETED_AT,
                DW_SYS_LOAD_TMSTP,
                DW_SYS_UPDT_TMSTP
            )
            VALUES (SRC.ID,
                    SRC.EMPLOYEE_FIXED_SHIFT_DETAILS_ID,
                    SRC.JOB_ID,
                    SRC.START_TIME,
                    SRC.END_TIME,
                    SRC.CREATED_AT,
                    SRC.LAST_UPDATED_AT,
                    SRC.IS_DELETED,
                    SRC.DELETED_AT,
                    CURRENT_TIMESTAMP(6),
                    CURRENT_TIMESTAMP(6));
ET;

SET QUERY_BAND = NONE FOR SESSION;

ET;
