/*
Purpose:          Inserts data in {{environment_schema}} tables for supplier profitability
                            supplier_profitability_expectation_channel_week_dept
Variable(s):     {{environment_schema}} t2dl_das_strategic_brand_management_reporting
                 {{wk_end_dt}} current_date -1(refreshes every week)
Author(s):       Manuela Hurtado Gonzalez
Updated: 		 1/11/24 by Alli Moore - 53rd Week Prep
*/

CREATE TEMPORARY TABLE IF NOT EXISTS sku_lkup

AS
SELECT DISTINCT sku.rms_sku_num,
 sku.channel_country,
   TRIM(FORMAT('%11d', sku.div_num)) || ', ' || TRIM(sku.div_desc) AS div_label,
 TRIM(FORMAT('%11d', sku.grp_num) || ', ' || sku.grp_desc) AS sdiv_label,
 TRIM(FORMAT('%11d', sku.dept_num) || ', ' || sku.dept_desc) AS dept_label,
 TRIM(FORMAT('%11d', sku.dept_num)) AS dept_idnt,
 sku.prmy_supp_num AS supplier_number,
 sku.brand_name,
 sku.brand_label_display_name AS brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 supp.vendor_name AS supplier
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.product_sku_dim_vw AS sku
 LEFT JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.vendor_dim AS supp ON LOWER(sku.prmy_supp_num) = LOWER(supp.vendor_num)
WHERE LOWER(sku.gwp_ind) <> LOWER('Y')
 AND CAST(TRIM(FORMAT('%11d', sku.dept_num)) AS FLOAT64) <> - 1
 AND LOWER(sku.channel_country) = LOWER('US')
 AND LOWER(sku.prmy_supp_num) <> LOWER('-1')
 AND LOWER(TRIM(FORMAT('%11d', sku.dept_num) || ', ' || sku.dept_desc)) NOT LIKE LOWER('%inact%')
 AND LOWER(TRIM(FORMAT('%11d', sku.div_num)) || ', ' || TRIM(sku.div_desc)) NOT LIKE LOWER('%inact%')
 AND LOWER(TRIM(FORMAT('%11d', sku.grp_num) || ', ' || sku.grp_desc)) NOT LIKE LOWER('%inact%');


CREATE TEMPORARY TABLE IF NOT EXISTS supplier_lkup

AS
SELECT supplier_num,
 dept_num,
 banner,
 supplier_group
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.supp_dept_map_dim
WHERE LOWER(supplier_group) <> LOWER('-1');


CREATE TEMPORARY TABLE IF NOT EXISTS supp_prof

AS
SELECT s.supplier_group,
 s.department_number AS dept_num,
  CASE
  WHEN LOWER(b.banner_desc) LIKE LOWER('OFF_PRICE')
  THEN 'OP'
  WHEN LOWER(b.banner_desc) LIKE LOWER('FULL_PRICE')
  THEN 'FP'
  ELSE NULL
  END AS banner,
 s.selling_country AS channel_country,
 s.year_num AS fiscal_year_num,
 s.planned_profitability_expectation_percent AS ty_profitability_expectation,
 s.regular_price_sales_expectation_percent AS ty_reg_sales_expectation,
 s.initial_markup_expectation_percent AS ty_initial_markup_expectation
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_vws.merch_spe_profitability_expectation_vw AS s
 INNER JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_vws.org_banner_country_dim AS b ON s.banner_num = b.banner_country_num
WHERE s.year_num IN (SELECT fiscal_year_num
   FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.day_cal_454_dim
   WHERE fiscal_year_num >= (SELECT MAX(fiscal_year_num) - 1 AS ty_fiscal_yr
      FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.day_cal_454_dim
      WHERE week_end_day_date < CURRENT_DATE('PST8PDT'))
   GROUP BY fiscal_year_num)
 AND LOWER(s.supplier_group) <> LOWER('-1')
 AND LOWER(s.selling_country) = LOWER('US');


CREATE TEMPORARY TABLE IF NOT EXISTS store_lkup

AS
SELECT DISTINCT store_num,
 business_unit_desc,
 channel_num,
 channel_desc,
 store_country_code,
  CASE
  WHEN channel_num IN (210, 211, 220, 221, 240, 250, 260, 261)
  THEN 'OP'
  ELSE 'FP'
  END AS banner
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.store_dim
WHERE LOWER(store_country_code) = LOWER('US')
 AND channel_num NOT IN (580, 922, 921, 990, 940);


CREATE TEMPORARY TABLE IF NOT EXISTS date_lkup

AS
SELECT DISTINCT wk.ty_ly_lly_ind AS ty_ly_ind,
 wk.fiscal_year_num,
 wk.fiscal_halfyear_num,
 wk.quarter_abrv,
 wk.quarter_label,
 wk.month_abrv,
 wk.month_idnt,
 wk.month_label,
 wk.week_desc,
 CONCAT(SUBSTR(wk.week_label, 0, 9), 'WK', TRIM(FORMAT('%11d', wk.week_num_of_fiscal_month))) AS week_label,
 wk.week_idnt,
 wk.fiscal_week_num,
 wk.week_start_day_date,
 wk.week_end_day_date,
 b.week_idnt AS week_idnt_true
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_vws.realigned_date_lkup_vw AS wk
 LEFT JOIN `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.day_cal_454_dim AS b ON wk.day_date = b.day_date
WHERE LOWER(wk.ty_ly_lly_ind) IN (LOWER('TY'), LOWER('LY'))
 AND wk.week_end_day_date <= DATE_SUB(CURRENT_DATE('PST8PDT'), INTERVAL 1 DAY);


CREATE TEMPORARY TABLE IF NOT EXISTS sb_lkup

AS
SELECT CASE
  WHEN LOWER(sb_banner) = LOWER('NORDSTROM')
  THEN 'FP'
  ELSE 'OP'
  END AS banner,
 vendor_brand_code,
 vendor_brand_name_adj AS vendor_brand_name,
 supplier_num,
 dept_num,
 supplier_group,
 'Y' AS sb_ind
FROM `{{params.gcp_project_id}}`.{{params.environment_schema}}.strat_brands_supp_curr_vw
WHERE LOWER(CASE
    WHEN LOWER(sb_banner) = LOWER('NORDSTROM')
    THEN 'FP'
    ELSE 'OP'
    END) = LOWER('FP')
 AND LOWER(supplier_group) NOT LIKE LOWER('OTHER')
 AND LOWER(supplier_group) NOT LIKE LOWER('% OTHER')
 AND LOWER(supplier_group) NOT LIKE LOWER('OTHER %');


CREATE TEMPORARY TABLE IF NOT EXISTS sales_stg

AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 COALESCE(sales.net_sales_tot_retl, 0) AS net_sales_tot_retl,
 COALESCE(sales.net_sales_tot_regular_retl, 0) AS net_sales_tot_regular_retl,
 COALESCE(sales.net_sales_tot_promo_retl, 0) AS net_sales_tot_promo_retl,
 COALESCE(sales.net_sales_tot_clearance_retl, 0) AS net_sales_tot_clearance_retl,
 COALESCE(sales.net_sales_tot_cost, 0) AS net_sales_tot_cost,
 COALESCE(sales.net_sales_tot_regular_cost, 0) AS net_sales_tot_regular_cost,
 COALESCE(sales.net_sales_tot_promo_cost, 0) AS net_sales_tot_promo_cost,
 COALESCE(sales.net_sales_tot_clearance_cost, 0) AS net_sales_tot_clearance_cost,
 COALESCE(sales.net_sales_tot_units, 0) AS net_sales_tot_units,
 COALESCE(sales.net_sales_tot_regular_units, 0) AS net_sales_tot_regular_units,
 COALESCE(sales.net_sales_tot_promo_units, 0) AS net_sales_tot_promo_units,
 COALESCE(sales.net_sales_tot_clearance_units, 0) AS net_sales_tot_clearance_units,
 COALESCE(sales.returns_tot_retl, 0) AS returns_tot_retl,
 COALESCE(sales.returns_tot_regular_retl, 0) AS returns_tot_regular_retl,
 COALESCE(sales.returns_tot_promo_retl, 0) AS returns_tot_promo_retl,
 COALESCE(sales.returns_tot_clearance_retl, 0) AS returns_tot_clearance_retl,
 COALESCE(sales.returns_tot_cost, 0) AS returns_tot_cost,
 COALESCE(sales.returns_tot_regular_cost, 0) AS returns_tot_regular_cost,
 COALESCE(sales.returns_tot_promo_cost, 0) AS returns_tot_promo_cost,
 COALESCE(sales.returns_tot_clearance_cost, 0) AS returns_tot_clearance_cost,
 COALESCE(sales.returns_tot_units, 0) AS returns_tot_units,
 COALESCE(sales.returns_tot_regular_units, 0) AS returns_tot_regular_units,
 COALESCE(sales.returns_tot_promo_units, 0) AS returns_tot_promo_units,
 COALESCE(sales.returns_tot_clearance_units, 0) AS returns_tot_clearance_units,
 COALESCE(CASE
   WHEN LOWER(sales.dropship_ind) = LOWER('Y')
   THEN sales.net_sales_tot_retl
   ELSE 0
   END, 0) AS dropship_net_sales_tot_retl,
 COALESCE(CASE
   WHEN LOWER(sales.dropship_ind) = LOWER('Y')
   THEN sales.net_sales_tot_cost
   ELSE 0
   END, 0) AS dropship_net_sales_tot_cost,
 COALESCE(CASE
   WHEN LOWER(sales.dropship_ind) = LOWER('Y')
   THEN sales.net_sales_tot_units
   ELSE 0
   END, 0) AS dropship_net_sales_tot_units
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_sale_return_sku_store_week_fact_vw AS sales
 INNER JOIN date_lkup AS dt ON sales.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON sales.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(sales.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920
 AND LOWER(sales.wac_avlbl_ind) = LOWER('Y');


CREATE TEMPORARY TABLE IF NOT EXISTS sales_final

AS
SELECT ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier,
 SUM(net_sales_tot_retl) AS net_sales_tot_retl,
 SUM(net_sales_tot_regular_retl) AS net_sales_tot_regular_retl,
 SUM(net_sales_tot_promo_retl) AS net_sales_tot_promo_retl,
 SUM(net_sales_tot_clearance_retl) AS net_sales_tot_clearance_retl,
 SUM(net_sales_tot_cost) AS net_sales_tot_cost,
 SUM(net_sales_tot_regular_cost) AS net_sales_tot_regular_cost,
 SUM(net_sales_tot_promo_cost) AS net_sales_tot_promo_cost,
 SUM(net_sales_tot_clearance_cost) AS net_sales_tot_clearance_cost,
 SUM(net_sales_tot_units) AS net_sales_tot_units,
 SUM(net_sales_tot_regular_units) AS net_sales_tot_regular_units,
 SUM(net_sales_tot_promo_units) AS net_sales_tot_promo_units,
 SUM(net_sales_tot_clearance_units) AS net_sales_tot_clearance_units,
 SUM(returns_tot_retl) AS returns_tot_retl,
 SUM(returns_tot_regular_retl) AS returns_tot_regular_retl,
 SUM(returns_tot_promo_retl) AS returns_tot_promo_retl,
 SUM(returns_tot_clearance_retl) AS returns_tot_clearance_retl,
 SUM(returns_tot_cost) AS returns_tot_cost,
 SUM(returns_tot_regular_cost) AS returns_tot_regular_cost,
 SUM(returns_tot_promo_cost) AS returns_tot_promo_cost,
 SUM(returns_tot_clearance_cost) AS returns_tot_clearance_cost,
 SUM(returns_tot_units) AS returns_tot_units,
 SUM(returns_tot_regular_units) AS returns_tot_regular_units,
 SUM(returns_tot_promo_units) AS returns_tot_promo_units,
 SUM(returns_tot_clearance_units) AS returns_tot_clearance_units,
 SUM(dropship_net_sales_tot_retl) AS dropship_net_sales_tot_retl,
 SUM(dropship_net_sales_tot_cost) AS dropship_net_sales_tot_cost,
 SUM(dropship_net_sales_tot_units) AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM sales_stg
GROUP BY ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS demand_stg

AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 COALESCE(dmd.demand_tot_amt, 0) AS demand_tot_amt,
 COALESCE(dmd.demand_regular_amt, 0) AS demand_regular_amt,
 COALESCE(dmd.demand_promo_amt, 0) AS demand_promo_amt,
 COALESCE(dmd.demand_clearence_amt, 0) AS demand_clearence_amt,
 COALESCE(dmd.demand_unknown_amt, 0) AS demand_unknown_amt,
 COALESCE(dmd.demand_tot_qty, 0) AS demand_tot_qty,
 COALESCE(dmd.demand_regular_qty, 0) AS demand_regular_qty,
 COALESCE(dmd.demand_promo_qty, 0) AS demand_promo_qty,
 COALESCE(dmd.demand_clearence_qty, 0) AS demand_clearence_qty,
 COALESCE(dmd.demand_unknown_qty, 0) AS demand_unknown_qty
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_demand_sku_store_week_agg_fact_vw AS dmd
 INNER JOIN date_lkup AS dt ON dmd.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON dmd.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(dmd.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920;


CREATE TEMPORARY TABLE IF NOT EXISTS demand_final

AS
SELECT ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 SUM(demand_tot_amt) AS demand_tot_amt,
 SUM(demand_regular_amt) AS demand_regular_amt,
 SUM(demand_promo_amt) AS demand_promo_amt,
 SUM(demand_clearence_amt) AS demand_clearence_amt,
 SUM(demand_unknown_amt) AS demand_unknown_amt,
 SUM(demand_tot_qty) AS demand_tot_qty,
 SUM(demand_regular_qty) AS demand_regular_qty,
 SUM(demand_promo_qty) AS demand_promo_qty,
 SUM(demand_clearence_qty) AS demand_clearence_qty,
 SUM(demand_unknown_qty) AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM demand_stg
GROUP BY ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS receipts_stg

AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
    COALESCE(receipts.receipts_regular_units, 0) + COALESCE(receipts.receipts_clearance_units, 0) + COALESCE(receipts.receipts_crossdock_regular_units
    , 0) + COALESCE(receipts.receipts_crossdock_clearance_units, 0) AS total_receipts_units,
    COALESCE(receipts.receipts_regular_cost, 0) + COALESCE(receipts.receipts_clearance_cost, 0) + COALESCE(receipts.receipts_crossdock_regular_cost
    , 0) + COALESCE(receipts.receipts_crossdock_clearance_cost, 0) AS total_receipts_cost,
    COALESCE(receipts.receipts_regular_retail, 0) + COALESCE(receipts.receipts_clearance_retail, 0) + COALESCE(receipts
    .receipts_crossdock_regular_retail, 0) + COALESCE(receipts.receipts_crossdock_clearance_retail, 0) AS
 total_receipts_retail,
 COALESCE(CASE
   WHEN LOWER(receipts.dropship_ind) = LOWER('Y')
   THEN COALESCE(receipts.receipts_regular_units, 0) + COALESCE(receipts.receipts_clearance_units, 0) + COALESCE(receipts
      .receipts_crossdock_regular_units, 0) + COALESCE(receipts.receipts_crossdock_clearance_units, 0)
   ELSE 0
   END, 0) AS dropship_receipts_units,
 COALESCE(CASE
   WHEN LOWER(receipts.dropship_ind) = LOWER('Y')
   THEN COALESCE(receipts.receipts_regular_cost, 0) + COALESCE(receipts.receipts_clearance_cost, 0) + COALESCE(receipts
      .receipts_crossdock_regular_cost, 0) + COALESCE(receipts.receipts_crossdock_clearance_cost, 0)
   ELSE 0
   END, 0) AS dropship_receipts_cost,
 COALESCE(CASE
   WHEN LOWER(receipts.dropship_ind) = LOWER('Y')
   THEN COALESCE(receipts.receipts_regular_retail, 0) + COALESCE(receipts.receipts_clearance_retail, 0) + COALESCE(receipts
      .receipts_crossdock_regular_retail, 0) + COALESCE(receipts.receipts_crossdock_clearance_retail, 0)
   ELSE 0
   END, 0) AS dropship_receipts_retail
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_poreceipt_sku_store_week_fact_vw AS receipts
 INNER JOIN date_lkup AS dt ON receipts.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON receipts.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(receipts.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920;


CREATE TEMPORARY TABLE IF NOT EXISTS receipts_final

AS
SELECT ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 SUM(total_receipts_units) AS total_receipts_units,
 SUM(total_receipts_cost) AS total_receipts_cost,
 SUM(total_receipts_retail) AS total_receipts_retail,
 SUM(dropship_receipts_units) AS dropship_receipts_units,
 SUM(dropship_receipts_cost) AS dropship_receipts_cost,
 SUM(dropship_receipts_retail) AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM receipts_stg
GROUP BY ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS transfer_stg

AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 COALESCE(transfer.packandhold_transfer_in_units, 0) AS packandhold_transfer_in_units,
 COALESCE(transfer.packandhold_transfer_out_units, 0) AS packandhold_transfer_out_units,
 COALESCE(transfer.reservestock_transfer_in_units, 0) AS reservestock_transfer_in_units,
 COALESCE(transfer.reservestock_transfer_out_units, 0) AS reservestock_transfer_out_units,
 COALESCE(transfer.packandhold_transfer_in_retail, 0) AS packandhold_transfer_in_retail,
 COALESCE(transfer.packandhold_transfer_out_retail, 0) AS packandhold_transfer_out_retail,
 COALESCE(transfer.packandhold_transfer_in_cost, 0) AS packandhold_transfer_in_cost,
 COALESCE(transfer.packandhold_transfer_out_cost, 0) AS packandhold_transfer_out_cost,
 COALESCE(transfer.reservestock_transfer_in_cost, 0) AS reservestock_transfer_in_cost,
 COALESCE(transfer.reservestock_transfer_out_cost, 0) AS reservestock_transfer_out_cost,
 COALESCE(transfer.reservestock_transfer_in_retail, 0) AS reservestock_transfer_in_retail,
 COALESCE(transfer.reservestock_transfer_out_retail, 0) AS reservestock_transfer_out_retail
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_transfer_sku_loc_week_agg_fact_vw AS transfer
 INNER JOIN date_lkup AS dt ON transfer.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON transfer.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(transfer.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920;


CREATE TEMPORARY TABLE IF NOT EXISTS transfer_final

AS
SELECT ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 SUM(packandhold_transfer_in_units) AS packandhold_transfer_in_units,
 SUM(packandhold_transfer_out_units) AS packandhold_transfer_out_units,
 SUM(reservestock_transfer_in_units) AS reservestock_transfer_in_units,
 SUM(reservestock_transfer_out_units) AS reservestock_transfer_out_units,
 SUM(packandhold_transfer_in_retail) AS packandhold_transfer_in_retail,
 SUM(packandhold_transfer_out_retail) AS packandhold_transfer_out_retail,
 SUM(packandhold_transfer_in_cost) AS packandhold_transfer_in_cost,
 SUM(packandhold_transfer_out_cost) AS packandhold_transfer_out_cost,
 SUM(reservestock_transfer_in_cost) AS reservestock_transfer_in_cost,
 SUM(reservestock_transfer_out_cost) AS reservestock_transfer_out_cost,
 SUM(reservestock_transfer_in_retail) AS reservestock_transfer_in_retail,
 SUM(reservestock_transfer_out_retail) AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM transfer_stg
GROUP BY ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS vendor_terms_final

AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 SUM(COALESCE(terms.disc_terms_cost, 0)) AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_disc_terms_sku_loc_week_agg_fact_vw AS terms
 INNER JOIN date_lkup AS dt ON terms.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON terms.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(terms.rms_sku_num) = LOWER(sku.rms_sku_num)
GROUP BY dt.ty_ly_ind,
 dt.week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS vendor_funds_stg

AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 COALESCE(vfm.vendor_funds_retail, 0) AS vendor_funds_retail,
 COALESCE(vfm.vendor_funds_cost, 0) AS vendor_funds_cost
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_vendor_funds_sku_store_week_fact_vw AS vfm
 INNER JOIN date_lkup AS dt ON vfm.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON vfm.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(vfm.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920;


CREATE TEMPORARY TABLE IF NOT EXISTS vfm_final
AS
SELECT ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 SUM(vendor_funds_retail) AS vendor_funds_retail,
 SUM(vendor_funds_cost) AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM vendor_funds_stg
GROUP BY ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS inventory_stg
AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 COALESCE(inventory.boh_total_cost, 0) AS boh_total_cost,
 COALESCE(inventory.boh_total_units, 0) AS boh_total_units,
 COALESCE(inventory.boh_total_retail, 0) AS boh_total_retail,
 COALESCE(inventory.boh_clearance_cost, 0) AS boh_clearance_cost,
 COALESCE(inventory.boh_clearance_units, 0) AS boh_clearance_units,
 COALESCE(inventory.boh_clearance_retail, 0) AS boh_clearance_retail,
 COALESCE(inventory.boh_regular_cost, 0) AS boh_regular_cost,
 COALESCE(inventory.boh_regular_units, 0) AS boh_regular_units,
 COALESCE(inventory.boh_regular_retail, 0) AS boh_regular_retail,
 COALESCE(inventory.eoh_total_cost, 0) AS eoh_total_cost,
 COALESCE(inventory.eoh_total_units, 0) AS eoh_total_units,
 COALESCE(inventory.eoh_total_retail, 0) AS eoh_total_retail,
 COALESCE(inventory.eoh_clearance_cost, 0) AS eoh_clearance_cost,
 COALESCE(inventory.eoh_clearance_units, 0) AS eoh_clearance_units,
 COALESCE(inventory.eoh_clearance_retail, 0) AS eoh_clearance_retail,
 COALESCE(inventory.eoh_regular_cost, 0) AS eoh_regular_cost,
 COALESCE(inventory.eoh_regular_units, 0) AS eoh_regular_units,
 COALESCE(inventory.eoh_regular_retail, 0) AS eoh_regular_retail
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_inventory_sku_store_week_fact_vw AS inventory
 INNER JOIN date_lkup AS dt ON inventory.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON CAST(inventory.store_num AS FLOAT64) = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(inventory.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920;


CREATE TEMPORARY TABLE IF NOT EXISTS inventory_final
AS
SELECT ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 SUM(boh_total_cost) AS boh_total_cost,
 SUM(boh_total_units) AS boh_total_units,
 SUM(boh_total_retail) AS boh_total_retail,
 SUM(boh_clearance_cost) AS boh_clearance_cost,
 SUM(boh_clearance_units) AS boh_clearance_units,
 SUM(boh_clearance_retail) AS boh_clearance_retail,
 SUM(boh_regular_cost) AS boh_regular_cost,
 SUM(boh_regular_units) AS boh_regular_units,
 SUM(boh_regular_retail) AS boh_regular_retail,
 SUM(eoh_total_cost) AS eoh_total_cost,
 SUM(eoh_total_units) AS eoh_total_units,
 SUM(eoh_total_retail) AS eoh_total_retail,
 SUM(eoh_clearance_cost) AS eoh_clearance_cost,
 SUM(eoh_clearance_units) AS eoh_clearance_units,
 SUM(eoh_clearance_retail) AS eoh_clearance_retail,
 SUM(eoh_regular_cost) AS eoh_regular_cost,
 SUM(eoh_regular_units) AS eoh_regular_units,
 SUM(eoh_regular_retail) AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM inventory_stg
GROUP BY ty_ly_ind,
 week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 div_label,
 sdiv_label,
 dept_label,
 dept_idnt,
 supplier_number,
 brand_name,
 brand_label,
 brand_label_num,
 npg_ind,
 supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS mos_final
AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 SUM(COALESCE(mos.mos_adjusted_total_cost, 0)) AS mos_total_cost_amt,
 SUM(COALESCE(mos.mos_adjusted_total_units, 0)) AS mos_total_units,
 SUM(COALESCE(mos.mos_adjusted_total_retail, 0)) AS mos_total_retail_amt,
 0 AS rtv_total_cost,
 0 AS rtv_total_retail,
 0 AS rtv_total_units
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_sp_mos_adjusted_sku_store_week_agg_fact AS mos
 INNER JOIN date_lkup AS dt ON mos.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON mos.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(mos.rms_sku_num) = LOWER(sku.rms_sku_num)
WHERE store.channel_num <> 920
GROUP BY dt.ty_ly_ind,
 dt.week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier;


CREATE TEMPORARY TABLE IF NOT EXISTS rtv_final
AS
SELECT dt.ty_ly_ind,
 dt.week_idnt,
 COALESCE(store.business_unit_desc, 'N/A') AS business_unit_desc,
 COALESCE(store.channel_num, - 1) AS channel_num,
 COALESCE(store.channel_desc, 'N/A') AS channel_desc,
 SUBSTR(COALESCE(store.store_country_code, 'N/A'), 1, 3) AS country_code,
 RPAD(COALESCE(store.banner, 'N/A'), 3, ' ') AS banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier,
 0 AS net_sales_tot_retl,
 0 AS net_sales_tot_regular_retl,
 0 AS net_sales_tot_promo_retl,
 0 AS net_sales_tot_clearance_retl,
 0 AS net_sales_tot_cost,
 0 AS net_sales_tot_regular_cost,
 0 AS net_sales_tot_promo_cost,
 0 AS net_sales_tot_clearance_cost,
 0 AS net_sales_tot_units,
 0 AS net_sales_tot_regular_units,
 0 AS net_sales_tot_promo_units,
 0 AS net_sales_tot_clearance_units,
 0 AS returns_tot_retl,
 0 AS returns_tot_regular_retl,
 0 AS returns_tot_promo_retl,
 0 AS returns_tot_clearance_retl,
 0 AS returns_tot_cost,
 0 AS returns_tot_regular_cost,
 0 AS returns_tot_promo_cost,
 0 AS returns_tot_clearance_cost,
 0 AS returns_tot_units,
 0 AS returns_tot_regular_units,
 0 AS returns_tot_promo_units,
 0 AS returns_tot_clearance_units,
 0 AS dropship_net_sales_tot_retl,
 0 AS dropship_net_sales_tot_cost,
 0 AS dropship_net_sales_tot_units,
 0 AS demand_tot_amt,
 0 AS demand_regular_amt,
 0 AS demand_promo_amt,
 0 AS demand_clearence_amt,
 0 AS demand_unknown_amt,
 0 AS demand_tot_qty,
 0 AS demand_regular_qty,
 0 AS demand_promo_qty,
 0 AS demand_clearence_qty,
 0 AS demand_unknown_qty,
 0 AS total_receipts_units,
 0 AS total_receipts_cost,
 0 AS total_receipts_retail,
 0 AS dropship_receipts_units,
 0 AS dropship_receipts_cost,
 0 AS dropship_receipts_retail,
 0 AS packandhold_transfer_in_units,
 0 AS packandhold_transfer_out_units,
 0 AS reservestock_transfer_in_units,
 0 AS reservestock_transfer_out_units,
 0 AS packandhold_transfer_in_retail,
 0 AS packandhold_transfer_out_retail,
 0 AS packandhold_transfer_in_cost,
 0 AS packandhold_transfer_out_cost,
 0 AS reservestock_transfer_in_cost,
 0 AS reservestock_transfer_out_cost,
 0 AS reservestock_transfer_in_retail,
 0 AS reservestock_transfer_out_retail,
 0 AS disc_terms_cost,
 0 AS vendor_funds_retail,
 0 AS vendor_funds_cost,
 0 AS boh_total_cost,
 0 AS boh_total_units,
 0 AS boh_total_retail,
 0 AS boh_clearance_cost,
 0 AS boh_clearance_units,
 0 AS boh_clearance_retail,
 0 AS boh_regular_cost,
 0 AS boh_regular_units,
 0 AS boh_regular_retail,
 0 AS eoh_total_cost,
 0 AS eoh_total_units,
 0 AS eoh_total_retail,
 0 AS eoh_clearance_cost,
 0 AS eoh_clearance_units,
 0 AS eoh_clearance_retail,
 0 AS eoh_regular_cost,
 0 AS eoh_regular_units,
 0 AS eoh_regular_retail,
 0 AS mos_total_cost_amt,
 0 AS mos_total_units,
 0 AS mos_total_retail_amt,
 SUM(COALESCE(rtv.rtv_total_cost, 0)) AS rtv_total_cost,
 SUM(COALESCE(rtv.rtv_total_retail, 0)) AS rtv_total_retail,
 SUM(COALESCE(rtv.rtv_total_units, 0)) AS rtv_total_units
FROM `{{params.gcp_project_id}}`.{{params.dbenv}}_nap_usr_vws.merch_return_to_vendor_sku_loc_week_agg_fact_vw AS rtv
 INNER JOIN date_lkup AS dt ON rtv.week_num = dt.week_idnt_true
 INNER JOIN store_lkup AS store ON rtv.store_num = store.store_num
 INNER JOIN sku_lkup AS sku ON LOWER(rtv.rms_sku_num) = LOWER(sku.rms_sku_num)
GROUP BY dt.ty_ly_ind,
 dt.week_idnt,
 business_unit_desc,
 channel_num,
 channel_desc,
 country_code,
 banner,
 sku.div_label,
 sku.sdiv_label,
 sku.dept_label,
 sku.dept_idnt,
 sku.supplier_number,
 sku.brand_name,
 sku.brand_label,
 sku.brand_label_num,
 sku.npg_ind,
 sku.supplier;


TRUNCATE TABLE `{{params.gcp_project_id}}`.{{params.environment_schema}}.supplier_profitability_expectation_channel_week_dept;


INSERT INTO `{{params.gcp_project_id}}`.{{params.environment_schema}}.supplier_profitability_expectation_channel_week_dept
(SELECT base.ty_ly_ind,
  base.week_idnt,
  d.fiscal_year_num,
  d.fiscal_halfyear_num,
  d.quarter_abrv,
  d.quarter_label,
  d.month_abrv,
  d.month_idnt,
  d.month_label,
  d.week_label,
  d.week_desc,
  d.fiscal_week_num,
  d.week_start_day_date,
  d.week_end_day_date,
  base.business_unit_desc,
  base.channel_num,
  base.channel_desc,
  base.country_code,
  base.banner,
  base.div_label,
  base.sdiv_label,
  base.dept_label,
  CAST(TRUNC(CAST(base.dept_idnt AS FLOAT64)) AS INTEGER) AS dept_idnt,
  CAST(TRUNC(CAST(base.supplier_number AS FLOAT64)) AS INTEGER) AS supplier_number,
  base.brand_name,
  base.brand_label,
  CAST(TRUNC(CAST(base.brand_label_num AS FLOAT64)) AS INTEGER) AS brand_label_num,
  base.npg_ind,
  COALESCE(sb.sb_ind, 'N'),
  base.supplier,
  COALESCE(supp.supplier_group, 'N/A') AS supplier_group,
  ROUND(CAST(SUM(base.net_sales_tot_retl) AS NUMERIC), 2) AS net_sales_tot_retl,
  ROUND(CAST(SUM(base.net_sales_tot_regular_retl) AS NUMERIC), 2) AS net_sales_tot_regular_retl,
  ROUND(CAST(SUM(base.net_sales_tot_promo_retl) AS NUMERIC), 2) AS net_sales_tot_promo_retl,
  ROUND(CAST(SUM(base.net_sales_tot_clearance_retl) AS NUMERIC), 2) AS net_sales_tot_clearance_retl,
  ROUND(CAST(SUM(base.net_sales_tot_cost) AS NUMERIC), 2) AS net_sales_tot_cost,
  ROUND(CAST(SUM(base.net_sales_tot_regular_cost) AS NUMERIC), 2) AS net_sales_tot_regular_cost,
  ROUND(CAST(SUM(base.net_sales_tot_promo_cost) AS NUMERIC), 2) AS net_sales_tot_promo_cost,
  ROUND(CAST(SUM(base.net_sales_tot_clearance_cost) AS NUMERIC), 2) AS net_sales_tot_clearance_cost,
  CAST(TRUNC(SUM(base.net_sales_tot_units)) AS INTEGER) AS net_sales_tot_units,
  CAST(TRUNC(SUM(base.net_sales_tot_regular_units)) AS INTEGER) AS net_sales_tot_regular_units,
  CAST(TRUNC(SUM(base.net_sales_tot_promo_units)) AS INTEGER) AS net_sales_tot_promo_units,
  CAST(TRUNC(SUM(base.net_sales_tot_clearance_units)) AS INTEGER) AS net_sales_tot_clearance_units,
  ROUND(CAST(SUM(base.returns_tot_retl) AS NUMERIC), 2) AS returns_tot_retl,
  ROUND(CAST(SUM(base.returns_tot_regular_retl) AS NUMERIC), 2) AS returns_tot_regular_retl,
  ROUND(CAST(SUM(base.returns_tot_promo_retl) AS NUMERIC), 2) AS returns_tot_promo_retl,
  ROUND(CAST(SUM(base.returns_tot_clearance_retl) AS NUMERIC), 2) AS returns_tot_clearance_retl,
  ROUND(CAST(SUM(base.returns_tot_cost) AS NUMERIC), 2) AS returns_tot_cost,
  ROUND(CAST(SUM(base.returns_tot_regular_cost) AS NUMERIC), 2) AS returns_tot_regular_cost,
  ROUND(CAST(SUM(base.returns_tot_promo_cost) AS NUMERIC), 2) AS returns_tot_promo_cost,
  ROUND(CAST(SUM(base.returns_tot_clearance_cost) AS NUMERIC), 2) AS returns_tot_clearance_cost,
  CAST(TRUNC(SUM(base.returns_tot_units)) AS INTEGER) AS returns_tot_units,
  CAST(TRUNC(SUM(base.returns_tot_regular_units)) AS INTEGER) AS returns_tot_regular_units,
  CAST(TRUNC(SUM(base.returns_tot_promo_units)) AS INTEGER) AS returns_tot_promo_units,
  CAST(TRUNC(SUM(base.returns_tot_clearance_units)) AS INTEGER) AS returns_tot_clearance_units,
  CAST(SUM(base.dropship_net_sales_tot_retl) AS NUMERIC) AS dropship_net_sales_tot_retl,
  CAST(SUM(base.dropship_net_sales_tot_cost) AS NUMERIC) AS dropship_net_sales_tot_cost,
  CAST(TRUNC(SUM(base.dropship_net_sales_tot_units)) AS INTEGER) AS dropship_net_sales_tot_units,
  ROUND(CAST(SUM(base.demand_tot_amt) AS NUMERIC), 2) AS demand_tot_amt,
  ROUND(CAST(SUM(base.demand_regular_amt) AS NUMERIC), 2) AS demand_regular_amt,
  ROUND(CAST(SUM(base.demand_promo_amt) AS NUMERIC), 2) AS demand_promo_amt,
  ROUND(CAST(SUM(base.demand_clearence_amt) AS NUMERIC), 2) AS demand_clearence_amt,
  ROUND(CAST(SUM(base.demand_unknown_amt) AS NUMERIC), 2) AS demand_unknown_amt,
  CAST(TRUNC(SUM(base.demand_tot_qty)) AS INTEGER) AS demand_tot_qty,
  CAST(TRUNC(SUM(base.demand_regular_qty)) AS INTEGER) AS demand_regular_qty,
  CAST(TRUNC(SUM(base.demand_promo_qty)) AS INTEGER) AS demand_promo_qty,
  CAST(TRUNC(SUM(base.demand_clearence_qty)) AS INTEGER) AS demand_clearence_qty,
  CAST(TRUNC(SUM(base.demand_unknown_qty)) AS INTEGER) AS demand_unknown_qty,
  CAST(TRUNC(SUM(base.total_receipts_units)) AS INTEGER) AS total_receipts_units,
  ROUND(CAST(SUM(base.total_receipts_cost) AS NUMERIC), 2) AS total_receipts_cost,
  ROUND(CAST(SUM(base.total_receipts_retail) AS NUMERIC), 2) AS total_receipts_retail,
  CAST(TRUNC(SUM(base.dropship_receipts_units)) AS INTEGER) AS dropship_receipts_units,
  CAST(SUM(base.dropship_receipts_cost) AS NUMERIC) AS dropship_receipts_cost,
  CAST(SUM(base.dropship_receipts_retail) AS NUMERIC) AS dropship_receipts_retail,
  CAST(TRUNC(SUM(base.packandhold_transfer_in_units)) AS INTEGER) AS packandhold_transfer_in_units,
  CAST(TRUNC(SUM(base.packandhold_transfer_out_units)) AS INTEGER) AS packandhold_transfer_out_units,
  CAST(TRUNC(SUM(base.reservestock_transfer_in_units)) AS INTEGER) AS reservestock_transfer_in_units,
  CAST(TRUNC(SUM(base.reservestock_transfer_out_units)) AS INTEGER) AS reservestock_transfer_out_units,
  ROUND(CAST(SUM(base.packandhold_transfer_in_retail) AS NUMERIC), 2) AS packandhold_transfer_in_retail,
  ROUND(CAST(SUM(base.packandhold_transfer_out_retail) AS NUMERIC), 2) AS packandhold_transfer_out_retail,
  ROUND(CAST(SUM(base.packandhold_transfer_in_cost) AS NUMERIC), 2) AS packandhold_transfer_in_cost,
  ROUND(CAST(SUM(base.packandhold_transfer_out_cost) AS NUMERIC), 2) AS packandhold_transfer_out_cost,
  ROUND(CAST(SUM(base.reservestock_transfer_in_cost) AS NUMERIC), 2) AS reservestock_transfer_in_cost,
  ROUND(CAST(SUM(base.reservestock_transfer_out_cost) AS NUMERIC), 2) AS reservestock_transfer_out_cost,
  ROUND(CAST(SUM(base.reservestock_transfer_in_retail) AS NUMERIC), 2) AS reservestock_transfer_in_retail,
  ROUND(CAST(SUM(base.reservestock_transfer_out_retail) AS NUMERIC), 2) AS reservestock_transfer_out_retail,
  ROUND(CAST(SUM(base.disc_terms_cost) AS NUMERIC), 2) AS disc_terms_cost,
  ROUND(CAST(SUM(base.vendor_funds_retail) AS NUMERIC), 2) AS vendor_funds_retail,
  ROUND(CAST(SUM(base.vendor_funds_cost) AS NUMERIC), 2) AS vendor_funds_cost,
  CAST(SUM(base.boh_total_cost) AS NUMERIC) AS boh_total_cost,
  CAST(TRUNC(SUM(base.boh_total_units)) AS INTEGER) AS boh_total_units,
  CAST(SUM(base.boh_total_retail) AS NUMERIC) AS boh_total_retail,
  CAST(SUM(base.boh_clearance_cost) AS NUMERIC) AS boh_clearance_cost,
  CAST(TRUNC(SUM(base.boh_clearance_units)) AS INTEGER) AS boh_clearance_units,
  CAST(SUM(base.boh_clearance_retail) AS NUMERIC) AS boh_clearance_retail,
  CAST(SUM(base.boh_regular_cost) AS NUMERIC) AS boh_regular_cost,
  CAST(TRUNC(SUM(base.boh_regular_units)) AS INTEGER) AS boh_regular_units,
  CAST(SUM(base.boh_regular_retail) AS NUMERIC) AS boh_regular_retail,
  CAST(SUM(base.eoh_total_cost) AS NUMERIC) AS eoh_total_cost,
  CAST(TRUNC(SUM(base.eoh_total_units)) AS INTEGER) AS eoh_total_units,
  CAST(SUM(base.eoh_total_retail) AS NUMERIC) AS eoh_total_retail,
  CAST(SUM(base.eoh_clearance_cost) AS NUMERIC) AS eoh_clearance_cost,
  CAST(TRUNC(SUM(base.eoh_clearance_units)) AS INTEGER) AS eoh_clearance_units,
  CAST(SUM(base.eoh_clearance_retail) AS NUMERIC) AS eoh_clearance_retail,
  CAST(SUM(base.eoh_regular_cost) AS NUMERIC) AS eoh_regular_cost,
  CAST(SUM(base.eoh_regular_units) AS INTEGER) AS eoh_regular_units,
  CAST(SUM(base.eoh_regular_retail) AS NUMERIC) AS eoh_regular_retail,
  ROUND(CAST(SUM(base.mos_total_cost_amt) AS NUMERIC), 2) AS mos_total_cost_amt,
  SUM(base.mos_total_units) AS mos_total_units,
  ROUND(CAST(SUM(base.mos_total_retail_amt) AS NUMERIC), 2) AS mos_total_retail_amt,
  ROUND(CAST(SUM(base.rtv_total_cost) AS NUMERIC), 2) AS rtv_total_cost,
  ROUND(CAST(SUM(base.rtv_total_retail) AS NUMERIC), 2) AS rtv_total_retail,
  CAST(TRUNC(SUM(base.rtv_total_units)) AS INTEGER) AS rtv_total_units,
  MAX(COALESCE(s.ty_profitability_expectation, 0)) AS profitability_expectation,
  MAX(COALESCE(s.ty_reg_sales_expectation, 0)) AS reg_sales_expectation,
  MAX(COALESCE(s.ty_initial_markup_expectation, 0)) AS initial_markup_expectation,
  CAST(CAST(FORMAT_TIMESTAMP('%F %H:%M:%E6S', CURRENT_DATETIME('PST8PDT')) AS DATETIME) AS TIMESTAMP) AS
  process_tmstp,
  `{{params.gcp_project_id}}.JWN_UDF.DEFAULT_TZ_PST`() AS process_tmstp_tz
 FROM (SELECT *
    FROM sales_final
    UNION ALL
    SELECT *
    FROM demand_final
    UNION ALL
    SELECT *
    FROM inventory_final
    UNION ALL
    SELECT *
    FROM receipts_final
    UNION ALL
    SELECT *
    FROM transfer_final
    UNION ALL
    SELECT *
    FROM vendor_terms_final
    UNION ALL
    SELECT *
    FROM mos_final
    UNION ALL
    SELECT *
    FROM vfm_final
    UNION ALL
    SELECT *
    FROM rtv_final) AS base
  INNER JOIN date_lkup AS d ON base.week_idnt = d.week_idnt
  LEFT JOIN supplier_lkup AS supp ON LOWER(base.supplier_number) = LOWER(supp.supplier_num) AND LOWER(base.dept_idnt) =
     LOWER(supp.dept_num) AND LOWER(base.banner) = LOWER(supp.banner)
  LEFT JOIN supp_prof AS s ON CAST(base.dept_idnt AS FLOAT64) = s.dept_num AND LOWER(supp.supplier_group) = LOWER(s.supplier_group
       ) AND LOWER(base.banner) = LOWER(s.banner) AND d.fiscal_year_num = s.fiscal_year_num
  LEFT JOIN sb_lkup AS sb ON LOWER(base.banner) = LOWER(sb.banner) AND LOWER(supp.supplier_group) = LOWER(sb.supplier_group
        ) AND LOWER(base.supplier_number) = LOWER(sb.supplier_num) AND LOWER(base.dept_idnt) = LOWER(sb.dept_num) AND
    LOWER(base.brand_name) = LOWER(sb.vendor_brand_name)
 GROUP BY base.ty_ly_ind,
  base.week_idnt,
  d.fiscal_year_num,
  d.fiscal_halfyear_num,
  d.quarter_abrv,
  d.quarter_label,
  d.month_abrv,
  d.month_idnt,
  d.month_label,
  d.week_label,
  d.week_desc,
  d.fiscal_week_num,
  d.week_start_day_date,
  d.week_end_day_date,
  base.business_unit_desc,
  base.channel_num,
  base.channel_desc,
  base.country_code,
  base.banner,
  base.div_label,
  base.sdiv_label,
  base.dept_label,
  base.dept_idnt,
  base.supplier_number,
  base.brand_name,
  base.brand_label,
  base.brand_label_num,
  base.npg_ind,
  COALESCE(sb.sb_ind, 'N'),
  base.supplier,
  supplier_group);


--collect statistics primary index (week_idnt, channel_num, supplier_number, dept_idnt ) 		on {{params.environment_schema}}.supplier_profitability_expectation_channel_week_dept