CREATE VOLATILE MULTISET TABLE  #TMP_ETL_BATCH_INFO AS
(SELECT BATCH_ID, BATCH_DATE
       FROM {db_env}_NAP_BASE_VWS.ETL_BATCH_INFO
      WHERE INTERFACE_CODE = 'INVENTORY_SIM_STORE_INVENTORY_ADJUSTED_FACT'
        AND DW_SYS_END_TMSTP IS NULL
        )
       WITH DATA ON COMMIT PRESERVE ROWS
;
ET;
DELETE FROM {db_env}_NAP_UTL.ETL_BATCH_DQC_LOG WHERE BATCH_ID IN (SELECT BATCH_ID FROM #TMP_ETL_BATCH_INFO);
ET;

LOCK {db_env}_NAP_UTL.ETL_BATCH_DQC_LOG FOR ACCESS
CREATE VOLATILE MULTISET TABLE #ETL_BATCH_DQC_LOG AS 
(SELECT BATCH_ID,      
        BATCH_DATE,    
        SOURCE_TABLE,  
        ERROR_STATUS,  
        ERROR_MESSAGE
  FROM {db_env}_NAP_UTL.ETL_BATCH_DQC_LOG)
WITH NO DATA 
ON COMMIT PRESERVE ROWS
;
ET;

-- Counts
INSERT INTO #ETL_BATCH_DQC_LOG (BATCH_ID, BATCH_DATE, SOURCE_TABLE, ERROR_STATUS, ERROR_MESSAGE)
SELECT BATCH_ID
 , BATCH_DATE
 , '{db_env}_NAP_BASE_VWS.INVENTORY_SIM_STORE_INVENTORY_ADJUSTED_FACT' as SOURCE_TABLE
 , CASE WHEN FCT_CNT = LDG_CNT AND  LDG_CNT > 0 THEN 'INFO'
        ELSE 'ERROR' END as ERROR_STATUS
 , CASE WHEN FCT_CNT = LDG_CNT THEN CONCAT('Loaded ', cast(LDG_CNT as varchar(20)), ' records')
        ELSE CONCAT('STAGE count=', cast(LDG_CNT as varchar(20)), ' is not equal to FACT count=', cast(FCT_CNT as char(20)))
        END as ERROR_MESSAGE
FROM (SELECT COUNT(1) as FCT_CNT, BATCH_ID, BATCH_DATE
        FROM {db_env}_NAP_BASE_VWS.INVENTORY_SIM_STORE_INVENTORY_ADJUSTED_FACT
        JOIN #TMP_ETL_BATCH_INFO as b ON DW_BATCH_ID = BATCH_ID
       GROUP BY BATCH_ID, BATCH_DATE
 ) as F
CROSS JOIN (
 SELECT COUNT(distinct inventoryAdjustmentId || adjustmentDetails_sku_Id) as LDG_CNT
   FROM {db_env}_NAP_STG.INVENTORY_SIM_STORE_INVENTORY_ADJUSTED_LDG
 ) as S
;
ET;

-- Duplicates
INSERT INTO #ETL_BATCH_DQC_LOG (BATCH_ID, BATCH_DATE, SOURCE_TABLE, ERROR_STATUS, ERROR_MESSAGE)
SELECT BATCH_ID
      , BATCH_DATE
      , '{db_env}_NAP_BASE_VWS.INVENTORY_SIM_STORE_INVENTORY_ADJUSTED_FACT' as SOURCE_TABLE
      , 'ERROR' as ERROR_STATUS
      , CONCAT('FACT has ', cast(COUNT(1) as varchar(20)), ' duplicates by adjustment_id, sku_num') as ERROR_MESSAGE
FROM (
    SELECT adjustment_id, sku_num, COUNT(1) as cnt, max(BATCH_ID) as BATCH_ID, max(BATCH_DATE) as BATCH_DATE
      FROM {db_env}_NAP_BASE_VWS.INVENTORY_SIM_STORE_INVENTORY_ADJUSTED_FACT
      JOIN #TMP_ETL_BATCH_INFO b ON DW_BATCH_ID = BATCH_ID
     GROUP BY adjustment_id, sku_num
    HAVING COUNT(1) > 1
    ) as F
GROUP BY BATCH_ID, BATCH_DATE
;
ET;