SET QUERY_BAND = 'App_ID=APP08866;
     DAG_ID= merch_ops_scorecard_11521_ACE_ENG;
     Task_Name= merch_ops_scorecard;'
     FOR SESSION VOLATILE;

------------------------------------------------------------
-- MERCH OPS SCORECARD --
-- Table Name: 
      -- Dev: PROTO_DSA_AI_BASE_VWS.WEEKLY_OPS_STANDUP_AGG
      --Prod: PRD_NAP_DSA_AI_BASE_VWS.WEEKLY_OPS_STANDUP_AGG
-- Date Created: 7/15/2024
-- Last Updated: 8/27/2024
-- Author: Shaila Karole

-- Note:
-- Purpose: To capture Merch KPIs
-- Update Cadence:  Monday Morning at 10:00am PST 
------------------------------------------------------------
-- code begins here --

 CREATE MULTISET VOLATILE TABLE WEEKLY_OPS_STANDUP,
 FALLBACK,
 NO BEFORE JOURNAL,
 NO AFTER JOURNAL,
 CHECKSUM = DEFAULT,
 DEFAULT MERGEBLOCKRATIO,
 MAP = TD_MAP1
 (
	OPS_NAME VARCHAR(50),
	BANNER VARCHAR(50),
	CHANNEL VARCHAR(50),
	METRIC_NAME VARCHAR(50),
	FISCAL_NUM INTEGER,
	FISCAL_DESC VARCHAR(50),
	LABEL VARCHAR(50),			-- Chart Plot Axis (x-axis)
	ROLLING_FISCAL_IND INTEGER,	-- identifier for Rolling & Forward weeks 
	PLAN_OP FLOAT,
	PLAN_CP FLOAT,
	TY FLOAT,
	LY FLOAT,						
	DAY_DATE DATE					
  ) PRIMARY INDEX (OPS_NAME,BANNER,METRIC_NAME,FISCAL_NUM,LABEL)  ON COMMIT PRESERVE rows ;

 

-- WK Identifier for automating weekly plots
CREATE MULTISET VOLATILE TABLE CURR_WK AS (
SELECT WEEK_IDNT
	, WEEK_START_DAY_DATE
	, WEEK_END_DAY_DATE
	, CONCAT(MONTH_ABRV,' ','WK ',CAST(WEEK_NUM_OF_FISCAL_MONTH AS VARCHAR(12))) AS WEEK_DESC
	, MONTH_IDNT
	, MONTH_START_DAY_DATE
	, MONTH_END_DAY_DATE
	, QUARTER_IDNT 
	, FISCAL_QUARTER_NUM
	, QUARTER_START_DAY_DATE
	, QUARTER_END_DAY_DATE
	, QUARTER_START_WEEK_IDNT
	, QUARTER_END_WEEK_IDNT
FROM PRD_NAP_BASE_VWS.DAY_CAL_454_DIM
WHERE day_date = {start_date}-7 	-- CURRENT_DATE - 7
) WITH data PRIMARY INDEX (WEEK_IDNT) ON COMMIT PRESERVE rows ;


-- CAL_LKUP;
CREATE MULTISET VOLATILE TABLE CAL_LKUP AS (
SELECT DISTINCT
	a.WEEK_NUM
	, a.WEEK_454_NUM
	, a.MONTH_SHORT_DESC
	, b.WEEK_START_DAY_DATE
	, b.WEEK_END_DAY_DATE
	, a.MONTH_NUM
	, b.MONTH_START_DAY_DATE
	, b.MONTH_END_DAY_DATE
	, A.QUARTER_NUM
	, A.QUARTER_454_NUM
	, A.YEAR_NUM
FROM PRD_NAP_BASE_VWS.DAY_CAL a
LEFT JOIN PRD_NAP_BASE_VWS.DAY_CAL_454_DIM b
on a.WEEK_NUM = b.WEEK_IDNT
and a.MONTH_NUM = b.MONTH_IDNT
WHERE b.day_date BETWEEN ({start_date}-120) AND ({start_date}+120) 
) WITH data PRIMARY INDEX (WEEK_NUM) ON COMMIT PRESERVE rows ;



-- MERCH_HIERARCHY_LKUP;
CREATE MULTISET VOLATILE TABLE MERCH_HIERARCHY_LKUP  AS (
SELECT DISTINCT DEPT_NUM, DEPT_NAME, DIVISION_NUM, DIVISION_NAME
FROM PRD_NAP_BASE_VWS.DEPARTMENT_DIM
WHERE DEPT_NUM NOT IN (584,585,523) -- Excluding Samples and CORP BEAUTY MKT PR
AND DIVISION_NUM NOT IN (600,800,96) -- Excluding ALT MODEL, LEASED BOUTIQUES and LAST CHANCE
AND DIVISION_NAME NOT LIKE '%INACTIVE%' -- Excluding INACTIVE divisions
) WITH data PRIMARY INDEX (DEPT_NUM) ON COMMIT PRESERVE rows ;


-- BANNER_CHNL_LKUP;
CREATE MULTISET VOLATILE TABLE BANNER_CHNL_LKUP AS (
SELECT 
DISTINCT CHANNEL_NUM
, CHANNEL_DESC
, CHANNEL_COUNTRY AS COUNTRY_CODE
, BANNER_ID as BANNER_COUNTRY_NUM
, CASE WHEN BANNER_DESC = 'OFF_PRICE' THEN 'NORDSTROM RACK'
	   WHEN BANNER_DESC = 'FULL_PRICE' THEN 'NORDSTROM' END AS BANNER
FROM PRD_NAP_BASE_VWS.ORG_CHANNEL_COUNTRY_BANNER_DIM 
WHERE CHANNEL_COUNTRY = 'US'
) WITH data PRIMARY INDEX (CHANNEL_NUM) ON COMMIT PRESERVE rows ;


-------------------------------------------------------------------------------------------------------------------------------------------------------

-- Fileds from table : MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT
CREATE MULTISET VOLATILE TABLE INV_OPS_1
AS (
SELECT
FACT.WEEK_NUM
, TME.WEEK_454_NUM
, TME.MONTH_SHORT_DESC
, TME.WEEK_START_DAY_DATE
, TME.WEEK_END_DAY_DATE
, TME.MONTH_NUM
, TME.MONTH_START_DAY_DATE
, TME.MONTH_END_DAY_DATE
, TME.QUARTER_NUM
, CASE WHEN BANNER_COUNTRY_NUM = 1 THEN 'NORDSTROM'
	   WHEN BANNER_COUNTRY_NUM = 3 THEN 'NORDSTROM RACK' END AS BANNER
, FACT.DEPT_NUM
, MCH.DIVISION_NAME
, MCH.DIVISION_NUM
--EOP $
, SUM(OP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + OP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as OP_EOP_TOT_COST_AMT
, SUM(CP_ENDING_OF_PERIOD_ACTIVE_COST_AMT + CP_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as CP_EOP_TOT_COST_AMT
, SUM(TY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + TY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as TY_EOP_TOT_COST_AMT
, SUM(LY_ENDING_OF_PERIOD_ACTIVE_COST_AMT + LY_ENDING_OF_PERIOD_INACTIVE_COST_AMT) as LY_EOP_TOT_COST_AMT
--Stock to Sales $
, SUM(OP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + OP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as OP_BOP_TOT_COST_AMT
, SUM(CP_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + CP_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as CP_BOP_TOT_COST_AMT
, SUM(TY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + TY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as TY_BOP_TOT_COST_AMT
, SUM(LY_BEGINNING_OF_PERIOD_ACTIVE_COST_AMT + LY_BEGINNING_OF_PERIOD_INACTIVE_COST_AMT) as LY_BOP_TOT_COST_AMT
--EOP U
, SUM(OP_ENDING_OF_PERIOD_ACTIVE_QTY + OP_ENDING_OF_PERIOD_INACTIVE_QTY) as OP_EOP_TOT_UNITS
, SUM(CP_ENDING_OF_PERIOD_ACTIVE_QTY + CP_ENDING_OF_PERIOD_INACTIVE_QTY) as CP_EOP_TOT_UNITS
, SUM(TY_ENDING_OF_PERIOD_ACTIVE_QTY + TY_ENDING_OF_PERIOD_INACTIVE_QTY) as TY_EOP_TOT_UNITS
, SUM(LY_ENDING_OF_PERIOD_ACTIVE_QTY + LY_ENDING_OF_PERIOD_INACTIVE_QTY) as LY_EOP_TOT_UNITS
--Merch Margin
, SUM(OP_MERCH_MARGIN_RETAIL_AMT) as OP_MERCH_MARGIN_AMT
, SUM(CP_MERCH_MARGIN_RETAIL_AMT) as CP_MERCH_MARGIN_AMT
, SUM(TY_MERCH_MARGIN_RETAIL_AMT) as TY_MERCH_MARGIN_AMT
, SUM(LY_MERCH_MARGIN_RETAIL_AMT) as LY_MERCH_MARGIN_AMT
--Receipts U
, SUM(CP_RECEIPTS_ACTIVE_QTY) as CP_RECEIPTS_ACTIVE_QTY
, SUM(OP_RECEIPTS_ACTIVE_QTY) as OP_RECEIPTS_ACTIVE_QTY
, SUM(SP_RECEIPTS_ACTIVE_QTY) as SP_RECEIPTS_ACTIVE_QTY
, SUM(TY_RECEIPTS_ACTIVE_QTY) as TY_RECEIPTS_ACTIVE_QTY
, SUM(LY_RECEIPTS_ACTIVE_QTY) as LY_RECEIPTS_ACTIVE_QTY
FROM PRD_NAP_BASE_VWS.MFP_COST_PLAN_ACTUAL_BANNER_COUNTRY_FACT FACT 
JOIN MERCH_HIERARCHY_LKUP MCH
ON FACT.DEPT_NUM = MCH.DEPT_NUM
JOIN CAL_LKUP TME
ON FACT.WEEK_NUM = TME.WEEK_NUM
WHERE FACT.WEEK_NUM IN (SELECT WEEK_NUM FROM CAL_LKUP)
AND BANNER_COUNTRY_NUM IN(1,3)
-- AND MCH.DIVISION_NUM IN (310, 340, 345, 351, 360, 365)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
) WITH DATA PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER) ON COMMIT PRESERVE rows ;



-- Fileds from table: MFP_COST_PLAN_ACTUAL_CHANNEL_FACT (Net Sales)
CREATE MULTISET VOLATILE TABLE INV_OPS_2
AS (
SELECT
FACT.WEEK_NUM
, TME.WEEK_454_NUM
, TME.MONTH_SHORT_DESC
, TME.WEEK_START_DAY_DATE
, TME.WEEK_END_DAY_DATE
, TME.MONTH_NUM
, TME.MONTH_START_DAY_DATE
, TME.MONTH_END_DAY_DATE
, TME.QUARTER_NUM
, BC.BANNER
, FACT.CHANNEL_NUM
, FACT.DEPT_NUM
, MCH.DIVISION_NAME
, MCH.DIVISION_NUM
, SUM(OP_NET_SALES_COST_AMT) as OP_NET_SALES_COST_AMT
, SUM(CP_NET_SALES_COST_AMT) as CP_NET_SALES_COST_AMT
, SUM(TY_NET_SALES_COST_AMT) as TY_NET_SALES_COST_AMT
, SUM(LY_NET_SALES_COST_AMT) as LY_NET_SALES_COST_AMT
, SUM(OP_NET_SALES_RETAIL_AMT) as OP_NET_SALES_RETAIL_AMT
, SUM(CP_NET_SALES_RETAIL_AMT) as CP_NET_SALES_RETAIL_AMT
, SUM(TY_NET_SALES_RETAIL_AMT) as TY_NET_SALES_RETAIL_AMT
, SUM(LY_NET_SALES_RETAIL_AMT) as LY_NET_SALES_RETAIL_AMT
, SUM(OP_GROSS_MARGIN_RETAIL_AMT) as OP_GROSS_MARGIN_RETAIL_AMT
, SUM(CP_GROSS_MARGIN_RETAIL_AMT) as CP_GROSS_MARGIN_RETAIL_AMT
, SUM(TY_GROSS_MARGIN_RETAIL_AMT) as TY_GROSS_MARGIN_RETAIL_AMT
, SUM(LY_GROSS_MARGIN_RETAIL_AMT) as LY_GROSS_MARGIN_RETAIL_AMT
, SUM(OP_NET_SALES_QTY) as OP_NET_SALES_QTY
, SUM(CP_NET_SALES_QTY) as CP_NET_SALES_QTY
, SUM(TY_NET_SALES_QTY) as TY_NET_SALES_QTY
, SUM(LY_NET_SALES_QTY) as LY_NET_SALES_QTY
FROM PRD_NAP_BASE_VWS.MFP_COST_PLAN_ACTUAL_CHANNEL_FACT FACT
JOIN MERCH_HIERARCHY_LKUP MCH
ON FACT.DEPT_NUM = MCH.DEPT_NUM
JOIN BANNER_CHNL_LKUP BC
ON FACT.CHANNEL_NUM  = BC.CHANNEL_NUM
JOIN CAL_LKUP TME
ON FACT.WEEK_NUM = TME.WEEK_NUM
WHERE FACT.WEEK_NUM IN (SELECT WEEK_NUM FROM CAL_LKUP)
-- AND MCH.DIVISION_NUM IN (310, 340, 345, 351, 360, 365)
AND FACT.CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14
) WITH DATA PRIMARY INDEX (DEPT_NUM, WEEK_NUM, BANNER) ON COMMIT PRESERVE ROWS ;

--------------------------------------------------------------------------------------------------------------------------------------------------------------

---- Dashboard table insertion, metric wise ----

-- EOP $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'EOP $' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
NULL AS LABEL,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_COST_AMT) AS PLAN_OP,
SUM(CP_EOP_TOT_COST_AMT) AS PLAN_CP,
SUM(TY_EOP_TOT_COST_AMT) AS TY,
SUM(LY_EOP_TOT_COST_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,13 ;



--------------------------------------------------------------------------------------------------------------------------------------------------------------


--Merch Margin %
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' as OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Merch Margin % weekly' as METRIC_NAME,
A.WEEK_NUM AS FISCAL_NUM,
FISCAL_DESC,
NULL AS LABEL,
CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN 1 ELSE 0 END AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE OP_MERCH_MARGIN_AMT/OP_NET_SALES_RETAIL_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE CP_MERCH_MARGIN_AMT/CP_NET_SALES_RETAIL_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE TY_MERCH_MARGIN_AMT/TY_NET_SALES_RETAIL_AMT END AS TY,
CASE WHEN LY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE LY_MERCH_MARGIN_AMT/LY_NET_SALES_RETAIL_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
WEEK_NUM,
SUM(OP_MERCH_MARGIN_AMT) AS OP_MERCH_MARGIN_AMT,
SUM(CP_MERCH_MARGIN_AMT) AS CP_MERCH_MARGIN_AMT,
SUM(TY_MERCH_MARGIN_AMT) AS TY_MERCH_MARGIN_AMT,
SUM(LY_MERCH_MARGIN_AMT) AS LY_MERCH_MARGIN_AMT
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2) A
JOIN
(SELECT
BANNER,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
WEEK_NUM,
WEEK_START_DAY_DATE,
SUM(OP_NET_SALES_RETAIL_AMT) AS OP_NET_SALES_RETAIL_AMT,
SUM(CP_NET_SALES_RETAIL_AMT) AS CP_NET_SALES_RETAIL_AMT,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY_NET_SALES_RETAIL_AMT,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY_NET_SALES_RETAIL_AMT
FROM INV_OPS_2
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE +27) FROM CURR_WK)
GROUP BY 1,2,3,4) B
ON A.WEEK_NUM = B.WEEK_NUM
AND A.BANNER = B.BANNER ;




-- QTD Merch Margin %
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' as OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Merch Margin % QTD' as METRIC_NAME,
A.QUARTER_NUM AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
NULL AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE OP_MERCH_MARGIN_AMT/OP_NET_SALES_RETAIL_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE CP_MERCH_MARGIN_AMT/CP_NET_SALES_RETAIL_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE TY_MERCH_MARGIN_AMT/TY_NET_SALES_RETAIL_AMT END AS TY,
CASE WHEN LY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE LY_MERCH_MARGIN_AMT/LY_NET_SALES_RETAIL_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
QUARTER_NUM,
SUM(OP_MERCH_MARGIN_AMT) AS OP_MERCH_MARGIN_AMT,
SUM(CP_MERCH_MARGIN_AMT) AS CP_MERCH_MARGIN_AMT,
SUM(TY_MERCH_MARGIN_AMT) AS TY_MERCH_MARGIN_AMT,
SUM(LY_MERCH_MARGIN_AMT) AS LY_MERCH_MARGIN_AMT
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) A 
JOIN
(SELECT
BANNER,
QUARTER_NUM,
SUM(OP_NET_SALES_RETAIL_AMT) AS OP_NET_SALES_RETAIL_AMT,
SUM(CP_NET_SALES_RETAIL_AMT) AS CP_NET_SALES_RETAIL_AMT,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY_NET_SALES_RETAIL_AMT,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY_NET_SALES_RETAIL_AMT
FROM INV_OPS_2
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) B
ON A.QUARTER_NUM = B.QUARTER_NUM
AND A.BANNER = B.BANNER ;


-- QTR Merch Margin %
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' as OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Merch Margin % QTR' as METRIC_NAME,
A.QUARTER_NUM AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
NULL AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE OP_MERCH_MARGIN_AMT/OP_NET_SALES_RETAIL_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE CP_MERCH_MARGIN_AMT/CP_NET_SALES_RETAIL_AMT END AS PLAN_CP,
CASE WHEN TY_CP_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE TY_CP_MERCH_MARGIN_RETAIL_AMT/TY_CP_NET_SALES_RETAIL_AMT END AS TY,
CASE WHEN LY_NET_SALES_RETAIL_AMT = 0 THEN 0 ELSE LY_MERCH_MARGIN_AMT/LY_NET_SALES_RETAIL_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
QUARTER_NUM,
SUM(OP_MERCH_MARGIN_AMT) AS OP_MERCH_MARGIN_AMT,
SUM(CP_MERCH_MARGIN_AMT) AS CP_MERCH_MARGIN_AMT,
SUM(TY_MERCH_MARGIN_AMT) AS TY_MERCH_MARGIN_AMT,
SUM(LY_MERCH_MARGIN_AMT) AS LY_MERCH_MARGIN_AMT,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_MERCH_MARGIN_AMT ELSE CP_MERCH_MARGIN_AMT END) AS TY_CP_MERCH_MARGIN_RETAIL_AMT
FROM INV_OPS_1 A
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) A 
JOIN
(SELECT
BANNER,
QUARTER_NUM,
SUM(OP_NET_SALES_RETAIL_AMT) AS OP_NET_SALES_RETAIL_AMT,
SUM(CP_NET_SALES_RETAIL_AMT) AS CP_NET_SALES_RETAIL_AMT,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY_NET_SALES_RETAIL_AMT,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY_NET_SALES_RETAIL_AMT,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_NET_SALES_RETAIL_AMT ELSE CP_NET_SALES_RETAIL_AMT END) AS TY_CP_NET_SALES_RETAIL_AMT
FROM INV_OPS_2 A
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) B 
ON A.QUARTER_NUM = B.QUARTER_NUM
AND A.BANNER = B.BANNER ;


-----------------------------------------------------------------------------------------------------------------------------------------


--Division Stock to Sales $ Weekly
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Div Stock to Sales $ Weekly' as METRIC_NAME,
A.WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS FISCAL_DESC,
A.DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS DIVISION_NAME,
WEEK_NUM,
MONTH_SHORT_DESC,
WEEK_454_NUM,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
FROM INV_OPS_1 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3,4,5) A
JOIN 
(SELECT
WEEK_NUM,
BANNER,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS DIVISION_NAME,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_2 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3) B
ON A.WEEK_NUM = B.WEEK_NUM
AND A.DIVISION_NAME = B.DIVISION_NAME
AND A.BANNER = B.BANNER  ;



--Division Stock to Sales $ Weekly  (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Div Stock to Sales $ Weekly' as METRIC_NAME,
A.WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12)))  AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
BANNER,
WEEK_NUM,
MONTH_SHORT_DESC,
WEEK_454_NUM,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
FROM INV_OPS_1 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3,4) A
JOIN 
(SELECT
WEEK_NUM,
BANNER,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_2 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) B
ON a.WEEK_NUM = b.WEEK_NUM
AND a.BANNER = b.BANNER  ;



--QTD DIVISION Stock to Sales $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Div Stock to Sales $ QTD' as METRIC_NAME,
A.quarter_num AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
A.DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
QUARTER_NUM,
BANNER,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS DIVISION_NAME,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
FROM INV_OPS_1 
WHERE WEEK_START_DAY_DATE = (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) 
GROUP BY 1,2,3) A
JOIN
(SELECT
QUARTER_NUM,
BANNER,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS DIVISION_NAME,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_2 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3) B
ON A.QUARTER_NUM = B.QUARTER_NUM
AND A.DIVISION_NAME = B.DIVISION_NAME
AND A.BANNER = B.BANNER;



--QTD DIVISION Stock to Sales $  (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Div Stock to Sales $ QTD' as METRIC_NAME,
A.quarter_num AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
QUARTER_NUM,
BANNER,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
FROM INV_OPS_1 
WHERE WEEK_START_DAY_DATE = (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) 
GROUP BY 1,2) A
JOIN
(SELECT
QUARTER_NUM,
BANNER,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(TY_NET_SALES_COST_AMT) AS TY_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_2 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) B
ON A.QUARTER_NUM = B.QUARTER_NUM
AND A.BANNER = B.BANNER;



--QTR DIVISION Stock to Sales $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Div Stock to Sales $ QTR' as METRIC_NAME,
A.quarter_num AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
A.DIVISION_NAME AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_CP_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
QUARTER_NUM,
BANNER,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS DIVISION_NAME,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
FROM INV_OPS_1 
WHERE WEEK_START_DAY_DATE = (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) 
GROUP BY 1,2,3) A
JOIN
(SELECT
QUARTER_NUM,
BANNER,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS DIVISION_NAME,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_NET_SALES_COST_AMT ELSE CP_NET_SALES_COST_AMT END) AS TY_CP_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_2 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3) B
ON A.QUARTER_NUM = B.QUARTER_NUM
AND A.DIVISION_NAME = B.DIVISION_NAME
AND A.BANNER = B.BANNER ;



--QTR DIVISION Stock to Sales $  (Total)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
A.BANNER,
NULL AS CHANNEL,
'Div Stock to Sales $ QTR' as METRIC_NAME,
A.quarter_num AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
CASE WHEN OP_NET_SALES_COST_AMT = 0 THEN 0 ELSE OP_BOP_TOT_COST_AMT/OP_NET_SALES_COST_AMT END AS PLAN_OP,
CASE WHEN CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE CP_BOP_TOT_COST_AMT/CP_NET_SALES_COST_AMT END AS PLAN_CP,
CASE WHEN TY_CP_NET_SALES_COST_AMT = 0 THEN 0 ELSE TY_BOP_TOT_COST_AMT/TY_CP_NET_SALES_COST_AMT END AS TY,
CASE WHEN LY_NET_SALES_COST_AMT = 0 THEN 0 ELSE LY_BOP_TOT_COST_AMT/LY_NET_SALES_COST_AMT END AS LY,
NULL AS DAY_DATE
FROM
(SELECT
QUARTER_NUM,
BANNER,
SUM(TY_BOP_TOT_COST_AMT) AS TY_BOP_TOT_COST_AMT,
SUM(OP_BOP_TOT_COST_AMT) AS OP_BOP_TOT_COST_AMT,
SUM(CP_BOP_TOT_COST_AMT) AS CP_BOP_TOT_COST_AMT,
SUM(LY_BOP_TOT_COST_AMT) AS LY_BOP_TOT_COST_AMT
FROM INV_OPS_1 
WHERE WEEK_START_DAY_DATE = (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) 
GROUP BY 1,2) A
JOIN
(SELECT
QUARTER_NUM,
BANNER,
SUM(OP_NET_SALES_COST_AMT) AS OP_NET_SALES_COST_AMT,
SUM(CP_NET_SALES_COST_AMT) AS CP_NET_SALES_COST_AMT,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_NET_SALES_COST_AMT ELSE CP_NET_SALES_COST_AMT END) AS TY_CP_NET_SALES_COST_AMT,
SUM(LY_NET_SALES_COST_AMT) AS LY_NET_SALES_COST_AMT
FROM INV_OPS_2 
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2) B
ON A.QUARTER_NUM = B.QUARTER_NUM
AND A.BANNER = B.BANNER ;

-----------------------------------------------------------------------------------------------------------------------------------------

-- DIVISION STORE/DIGITAL SALES $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER','FINANCIAL PLANNING RESERVE') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- DIVISION STORE/DIGITAL SALES $ (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- DIVISION STORE/DIGITAL SALES $ (TOTAL W/O FINANCIAL PLAN RESERVE)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
'TOTAL(w/o FPR*)' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
AND DIVISION_NAME <> 'FINANCIAL PLANNING RESERVE'
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTD DIVISION STORE/DIGITAL SALES $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ QTD' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER','FINANCIAL PLANNING RESERVE') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2 a
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,13;


-- QTD DIVISION STORE/DIGITAL SALES $ (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ QTD' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2 a
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,13;


-- QTD DIVISION STORE/DIGITAL SALES $ (TOTAL W/O FPR)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ QTD' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
'TOTAL(w/o FPR*)' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(TY_NET_SALES_RETAIL_AMT) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2 a
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_START_DAY_DATE FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
AND DIVISION_NAME <> 'FINANCIAL PLANNING RESERVE'
GROUP BY 1,2,3,4,5,6,7,8,13;


-- QTR DIVISION STORE/DIGITAL SALES $
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ QTR' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER','FINANCIAL PLANNING RESERVE') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_NET_SALES_RETAIL_AMT ELSE CP_NET_SALES_RETAIL_AMT END) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2 a
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTR DIVISION STORE/DIGITAL SALES $ (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ QTR' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_NET_SALES_RETAIL_AMT ELSE CP_NET_SALES_RETAIL_AMT END) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2 a
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTR DIVISION STORE/DIGITAL SALES $ (TOTAL W/O FPR)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
CASE WHEN CHANNEL_NUM = 110 THEN 'FLS'
	 WHEN CHANNEL_NUM = 120 THEN 'N.COM'
	 WHEN CHANNEL_NUM = 210 THEN 'RACK STORE'
	 WHEN CHANNEL_NUM = 250 THEN 'R.COM'
	 END AS CHANNEL,
'Div Store/Digital Sales $ QTR' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
'TOTAL(w/o FPR*' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_NET_SALES_RETAIL_AMT) AS PLAN_OP,
SUM(CP_NET_SALES_RETAIL_AMT) AS PLAN_CP,
SUM(CASE WHEN WEEK_START_DAY_DATE <= ({start_date} -7) THEN TY_NET_SALES_RETAIL_AMT ELSE CP_NET_SALES_RETAIL_AMT END) AS TY,
SUM(LY_NET_SALES_RETAIL_AMT) AS LY,
NULL AS DAY_DATE
FROM INV_OPS_2 a
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT QUARTER_END_DAY_DATE FROM CURR_WK)
AND CHANNEL_NUM IN (110,120,210,250)
AND DIVISION_NAME <> 'FINANCIAL PLANNING RESERVE'
GROUP BY 1,2,3,4,5,6,7,8,13 ;

--------------------------------------------------------------------------------------------------------------------------------------------------------------

-- Weekly Receipt U (Division) --
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Receipt U Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_RECEIPTS_ACTIVE_QTY) AS PLAN_OP,
SUM(SP_RECEIPTS_ACTIVE_QTY) AS PLAN_CP,
SUM(TY_RECEIPTS_ACTIVE_QTY) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,12,13 ;



-- Weekly Receipt U (TOTAL) --
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Receipt U Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_RECEIPTS_ACTIVE_QTY) AS PLAN_OP,
SUM(SP_RECEIPTS_ACTIVE_QTY) AS PLAN_CP,
SUM(TY_RECEIPTS_ACTIVE_QTY) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,12,13 ;



-- QTD Division Receipt U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Receipt U QTD' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_RECEIPTS_ACTIVE_QTY) AS PLAN_OP,
SUM(SP_RECEIPTS_ACTIVE_QTY) AS PLAN_CP,
SUM(TY_RECEIPTS_ACTIVE_QTY) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,12,13 ;


-- QTD Receipt U (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Receipt U QTD ' AS METRIC_NAME,
QUARTER_NUM AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_RECEIPTS_ACTIVE_QTY) AS PLAN_OP,
SUM(SP_RECEIPTS_ACTIVE_QTY) AS PLAN_CP,
SUM(TY_RECEIPTS_ACTIVE_QTY) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT QUARTER_START_DAY_DATE FROM CURR_WK) AND (SELECT WEEK_END_DAY_DATE FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,12,13 ;


--------------------------------------------------------------------------------------------------------------------------------------------------------------


-- DIVISION EOP U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Div EOP U Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(TY_EOP_TOT_UNITS) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- DIVISION EOP U (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Div EOP U Weekly' AS METRIC_NAME,
WEEK_NUM AS FISCAL_NUM,
CONCAT(MONTH_SHORT_DESC,' ','WK ',CAST(WEEK_454_NUM AS VARCHAR(12))) AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(TY_EOP_TOT_UNITS) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1
WHERE WEEK_START_DAY_DATE BETWEEN (SELECT (WEEK_START_DAY_DATE -14) FROM CURR_WK) AND (SELECT (WEEK_START_DAY_DATE) FROM CURR_WK)
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTD DIVISION EOP U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Div EOP U QTD' AS METRIC_NAME,
quarter_num AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(TY_EOP_TOT_UNITS) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1 a
WHERE WEEK_NUM = (SELECT WEEK_IDNT FROM CURR_WK) -- QTD metric, selecting latest week for EOP calculation
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTD DIVISION EOP U (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Div EOP U QTD' AS METRIC_NAME,
quarter_num AS FISCAL_NUM,
'QTD' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(TY_EOP_TOT_UNITS) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1 a
WHERE WEEK_NUM = (SELECT WEEK_IDNT FROM CURR_WK) -- QTD metric, selecting latest week for EOP calculation
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTR DIVISION EOP U
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Div EOP U QTR' AS METRIC_NAME,
quarter_num AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
CASE WHEN DIVISION_NAME IN('ACCESSORIES','HOME') THEN 'ACC/HOME' 
	 WHEN DIVISION_NAME IN ('APPAREL','SHOES','BEAUTY','DESIGNER') THEN DIVISION_NAME ELSE 'OTHER' END AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(CASE WHEN WEEK_NUM = WEEK_IDNT THEN TY_EOP_TOT_UNITS ELSE CP_EOP_TOT_UNITS END) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1 A
JOIN CURR_WK B
ON WEEK_NUM = QUARTER_END_WEEK_IDNT  -- QTR metric, selecting last week of quarter for EOP calculation
GROUP BY 1,2,3,4,5,6,7,8,13 ;


-- QTR DIVISION EOP U (TOTAL)
INSERT INTO WEEKLY_OPS_STANDUP
SELECT
'MERCH' AS OPS_NAME,
BANNER,
NULL AS CHANNEL,
'Div EOP U QTR' AS METRIC_NAME,
quarter_num AS FISCAL_NUM,
'QTR' AS FISCAL_DESC,
'TOTAL' AS LABEL,
NULL AS ROLLING_FISCAL_IND,
SUM(OP_EOP_TOT_UNITS) AS PLAN_OP,
SUM(CP_EOP_TOT_UNITS) AS PLAN_CP,
SUM(CASE WHEN WEEK_NUM = WEEK_IDNT THEN TY_EOP_TOT_UNITS ELSE CP_EOP_TOT_UNITS END) AS TY,
NULL AS LY,
NULL AS DAY_DATE
FROM INV_OPS_1 A
JOIN CURR_WK B
ON WEEK_NUM = QUARTER_END_WEEK_IDNT  -- QTR metric, selecting last week of quarter for EOP calculation
GROUP BY 1,2,3,4,5,6,7,8,13 ;

-------------------------------------------------------------------------------------------------------------------------------------------------------

DELETE FROM {clarity_schema}.WEEKLY_OPS_STANDUP_AGG
WHERE OPS_NAME = 'MERCH' -- Adding an extra filter since all Ops Scorecard will be using the same table
AND UPDATED_WEEK = (SELECT WEEK_IDNT FROM CURR_WK) ;


insert into {clarity_schema}.WEEKLY_OPS_STANDUP_AGG
select
ops_name               
    ,banner            
    ,channel               
    ,metric_name            
    ,fiscal_num            
    ,fiscal_desc            
    ,label                  
    ,rolling_fiscal_ind     
    ,plan_op                
    ,plan_cp               
    ,ty                    
    ,ly                     
    ,WEEK_IDNT AS updated_week            
    ,CURRENT_TIMESTAMP as dw_sys_load_tmstp      
    ,day_date 
FROM WEEKLY_OPS_STANDUP AS A, CURR_WK ;


-------------------------------------------------------------------------------------------------------------------------------------------------------------

/* 
SQL script must end with statement to turn off QUERY_BAND 
*/
SET QUERY_BAND = NONE FOR SESSION;

