select
    web_style_num
    ,selling_channel
    ,epm_style_num
    ,partner_relationship_type
    ,npg_ind
    ,brand_name
    ,div_num
    ,div_desc
    ,grp_num
    ,grp_desc
    ,dept_num
    ,dept_desc
    ,class_num
    ,class_desc
    ,sbclass_num
    ,sbclass_desc
    ,prmy_supp_num
    ,vender_name
    ,style_group_num
    ,style_group_desc
    ,style_group_short_desc
    ,type_level_1_num
    ,type_level_1_desc
    ,type_level_2_num
    ,type_level_2_desc
    ,genders_code
    ,genders_desc
    ,age_groups_code
    ,age_groups_desc
    ,QUANTRIX_CATEGORY
    ,CCS_CATEGORY
    ,CCS_SUBCATEGORY
    ,NORD_ROLE
    ,NORD_ROLE_DESC
    ,RACK_ROLE
    ,RACK_ROLE_DESC
    ,PARENT_GROUP
    ,MERCH_THEMES
    ,ANNIVERSARY_21
    ,ANNIVERSARY_THEME
    ,HOLIDAY_21
    ,HOLIDAY_THEME_TY
    ,GIFT_IND
    ,STOCKING_STUFFER
    ,ASSORTMENT_GROUPING
    ,product_views_ppfd
    ,los_flag
    ,unfiltered_units
    ,unfiltered_orders
    ,unfiltered_demand
    ,filtered_units
    ,filtered_orders
    ,filtered_demand
    ,ds_fulfilled_unfiltered_units
    ,ds_fulfilled_unfiltered_orders
    ,ds_fulfilled_unfiltered_demand
    ,ds_fulfilled_filtered_units
    ,ds_fulfilled_filtered_orders
    ,ds_fulfilled_filtered_demand
    ,min_selling_price
    ,max_selling_price
    ,avg_selling_price
    ,number_selling_price
    ,min_reg_price
    ,max_reg_price
    ,avg_reg_price
    ,number_reg_price
    ,min_md_discount
    ,max_md_discount
    ,avg_md_discount
    ,number_md_discount
    ,num_md
    ,min_inventory_age
    ,max_inventory_age
    ,avg_inventory_age
    ,sku_count
    ,color_count
    ,boh_units
    ,eoh_units
    ,nonsellable_units
    ,instock_views
    ,total_views
    ,twist
    ,sku_count_new
    ,color_count_new
    ,sku_count_not_new
    ,color_count_not_new
    ,new_boh_units
    ,new_eoh_units
    ,new_nonsellable_units
    ,not_new_boh_units
    ,not_new_eoh_units
    ,not_new_nonsellable_units
    ,new_twist
    ,not_new_twist
    ,sku_count_rp
    ,color_count_rp
    ,sku_count_non_rp
    ,color_count_non_rp
    ,rp_boh_units
    ,rp_eoh_units
    ,rp_nonsellable_units
    ,not_rp_boh_units
    ,not_rp_eoh_units
    ,not_rp_nonsellable_units
    ,rp_twist
    ,not_rp_twist
    ,sku_count_R
    ,sku_count_P
    ,sku_count_C
    ,color_count_R
    ,color_count_P
    ,color_count_C
    ,eoh_reg_units
    ,eoh_clr_units
    ,eoh_pro_units
    ,R_twist
    ,P_twist
    ,C_twist
    ,sku_count_DS
    ,sku_count_Unsellable
    ,sku_count_Owned
    ,color_count_DS
    ,color_count_Unsellable
    ,color_count_Owned
    ,DS_boh_units
    ,Unsellable_boh_units
    ,Owned_boh_units
    ,DS_eoh_units
    ,Unsellable_eoh_units
    ,Owned_eoh_units
    ,DS_twist
    ,Unsellable_twist
    ,Owned_twist
    ,flash_sku_count   
    ,mp_flag
    ,sku_count_mp
    ,sku_count_nmp
    ,color_count_mp
    ,color_count_nmp       
    ,dw_sys_load_tmstp  
	,day_date
from T2DL_DAS_DIGITALMERCH_FLASH.digital_merch_table
where day_date between date '2024-08-23' and date '2024-08-23';
 
