SET QUERY_BAND = 'App_ID=APP08047;
     DAG_ID=ddl_mta_utm_session_agg_11521_ACE_ENG;
     Task_Name=ddl_mta_utm_session_agg;'
     FOR SESSION VOLATILE;

/*
-----------------------------------
T2DL_DAS_MTA.MTA_UTM_SESSION_AGG
-----------------------------------
*/
CREATE MULTISET TABLE {mta_t2_schema}.MTA_UTM_SESSION_AGG
     , FALLBACK
     , NO BEFORE JOURNAL
     , NO AFTER JOURNAL
     , CHECKSUM = DEFAULT
     , DEFAULT MERGEBLOCKRATIO
(
    activity_date_pacific DATE FORMAT 'YYYY-MM-DD' NOT NULL
    , channelcountry VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    , channel VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    , experience VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
    , siteid VARCHAR(250) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_source VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_medium VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
    , sp_source VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_channel VARCHAR(300) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_campaign VARCHAR(300) CHARACTER SET UNICODE NOT CASESPECIFIC
    , sp_campaign VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_term VARCHAR(300) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_content VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , gclid VARCHAR(200) CHARACTER SET UNICODE NOT CASESPECIFIC
    , funnel_type VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS('Up', 'Low', 'Mid','BASE','UNATTRIBUTED')
    , mrkt_touch CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS('Y', 'N')
    , session_type VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('ARRIVED','NON_ARRIVED')
    , mrkt_type VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    , finance_rollup VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    , finance_detail VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    , web_orders INT
    , web_demand_usd DECIMAL(15, 2)
    , bounced_sessions int
    , total_sessions int
    , dw_batch_date DATE FORMAT 'YYYY-MM-DD' NOT NULL
    , dw_sys_updt_tmstp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
PRIMARY INDEX (activity_date_pacific,finance_detail,utm_content)
PARTITION BY RANGE_N(activity_date_pacific BETWEEN DATE '2022-01-01' AND DATE '2025-01-01' EACH INTERVAL '1' DAY)
INDEX (activity_date_pacific)
;


SET QUERY_BAND = NONE FOR SESSION;