 /*
SQL script must begin with QUERY_BAND SETTINGS
*/
SET QUERY_BAND = 'App_ID=APP08134;
     DAG_ID=ssa_mkt_attr_fact_11521_ACE_ENG;
     Task_Name=ddl_ssa_mkt_attr_ldg;'
     FOR SESSION VOLATILE;


/*
T2/Table Name: T2DL_DAS_MTA.ssa_mkt_attr_fact_ldg
Team/Owner: Analytics Engineering
Date Created/Modified: 08/23/23

Note:
This landing table is created as part of the hive to td job that loads
data from hive to teradata.

*/
--CALL SYS_MGMT.DROP_IF_EXISTS_SP ('t2dl_das_bie_dev', 'ssa_mkt_attr_fact_ldg', OUT_RETURN_MSG);

CREATE MULTISET TABLE {mta_t2_schema}.ssa_mkt_attr_fact_ldg
     , FALLBACK
     , NO BEFORE JOURNAL
     , NO AFTER JOURNAL
     , CHECKSUM = DEFAULT
     , DEFAULT MERGEBLOCKRATIO
(
    activity_date_pacific DATE FORMAT 'YYYY-MM-DD' NOT NULL
    , channelcountry VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('US','CA','UNKNOWN')
    , channel VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('UNKNOWN','JWN','NORDSTROM','NORDSTROM_RACK','HAUTELOOK','TRUNK_CLUB')
    , experience VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('UNKNOWN','WEB','MOW','IOS','ANDROID','POS','IN_STORE_DIGITAL','CSR_STORE','CSR_APP','CSR_PHONE','BACKEND_SERVICE','RPOS','THIRD_PARTY_VENDOR')
    , session_id VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL
    , referrer VARCHAR(6000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , siteid VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_source VARCHAR(2000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_medium VARCHAR(2000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , sp_source VARCHAR(1000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_channel VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_campaign VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , sp_campaign VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_term VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , utm_content VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , gclid VARCHAR(3000) CHARACTER SET UNICODE NOT CASESPECIFIC
    , bounce_ind CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS('Y', 'N')
    , funnel_type VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS('Up', 'Low', 'Mid')
    , web_orders INT
    , web_demand_usd DECIMAL(15, 2)
    , session_type VARCHAR(15) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('ARRIVED','NON_ARRIVED')
    , mrkt_touch CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS('Y', 'N')
    , mrkt_type VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    , finance_rollup VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    , finance_detail VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
    , dw_sys_updt_tmstp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
)
PRIMARY INDEX (session_id)
PARTITION BY RANGE_N(activity_date_pacific BETWEEN DATE '2022-01-01' AND DATE '2025-01-01' EACH INTERVAL '1' DAY)
;

SET QUERY_BAND = NONE FOR SESSION;
