   /*
Purpose:        Creates empty table in {{environment_schema}} for Selection Productivity
                   selection_productivity

Variable(s):     {{environment_schema}} T2DL_DAS_SELECTION (prod) or T3DL_ACE_ASSORTMENT
                 {{env_suffix}} '' or '_dev' tablesuffix for prod testing
Author(s):       Sara Scott
*/



CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'selection_productivity{env_suffix}', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.selection_productivity{env_suffix} ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      month_idnt INTEGER NOT NULL,
      month_abrv VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC,
      quarter_idnt INTEGER NOT NULL,
      half_idnt INTEGER NOT NULL,
      year_idnt INTEGER NOT NULL,
      customer_choice VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      channel_brand VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_country CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC NOT NULL,
      div_idnt INTEGER,
      div_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      subdiv_idnt INTEGER,
      subdiv_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      dept_idnt INTEGER,
      dept_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      supplier_name VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      supp_part_num VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      quantrix_category VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      ccs_category VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  ccs_subcategory VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  nord_role_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  rack_role_desc VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
	  parent_group VARCHAR(100) CHARACTER SET UNICODE NOT CASESPECIFIC,
      days_live INTEGER,
      days_published DATE FORMAT 'YYYY-MM-DD',
      new_flag INTEGER,
      cf_flag INTEGER,
      npg_flag CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      rp_flag BYTEINT,
      dropship_flag BYTEINT,
      anniversary_flag BYTEINT,
      fanatics_flag CHAR(2) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_dept_cat_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_dept_cat_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_dept_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_dept_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_subdiv_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_subdiv_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_div_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_div_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      channel_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_dept_cat_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_dept_cat_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_dept_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_dept_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_subdiv_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_subdiv_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_div_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_div_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_demand_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      qtr_channel_sales_deciles VARCHAR(20) CHARACTER SET UNICODE NOT CASESPECIFIC,
      sales_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      demand_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      demand_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      sales_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      receipt_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      receipt_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      qtr_eoh_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      qtr_eoh_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      qtr_boh_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      qtr_boh_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      eoh_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      eoh_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      boh_dollars DECIMAL(20,2) NOT NULL DEFAULT 0.00  COMPRESS 0.00 ,
      boh_units DECIMAL(12,0) NOT NULL DEFAULT 0.  COMPRESS (0. ,1. ,2. ,3. ,4. ,5. ,-1. ),
      product_views DECIMAL(38,6),
      order_sessions INTEGER,
      instock_views DECIMAL(38,6),
      product_view_sessions INTEGER,
      order_demand DECIMAL(20,2) DEFAULT 0.00  COMPRESS 0.00 ,
      order_quantity INTEGER)
PRIMARY INDEX ( month_idnt ,customer_choice ,channel ,channel_country )
PARTITION BY RANGE_N(month_idnt  BETWEEN 201901  AND 201912  EACH 1 ,
202001  AND 202012  EACH 1 ,
202101  AND 202112  EACH 1 ,
202201  AND 202212  EACH 1 ,
202301  AND 202312  EACH 1 ,
202401  AND 202412  EACH 1 ,
202501  AND 202512  EACH 1 ,
202601  AND 202612  EACH 1 ,
202701  AND 202712  EACH 1 ,
202801  AND 202812  EACH 1 ,
202901  AND 202912  EACH 1 ,
203001  AND 203012  EACH 1 );
