UPDATE {{params.gcp_project_id}}.{{params.dbenv}}_NAP_UTL.ELT_CONTROL 
SET 
ACTIVE_LOAD_IND = 'Y', 
BATCH_ID = (SELECT BATCH_ID + 1 FROM
      {{params.gcp_project_id}}.{{params.dbenv}}_NAP_BASE_VWS.ELT_CONTROL AS ELT_CONTROL_0
    WHERE LOWER(SUBJECT_AREA_NM) = LOWER('PRODUCT_ITEM_SELLING_RIGHTS')
), CURR_BATCH_DATE = CASE
  WHEN ELT_CONTROL.CURR_BATCH_DATE < CURRENT_DATE('PST8PDT') THEN 
  DATE(ELT_CONTROL.CURR_BATCH_DATE + INTERVAL 1 DAY)
  ELSE ELT_CONTROL.CURR_BATCH_DATE
END, EXTRACT_FROM_TMSTP = CAST(ELT_CONTROL.EXTRACT_TO_TMSTP AS TIMESTAMP) - INTERVAL 1 DAY,
 EXTRACT_TO_TMSTP = CAST(current_datetime('PST8PDT') AS TIMESTAMP),
 BATCH_START_TMSTP = CAST(current_datetime('PST8PDT') AS TIMESTAMP)
 WHERE LOWER(ELT_CONTROL.SUBJECT_AREA_NM) = LOWER('PRODUCT_ITEM_SELLING_RIGHTS')
 AND LOWER(ELT_CONTROL.ACTIVE_LOAD_IND) = LOWER('N')
 AND ELT_CONTROL.CURR_BATCH_DATE <= CURRENT_DATE('PST8PDT');
 
 
 
