CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'RP_CONTRIBUTION_ROLLUP', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.RP_CONTRIBUTION_ROLLUP
    ,FALLBACK
	,NO BEFORE JOURNAL
	,NO AFTER JOURNAL
	,CHECKSUM = DEFAULT 
	,DEFAULT MERGEBLOCKRATIO 
(  
 WEEK_NUM	INTEGER NOT NULL
,WEEK_END_DAY_DATE DATE
,WEEK_NUM_OF_FISCAL_MONTH INTEGER
,WEEK_454_LABEL VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
,MONTH_ABRV VARCHAR(3) CHARACTER SET UNICODE CASESPECIFIC
,MONTH_IDNT INTEGER
,MONTH_454_LABEL VARCHAR(10) CHARACTER SET UNICODE NOT CASESPECIFIC
,FISCAL_MONTH_NUM BYTEINT
,MONTH_DESC VARCHAR(9) CHARACTER SET UNICODE NOT CASESPECIFIC
,QUARTER_DESC VARCHAR(11) CHARACTER SET UNICODE NOT CASESPECIFIC
,FISCAL_YEAR_NUM INTEGER
,TY_LY_IND VARCHAR(3) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('TY','LY','LLY')
,CHANNEL_NUM	INTEGER NOT NULL
,CHANNEL_DESC	VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
,DIVISION_NUM	INTEGER
,DIVISION_DESC	VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
,SUBDIVISION_NUM	INTEGER
,SUBDIVISION_DESC	VARCHAR(50) CHARACTER SET UNICODE NOT CASESPECIFIC
,DEPARTMENT_NUM	INTEGER NOT NULL
,DEPARTMENT_DESC	VARCHAR(150) CHARACTER SET UNICODE NOT CASESPECIFIC
,CLASS_NUM	INTEGER NOT NULL
,CLASS_DESC	VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
,SUPPLIER_NUM	VARCHAR(10) NOT NULL CHARACTER SET UNICODE NOT CASESPECIFIC
,SUPPLIER_NAME	VARCHAR(60) CHARACTER SET UNICODE NOT CASESPECIFIC
,NPG_IND	CHAR(1) CHARACTER SET UNICODE NOT CASESPECIFIC COMPRESS ('N','Y')
,RPL_EOH_TOTAL_RETAIL	DECIMAL(33,2)
,NRP_EOH_TOTAL_RETAIL	DECIMAL(33,2)
,RPL_EOH_TOTAL_COST	DECIMAL(33,2)
,NRP_EOH_TOTAL_COST	DECIMAL(33,2)
,RPL_EOH_TOTAL_UNITS	INTEGER
,NRP_EOH_TOTAL_UNITS	INTEGER
,RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT DECIMAL(38,4)
,NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT DECIMAL(38,4)
,RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT DECIMAL(38,4)
,NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT DECIMAL(38,4)
,RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS INTEGER
,NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS INTEGER
,RPL_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT	DECIMAL(38,4)
,NRP_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT	DECIMAL(38,4)
,RPL_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT		DECIMAL(38,4)
,NRP_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT		DECIMAL(38,4)
,RPL_JWN_OPERATIONAL_GMV_TOTAL_UNITS		INTEGER
,NRP_JWN_OPERATIONAL_GMV_TOTAL_UNITS		INTEGER
,RPL_RECEIPTS_TOTAL_RETAIL_AMT				DECIMAL(38,4)
,NRP_RECEIPTS_TOTAL_RETAIL_AMT				DECIMAL(38,4)
,RPL_RECEIPTS_TOTAL_COST_AMT				DECIMAL(38,4)
,NRP_RECEIPTS_TOTAL_COST_AMT				DECIMAL(38,4)
,RPL_RECEIPTS_TOTAL_UNITS					INTEGER
,NRP_RECEIPTS_TOTAL_UNITS					INTEGER
,RPL_RECEIPTS_PO_RETAIL_AMT DECIMAL(38,4)
,NRP_RECEIPTS_PO_RETAIL_AMT DECIMAL(38,4)
,RPL_RECEIPTS_PO_COST_AMT   DECIMAL(38,4)
,NRP_RECEIPTS_PO_COST_AMT   DECIMAL(38,4)
,RPL_RECEIPTS_PO_UNITS INTEGER
,NRP_RECEIPTS_PO_UNITS INTEGER
,RPL_INVENTORY_BOH_TOTAL_UNITS				INTEGER
,NRP_INVENTORY_BOH_TOTAL_UNITS				INTEGER
,RPL_INVENTORY_BOH_TOTAL_RETAIL_AMT			DECIMAL(38,4)
,NRP_INVENTORY_BOH_TOTAL_RETAIL_AMT			DECIMAL(38,4)
,RPL_INVENTORY_BOH_TOTAL_COST_AMT			DECIMAL(38,4)
,NRP_INVENTORY_BOH_TOTAL_COST_AMT			DECIMAL(38,4)
,DW_SYS_LOAD_TMSTP                          TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0)
)
PRIMARY INDEX (WEEK_NUM,CHANNEL_NUM,DEPARTMENT_NUM,CLASS_NUM,SUPPLIER_NUM);

GRANT SELECT ON {environment_schema}.RP_CONTRIBUTION_ROLLUP TO PUBLIC;


		
