/*
Name:RP Contribution
Project:RP Contribution Dashboard
Purpose: Serve as the datasource to the Tableau RP Contribution Published Data Source and to the RP Contribution Dashboard
Variable(s): {{environment_schema}} T2DL_DAS_IN_SEASON_MANAGEMENT_REPORTING
DAG: merch_main_rp_contribution_9850_MERCH_ANALYTICS_insights 
schedule: 00 3 * * 1
Author(s):Jen Latta
Date Created:1/11/24
Date Updated:1/16/24
Updates: 
	* Add BOH Units, BOH Retail, and BOH Cost
	* Add DW_SYS_LOAD_TMSTP 

Date Updated:1/31/24
Updates: 
	* Add EOH_IN_TRANSIT Units, EOH_IN_TRANSIT Retail, EOH_IN_TRANSIT Cost
	* Add RECEIPTS_PO Units, RECEIPTS_PO Retail, RECEIPTS_PO Cost
	
Date Updated: 3/11/24
Updates:
	* Add WEEK_END_DAY_DATE

*/

CREATE MULTISET VOLATILE TABLE WEEK_DIM_LKUP AS (

SELECT DISTINCT
 r.WEEK_IDNT AS WEEK_IDNT
,d.WEEK_IDNT AS WEEK_IDNT_TRUE
,r.WEEK_NUM_OF_FISCAL_MONTH AS WEEK_NUM_OF_FISCAL_MONTH
,r.WEEK_454_LABEL AS WEEK_454_LABEL
,r.MONTH_ABRV AS MONTH_ABRV
,r.MONTH_IDNT AS MONTH_IDNT
,r.MONTH_454_LABEL AS MONTH_454_LABEL
,r.FISCAL_MONTH_NUM AS FISCAL_MONTH_NUM
,r.MONTH_DESC AS MONTH_DESC 
,r.QUARTER_DESC AS QUARTER_DESC
,r.FISCAL_YEAR_NUM AS FISCAL_YEAR_NUM
,r.TY_LY_LLY_IND AS TY_LY_IND
,r.week_end_day_date AS WEEK_END_DAY_DATE
FROM PRD_NAP_VWS.REALIGNED_DATE_LKUP_VW r 
LEFT JOIN PRD_NAP_USR_VWS.DAY_CAL_454_DIM d
ON r.DAY_DATE = d.DAY_DATE 
WHERE 
r.FISCAL_YEAR_NUM BETWEEN(SELECT MAX(FISCAL_YEAR_NUM)-2 FROM PRD_NAP_VWS.REALIGNED_DATE_LKUP_VW WHERE WEEK_END_DAY_DATE < CURRENT_DATE)
        AND (SELECT MAX(FISCAL_YEAR_NUM) FROM PRD_NAP_VWS.REALIGNED_DATE_LKUP_VW WHERE WEEK_END_DAY_DATE < CURRENT_DATE) 
        AND r.WEEK_IDNT <= (SELECT MAX(WEEK_IDNT) FROM PRD_NAP_VWS.REALIGNED_DATE_LKUP_VW WHERE WEEK_END_DAY_DATE < CURRENT_DATE)
		
)       
WITH DATA 
PRIMARY INDEX (WEEK_IDNT) 
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(WEEK_IDNT) ON WEEK_DIM_LKUP;


CREATE MULTISET VOLATILE TABLE STORE_DIM_LKUP AS (
SELECT DISTINCT
	STORE_NUM AS STORE_NUM,
	CHANNEL_NUM AS CHANNEL_NUM,
	CHANNEL_DESC AS CHANNEL_DESC
	FROM PRD_NAP_USR_VWS.STORE_DIM 
	WHERE STORE_COUNTRY_CODE='US'
	AND STORE_ABBREV_NAME <> 'CLOSED'
	AND CHANNEL_NUM NOT IN (140, 930, 990) /* Trunk Club- chnl 140,  NQC- chnl 930, FACO- chnl 990 */
	AND CHANNEL_NUM IS NOT NULL
)
WITH DATA 
PRIMARY INDEX (STORE_NUM,CHANNEL_NUM)
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(STORE_NUM,CHANNEL_NUM) ON STORE_DIM_LKUP;

CREATE MULTISET VOLATILE TABLE DEPT_CLASS_DIM_LKUP AS (
SELECT DISTINCT
	 DEPT_NUM AS DEPT_NUM
	,DEPT_DESC AS DEPT_DESC 
	,DIVISION_NUM AS DIVISION_NUM
	,DIVISION_DESC AS DIVISION_DESC
	,SUBDIVISION_NUM AS SUBDIVISION_NUM
	,SUBDIVISION_DESC AS SUBDIVISION_DESC 
	,CLASS_NUM AS CLASS_NUM
	,CLASS_DESC AS CLASS_DESC
FROM PRD_NAP_VWS.MERCH_PRODUCT_SUBCLASS_DIM_VW
WHERE UPPER(DEPT_DESC) not like      '%INACTIVE%'
AND UPPER(DIVISION_DESC)  not like    '%INACTIVE%'
AND UPPER(SUBDIVISION_DESC)  not like '%INACTIVE%'
)
WITH DATA 
PRIMARY INDEX (DEPT_NUM,CLASS_NUM)
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(DEPT_NUM,CLASS_NUM) ON DEPT_CLASS_DIM_LKUP ;


CREATE MULTISET VOLATILE TABLE VENDOR_DIM_LKUP AS (
SELECT DISTINCT
	VENDOR_NUM AS VENDOR_NUM, 
	VENDOR_NAME AS VENDOR_NAME
FROM PRD_NAP_USR_VWS.VENDOR_DIM
)
WITH DATA 
PRIMARY INDEX (VENDOR_NUM)
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(VENDOR_NUM) ON VENDOR_DIM_LKUP;

CREATE MULTISET VOLATILE TABLE RP_CONTRIBUTION_FACT AS (

SELECT
	d.WEEK_IDNT AS WEEK_NUM,
	f.CHANNEL_NUM AS CHANNEL_NUM,
	f.DEPT_NUM AS DEPT_NUM,
	f.STORE_NUM AS STORE_NUM,
	f.SUPP_NUM AS SUPP_NUM,
	f.CLASS_NUM AS CLASS_NUM,
	f.NPG_IND AS NPG_IND,
 	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS RPL_EOH_TOTAL_RETAIL,
 	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_EOH_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS NRP_EOH_TOTAL_RETAIL,
 	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_EOH_TOTAL_COST_AMT_TY ELSE 0 END) AS RPL_EOH_TOTAL_COST,
 	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_EOH_TOTAL_COST_AMT_TY  ELSE 0 END) AS NRP_EOH_TOTAL_COST,
 	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE 0 END) AS RPL_EOH_TOTAL_UNITS,
 	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_EOH_TOTAL_UNITS_TY ELSE 0 END) AS NRP_EOH_TOTAL_UNITS,
	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT,
	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT,
	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY ELSE 0 END) AS RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT,
	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT_TY ELSE 0 END) AS NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT,
	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY ELSE 0 END) AS RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS,
	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS_TY ELSE 0 END) AS NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS,
 	SUM(CASE WHEN f.rp_ind='Y' THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS RPL_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT,
    SUM(CASE WHEN f.rp_ind='N' THEN JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS NRP_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT,
    SUM(CASE WHEN f.rp_ind='Y' THEN JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY ELSE 0 END) AS RPL_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT,
    SUM(CASE WHEN f.rp_ind='N' THEN JWN_OPERATIONAL_GMV_TOTAL_COST_AMT_TY ELSE 0 END) AS NRP_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT,
    SUM(CASE WHEN f.rp_ind='Y' THEN JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY ELSE 0 END) AS RPL_JWN_OPERATIONAL_GMV_TOTAL_UNITS,
    SUM(CASE WHEN f.rp_ind='N' THEN JWN_OPERATIONAL_GMV_TOTAL_UNITS_TY ELSE 0 END) AS NRP_JWN_OPERATIONAL_GMV_TOTAL_UNITS,
	SUM(CASE WHEN f.rp_ind='Y' THEN RECEIPTS_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS RPL_RECEIPTS_TOTAL_RETAIL_AMT,
    SUM(CASE WHEN f.rp_ind='N' THEN RECEIPTS_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS NRP_RECEIPTS_TOTAL_RETAIL_AMT,
    SUM(CASE WHEN f.rp_ind='Y' THEN RECEIPTS_TOTAL_COST_AMT_TY ELSE 0 END) AS RPL_RECEIPTS_TOTAL_COST_AMT,
    SUM(CASE WHEN f.rp_ind='N' THEN RECEIPTS_TOTAL_COST_AMT_TY ELSE 0 END) AS NRP_RECEIPTS_TOTAL_COST_AMT,
    SUM(CASE WHEN f.rp_ind='Y' THEN RECEIPTS_TOTAL_UNITS_TY ELSE 0 END) AS RPL_RECEIPTS_TOTAL_UNITS,
    SUM(CASE WHEN f.rp_ind='N' THEN RECEIPTS_TOTAL_UNITS_TY ELSE 0 END) AS NRP_RECEIPTS_TOTAL_UNITS,
 	SUM(CASE WHEN f.rp_ind='Y' THEN RECEIPTS_PO_RETAIL_AMT_TY ELSE 0 END) AS RPL_RECEIPTS_PO_RETAIL_AMT,
	SUM(CASE WHEN f.rp_ind='N' THEN RECEIPTS_PO_RETAIL_AMT_TY ELSE 0 END) AS NRP_RECEIPTS_PO_RETAIL_AMT,
	SUM(CASE WHEN f.rp_ind='Y' THEN RECEIPTS_PO_COST_AMT_TY ELSE 0 END) AS RPL_RECEIPTS_PO_COST_AMT,
	SUM(CASE WHEN f.rp_ind='N' THEN RECEIPTS_PO_COST_AMT_TY ELSE 0 END) AS NRP_RECEIPTS_PO_COST_AMT,
	SUM(CASE WHEN f.rp_ind='Y' THEN RECEIPTS_PO_UNITS_TY ELSE 0 END) AS RPL_RECEIPTS_PO_UNITS,
	SUM(CASE WHEN f.rp_ind='N' THEN RECEIPTS_PO_UNITS_TY ELSE 0 END) AS NRP_RECEIPTS_PO_UNITS,
	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_BOH_TOTAL_UNITS_TY ELSE 0 END) AS RPL_INVENTORY_BOH_TOTAL_UNITS,
	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_BOH_TOTAL_UNITS_TY ELSE 0 END) AS NRP_INVENTORY_BOH_TOTAL_UNITS,
	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_BOH_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS RPL_INVENTORY_BOH_TOTAL_RETAIL_AMT,
	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_BOH_TOTAL_RETAIL_AMT_TY ELSE 0 END) AS NRP_INVENTORY_BOH_TOTAL_RETAIL_AMT,
	SUM(CASE WHEN f.rp_ind='Y' THEN INVENTORY_BOH_TOTAL_COST_AMT_TY ELSE 0 END) AS RPL_INVENTORY_BOH_TOTAL_COST_AMT,
	SUM(CASE WHEN f.rp_ind='N' THEN INVENTORY_BOH_TOTAL_COST_AMT_TY ELSE 0 END) AS NRP_INVENTORY_BOH_TOTAL_COST_AMT

FROM PRD_NAP_USR_VWS.MERCH_TRANSACTION_SBCLASS_STORE_WEEK_AGG_FACT f
INNER JOIN WEEK_DIM_LKUP d
ON f.WEEK_NUM=d.WEEK_IDNT_TRUE
GROUP BY
	d.WEEK_IDNT,
	f.CHANNEL_NUM,
	f.DEPT_NUM,
	f.STORE_NUM,
	f.SUPP_NUM,
	f.CLASS_NUM,
	f.NPG_IND
)

WITH DATA 
PRIMARY INDEX (WEEK_NUM,CHANNEL_NUM,DEPT_NUM,CLASS_NUM,STORE_NUM,SUPP_NUM,NPG_IND)
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(WEEK_NUM,CHANNEL_NUM,DEPT_NUM,CLASS_NUM,STORE_NUM,SUPP_NUM,NPG_IND) ON RP_CONTRIBUTION_FACT;

CREATE MULTISET VOLATILE TABLE RP_CONTRIBUTION_FACT_DIM AS (

SELECT 
	f.WEEK_NUM AS WEEK_NUM,
	f.DEPT_NUM AS DEPARTMENT_NUM,
	dc.DEPT_DESC AS DEPARTMENT_DESC,
	dc.DIVISION_NUM AS DIVISION_NUM,
	dc.DIVISION_DESC as DIVISION_DESC, 
	dc.SUBDIVISION_NUM as SUBDIVISION_NUM,
	dc.SUBDIVISION_DESC as SUBDIVISION_DESC,
	f.SUPP_NUM AS SUPPLIER_NUM,
	vd.VENDOR_NAME AS SUPPLIER_NAME,
	f.CLASS_NUM AS CLASS_NUM,
	dc.CLASS_DESC as CLASS_DESC,
	f.NPG_IND AS NPG_IND,
	orgstore.CHANNEL_NUM AS CHANNEL_NUM,
	orgstore.CHANNEL_DESC AS CHANNEL_DESC,
 	SUM(RPL_EOH_TOTAL_RETAIL) AS RPL_EOH_TOTAL_RETAIL,
 	SUM(NRP_EOH_TOTAL_RETAIL) AS NRP_EOH_TOTAL_RETAIL,
 	SUM(RPL_EOH_TOTAL_COST) AS RPL_EOH_TOTAL_COST,
 	SUM(NRP_EOH_TOTAL_COST) AS NRP_EOH_TOTAL_COST,
 	SUM(RPL_EOH_TOTAL_UNITS) AS RPL_EOH_TOTAL_UNITS,
 	SUM(NRP_EOH_TOTAL_UNITS) AS NRP_EOH_TOTAL_UNITS,
	SUM(RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT) AS RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT,
	SUM(NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT) AS NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT,
	SUM(RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT) AS RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT,
	SUM(NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT) AS NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT,
	SUM(RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS) AS RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS,
	SUM(NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS) AS NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS,
 	SUM(RPL_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT) AS RPL_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT,
    SUM(NRP_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT) AS NRP_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT,
    SUM(RPL_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT) AS RPL_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT,
    SUM(NRP_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT) AS NRP_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT,
    SUM(RPL_JWN_OPERATIONAL_GMV_TOTAL_UNITS) AS RPL_JWN_OPERATIONAL_GMV_TOTAL_UNITS,
    SUM(NRP_JWN_OPERATIONAL_GMV_TOTAL_UNITS) AS NRP_JWN_OPERATIONAL_GMV_TOTAL_UNITS,
	SUM(RPL_RECEIPTS_TOTAL_RETAIL_AMT) AS RPL_RECEIPTS_TOTAL_RETAIL_AMT,
    SUM(NRP_RECEIPTS_TOTAL_RETAIL_AMT) AS NRP_RECEIPTS_TOTAL_RETAIL_AMT,
    SUM(RPL_RECEIPTS_TOTAL_COST_AMT) AS RPL_RECEIPTS_TOTAL_COST_AMT,
    SUM(NRP_RECEIPTS_TOTAL_COST_AMT) AS NRP_RECEIPTS_TOTAL_COST_AMT,
    SUM(RPL_RECEIPTS_TOTAL_UNITS) AS RPL_RECEIPTS_TOTAL_UNITS,
    SUM(NRP_RECEIPTS_TOTAL_UNITS) AS NRP_RECEIPTS_TOTAL_UNITS,
	SUM(RPL_RECEIPTS_PO_RETAIL_AMT) AS RPL_RECEIPTS_PO_RETAIL_AMT,
	SUM(NRP_RECEIPTS_PO_RETAIL_AMT) AS NRP_RECEIPTS_PO_RETAIL_AMT,
	SUM(RPL_RECEIPTS_PO_COST_AMT) AS RPL_RECEIPTS_PO_COST_AMT,
	SUM(NRP_RECEIPTS_PO_COST_AMT) AS NRP_RECEIPTS_PO_COST_AMT,
	SUM( RPL_RECEIPTS_PO_UNITS) AS RPL_RECEIPTS_PO_UNITS,
	SUM(NRP_RECEIPTS_PO_UNITS) AS NRP_RECEIPTS_PO_UNITS,
	SUM(RPL_INVENTORY_BOH_TOTAL_UNITS) AS RPL_INVENTORY_BOH_TOTAL_UNITS,
	SUM(NRP_INVENTORY_BOH_TOTAL_UNITS) AS NRP_INVENTORY_BOH_TOTAL_UNITS,
	SUM(RPL_INVENTORY_BOH_TOTAL_RETAIL_AMT) AS RPL_INVENTORY_BOH_TOTAL_RETAIL_AMT,
	SUM(NRP_INVENTORY_BOH_TOTAL_RETAIL_AMT) AS NRP_INVENTORY_BOH_TOTAL_RETAIL_AMT,
	SUM(RPL_INVENTORY_BOH_TOTAL_COST_AMT) AS RPL_INVENTORY_BOH_TOTAL_COST_AMT,
	SUM(NRP_INVENTORY_BOH_TOTAL_COST_AMT) AS NRP_INVENTORY_BOH_TOTAL_COST_AMT
	
FROM RP_CONTRIBUTION_FACT f
INNER JOIN STORE_DIM_LKUP orgstore
ON f.STORE_NUM=orgstore.STORE_NUM
INNER JOIN DEPT_CLASS_DIM_LKUP  dc
ON dc.DEPT_NUM=f.DEPT_NUM
AND dc.CLASS_NUM=f.CLASS_NUM
INNER JOIN VENDOR_DIM_LKUP vd
on vd.VENDOR_NUM=f.SUPP_NUM
GROUP BY 
	f.WEEK_NUM,
	f.DEPT_NUM,
	dc.DEPT_DESC,
	dc.DIVISION_NUM,
	dc.DIVISION_DESC, 
	dc.SUBDIVISION_NUM,
	dc.SUBDIVISION_DESC,
	f.SUPP_NUM,
	vd.VENDOR_NAME,
	f.CLASS_NUM,
	dc.CLASS_DESC,
	f.NPG_IND,
	orgstore.CHANNEL_NUM,
	orgstore.CHANNEL_DESC
)

WITH DATA 
PRIMARY INDEX (WEEK_NUM,CHANNEL_NUM,DEPARTMENT_NUM,DIVISION_NUM,SUBDIVISION_NUM,SUPPLIER_NUM,CLASS_NUM,NPG_IND)
ON COMMIT PRESERVE ROWS;
COLLECT STATS PRIMARY INDEX(WEEK_NUM,CHANNEL_NUM,DEPARTMENT_NUM,DIVISION_NUM,SUBDIVISION_NUM,SUPPLIER_NUM,CLASS_NUM,NPG_IND) ON RP_CONTRIBUTION_FACT_DIM;

DELETE {environment_schema}.RP_CONTRIBUTION_ROLLUP ALL;

INSERT INTO {environment_schema}.RP_CONTRIBUTION_ROLLUP
(

 WEEK_NUM
,WEEK_END_DAY_DATE
,WEEK_NUM_OF_FISCAL_MONTH 
,WEEK_454_LABEL
,MONTH_ABRV
,MONTH_IDNT 
,MONTH_454_LABEL 
,FISCAL_MONTH_NUM 
,MONTH_DESC
,QUARTER_DESC
,FISCAL_YEAR_NUM 
,TY_LY_IND
,CHANNEL_NUM
,CHANNEL_DESC
,DIVISION_NUM   
,DIVISION_DESC  
,SUBDIVISION_NUM    
,SUBDIVISION_DESC   
,DEPARTMENT_NUM 
,DEPARTMENT_DESC    
,CLASS_NUM  
,CLASS_DESC 
,SUPPLIER_NUM   
,SUPPLIER_NAME  
,NPG_IND    
,RPL_EOH_TOTAL_RETAIL   
,NRP_EOH_TOTAL_RETAIL   
,RPL_EOH_TOTAL_COST 
,NRP_EOH_TOTAL_COST 
,RPL_EOH_TOTAL_UNITS    
,NRP_EOH_TOTAL_UNITS
,RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT 
,NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT 
,RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT 
,NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT 
,RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS 
,NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS 
,RPL_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT    
,NRP_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT  
,RPL_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT
,NRP_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT
,RPL_JWN_OPERATIONAL_GMV_TOTAL_UNITS 
,NRP_JWN_OPERATIONAL_GMV_TOTAL_UNITS 
,RPL_RECEIPTS_TOTAL_RETAIL_AMT   
,NRP_RECEIPTS_TOTAL_RETAIL_AMT   
,RPL_RECEIPTS_TOTAL_COST_AMT
,NRP_RECEIPTS_TOTAL_COST_AMT 
,RPL_RECEIPTS_TOTAL_UNITS    
,NRP_RECEIPTS_TOTAL_UNITS   
,RPL_RECEIPTS_PO_RETAIL_AMT
,NRP_RECEIPTS_PO_RETAIL_AMT 
,RPL_RECEIPTS_PO_COST_AMT
,NRP_RECEIPTS_PO_COST_AMT
,RPL_RECEIPTS_PO_UNITS 
,NRP_RECEIPTS_PO_UNITS 
,RPL_INVENTORY_BOH_TOTAL_UNITS			
,NRP_INVENTORY_BOH_TOTAL_UNITS				
,RPL_INVENTORY_BOH_TOTAL_RETAIL_AMT			
,NRP_INVENTORY_BOH_TOTAL_RETAIL_AMT			
,RPL_INVENTORY_BOH_TOTAL_COST_AMT			
,NRP_INVENTORY_BOH_TOTAL_COST_AMT
,DW_SYS_LOAD_TMSTP  
)
SELECT 
    r.WEEK_NUM,
	d.WEEK_END_DAY_DATE,
    d.WEEK_NUM_OF_FISCAL_MONTH,
    d.WEEK_454_LABEL,
    d.MONTH_ABRV,
    d.MONTH_IDNT,
    d.MONTH_454_LABEL,
    d.FISCAL_MONTH_NUM,
    d.MONTH_DESC,
    d.QUARTER_DESC,
    d.FISCAL_YEAR_NUM,
	d.TY_LY_IND,
    r.CHANNEL_NUM,
    r.CHANNEL_DESC,
    r.DIVISION_NUM,
    r.DIVISION_DESC,
    r.SUBDIVISION_NUM,
    r.SUBDIVISION_DESC,
    r.DEPARTMENT_NUM,
    r.DEPARTMENT_DESC,
    r.CLASS_NUM,
    r.CLASS_DESC,
    r.SUPPLIER_NUM,
    r.SUPPLIER_NAME,
    r.NPG_IND,
    r.RPL_EOH_TOTAL_RETAIL,
    r.NRP_EOH_TOTAL_RETAIL,
    r.RPL_EOH_TOTAL_COST,
    r.NRP_EOH_TOTAL_COST,
    r.RPL_EOH_TOTAL_UNITS,
    r.NRP_EOH_TOTAL_UNITS,
	r.RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT, 
	r.NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_RETAIL_AMT, 
	r.RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT, 
	r.NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_COST_AMT, 
	r.RPL_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS, 
	r.NRP_INVENTORY_EOH_IN_TRANSIT_TOTAL_UNITS,
    r.RPL_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT,
    r.NRP_JWN_OPERATIONAL_GMV_TOTAL_RETAIL_AMT,
    r.RPL_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT,
    r.NRP_JWN_OPERATIONAL_GMV_TOTAL_COST_AMT,
    r.RPL_JWN_OPERATIONAL_GMV_TOTAL_UNITS,
    r.NRP_JWN_OPERATIONAL_GMV_TOTAL_UNITS,
    r.RPL_RECEIPTS_TOTAL_RETAIL_AMT,
    r.NRP_RECEIPTS_TOTAL_RETAIL_AMT,
    r.RPL_RECEIPTS_TOTAL_COST_AMT,
    r.NRP_RECEIPTS_TOTAL_COST_AMT,
    r.RPL_RECEIPTS_TOTAL_UNITS,
    r.NRP_RECEIPTS_TOTAL_UNITS,
	r.RPL_RECEIPTS_PO_RETAIL_AMT,
	r.NRP_RECEIPTS_PO_RETAIL_AMT, 
	r.RPL_RECEIPTS_TOTAL_COST_AMT, 
	r.NRP_RECEIPTS_TOTAL_COST_AMT, 
	r.RPL_RECEIPTS_PO_UNITS, 
	r.NRP_RECEIPTS_PO_UNITS, 
    r.RPL_INVENTORY_BOH_TOTAL_UNITS,			
	r.NRP_INVENTORY_BOH_TOTAL_UNITS,				
	r.RPL_INVENTORY_BOH_TOTAL_RETAIL_AMT,			
	r.NRP_INVENTORY_BOH_TOTAL_RETAIL_AMT,			
	r.RPL_INVENTORY_BOH_TOTAL_COST_AMT,			
	r.NRP_INVENTORY_BOH_TOTAL_COST_AMT,
	CURRENT_TIMESTAMP(0) AS DW_SYS_LOAD_TMSTP  
	FROM RP_CONTRIBUTION_FACT_DIM r
	INNER JOIN WEEK_DIM_LKUP d
	ON r.WEEK_NUM=d.WEEK_IDNT;
	
COLLECT STATS PRIMARY INDEX(WEEK_NUM,CHANNEL_NUM,DEPARTMENT_NUM,CLASS_NUM,SUPPLIER_NUM) ON {environment_schema}.RP_CONTRIBUTION_ROLLUP;





