-- noqa: disable=all
CREATE TABLE IF NOT EXISTS {delta_schema_name}.customer_activity_intermediate_session_delta
(
  sessionId string,
  sessionLastUpdatedTime_utc timestamp,
  sessionLastUpdatedTime_pst timestamp,
  sessionAlgorithmId string,
  sessionStartTime_utc timestamp,
  sessionStartTime_pst timestamp,
  sessionEndTime_utc timestamp,
  sessionEndTime_pst timestamp,
  sessionDuration_seconds int,
  sessionBounceInd char(1),
  sessionExperience string,
  sessionChannel struct<channelCountry:string,channelBrand:string,sellingChannel:string>,
  sessionEventName string,
  sessionEventId string,
  eventId string,
  eventHeaderEventTime_utc timestamp,
  eventHeaderEventTime_pst timestamp,
  eventSystemTime_utc timestamp,
  eventSystemTime_pst timestamp,
  eventHeaders map<string,binary>,
  eventtime_utc timestamp,
  eventtime_pst timestamp,
  source struct<channelcountry:string,channel:string,platform:string,feature:string,servicename:string,store:string,register:string>,
  customer struct<idtype:string,id:string>,
  credentials struct<iconid:string,shopperid:string,tokenizingcreditcardhvt:struct<value:string,authority:string,strategy:string,dataclassification:string>,creditcardhvt:struct<value:string,authority:string,dataclassification:string>,fraudtoken:string,useragent:string,tokenizingipaddress:struct<value:string,authority:string,strategy:string,dataclassification:string>,ipaddress:struct<value:string,authority:string,dataclassification:string>,experimentid:string,adtrackingstatus:string,advertisingid:string,applevendorid:string,firebaseinstanceid:string>,
  contextid string,
  referrer string,
  requesteddestination string,
  actualdestination string,
  bagtype string,
  bagactiontype string,
  product struct<idtype:string,id:string>,
  productstyle struct<idtype:string,id:string>,
  quantity int,
  bagsize int,
  context struct<id:string,pagetype:string,pageinstanceid:string,digitalcontents:array<struct<idtype:string,id:string>>,enticement:string,pagecontainer:string>,
  element struct<type:string,id:string,subid:string,value:string,valuehierarchy:array<string>,index:int,state:string>,
  elements array<struct<type:string,id:string,subid:string,value:string,valuehierarchy:array<string>,index:int,state:string>>,
  filters map<string,array<string>>,
  pageinstanceid string,
  productsummarycollection array<struct<productstyle:struct<idtype:string,id:string>,productsku:struct<idtype:string,id:string>,element:struct<id:string,subid:string,index:int,subindex:int>,enticements:array<string>>>,
  productsummary struct<productstyle:struct<idtype:string,id:string>,productsku:struct<idtype:string,id:string>,element:struct<id:string,subid:string,index:int,subindex:int>,enticements:array<string>>,
  searchresults array<struct<productstyle:struct<idtype:string,id:string>,relevancescore:double,inventoryconfidence:int,instockrate:double,perishability:double,pageviews:int,numberofreviews:int,averagerating:double,purchases:int,addtocart:int,newflag:boolean,designerflag:boolean,maxpercentoff:double,mincurrentprice:struct<currencycode:string,units:bigint,nanos:int>,enticements:array<struct<type:string,displaytext:string,descriptionhtml:string>>,offerenticements:array<struct<type:string,displaytext:string,copy:string>>>>,
  invoice struct<ordernumber:string,ordersessionid:string,subtotal:struct<currencycode:string,units:bigint,nanos:int>,discount:struct<currencycode:string,units:bigint,nanos:int>,shipping:struct<currencycode:string,units:bigint,nanos:int>,fees:array<struct<feeid:string,amount:struct<currencycode:string,units:bigint,nanos:int>,feetype:string>>,shippingoverride:struct<originalshipping:struct<currencycode:string,units:bigint,nanos:int>,reason:string>,anniversaryearlyaccessoverride:string,chargedpromise:struct<maxpromisedate:timestamp,promisetype:string,promisemode:string>,giftoptionstotal:struct<currencycode:string,units:bigint,nanos:int>,tax:struct<currencycode:string,units:bigint,nanos:int>,taxadjustmentdetails:struct<taxmodificationtype:string,taxmodificationentrymethod:string,taxmodificationreason:string,amount:struct<currencycode:string,units:bigint,nanos:int>,governmentidentifier:struct<governmentidtype:string,id:struct<value:string,authority:string,strategy:string,dataclassification:string>,expirydate:date>,offlinereturntaxlocation:struct<city:string,state:string,postalcode:binary,salescountry:string>>,total:struct<currencycode:string,units:bigint,nanos:int>,createtime:timestamp,customercontact:struct<email:struct<value:string,authority:string,strategy:string,dataclassification:string>,phone:struct<value:string,authority:string,strategy:string,dataclassification:string>,firstname:struct<value:string,authority:string,strategy:string,dataclassification:string>,lastname:struct<value:string,authority:string,strategy:string,dataclassification:string>>,referredby:string>,
  items array<struct<orderlineid:string,orderlinenumber:string,product:struct<idtype:string,id:string>,productstyle:struct<idtype:string,id:string>,destination:struct<storenumber:string,address:struct<id:string,firstname:struct<value:string,authority:string,strategy:string,dataclassification:string>,lastname:struct<value:string,authority:string,strategy:string,dataclassification:string>,middlename:struct<value:string,authority:string,strategy:string,dataclassification:string>,line1:struct<value:string,authority:string,strategy:string,dataclassification:string>,line2:struct<value:string,authority:string,strategy:string,dataclassification:string>,line3:struct<value:string,authority:string,strategy:string,dataclassification:string>,city:string,state:string,postalcode:struct<value:string,authority:string,strategy:string,dataclassification:string>,coarsepostalcode:string,countrycode:string,maskaddress:boolean>>,price:struct<current:struct<currencycode:string,units:bigint,nanos:int>,ownership:struct<currencycode:string,units:bigint,nanos:int>,regular:struct<currencycode:string,units:bigint,nanos:int>,percentoff:double,discount:struct<currencycode:string,units:bigint,nanos:int>,taxdetail:struct<taxbreakdown:array<struct<amount:struct<currencycode:string,units:bigint,nanos:int>,category:string>>,tax:struct<currencycode:string,units:bigint,nanos:int>>,adjustmentdetail:struct<discount:struct<currencycode:string,units:bigint,nanos:int>,adjustmentreason:string,pricematchurl:string>,total:struct<currencycode:string,units:bigint,nanos:int>>,promotions:array<struct<promotionid:string,changetype:string,reason:string,discount:struct<currencycode:string,units:bigint,nanos:int>,percentoff:double,activationcode:string,employee:struct<idtype:string,id:string>>>,promise:struct<maxpromisedate:timestamp,promisetype:string,promisemode:string>,backorder:boolean,isgwp:boolean,isbeautysample:boolean,isfinalsale:boolean,customizations:map<string,string>,metadata:map<string,string>,wishlistid:string,upc:string,giftoption:struct<type:string,giftoptionindex:string,recipientemail:struct<value:string,authority:string,strategy:string,dataclassification:string>,from:struct<value:string,authority:string,strategy:string,dataclassification:string>,to:struct<value:string,authority:string,strategy:string,dataclassification:string>,message:struct<value:string,authority:string,strategy:string,dataclassification:string>,cost:struct<currencycode:string,units:bigint,nanos:int>>,assistedbyemployee:struct<idtype:string,id:string>>>,
  clientInstanceId string,
  activityDate_pst date,
  batch_id int,
  batch_date date,
  rcd_load_tmstp timestamp,
  rcd_update_tmstp timestamp
)
USING DELTA
PARTITIONED BY (activityDate_pst)
LOCATION 's3://{delta_s3_bucket}/session_event_delta/customer_activity_intermediate_session_delta/';
-- noqa: enable=all
