--ddl, run just one time to create the base table that we insert into it.  
/*
ast_pipeline_prod_ddl_mfp_on_order_hist.sql
Author: Paria Avij
project: planned history report
Purpose: To create the snap shot of prd_nap_vws.MERCH_ON_ORDER_FACT_VW table for planned history report
Date Created: 01/24/23

Datalab: t2dl_das_open_to_buy
Updates Tables: 
    - merch_on_order_hist_plans
*/

CALL SYS_MGMT.DROP_IF_EXISTS_SP ('{environment_schema}', 'merch_on_order_hist_plans{env_suffix}', OUT_RETURN_MSG);
CREATE MULTISET TABLE {environment_schema}.merch_on_order_hist_plans{env_suffix} ,FALLBACK , 
	NO BEFORE JOURNAL,
	NO AFTER JOURNAL,
	CHECKSUM = DEFAULT,
	DEFAULT MERGEBLOCKRATIO,
	MAP = TD_MAP1
(
     snapshot_plan_month_idnt INTEGER 
    ,snapshot_start_day_date DATE
    ,PURCHASE_ORDER_NUMBER VARCHAR(100)
	,RMS_SKU_NUM VARCHAR(20)
	,EPM_SKU_NUM BIGINT
	,STORE_NUM INTEGER
	,WEEK_NUM INTEGER
	,SHIP_LOCATION_ID VARCHAR(10)
	,RMS_CASEPACK_NUM VARCHAR(20)
	,EPM_CASEPACK_NUM BIGINT
	,ORDER_FROM_VENDOR_ID VARCHAR(20)
	,ANTICIPATED_PRICE_TYPE CHAR(1)
	,ORDER_CATEGORY_CODE CHAR(2)
	,PO_TYPE VARCHAR(10)
	,ORDER_TYPE VARCHAR(20)
	,PURCHASE_TYPE VARCHAR(40)
	,STATUS VARCHAR(10)
	,START_SHIP_DATE DATE
	,END_SHIP_DATE DATE
	,OTB_EOW_DATE DATE
	,FIRST_APPROVAL_DATE DATE
	,LATEST_APPROVAL_DATE DATE
	,FIRST_APPROVAL_EVENT_TMSTP_PACIFIC TIMESTAMP (6) WITH TIME ZONE
	,LATEST_APPROVAL_EVENT_TMSTP_PACIFIC TIMESTAMP (6) WITH TIME ZONE
	,ANTICIPATED_RETAIL_AMT DECIMAL(38,9)
	,TOTAL_EXPENSES_PER_UNIT_CURRENCY CHAR(3)
	,QUANTITY_ORDERED INTEGER
	,QUANTITY_CANCELED INTEGER
	,QUANTITY_RECEIVED INTEGER
	,QUANTITY_OPEN INTEGER
	,UNIT_COST_AMT DECIMAL(38,9)
	,TOTAL_EXPENSES_PER_UNIT_AMT DECIMAL(38,9)
	,TOTAL_DUTY_PER_UNIT_AMT DECIMAL(38,9)
	,UNIT_ESTIMATED_LANDING_COST DECIMAL(38,9)
	,TOTAL_ESTIMATED_LANDING_COST DECIMAL(38,9)
	,TOTAL_ANTICIPATED_RETAIL_AMT DECIMAL(38,9)
	,DW_BATCH_DATE DATE
	,DW_SYS_LOAD_TMSTP TIMESTAMP(6) WITH TIME ZONE
    ,rcd_update_timestamp TIMESTAMP(6) WITH TIME ZONE
)
PRIMARY INDEX(snapshot_plan_month_idnt, week_num,RMS_SKU_NUM, STORE_NUM)
PARTITION BY RANGE_N(snapshot_start_day_date BETWEEN DATE '2011-01-01' AND DATE '2031-12-31' EACH INTERVAL '1' DAY , NO RANGE)
;

Grant SELECT ON {environment_schema}.merch_on_order_hist_plans{env_suffix} TO PUBLIC;