/*
Purpose:        APT query used in Selection Planning validation Tableau dashboard
Author(s):      Christine Buckler
*/


SELECT 
	CHANNEL_NUM,
	CASE WHEN CHANNEL_NUM IN (110, 120, 310) THEN 'NORDSTROM'
		WHEN CHANNEL_NUM IN (210, 220, 250, 260) THEN 'NORDSTROM_RACK'
		END AS CHANNEL_BRAND,
	CLUSTER_IDNT,
	MONTH_NUM,
	DEPARTMENT_NUM,
	CATEGORY,
	SUM(GROSS_SALES_TOT_RETL) AS GROSS_SALES_TOT_RETL,
	SUM(GROSS_SALES_TOT_COST) AS GROSS_SALES_TOT_COST,
	SUM(GROSS_SALES_TOT_UNITS) AS GROSS_SALES_TOT_UNITS,
	SUM(GROSS_SALES_TOT_REGULAR_UNITS) AS GROSS_SALES_TOT_REGULAR_UNITS,
	SUM(NET_SALES_TOT_RETL) AS NET_SALES_TOT_RETL,
	SUM(NET_SALES_TOT_COST) AS NET_SALES_TOT_COST,
	SUM(NET_SALES_TOT_UNITS) AS NET_SALES_TOT_UNITS,
	SUM(NET_SALES_TOT_REGULAR_RETL) AS NET_SALES_REG_RETL,
	SUM(NET_SALES_TOT_REGULAR_COST) AS NET_SALES_REG_COST,
	SUM(NET_SALES_TOT_REGULAR_UNITS) AS NET_SALES_REG_UNITS,
	SUM(NET_SALES_TOT_PROMO_RETL) AS NET_SALES_PRO_RETL,
	SUM(NET_SALES_TOT_PROMO_COST) AS NET_SALES_PRO_COST,
	SUM(NET_SALES_TOT_PROMO_UNITS) AS NET_SALES_PRO_UNITS,
	SUM(NET_SALES_TOT_CLEARANCE_RETL) AS NET_SALES_CLR_RETL,
	SUM(NET_SALES_TOT_CLEARANCE_COST) AS NET_SALES_CLR_COST,
	SUM(NET_SALES_TOT_CLEARANCE_UNITS) AS NET_SALES_CLR_UNITS,
	(SUM(NET_SALES_TOT_REGULAR_RETL) - SUM(NET_SALES_TOT_REGULAR_COST)) AS NET_SALES_REG_PM,
	(SUM(NET_SALES_TOT_PROMO_RETL) - SUM(NET_SALES_TOT_PROMO_COST)) AS NET_SALES_PRO_PM,
	(SUM(NET_SALES_TOT_CLEARANCE_RETL) - SUM(NET_SALES_TOT_CLEARANCE_COST)) AS NET_SALES_CLR_PM,
	SUM(RETURNS_TOT_RETL) AS RETURNS_TOT_RETL,
	SUM(RETURNS_TOT_COST) AS RETURNS_TOT_COST,
	SUM(RETURNS_TOT_UNITS) AS RETURNS_TOT_UNITS,
	SUM(DEMAND_TOT_AMT) AS DEMAND_TOT_AMT, -- demand retail
	SUM(DEMAND_REGULAR_AMT) AS DEMAND_REGULAR_AMT,
	SUM(DEMAND_TOT_QTY) AS DEMAND_TOT_QTY,  -- demand units
	SUM(DEMAND_REGULAR_QTY) AS DEMAND_REGULAR_QTY,
	CASE
		WHEN CLUSTER_IDNT IN (
			'PRICE',
			'HYBRID',
			'BRAND',
			'US RACK RS',
			'FLS',
			'US NORD RS'
		) THEN SUM(GROSS_SALES_TOT_RETL)
		ELSE SUM(DEMAND_TOT_AMT)
		END AS "CALC DEMAND_TOT_AMT",
	CASE
		WHEN CLUSTER_IDNT IN (
			'PRICE',
			'HYBRID',
			'BRAND',
			'US RACK RS',
			'FLS',
			'US NORD RS'
		) THEN SUM(GROSS_SALES_TOT_UNITS)
		ELSE SUM(DEMAND_TOT_QTY)
		END AS "CALC DEMAND_TOT_QTY",
	CASE
		WHEN CLUSTER_IDNT IN (
			'PRICE',
			'HYBRID',
			'BRAND',
			'US RACK RS',
			'FLS',
			'US NORD RS'
		) THEN SUM(GROSS_SALES_TOT_REGULAR_UNITS)
		ELSE SUM(DEMAND_REGULAR_QTY)
		END AS "CALC DEMAND_REGULAR_QTY",
	(SUM(RECEIPTS_REGULAR_RETAIL) + SUM(RECEIPTS_CROSSDOCK_REGULAR_RETAIL) + SUM(RECEIPTS_CLEARANCE_RETAIL) + SUM(RECEIPTS_CROSSDOCK_CLEARANCE_RETAIL)) AS RECEIPTS_TOT_RETAIL, -- receipts units
	(SUM(RECEIPTS_REGULAR_COST) + SUM(RECEIPTS_CROSSDOCK_REGULAR_COST) + SUM(RECEIPTS_CLEARANCE_COST) + SUM(RECEIPTS_CROSSDOCK_CLEARANCE_COST)) AS RECEIPTS_TOT_COST,
	(SUM(RECEIPTS_REGULAR_UNITS) + SUM(RECEIPTS_CROSSDOCK_REGULAR_UNITS) + SUM(RECEIPTS_CLEARANCE_UNITS) + SUM(RECEIPTS_CROSSDOCK_CLEARANCE_UNITS)) AS RECEIPTS_TOT_UNITS,
	(SUM(RECEIPTS_REGULAR_RETAIL) + SUM(RECEIPTS_CROSSDOCK_REGULAR_RETAIL)) AS RECEIPTS_REGULAR_RETAIL,
	(SUM(RECEIPTS_REGULAR_UNITS) + SUM(RECEIPTS_CROSSDOCK_REGULAR_UNITS)) AS RECEIPTS_REGULAR_UNITS,
	(SUM(RECEIPTS_REGULAR_COST) + SUM(RECEIPTS_CROSSDOCK_REGULAR_COST)) AS RECEIPTS_REGULAR_COST,
	(SUM(RECEIPTS_CLEARANCE_RETAIL) + SUM(RECEIPTS_CROSSDOCK_CLEARANCE_RETAIL)) AS RECEIPTS_CLEARANCE_RETAIL,
	(SUM(RECEIPTS_CLEARANCE_UNITS) + SUM(RECEIPTS_CROSSDOCK_CLEARANCE_UNITS)) AS RECEIPTS_CLEARANCE_UNITS,
	(SUM(RECEIPTS_CLEARANCE_COST) + SUM(RECEIPTS_CROSSDOCK_CLEARANCE_COST)) AS RECEIPTS_CLEARANCE_COST,
	SUM(EOH_REGULAR_UNITS) AS EOH_REGULAR_UNITS,
	SUM(EOH_REGULAR_COST) AS EOH_REGULAR_COST,
	SUM(EOH_REGULAR_RETAIL) AS EOH_REGULAR_RETAIL,
	SUM(EOH_CLEARANCE_UNITS) AS EOH_CLEARANCE_UNITS,
	SUM(EOH_CLEARANCE_COST) AS EOH_CLEARANCE_COST,
	SUM(EOH_CLEARANCE_RETAIL) AS EOH_CLEARANCE_RETAIL,
	SUM(BOH_REGULAR_UNITS) AS BOH_REGULAR_UNITS,
	SUM(BOH_REGULAR_COST) AS BOH_REGULAR_COST,
	SUM(BOH_REGULAR_RETAIL) AS BOH_REGULAR_RETAIL,
	SUM(BOH_CLEARANCE_UNITS) AS BOH_CLEARANCE_UNITS,
	SUM(BOH_CLEARANCE_COST) AS BOH_CLEARANCE_COST,
	SUM(BOH_CLEARANCE_RETAIL) AS BOH_CLEARANCE_RETAIL,
	(SUM(EOH_REGULAR_UNITS + EOH_CLEARANCE_UNITS + BOH_REGULAR_UNITS + BOH_CLEARANCE_UNITS) / 2) "Avg Inv U",
	(SUM(EOH_REGULAR_COST + EOH_CLEARANCE_COST + BOH_REGULAR_COST + BOH_CLEARANCE_COST) / 2) "Avg Inv C",
	SUM(RACKING_TRANSFER_OUT_COST) AS RACKING_TRANSFER_OUT_COST,
	SUM(RACKING_TRANSFER_OUT_RETAIL) AS RACKING_TRANSFER_OUT_RETAIL,
	SUM(RACKING_TRANSFER_OUT_UNITS) AS RACKING_TRANSFER_OUT_UNITS,
	SUM(RESERVESTOCK_TRANSFER_IN_COST) AS RESERVESTOCK_TRANSFER_IN_COST,
	SUM(RESERVESTOCK_TRANSFER_IN_RETAIL) AS RESERVESTOCK_TRANSFER_IN_RETAIL,
	SUM(RESERVESTOCK_TRANSFER_IN_UNITS) AS RESERVESTOCK_TRANSFER_IN_UNITS,
	SUM(RESERVESTOCK_TRANSFER_OUT_COST) AS RESERVESTOCK_TRANSFER_OUT_COST,
	SUM(RESERVESTOCK_TRANSFER_OUT_RETAIL) AS RESERVESTOCK_TRANSFER_OUT_RETAIL,
	SUM(RESERVESTOCK_TRANSFER_OUT_UNITS) AS RESERVESTOCK_TRANSFER_OUT_UNITS,
	SUM(MOS_TOTAL_COST) AS MOS_TOTAL_COST,
	SUM(MOS_TOTAL_UNITS) AS MOS_TOTAL_UNITS,
	SUM(MOS_TOTAL_RETAIL) AS MOS_TOTAL_RETAIL,
	SUM(RTV_TOTAL_COST) AS RTV_TOTAL_COST,
	SUM(RTV_TOTAL_UNITS) AS RTV_TOTAL_UNITS,
	SUM(RTV_TOTAL_RETAIL) AS RTV_TOTAL_RETAIL
FROM T2DL_DAS_APT.NORD_CATEGORY_HIST
WHERE COUNTRY = 'US'
	AND CHANNEL_NUM IN (120, 250, 260, 310) -- only online channels
GROUP BY 1,2,3,4,5,6